### ISSUE TITLE
Function tag

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#1]
Would adding a function tag be useful?  Such as @fun{rotate} would access a sort of simplified version of the documentation and bring up something like: rotate: Number Image -> Image. Rotates an Image counterclockwise the specified Number of degrees.
This could then generate a little function cheat sheet for each lesson.

**Comment by schanzer** [comment]
I've decided to close this for a few reasons:

1. This would definitely come in handy if these lesson plans are intended to be directly used by students, but that's not (yet) our design goal and there is a LOT of other work that would need to happen to get us there.
2. If it's primarily used by teachers, I don't think it's such a harm to have them look at the contracts in the workbook solutions. If anything, it reinforces the pedagogy we want _them_ to adopt.
3. The engineering required to implement this is very significant, and I think we have more urgent needs for Dorai's wizardry.

I hope that's ok! If you feel really strongly about this and want to make a case for it, I'm comfortable re-opening.
