### ISSUE TITLE
Layout{LaunchC} causes {width="..."} not to be recognized 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1000]
We had to switch slides 3 and 4 in function-notation from the launchC layout to launch layout in order to make images visible.

**Comment by flannery-denny** [comment]
@schanzer It seems that this might not always have been the case? When I build slides for `functions-can-be-linear` the images come up very tiny. 

But on the web the images are big... 

When I look at `slides.md` they're `Layout{LaunchC}`. 

I'm going to assume that you can make the fix at a higher level than me switching every `Layout{LaunchC}` slide with images that doesn't build correctly to `Layout{Launch}`.

**Comment by schanzer** [comment]
This is definitely a regression. I won't be able to look into it until later tonight, but it will be fixed.

**Comment by schanzer** [comment]
@flannery-denny wait, it's not a regression at all! ANY layout with a fixed image size automatically ignores the `width` attribute. This is the correct behavior.

If you want custom sizes, don't use a fixed template.
