### ISSUE TITLE
WeScheme version of lessons is not discoverable from the main Algebra landing page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1001]
And, once you click on "also available in wescheme" the message at the top of the lesson says "also available in wescheme, codap"

see `https://bootstrapworld.org/materials/fall2022/en-us/lessons/computing-needs-all-voices-wescheme/index.shtml`

**Comment by schanzer** [comment]
@flannery-denny ping?

**Comment by ds26gte** [comment]
I just pushed a fix for the narratives of `algebra-wescheme` and `algebra-pyret` to refer to each other.

The `proglang.txt` for the lesson `computing-needs-all-voices` currently includes `pyret`, `wescheme`, and `codap`. Perhaps it shouldn't include `codap`?

**Comment by schanzer** [comment]
@ds26gte CODAP is appropriate, since this lesson will show up in the data-science-codap pathway.
