### ISSUE TITLE
lessons missing from algebra wescheme pathway

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1002]
- [ ] Simple Data Types
- [ ] Solving Word Problems with the Design Recipe

**Comment by ds26gte** [comment]
Hmm. Building locally does pull in those lessons in algebra-wescheme. The ones on the website may be from an old build?

**Comment by schanzer** [comment]
Nope - did a fresh build this morning. I'm a little disturbed that those lessons didn't make it to the server, but I'm rebuilding now and will re-upload ASAP

**Comment by schanzer** [comment]
Pushed to the web - these lessons are now available. See `https://bootstrapworld.org/materials/fall2022/en-us/lessons/contracts-wescheme/index.shtml?pathway=algebra-wescheme`
