### ISSUE TITLE
algebra-wescheme issues

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1003]
- [x] lesson list is missing from sidebar (only showing prereqs)
- [x] link formatting is off

![Screen Shot 2022-06-27 at 11 50 19 AM](https://user-images.githubusercontent.com/66691020/175994146-ee0160af-3d93-426f-8c79-c059400b3db5.png)

**Comment by schanzer** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/77126/176048171-85b94634-a7dc-47ef-bb7a-102eb9945253.png">

These are now resolved after a fresh build-and-push
