### ISSUE TITLE
live on the web - data cycle worksheet is missing icons

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1007]
[https://bootstrapworld.org/materials/fall2022/en-us/lessons/data-cycle/pages/analyzing-with-displays.html](https://bootstrapworld.org/materials/fall2022/en-us/lessons/data-cycle/pages/analyzing-with-displays.html)
![Screen Shot 2022-06-28 at 8 03 47 AM](https://user-images.githubusercontent.com/66691020/176185397-96fda8c1-b084-4ee3-bf7c-5e804098cc8b.png)

**Comment by schanzer** [comment]
@ds26gte compare the `data-cycle` and `histograms2` lessons.

- Both have pages that use the data cycle template
- Both have the proper image files in the `images` folder

And yet the image filenames are anonymized for histograms2, but not for data-cycle. Why?

**Comment by schanzer** [comment]
fixed by https://github.com/bootstrapworld/curriculum/commit/36ec5de1ad202641e82b1f63b6ef9396faa721c6
