### ISSUE TITLE
Displaying Categorical Data Slides should be replaced by Bar & Pie Charts slides in fall2022 and in PD materials

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1008]
Not sure whether the deck just has the wrong title or the issue is bigger.
The title in the slides.md file is definitely wrong. I'm not remembering what else changed about this lesson that I could verify is correct.

**Comment by schanzer** [comment]
Fixed the slides.md file, the slide deck for the lesson, as well as the PD deck.

This is _definitely_ an argument for why it's worth exploring whether the slide and lesson plan files can be merged.
