### ISSUE TITLE
exercises and solutions not appearing on teacher resource pages - live on web

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1011]
https://bootstrapworld.org/materials/fall2022/en-us/courses/data-science/resources/index.shtml
https://bootstrapworld.org/materials/fall2022/en-us/courses/algebra-pyret/resources/index.shtml

![image](https://user-images.githubusercontent.com/87144723/176466165-4947a61c-566a-4e80-a6a1-2ca47bb7063a.png)

**Comment by schanzer** [comment]
I have literally no idea how this is possible. @ds26gte any ideas why a directive would die silently?
