### ISSUE TITLE
What should @fitbruby's first argument (length) default to?

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#1012]
Currently `@fitbruby`'s first argument should be a width, something like `15ex` or `100%`.  Leaving it empty causes problems. 

Arguably, I should substitute a valid default length when the argument isn't supplied, but what should it be?  Is `100%` ok?

**Comment by ds26gte** [comment]
An option is to estimate the length of the 2nd and 3rd arguments (this will be a shrewd guess at best), take their max, and use that as the width.

Since I found the argument left empty by only one author, maybe it just needs practice to remember to always insert a valid width.

**Comment by flannery-denny** [comment]
@ds26gte @schanzer wondering if it would be better to give feedback to authors that we need to give it a width when we forget, rather than to create a default width?

**Comment by schanzer** [comment]
@ds26gte let's start with Flannery's suggestion. Ideally I'd like to see the default behavior be the same as `@fitb`, and just stretch to infinity. Unfortunately that's not possible with the way the ruby is positioned.

**Comment by retabak** [comment]
The "one author" is me. Woops.

In case I repeat the mistake, I like the idea of getting feedback to add a length!
