### ISSUE TITLE
Fixes from pyret opt-printable exercises

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1016]
- [x] tree diagrams 2 - use @fitb for 2 and 4. provide more @vspsace for 1.
- [x] word problem: species-dot... are we intentionally giving them the fully completed DR? - _ES - yes_
- [x] DR Telephone Set 1: is-dog - this DR should definitely be blank but is mostly completed
- [x] DR Telephone Set 1: days-to-adopt - this DR should definitely be blank but is mostly completed
- [x] DR Telephone Set 2: kilos - this DR should definitely be blank but is showing the contract and purpose statement
- [x] DR Telephone Set 2: is-cat - this DR should definitely be blank but is mostly completed
- [x] line-length - do we mean to give away 2 examples? (I think probably so?) - _ES - yes_
- [x] DR (Marquee) needs a better title for the page - it has 2 functions - the second is num-cube
- [x] age v height explore - add @vspace before 5 and 6 and before the word Rebuild in 4
- [x] Quick guide to saving images to google drive - seems like we're missing a step (or several) here. _**RT: looks as though only one of two of the pages of this PDF is ending up in the opt-printable exercises printout? I see a two-page handout [here](https://bootstrapworld.org/materials/fall2022/en-us/lessons/making-game-images/pages/SavingImagesGuide.pdf).**_ - _ES - combined workbook pages can NEVER go for more than one full page. The only solution here is to split the source PDF into two separate one-pagers. Since almost no one will ever use this as part of a real, printed workbook, I say we punt._
- [x] `creating circles of evaluation from arithmetic expressions` and  `creating circles of evaluation from arithmetic expressions 2` have the same first problem
- [ ] `converting circles of evaluation to arithmetic expressions` and `evaluating circles of evaluation` have 2 of the same problems (1 and 3 on first page are 1 and 4 on second)
- [x] `word problem: mood generator` Did we mean to give away examples? - _ES - yes_

**Comment by retabak** [comment]
I wanted to fix all these DR Telephone things that @flannery-denny mentioned but got real confused in the process.

I'm not at all seeing what Flannery is seeing here. Specifically, the DR Telephone sets don't involve animals at all. I do not see is-dog, days-to-adopt, kilos, or is-cat. I see g, h, r!  I'm also not seeing that any of the telephone sets are completed (although symmetry and right-trapezoid provide some weird additional stuff at the bottom of the DR page). WIsh I could fix this stuff but I'm afraid I'm not certain what's going on.
