### ISSUE TITLE
live on web - materials landing page not appearing

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1018]
Got here by clicking "materials" then "build your own" from our homepage.

https://bootstrapworld.org/materials/#BuildYourOwn

![image](https://user-images.githubusercontent.com/87144723/176581331-efdd9f01-166c-440d-87f1-b33cd7653abb.png)

**Comment by retabak** [comment]
I'm still seeing the same thing. Not sure what's up.

**Comment by schanzer** [comment]
@retabak can you try now?

**Comment by retabak** [comment]
Still the same, even with shift + refresh. 

Weird!

**Comment by schanzer** [comment]
That's odd - it's working for me on three different browsers, including my phone! @flannery-denny can you try?

**Comment by schanzer** [comment]
@retabak wait hold on -- don't click the URL. Click the _actual button_ on the website.

**Comment by schanzer** [comment]
@retabak if you're happy and you know it close the issue? *clap clap*

**Comment by retabak** [comment]
lol
