### ISSUE TITLE
consider updating animation at bottom of home page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1020]
we have a map that says we are in 49 states and 50 countries... and then one of the slides that goes by says we were in 26 states in 2016.... makes me think probably most of that data is outdated... but that, at least, we should cut the slide that is definitely in conflict with map above it.

also confused as to why I've seen two different quotes at the bottom but I don't seem to be able to navigate between them.

and, finally, this sentence would read better with the word several replacing numerous

> Bootstrap collaborates with faculty at numerous of the leading universities in computer science, including Brown University, Northeastern University, and the University of California at San Diego, as well as other institutions.

**Comment by schanzer** [comment]
@flannery-denny good call - I've updated those images and replaced "numerous" with "several". The quotes are randomly chosen from a list every time you refresh the page.
