### ISSUE TITLE
Spurious build warnings for exercise pages

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1021]
Right now we get a lot of warnings about various pages that are "not an exercise". All of these warnings seem to deal with pages that are referenced in `workbook-pages.txt` AND in the lesson plan, but using `@opt-printable-exercise` rather than `@printable-exercise`.

If a workbook page is referenced from the lesson plan by _either_ directive, we do not need a warning.

**Comment by ds26gte** [comment]
Are these using `@link` rather than `@[opt-]printable-exercise`.  I could beef up `@link`, but it's really meant for general-purpose URLs

**Comment by schanzer** [comment]
@ds26gte no.

**Comment by schanzer** [comment]
@ds26gte I've "fixed" most of the remaining (real) warnings on `fix-1021`, but they persist! Can you investigate?

**Comment by ds26gte** [comment]
The directive `@opt-printable-exercise` is typo'd as `@opt-printable-exercises` (plural s) in the lesson plans for `linear-regression`, `grouped-samples`, and `defining-table-functions`

**Comment by schanzer** [comment]
@ds26gte fixed. Still getting what feels like an erroneous warning for `random-samples/pages/sampling-and-inference.adoc`. Is that because the adoc is actually behind a proglang directory?

**Comment by schanzer** [comment]
Confirming this is now fixed
