### ISSUE TITLE
Feedback on collapsing headers branch

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1025]
I am only seeing collapsing headers on the teacher resources pages: 

Data Science, which looks like this:
![Screen Shot 2022-07-01 at 8 52 16 AM](https://user-images.githubusercontent.com/66691020/176908114-806a1b72-1d4a-4ef2-b9be-c04cb53508d7.png)

is quite different from algebra, which looks like this:

I'm not sure which I like better, probably algebra?
![Screen Shot 2022-07-01 at 9 07 43 AM](https://user-images.githubusercontent.com/66691020/176910987-cd28f62a-ba30-4f15-9a54-8a3a3f5fddf1.png)

- DS is missing notes
- If I were going to limit what teachers see at first glance, I would proponent rethinking the headers a little. For DS...

> - How about bringing projects to the front?
> - How about highlighting the research paper as separate from the starter files.
> - I'd probably put resources that pair well with Bootstrap DS at the end of the list.
> - Decide whether to use DS in all of the header titles or none  except "resources that pair well with Bootstrap DS."

-  Did you mean to also use collapsing headers in lesson plans?

**Comment by schanzer** [comment]
@flannery-denny good call. I've implemented some of these suggestions, but it's not ready for review until Dorai addresses some stuff.

@ds26gte the `@all-lesson-notes` directive dumps in a LOT of extra stuff that has nothing to do with the lesson notes. Can you fix this?

- [ ] "Click here to return to lessons" can be safely removed
- [ ] The projects should be an entirely separate directive
- [ ] The teacher's edition link should be generated as part of the `exercises and solutions` directive. Probably better to rename it as "workbook solutions" anyway!

**Comment by ds26gte** [comment]
(recycled from Slack):   The teacher resources pages autoinserts a bunch of stuff just after the first header. If the header for `@all-lesson-notes` happens to be the first header, then it will get these autoinsertions, leading one to infer that they were dumped by `@all-lesson-notes`.  Solution is to make sure that `== All Lesson Notes` isn't the first header.

**Comment by schanzer** [comment]
@retabak take a look when you have a moment? Dorai did some revision on a lot of the directives, and it's looking a lot better.

**Comment by retabak** [comment]
First, I *really* like the idea of these collapsing headers!

I'm only seeing them working on the teacher resource page, however. They work great there! My one suggestion would be that we put the top section in a header too - maybe called "Essentials" - or something. It feels a little odd that it's just at the top and everything else goes under a header. 

On lesson pages, I can put my mouse on a section heading and it turns green. A little "+" sign also shows up - but clicking the "+" doesn't cause anything to happen.

**Comment by retabak** [comment]
Lol, just noticing that Flannery gave the opposite feedback as I did re: putting the top section under a collapsing header. I still think it looks nice and more uniform with everything formatted the same, but I can let it go.

**Comment by schanzer** [comment]
@retabak would you like to see this used in lesson plans as well? I switched off the behavior (though obviously not the CSS rules!) to make sure we could just test it out on TR.

I like it on the lesson plans, too, and I believe Flannery did as well.

**Comment by retabak** [comment]
yep! I am into the idea of it in lesson plans. Would want to see it and check it out to make sure, of course. :)

**Comment by schanzer** [comment]
@retabak try now! 

(Also, I notice some changes you pushed to this branch. Are they specific to the collapsing-headers feature? If so, that's great. If not, these should really have gone in `master`. It's no big deal, since we'll likely merge this branch into `master` soon, but something to keep in mind for future reference)

**Comment by retabak** [comment]
Woops, wrong branch! Sorry.

**Comment by retabak** [comment]
Wow! This looks SO good! I think it's a huge improvement to the look / feel of our lessons. I'm not finding any issues or problems with its functionality either.

One idea I'm wondering about: is there anyway that the lesson overview could also show _before_ you click to expand the collapsed header? If this is something that could happen easily, I'd be curious to see it. If not, I don't think it's a big deal. My thinking here is it might be nice for folks to glimpse the overview so they don't need to click open the all the headers to get a sense of what a section is about.

**Comment by schanzer** [comment]
@retabak I looked into keeping the overview for each section visible, and unfortunately it's not possible based on the CSS trick we're using. Finding a new solution is going to be HARD, and may not even be possible. If you're ok with merging this as-is, let me know and we can close the issue. Otherwise, this will have to wait until Sept at the earliest.

**Comment by retabak** [comment]
I'm happy as-is!
