### ISSUE TITLE
Figure out how to include lessons in our repository that are not proglang specific - SS lessons will not use codap or pyret or wescheme!

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1027]
In order to be able to start asciidocifying the SS materials, I will need a way to build a lesson without specifying a language. This issue may or may not connect to #906

**Comment by schanzer** [comment]
@flannery-denny Computing needs all voices doesn't use a proglang either, and it's never been an issue. Why is it a problem for these lessons?

**Comment by flannery-denny** [comment]
@schanzer computing needs all voices is listed as being trilingual… pyret and wescheme and codap

Flannery

**Comment by schanzer** [comment]
But that doesn't answer the question.

Any problem the SS lessons will have is also a problem with CNAV. What's wrong with the computing needs all voices lesson? It doesn't use ANY proglang, and it still works in any pathway we want it to. The same will be true with SS.

**Comment by flannery-denny** [comment]
Currently, lessons won’t build unless we list the langs they should build in.

Are you suggesting that we pretend it’s written in pyret in order to build it? I anticipate that might lead to some mistake down the line.

I would prefer that an alternate proglang were named for this pathway instead… perhaps “none”?

But if it works best for you and @ds26gte to have these pages listed ad pyret, that would also answer how you want me to proceed.

Flannery

**Comment by schanzer** [comment]
We can either list them as Pyret, or make up a new "language" (I propose "spreadsheets").

Either way, I think we can safely close this issue.
