### ISSUE TITLE
Confirm the LR Deck is using correct image for slide 6

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1030]
It's talking about a line, but I'm not seeing a line... not sure, because we haven't taught them about a line yet. Maybe no image?
[https://docs.google.com/presentation/d/1khuMUKtj7eAO6b7K8scConeQMs37ql5i1fqDZ5Bsi-A/edit?usp=sharing](https://docs.google.com/presentation/d/1khuMUKtj7eAO6b7K8scConeQMs37ql5i1fqDZ5Bsi-A/edit?usp=sharing)

**Comment by schanzer** [comment]
Updated lesson slide and PD slide to match
