### ISSUE TITLE
live on web - broken links to rubrics from project pages

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1034]
ALGEBRA: 
Project page: https://bootstrapworld.org/materials/fall2022/en-us/lessons/project-video-game/index.shtml
Broken link to rubric: https://bootstrapworld.org/materials/fall2022/en-us/lessons/project-video-game/video-game-rubric.html

DS: 
Project page: https://bootstrapworld.org/materials/fall2022/en-us/lessons/project-research-paper/index.shtml
Broken link to rubric: https://bootstrapworld.org/materials/fall2022/en-us/lessons/project-research-paper/research-paper-rubric.html

Also, we say we'll provide a rubric for the exploration, but we do not. This statement - "You can find the description of this project (and the grading rubric!) at [the Exploration Project Page](https://bootstrapworld.org/materials/fall2022/en-us/lessons/project-exploration-paper/index.shtml)" - is a lie.

**Comment by schanzer** [comment]
@retabak feel free to fix broken links in the asciidoc if you find them.
