### ISSUE TITLE
proposal - add introductory slide to all decks that explains various icons 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1035]
am looking at youcubed slides for a school project and am seeing this introductory slide in the slide decks:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/87144723/177590789-6a8c1587-c5fa-4065-8c4d-d9cc9d85b388.png">

I envision that ours would include:
- launch
- investigate
- synthesize
- driver/navigator
- role play (?) - we've discussed adding this 
- notice & wonder (?) - we don't have an icon for this but maybe we should?

**Comment by schanzer** [comment]
@retabak GREAT idea. Add this to your "if there's time" list.

**Comment by flannery-denny** [comment]
@retabak There are notice and wonder images in pd decks. Perhaps you'll have time to make them into an icon and save them? Check out slide 18 of this deck. [https://docs.google.com/presentation/d/1nQbPuUE3akyIn0yLKRcTBNAlXxodj8VJXlDTG07BpKw/edit?usp=sharing](https://docs.google.com/presentation/d/1nQbPuUE3akyIn0yLKRcTBNAlXxodj8VJXlDTG07BpKw/edit?usp=sharing)

**Comment by retabak** [comment]
Here's a crack at an introductory slide: https://docs.google.com/presentation/d/1bTIQd390Oud9e8xQSSk41lGp65a5VgY1g77g_tWEWrU/edit?usp=sharing

I considered adding text to explain what each of these different things entail, but decided it would look too cluttered. I think we can perhaps add a bit of explanation as an author's note.

(@schanzer - we would just add this to the slide deck template and incorporate it via slides.md whenever we do another big materials release, right? DEFINITELY doesn't seem worth the trouble to add it manually.)

**Comment by schanzer** [comment]
@retabak I made some small changes, and modified the title to something pithy. Feel free to undo if you don't like it. :)

This is WAY too complex for markdown, however. Here's my suggested compromise: we make this a slide template in the master deck, so that it can be included in markdown with an empty slide using `{layout="roadmap"}` or something.

Alternatively -- do you think EVERY deck needs this?

**Comment by retabak** [comment]
I agree with adding it into the slide template - that's what I was thinking we'd do!

I'm not sure if every slide deck needs it but I'm not sure how we would decide where to include it, otherwise? What do you think? Or maybe @flannery-denny has an opinion?

**Comment by flannery-denny** [comment]
works for me.

**Comment by schanzer** [comment]
@retabak I've added this layout to https://docs.google.com/presentation/d/1vFGtTzhTlc1p8VJECRucj5DO83skm4wMI1BU3QbHE5k/edit

Close if you're satisfied

**Comment by schanzer** [comment]
@flannery-denny the template has always been blank. View master slides

**Comment by retabak** [comment]
@flannery-denny - if you're interested in viewing, click on "Slide" and then "Edit Theme"
