### ISSUE TITLE
issues in "problem solving together"

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1037]
- [x] the collaboration starter file refers to functions g, j, and r - but the lessons uses g, h, and r. I would fix but wasn't certain the solution was as simple as replacing each j with h.
- [x] the hyperlink highlighted in the image below doesn't work. (Not sure of our protocol for hyperlinking to another lesson of ours - do we have one? - or I'd fix it.)
- [x] some DRs (r, symmetry, and right-trapezoid) have some answers revealed at the bottom of the page

![image](https://user-images.githubusercontent.com/87144723/177670495-02bf784d-395f-4d29-ad85-524f0e1f4db4.png)

**Comment by schanzer** [comment]
@flannery-denny The collaboration starter file is owned by you, so if I make a change and publish will require a new link. Do you make making this changes ASAP when you return?

**Comment by schanzer** [comment]
@retabak sure, feel free to move them to the top.

**Comment by schanzer** [comment]
@retabak I took care of it. This issue is waiting on @flannery-denny to make the starter file change.
