### ISSUE TITLE
write pedagogy box for DR Telephone

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1038]
Why do we have the same instruction twice in the same pathway?

This feels very confusing.  Like it must be a mistake. My knee-jerk reaction is, "Wait, what? I already did this. Why is it here again?" 

I see that the worksheets offered are different, but there is no context or explanation as to why the same activity is showing up AGAIN. 

I think this activity is *begging* for a pedagogy call-out box (which unfortunately I do not feel qualified to write) to accompany its very first appearance. Then, when the activity appears for the 2nd time, we could say, "To learn more about how to facilitate DR Telephone - and why we love it! - refer to our lesson on Defining Table Functions, where we first introduce this highly effective practice and collaborative structure." Or something along those lines.

**Comment by schanzer** [comment]
@retabak you're absolutely right! Want to take a crack at writing that pedagogy box?

**Comment by retabak** [comment]
No -- because I've never facilitated or seen this activity facilitated
before :(
I'd have a hard time doing this authentically. (...but I fully trust you
that it's worth it!!)

I can remove "problem solving together" from the data-science pathway
though :)

**Comment by flannery-denny** [comment]
@schanzer I'm not sure where this issue stands... 
- looks like problem solving together has been removed from the DS pathway and we need a pedagogy box about DR telephone in the defining table functions lesson?
- happy to write the pedagogy box if I'm understanding that correctly.

**Comment by retabak** [comment]
@flannery-denny yay! Welcome!

The pedagogy box would need to appear twice - in "defining table functions" *and* in "problem solving together" - because those are the two instance where DR telephone appears.

**Comment by flannery-denny** [comment]
great work @retabak. I unsuccessfully tried to convince @schanzer to remove problem solving together from the DS pathway ;) 

I just dug into the lesson plans and have pushed some improvement, but I don't understand why you still think there should be a pedagogy box. The directions are clear to me. Have another look and if you still think they belong, let's schedule a time to talk.

**Comment by retabak** [comment]
@schanzer - closing this issue after a conversation with @flannery-denny and adding it to our meeting agenda!
