### ISSUE TITLE
can algebra landing page be as concise and tidy as data science landing page?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1040]
DS landing page looks and feels better than the algebra one!

https://bootstrapworld.org/materials/algebra/
https://bootstrapworld.org/materials/data-science/

- [x] DS has "created in partnership with" section; algebra doesn't
- [x] DS - top of video aligns nicely with top of text; in algebra, it doesn't
- [x] DS has bullets, algebra has paragraphs
- [x] Algebra landing page has these paragraphs about pyret versus wescheme that I think are essentially gobbledy-gook to most visitors; if we're not training folks in wescheme anymore, I don't see the purpose of this getting such a prominent position.
- [x] "backed by research" section can also go, I think; we've got a whole page dedicated to that. Why the blurb here?

**Comment by schanzer** [comment]
@retabak we have actual studies showing student gains in math concepts for Bootstrap:Algebra. Data Science doesn't (yet). 

As for WeScheme v. Pyret -- we need SOME way of differentiating the two. If it feels like gobbledegook, how would you simplify it? I asked Flannery for feedback about this a few weeks ago as well, and would love to hear what she has to say.

**Comment by schanzer** [comment]
@retabak try now. *grin*

**Comment by retabak** [comment]
Oooooh! SO MUCH better! The two buttons thing is a clever way to get rid of the gobbledegook. :)

A few little suggestions:

- [ ] fix typo: 2nd bullet - "Let math teachers can build on"
- [ ] fix typo: under Pyret button - "when you a smooth pathway"
- [ ] is the "Attend a Workshop" text needed now that we've got a "Get Trained" button?
- [ ] is the "Backed by Research" text needed now that we link to those articles in the 2nd bullet? (up to you, I get it that this research is a big deal!)

**Comment by schanzer** [comment]
@retabak the first three checkboxes have all been implemented. And yes, we want to show off the math research like CRAZY. :)

**Comment by retabak** [comment]
I'm happy!
