### ISSUE TITLE
is it possible to make [.lesson-instruction] not fill an entire line?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1045]
Putting the do-the-worksheet prompt into a [.lesson-instruction] box (as we've agreed to do) results in some ugly formatting.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/87144723/178543919-4a28410b-e6e4-4740-9429-f3fb6d88b68a.png">

Here's how this segment looked before I added the instruction box:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/87144723/178549243-cd96fa21-162d-497d-8eb9-1f723efc3293.png">

Is there any sort of fix for this, aside from completely rethinking the layout?

**Comment by schanzer** [comment]
There is no fix for this, without dramatically increasingly the complexity of the layout/CSS. And more complexity means more corner-cases later.
