### ISSUE TITLE
can we turn off collapsing headers on worksheets?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1046]
When I open a worksheet, I expect to see a worksheet - not collapsed headers.

Is it possible to turn off collapsing headers on worksheets? 

Screenshot below is from lessons/codap-transformers-2-codap/pages/codap-transform.html

<img width="542" alt="image" src="https://user-images.githubusercontent.com/87144723/178550062-209a21c2-9e81-42be-ac25-c03a42372fdb.png">

**Comment by schanzer** [comment]
fixed!
