### ISSUE TITLE
worksheet hyperlink works for Pyret data-cycle lesson but not for CODAP data-cycle lesson

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1047]
Any idea what's going on here?

This is what appears in CODAP:
![image](https://user-images.githubusercontent.com/87144723/178550700-e89e91aa-d9ab-432a-86f3-24c9847e5f60.png)

And this is what appears in Pyret:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/87144723/178551037-fb532a77-fb74-4730-a5cd-84cdc3ce6824.png">

**Comment by retabak** [comment]
is this resolved?
Can we close?

**Comment by schanzer** [comment]
Yep!
