### ISSUE TITLE
Language Table display isn't quite right

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#105]
The current language tables are inheriting the styling of the outer table when they shouldn't be. Can these tables be given a CSS class or id (since there's only one per lesson), so I can style them appropriately?

**Comment by ds26gte** [comment]
To confirm: This is for the Data Science lessons?  For the sub-table that occurs in the row entited "Pyret features"?

**Comment by ds26gte** [comment]
I've pushed eaf7e2f which introduces a new CSS class `.lang-features-table` for this. I've put some merely stopgap styling for this in `lib/shared.css` but it should be quickly changed to what is required.
