### ISSUE TITLE
Expanding/Collapsing headers behaves inconsistently

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1051]
Take a look at the screenshots below...

Here, 'sorting with transformers' is collapsed:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/87144723/179539591-1e3d0bc2-5a49-4a6d-b063-b8e58868fb42.png">

and it's un-collapsed here:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/87144723/179539660-7118e020-4fd5-4587-b2c7-406be6810b03.png">

I clicked that section, so I wanted to read it and expected it to appear immediately. The only thing that changed when I clicked, however, is that the scroll bar (on the right) jumped up, and the header color changed from purple to green. The section text did not come into view! Can we make it so that a section comes into view immediately (without scrolling) when I click on its header? Or, what is the reason that we've opted for it to be this way? (I'm guessing there's some very logical, rational explanation.)

**Comment by schanzer** [comment]
@retabak the scrolling is not a problem here. I can turn it off, but that won't change what's happening -- the page is getting longer, but without scrolling. Even if it _instantly_ becomes visible, you'll have to manually scroll down to see what happens. 

The only option I could imagine is to maybe auto-scroll the page by a tiny amount, to hint that there's more below. But I find it really jarring when a page scrolls on me.

**Comment by retabak** [comment]
I'd be curious to see the auto-scroll.
Maybe @flannery-denny will want to weigh in when she's back online!

**Comment by flannery-denny** [comment]
@schanzer @retabak I'm happy to weigh in, but am not sure where to find / how to generate the page in question.

**Comment by schanzer** [comment]
@flannery-denny welcome back!!!! 

Building any pathway and opening a lesson plan will show you the issue.

**Comment by flannery-denny** [comment]
I've played around with several lesson plans and am finding the behavior of clicking on the header to expand the hiddent section to be inconsistent. Sometimes when I click for it to expand:

- the header text stays where it was
- the header text jumps to the top of the screen and the hidden content is revealed
- the header text jumps off the top of the screen and the bottom of the hidden content is revealed

**Comment by schanzer** [comment]
@flannery-denny That's quite strange. Can you tell me on which lessons/headers you're seeing this?

**Comment by flannery-denny** [comment]
@schanzer open any lesson and try clicking the headers a bunch of times and they will do different things depending on the moment and perhaps the exact position of your mouse. If you can't duplicate, let's zoom.

**Comment by flannery-denny** [comment]
@retabak @schanzer I am finding the inconsistency of how this feature works in lesson plans to be pretty frustrating. I vote we go back to non-collapsing lesson sections until there's bandwidth to get it working better in a branch that people aren't actively interacting with.

**Comment by schanzer** [comment]
@flannery-denny I still can't reproduce this. What browser are you on? Do you have a few minutes to zoom today, just so I can see what you're seeing?

**Comment by schanzer** [comment]
@flannery-denny and @retabak I've pushed some improvements, based on a quick zoom and chat with Flannery. Let me know what you think?

**Comment by retabak** [comment]
Okay... I'm finding I agree with this statement that you made a few comments back, @schanzer: "I find it really jarring when a page scrolls on me."

It's nice that the section comes into view when I click the header, but... maybe I wasn't done reading the stuff _above_ the header and then suddenly it's gone?! Is there any way to make this all feel a bit more subtle?

If this version is what you both like, @schanzer and @flannery-denny, I can let it go. That said, I think a bit less auto scrolling (what you suggested previously, @schanzer - just a tiny autoscroll to suggest there's more?) might feel better to me.

**Comment by schanzer** [comment]
"A bit less auto scrolling" isn't going to happen. Either we turn the feature off or we close the issue and update the website.

**Comment by schanzer** [comment]
@retabak @flannery-denny ok, I've used the newly-inserted vertical space to minimize scrolling. This is about as good as it's going to get.

**Comment by flannery-denny** [comment]
@schanzer I can live with this. It's much better than it was on Friday.

**Comment by schanzer** [comment]
Website is updated!

**Comment by flannery-denny** [comment]
@retabak I think this resolves your original codap issue? close if so.

**Comment by retabak** [comment]
yep, feels good to me too! Closing.
