### ISSUE TITLE
capitalization should be consistent in defining table functions goals

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1052]
Dorai and I aren't sure why Rows gets capitalized and column does not.
Boolean and Image are only sometimes capitalized...
![Screen Shot 2022-07-19 at 2 12 25 PM](https://user-images.githubusercontent.com/66691020/179830665-ce73050e-52c3-49dd-8939-6776cfc24aeb.png)
.

**Comment by schanzer** [comment]
`Row` and `Boolean` are datatypes, and should always be capitalized. "Column" is not.

**Comment by flannery-denny** [comment]
If I understand correctly,

- [ ] Lesson goals should stay as they are?

- [ ] student-facing Lesson goals should be changed to the following?

- I can define functions that look up values from a Row.
- I can define functions that produce Images from a Row.
- I can define functions that compute a Boolean from a Row.

**Comment by schanzer** [comment]
@flannery-denny perfect

**Comment by flannery-denny** [comment]
@schanzer 

If I understand correctly,

- [ ] Lesson goals should stay as they are?

- [ ] student-facing Lesson goals should be changed to the following?

- I can define functions that look up values from a Row.
- I can define functions that produce Images from a Row.
- I can define functions that compute a Boolean from a Row.
