### ISSUE TITLE
idea - expandable ("see more...") pedagogy boxes?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1054]
If this is impossible, that is TOTALLY okay, just say so! 

I was just poking around in the Flags lesson, and noticed there are heaps of (awesome! amazing!) pedagogy boxes. Some of them, however, are really long - and they're stacked - and they feel a little visually overwhelming. I suspect some folks just want to read the lesson narrative and want to skip these boxes, while others want to learn more about our brilliant, useful pedagogy suggestions.

Would it be possible to show a few sentences of what's in the pedagogy box and have a "see more" button to view the rest of the text - kinda like on facebook / instagram?

**Comment by schanzer** [comment]
@retabak We already have collapsing headers, which means people won't see many pedagogy boxes at any given time.
