### ISSUE TITLE
Plan for SS Glossary words

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1056]
As we had the SS lessons to the repository, I had imagined that we would add the glossary words, but I am noticing that [many of the terms](https://docs.google.com/document/d/1GctJGOpuReW-LfxWDipwrR5QVILBwpBmrdgkuHdKcmI/edit?usp=sharing) overlap with what is already in our repository and the definitions do not align. 

- [ ] Is there a way to have a separate glossary file for this content?
- [x] Our current glossary is bilingual English-Spanish. Not sure whether translating these SS glossary terms into Spanish is a priority.

**Comment by kfisler** [comment]
Spanish translation is not a priority.

I expect there would be slight differences in term definitions. We could check whether those differences are due to grade level, or a meaningful difference wrt content.

**Comment by ds26gte** [comment]
I take it you (@flannery-denny) would like a pathway-specific glossary that shadows the current global glossary. Unfortunately, the `@vocab` entries occur in lessons and lessons are pathway-agnostic nowadays.  Perhaps if we know that a lesson will only occur in specific pathways, we can specify that information in the lesson's directory (like we currently do `proglang.txt`). Then we can have the glossaries associated with those pathways serially shadow the global glossary for that lesson. @schanzer?

**Comment by schanzer** [comment]
@flannery-denny I see a very small number of terms that overlap, and I believe every one of those terms exists in both algebra and data science _now_. And for those, we've already come up with definitions that work for both contexts. (IIRC we may have punted on "variable", but I think that's it)

What other words are you concerned about?

**Comment by flannery-denny** [comment]
@schanzer @kfisler 
Below are 5 examples of terms that overlap from the Shipwreck unit. While I'm sure that definitions from both sources could be improved upon, I'm not entirely convinced that merging them is the right way to go. Particularly since there will be more words as we dig into other units.

> KIPP variable: a characteristic that can be different for different people or things
> BS variable: a letter or symbol that stands in for a value or expression
>     
> KIPP average (mean): the sum of all numbers in a data set, divided by how many there are. The average is a way of telling us what’s typical for a set of numbers.
> BS mean: a representation of the center, or 'typical' value in a set of numbers, calculated as the sum of those numbers divided by the number of values.
> 
> KIPP outlier: a value in a quantitative data set that is unusually low or high compared to the rest of the values
> BS outlier: observations whose values are very different from the other observations in the same data set, perhaps due to experimental error. Outliers can also be indicative of data belonging to a different population from the rest of the established samples.
>    
> KIPP probability: the chance of happening, usually reported as a percentage
> BS doesn't have one, but should!
> 
> KIPP Range: the difference between lowest and highest values in a data set
> BS ("range") "the type or set of outputs that a function produces")
>       ("range of a dataset") "the distance between minimum and maximum values")

From this list, range seems to be the most complicated to reconcile, since we are referring to two different meanings. But maybe the SS term could also be called the Range of a dataset?

Is your preference that we merge the definitions or that I pursue making a separate glossary file with Dorai?
- If you want to merge them, should I make executive decisions or do you want to weigh in?

**Comment by kfisler** [comment]
If "merging" means "come up with a common wording that works for both
curricula", then I'm against merging. "Range" and "variable" have different
meanings in the two contexts, "mean" shows why we might want different
definitions for different grade levels. I highly doubt that we can come up
with common definitions that work for both 5th graders and high school
students.

Kathi

**Comment by flannery-denny** [comment]
@ds26gte Looks like it's time for us to explore your suggestion. We know that the SS lessons I am working on will only show up in their pathway. I'll message you on slack re: setting up a time to discuss.

**Comment by ds26gte** [comment]
Proposed implementation pushed in branch `shipwreck`, commit e81a1511e

**Comment by schanzer** [comment]
@kfisler Range is really the one that's hardest to reconcile. We've already solved most of the others, and punted on "variable" in a way that I'm quite comfortable with.

But if we're not going to merge, we should really do this right. Pathway-specific vocabulary shadowing is the way to go. Keeping these words lesson-specific is going to be a maintenance headache in the long run, and _it doesn't even solve the problem_ when dealing with lessons that show up in multiple pathways!

@ds26gte, this feels like the same problem as page numbers -- they have to be calculated at page-load time using JS. I think we should keep the default, global vocabulary list, and generate static definitions based on this. Then we export the pathway-specific vocab as part of the `pathwayTocs` dictionary, and have javascript overwrite the words depending on the selected pathway.

**Comment by ds26gte** [comment]
Consider a paragraph in some lesson plan. It uses the word `variable`. Are you saying you expect the meaning of the word `variable`, as used in this paragraph, is going to change depending on which pathway this lesson is included in? That would have to be one extraordinarily poststructuralist paragraph!

Having a lesson specify a shadowing glossary is simple and static. And I've pushed an implementation (see above).

**Comment by schanzer** [comment]
The example you're giving is a perfect example of a lesson that will NOT show up in conflicting pathways. I'd rather let the content dictate the crossover, rather than a technical convenience. 

But I've voiced my concerns, and maybe they won't come to pass. We'll see how the lesson-specific solution holds up in the long run.

**Comment by kfisler** [comment]
Where would I look to see what you propose as a shared definition of "variable"? I think the two original definitions were about rather different conceptual ideas, one very concrete and one more abstract.

**Comment by ds26gte** [comment]
We could do what mainstream dictionaries do, i.e. give an enumerated list of the different senses of the same headword.

**Comment by flannery-denny** [comment]
@schanzer @kfisler

@ds26gte has already resolved this! ss has a separate glossary :) I am close to having the first two lessons ready for viewing.

Flannery
