### ISSUE TITLE
bug report - live on the web - squished Notice and Wonder Tables

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1057]
https://bootstrapworld.org/materials/fall2022/en-us/lessons/making-game-images/pages/NoticeAndWonder.html

This is what I see on the workbook PDF and on the website:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/87144723/180264303-7aa4f015-b16e-4d25-b682-45cf24aa25ed.png">

The text below is in the asciidoc so I don't think this should be happening?:
`++++`
`<style>`
`table { height: 90%; }`
`</style>`
`++++`

...or maybe there's an error there? Not sure.

**Comment by retabak** [comment]
https://bootstrapworld.org/materials/fall2022/en-us/lessons/functions-vertical-line-test/pages/notice-wonder-functions.html

Seeing the same problem at link above; concerned there's a bigger problem!

**Comment by flannery-denny** [comment]
@schanzer I am seeing this issue throughout our materials. Here's another example [numbers inside video games notice and wonder](https://bootstrapworld.org/materials/fall2022/en-us/lessons/numbers-inside-video-games/pages/NoticeAndWonder.html)

**Comment by schanzer** [comment]
There's definitely been some kind of regression on our use of CSS flexbox. But the need to get the workbooks updated asap means this is NOT the time to dig into major structural changes to the underlying CSS. Pushing this off until the fall.

In the meantime, I can't update the website until #1051 is resolved.
