### ISSUE TITLE
@handout{} directive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1059]
@ds26gte , spec for the directive is at the bottom of the comment thread

---------------------------------
Currently I have two directives available to me for printed materials.

@printable-exercise, which lists pages that don't belong in the workbook as page 0
![Screen Shot 2022-07-22 at 1 58 12 PM](https://user-images.githubusercontent.com/66691020/180505876-5f4929b5-aa74-4432-8c1e-a92e10e86588.png)

and @opt-printable exercise, which lists pages as optional at the end of the materials list.
![Screen Shot 2022-07-22 at 1 57 17 PM](https://user-images.githubusercontent.com/66691020/180505948-12140d1f-a494-4edf-a735-b1760d47376c.png)

Neither of these is what I want here!

I want the Shipwreck Evidence Cards to appear at the top of the materials list, because they are the first thing that students will engage with, and I don't want them to be in the workbook because they are supposed to be printed doublesided and cut out for students to work with.

Not sure whether it would be better to 

- make a third directive @printout / @handout 
or 
- change the default so that a @printable-exercise puts something other than (page 0) in the parentheses if a page is not listed in workbookpages.txt - pretty sure pages like this used to just not have anything after the page title.

open to other ideas. What do you think @schanzer?

**Comment by schanzer** [comment]
@flannery-denny this is what `@link` is good for. It just takes a standard, relative URL, so something like `@link{pages/evidence-cards.shtml}` should do nicely.

**Comment by flannery-denny** [comment]
@schanzer actually `@link` is not the right tool for this job. Those links don't (and shouldn't!) get autoincluded in the materials section. We use them for things like linking to sources for notice and wonder pedagogy, which don't belong in the materials table at all.

**Comment by schanzer** [comment]
@flannery-denny I'm suggesting you use @link _in the materials section_, manually adding it to the top where you want it, rather than having it auto-included. 

How frequent of a use-case is this? How many of these are needed in each lesson?

**Comment by flannery-denny** [comment]
@schanzer Experience has proven time and time again that the materials
section should be autogenerated.
These are needed in every SS lesson (I'd guess there are already 50 of them
to be converted!) and some DS and algebra lessons.

**Comment by schanzer** [comment]
@flannery-denny if these are used that frequently, then I agree that a new directive is needed. 

@ds26gte , can you make a `@handout` directive? Here are the semantics:

- handouts should be auto-listed in the materials section, above optional materials
- handout list items should have `"class=handout"`
- a handout specified in a lesson must correspond to a file in the pages directory

**Comment by schanzer** [comment]
@flannery-denny this is ready for testing! :)

**Comment by flannery-denny** [comment]
@ds26gte  looks great!

**Comment by flannery-denny** [comment]
@ds26gte For some reason when I build `defining-table-functions` the list includes the handouts from `functions-problem-solving-together` (listed here as set 1: g, h, r)
![Screen Shot 2022-07-24 at 4 56 17 PM](https://user-images.githubusercontent.com/66691020/180667443-7dd2d4b3-f16f-4a99-823a-dc170ba84541.png)

**Comment by flannery-denny** [comment]
@ds26gte to reproduce, list the following in your `__sample` pathway

> functions-problem-solving-together
> defining-table-functions
