### ISSUE TITLE
Bootstrap Team page ready for an update

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1064]
- [x] Jen is no longer the Manager of Training and Outreach for Bootstrap.
- [x] Eric is no longer in NY
- [x] Mariana, Monique, & Adam's bios are time capsules - I'm sure they all have more experience with bootstrap than represented here.
- [x] Bootstrappers Emeritus: Might make more sense to put Danny & Sorawee at the beginning of the list as language developers?

**Comment by schanzer** [comment]
Good call! Done.
