### ISSUE TITLE
Track down KIPP lesson plans missing from Shipwreck unit module (links go to blank lesson plans)

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1065]
Misha Jemison owns the original file that has empty and/or wrong links for more than half of the lesson plans. I am assuming those lesson plans exist somewhere if teachers have already piloted them... and they would be quite helpful to have access to.
- [ ] 1
- [ ] 3
- [ ] 5 (the lesson plan linked is lesson plan 6)
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10
- [ ] 11
- [ ] 12

While we're at it:
- [ ] UNIT 1 is totally MIA
- [ ] UNIT 4 (Rights in America) doesn't have anything in it besides audio recordings and original brainstorming

Here is a [link to what we have copies of](https://drive.google.com/drive/folders/1Rlmx1ouzcdAqxTF5bg4YpUGjXkmKJgMz?usp=sharing)

**Comment by kfisler** [comment]
Just got the [folder link](https://drive.google.com/drive/folders/1QgwYy3e2I7vNdblUI9-WGrvu8FHfEBUJ?usp=sharing) and shared it with Flannery.

**Comment by flannery-denny** [comment]
@kfisler thanks for the folder! It is missing lesson plan 5.

**Comment by flannery-denny** [comment]
@kfisler Any luck with this?
