### ISSUE TITLE
Decide how we want the glossary to work

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1067]
Currently we can use more than word in `glossary.rkt` to return the same definition 

For example:
`((en-us ("coordinate" "coordinate pair") "a number or set of numbers describing an object's location")
     (es-mx ("coordenada") "un número o conjunto de números que describen la ubicación de un objeto" "sistema de coordenadas"))
`
What I would expect to happen is that the term that appears in the glossary section of the lesson plan would be the one used in the body of the lesson plan

> Glossary
> coordinate a number or set of numbers describing an object’s location 
> domain the type or set of inputs that a function expects 
> range the type or set of outputs that a function produces 
> slope the steepness of a straight line on a graph 
> y-intercept the point where a line or curve crosses the y-axis of a graph

Currently, no matter which term is used in the lesson plan (in the case of Defining Linear Functions this would be coordinate pair, the first term listed in the glossary is the one that appears in the glossary. 

If you would expect the glossary to work the way that I would, please assign to Dorai. Otherwise let's discuss and come up with a clearer spec.

**Comment by ds26gte** [comment]
The reason for allowing multiple forms of a term in `glossary*.rkt` is to allow you to use `@vocab` around any grammatical variant (plural, preterite, gerund) of the term in the source. 

Thus, one can write the source document to use whatever natural variant of the term suits the text, but the corresponding term in the glossary is always the canonical (singular, non-declined) form the term, which would be the first term in the term list. Having the generated glossary use the item as used in the source would then be undesirable.

**Comment by flannery-denny** [comment]
@schanzer @ds26gte 

Let's mean and average as an example for thinking this through. 
- If I've only seen the word average in the lesson plan, it might not help me to see the definition of mean appear. 
- Similarly, if I know what the average is but I've never heard of the mean and I look at the glossary to support me but the word mean isn't in the glossary, I don't get the support I need.

If you'd prefer to always use the first word, we should list mean and average as two separate entries in the glossary. I'm ok with that, but it's not how we've been working.

**Comment by ds26gte** [comment]
I can add some syntax to the headword(s) specification in the glossary file to accommodate this view. Thus instead of

`("mean" "average")`

we could have 

`(("mean") ("average"))`

This would avoid having to specify two separate entries for `mean` and `average` with the identical definition.

All the older syntaxes for headword(s) would still be read as currently. The cost is having your eyes ache seeing so many parens, but it will only be for the contentious entries.

**Comment by flannery-denny** [comment]
@ds26gte I love this proposal. If @schanzer is on board, please make it so!

**Comment by schanzer** [comment]
@ds26gte onboard. Make it so!
