### ISSUE TITLE
Inconsistent use of box-plot, boxplot and Box Plot in lesson plan and accompanying workbook pages

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1072]
I changed a couple of workbook page titles but then looked at more content am not sure that it's actually the way we should be standardizing.

**Comment by schanzer** [comment]
@flannery-denny "box plot" is the correct term (as opposed to boxplot, box-plot, or box-and-whisker plot). I'll make these changes.
