### ISSUE TITLE
Resolve float of side by side displays in custom scatterplot lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1073]
- [ ] In the custom scatterplot lesson there are two scatterplots that should be appearing side by side and don't for some reason. I know they used to be side by side. And I have tried changing their sizes to be dramatically smaller to no avail. 

You'll find them at line 118.

- [ ] the same type of glitch is resulting in histograms/summarizing columns taking up 2 pages.

**Comment by schanzer** [comment]
@flannery-denny this is related to #1058. Dorai and I are working on it, but this is essentially a duplicate
