### ISSUE TITLE
Some workbook pages are listed without a title In Exercises and Solution section of Teacher Resources Page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1074]
[https://bootstrapworld.org/materials/fall2022/en-us/courses/algebra-pyret/resources/index.shtml](https://bootstrapworld.org/materials/fall2022/en-us/courses/algebra-pyret/resources/index.shtml)
Scroll down to Solving Word Problems with the Design Recipe to see what I'm talking about. There are several other instances in lessons that follow.

**Comment by schanzer** [comment]
@ds26gte I believe the issue here is that DR directive pages supply their titles via a different mechanism than other pages, and the directive that scrapes them here isn't accounting for that.

**Comment by schanzer** [comment]
Confirmed fixed! Thanks, Dorai! 🧙🏽‍♀️
