### ISSUE TITLE
Should standard deviation lesson engage students with a starter file or is it totally unplugged?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1076]
Most of the other lessons say this in the preparation section:
`All students should log into @starter-file{program-list} and open their saved "Animals Starter File". If they don't have the file, they can open a new one from @starter-file{animals}.`

This lesson does not.

I see the contract for standard deviation, but I don't think I'm seeing anywhere where students are actually asked to use it. Perhaps this an entirely unplugged lesson?

**Comment by schanzer** [comment]
@flannery-denny yes, feel free to add that text. The lesson asks students to use the contract for standard deviation with a column of the animals dataset. Close when this is complete.
