### ISSUE TITLE
Live on web "Jump to Datasets and Starter files" doesn't go where it's supposed to 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1078]
This is an important [link](https://bootstrapworld.org/materials/fall2022/en-us/lessons/choosing-your-dataset/index.shtml?pathway=data-science#Datasets) in the [Choosing your dataset lesson plan](https://bootstrapworld.org/materials/fall2022/en-us/lessons/choosing-your-dataset/index.shtml?pathway=data-science) and it's not working properly.

**Comment by schanzer** [comment]
Good point! Feel free to delete the link and close the issue.
