### ISSUE TITLE
Audit CMP and IM lessons to see whether our new lessons align with anything

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1079]
- [ ] IM6
- [ ] IM7
- [ ] IM8
- [ ] IMHS
- [x] CMP6 (Data Collection could be an extension to [Data About Us](https://media.pk12ls.com/curriculum/math/cmp3/html_books/G6/U7/htmls/page_7.html), which focuses on IQR, measures of central tendency, box plots)
- [x] CMP7 ([data unit](https://media.pk12ls.com/curriculum/math/cmp3/html_books/G7/U8/htmls/page_vi.html) focuses entirely on center and spread)
- [x] CMP8 (We could offer function notation as extra scaffolding for [function junction](https://media.pk12ls.com/curriculum/math/cmp3/html_books/G8/U8/htmls/page_vi.html)

_CMP has nothing on scatter plots, standard deviation, or linear regression_
 
New lessons include:

- Custom Scatter Plots
- Data Cycle
- Data Collection
- Function Notation
- HOC-Data
- Linear Regression
- Standard Deviation

**Comment by flannery-denny** [comment]
[CMP Math Content by Unit](https://connectedmath.msu.edu/sites/_connectedMath/assets/File/the-math/pdf/math-content-by-unit.pdf)

**Comment by flannery-denny** [comment]
@schanzer I've identified which units could be added to the CMP alignment as extensions / scaffolds. None are a direct match. Lmk whether or not you want me to add them to the files.

**Comment by schanzer** [comment]
@flannery-denny Thanks for looking into this! 

I think it's reasonable to add them to the files.

**Comment by flannery-denny** [comment]
@schanzer can you remind me where these alignment files are now stored?

**Comment by schanzer** [comment]
@flannery-denny `/shared/langs/en-us/docroot/textbooks`

**Comment by flannery-denny** [comment]
@schanzer @retabak please confirm you're satisfied with these commits.

**Comment by schanzer** [comment]
@flannery-denny oh! sorry, your last comment made me think this was the end of it. Reopening.

**Comment by retabak** [comment]
After reviewing, I don't think the IM pages need to be adjusted at all. Closing!
