### ISSUE TITLE
@lesson-link

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1080]
There are multiple places where want to link to a lesson plan, or a page inside a lesson folder:

- [x] Lessons that refer to other lessons
- [x] Lessons that refer to other lessons' wb pages (e.g. the box-plot lesson depends on a measures-of-center wb page)
- [x] Pathway-specific pages like `data-science/resources/pages/implementation-options`, and all the textbook alignment files

While not a _constant_ source of bugs and headaches, they are a persistent one. I wonder if it would make sense to add a `@lesson-link{}` directive, which consumes a path that always starts with a valid lesson name. The directive could do several things that make authors' lives easier:

- Check to ensure the lesson is valid
- Auto-append `proglang` extensions
- Use the proper relative link paths

Let's discuss in our curriculum call today.
------------------------------------------------------
Changes/additions:

- [x] make the directive work on slides
- [ ] extract link text from WBpage and Lesson titles
- [x] don't need `lessons/` to be at the start of the link path

**Comment by schanzer** [comment]
@ds26gte and @flannery-denny having the preprocessor handle proglang extensions was a HUGE savings for the project asciidocs, which previously used ifproglang in a million places.

**Comment by flannery-denny** [comment]
Hooray!
