### ISSUE TITLE
Make DR Telephone @opt-project

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1081]
- make a new branch
- turn DR directions into @opt-project page
- link to it from DR page
- remove collaboration lesson
-------------------------------------

Re-opened 8/29 -- Our choices for this activity are (1) make it a lesson, (2) make it a project, or (3) make it a handout.

@retabak points out that a number of problems with the lesson format. Primarily, the issue is that this would be a lesson that feels solely like _practice_ (and it is!). But there's also the issue of adding it to the pathway but highlighting it as optional (as @flannery-denny has proposed).

This PR initially focused on making it an opt-project, but we got stuck because projects need rubrics.

This PR tried to make it a handout, but this runs afoul of the semantics we already for handouts: handouts are _student facing_, and we don't have any kind of "sub-handout" for handouts that support an existing handout. This is teacher-facing, and has supporting documents. Handouts also don't align to standards, but this activity clearly does and should be called out.

After speaking with Rachel, I think it makes sense to revisit the project approach. Maybe there _is_ a rubric for an activity as complex as this! Rachel agreed to take a whack at it, so I'm re-opening.

**Comment by flannery-denny** [comment]
@schanzer @ds26gte Could you please remind me how to make a new branch? I tried to find it in the README doc, but am not. Thanks!

**Comment by schanzer** [comment]
@flannery-denny 

git checkout -b myNewBranch

This will create a new branch (based on whatever one you have checked out) called "myNewBranch"

**Comment by flannery-denny** [comment]
Please checkout to branch `telephone` and see how `functions-dr` lands with you now.

2 issues:

1. I have used the @opt-project directive. That means that these activities will be autoincluded in the @optprojects section of the teacher resources page. And it means that it's throwing a warning about the lack of rubric... I can live with this but am open to other proposals.
2. I see that E moved the contracts on the Design Recipe Telephone pages from the bottom of the page to the top of the page R's request. 

I understand why she thinks that might look better... but it **doesn't serve the activity.** The person who needs to see the contract is the person writing the examples and by the time they get this piece of paper that contract will be folded over and unavailable to them if it get listed at the top of the page! 

@schanzer None of us have loved it at the bottom of the page. Is there any way to make it appear above the Examples section... that's where it's really needed. And if you could figure out how to do it, there are several of these DR telephone exercises that the infrastructure would support.

If that's a no go for you. I'm going to let @retabak sort out how best to include the contracts at the end, since I have tried several strategies to make them read well at the bottom, you have each objected to them being there, and this is the second time that I've had to remind you that the **contracts cannot go at the top of these pages**.

**Comment by schanzer** [comment]
@flannery-denny I hear you re: contract positioning. On my list, but may not get to it until the weekend.

I took a look at the branch, and I'm happy with the way telephone is factored out into an optional project. However, "where'd you get that" is such an important part of our pedagogy that I'm feeling pretty uncomfortable hiding them in an optional project that teachers might miss. Can we keep this as part of the lesson?

**Comment by flannery-denny** [comment]
I don't have strong feelings. Where'd you get that was in a pedagogy box. I can put it back in one.

**Comment by flannery-denny** [comment]
@schanzer @retabak pushed an update that addresses Es request. (and removed some vocab words from the glossary) close and merge if you're satisfied.

**Comment by flannery-denny** [comment]
My one question reminds about use of @opt-project without a rubric. It's too many pages for an @opt-printable exercise. I guess it could be an @online-exercise.

But it would be cool if stuff like this and where'd you get that were included on the Teacher Resources page. Some part of me wonders whether there's another directive we want for flagging activities... like this... and the playdough stuff in DS and there are probably more things that I'm not thinking of... but I'm not attached to the idea.

**Comment by retabak** [comment]
@flannery-denny - you're a genius; having the telephone activity in this position feels MUCH better to me. I really like this!  It makes so much sense now :)

Apologies for requesting that the contracts be relocated! It didn't occur to me that their position on the paper was strategic. I agree with your proposal @flannery-denny for them to be located above the Examples section if @schanzer can swing it.

Re: the lack of rubric and the warnings: a new directive seems like a possibly good idea but I do not have strong feelings.

**Comment by schanzer** [comment]
@flannery-denny and @retabak this looks really great - I'm happy with all the changes. I spent about two hours today trying to figure out a way to shoehorn the contracts inside the DR template, and eventually had to concede defeat -- there's just no way of doing this without re-creating the entire Design Recipe directive from scratch. 

For what it's worth, I never felt that adding these contracts was even necessary. They literally have all the contracts in their workbooks already! @retabak , if you want to move them back to the top, that's fine with me. But I'd vote for removing them altogether.

**Comment by schanzer** [comment]
Let's discuss the idea of a new directive in our next meeting - but I definitely encourage you both to think creatively about whether existing directives can be repurposed, or whether this is infrequent enough as to be done manually via a standard `@link{}`

**Comment by retabak** [comment]
I can remove the contracts completely or move them back to the top. I have no preference; @flannery-denny , do you? So far we have one vote for removing completely.

**Comment by flannery-denny** [comment]
@retabak They do not belong at the top. 

Can you figure out a way to include them at the bottom that satisfies you?

Flannery

**Comment by retabak** [comment]
Nah. So I suppose I vote for removing them. Cool with you @flannery-denny ?

**Comment by retabak** [comment]
Moved contracts back to bottom of page after chatting with @flannery-denny.

**Comment by flannery-denny** [comment]
Flannery will hand include the links from the DR page in the materials section.

**Comment by flannery-denny** [comment]
@retabak @schanzer After many attempts to get the materials section looking good I listed all of the DR pages in the additional practice section and they now get autoincluded in materials in a logical order. Merge if you're satisfied.

**Comment by flannery-denny** [comment]
@schanzer please make sure these last commits get pushed through to the web. thanks.

**Comment by retabak** [comment]
Started thinking about a rubric and realized that... maybe the [DR rubric we already have](https://docs.google.com/document/d/10YYUmMbE77VwC3W24yZykZe1I0ELL_jE2_NQyH473MY/edit) could serve as a jumping off point? I would revise it to look and feel more similar to the other rubrics I've worked on (for instance, by putting the "advanced" column on the left rather than the right), but it seems like it might fit in perfectly here.

Here are some thoughts / questions I have about said rubric:
- [ ] does it already exist as an asciidoc?
- [ ] should we add any collaboration rubric rows? (Not totally sure what this would look like, given that - as I've mentioned - this project doesn't TOTALLY feel like an exercise in collaboration to me)
- [ ] should we add a general ['attending to precision'](http://www.corestandards.org/Math/Practice/MP6/) rubric row?
- [ ] how would we want to integrate this rubric? Seems like it might be more appropriate for students to self assess / peer assess than for teachers to give a grade.... which is actually aligned with equity audit concerns, I believe?

Now that we're thinking about adding a rubric, I'm wondering if we ought to modify the project page to look more like our other project pages, which generally have these sections - issue, objectives, project phases - rather than launch / investigate / synthesize.

**Comment by schanzer** [comment]
@retabak I does _not_ exist as an asciidoc, but it definitely should! No need for additional rows -- let's see if there's even room on the page first!

I LOVE the idea of having students peer-assess. Maybe each group of 3 students trades papers with another group?

And YES this should look like a project page. Go for it!

**Comment by flannery-denny** [comment]
@retabak I'm not attached to Launch Investigate Synthesize for DR telephone and am happy to get rid of them but I also don't see the projects as having a consistent format and I don't think the words you've proposed make sense for the file. Feel free to change.

I am happy to asciidocify the rubric for you today or tomorrow if you want.

**Comment by retabak** [comment]
@flannery-denny - I'd love for you to asciidocify the rubric! THANKS. Also, you're right, project formatting is not totally consistent but the ones that we've adapted from IDS (by Joy) sort of follow a similar template. 

I'll revise the lesson / project to look a bit more like those projects, as I don't think "launch / investigate / synthesize" are quite right either.

**Comment by flannery-denny** [comment]
@retabak in case you missed the commit, I've asciidocified that rubric. I switched the order of the columns so that wow came first to save you the effort. And I changed the wording about to cond to piecewise functions, since we aren't using cond anymore. Have to admit I'm not impressed with this rubric (not even sure whether it make sense to have a 1-4 scale as opposed to a 1-3 scale) and am looking forward to you giving it some tlc.

**Comment by retabak** [comment]
I started tinkering with the asciidoc then was just making too many changes. Here's a rough, not-totally-finished google doc draft (that I think I like so far?):

https://docs.google.com/document/d/1eWUDRZ2pH0qPPbW7cnGQ3M9V-rwDKDuNi-FOerfUXd4/edit

**Comment by retabak** [comment]
make sure rubric gets put on TR page and in lesson

**Comment by retabak** [comment]
@flannery-denny and @schanzer - take a look!
Pushed a rubric and modified the lesson structure a bit to make the activity feel more aligned with our other projects.

**Comment by schanzer** [comment]
@retabak the rubric looks really good. Nice work!

I've reformatted the lesson plan somewhat, to treat the opt-project the way such projects are handled in other lessons. Let me know what you think?

**Comment by retabak** [comment]
@schanzer - I had considered doing this myself but wasn't sure if it would work. I was concerned about having two big pedagogy boxes in the same section, and also about not giving telephone-dr enough attention. 

Now that I see it, though, I think that this works. I'm happy!

**Comment by flannery-denny** [comment]
@retabak I have edits to push for the `dr-telephone` page but am not able to push or pull on master at the moment. Will review @schanzer's suggestions, your rubric, and share my thinking as soon as I'm back in action

**Comment by schanzer** [comment]
@retabak with Flannery's changes in place, I'm happy to sign off on this. Close if you feel good about the version as-is?

**Comment by flannery-denny** [comment]
I think this issue is ready to close. 

And I have two more quickly addressable concerns about this lesson:

- [ ] @schanzer could you please make the formatting of this section more consistent? We're using "", @vocab,  and italicization. I have a feeling you have opinions about which makes the most sense
![Screen Shot 2022-09-08 at 5 23 31 PM](https://user-images.githubusercontent.com/66691020/189228722-0648fb5c-069b-4fa9-8ced-9eaca4634354.png)

- [ ] @retabak What is the decision re: the MLR strategy boxes? Are we cutting them? Or are you wanting to update them? This lesson has one worth addressing, either way.

**Comment by flannery-denny** [comment]
@retabak please also confirm that you like my formatting suggestions. No worries if you'd prefer to revert them.
