### ISSUE TITLE
Introduce "Variables" explicitly in Numbers in Videogames

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1082]
Revisit this lesson and think about whether we could introduce the term variable here.

**Comment by flannery-denny** [comment]
@schanzer I tackled the numbers inside video games lesson. Curious how it lands with you. Realizing that perhaps these should have gone on Fall2023 and should not get pushed to the web because my suggestions include a change to a workbook page… but the only workbook change is to add words to a column title to make it more explicit, so maybe it’s ok? Fyi - the word variable was in the lesson description… even though it wasn't in the lesson.

**Comment by schanzer** [comment]
@flannery-denny this seems like a small enough change that we can push it through to fall2022. Nice work!
