### ISSUE TITLE
bug with @starter-file{program-list} 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1083]
In `starter-files.rkt` we have these definitions

> (define *starter-files*
> 
> '(
> 
>   ("editor" "the editor"
>     ("pyret" "https://code.pyret.org/editor" "code.pyret.org (CPO)")
>     ("wescheme" "https://www.wescheme.org/openEditor" "WeScheme")
>     ("codap" "https://codap.concord.org/app/static/dg/en/cert/index.html" "CODAP")
>   )
> 
>   ("program-list" "program list"
>     ("pyret" "https://code.pyret.org/" "code.pyret.org (CPO)")
>     ("wescheme" "https://www.wescheme.org/console" "WeScheme")
>     ("codap" "https://codap.concord.org/app/static/dg/en/cert/index.html" "CODAP")
>   )

In the Data Science version of Method Chaining that translates to this in the preparation section:
![Screen Shot 2022-08-04 at 8 28 25 AM](https://user-images.githubusercontent.com/66691020/182858982-c0a0db28-4a61-47f1-9982-628ebc07d8f9.png)
In the CODAP version of the same lesson the word CODAP is missing where we see CPO in the previous example
![Screen Shot 2022-08-04 at 8 28 35 AM](https://user-images.githubusercontent.com/66691020/182859070-9856d016-4f4e-4a13-8b45-1a1c8f3a5e1d.png)

**Comment by ds26gte** [comment]
Not able to replicate this.

![codap-starter-file](https://user-images.githubusercontent.com/3708729/182865638-4c824f4b-9f21-4ed7-96ed-4f36b2f91332.png)

Is this a local build with the latest?

**Comment by flannery-denny** [comment]
Well, that's good news. Trashed my directory and rebuilt and it resolved itself. But I had just force-built...

**Comment by ds26gte** [comment]
Possible you had a stale `starter-files.rkt` in your `distribution/.prog`

**Comment by flannery-denny** [comment]
@ds26gte. good to know that's a thing. thanks!
