### ISSUE TITLE
bug live on website - teacher solutions page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1085]
What's going on here? Worksheet name is not showing up sometimes?

https://bootstrapworld.org/materials/fall2022/en-us/courses/algebra-pyret/resources/index.shtml

![image](https://user-images.githubusercontent.com/87144723/183148203-41e2f5fa-cbde-40ae-9f99-8c002d1ca796.png)

**Comment by schanzer** [comment]
Yep. It'll be updated this weekend

**Comment by retabak** [comment]
Okay! I'll close.
