### ISSUE TITLE
update slides in 2 inequalities lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1086]
@flannery-denny - I think this lesson is your baby!

In doing the instruction box audit, I noticed that this "launch" felt a little confusing and structure-less. There are no actual instructions for what students should do in the starter file. Basically, there's a lot of notes for hte teacher, and then kids are supposed to open the starter file, then notice, and wonder, and jump into the investigate section. 

Optimally, I think we'd include a worksheet to guide student thinking as they explore the starter file during the launch, but that's not possible now - so I just added more structure.  I'll tag the commit to this issue once I check it (which I'm about to do now!).

Take a look, see what you think! Hoping I didn't step on your toes :)

**Comment by retabak** [comment]
Also gave similar treatment to "Compound Inequalities", which had the same issues as "Simple Inequalities."

**Comment by retabak** [comment]
Good catch re: the new image! I hadn't noticed the old image was off.

**Comment by flannery-denny** [comment]
@retabak Just pushed adjustments to the second lesson. close if you're satisfied

**Comment by flannery-denny** [comment]
@schanzer @retabak is suggesting a workbook page be made for next year. Would you like to open a fall2023 branch now where that can happen or should we make a new issue to deal with in the future and put it on the fall2023 milestone?

**Comment by schanzer** [comment]
@flannery-denny Let's open a new branch -- with the usual caveat about being extra careful which branch we work on. We have a full year to create a merge nightmare. :)

**Comment by flannery-denny** [comment]
@retabak ready for slide updates. close when you're done.
