### ISSUE TITLE
Proposal: Revise standards alignment infrastructure

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1088]
I'm working on the NGSS alignment (#1060), and realizing that our dictionaries are not set up as well as they could be.

The workflow for alignment is typically "find a standard, then go find the lessons that implement it".  Currently we have one dictionary that associates an identifier like "MS-SEP8-3" with a description like "Gather, read, synthesize information from multiple appropriate sources and assess the credibility....". This is well and good.

We _also_ have a dictionary that associates a single lesson with all the various standards. This is problematic, because as the lists of standards gets longer it becomes harder and harder to scroll through all the lessons. It's also **totally backwards** from the workflow, which uses the standard as the key and the associated lessons as the values.

**Proposal:** We transpose the second dictionary. So instead of:

```
    ("grouped-samples"
        "6.EE.B.6"
        "8.SP.A.1"
       ....
        "MS-SEP4-7"
        "MS-SEP5-3")
```

We have 

```
    ("6.EE.B.6"
        "grouped-samples"
        "linear-regression" 
        "functions-make-life-easier"
        "functions-examples-definitions")
```

@ds26gte I'd like you to weight in here, especially on whether this transposition is something that can be automated, or if it has to be done by hand.

**Comment by ds26gte** [comment]
Can do it with a throwaway Racket program

**Comment by schanzer** [comment]
In that case, let's do it. I think this is going to save us a LOT of time in the long run, both in maintaining existing standards alignments and adding new ones.

**Comment by ds26gte** [comment]
OK, I'll do it with a couple of commits, starting with creating a new `standards-and-lessons.rkt` file (from the `lessons-and-standards.rkt` file) that inverts the mapping. Wait til the last commit

**Comment by schanzer** [comment]
@ds26gte nice! I see that you did not remove the `lessons-and-standards.rkt` file. Do they co-exist, or is one of them deprecated?

**Comment by ds26gte** [comment]
What about for practices and textbooks? They also currently have maps from lessons -> {practices, textbooks} rather than the other way around

**Comment by schanzer** [comment]
Yup - I'd switch them all.
