### ISSUE TITLE
tweak CODAP DR template

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1089]
The directions (under "Example Tables") say: "In the sample tables below, add the relevant columns." 

Adding relevant columns isn't always needed, however, causing this to be confusing.

Maybe we say: "Populate the sample tables below and (if needed) and any relevant columns." ?

**Comment by schanzer** [comment]
@retabak Love it. Make it so!

**Comment by schanzer** [comment]
Err....I mean I'll make it so :)
