### ISSUE TITLE
codap DR solutions - can I check which Transformer to use?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1092]
Is there a way for me to check off which Transformer to use on the solutions page?

![image](https://user-images.githubusercontent.com/87144723/184374341-9246a5de-34da-4d43-abce-8d46ee8b0a8b.png)

if so, I'm not seeing it! Can someone spell it out for me if it exists? @ds26gte @schanzer ? And... if it doesn't exist, can you make it so? (I'm working in method-chaining right now!)

**Comment by ds26gte** [comment]
You have to supply the `#:transformer-type` field in the design recipe. In this case, you want to add

```
#:transformer-type "filter"
```

Ohter possible values are `"transform"` and `"build"`. Case doesn't matter, although they will be shown in title-case in the output (as in your image above).

**Comment by ds26gte** [comment]
P.S. And in the rare case where you want to show the transformer type on the student (non-solutions) page too, add the further field
```
#:show-transformer-type? #t
```

**Comment by retabak** [comment]
@schanzer - I'm still not seeing the Transformer checked on the solutions page and @ds26gte doesn't know why! We're wondering if it's OS-related.

Can you check if you see "Filter" checked off on dr-2 in method-chaining in the codap pathway?

**Comment by schanzer** [comment]
@retabak I think Dorai fixed this - can you confirm?

**Comment by retabak** [comment]
fixed!
