### ISSUE TITLE
LIVE ON WEB - Codap stuff on Pyret Page 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1093]
Ahhh!

There's a very old version of the CODAP method chaining lesson that is live on the Pyret method chaining lesson.

Very very sorry if this is my doing. Please fix ASAP.

All this stuff does not belong in Pyret (nor is it in CODAP anymore):
![image](https://user-images.githubusercontent.com/87144723/184395506-e0a93880-bdb6-4077-b60e-13f223993f09.png)

**Comment by schanzer** [comment]
@retabak sorry, I don't see ANY of this stuff in [the method chaining lesson](https://bootstrapworld.org/materials/fall2022/en-us/lessons/method-chaining/index.shtml?pathway=data-science). The screenshot is helpful, but without a link it's hard for me to know where you're getting it.

**Comment by retabak** [comment]
Whew, I was looking at an older version. not sure how I got there though? All clear. Closing.

https://www.bootstrapworld.org/materials/fall2021/en-us/courses/data-science/lessons/method-chaining/index.shtml

**Comment by schanzer** [comment]
That's helpful, thanks. I'm going to re-open this so I remember to go back and fix it.

**Comment by schanzer** [comment]
This is now fixed -- I had to check out the Fall2021 tag and rebuild, then hunt down a typo in some codap material. As it stands there are other problems with this page, but at least we're not leaking codap. I don't think it's worth going back to fix the workbook page numbers, especially given that this version is a full year old.
