### ISSUE TITLE
method chaining concern

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1094]
From Flannery: " There are lot of words in the launch of chaining. I recommend an activity that takes the importance of order out of the heady space and gives them an opportunity to write something down before weighing in on which should happen first."

I think this is good feedback! I think the Pyret lesson launch is also kinda heady as well. @schanzer - any ideas on how we could address @flannery-denny's good suggestion in both lessons? Or, @flannery-denny - do you have any specific suggestions, here?

**Comment by schanzer** [comment]
@flannery-denny definitely curious what you have in mind here!

**Comment by flannery-denny** [comment]
I could definitely make some scaffolding for this, but without investing real time I see the absence of it more clearly than the solution.

A few things I notice...

1. There's a lot of code referenced that most people won't be able to visualize in their head. 
- We could have a starter file that would allow them to test it out so that we can show them what happens rather than tell them about.
- We could have a handout that shows the code alongside the table it produces so there's at least a visual to look at.
2. You describe errors that will happen when order is incorrect. Wouldn't it be nice to let them see one of those error messages?
3. The lesson plan includes this teaching tip:

> Teaching Tip
> Use different color markers to draw nested boxes around each part of the expression, showing where each Table came from.

As far as I can tell, there are not tables or directions to make tables... seems like it would be beneficial for teachers and students alike to see how the code connects to the tables.

Finally, there's a typo on the second line of this paragraph and I'm not really sure what it's supposed to say so I can't fix it...
![Screen Shot 2022-08-18 at 9 38 34 AM](https://user-images.githubusercontent.com/66691020/185422845-90a80e96-237f-43a2-8d81-4002c253850c.png)

**Comment by schanzer** [comment]
@flannery-denny @retabak I added some content that I think addresses these concerns, but it shift the framing a little bit by drawing an analogy to adding multiple numbers together. I think this shift is good, and I've adapted the Pyret section to work with it. 

**First:** Please build the Pyret version and see if it addresses the issues above.

**Second:** I'm not as clear on how the CODAP section would need to be changed, however -- perhaps Rachel can take a crack at that?

**Comment by flannery-denny** [comment]
@schanzer I think this is an improvement. It would still benefit from an example of 
![Screen Shot 2022-08-30 at 4 35 40 PM](https://user-images.githubusercontent.com/66691020/187538357-144a2f9e-9791-40ee-8ec5-9d3ab3adaffb.png)
before we get to the Investigate section.

**Comment by schanzer** [comment]
@flannery-denny strongly disagree. The investigate section gives students a chance to think and explore, without telling them what will happen. Inevitably some of them will open their Pyret starter file and experiment. I do not want to take away this opportunity for discovery.

To me, this is very much a synthesize discussion. Happy to hop on the phone if I haven't convinced you.

**Comment by flannery-denny** [comment]
Add instructions to the launch that have students think about what will happen when they add a column and filter the table in the method chaining starter file in two different orders.

**Comment by flannery-denny** [comment]
@schanzer 

1. I pushed some small but significant changes to the rewrite. Please confirm they work for you.

2. When we talked this evening you seemed to think that the helper functions predefined in the table methods starter file would work well for illustrating the importance of order. Perhaps I'm missing something, but I don't see how any of these things conflict/interact with each other. Am I missing something? If I'm not, is it ok to add another function to the file that would serve the purpose?

```
# is-dog :: (r :: Row) -> Boolean
# takes in a row and tests whether the species is dog.
fun is-dog(r): r["species"] == "dog" end

# is-old :: (r :: Row) -> Boolean
fun is-old(r): r["age"] > 10 end

# lookup-name :: (r :: Row) -> String
fun lookup-name(r): r["name"] end

# lookup-fixed :: (r :: Row) -> Boolean
fun lookup-fixed(r): r["fixed"] end

# label :: (r :: Row) -> Image
fun label(r): text(r["name"], 20, "red")
end

# kilos :: (r :: Row) -> Number
fun kilos(r): r["pounds"] / 2.2 end

```

**Comment by schanzer** [comment]
@flannery-denny I'm nor sure what you mean by "conflict". This lesson has nothing to do with functions conflicting.

I think what you're asking is "how can we mess up the ordering of methods, to trigger an error?" Here's an example:

```
animals-table.order-by("kg", true).build-column("kg", kilos)
```

**Comment by flannery-denny** [comment]
@schanzer Thanks. I was looking for an example of 

> Suppose we want to build a column and then use it to filter our table... 

ordering a non-existent column is a clearer-cut example.

**Comment by retabak** [comment]
This snippet (below) would VERY confusing to students who will almost certainly jump to the conclusion that `result` is merely `x + y` given that 1+2 is 3.  1, 2 and 3 are nto good numbers for this example unless you are actually trying to be confusing, given that this is an example of ugly code? (Then you accidentally omitted 3 in the subsequent sample line of code and I was even more confused!!)

![image](https://user-images.githubusercontent.com/87144723/187763141-e6f490bc-4bbe-42b7-b6bc-c2889e427517.png)

This example seems useful but it isn't QUITE working for me. I think that putting the two snippets of code side by side (like in a table) would have a much stronger impact. We could then ask different and (I think) more productive questions, like, how are these different? How are they alike? Or even - what do you notice and wonder?!

IMPORTANT SIDE NOTE: @schanzer ! When you're writing / adding to / modifying lessons and you use [.lesson-instruction]. can you put the question _AND_ the answer in the gray box? You've provided an answer to "Why is this code ugly, or hard to read" both times, but in each instance it is not formatted in the way that we agreed when we discussed Instruction Box Auditing. (The answer should be in the box, intented and italicized below the question.)

**Comment by schanzer** [comment]
@retabak fixed the instruction box to include the italicized answers. Thanks!

I don't think making a side-by-side table is the best idea here, but I made some other changes that I hope will address the issue. Let me know what you think?

**Comment by retabak** [comment]
Wow! This feels SO MUCH BETTER to me.
I'm ready to close if y'all are happy. I think I was the last person who needed to weigh in, unless @flannery-denny wants to take another look at the latest changes?
