### ISSUE TITLE
formatting help needed - chaining-methods-order-matters in CODAP pathway

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1095]
@flannery-denny has rightly pointed out that this worksheet looks too squished, especially at the bottom:
![image](https://user-images.githubusercontent.com/87144723/184404109-daa19212-3fb3-4e45-a8bb-2334109f7123.png)

The only idea I have to fix it is to add a blank row between items. The worksheet looks nicer this way, but it spills onto a 2nd page, however, which is a no-go for a matching activity. Any ideas @schanzer ?
![image](https://user-images.githubusercontent.com/87144723/184403978-45b8a85c-af9a-43a6-8241-643a27c8f05b.png)

**Comment by schanzer** [comment]
@retabak pushed a fix. Be sure to look at the actual change, in case you need to make a similar one yourself in the future. Close if you're happy with this amount of spacing (I wouldn't go much bigger, since the page number will start bleeding into the table at around 6in)

**Comment by retabak** [comment]
perfect, thank!!
