### ISSUE TITLE
Make new workbook pages for inequalities lesson on Fall 2023 branch

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1098]
@retabak's lesson audit led to changes that led to more changes and now the lesson involves more explicit teaching before exploration. Make workbook pages to accompany this scaffolding.

**Comment by flannery-denny** [comment]
@schanzer I decided to make these pages as opt-printable exercises for 2022. Not sure whether they should stay that way or become printable exercises for 2023.

**Comment by schanzer** [comment]
@flannery-denny that's a good way to do it - we can revisit for 2023
