### ISSUE TITLE
Pyret tables in the lesson plans should have a custom CSS class

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#110]
We have a few tables in the DS lessons that represent REPL output. We should try to style these as close to CPO as possible. I'll handle the CSS, if Dorai can give me a CSS classname and a way of declaring it when authoring such tables.

**Comment by ds26gte** [comment]
Is this exclusively the third column (titled *Values*) in the subtable for "Pyret features" inside the larger table that starts off most lessons?
