### ISSUE TITLE
suggestions for "measuring deviance" section of standard deviation lesson

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1102]
- In the section of the lesson where standard deviation is introduced, students only compute standard deviation **once**. I know that finding standard deviation is a bit laborious, but I think one exposure is not enough to do the other activities in the lesson (which require some grasp on what standard deviation is). LET'S ADD A WORKSHEET. Maybe the worksheet could be optional? (If it were up to me, though, I think it would be required!) I get that Pyret can do it for them, but... will they understand what it is that Pyret is doing?
- We ask kids to make a guess about what the summary number for the cats ages dataset should be. My guess is that lots of kids will guess the Mean Absolute Deviation? (They'll add the distances and find the mean... yeah?) Given that we are essentially setting kids up to guess the MAD, I think we need to prepare teachers to explain the difference between MAD and STD. Or we need to at least offer some sort of response to inquiries on this topic.

**Comment by schanzer** [comment]
@retabak these changes are ready for your review!

**Comment by retabak** [comment]
Worksheet looks great! This all feels better.

One question: We say "standard deviation is the most useful way to summarize spread of a quantitative column." Can we highlight we it's more useful than MAD? (If my students asked - which seems quite possible - I wouldn't be sure how to respond.)

**Comment by retabak** [comment]
Oops!!! I saw the first change and missed the other part! YES, this is perfect. Exactly what I wanted. :)
