### ISSUE TITLE
Check for option types and throw an empty cell error

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1104]

**Comment by schanzer** [comment]
@flannery-denny I believe this is now fixed! Try leaving a blank cell _anywhere_ in the spreadsheet, and trying to make a chart, compute the mean, etc.

Note that you may need to hold the shift key down when you reload a starter file, to force the browser to fetch the latest published version of the DS-1.6 library.

**Comment by flannery-denny** [comment]
Wow! What a dramatic improvement. Thank you!!
