### ISSUE TITLE
images creating unneeded white space - nitpicky concern

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1107]
It bothers me when there's a big block of white space because we've inserted a large image on one side of the text, like below:
![image](https://user-images.githubusercontent.com/87144723/186755218-0f1faeaa-ffb4-4ae1-8a5c-ae999b4332ce.png)

Is there some sort of solution, aside from adding more text or making the picture smaller? I had mentally decided to ignore this and let it be.... then encountered it a few more times and figured it couldn't hurt to inquire if there's a relatively quick fix?

In the example above, I think this would look better if the "Investigate" section started right below the text and wrapped around the image.

**Comment by schanzer** [comment]
Unfortunately this is built into the way asciidoctor generates html
