### ISSUE TITLE
How do we include notes from Piecewise Functions Conditionals in the list for teachers in the resources section?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1112]
Piecewise functions conditionals is an optional lesson in this pathway, which means it's not listed in the DS pathway and just gets linked to... that means 

- [x] the notes don't get printed in the student workbook (perhaps they should be moved to another lesson so that students have them as a reference?
- [ ] and they aren't auto-included in the teacher resources section... we should at the very least be able to add them there manually.

**Comment by flannery-denny** [comment]
- copy-paste notes from pwc into custoscatterplots and add a link to it from the lesson plan mention

**Comment by flannery-denny** [comment]
@ds26gte I have added `notes-piecewise-functions.adoc` to `lessons/custom-scatter-plots/pages` and they are not being autoincluded in this list of notes on the data science/ resources page.

Please figure out how to make it happen ;)

Note: These notes are different from other notes in that they are not and should not be listed in `workbook-pages.txt`

![Screen Shot 2022-08-30 at 4 19 11 PM](https://user-images.githubusercontent.com/66691020/187535184-45bdc343-70fc-46a1-bd0e-3be7a77e6068.png)

**Comment by schanzer** [comment]
@flannery-denny does @ds26gte 's commit address the issue?

**Comment by schanzer** [comment]
@flannery-denny poke?

**Comment by ds26gte** [comment]
It does show up when I build on `master`.  The link is called `Piecewise Functions` because that's the title used in `custom-scatter-plots/pages/notes-piecewise-functions.adoc`.

**Comment by schanzer** [comment]
@ds26gte Ah, of course -- the issue was needing to rebuild all the lessons, not just the course folder. Awesome. THANKS!
