### ISSUE TITLE
Add a pedagogy box to the contracts lesson with a link to strategies for students as teachers

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1114]
Suggesting as an option that students could teach each other contracts for more complex contracts like `regular-polygon`, `isosceles-triangle`, etc.

**Comment by flannery-denny** [comment]
Possible articles:

- https://www.naesp.org/sites/default/files/StudentsasTeachers_CCAC15.pdf

**Comment by schanzer** [comment]
This is low priority, but if you think it can be done *quickly* I'm comfortable bumping that to the front of the queue. today?

**Comment by flannery-denny** [comment]
@retabak @schanzer Do you think this adds something to the lesson / our curriculum? Close if you're satisfied. Revert if you'd rather not include it.

**Comment by retabak** [comment]
I like this insertion!
