### ISSUE TITLE
Fall 2023 ToDos

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1115]
- [x] Decide whether the Frayer Models for Domain & Range, Function & Variable in `Contracts` should be `opt-printable` or `printable`
- [x] Decide whether or not include the new pages in the Compound Inequalities lesson in the workbook.
- [x] Decide whether to include the box plot concept vocab map in the workbook
- [x] Remove MLRs from lessons and standards library
- [x] Replace methods with functions in data science
- [x] replace histogram with functionality of labeled-histogram

**Comment by schanzer** [comment]
@flannery-denny I beloeve
