### ISSUE TITLE
Clean up "3 reads" pegagoy box in "Solving Word Problems with the Design Recipe"

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1119]
![image](https://user-images.githubusercontent.com/87144723/187972333-ff02ed30-39a9-4aec-8089-ba10d156664f.png)
It took me several minutes of googling to figure out that "MLR 6" stands for "Mathematical Language Routine 6". I _think_ these routinse are articulated in [this publication](https://www.heinemann.com/products/e07815.aspx).... but maybe they were developed as a part of the Illustrative Math curriculum? EIther way, we need a source.

There is also reference to a handout here that doesn't exist / isn't linked to?

I'm also not sure our synopsis of "3 reads" is faithful to the authors' original intent: http://www.fosteringmathpractices.com/3-reads/

Do we actually want students to use this strategy on the Matching worksheet right beneath the "3 reads" pegagogy box? If so, I think it would make more sense to actually incorporate that in the instruction box, i.e. "Read each problem three times. The first time, think about... The second time...."

**Comment by flannery-denny** [comment]
@schanzer These pedagogy boxes also feel randomly thrown into the lessons to me, rather than that they are relevant to the lessons themselves. I vote to remove this box if you're ok with it (being careful to check the lesson alignment and making sure we remove something there if it's overstated. If you'd rather keep them, I agree with @retabak that they deserve a rewrite.

**Comment by flannery-denny** [comment]
@retabak Do you think it would be an improvement to our materials to find and replace all uses of MLR in lesson plans with Mathematical Language Routine?

**Comment by retabak** [comment]
yes, finding + replacing with "Mathematical Language Routine" would be helpful (I don't think we can assume most folks know what MLR is?) but I think we need a source.

I just skimmed other instances of MLRs and I'm not sure they're integrated thoughtfully enough to be useful / meaningful / relevant ...

**Comment by flannery-denny** [comment]
@retabak I'm not advocating for those boxes to stay, but MLRs are referenced in our practices dictionary and this is [the source](https://achievethecore.org/peersandpedagogy/developing-math-language-routines/)

**Comment by retabak** [comment]
Ah. I had no idea.  That pedagogy box just felt like a weird and random insertion that was not very helpful. When I made this issue, I honestly didn't realize that we had these standards in our practices dictionary! (I am not well versed in these MLRs.) 

Knowing that, I think this issue falls under the umbrella of issue #968 which definitely requires a more involved conversation.

**Comment by schanzer** [comment]
@retabak 

This "3 reads" thing is an Ed holdover. I'm not attached to it, and I don't get the sense that it's being used as much as I was told it would be. 

If you think it's useful, then let's make this a checkbox under #968 and close this issue. 

If you don't think it's useful, let's made removing it a checkbox under #1115 and close this issue.

**Comment by retabak** [comment]
I think we have many many standards that we're aligned to. I also think language is interwoven literally everywhere in our curriculum. I don't think these MLRs are getting us much mileage, so.... 

Closing and adding removal to #1115.  

Reopen if you object, @flannery-denny !
