### ISSUE TITLE
refine .subtitle 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1126]
Theoretically `@span[.subtitle]` exists as something we can work with in asciidoc, but it doesn't quite do what I would expect it to, which is to 
- center the subtitle text below the title text
- place the subtitle text vertically close to the title so that it read as if they go together
- be styled to be smaller than the title text but different from the body text.

Two applications where I am consistently interested in using this directive
- pioneer posters (see Bob Moses)
- strategy boxes (see maya-1-spreadsheets/pages/research-on-maya

**Comment by schanzer** [comment]
@flannery-denny let's discuss in our meeting today? Also note that Bob Moses's picture is actual Ajay Bhatt
