### ISSUE TITLE
Determine the most efficient way to address vertical spacing in files like this one from maya-skulls/skull-explore

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1129]
[skull-explore.pdf](https://github.com/bootstrapworld/curriculum/files/9552698/skull-explore.pdf)

There are places where I want a little more vertical space, but `@vspace{1ex}` is too big and nothing smaller works. Could we make a directive for a small vertical space? Or is there CSS that I'm supposed to master?

I also had to take advantage of  `@span{.blankline}` using less vertical space than  `@fitb{}` in order to get this to fit on one page...

**Comment by schanzer** [comment]
@flannery-denny 
Part of what allows us to position a blank line so it stretches to the horizontal end is that we guarantee the browser that the _vertical_ end is fixed. You can change this rule with some CSS:

`body:not(.LessonPlan, .narrativepage) p {min-height: 1.5rem}`

The default is `1.75rem`, but it can be changed to any thing you like.

**Comment by schanzer** [comment]
@flannery-denny is this issue resolved, based on our conversation yesterday?

**Comment by flannery-denny** [comment]
@schanzer Closing the issue and will report back if the local style rule solution isn't solving future issues.
