### ISSUE TITLE
early thoughts / brainstorm for structural math for grades 4-6

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1130]
@schanzer - here is a brain dump / some very early brainstorming! 

https://docs.google.com/document/d/1PwyaEcH3vj0fsytEn69IsjSU_gvjI-13e8AFP0mPM1A/edit#heading=h.c0tc9tafojv

I'd love feedback (or to discuss via zoom) when you've got a chance.

I think some of the stuff here has promise - although some ideas, I'm not so sure about.

I took a lot of inspiration from Illustrative Math. I can either change stuff I took inspiration from so that it is more radically different from their content, or we could credit them if that feels right. I don't necessarily think that conversation needs to happen right now, though.

I've got more ideas but decided to pause for the moment!

**Comment by retabak** [comment]
https://docs.google.com/spreadsheets/d/1IgZ8eVXZJlZqoSPLReRLhuKFPwoPpc2URVhzS8KZDpA/edit?usp=sharing

updated spreadsheet! I'm stuck on fractions. Am thinking I maybe start making worksheets for the other lessons and circle back? Or, we could chat, @schanzer.

**Comment by schanzer** [comment]
@retabak left you a few comments. Yes, let's definitely chat about fractions!

In the meantime, I say start making worksheets for Properties and Order of Operations

**Comment by retabak** [comment]
Closing this and opening a new issue to track progress on my branch!
