### ISSUE TITLE
add either num-opp or num-negate to Bootstrap library

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1131]
as per our Slack discussion: 

Would it be possible to develop a function in Pyret - like num-opp - that spits out the opposite of a number? I can envision uses for it, particularly helping to teach this standard: **6.NS.C.6.a** Recognize opposite signs of numbers as indicating locations on opposite sides of 0 on the number line; recognize that the opposite of the opposite of a number is the number itself, e.g., -(-3)=3 , and that 0 is its own opposite.

When I was in the classroom and using wescheme, I taught lessons on opposite and opposite of an opposite and absolute value using COEs. I didn't know that then that - just meant subtract from zero. It worked out well, though!

REQUEST for @flannery-denny - I proposed naming said function `num-opp` because it's the language in the standard. @schanzer felt that perhaps `num-negate` would more effectively drive home what opposite means (“e.g., -(-3)=3 , and that 0 is its own opposite").  You get to be the tiebreaker! (Tbh, I'm happy with either... but leaning toward `num-opp`.)

**Comment by flannery-denny** [comment]
@retabak I'm a little unclear as to how this directive is going to help students. Could you mock up a workbook page that would help me to understand what you're envisioning?

I feel one way about it if we're focusing on `num-opp(-3)` = 3 and `num-opp(3)` = 3 and `num-opp(0)` = 0 

but, I am less clear on it's usefulness in getting students to make sense of -(-3) or -(-(-3)), neither of which is something I think about as being the focus of the standard on opposites... if this is the focus, I definitely vote for `num-negate` as the name... although, I'm honestly less clear on how a directive will support them in developing understanding here.

**Comment by retabak** [comment]
I think on the one hand, the standard wants kids to think about distance on the number line. - but it's also foreshadowing something much bigger - that multiplying by negative one produces the opposite value, and that multiplying a negative by a negative results in a positive value.

I've had kids struggle to decipher the difference between |3|, -|3|, |-3|, -|-3|, and -(-3). I've used COEs to help them think about the order of operations when they're dealing with situations like above. (Take the opposite first? Or find absolute value first? Circle helps you decide.)

This concept gets even harrier for students when they see |-x| or -|x| and you tell them that x is negative.

[This little kinda corny discussion prompt](https://docs.google.com/document/d/1PeXIRHKizfcSSzeY7HZHsHFddqX930KCGPdN7yf-TJk/edit) has also faciliated useful conversation with my students around absolute value compared to opposite. I think a similar prompt could fit really organically into a lesson that teaches the functions `num-opp` and `num-abs`.

I agree that the standard is not interested in getting kids to make sense of -(-(-3))).

The more I write about this, the more I think `num-opp` is the way to go...

**Comment by retabak** [comment]
@schanzer 
Kids can quickly and easily grasp that "opposite" means flip the sign and that absolute value means "find the distance," but those core understanding seem to evaporate when kids must also consider order of operations. (Absolute value is also introduced in sixth grade.)

For instance, kids see -|-3| and jump to conclusions like, "Absolute value is always positive so that equals 3!" or "There are two negatives so that's positive 3!" 

I've also seen kids struggle to reason through something like -x = 3.

**Comment by schanzer** [comment]
@retabak 

If they quickly grasp that, then why do we need this new primitive? Is it because you want to link this to circles of evaluation? (Not being critical, just making sure I understand the reasoning)

**Comment by retabak** [comment]
yep!

**Comment by schanzer** [comment]
@retabak ok, that's really helpful. In that case, I would strongly push for `num-negate`, since that's the mathematical operations being performed and you're saying that kids don't have a problem with the notion that _opposite = negate_.

**Comment by retabak** [comment]
@schanzer 
I'm not sure I understand your reasoning, but... I'm comfortable with `num-negate` and it seems like you have a strong opinion. So, let's do it!

**Comment by schanzer** [comment]
@retabak `num-negate` is now added to the Algebra library. We can move it to an early-math library once you've fleshed out more ideas.
