### ISSUE TITLE
replace "data set" with "dataset"

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1138]
I know that I could do this myself, but I'm kind of terrified of the general find and replace...

**Comment by retabak** [comment]
I raised this same issue a year ago! (Issue #626)

Makes me think we should have like a style book or something with all of these possible discrepancies?

**Comment by flannery-denny** [comment]
@retabak The style book might be a decent start, but the real story is that we're human and, while I hope to make fewer mistakes, I'm sure that I will continue to make them as my brain focuses on writing lessons and isn't fully prioritizing spelling consistency... so we need to do periodic audits...  Perhaps we should make a list of things that need to be audited for before each release? @schanzer There are other things besides spelling / spacing discrepancies that should be audited for every year, like "Run". Is there a good place to make a list of these that won't get lost from release to release?

**Comment by schanzer** [comment]
@flannery-denny great idea. I've added these two items to the team calendar (next release date is due 9/25!)
