### ISSUE TITLE
-F is not replacing pdfs...

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1140]
- [x] I built `./build-pathway maya --proglang spreadsheets --book -F -w` and it did what I'd expect it to. Then I modified an asciidoc and saved it and `./build-pathway maya --proglang spreadsheets --book -F -w`again.

The html updated
![Screen Shot 2022-09-22 at 10 54 28 AM](https://user-images.githubusercontent.com/66691020/191780972-d27807b0-cd8f-4b02-821f-2774002968b9.png)

And the pdf did not.
![Screen Shot 2022-09-22 at 10 54 46 AM](https://user-images.githubusercontent.com/66691020/191781060-abd692d0-a193-4bdb-b79f-c91f637e6e5e.png)

- [ ] `-f` and `-F` should also be able to update the title of a file in the materials section, but neither is accomplishing that.

![Screen Shot 2022-09-22 at 11 05 38 AM](https://user-images.githubusercontent.com/66691020/191783886-ca09c069-a92b-4e90-bf43-2bad5002defd.png)
![Screen Shot 2022-09-22 at 11 05 49 AM](https://user-images.githubusercontent.com/66691020/191783904-814cf139-4d00-4605-838a-801f4b1af02c.png)

**Comment by flannery-denny** [comment]
ds26gte - By default, PDFs are not built, right? You have to. --book

schanzer
Correct

Flannery Denny
Sorry. I’m pretty sure that I did do ./build-pathway maya --proglang spreadsheets --book -F but unfortunately something changed about how things stay around in my terminal recently and I can’t confirm. I’ll close the issue and report again if it repeats. Any chance of making it so that the history of the command line I typed in doesn’t disappear during the build?

**Comment by flannery-denny** [comment]
@ds26gte First point seems to have been resolved. I'm not seeing improvement on the second task.

**Comment by ds26gte** [comment]
This is a case where comparing file timestamps of adoc vs html vs pdf isn't enough, as the lesson plan adoc has a link to a page, and the page's title has changed. Thus the link text used by the lesson plan's html/pdf should change, even though the lesson plan adoc remains the same.

I've updated build-pathway to mark lesson plan adoc's for regeneration if any pages within the lesson have changed. If the lesson plan adoc refers to pages outside the lesson, the problem remains. We should evaluate if this is acceptable. The solution is pretty drastic: regenerate lesson plans for every biuild (even unforced).

**Comment by schanzer** [comment]
@flannery-denny I think you suggested optimistically closing this in our meeting yesterday, right?
