### ISSUE TITLE
build pathway-independent adocs only when building without explicit pathway argument

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#1141]
This is suggested because, the pathway-independent adocs in `shared/langs/**/docroot/` have `@lesson-link`s to potentially unbuilt lessons and these causes distracting missing-file warnings. 

Building without a pathway argument leaves no lesson unbuilt and none of the requested files would be missing.

![noarg](https://user-images.githubusercontent.com/3708729/191801680-e8734ce4-3745-4f21-8015-4e51122b0752.png)

**Comment by schanzer** [comment]
Confirming this no longer throws the missing-file warnings. Thanks!
