### ISSUE TITLE
Student-facing learning goals wording is inconsistent

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1143]
Some our lessons use the framing "let's... " others use "I can..."  Standardize to let's.

- [x] bar and pie
- [x] boxplot
- [x] checking your work
- [x] choosing your dataset
- [x] codap bar
- [x] codap exploring
- [x] codap transformers 1
- [x] codap transformers 2
- [x] combination
- [x] permutation
- [x] composing table operations
- [x] computing needs all voices
- [x] contracts
- [x] coordinates
- [x] correlations
- [x] custom scatter plots
- [x] data collection
- [x] data cycle
- [x] debugging
- [x] defining table functions
- [x] defining values
- [x] distance formula
- [x] ds intro
- [x] ethics
- [x] flags
- [x] function composition
- [x] function definition
- [x] function notation
- [x] functions can be linear
- [x] functions dr
- [x] functions examples definitions
- [x] functions for character animation
- [x] functions make life easier
- [x] functions vertical line test
- [x] grouped samples
- [x] histograms
- [x] histograms 2
- [x] hoc-data
- [x] collision
- [x] ineq 1
- [x] ineq2
- [x] ineq3
- [x] lr
- [x] lookups
- [x] making game images
- [x] measures of center
- [x] numbers in games
- [x] order of op
- [x] piecewise
- [x] player animation
- [x] probability
- [x] problem decomp
- [x] scatter plot
- [x] simple data types
- [x] standard deviation
- [x] surface area
- [x] table and display functions
- [x] table functions
- [x] threats to validity

Note: Reactive doesn't have lesson goals.
Note: The Fall2023 branch doesn't have updated versions of social studies files, so I have not adjusted any learning goals from those pathways.

**Comment by schanzer** [comment]
I think standardizing them is worth doing, but low priority.

**Comment by flannery-denny** [comment]
I’m writing a lot of them these days so if either of you have a preference, lmk.

Flannery

**Comment by retabak** [comment]
I like the general vibe of "Let's" but don't have strong feelings. ("Let's"
says "c'mon team!" whereas "I can" is obviously individual-focused.)

**Comment by schanzer** [comment]
Agreed. I'd like to stick to those.

**Comment by flannery-denny** [comment]
- [ ] @retabak Noting that some of these lessons use @vocab{expression} which I believe you've removed from the glossary. Do we need to make a new issue to audit all instances of @vocab{expression} and update them to @vocab{arithmetic expression} or @vocab{algebraic expression}? or have you already done that on your branch and will resolve it with the merge? or was the change merely additive and this is a non-issue?
- [ ] @schanzer please review all of the lesson goals I committed and make sure wording works for you. 
- [ ] the lesson goals for piecewise functions conditionals and player animation both distinguished between conditionals and piecewise functions in a way that I'm not certain about. Wondering if this language is still current or is a holdover from before we made the starterfile switch in the piecewise lesson? Please have a look and modify as needed.

Close if satisfied.

**Comment by retabak** [comment]
Good catch re: expression! Yes, we should create a new issue to audit instances of @vocab{expression}.

**Comment by schanzer** [comment]
@flannery-denny This all looks terrific! 

re: piecewise: the difference in language is current. Thanks for checking, and awesome work pushing this  over the finish line!
