### ISSUE TITLE
Consider Desmos activities for Alg2 lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1161]
**Update from 4/2 curriculum meeting: We will close this issue once @schanzer has reviewed Algebra 2 Desmos activities. We've decided not to link to other Desmos things as supplemental.**

Identify whether there are activity ideas worth linking to from our supplemental resources section.

Don't link to stuff that costs money. Only entirely free things!

@schanzer @flannery-denny 
Spent some time (finally!) going through Desmos-created activities. Here are a bunch that would fit well into our lesson. We could (1) add these in as supplementary/optional materials, or (2) find more meaningful ways to weave them into the lesson. If we go with option 2, I think we might want to modify the activites (e.g., shorten them) so that just the most pertinent stuff remains.

Histograms - [Creating Histograms](https://teacher.desmos.com/activitybuilder/custom/5a4fce73b473640e051f9199?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da8a6474d5c010a4455b470)

Mean - [Make it Balance](https://teacher.desmos.com/activitybuilder/custom/59de912a3f06a210c73513fa?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da8a6474d5c010a4455b470)

Standard Deviation - [What's My Number?](https://teacher.desmos.com/activitybuilder/custom/591f061bc98f7b726700e66b?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da8a6474d5c010a4455b470) - add to pedagogy box on MAD

Linear Regreeession - [Fit Flights](https://teacher.desmos.com/activitybuilder/custom/5c5bc938531af975828d9e92?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da8a6474d5c010a4455b470)

Vertical Line Test - [Guess My Rule](https://teacher.desmos.com/activitybuilder/custom/5e54200051afec695ca0a71a?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da6476150c0c36a0caf8ffb) and [Card Sort: Functions](https://teacher.desmos.com/activitybuilder/custom/579b87d30a4f3e3512892937?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da6476150c0c36a0caf8ffb)

Piecewise Functions - [Domain and Range Introduction](https://teacher.desmos.com/activitybuilder/custom/57d6b323d5b6478408b8748b?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da6476150c0c36a0caf8ffb) 

Simple Inequalities - [Inequalities on the Number Line](https://teacher.desmos.com/activitybuilder/custom/57d9fdc6ebf48f73093807b2?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da647f16254f22e20fd1035)

Compound Inequalities - [Compound Inequalities on the Number Line](https://teacher.desmos.com/activitybuilder/custom/57b7f808ce9904f705558c4e?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da647f16254f22e20fd1035)

Alg2 ideas (@schanzer - I think you can probably draw some inspiration from many of these!)
[Card Sort: Modeling](https://teacher.desmos.com/activitybuilder/custom/5798ea85bef943016af8a240?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da649ac6254f22e20fd1107) 
[Match My Parabola](https://teacher.desmos.com/activitybuilder/custom/5605bb6200701ed10fb0931a?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5e73b204d560367270838c4b)
[Match My Exponential](https://teacher.desmos.com/activitybuilder/custom/5aaad32fb74c9051fb578bd9?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5e73b275913f047206662889)
~[Match My Line](https://teacher.desmos.com/activitybuilder/custom/5605bb5f00701ed10fb09314?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5e73b204d560367270838c4b)~
[Quadratic Functions - 9 Desmos activities
](https://teacher.desmos.com/collection/5da649da5a46437eff2441d0?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections)[Exponential Functions - 9 Desmos activities
](https://teacher.desmos.com/collection/5da6462c8b305273be677729?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections)
~[Commuting Times](https://teacher.desmos.com/activitybuilder/custom/575f221e56a5e3a7573ddd0e?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da6476150c0c36a0caf8ffb)~
[Fit Fights](https://teacher.desmos.com/activitybuilder/custom/5c5bc938531af975828d9e92?utm_campaign=October%20Newsletter&utm_medium=email&_hsmi=229056727&_hsenc=p2ANqtz--GGKiUS0QuAGQtFL8wgvqYTZ-Kn_g5Ugxjyi3fiOip4bPoTYBJW5y6SjD1sWuTnz4PtwTOl3-wIKk2KgQ3Lm3XrCCQBA&utm_content=228808976&utm_source=hs_email&collections=featured-collections%2C5da8a6474d5c010a4455b470)

**Comment by retabak** [comment]
Thinking maybe this fell off the radar. Adding to Curriculum meeting agenda. I'm not sure what next steps might be here and would like to discuss.

**Comment by schanzer** [comment]
Adding to May milestone, because we should either link to good activities (which takes very little time) or just close the issue (even less time!).

**Comment by schanzer** [comment]
I've copied the Alg2 desmos activities that seem promising to #1345 , so this is ready to close!
