### ISSUE TITLE
Allow non-Pyret prereqs to use canonical lesson names

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1163]
(This is Emmanuel re-writing Flannery's comment to reflect the changed nature of the issue)

**Note: this should be done entirely on the Maya branch**

- Suppose lessons A and B are available in both Pyret and language X, and B lists A as a prerequisite
- When building in both languages, the build script automatically knows to append `-X` to both lesson names, and to the prerequisite list for lesson B in the dependency graph.
- This all works beautifully!

But now...
- Suppose lessons A and B are availably ONLY in language X, and B lists A as a prerequisite
- When building in X, the build script appends `-X` to both lesson names, but _fails_ to append it to the prerequisite list for lesson B in the dependency graph.
- As a result, no lessons list their dependencies (and this probably breaks some JS page formatting as well, since the dependency graph is not well-formed)

(We never noticed this before with CODAP, because Rachel just _happened_ to name all her lessons with `-codap` at the end.)

**Comment by ds26gte** [comment]
> 
> (We never noticed this before with CODAP, because Rachel just _happened_ to name all her lessons with `-codap` at the end.)

JFYI, this isn't true.  The codap lessons happen to have a codap- prefix (not suffix), but that's a legit part of the lesson name, and not tacked on by the build.

Currently all @lesson-prereqs use only the non-postfixed lesson name. I think we want to persist with this practice, but let me know if you want the option.
