### ISSUE TITLE
worksheet showing up in student workbook and opt-printable workbook?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1164]
I don't think this is a big deal, but I'm so confused as to why it's happening?!

[This worksheet](https://bootstrapworld.org/materials/fall2022/en-us/lessons/bar-and-pie-charts/pages/bar-and-pie-notice.html) is clearly specified to be @opt-printable-exercise every time it appears. What's going on?

**Comment by schanzer** [comment]
@retabak it's listed as a required workbook page in `workbook-pages.txt`. It sounds like every use of @opt-printable-exercise is wrong, and should be corrected. _That's_ the bug
