### ISSUE TITLE
Better handling of copycat standards

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1165]
Many states basically photocopy common core and CSTA standards. For example:

8.F.A.1 exists in common core, but also in Iowa and MA standards. That means the same standard shows up in three different dictionaries! We handle this right now by prefixing them in each dictionary. So we have `8.F.A.1` in common core, but also `IA.8.F.A.1` and `MA.8.F.A.1` in the other dictionaries. This seems like a reasonable approach!

_However.._
In `standards-and-lessons`, that means we need three duplicate entries like this:
```
    ("8.F.A.1"
     "contracts"
     )
```

I propose that we use the same solution that we currently do for vocabulary words with multiple definitions:

```
    (("8.F.A.1" "IA.8.F.A.1" "MA.8.F.A.1")
     "contracts"
     )
```

(NOTE: this should be implemented in the `MA-standards` branch)

**Comment by ds26gte** [comment]
Looks like the fact that {8.F.A.1, IA.8.F.A.1, MA.8.F.A.1} are the same but slightly differently named standard in different dictionaries is not really crucial for this shorthand. 

We could use it even if the several standards specified are genuinely different standards, and possibly belong to the same dictionary!

**Comment by flannery-denny** [comment]
@schanzer when I force build the oklahoma pathway, I'm getting a long list of warnings that seem related to the copycat standards...

> 👨‍💻CALLING RACKET IN BATCH MODE
> -----------------------------------------------------------
> WARNING: File lessons/combinatorics-permutation/slides-pyret.id not found
> 
> WARNING: File lessons/combinatorics-combination/slides-pyret.id not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard AL.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard AR.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard CA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard CO.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard CT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard DE.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard GA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard HI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard ID.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard IL.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard IA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard KS.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard KY.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard LA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard ME.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard MD.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard MA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard MI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard MS.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard MO.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard MT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard NV.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard NH.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard NJ.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard NM.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard NY.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard NC.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard ND.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard OH.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard OR.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard PA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard RI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard SD.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard TN.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard UT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard VT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard WA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard WV.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard WI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms/index.adoc: Standard WY.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard AL.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard AR.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard CA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard CO.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard CT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard DE.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard GA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard HI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard ID.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard IL.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard IA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard KS.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard KY.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard LA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard ME.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard MD.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard MA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard MI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard MS.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard MO.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard MT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard NV.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard NH.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard NJ.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard NM.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard NY.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard NC.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard ND.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard OH.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard OR.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard PA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard RI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard SD.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard TN.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard UT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard VT.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard WA.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard WV.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard WI.6.P.A not found
> 
> WARNING: Lesson plan lessons/histograms2/index.adoc: Standard WY.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard AL.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard AR.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard CA.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard CO.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard CT.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard DE.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard GA.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard HI.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard ID.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard IL.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard IA.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard KS.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard KY.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard LA.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard ME.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard MD.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard MA.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard MI.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard MS.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard MO.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard MT.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard NV.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard NH.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard NJ.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard NM.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard NY.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard NC.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard ND.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard OH.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard OR.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard PA.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard RI.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard SD.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard TN.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard UT.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard VT.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard WA.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard WV.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard WI.6.P.A not found
> 
> WARNING: Lesson plan lessons/measures-of-center/index.adoc: Standard WY.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard AL.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard AR.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard CA.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard CO.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard CT.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard DE.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard GA.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard HI.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard ID.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard IL.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard IA.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard KS.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard KY.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard LA.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard ME.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard MD.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard MA.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard MI.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard MS.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard MO.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard MT.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard NV.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard NH.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard NJ.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard NM.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard NY.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard NC.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard ND.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard OH.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard OR.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard PA.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard RI.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard SD.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard TN.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard UT.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard VT.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard WA.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard WV.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard WI.6.P.A not found
> 
> WARNING: Lesson plan lessons/box-plots/index.adoc: Standard WY.6.P.A not found

**Comment by retabak** [comment]
I observed this yesterday, too! Can't remember what I was building, though. (Sorry!)

**Comment by schanzer** [comment]
@retabak that's how branches work! Pioneers isn't master, so it won't get the updates until we manually merge master into it.

You can do it yourself: git merge master

**Comment by retabak** [comment]
ah! That explains it. Thanks :)

**Comment by schanzer** [comment]
I've just merged from master, so this issue should go away after your next pull and forced build. :)
