### ISSUE TITLE
live on web - HOC assorted issues

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1173]
- There are no descriptions for two HOC activities [here](https://bootstrapworld.org/materials/fall2022/en-us/courses/hour-of-code/) (screenshot below), nor do they have helpful / descriptive titles. (When the descriptions are added, I think it might be worth noting that these take WAY longer than an hour. I actually remember my first encounter with our website, and thinking, "Oooh, I'll check out Hour of Code to get a little teensy taste of what Bootstrap is about." I think I skimmed for two minutes then navigated away. I know @flannery-denny is addressing this issue with the Snowman task!)

![image](https://user-images.githubusercontent.com/87144723/196795119-5e5b82c4-b7c2-44d9-b8b3-74251f58b943.png)

- Should the HOC activities go to lesson plans pages, like the Hour of Data does? Seems weirdly inconsistent.
- While I'm at it... it also feels a bit odd that the HOC stuff has all the same stuff at the bottom as our other curricula, i.e. "Ordering Student Workbooks?", "Teaching Remotely?", "Other Teacher Resources." I'm just noticing these here, but they feel out of place. Perhaps I'm wrong, but I think people who are checking out HOC resources want just a little taste of BS. We don't have HOC in our workbooks, anyhow.
- Weird blank bullet on the Hour of Data lesson table [here](https://bootstrapworld.org/materials/fall2022/en-us/lessons/hoc-data/index.shtml?pathway=hour-of-code) (screenshot below), + the lesson slides link (obviously) doesn't work, as we do not have lesson slides for this activity in Desmos. 
![image](https://user-images.githubusercontent.com/87144723/196796063-1d8a394b-e1fe-4716-a04f-80b5ff0982cb.png)

**Comment by flannery-denny** [comment]
@retabak this is a big regression and it looks like the result of autogeneration. I know that I had images and text for all of these for the January 2022 release and there shouldn't have been any updates since then. Hoping @ds26gte or @schanzer can restore this pathway's page to the jan22 version?
