### ISSUE TITLE
Algebra II

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1177]
The shortest possible data science pathway that gets kids to scatter plots, linear regression and then new lessons with scatterplots that don't work with linear regression and require use of inverse functions.

- [x] ask MA for quadratic dataset to experiment with
[quadratic data sets from MA](https://mail.google.com/mail/u/0?ui=2&ik=c30a6a5d0b&attid=0.1.3&permmsgid=msg-f:1751201303536910322&th=184d844eab84bff2&view=att&disp=safe)
- [x] ask MA for exponential dataset to experiment with
[possibly exponential dataset from MA](https://drive.google.com/drive/folders/1JaFHzpiyiJdotYiTjyqrp7vuQXayC30J?usp=share_link)
- [x] find MA alg 2 framework
[Massachusetts Mathematics Curriculum Framework — 2017 - Model Alg 2.pdf](https://github.com/bootstrapworld/curriculum/files/9862407/Massachusetts.Mathematics.Curriculum.Framework.2017.-.Model.Alg.2.pdf)
- [x] check whether there is an alg 2 book people like.
[illustrative mathematics alg 2](https://tasks.illustrativemathematics.org/blueprints/A2)

### Definite Standards to Target

- [x] HSF.IF.C.7 - Graph linear and quadratic functions and show intercepts, maxima, and minima.
- [x] HSF.LE.A - Construct and compare linear, quadratic, and exponential models and solve problems.🏴‍☠️
- [x] HSF.LE.A.1 - Distinguish between situations that can be modeled with linear functions and with exponential functions.🏴‍☠️
- [x] HSF.LE.A.1.A - Prove that linear functions grow by equal differences over equal intervals, and that exponential functions grow by equal factors over equal intervals.
- [x] HSF.LE.A.1.B - Recognize situations in which one quantity changes at a constant rate per unit interval relative to another.
- [x] HSF.LE.A.2 - Construct linear and exponential functions, including arithmetic and geometric sequences, given a graph, a description of a relationship, or two input-output pairs (include reading these from a table).
- [x] HSF.LE.B - Interpret expressions for functions in terms of the situation they model. 🏴‍☠️
- [x] HSF.LE.B.5 - Interpret the parameters in a linear or exponential function in terms of a context.🏴‍☠️
- [x] HSS.ID.B.6.A - Fit a function to the data; use functions fitted to data to solve problems in the context of the data. Use given functions or choose a function suggested by the context. Emphasize linear, quadratic, and exponential models.🏴‍☠️

### Possible Standards to Target

HSA.SSE.B.3.C - Use the properties of exponents to transform expressions for exponential functions.
HSA.REI.B.4 - Solve quadratic equations in one variable.
HSF.LE.A.3 - Observe using graphs and tables that a quantity increasing exponentially eventually exceeds a quantity increasing linearly, quadratically, or (more generally) as a polynomial function.
HSF.LE.A.4 - For exponential models, express as a logarithm the solution to abct = d where a, c, and d are numbers and the base b is 2, 10, or e; evaluate the logarithm using technology.
HSF.BF.B.4.A - Solve an equation of the form f(x) = c for a simple function f that has an inverse and write an expression for the inverse.
HSF.BF.B.4.C - Read values of an inverse function from a graph or a table, given that the function has an inverse.

### Standards we'll probably ignore
HSA.SSE.B.3.A - Factor a quadratic expression to reveal the zeros of the function it defines.
HSA.SSE.B.3.B - Complete the square in a quadratic expression to reveal the maximum or minimum value of the function it defines
HSA.REI.B.4.A - Use the method of completing the square to transform any quadratic equation in x into an equation of the form (x - p)2 = q that has the same solutions. Derive the quadratic formula from this form.
HSA.REI.B.4.B - Solve quadratic equations by inspection (e.g., for x^2 = 49), taking square roots, completing the square, the quadratic formula and factoring, as appropriate to the initial form of the equation. Recognize when the quadratic formula gives complex solutions and write them as a ± bi for real numbers a and b.
HSF.IF.C.8.A - Use the process of factoring and completing the square in a quadratic function to show zeros, extreme values, and symmetry of the graph, and interpret these in terms of a context.

**Comment by schanzer** [comment]
Running TODOS

**All**

- [ ] reference _linear term_, _quadratic term_, etc.
- [ ] Exercises where students distinguish between linear, quadratic, and exponential models based on scatter plot
- [ ] Exercises where students distinguish between linear, quadratic, and exponential models based on tables
- [ ] Exercises where students distinguish between linear, quadratic, and exponential models based on a written description
- [ ] Exercises devoted entirely to inverse functions

**Quadratics**

- [ ] worksheets shoudl allow calculation of  maxima/minima and intercepts
