### ISSUE TITLE
Image citation/captioning Reorganization spec

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1179]
Confirmed implementation from Shriram (10/26):

1) Caption displayed below an image - some kind of short description, adding context for a sighted user
2) Alt-text displayed on mouseover - full citation
3) Screenreader-only text - full description, providing context for a non-sighted user
4) Pathway-wide attribution index, just like the alignments file.

-----------------------------
Dorai has made infrastructure that allows us to include the source of an image as its fifth argument, which appears beneath each image. Now that we've done more thinking about citing images we may want to adapt that infrastructure.

We need to confirm where the directors stand on where information about image sources will be displayed. 
- Is a mouse-over citation reveal enough?
- Do we want a works cited page for each social studies unit that is accessible to teachers and students?
- Do we want image citations to appear on the page in web format but not workbook format?

Initial brainstorming about what might be useful from a curriculum perspective:
- Perhaps the image caption beneath an image should not show the source? and an explanation of what the image is might be more useful to students interfacing with a workbook page?
- If we do mouseover citations, perhaps we want them auto-appended to the screenreader text?

(Addition by @schanzer, 10/26 )
We also need to think about implementation, since the `@image` tag already has a lot of arguments (some optional!) and adding half a dozen more feels like a recipe for mistakes. One option is to make an `image-files.rkt` dictionary like we did for starter files, and provide the file path, short caption, full description, and citation info in a structured format. 

I propose a per-lesson dictionary, with entries like this (@ds26gte please weigh in on this!):

```
'(sw-where-in-asia.png "Location of Kilns used for export" "A map of southwest China, showing locations of kilns near the coast that were used for exports"  "Journal" "National Maps" "May, 2022" "Page 66" )
```

When including an image, we can just use the standard `@image` tag, with arguments solely for filename and size. The build script can compare the filename to the dictionary, and include proper captions, alt text, etc. It can also produce a warning if an image isn't in the dictionary. And finally, it could combine all the dictionaries into a single citation page for each pathway, allowing us to show exactly where every piece of media we use came from.

This has the benefit of backwards-compatibility: none of the existing `@image` tags _need_ to change. Everything will still work! Over time, we can move all the captions out of those tags and into these dictionaries.

Previous thinking can be seen in #1142

**Comment by schanzer** [comment]
Closing in favor of #1197
