### ISSUE TITLE
bug - live on web - standards page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1181]
Lessons are being listed multiple times! https://bootstrapworld.org/materials/fall2022/en-us/Alignments.shtml

![image](https://user-images.githubusercontent.com/87144723/198703869-e72b72c9-a516-4218-aa28-dbaf8779b19d.png)

**Comment by schanzer** [comment]
@retabak not related to #1165 . I've adjusted the issue.
