### ISSUE TITLE
standards alignment for hoc lessons!

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1183]
we need these in order to list our lessons with hour of code

**Comment by flannery-denny** [comment]
@schanzer - please confirm that you feel good about these alignments.

**Hour of Data:**

ccmath
- "6.RP.A.3" "Use ratio and rate reasoning to solve real-world and mathematical problems, e.g., by reasoning about tables of equivalent ratios, tape diagrams, double number line diagrams, or equations."
- "7.RP.A.3"  "Use proportional relationships to solve multistep ratio and percent problems."
- "7.SP.A.1" "Understand that statistics can be used to gain information about a population by examining a sample of the population; generalizations about a population from a sample are valid only if the sample is representative of that population. Understand that random sampling tends to produce representative samples and support valid inferences."
- "7.SP.B"  "Draw informal comparative inferences about two populations."
- "HSS.ID.B.6"  "Represent data on two quantitative variables on a scatter plot, and describe how the variables are related."
- "HSS.IC.B" "Make inferences and justify conclusions from sample surveys, experiments, and observational studies."
    
csta
- "1B-DA-07" "Use data to highlight or propose cause-and-effect relationships, predict outcomes, or communicate an idea."

k12cs
- "6-8.Computing Systems.Devices""The interaction between humans and computing devices presents advantages, disadvantages, and unintended consequences. The study of human–computer interaction can improve the design of devices and extend the abilities of humans."

ngss
- "MS-SEP1-8" "Ask questions that challenge the premise(s) of an argument or the interpretation of a data set."
- "MS-SEP1-2" "Ask questions that arise from careful observation of phenomena, models, or unexpected results, to clarify and/or seek additional information."
- "MS-SEP4-4" "Analyze and interpret data to provide evidence for phenomena."
- "MS-SEP4-7" "Analyze and interpret data to determine similarities and differences in findings."
- "MS-SEP5-4" "Apply mathematical concepts and/or processes (such as ratio, rate, percent, basic operations, and simple algebra) to scientific and engineering questions and problems."
- "HS-SEP5-2" "Use mathematical, computational, and/or algorithmic representations of phenomena or design solutions to describe and/or support claims and/or explanations."
- "HS-SEP5-4" "Use simple limit cases to test mathematical expressions, computer programs, algorithms, or simulations of a process or system to see if a model “makes sense” by comparing the outcomes with what is known about the real world."  
    
**Hoc-winter-parley**

ccmath
- "5.G.A" "Graph points on the coordinate plane to solve real-world and mathematical problems."
- "5.G.A.2" "Represent real world and mathematical problems by graphing points in the first quadrant of the coordinate plane, and interpret coordinate values of points in the context of the situation."
- "5.G.B" "Classify two-dimensional figures into categories based on their properties."
- "6.NS.C.6.C" "Find and position integers and other rational numbers on a horizontal or vertical number line diagram; find and position pairs of integers and other rational numbers on a coordinate plane."
- "7.G.A" "Draw, construct, and describe geometical figures and describe the relationships between them."
- "7.G.A.2" "Draw (freehand, with ruler and protractor, and with technology) geometric shapes with given conditions. Focus on constructing triangles from three measures of angles or sides, noticing when the conditions determine a unique triangle, more than one triangle, or no triangle."

csta 
- "3A-DA-09"
     "Translate between different bit representations of real-world phenomena, such as characters, numbers, and images."
- "1B-AP-12" "Modify, remix, or incorporate portions of an existing program into one's own work, to develop something new or add more advanced features."
- "1B-AP-15"  "Test and debug (identify and fix errors) a program or algorithm to ensure it runs as intended."

k12cs
- "6-8.Algorithms and Programming.Variables"
   "Programmers create variables to store data values of selected types. A meaningful identifier is assigned to each variable to access and perform operations on the value by name. Variables enable the flexibility to represent different situations, process different sets of data, and produce varying outputs."

**Comment by schanzer** [comment]
@flannery-denny looks good! The one things I'd take out are "HS-SEP5-4" from the Hour of Data (I don't see any limit cases being used) and "7.G.A.2" from Winter-Parley (we aren't doing anything involving properties that define multiple or unique triangles).

**Comment by flannery-denny** [comment]
@schanzer noting that hoc asked about alignment to PARCC / Smarter Balanced Assessment Skills. Never heard of them, but wondering if we want them in our library.

**Comment by schanzer** [comment]
The PARCC tests are the $1b monopoly that Pearson got to develop a new generation of tests accompanying the common core. They've largely faded from relevance, so I think we can safely ignore them.

**Comment by flannery-denny** [comment]
@schanzer 
If this standard aligns with hoc,

> “6.RP.A.3” “Use ratio and rate reasoning to solve real-world and mathematical problems, e.g., by reasoning about tables of equivalent ratios, tape diagrams, double number line diagrams, or equations.”

but the `standards-and-lessons.rkt` file shows

> (,(all-cc-states “6.RP.A.1”)
>      “flags”
>      )
>     (,(all-cc-states “6.RP.A.3.D”)
>      “flags”
>      )

Does that mean that the `standards-and-lessons.rkt` file only includes the standards that we actively align to and I need to add `6.RP.A.3` to the file?

**Comment by schanzer** [comment]
> Does that mean that the standards-and-lessons.rkt file only includes the standards that we actively align to and I need to add 6.RP.A.3 to the file?

@flannery-denny Bingo. :)

**Comment by flannery-denny** [comment]
@schanzer Will do. But I think it used to include all of the standards so that we could get a report of which standards we weren't addressing.

**Comment by schanzer** [comment]
@flannery-denny that report is generated by looking at ALL the dictionaries. This file has _never_ included all of the standards.

**Comment by flannery-denny** [comment]
@schanzer I have added alignments for these hoc lessons to everything but NGSS, because I cannot find that section of the the `standards-and-lessons.rkt`, which has become extremely cumbersome.  

It seems very unlikely that none of our lessons have been aligned to the NGSS standards? 
But, if that is so, it's a big gap to address.  

I'm guessing it's more likely that there's an alternate name for them that you would be able to come up with, search for and tell me the line number to look for in the file...

**Comment by schanzer** [comment]
@flannery-denny we've only aligned to the NGSS _practices_, but not the standards. see https://github.com/bootstrapworld/curriculum/blob/master/shared/langs/en-us/practices/practices-and-lessons.rkt

**Comment by flannery-denny** [comment]
@schanzer I added the NGSS standards from the above list to lessons and standards for hoc-data, but NGSS standards are not available in the drop down menu.

**Comment by schanzer** [comment]
@flannery-denny thanks! Unfortunately, the NGSS practices need to be added to lessons-and-practices, not lessons-and-standards.

**Comment by flannery-denny** [comment]
@schanzer I found them in the standards dictionary. I don't think they are practices...
![Screen Shot 2022-11-08 at 12 01 40 PM](https://user-images.githubusercontent.com/66691020/200641242-077dde76-de21-41dc-8d9f-d91f69d052c2.png)

**Comment by schanzer** [comment]
@flannery-denny upon further investigation, it looks like the ONLY ngss standards we have in the dictionary are actually _practices_. There are over a hundred content standards, of which only our physics material is really aligned.

That being said, I'm comfortable keeping the ngss "standards" where they are for now. And when I build the HOC pathway, here's what I see for hoc-data:

![image](https://user-images.githubusercontent.com/77126/200844607-9981d91a-b298-441e-badf-30167b78d8e4.png)

Closing as per your recommendation, since this issue is resolved.
