### ISSUE TITLE
Whatever happened to linearity starter files?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1191]
https://code.pyret.org/editor#share=1n9x5gSOiBbmfo-VLZIirB8P1NjkjS3gS&
https://code.pyret.org/editor#share=1VpOqRgXqWaNgJf8YHAeRqnFU5W6qTLiN
https://code.pyret.org/editor#share=1AQi6tgmr8WsR9wXfi_8ylra1pnb0wUh9

They were in Spring 2021, but they're all gone now.

**Comment by flannery-denny** [comment]
@schanzer If I remember correctly, I deemed them not integral to the new structure of the lessons and put them in the additional exercises section... then, when @retabak reviewed the new lessons, she didn't think they were worth including as optional exercises.

**Comment by retabak** [comment]
hi! Are we talking about functions-can-be-linear?

Embarrassingly, I do not remember this well. I do remember feeling like that lesson had SO MUCH STUFF and was overwhelming, and I remember paring it down. 

If you shared them with teachers who loved them, I'd say that they belong back in optional exercises. And... sorry!
