### ISSUE TITLE
Image Infrastructure Update

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1197]
### The Problem
Demands on our use of images have grown a LOT since 2020:

- We added image _captions_ in 2021
- Flannery led the addition of screenreader-friendly _descriptions_ in 2022
- Flannery's work on the Social Studies branch has led to the need for image _citations_ as well

Dorai has heroically extended the `@image{...}` directive with optional arguments this whole time. But each argument adds a layer of complexity and an opportunity for mistakes. (QUICK! What is the size and description of the following image: `@image{images/box-n-whisker-plot.png, 300, "A sample box-and-whisker plot"}` -- lmfao no ur wrong the caption is "300" silly!)

We've also accumulated some technical debt, with zero standardization on _where image files live_ within a lesson. Sometimes they're in a dedicated `images/` directory, but sometimes they're in the `pages/` directory. And sometimes they're in both!

With the addition of image citations coming down the pike in 2023, it's time to address this problem.

 ### Proposed Solution

- All lesson images should live inside an `images` folder within the lesson plan (just like the `pages` directory).
- This folder should include a `lesson-images.json` file, which acts as a dictionary for all the relevant lesson information
- The dictionary has the following structure[*]:

```
[
  "box-plot.png" : {
        "caption" : "distribution of US Income in 2003"
        "description" : "a box plot showing a right skew"
        "source" : "retrieved from data.gov on April 15th, 2022"
        "license" : "Creative Commons 2.0 - ND - SA"
  },
  "red-star.png" : {
        "caption" : ""
        "description" : "an image of a solid, red star"
        "source" : "Created by the Bootstrap Team"
        "license" : "Creative Commons 4.0 - NC - SA"
  },
]
```

- All `@image` directives include nothing more than the image path and (optionally) the size of the image. For example:
```
@image{../images/box-plot.png, 250}
OR
@image{../images/box-plot.png}
```
- When building a lesson, we perform the normal integrity checks (does the image exist? Does it have the required fields?) and generate the appropriate markup. For example, the directive `@image{image1.png, 300}` would yield the following HTML:
```
<div class="image" width="300">
  <img src="images/box-plot.png" aria-labelledby="box-plot-caption" aria-describedby="box-plot-description">
  <span id="box-plot-caption"        class="image-caption">distribution of US Income in 2003</span>
  <span id="box-plot-source"         class="image-source">retrieved from data.gov on April 15th, 2022</span>
  <span id="box-plot-description"    class="image-description">a box plot showing a right skew</span>
</div>
```

With this implementation, we can use CSS to ensure that empty captions aren't rendered. Screenreaders will always vocalize using the label first, then the description. Visually-impaired users will hear "distribution of US Income in 2003, a box plot showing a right skew". Sighted users will see the image, with the text "distribution of US Income in 2003, retrieved from data.gov on April 15th, 2022". 

----------

When including an image, we can just use the standard @image tag, with arguments solely for filename and size. The build script can compare the filename to the dictionary, and include proper captions, alt text, etc. It can also produce a warning if an image isn't in the dictionary. And finally, it could combine all the dictionaries into a single citation page for each pathway, allowing us to show exactly where every piece of media we use came from.

This has the benefit of backwards-compatibility: none of the existing @image tags need to change. Everything will still work! Over time, we can move all the captions out of those tags and into these dictionaries.

**Comment by flannery-denny** [comment]
@schanzer nudging you to add the following to the spec above:
- standardized language for how to report the source of images of our own creation
- how you want dorai's script to handle those sources in the build

**Comment by flannery-denny** [comment]
@ds26gte please implement this on the `image` branch so that I can confirm that my changes are working as expected. Thanks!

**Comment by flannery-denny** [comment]
@schanzer Flagging that the coordinates lesson includes images that are linked to with @link… not sure how this will work with the image infrastructure

**Comment by schanzer** [comment]
@flannery-denny good call! I've implemented that change and pushed.

**Comment by flannery-denny** [comment]
@schanzer There are sometimes images that only exist in slides. Do we want to describe them, too?

**Comment by schanzer** [comment]
@flannery-denny No need to describe them (this includes china-code.png in the defining values lesson)

**Comment by flannery-denny** [comment]
Does that mean we should leave them out of `lesson-images.json` or make a commented section of that file that says `images only used in slides` or list them in the file with `"slides"` in the 3 required fields?

**Comment by schanzer** [comment]
Leave them out.

(Also FYI - you can't add comments to a `.json` file)

**Comment by flannery-denny** [comment]
@ds26gte 
- Thanks for volunteering to populate `lesson-images.json` files from information in the `@image` directives in lesson plans and workbook pages.

- Any image created by us can get the following attribution.
>       "source" : "Created by the Bootstrap Team"
>         "license" : "Creative Commons 4.0 - NC - SA"

- Please do not fill in bogus information for images that we did not create, such as images of food in @schanzer's combinatorics lesson.
- Please reach out for help if you run into stuff that feels unclear!

@schanzer Thanks for agreeing to take on the computing needs all voices lesson. Encouraging you to also look at the comments I made in the comment with the checkboxes above about images I had questions about the provenance of, as I expect Dorai will also not know what to do about them.

**Comment by flannery-denny** [comment]
@schanzer @ds26gte Had a chance to check out the `image` branch.
Here are some things I have questions about:

- Should I be able to use @link in a caption?

>  "dollar-infographic-mona-chalabi.png" : {
>         "caption" : "Made by Data Designer @link{https://www.instagram.com/monachalabi/, Mona Chalabi}",
>         "description" : "Infographic: For every dollar a white man earns... visual shows parts of dollar bills corresponding to the comparable earning of other groups including (from highest to lowest earnings): Asian Men, Asian Women, White Women, Black Men, Native American Men, Black Women, Hispanic Men, Native American Women, Hispanic Women",
>         "source" : "https://www.instagram.com/monachalabi/",
>         "license" : "Used with permission from the creator."
>   },

- Why don't I get a warning/error for images like these that are missing descriptions?
![Screen Shot 2022-12-13 at 10 09 08 AM](https://user-images.githubusercontent.com/66691020/207385029-3ce6305d-bbf9-488c-8747-80be92b9ab01.png)
- Why are there so many images that are missing some of the four fields? The entire correlations lesson, for examples is missing descriptions...
- Confirming it's intentional that we turned off the warning for missing sources for images like these and someone will turn those warnings back on in the future and clean up the files?
> "ethics-privacy-and-bias": {
>  "AtomicBomb.png" : {
>         "caption" : "",
>         "description" : "Mushroom cloud from an atomic bomb",
>         "source" : "",
>         "license" : ""
>   }
- [ ] Assuming that the `images.js` file gets built from other files, which means it's pointless for authors to edit it. Can we make that clear within the file somehow?
- [ ] The `images.js` file is supposed to be pathway specific. As such, I would expect it to build within each of the courses folders rather than in the `en-us` folder.

**Comment by flannery-denny** [comment]
@ds26gte before we close this issue, let's add something about these files to the README doc, including wording standards for authors.
