### ISSUE TITLE
Shouldn't all DS lessons focused on displays be dependent on Intro do DS?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1199]
This is where we explain how spreadsheets are imported to pyret and talk about the difference between categorical and quantitative variables. Seems strange that they can get to bar charts, etc. without it...

**Comment by schanzer** [comment]
@flannery-denny  If a teacher just wants to do a lesson on histograms, they don't need to talk about how to import spreadsheets. Nor do they have to talk about categorical versus quantitative data, or the complexities of asking questions and answering them with data.

**Comment by flannery-denny** [comment]
@schanzer Following our discussion I have review the DS-Intro lesson. It is not attempting to teach students how to import a spreadsheet. It is making sure that they know how to read the code that they will see in the editor while working with a dataset that's already embedded in a starter file. In addition, it introduces the categorical & quantitative data, which all lessons refer to. And it introduces the animals dataset (which all lesson focused on displays engage with). I had added it as a prereq for all lessons focused on displays in ds-restructure for Fall2023
