### ISSUE TITLE
BSA:FunctionApplications

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#12]
- [x] What does this lesson have to do with function application?
- [x] Why do kids have to save their files to GDrive?
- [x] Fair use diagram is a broken image
- [x] Update prose to mesh with new files -J
- [x] Make new image search graphic with generic image instead of Mario (copyright) -J

**Comment by BootstrapJen** [comment]
re: GDrive - There seems to be a decisive preference among teachers (if I'm wrong here, please stop me) for the GDrive method of adding images to the game, and it eliminates the problem of game images disappearing or not loading if someone wants to open the game months or years later.  I'm going to make a separate sheet that documents the direct linking method for those that prefer it.

**Comment by BootstrapJen** [comment]
re: function application - the big idea here is that students will apply previously-learned functions (mostly scale, but also flip-vertical, flip-horizontal, or rotate) alongside the new bitmap/url to create their game images in order to coalescence their understanding of how to apply these tools to best complete a task.

**Comment by schanzer** [comment]
OK, but the lesson plan just says "save it to google drive" without any explanation of how. 

And as for function application, I like your answer a lot. It's just not clearly in the lesson plan. You should explicitly call out these functions somewhere in the lesson, and explain that students will need to apply them.

**Comment by BootstrapJen** [comment]
Image guide file is there but not linking correctly - note to self to fix 3/7
