### ISSUE TITLE
Write lesson introducing DS contracts

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1206]
- [x] Sort animals-table alphabetically / youngest -> oldest
- [x] Count animals-table by species - new table with 2 columns: list of species and count.
- Notion of summarizing or grouping? What makes histogram different?
- [x] Exploring one-variable Displays & remove it from Bar & Pie Charts
- [x] Acknowledging that there is a contracts lesson for other shapes

perhaps this will include the `sort` function
(Added by ES) also include the new `first-n-rows` function, which lets us get the first _n_ rows of a table. Used in conjunction with `sort`, we can give challenges like "produce a table showing the 10 heaviest animals." This might also be an opportunity to use the Circles of Evaluation!

**Comment by schanzer** [comment]
@flannery-denny is it worth adding stacked-bar-chart and multi-bar-chart to the "exploring functions" activity? I don't have a strong feeling either way, but this will impact how I introduce them in the pie-and-bar-chart lesson

**Comment by flannery-denny** [comment]
@schanzer we decided ds contracts will only cover one-variable displays.

Flannery

**Comment by schanzer** [comment]
Thanks. What about the other question?

**Comment by flannery-denny** [comment]
I am not planning to include any 2-variable displays in exploring displays. It has never made sense to me that they were in this activity and the new framing solidified that.

If you disagree, let’s discuss next week rather than over git.

Flannery

**Comment by schanzer** [comment]
@flannery-denny I don't disagree - I'm asking about the second question above:

Will the making infographics project live in this new lesson you're writing?

**Comment by flannery-denny** [comment]
@schanzer Huh. That question didn’t come through before. That project will continue to live with bar and pie charts.

Flannery

**Comment by flannery-denny** [comment]
@schanzer I just tried to `sort(animals-table, "species", true)` in the animals starter file and was told `sort` only accepts one parameter. My best guesses for single inputs would be `animals-table` and `"species"` but they both return errors. 
 Would love to know if I should be in a different file or am using the wrong function name. Thanks!

**Comment by flannery-denny** [comment]
I'm on the `functions-for-tables` branch which comes from the `fall2023` branch and has recently been updated to include the `image` branch because of error messages I was getting. Guessing you haven't updated `starterfiles.rkt` yet?

It feels problematic to me that DS 1.6 has a `sort` function that doesn't work like the function will work in 2.0

**Comment by schanzer** [comment]
That branch is quite old. You should use fall2023. I'll go ahead and delete this branch.

Where does DS 1.6 use `sort`? As far as I know it's just another function in Pyret that nobody in our courses uses.
