### ISSUE TITLE
Streamline Linear Regression lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1209]
- [x] Less discussion of contract "like scatter-plot..."
- [x] Rewrite lesson goals to be more user friendly
- [x] Add workbook page for interactive LR plot and pyret plots they are just looking at
- [x] standardize R2 and deprioritize 
- [x] explicitly remind students what they know about r-value! I can't find anywhere that we provide guidance on it in the lesson.
- [x] Be more explicit about the fact the predictor function is written in slope-intercept form. 
- [ ] Perhaps link to other lessons that introduce slope and intercept?

**Comment by flannery-denny** [comment]
@schanzer The current lesson has students make scatterplots in pyret. Then look at the interactive geogebra linear regression activity. And then think about the same scatterplots that they just made... 

Ok with you if we only look at the pyret plots once? Preference for whether the workbook page asks them to build the plots or look at the screenshots?

**Comment by schanzer** [comment]
Totally fine to do it once, and I don't think they have to make some in Pyret

**Comment by flannery-denny** [comment]
@schanzer I’m wondering about removing the research paper link from the materials section of lesson plans where only some users will end up writing the research paper. Is there some behind the scenes magic we can work that would designate the lesson where it is first introduced as the only place shows up in the materials section and still allow us to use @starter-file to provide a link to it from within whatever other lesson plans we want to refer to it?

**Comment by schanzer** [comment]
@flannery-denny Using `@link` will allow us to show a link without it appearing the materials list.
