### ISSUE TITLE
If an @online-exercise is referred to twice in a lesson plan, it should only appear once in materials - even when different words are used to describe it

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1210]
I have changed the text to match, but if you want to test it out, open a lesson like linear regressions and change one of the @online-exercise references to have a different descriptor. Then build.

**Comment by ds26gte** [comment]
Fix pushed to master. Any other branch need this immediately?  

Also does this kind of fix need to be done for anything other than @online-exercise?

**Comment by flannery-denny** [comment]
It should be pushed to fall2023 and as far as I can think of should apply to all exercise types. Any objections @schanzer?

**Comment by schanzer** [comment]
@flannery-denny and @ds26gte Fully agree
