### ISSUE TITLE
post HOC in facebook groups week after Thanksgiving

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1215]

**Comment by flannery-denny** [comment]
@retabak reminding you this is on your todo for the week and probably wouldn't take much time
Recommend drawing attention to the following 3 lessons
- [ ] computing needs all voices 
- [ ] hour of data
- [ ] new winter parley lesson

**Comment by retabak** [comment]
Done. 
Post has garnered many likes!
