### ISSUE TITLE
Make fitbruby work like fitb

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1216]
When `@fitb` is used without a width, the build script generates a span with class `fitb stretch`. 
When `@fitbruby` is used without a width, the build script generates a span with width `100%`.

They should both follow the behavior of `fitb`

**Comment by ds26gte** [comment]
Pushed fix to master. Please check that `@fitbruby{}...` doesn't extend too much in situations you care about.

**Comment by schanzer** [comment]
@ds26gte looks great! push to fall2023
