### ISSUE TITLE
Add another self-guided Hour of Code lesson using parley and Schanzer Slides 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1219]
- [ ] Check in with Joe Politz about whether he's willing to commit to making it possible to import spreadsheets in Parley?

**Comment by flannery-denny** [comment]
@schanzer seeing the note in this issue about checking in with Joe. Worth the ask at this point?

**Comment by schanzer** [comment]
@flannery-denny sure - let him know we're wondering what the state of things is, and if there's anything new we should be aware of as we plan for this Fall's hour of code
