### ISSUE TITLE
Implement @funname for CODAP

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1220]
@ds26gte please add @funname to CODAP design recipe so that @retabak can use them.

![Screen Shot 2022-11-30 at 3 53 55 PM](https://user-images.githubusercontent.com/66691020/204917088-9382c439-0a02-4c5d-a211-8f07ca0e7209.png)

**Comment by ds26gte** [comment]
Pushed fix to `master`.  Let me know if there's any other branch(es)  you want me to add this to.

**Comment by flannery-denny** [comment]
@ds26gte Woohoo! One issue resolved at the Linden Row Inn :) Please push to fall2023.

**Comment by ds26gte** [comment]
Done
