### ISSUE TITLE
Audit image sources

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1228]
Any image created from a display of data should include attribution for the source of that data. 

If data is contrived, note that too.

- [x] Bar and Pie Charts
- [x] Data Cycle
- [x] Probability Inference & Sample Size
- [x] Choosing your Dataset
- [x] Histograms
- [x] Visualizing the Shape of Data
- [x] Measures of Center
- [x] Box Plots
- [x] Standard Deviation
- [x] Scatter plots
- [x] Ethics Privacy & Bias
- [x] Collecting Data
- [x] Row and Column Lookups
- [x] Custom Scatterplots
- [x] Table Functions
- [x] Composing Table Operations
- [x] Defining Table Functions
- [x] Grouped Samples
- [x] Correlations
- [x] Linear Regression
- [x] Checking your work
- [x] Threats to Validity

**Comment by flannery-denny** [comment]
@schanzer is the teeth data in histograms contrived?

**Comment by schanzer** [comment]
@flannery-denny all of the data is contrived, except for the school data, which comes from the RI Schools dataset
