### ISSUE TITLE
Stress/Chill project needs attention

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1243]
https://bootstrapworld.org/materials/spring2023/en-us/lessons/box-plots/pages/stress-project.html

I sat down to crank out a rubric for "Stress or Chill?" and am discovering I have a million questions about this project. (Somehow, I never reviewed / improved this project when I was going through all of the projects a million years ago. Not sure how I missed it.) If you quickly skim it, it looks fine -- but if you put yourself in a teachers' shoes and actually try to envision doing the project with kids....

Here are the issues:
- This project is in the box plots lesson, but it does not make sense for students to make box plots to analyze this data. Students hardly collect any quantitative data in this project.
- Several of the objectives don't make sense. There are all these questions about "typical stress/chill" level across the class, and class wide trends, but students' never actually look at class data - only their own. Are they supposed to infer based on their peers' presentations? That doesn't seem like a practice we want to encourage in a data science curriculum...
- I looked at the original IDS project, and it totally makes sense! The project there is all about merging two data sets (color personalities and stress levels). There's a lot more going on with that project.

I think Joy has done this project with students, but it does not feel rigorous or clear and I do not actually understand the objectives or what it is trying to assess.  I think it needs to be radically altered or deleted.

**Comment by schanzer** [comment]
@retabak totally agree - this project has never felt great to me. I would love to have you look into it after you've completed the early-math and codap work on your plate!
