### ISSUE TITLE
Change All Projects to Lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1248]
Projects are student-facing, so it doesn't make sense for us to include important information that is supposed to be exclusively teacher-facing, including:
- lesson table 
- rubric (which we encourage teachers to modify if needed)
- teacher guidance
- pre-requisites

We can also be much more thoughtful in thinking about how projects advance lesson objectives. Many projects need to be tweaked so that it is clear how they advance lesson learning goals; we don't want it to feel like we took an IDS project and thoughtlessly plopped it into our lesson. On that note, some lessons are possibly situated in the wrong lessons. 

This is not urgent, and will likely require more discussion, along with some magic from @ds26gte.

- [x] Build a video game
- [x] Exploring a New dataset
- [x] Research Paper
- [x] surface area (needs rubric)
- [x] Flags
- [x] Making an Infographic (bar & pie charts)
- [x] Threats to validity 
- [x] beautiful data (advanced displays)
- [x] survey design

additional to-dos:

*slides*

- [x] Build a video game
- [x] Exploring a New dataset
- [x] Research Paper
- [x] surface area 
- [x] Flags 
- [x] Making an Infographic (bar & pie charts) 
- [x] Threats to validity 
- [x] beautiful data (advanced displays)
- [x] survey design
- [x] project-logo
- [x] project-function

*standards*

- [x] Build a video game
- [x] Exploring a New dataset
- [x] Research Paper
- [x] surface area 
- [x] Flags
- [x] Making an Infographic (bar & pie charts)
- [x] Threats to validity
- [x] beautiful data
- [x] survey design
- [x] project-logo
- [x] project-function

These are maybe not worth the time commitment:
- [ ] Food Habits (probability & inference)
- [ ] Time Use (probability & inference)
- [ ] Stress or Chill (box plots) **[PPS needs]**
- [ ] olympic records

**Comment by schanzer** [comment]
From the discussion in #1312 :

Part of this work should be to define the data structure for Projects. What should every single project have? It may necessitate an entirely new top-level structure....or not. But either way, any effort put towards standardizing our projects is a Good Thing(tm).

**Comment by retabak** [comment]
brain dump about projects: 

https://docs.google.com/document/d/1Uj2mrPu6knu_9QOrGEIU5x1VBxiKVvCufwg1IvO2Zuo/edit?usp=sharing

**Comment by retabak** [comment]
- [ ] Build a video game
- [ ] Exploring a New dataset
- [ ] Research Paper
- [ ] Making an Infographic (bar & pie charts)
- [ ] Food Habits (probability & inference)
- [ ] Time Use (probability & inference)
- [ ] Stress or Chill (box plots)
- [ ] Threats to validity

**Comment by retabak** [comment]
This is a perfect place for that comment, @flannery-denny . Thank you! Was feeling overwhelmed by all the project related issues so did some consolidating yesterday. When I get to this, I'll reach out if I have any questions.

**Comment by retabak** [comment]
PS - this is a great suggestion :)

**Comment by retabak** [comment]
@flannery-denny - I'm working on a draft of the threats to validity project. I don't think I can think of a way to integrate your suggestion, given that students don't actually collect or look at data during the project.... they're just pretending they're bad data scientists who come up with a bad research plan. 

Any ideas?

**Comment by retabak** [comment]
also noting here that we need to decide:
- if projects will be listed in various pathways / course landing pages
- we need to think about if we want to still include the pedagogy boxes inside of the lessons?
- do we want project worksheets to be @opt-printable or @printable? (I think this decision should relate to whether we want projects in the workbook or not. I'm not sure.)
- once we put these on the web, we'll need to remove the old project pages (which are not lessons)

**Comment by retabak** [comment]
additional to-dos:

- [ ] slides
- [ ] standards
- [ ] change opt-printable to handout

**Comment by schanzer** [comment]
@retabak now that #1937 is tracking the remaining un-checked items, can this be closed as a duplicate? Or should we close #1937 instead? Either way - we don't need both
