### ISSUE TITLE
early math glossary - review, critique, improve (and maybe translate?)

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1252]
https://docs.google.com/document/d/1eQdYoMEiLBVwzyD85D6PGRDm3SvOWBnLLyDOQyU9WQ8/edit?usp=sharing

Hoping for any feedback, complaints, suggestions, deletions, additions that y'all might have.
- do all of these words seem relevant enough to be in the glossary?
- have I missed any words that felt important to you?

This draft is a google doc because I genuinely felt it would be easier to have just the early math stuff filtered out.  (I swear, I'm over my fear of ascii!) If this is inefficient, let me know, and I can asciidocify.

@flannery-denny - I know you have very minimal time left, but is a Spanish translation something you could do relatively easily? Or is this a no-go for now? (I can't remember your level of fluency. I have a feeling this might be a somewhat time-consuming ask.)

**Comment by schanzer** [comment]
@retabak left some comments in the doc. Overall it looks like a good start, and I think all of these words are relevant enough to your lessons to put them in the glossary.

Offhand, I can't think of any other words that are missing.

**Comment by flannery-denny** [comment]
I we can agree on the definitions, I can knock out the Spanish translations.

**Comment by retabak** [comment]
@retabak will add English glossary to early-math
Send message to @flannery-denny when done

**Comment by retabak** [comment]
@flannery-denny - dictionary has new vocab added and is awaiting your translation! It's on early-math branch.

**Comment by flannery-denny** [comment]
@retabak @schanzer Translation always leads to increased scrutiny of definitions. I have made changes where they felt needed. Please look at the commits.  

Apologies for the missing parentheses breaking the build. My sublime isn't configured quite right and I couldn't find it.

**Comment by schanzer** [comment]
Fixed the glossary typo

**Comment by schanzer** [comment]
@retabak I think you have the final say on Flannery's edits, and on closing this issue

**Comment by retabak** [comment]
Okay - I remember hearing that y'all agreed on a new definition for "circle of evaluation" - one that does not include "sentence diagram"? What is the new definition?

**Comment by retabak** [comment]
@flannery-denny @schanzer 
was the proposal just to remove "sentence" and define COE as "a diagram of the structure of a mathematical expression" ?

**Comment by schanzer** [comment]
@retabak I believe so
