### ISSUE TITLE
improve warnings for extra comma in lesson-images.json files

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1256]
It took me a while to figure out that all of these warnings might have come from a lesson-images.json file mistake. In the end I discovered I'd delete the last entry and not removed the comma from the end of what had been the second-to-last entry. Perhaps the system could give better feedback?

> 👨‍💻CALLING ASCIIDOCTOR IN BATCH MODE
> -----------------------------------------------------------
> asciidoctor: WARNING: .describing-relationships-1.asc: line 12: unterminated table block
> asciidoctor: WARNING: .describing-relationships-2.asc: line 13: unterminated table block
> asciidoctor: WARNING: .drawing-predictors.asc: line 29: unterminated table block
> asciidoctor: WARNING: .lr-plot-intro.asc: line 12: unterminated table block
> asciidoctor: WARNING: .describing-relationships-1.asc: line 13: unterminated table block
> asciidoctor: WARNING: .describing-relationships-2.asc: line 14: unterminated table block
> asciidoctor: WARNING: .drawing-predictors.asc: line 30: unterminated table block
> asciidoctor: WARNING: .lr-plot-intro.asc: line 13: unterminated table block
> asciidoctor: WARNING: .index.asc: line 69: unterminated table block

**Comment by schanzer** [comment]
@flannery-denny and @retabak this is how I was able to update the syntax highlighter in Sublime, to detect dangling commas:

1) From the "Sublime Text" menu, I selected "Settings..." and then "Select color scheme...". This brought up a modal window with lots of options underneath. Using my mouse, I scrolled down until I saw the "Mariana" scheme. 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/77126/214440530-49696ae4-5d0c-495d-8d65-452459ffcc44.png">

2) Once enabled, the new color scheme highlighted any problematic commas
<img width="711" alt="image" src="https://user-images.githubusercontent.com/77126/214440834-ac86a5fe-b62d-4073-98a3-3cc1c3742577.png">

**Comment by ds26gte** [comment]
Are you sure this is what's triggering the opaque error message? I deliberately added an extraneous comma to a `lesson-images.json` file and got the following, appropriate, error:

```
ERROR: lessons/computing-needs-all-voices/pages/../images/lesson-images.json::9543: read-json: bad input
 starting #"}\n" in "lessons/computing-needs-all-voices/pages/ada-lovelace.adoc"
```

(This was on the `fall-2023` branch.)

**Comment by flannery-denny** [comment]
@ds26gte

Just tested it out in a different file and got the same clearer message you did.

> ERROR: lessons/box-plots/images/lesson-images.json::8206: read-json: bad input starting #"}\n}\n" in "lessons/box-plots/index.adoc"

 I am sure that that's the only mistake there was in my files. It's possible, however, that when I fixed it, it was the force building that resolved the opaque communication and I would have continued getting strange messages had I not forcebuilt?

Finally, just double checking that you meant you were on the `fall2023` branch and we do not have a separately active `fall-2023` branch...

**Comment by schanzer** [comment]
If this is indeed no longer replicable, I suggest we close once @retabak installs the Sublime linter. Rachel, try following the comment above and let me know if you run into trouble!

**Comment by ds26gte** [comment]
BTW, that error message is Racket's. It does mention where the error occurs, but uses the character position in the file rather than the more human-friendly line number.  

You may be able to use a command-line tool like `jq` to pinpoint the line number. (But I've found the syntax highlighter on my text editor good enough. I suspect Sublime must have something comparable. Or see if Sublime lets you jump to a numerical character position in the file.)

**Comment by schanzer** [comment]
@flannery-denny to go to a character index in sublime, select "Goto anything..." from the "Go to" menu. 
![image](https://user-images.githubusercontent.com/77126/214869665-ed957d67-2290-4867-9ae9-af9657a1d49b.png)

Then type `::XYZ`, where `XYZ` is the character index.
![image](https://user-images.githubusercontent.com/77126/214869829-e40a3003-ffd5-4c9a-9eb1-9848e82f5618.png)

At this point it looks like the original issue (json errors) is resolved. OK to close?
