### ISSUE TITLE
Add stories to linearity lessons

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1279]
From Annie Fetter: ask kids to tell the story behind each graph, table, etc.
Add `opt-printable-exercise` for these

**Comment by schanzer** [comment]
@flannery-denny this is PERFECT. Exactly what I had in mind. Definitely go ahead and make table versions as well. (Minor nit: it would be great if there was just one graph where time wasn't one of the variables.)

I'm happy to let go of covering independent/dependent variables here.

**Comment by flannery-denny** [comment]
@schanzer Please close if you're satisfied.

**Comment by schanzer** [comment]
Oooh, these are PERFECT! Love the diversity of stories, too.
