### ISSUE TITLE
Collect starter files used in each pathway, so they can be automatically listed in the pathway resources page

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1283]
Right now our pathways have hand-coded lists of `@starter-file{...}`, which have to be assembled by hand by surveying all the lessons in each pathway. This is error prone, and will break once user-created pathways are created.

1. In the short term, it would be great to have a directive `@pathway-starters`, which prints out the list programmatically. 
2. In the long term, we should extend the `dependency-graph` to include fields for starter files, so that the normal graph traversal can do this programmatically. But this has implications for having our graph include _all_ language variations, so probably not something that can be done quickly...

**Comment by schanzer** [comment]
@ds26gte this can now be completed, with the new dependency graph in place. Reminder: let's do this on a branch, so the debugging noise doesn't clutter up fall2023

**Comment by ds26gte** [comment]
I see that the `@starter-file` directive is called in both lesson plans and workbook pages, but it is possible that the latter merely point to ones that are already represented in the lesson plan? Should we scan only lesson plans to get at the starter files associated with a lesson, or should we expand the net to look at workbook pages too?

**Comment by schanzer** [comment]
Expand the net :)

**Comment by schanzer** [comment]
@ds26gte this is a great start! I realize now that we _talked_ about how to handle proglang-specific starter file URLs, but I didn't write this up in the issue description.

We'll either need to change the "arrays of strings" to "arrays of name/url pairs", or export the starter file dictionary itself as a JSON object. I defer to your engineering sensibilities. :)
