### ISSUE TITLE
Need a warning to prevent duplicate workbook pages

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1286]
There have been a few instances where an author uses the @opt-printable directive for a workbook page, and then ALSO lists that same adoc file in workbook-pages.txt. 

This results in optional pages appearing in the printed workbook, which is not what we want! 

Can we have a warning appear when authors make this mistake?

**Comment by ds26gte** [comment]
Pl let me know if you're seeing the warnings you expect now.

**Comment by schanzer** [comment]
Confirmed fixed! Thanks, @ds26gte
