### ISSUE TITLE
issue with make

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1287]
Okay, putting this in an issue rather than slack because it is SO WEIRD and my description of this bug required me to write an essay, basically.... feel free to ask any clarifying questions! I was on fall2023 for all of the following activity, and replicated it numerous times.

1. `make clean`
2. `make`
3. Fiddle with solutions (@ifsoln...) on lessons/Early-Math/absolute-value-and-opposites/--/pages/true-false-negate.adoc.
4. Save.
5. `make` again 
6.  Changes still do not appear in distribution/--/pages/true-false-negate.adoc

So, I think, hm, okay, I'll do `make clean` and try again....

7. `make clean`
8. `make`

9. Here's the weird part... I GET ERRORS this time?!:

lua: lib/maker/make-bilingual-glossary.lua:30: bad argument #1 to 'ipairs' (table expected, got string)           stack traceback:                                                                                                          [C]: in function 'ipairs'                                                                                         lib/maker/make-bilingual-glossary.lua:30: in upvalue 'extract_keywords'                                           lib/maker/make-bilingual-glossary.lua:42: in local 'display_lang_entry'                                           lib/maker/make-bilingual-glossary.lua:74: in main chunk                                                           [C]: in ?                                                                                                 make[1]: *** [lib/maker/Makefile.phase1:116: distribution/en-us/lib/bilingual-glossary.adoc] Error 1              make: *** [lib/maker/Makefile.all:49: all] Error 2    

...and then when I click on my file in distribution (or even refresh the page that was open before), I get, "your file couldn't be accessed."

A bit baffled, I think, hm, I'll just try `make` again.... So...

10. `make` 
11. No errors appear!
12. I open my workbook page and everything loads correctly with my altered solutions (that I fiddled with in step 3).

I did a few cycles of this. It is happening consistently. If I'm doing something wrong, let me know!

**Comment by ds26gte** [comment]
Thanks for the detailed report. Unfortunately I can't replicate it -- things work as expected. What was the nature of the change you made inside `@ifsoln` in `true-or-false-negate.adoc`?  Also, were you working with a recent pull? Branch `fall2023`?

**Comment by retabak** [comment]
hmmm..... Today, steps 1-6 are the same as described, but I'm not getting the mystery errors (meaning I skip steps 9-10, above). Everything else is the same.

**Comment by retabak** [comment]
@ds26gte - can I close this? Or keep it open because of the bilingual glossary issue?

**Comment by ds26gte** [comment]
You may keep it open, as the report does mention the bilingual glossary failure, even though the heading describes a different, unrelated bug (which has now been fixed).
