### ISSUE TITLE
@lesson-link breaks when used outside of lesson plans

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1289]
1. [Live on our website right now](https://bootstrapworld.org/materials/spring2023/en-us/textbooks/IM-grade-6.html):

![image](https://user-images.githubusercontent.com/77126/223902994-4ee33831-88fe-44c9-a34a-c3d219440d49.png)

It looks like @lesson-link isn't resolving to the lesson titles, when used from these textbook pages. It's broken in both `master` and `fall2023` (new build system), so it's likely a racket preprocessor issue. 

2. The same issue happens in the last section of the [teacher resources page](https://bootstrapworld.org/materials/spring2023/en-us/courses/algebra-pyret/resources/index.shtml), when referring to a lesson:

![image](https://user-images.githubusercontent.com/77126/223903804-82e8e3d7-259b-4f5d-bdc9-f784facfe741.png)

Look at the URL at the bottom - "distribution" shouldn't show up there at all!

**Comment by ds26gte** [comment]
Fix in commit e78b39f71
