### ISSUE TITLE
Audit use of @opt-printable-exercises

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1295]
We want to flag for teachers when stuff is optional versus not (and when they can expect stuff to be in the workbook versus not).

I observed a few instances of us saying things like this:

[.lesson-instruction]
Now, complete @printable-exercise{blah} and @opt-printable-exercise{blah} to practice this skill.

Instead, we ought to be saying things like this:

[.lesson-instruction]
- Complete @printable-exercise{blah}. 
- Optional: If you have time, turn to @opt-printable-exercise{blah} for an additional challenge.

**Comment by schanzer** [comment]
@retabak I did this as a single commit, but if you're not cool with the changes I can revert them easily

**Comment by retabak** [comment]
Looks good!
