### ISSUE TITLE
Use rync in the deployment script

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1299]
Rather than use scp to copy all our files, we should use rsync. Apparently this is both faster and more reliable as well! Also, I think rsync does its own compression, so we could probably skip the taring and untarring phases.

**Comment by ds26gte** [comment]
It looks like the untarring and copying at the destination (via ssh) is what's taking long. Still, using rsync without tar may be a win. This avoids untarring at the destination. There is still a copy of a directory to public_html, but maybe we can directly rsync to public_html, if we feel brave about it.
