### ISSUE TITLE
Regression in workbook PDF collation

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1301]
When collating workbook pages, `makeWorkbook.js` is supposed to grab any pdfFileSpecList that ends in `workbook.pdf`, split off the first and last page, and use those to generate `cover.pdf` for uploading to Lulu. Likewise, the resulting `workbook.pdf` file is supposed to have covers!

This works on master, but does not on `fall2023`. It looks like the first and last fileSpec are removed prematurely.

UPDATE: Oh! It's extremely possible that the build script just isn't adding the covers to the fileSpec list to begin with!

**Comment by ds26gte** [comment]
Very good catch, thanks! 

Rare case where Lua `return` keyword syntax was non-intuitive and I misused it in good faith.
