### ISSUE TITLE
Add glossary info to dictionaries and graph json

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1303]
- [x] We should add a 'glossary' field to the object defined in `dictionaries.js`
- [x] Vocabulary used in a lesson should show up as an array for `glossary` in `dependency-graph.js`
- [x] Create a global `Glossary.shtml` file (just like `Alignments.shtml`) , and have all course narrative pages' glossary links point there
- [x] Add JS to the `Glossary.shtml` file so that it filters by URL parameters 
- [x] Remove all code related to generating `pathway-glossary.shtml`

**Comment by ds26gte** [comment]
`dictionaries.js` is a repo file, not . You want it to mention the glossary items statically, as opposed to having the build process determine them based on the `@vocab` entries in the lesson's text?  

Or do you mean you want the copy of the `dictionaries.js` file in the `distribution/` to be enhanced with a `glossary` field by the build process?

**Comment by schanzer** [comment]
@ds26gte the glossary items are looking great, in english. But where are the other natlangs?

**Comment by ds26gte** [comment]
These entries are keyed off of @vocab entries in English prose in the en-us portion of these lessons. How do we meaningfully bring back the es-mx counterparts at this filtered stage?

**Comment by schanzer** [comment]
Good point! In fact, it looks like our internal glossary groups definitions across languages simply by having them defined in adjacent locations in the file itself (there's no actual connection between the spanish and english word for `value`, for example).

Dynamically generating a bilingual glossary will require changes to our internal dictionary as well, which I'm not sure we want to do right now.

In that case, I'll leave a link to the bilingual glossary and use the dynamic one simply to replace the pathway-glossary file.
