### ISSUE TITLE
Standardize formatting for "pick one" solutions

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1305]
As @flannery-denny points out in #1302 , we have a few places where students are given _N_ options, and have to select one. A few examples can be found in the Early Math lessons, every single Data Cycle, Linear Regression, the Linearity lessons, and more.

New directive: `@ifsoln-choice{...}`!

This directive will _always_ produce a wrapper span with the same contents `{...}`. But in solution mode, this span should get `class="chosen"`.

Note: this is _different_ from how @ifsoln{} works, which only displays its contents in solution mode.

Emmanuel will style `span.chosen` to have some kind of emoji decoration.

We should change/confirm that this new style is used in the following:

- [x] Data Cycle
- [x] Transformer Design Recipe
- [x] Contracts (practicing-contracts.adoc)
- [x] Most Early Math lessons

**Comment by flannery-denny** [comment]
@ds26gte please push to the `codap` branch - I have a use case for it that I'd like to test out. Thanks!

**Comment by schanzer** [comment]
@flannery-denny and @retabak , here's a little git-fu tip if you want to push one of Dorai's commits to another branch and he's not available:

1. Copy the _commit hash_ for the commit in question. Looking at this very issue, I can see that the hash is `
8281d78`
2. Check out the branch you want to apply it to. In this case, you'd type `git checkout codap`
3. _Cherry pick_ the commit onto that branch, by typing `git cherry-pick 8281d78`

Voila!

**Comment by schanzer** [comment]
@ds26gte I tried the following:

1. Open `lessons/Early-Math/associative-property`, and edit the workbook page `which-circles-math-the-math-easier.adoc`
2. Wrap the table-cell value on line 18 with `@ifsoln-choice{...}`:
       `| @ifsoln-choice{@show{(coe '(+ (+ 17 46) 4))}}`
3. Build and open the solutions page you just edited

On would expect the circle of evaluation to be wrapped in `<span class="chosen">....</span>`. But I don't see it?

**Comment by flannery-denny** [comment]
@schanzer @ds26gte - I'm not sure whose department this is, but I deployed `@ifsoln-choice` in `codap-exploring/codap-apply-functions`. It looks as expected on the workbook page. 
On the solution page `@ifsoln-choice` is visible rather than an emoji.

**Comment by schanzer** [comment]
@flannery-denny looks like some CSS rules didn't get pushed. I've just checked them in, and confirmed that the page in questions shows checkboxes when in solutions mode:
![image](https://user-images.githubusercontent.com/77126/234075299-2dc47a71-a608-4f08-85b0-f7b8cfd48397.png)

**Comment by retabak** [comment]
I know this issue is closed, but I've got a question:  Should going through the lessons and adding in @ifsolnchoice where needed be an issue / on a to-do list somewhere? I'm suspecting it's not high-priority at the moment, but feeling like at some point, we will want to do an audit.

**Comment by schanzer** [comment]
Good call, @retabak !

**Comment by schanzer** [comment]
@ds26gte I've pushed a commit to `fall2023` that addes `ifsoln-choice` to a bunch of lessons, and I'm noticing an issue when the directive is used on the first child of a row. In `computation/solution-pages/wodb.html`, the red-X correctly appears to the right of every circle where it's used....except those that are the first circle in a row.

In that situation, the red-X is simply _inserted as a prior sibling_ of the circle. Not sure what could be causing the glitch, but wanted to bring this to your attention.

**Comment by schanzer** [comment]
I believe this issue is now closed, but can be reopened if we find other glitches. I've checked against all known use cases.
