### ISSUE TITLE
Python issues should be addressed🐍

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1309]
From @ds26gte

_I heard some sounds in my attic all through the night, went up to check and saw a medium sized python (about 6 feet). Quickly shut the door. Any ideas what to do?_

**Comment by schanzer** [comment]
@ds26gte have you tried deleting the distribution folder and rebuilding?

**Comment by ds26gte** [comment]
Fixing this has swallowed up my entire morning

**Comment by schanzer** [comment]
Have you tried using the `scale` function?
