### ISSUE TITLE
Proposed Lesson Folder Reorganization

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1312]
The `lessons` folder has grown like crazy, and is about to grow more once #1248 is completed. We need to take advantage of @ds26gte 's subfolder organization capabilities to clean it up.

**Proposal**

Social-Studies
- Maya (and subfolders)
- Shipwrecks (and subfolders)

Early-Math

- translating
- computation
- commutative-property
- associative-property
- distributive-property
- equivalence
- identity-property
- absolute-value-and-opposites
- absolute-value-and-opposites-2
- evaluating-exponents
- exponent-expressions-with-negatives

Hour-of-Code

- hoc-data
- hoc-wescheme-intro
- hoc-winter
- hoc-winter-parley

Data Science
- ds-intro
- contracts-tables-displays
- bar-and-pie-charts
- data-cycle
- probability-inference
- choosing-your-dataset
- histograms
- histograms2
- measures-of-center
- box-plots
- scatter-plots
- correlations
- standard-deviation
- linear-regression
- ethics-privacy-and-bias
- data-collection
- lookups
- advanced-displays
- table-functions
- composing-table-operations
- defining-table-functions
- CODAP (and subfolders)
- grouped-samples
- checking-your-work
- threats-to-validity

Algebra2

- exploring-linear-relationships
- exploring-quadratic-relationships
- exploring-logarithmic-relationships

Math

- coordinates
- order-of-operations
- distance-formula
- flags
- function-definition-linear
- function-notation
- functions-can-be-linear
- functions-vertical-line-test
- inequalities-collision
- inequalities1-simple
- inequalities2-compound
- problem-decomposition
- surface-area-rect-prism
- combinatorics-combination
- combinatorics-permutation

Core

- computing-needs-all-voices
- simple-data-types
- contracts
- defining-values
- function-composition
- functions-make-life-easier
- functions-examples-definitions
- functions-dr
- piecewise-functions-conditionals
- debugging

Project Lessons

- making-game-images
- numbers-inside-video-games
- player-animation
- functions-for-character-animation
- project-exploration-paper
- project-research-paper
- project-video-game
- inequalities3-sam

Reactive

- re-intro-to-data-structures
- re-structures-reactors-animations
- re-functions-that-ask-questions
- re-key-events
- re-refactoring
- re-your-own-drawing-functions
- re-build-your-own-animation
- re-adding-collisions
- re-scoring
- re-adding-levels
- re-making-pong
- re-nested-structures
- re-timers

@flannery-denny and @retabak need your input/approval on this

**Comment by flannery-denny** [comment]
My only question is about projects. I think they’re pathway specific? In which case they could be subfolders within math and ds.FlanneryOn Apr 4, 2023, at 2:29 PM, Emmanuel Schanzer ***@***.***> wrote:﻿
The lessons folder has grown like crazy, and is about to grow more once #1248 is completed. We need to take advantage of @ds26gte 's subfolder organization capabilities to clean it up.
Proposal
Social-Studies

Maya (and subfolders)
Shipwrecks (and subfolders)

Early-Math

translating
computation
commutative-property
associative-property
distributive-property
equivalence
identity-property
absolute-value-and-opposites
absolute-value-and-opposites-2
evaluating-exponents
exponent-expressions-with-negatives

Hour-of-Code

hoc-data
hoc-wescheme-intro
hoc-winter
hoc-winter-parley

Data Science

ds-intro
contracts-tables-displays
bar-and-pie-charts
data-cycle
probability-inference
choosing-your-dataset
histograms
histograms2
measures-of-center
box-plots
scatter-plots
correlations
standard-deviation
linear-regression
ethics-privacy-and-bias
data-collection
lookups
advanced-displays
table-functions
composing-table-operations
defining-table-functions
CODAP (and subfolders)
grouped-samples
checking-your-work
threats-to-validity

Algebra2

exploring-linear-relationships
exploring-quadratic-relationships
exploring-logarithmic-relationships

Math

coordinates
order-of-operations
distance-formula
flags
function-definition-linear
function-notation
functions-can-be-linear
functions-vertical-line-test
inequalities-collision
inequalities1-simple
inequalities2-compound
problem-decomposition
surface-area-rect-prism
combinatorics-combination
combinatorics-permutation

Core

computing-needs-all-voices
simple-data-types
contracts
defining-values
function-composition
functions-make-life-easier
functions-examples-definitions
functions-dr
piecewise-functions-conditionals
debugging

Project Lessons

making-game-images
numbers-inside-video-games
player-animation
functions-for-character-animation
project-exploration-paper
project-research-paper
project-video-game
inequalities3-sam

Reactive

re-intro-to-data-structures
re-structures-reactors-animations
re-functions-that-ask-questions
re-key-events
re-refactoring
re-your-own-drawing-functions
re-build-your-own-animation
re-adding-collisions
re-scoring
re-adding-levels
re-making-pong
re-nested-structures
re-timers

@flannery-denny and @retabak need your input/approval on this

**Comment by schanzer** [comment]
@flannery-denny good call! My only (minor) concern is that it might be easier for us to keep all projects with a consistent look and feel if they are grouped together in the authoring directory. But that's not such a big deal.

@retabak curious what you think?

**Comment by ds26gte** [comment]
Let me know how deep your subfolders will be. When I wrote the makefiles with dynamically generated rules, the makefile's wildcards (unlike the shell's) wouldn't allow me to pick up lessons at arbitrary subfolder depth, so I punted and chose a definite maximum depth of 3 (after viewing the current repo). 

I can easily hike up this limit as needed, or have it settable via a makefile variable in the topmost makefile, so you can DIY. In any case, make the subfolders as deep as is convenient for maintenance purposes, and the build system can accommodate. (I'm sure too deep is also not good, from a human-understanding POV, even if it is mathematically pleasing.)

**Comment by schanzer** [comment]
I'd be shocked if we go more than 4 levels deep. Let's keep it at 3 for now, and see if we need more after the reorganization

**Comment by retabak** [comment]
ooh, I LOVE the idea of grouping projects together for a more consistent look/feel.

**Comment by schanzer** [comment]
I've _long_ argued that abusing the lesson folder system for projects is a bad idea. We want the build system to always be _more_ opinionated about lessons - not less. And we've already had to do some backflips to force projects into the existing lesson system.

Imagine if we had a very clearly-defined notion of a _project_, and an entirely separate top-level `projects` folder than does all sorts of checking and error-reporting that is specific to projects.

This proposal only makes sense if we have a truly well-defined notion of "Project", with a lot of confidence that it works for all of our existing projects. Either way, it won't be sorted out now -- but if we want to get there eventually it's an argument in favor or grouping all projects together in this issue.

**Comment by flannery-denny** [comment]
@schanzer I weighed in on this before. It seems you have a clear reason why you want projects to be somewhere else - wanting to unify the look. 

Having just reviewed the 3 projects we have at the lesson level, I can confirm that they do not currently have a unified look. I'm also not convinced that it will make sense for all of our projects to have a more unified look, in that they are all quite different, but I have nothing else to add to this issue. If you think formatting logic of the future is more important than course logic, I trust that we'll find things when we need them, and, if the goal is to unify the look of projects, they are more likely to get closer to that if we make it easy for us to find and compare them.

One small request is that I am someone who sometimes types out full pathways to copy files, I think shorter names for folders are better.

**Comment by schanzer** [comment]
@flannery-denny and @retabak I've pushed a commit to `fall2023` that implements this (Flannery, I took your request for short names into account!). Everything seems to work ok, but I'd like to have you both build before I closing the issue.
