### ISSUE TITLE
Alias symbols in Pyret

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1325]
It's annoying that in WeScheme we can just type `sqrt`, but in Pyret we have to type `num-sqrt`. I spoke to Joe at length about this, and he agreed to export _aliases_ for these functions in a new `essentials2023` context. That means `num-sqrt` will continue to work, but `sqrt` will work as well!

I created a [tracking issue](https://github.com/brownplt/code.pyret.org/issues/468) for it, but I need input from both @retabak and @flannery-denny to make sure it's complete.

(I will make any necessary changes to WeScheme as well)

**Comment by retabak** [comment]
oooooh! I am SO in favor of this! YAY!

**Comment by retabak** [comment]
Also: num-expt ?

**Comment by schanzer** [comment]
Noting that this was completed some time ago!
