### ISSUE TITLE
Resizing a lesson after loading can result in invalid height calculations

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1332]
To reproduce:

1. Open any lesson plan ([like this one!](https://bootstrapworld.org/materials/spring2023/en-us/lessons/simple-data-types/index.shtml?pathway=data-science))
2. Expand the first lesson slice, then scroll down so you can see where that slice ends and the next one begins
3. Make the window a lot narrower.

EXPECTED: everything re-flows nicely
ACTUAL: all hell breaks loose, as the following slice gets taller and starts "eating" the slice above it.

<img width="728" alt="Screen Shot 2023-04-20 at 11 01 31 AM" src="https://user-images.githubusercontent.com/66691020/233423041-08d80317-eca8-48e4-8706-2726067770d6.png">

here's what it looks like when maximized
<img width="869" alt="Screen Shot 2023-04-20 at 11 03 34 AM" src="https://user-images.githubusercontent.com/66691020/233423376-8dbeab2b-04e5-45cf-b837-480645b95e75.png">

**Comment by schanzer** [comment]
@flannery-denny I'm not sure what's broken here. When a section is minimized, the text _has_ to be cut off. The only way to have no text cut off would be to start every lesson maximized. But we already decided that would be overwhelming to users.

**Comment by retabak** [comment]
Just here to say I love @flannery-denny 's colorful description of the problem.

**Comment by schanzer** [comment]
This problem is now fixed on the `codap` branch. I'll be cherry-picking this to `master` and `fall2023` shortly
