### ISSUE TITLE
Allow infographics page to be longer than a single printed page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1333]
I'm seeing this on making infographics in dot plots and bar charts

<img width="971" alt="Screen Shot 2023-04-20 at 11 04 35 AM" src="https://user-images.githubusercontent.com/66691020/233424469-b252e82c-abae-4e03-8c8e-3a8d9331c7a7.png">

**Comment by schanzer** [comment]
Add `[.canBeLongerThanAPage]` to the top of any page that does not need to print
