### ISSUE TITLE
No need to check if images are in the dictionary when processing slides

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1336]
Images that are used _only in slides_ need not be in the dictionary.

In the `contracts` lesson, we use an image called `sample-contracts-table.png` in the slides, but nowhere else. Currently the `build-slide` script generates a warning because it's not in the image dictionary, but it shouldn't.

I'm fairly certain we just need to remove [the expression on line 59](https://github.com/bootstrapworld/curriculum/blob/fall2023/lib/slides-preproc.rkt#L59-L67) in the slides-preproc.rkt file

Another two images from the distance-formula lesson that should not throw warnings:
** WARNING: Image role-play1.png missing from dictionary
** WARNING: Image role-play2.png missing from dictionary

**Comment by flannery-denny** [comment]
I'm on `fall2023` just did a fresh pull and am still seeing warnings when I `./build-slide`

> flannery@Flannerys-MacBook-Air curriculum % ./build-slide inequalities3-sam -f
> cat: .repodir.txt.kp: No such file or directory
> ** WARNING: Image safe-left-dr.png missing from dictionary
> ** WARNING: Image sam-slide.png missing from dictionary
> ** WARNING: Image onscreen.png missing from dictionary

**Comment by ds26gte** [comment]
This is happening because you didn't do a clean make. However, I've just pushed a fix f70650b whereby at least the slide-generation code will function OK without having to do a clean make.
