### ISSUE TITLE
Auto-running make as needed?

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#1338]
@schanzer writes: "Now that make is so fast, I’m curious: couldn’t we watch the lessons , lib, and pathway directories, and auto-run make if it changes? I’m inspired by [this script](https://www.baeldung.com/linux/command-execute-file-dir-change), and the react/webpack authoring experience."

**Comment by schanzer** [comment]
@ds26gte This seems to work nicely after running `brew install fswatch` on osx. (`fswatch` is apparently available across platforms.)

```
#!/bin/bash

# watch the relevant directories for changes to adoc, less, css, md, txt, and shtml files 
# if any are created/modified/deleted, re-run make
fswatch -or \
    ./lessons ./pathways ./shared ./lib/shared.less \
    -e ".*" \
    -i "\\.adoc$" -i "\\.less$" -i "\\.css$" -i "\\.md$" -i "\\.txt$" -i "\\.shtml$" \
    | xargs -n1 -I{} make -j 32

```

I'm using it right now and it's purring nicely.

**Comment by schanzer** [comment]
It would probably be wise to debounce this (throttling for 1-2sec), but I'm not sure how debouncing works in `bash`.

**Comment by schanzer** [comment]
The following steps should do the trick for Sublime users!

**First, we need to define a "build system" for Sublime.** This teaches Sublime what it means to build a project. Fortunately, thanks to @ds26gte , our build system is super simple!

1. In Sublime, select `Tools` > `Build System` > `New Build System...`
2. This will open a new JSON file, which is how we configure the build. Replace the contents of this entire file with the following, and save the file (use the default location):
```
{
	"cmd": ["make","GRAPH=true"], // for default target
	"working_dir": "$folder",
}
```
3. To test this build system, select `Tools` > `Build`. You should see a small window pop up and run the `make` command.

**Next, we need to trigger a build on any save event**
1. In Sublime, open Package Control
4. The Package Control modal window pops up. Type "install package"
5. After a few seconds' pause for Sublime to download the most up-to-date package list, you'll get a text prompt
6. Type `SublimeOnSaveBuild`, and hit Enter. This will install the package.
7. From the `Sublime Text` menu, select `Settings...` > `Package Settings` > `SublimeOnSaveBuild` > `Settings - User`
8. This will open a new JSON file, which is how we configure the package to tell it which types of files should trigger a build. Replace the contents of this file with the following, and save the file (use the default location):
```
{
    "filename_filter": "\\.(css|js|less|scss|rkt|adoc|lua|shtml|txt)$",
    "build_on_save": 1
}
```

To test it out, try opening any lesson file, make a small change, and save!
