### ISSUE TITLE
Introduce Circles of Evaluation in contracts-tables-displays

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1350]
This came up in a big way in today's PD.

Teachers were diving into combining `sort` with `first-n-rows`, and having a lot of success. They LOVED the problem statement at the bottom of [the last workbook page](https://bootstrapworld.org/materials/fall2023-beta/en-us/lessons/contracts-tables-displays/pages/functions-for-tables-cont.html), but wanted more complex examples to test their skills. As soon as they learned how to make displays, they realized they could make more complex examples by combining displays with `sort` and `first-n-rows`:

- "I want a box showing the weight of the 20 youngest animals"
- "I want a bar chart showing the species of the 10 heaviest animals"
- etc, etc...

Remarkably, they really struggled with these! But when I showed them Circles of Evaluation, it was a MAJOR lightbulb. They instantly leveled up and started daring themselves to do much more complicated things.

Afterwards they had LOTS to say about Circles. They wanted more of them, they wanted tons of worksheets with matching activities where circles are matched with code, circles are matched with prompts, etc. They wanted circles with fill in blanks. They want TONS of this.

And this would 100% support the more advanced work they do with `filter` and `build-column` down the line. It's too good to pass up!

Workbooks have gone to print, but we should absolutely add some opt-printables to the mix and bring them up in the lesson plan and slides.

**Comment by flannery-denny** [comment]
How could these two functions work together? What if we wanted to get the four youngest animals?
You could draw a map of how this would fit together and it would look like this.

Workbook page with 3 or 4 prompts. 
Find the 3 oldest this
Find the 4 youngest this.
Contracts at the top of workbook page. 

Sets us up for another workbook page for after students have explored creating displays. 
Make a histogram of the 20 oldest animals showing a distribution of pounds.
Each prompt should either change or add one thing from the previous prompt.
Ask for coe and code.

Make a histogram of animals pounds.
Then make a histogram of animals by species.

**Comment by flannery-denny** [comment]
@schanzer I think I've done everything you asked for with this lesson... and I have a proposal...

You asked for `coe-displays.adoc` to go from 4 to 6 prompts. I'd like to remove the 2 that I've added and put them on a third `opt-printable` page that has those two displays and 2 more without displays... because:

- there's not much room for drawing the circles and they all will have words and 3 circles.
- the structure of all of these is identical 
```
(define exp1 '(bar-chart (first-n-rows (sort animals-table "pounds" true) 16) "sex"))
(define exp2 '(histogram (first-n-rows (sort animals-table "pounds" false) 20) "name" "weeks" 5))
(define exp3 '(box-plot(first-n-rows(sort animals-table "weeks" false) 11) "age"))
(define exp4 '(pie-chart(first-n-rows(sort animals-table "pounds" true) 18) "species"))
(define exp5 '(box-plot(first-n-rows(sort animals-table "age" true) 12) "pounds"))
(define exp6 '(pie-chart(first-n-rows(sort animals-table "pounds" false) 10) "legs"))
```
whereas on the other page it varied more
```
(define exp1 '(first-n-rows (sort animals-table "weeks" true) 10))
(define exp2 '(first-n-rows (sort animals-table "pounds" false) 1))
(define exp3 '(sort(first-n-rows(animals-table 8) "name" true)))
(define exp4 '(count(first-n-rows(sort animals-table "pounds" true) 16) "species"))
```
and I think varying the structure will keep kids thinking more deeply.

lmk which way you want to go.
If you think it's good enough as is, please check code in solutions is corrrect

**Comment by schanzer** [comment]
@flannery-denny  this looks like a terrific start! I fixed two of the solutions, and also pushed some formatting changes that I think will give kids a lot more space to write on the first circle page. If you approve of the change, feel free to make it on the second one as well. 

I'm going to print the books this evening so they can make it to CA by June 1st, so let's see if we can't finalize these asap. Thanks again for moving so quickly on it!!

**Comment by flannery-denny** [comment]
@schanzer is going to reconstruct the 2 workbook pages we discussed for the last section.

Slides and lesson section need to be updated once the 2 workbook pages for this section are complete.

**Comment by schanzer** [comment]
@flannery-denny just pushed the missing wbpage, and made some adjustments to the lesson plan so that the circles feel more closely integrated. Would love to get your feedback when you have a chance
