### ISSUE TITLE
Update description of who Pyret and WeScheme are for

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1351]
Starting Point:

> WeScheme - Simpler syntax, recommended for younger students or students of ANY age when your only focus is math
> 
> Pyret - Python-like syntax. Recommended for older students and/or when you want a smooth pathway into other CS (and Bootstrap!) classes

Recommended replacement ready for weighing in on:

Pyret - Python-like syntax. Recommended for math classes also interested in building pie-charts and other data displays. Also a smooth pathway into more advanced CS classes.

WeScheme -  Simpler syntax. Recommended as an entry point for those looking for a shorter time investment and/or for those focused on making visible the structure behind the order of operations.

**Comment by schanzer** [comment]
@flannery-denny A decent start! Proposed changes:

Pyret - Python-like syntax, which also lets kids work with bar charts, histograms, scatterplots, etc - and gives a smooth pathway into later CS classes - in exchange for a heavier programming lift now.

WeScheme - Simpler syntax, designed to for Bootstrap:Algebra teachers who want to spend the least-possible time teaching programming.
