### ISSUE TITLE
./build-slide should append platform to online exercise file names

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1352]
I'm on `fall2023` in `Functions can be linear`.
The lesson plan says:
<img width="787" alt="Screen Shot 2023-05-05 at 10 33 18 AM" src="https://user-images.githubusercontent.com/66691020/236503099-4aaf437c-b9e2-42cd-8c53-1f7f8d228405.png">

The slide deck says:
<img width="623" alt="Screen Shot 2023-05-05 at 10 35 07 AM" src="https://user-images.githubusercontent.com/66691020/236503437-48b35211-f099-48e3-a325-f838ee558b1e.png">

This is pretty confusing since the two activities look like exactly the same thing! Please make links in slides mirror lesson plan styling. Thanks!

**Comment by schanzer** [comment]
Confirming that this is fixed 
<img width="874" alt="image" src="https://user-images.githubusercontent.com/77126/236683230-a5c9f971-66df-4f4d-975a-73e029b379a6.png">
