### ISSUE TITLE
Address `is-collision` `collide?` discrepancy in wescheme and pyret

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1364]
- FD just changed `collision` lesson plan to use `is-collision` and `collision?` in agreement with functions in the Design Recipe workbook page.
- Then went to double check in a sample game `"sample-game-no-distance-lines":` from the `starter-files.rkt` file and I'm seeing `is-collision` in pyret and `collide?` in wescheme.

Which do we actually want?
We should make it so in 
- [ ] ALL game starter file versions we link to from lessons and resources
- [ ] workbook pages 
- [ ] slides (which have been fixed by hand because the link to the DR page isn't building correctly)
- [ ] slides.md files
- [ ] lesson plan
- [ ] Anywhere else?

**Comment by schanzer** [comment]
@flannery-denny `is-collision` is used in Pyret, and `collide?` is used in WeScheme. We do NOT want to use the same for both.
