### ISSUE TITLE
Improve spec and functionality of `opt-project` directive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1365]
- [x] @project and @opt-project directives should ALL resolve to: `<span class="prefix">Project:</span> <a href="">ProjectName</> [<a href="">Rubric</a>]`
- [x] Audit all uses of these directives in printed materials to make sure they look right
- [x] (Flannery) Fix slides that use opt-project
---
Opt project does what we want it to do in the materials section, where it is preceded by the words `optional project` but it's strange that the word project doesn't appear along with titles to links on slides and in the lesson plan.

<img width="500" alt="Screen Shot 2023-05-12 at 12 21 35 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/08ad025a-8ac9-4ad6-b706-31582c35d070">
<img width="378" alt="Screen Shot 2023-05-12 at 12 21 24 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/9cae46ae-cb79-4159-9b70-eafa330866c4">
<img width="786" alt="Screen Shot 2023-05-12 at 12 21 43 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/2589480c-73a4-4800-9b2b-5c81ff8a3b0f">
<img width="673" alt="Screen Shot 2023-05-12 at 12 21 58 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/cd9ce3a6-3aa7-422f-bfe7-16e00e0bbe61">

**Comment by ds26gte** [comment]
They are not comparable. The opt project items in the Materials section of the lesson plan are autoinserted, harvested form `@opt-project` calls in the body of the lesson plan. The places where `@opt-project` is actually called in the lesson plan, they work
exactly as they do in the slides, with no extra annotation.

**Comment by schanzer** [comment]
@ds26gte it sounds like Flannery wants these prefixes to be statically generated when used in a lesson plan or a slide deck.

**Comment by schanzer** [comment]
Google Slides doesn't support advanced CSS like ``::before{ content: ...;}`, so unfortunately that will need to be manually inserted for slides.

In the lesson plan, I suppose you _could_ add the same class name to the link that you use in the aggregated materials list. That would certainly provide a more consistent look and feel

**Comment by flannery-denny** [comment]
I’d actually suggest we talk about it before @ds26gte works on it. That’s why the issue says improve specFlanneryOn May 15, 2023, at 9:46 AM, Emmanuel Schanzer ***@***.***> wrote:﻿
Google Slides doesn't support advanced CSS like ``::before{ content: ...;}`, so unfortunately that will need to be manually inserted for slides.
In the lesson plan, I suppose you could add the same class name to the link that you use in the aggregated materials list. That would certainly provide a more consistent look and feel

**Comment by flannery-denny** [comment]
Update slides.md files for
- [ ] advanced displays
- [ ] bar and pie charts
- [ ] box plots
- [ ] data collection
- [ ] linear regression
- [ ] probability / inference
- [ ] threats to validity

**Comment by ds26gte** [comment]
Please note that there is no `@project` directive, only `@opt-project`.
