### ISSUE TITLE
Remove [.lesson-point] instances that are numbered or bulleted

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1369]
Sometimes we use [.lesson-point] to state a key idea **the very first time it appears**, and then we elaborate on and explain the key idea. This usage makes [.lesson-point] look like a section header.

Other times, we use it to emphasize a key point that has already been made, meaning that it comes **after** a longer explanation.

I prefer the 2nd usage, but sometimes it can be challenging to format lessons this way and feels like it builds in redundancy. We should get on the same page here.

Pasting in a few examples that feel off to me, where [.lesson-point] is not doing what I believe it is intended to do. 

From probability-inference:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/e5ddd12a-ea14-4747-8c2d-f880170501cd)

From table functions:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/57eff196-3908-4db3-8930-0a3f141cf1a6)

functions-examples-definitions:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/0548b472-8b10-4f67-9395-2d67ffa3b5e5)

**Comment by flannery-denny** [comment]
@schanzer @retabak I would like to suggest that we look at the 4 different views of each lesson plan that IM provides as part of this discussion

- [Lesson Plan](https://curriculum.illustrativemathematics.org/HS/teachers/3/1/1/index.html)
- [Preparation](https://curriculum.illustrativemathematics.org/HS/teachers/3/1/1/preparation.html)
- [Practice](https://curriculum.illustrativemathematics.org/HS/teachers/3/1/1/practice.html)
- [Student Lesson](https://curriculum.illustrativemathematics.org/HS/students/3/1/1/index.html)

**Comment by retabak** [comment]
Okay, I attempted to remove all uses of [.lesson-point] that:
- included numbered text
- included bulleted points
- included a long paragraph
- were being used as a section header

This was not a deep dive, but a scan of search results for egregious misuses. So, keep an eye out and try to use [.lesson-point] properly in the future!
