### ISSUE TITLE
Finding misconceptions in PD

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1373]
- [x] Develop a SHORT survey for DS. Emped in PD Decks. 
- Focus on 1) Histograms and Box Plots 2) Misreading Linear Regression -> correlations
- [x] Develop a SHORT survey for Algebra. Embed in PD Decks 
- Focus on Functions? Partial Functions?

**Comment by flannery-denny** [comment]
@schanzer @retabak Here's a[ set of draft questions](https://forms.gle/mqK2DpTpBGvnUbAQ6) addressing:

- misconceptions about bar charts & histograms
- box plots
- correlation

Feel free to edit or make suggestions.

There are other items in the issue description which we did not discuss, so I haven't addressed them.

**Comment by schanzer** [comment]
@flannery-denny I like these a LOT! I've made some small wording changes and added another statement to the histogram/bar-chart set, but otherwise these look terrific.

I see a question here about correlations, but not linear regression per. Didn't we decide we'd focus on LR?

**Comment by retabak** [comment]
I only have minor comments: 

One of the options for Q2 is "The average (mean) value in this dataset is 5.5." 
Why / how did you choose 5.5? I think that 4.8 might do a better job of revealing misconceptions.

And, the last question feels the least interesting / revealing to me. I just looked in our correlations lesson plan, and we outline three misconceptions, which might be helpful to consider in designing a question:
- Students often conflate strength and direction, thinking that a strong correlation must be positive and a weak one must be negative.
- Students may also falsely believe that there is ALWAYS a correlation between any two variables in their dataset.
- Students often believe that strength and sample size are interchangeable, leading to mistaken assumptions like "any correlation found in a million data points must be strong!"

Final note - are we going to have Shriram review these? Seems like something he would likely have a strong opinion about (and I know he was very interested in teacher misconceptions).

**Comment by retabak** [comment]
Ah, I missed that. That's fin with me..... except:

I think there is an argument to be made about focusing on correlations. I wonder if there are teachers that haven't even had _any exposure_ to LR at all - therefore they might have just plain old lack of knowledge rather than misconceptions.

**Comment by flannery-denny** [comment]
@retabak 

- I picked 5.5 because it is the mean of 3 and 8. 
- I made the last question to get at the misconception that strength and direction are connected.
- agreed that misconceptions about correlation seem more important to assess than misconceptions about lr, but I will think about drafting something for lr.

Happy for Shriram to weigh, but we'd probably need his feedback by tomorrow morning in order to be able to address it and embed questions in slides before Monday. @schanzer?

**Comment by flannery-denny** [comment]
@schanzer fyi Part of why I think misconceptions with correlations are more important than with lr is that we have a long list in one lesson and not in the other.

**Comment by schanzer** [comment]
@flannery-denny I'm sold. Let's stick with correlations, adding in @retabak 's suggestions.

When you've made the changes, email Shriram, Kathi and JoJo for feedback -- and be sure to emphasize how time-sensitive this all is!

**Comment by flannery-denny** [comment]
@schanzer we've made the assessment for DS. The original issue said we needed one for other things, but we only specked DS. Please clarify what else needs to be done or close the issue if it morphed and has been completed. Thanks!

**Comment by schanzer** [comment]
@flannery-denny we also need something for Algebra, ideally focused on functions. Lots of misconceptions to be thought of here. We can discuss next week, but you likely have ideas cooking that can be put to draft use ASAP

**Comment by flannery-denny** [comment]
@schanzer do you have clarity on what the Algebra misconceptions should focus on? or should we make a time to discuss?

**Comment by schanzer** [comment]
We'll try to make time, but for now:

- [ ] Rigidity for the order of operations. 
- [ ] Functions as having multiple representations
- [ ] Syntax-bound thinking (e.g. - what is the name of the function in `x(f) = 2f - 1`?, is `+` a function? why or why not?)
- [ ] Thinking that functions have to be complete (ie - must be defined over the whole domain)

**Comment by flannery-denny** [comment]
@schanzer @retabak Planning to email a draft of [this pre-pd diagnostic](https://docs.google.com/forms/d/1fgMQmfzNQimixyA1qLaRT1sKbHv5g3199RkISai_708/edit) to Kathi and Shriram today. 

Please lmk if there's anything you'd suggest adding or changing.

@schanzer lmk if you think this is close enough that it's worth drafting a post-pd diagnostic.

**Comment by schanzer** [comment]
@flannery-denny once we have a post-diagnostic for Algebra, I think we're ready to close.

**Comment by flannery-denny** [comment]
@schanzer 
pre-pd terminology survey: [https://docs.google.com/forms/d/1fgMQmfzNQimixyA1qLaRT1sKbHv5g3199RkISai_708/edit](https://docs.google.com/forms/d/1fgMQmfzNQimixyA1qLaRT1sKbHv5g3199RkISai_708/edit)
post-pd terminology survey: [https://docs.google.com/forms/d/1YYwlnbQc_4pNFMxa_KHSljPCrHEKQ-l3hTgCQxI0Rns/edit](https://docs.google.com/forms/d/1YYwlnbQc_4pNFMxa_KHSljPCrHEKQ-l3hTgCQxI0Rns/edit)
