### ISSUE TITLE
Pedagogy box: limitations of vertical line test?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1381]
I'm doing the Oklahoma prework, including reading this [article](http://files.mathematicalthinking.org/bootstrap/oklahoma2019/ess-und-functions_chapter-1.pdf).  The authors outline three common misconceptions related to student understanding of functions. One of these is that, "They may rely on superficial or misleading indicators, such as the so-called vertical line test, to determine whether they are in fact dealing with a function" (p. 18). The authors elaborate on this claim in detail (see p19-22). 

Given that we're heavily emphasizing this notion with the OK cohort, I wonder if we ought to add a pedagogy box or something to the "Vertical Line Test" concerning the limitations of the vertical lin test? (These limitations were entirely new to me!) Just a thought...

**Comment by flannery-denny** [comment]
Having read the article, I would consider adding a small pedagogy box that acknowledges something like the following.

> Note: Use of the vertical line test is contingent upon restricting ourselves to functions where the domain is composed of x-values and the range is composed of y-values. Once students are exploring questions about whether ‘x is a function of y’  (an important question for Alg 2 students thinking about inverse functions), they will need to make use of other strategies.

I disagree with the idea that the problem with students who are confused about whether or not the caterpillars path can be represented by a function with location graphed against time is a result of the vertical line test. 

And I also disagree with the idea that the vertical line test poses a problem with determining whether or not a function is a circle, given that one could switch to polar coordinates. Graphing a circle using cartesian coordinates is a different conversation than graphing a circle using polar coordinates.

**Comment by retabak** [comment]
FWIW, I think there's more nuance in the article than you're conveying re: the caterpillar and the circle, but would agree that these are very niche examples and need not be mentioned.

That said, I'm fine focusing on the excerpt you've highlighted! I think it is the most accessible.

**Comment by schanzer** [comment]
@retabak make it so! 🚀
