### ISSUE TITLE
create more function composition worksheets using algebraic functions

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1391]
At PD, several folks had a tough time with this page:
https://bootstrapworld.org/materials/fall2023/en-us/lessons/function-composition/pages/diagramming-function-composition.html

I wanted to offer additional practice, and was surprised to see that... we don't have any! This felt surprising because composing functions in Pyret gets SO MUCH attention. It deserves more coverage! I also think translating between different representations would be valuable.

I think we could easly make variations on this worksheet where we start by providing different information--i.e., fill in only the second column, fill in only the operatoins, fill in only evaluating for x.

**Comment by flannery-denny** [comment]
@retabak I'm glad to see you like the idea of that page. When I built it, it felt like a breakthrough. It'll be a good exercise to revisit that lesson and expand upon it.

**Comment by flannery-denny** [comment]
@retabak I've pushed 2 new pages. Curious if you think that will satisfy the request for now or if you were looking for lots more. Close if you're satisfied.

**Comment by retabak** [comment]
Love these! They are exactly what I was hoping for and would have been perfect to support the teachers who needed a bit more practice. Closing :)
