### ISSUE TITLE
PD prep 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1397]
- [x] Create slide deck of extra PD-specific slides (including chart paper activities, pre/post diagnostics, implementation options, [implementation planning](https://docs.google.com/presentation/d/1_h4yvbJxUU8l8ohEhRDHgrd5_jnX6RL7G5rDW6Twhm8/edit)
- [x] Develop scripts to accompany opening slides
- [x] https://github.com/bootstrapworld/teacher-training-and-support/issues/9
- [x] Develop list of PD materials needed (i.e., chart paper, markers, extension cords, BS stickers, laminated posters)
-  ~Timestamp youtube videos of PD by lesson~

**Comment by retabak** [comment]
@schanzer [here's what I've done so far.](https://drive.google.com/drive/folders/1RJvplCVVQma1zpAFVvecx7POE3qWc-la?usp=drive_link)

Some thoughts:
- I know you don't like numbering lessons, and I'm fine with that. Just doing it for now to help me keep track of things. (That said, if I'm someone trying to learn how to run PD, it might be nice to have everything appear in the folder in the order in which it will be presented?)
- The most important parts for facilitators - and the thing that does not at the moment exist - are the "Connect to Classroom" sections, which I can make slides for as well.
- I'm thinking also of creating a section for each lesson called "essential workbook pages" - which highlights pages that cannot and should not be skipped.
- I will also add activities that are just for in-person PD, like the chart paper activities.
- I'm scripting out the direct instruction, which might not be needed, given that basically exists in the lesson plans that are on our website. Still, it's kind of nice to see the entire flow of how things might unfold during PD. Let me know if you think this is something I should continue spending time on or not. I am okay going either way.

**Comment by retabak** [comment]
@schanzer -

[opening slides](https://docs.google.com/presentation/d/1OHRJRWWFlwviTwmBGtzOvOodgF2_YRJjB7viUi7llUY/edit?usp=sharing) for DS (1-10) + Algebra (11-20)

**Comment by schanzer** [comment]
Framing for opening slides:

- Datacentric Function Design
- Integrating Computing into Traditional Subjections
- Supporting the Learning that is in the room
- Teach students how to think about problems
- I’m not here to teach you data science - our purpose is to teach you how to teach it
- Notice & Wonder
- We don’t expect you to be programming masters, so part of this is being vulnerable in front of your students!
- Bootstrap is not a “turn-key” experience. Can’t be! That means you’ll need to make it your own, and that will take time that will extend beyond this PD.
