### ISSUE TITLE
Could we make @star work in lesson plans?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1401]
Here's an example of where I would use it in the Function Notation lesson

> [.lesson-instruction]
> - Turn to @printable-exercise{pages/function-notation-substitution.adoc}.
> 
> @star For more challenging function notation evaluation exercises turn to @opt-printable-exercise{function-notation-challenge.adoc}

Currently @star disappears the line of text

**Comment by schanzer** [comment]
@ds26gte hopefully a straightforward addition!

**Comment by ds26gte** [comment]
![image](https://github.com/bootstrapworld/curriculum/assets/3708729/9006f595-a527-490c-afc6-2f5cf45f632a)

`@star` seems to work for me already. What up?

**Comment by flannery-denny** [comment]
Not sure why it wasn't working before... Thanks!
