### ISSUE TITLE
Consider whether we should revise the DR Rubric?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1402]
[from Teacher Resources page](https://docs.google.com/document/d/10YYUmMbE77VwC3W24yZykZe1I0ELL_jE2_NQyH473MY/edit)

At the very least I'm guessing we could shift this away from the deficit model, but I'm curious what @retabak would have to say about this.

**Comment by retabak** [comment]
Done! https://github.com/bootstrapworld/curriculum/commit/dd42025762277b088f8263aaeaa56be0751f039f

Closing this issue.
