### ISSUE TITLE
Develop a SHORT survey for Early Math. Embed in PD Decks

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1406]

**Comment by retabak** [comment]
I replied to some of your comments and added a question. Let me know what you think!

**Comment by schanzer** [comment]
@retabak back to you!

**Comment by flannery-denny** [comment]
@retabak Before we wrote the other pd misconception surveys, we made a list of misconceptions we wanted to address. Could you please tell me what those were for early math?

**Comment by flannery-denny** [comment]
@retabak still waiting to hear what the goals of these assessments are before replying to your comment in the doc.

**Comment by retabak** [comment]
https://docs.google.com/document/d/1P7lzc-OET0JcsvlKPzao4aN_HxO0RQK2WTbkRrStD1s/edit

played around with this, added misconceptions being addressed!
