### ISSUE TITLE
Better error-checking for typos in lesson-order.txt

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1407]
Here's @ds26gte's summary (from slack) of some glossary issues I encountered:

@retabak reported an error in which the Glossary link from the early-math course was showing an empty page. Turns out that the problem is because the name of one of the lessons in early-math's lesson-order.txt was typo'd. While I have pushed the fix, the error seems too drastic. Perhaps the relevant error code in bootstraplesson.js should be rewritten to be a graceful warning instead.

**Comment by schanzer** [comment]
@ds26gte this can't happen at runtime -- if we're going to show the author a warning, it _must_ happen at compile time via racket or lua
