### ISSUE TITLE
investigate "Zoom Events"

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1408]
I couldn't figure it out, I think because I don't have admin priveleges. Maybe you can?! 

(Making this an issue mostly so we don't forget about it.)

**Comment by schanzer** [comment]
Zoom events and sessions are two different things. Both cost $100 or more _per event_. While they do add some nice features, they also add complexity on the backend in terms of accounting and bookkeeping. 

@retabak We'll still to Eventbrite for coaching sessions.
