### ISSUE TITLE
make a workbook page for choosing the right bin size from histograms

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1414]
There's a large amount of instruction in the histogram lesson that would work better as a workbook page. make it so. Add as @opt-printable exercise for 2023. add as printable-exercise for 2024. Then add histograms to grade level pathways per #1374.

**Comment by flannery-denny** [comment]
@schanzer I made some edits to the lesson because adding this workbook page revealed some disconnects for me.  Please confirm that the changes work for you.

If you're satisfied, I'll check with Rachel that this is ready to be added to middle school grade specific pathways.

**Comment by schanzer** [comment]
@flannery-denny This looks good! I made some small changes to deal with formatting problems when the page is built and printed. If you're OK with them, feel free to close.

**Comment by schanzer** [comment]
@flannery-denny I'm happy with this page. OK to close, or is there more work you have in mind?
