### ISSUE TITLE
audit early math to see where spiraling exists

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1416]
Is it possible to make spiraled worksheets optional?

**Comment by retabak** [comment]
Start of audit (incomplete now):

- [ ]  Associative Prop: could make last section optional and then it would not need Commutative Prop as a prereq

-

**Comment by schanzer** [comment]
@retabak adding comment from Slack: 

_I think it’s fine to leave it as-is. Until we have more than 0 users, I think more at this point it’s unproductive guesswork 😉_
