### ISSUE TITLE
In standards alignment page, add a link back to the standards' websites

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1425]
We already store these links (see `lib/maker/read-alignments.lua`), but don't push them through to the dependency graph or dictionaries.

- [x] Dorai, we need to project these links (and the full standard name) out into the distribution directory
- [x] Emmanuel, we need to render that info on the standards alignment page

**Comment by ds26gte** [comment]
Which file (dependency-graph.js or dictionaries.js) do you want this info going to and in which format (JSON field)?

**Comment by schanzer** [comment]
@ds26gte to minimize the changes to the current JSON structure, here's what I propose: **add a "__metadata" field to each dictionary**

```
    "CC-ELA": {
      "__metadata": {
        "fullname": "Common Core ELA Standards",
        "url": "https://........",
      },
      "WHST.6-8.1.A": {
        "description": "Introduce claim(s) about a topic or issue, acknowledge and distinguish the claim(s) from alternate or opposing claims, and organize the reasons and evidence logically.",
        "lessons": []
      },
      "WHST.6-8.1.B": {
        "description": "Support claim(s) with logical reasoning and relevant, accurate data and evidence that demonstrate an understanding of the topic or text, using credible sources.",
        "lessons": []
      },
```
