### ISSUE TITLE
new glossary format causes regressions in quoted text

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1426]
@ds26gte  - I noticed that things typed into the glossary like `\"this"\` disappear!

Example 1:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/d6044a0f-e223-4bbd-9a44-742aaae7b748)

Example 2:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/2b4b16d8-4be6-44bd-873a-69a65422b434)

**Comment by schanzer** [comment]
@ds26gte is amazing.🧙🏽‍♀️
