### ISSUE TITLE
In Pyret, avoid decimal use for count (y-axis) when only wholes are represented

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1429]
In a breakout room at PD, someone commented that "Pyret isn't very smart" because there aren't just whole numbers on the y-axis of this bar chart showing animals' weights.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/ecd34856-dbae-41a2-b4c1-08773ce63b7a)

**Comment by schanzer** [comment]
@retabak looked into this - this gets deep into the bowels of Google's chart API, and I just don't think we have the bandwidth to address it.
