### ISSUE TITLE
live on the web - glossary terms are small

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1440]
<img width="375" alt="Screen Shot 2023-07-28 at 11 47 09 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/55ab8b09-9772-468b-9c0f-2342d90f42d2">

I'm seeing this here: [https://bootstrapworld.org/materials/fall2023/en-us/lessons/contracts-tables-displays/index.shtml?pathway=data-science](https://bootstrapworld.org/materials/fall2023/en-us/lessons/contracts-tables-displays/index.shtml?pathway=data-science)

**Comment by retabak** [comment]
The glossary terms are now the right size, but the word "Glossary" is still too small!

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/c2f5ec80-8ada-45ae-bd7d-e99ba8f2a02b)
