### ISSUE TITLE
consider alternate contract formatting for lower grades using fitbruby code

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1441]
### Updated spec

When using `(contract....)` in extended (named-variable) form, we should generate fitbrubies instead of the extra double-colon notation:
![image](https://github.com/bootstrapworld/curriculum/assets/77126/9bab5fb9-922e-4d00-8553-83621bc1186a)

Example can be found in `contracts-tables-displays/pages/functions-for-tables.adoc`

### Original
I need to provide a sixth-grade friendly contract for histograms. I'm not convinced that either the basic contract or the advanced contract below is sixth grade friendly
<img width="252" alt="Screen Shot 2023-07-28 at 11 44 39 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/73852c9a-ff13-4550-8e31-9d007ad6f2c5">

In [Contracts: Making Tables and Displays](https://bootstrapworld.org/materials/fall2023/en-us/lessons/contracts-tables-displays/index.shtml?pathway=data-science) we use `@fitbruby` to provide additional scaffolding around code
<img width="735" alt="Screen Shot 2023-07-28 at 11 49 20 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/658a4d4c-2eba-4c21-bbf4-d28fcb88b070">

I am tempted to use this to provide contracts with the data type below the line and the description above the line, something like this.

<img width="525" alt="Screen Shot 2023-07-28 at 12 08 56 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/1708737e-f9ff-4116-b5d6-6e600dec9ca0">

Thoughts?

Once we address this, revisit #1414 and #1374

**Comment by flannery-denny** [comment]
@schanzer I'm adding this to the curriculum meeting agenda for discussion because:

- I wonder if you have objections
- I wonder whether we should build infrastructure to do this rather than have me use `@fitbruby`

If, however, you love this and are clear that we shouldn't build infrastructure to do this, lmk and I can move #1414 and #1374 forward

**Comment by schanzer** [comment]
My concern here is that we're introducing yet-more notation, and this is a notation that deliberately blurs the line between contracts and code. I'm not _opposed_ to it, but I think if we add this we need to subtract something else. 

What notation should this replace?

**Comment by flannery-denny** [comment]
@schanzer How about replacing the expanded form that's screenshotted in the issue description? 

We don't have a directive for that format yet, anyway... it currently requires authors to write all of the following

```
++++
<style>
#content img { width: 50%; }
#content .forceShadedBlockWTF { background-color: #f7f7f8; }
.highlight { padding: 0 !important; }
</style>
++++

[.forceShadedBlockWTF]
--
@show{(code 'histogram)}`{two-colons} (`
```
	table-name :: Table,
	labels :: String,
	column-name :: String,
	bin-size :: Number,
) -> Image

```
--

```

**Comment by flannery-denny** [comment]
@schanzer If you're able to let us know whether I should implement this using existing `@fitbruby` capabilities or talk to @ds26gte about an expanded contracts directive, that would help me to be able to move forward in either direction. Thanks!

**Comment by flannery-denny** [comment]
@schanzer If we understand you correctly, the proposal is to modify existing code

`@show{(contract 'sort '((table-name Table) (column-name String) (order Boolean)) "Table")}`

which currently renders as follows

<img width="812" alt="Screen Shot 2023-08-02 at 10 35 21 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/a63e314f-8486-4c25-a05e-3391aa8eb753">

so that it renders in the following format instead
![image](https://github.com/bootstrapworld/curriculum/assets/66691020/3c0f54c3-a6ef-40fd-82a7-8a21c668c354)

@ds26gte is wary of this and would prefer to use a different directive like

`@expanded-contract{sort ((table-name Table) (column-name String) (order Boolean)) Table)}`

because the thing we're asking for isn't pyret code

We are tabling the discussion and further work on this until our full team meeting next week.

The above example was found in `contracts-tables-displays/pages/functions-for-tables.adoc`

**Comment by schanzer** [comment]
@ds26gte Flannery and I spoke, and we'd like to have you implement _this_ out on a feature branch:

![image](https://github.com/bootstrapworld/curriculum/assets/77126/d99b51be-9c0b-41f5-af2c-7e015fc9f7c7)

This represents a slight tweak from Flannery's original proposal.

Let's _start_ by having this branch implement the proposal as a separate directive - but temporarily alias the existing `contract` function to point here. In the case of simple (un-named variable) contracts, the behavior will be unchanged. But in the case of extended (named variable) contracts, we will generate underlines and rubies.

**Comment by schanzer** [comment]
@flannery-denny if you're satisfied with Dorai's work here, is it ok to merge his branch into master and close the issue?

**Comment by flannery-denny** [comment]
@ds26gte I'm so excited about this! 

One nit which may or may not be addressable. Because the ruby text is of a smaller font-size than the text above the fitb, 10 character below and 10 characters above do not require the same fitb length. 

<img width="927" alt="Screen Shot 2023-08-13 at 1 51 17 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/11b66dd8-bc2d-4fba-90e5-cf1f7a5bc307">

Feel free to merge once you either address or decide not to address that.
