### ISSUE TITLE
on web - some lessons incorrectly showing up 2x on "build your own lesson" page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1442]
https://bootstrapworld.org/materials/fall2023/en-us/#BuildYourOwn

Some duplicates: surface area, combinations, permutations, computing needs all voices

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/72f83aa9-42ad-4c7d-9591-b0204fc0c18a)

**Comment by retabak** [comment]
Now, the "build your own feature doesn't work at all. No lessons appear no matter what word I type in. There are also no lessons if I leave the search bar blank.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/c9b2a56e-473b-41d3-b3ec-0e1015d9e34b)

**Comment by schanzer** [comment]
@retabak have you refreshed? This works for me.

**Comment by retabak** [comment]
I had not refreshed! Sorry. It's all good now.
