### ISSUE TITLE
on web - yikes, egregious error for hoc-wescheme-intro

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1444]
Clicking the link under Intro to Graphics on [this page](https://www.bootstrapworld.org/materials/fall2023/en-us/courses/hour-of-code/) brings users to [this page](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/hoc-wescheme-intro/index.shtml) (screenshot below):

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/a568e5d7-4d53-4b7b-8e92-6ce8c916aed1)

**Comment by schanzer** [comment]
Fixed by the wizard!
