### ISSUE TITLE
dataset table in choosing your own dataset is in miniature font - assuming that's a bug?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1446]

**Comment by schanzer** [comment]
@flannery-denny good catch! I've been slowly rolling out the CSS work to merge print and screen wbpages, hoping to never have all that much break at once. Rachel did a ton of vetting before I rolled it out, but (clearly) there have been a few places where it still isn't ready for prime time.

I've fixed the issue and updated the css-size branch
