### ISSUE TITLE
All Textbook alignment links are broken on Algebra Teacher Resources Page

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1447]
https://bootstrapworld.org/materials/fall2023/en-us/textbooks/IM-HS.html

**Comment by flannery-denny** [comment]
@schanzer if you can tell me what page you found this link on, I can probably fix it. We don't have a HS alignment, just alg1 and alg2
<img width="269" alt="Screen Shot 2023-08-02 at 1 17 53 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/33ec9949-229b-4053-a522-91a57ef230cb">

**Comment by schanzer** [comment]
@flannery-denny this is in the teacher resources section for Alg1, where all the textbook alignments are

**Comment by flannery-denny** [comment]
@schanzer tried to fix this, but I can't make sense of what's going on. 

- File names in distribution do not match filenames in the textbook folder.
<img width="278" alt="Screen Shot 2023-08-02 at 3 51 50 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/202db2c2-0403-40eb-8122-3afd997d8197">
<img width="267" alt="Screen Shot 2023-08-02 at 3 51 31 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/00838ecf-7395-4cca-ae56-ec1be84ccb7e">
- Image sizes on pdfs are very large and therefore blurry, which is not how we left off with them.

**Comment by schanzer** [comment]
@flannery-denny Looks like a deployment issue, which I've now fixed.

JFYI - you need to look in shared/langs/en-us/docroot/textbooks.
