### ISSUE TITLE
live on web! - standards for DS lessons are not appearing AT ALL

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1448]
Algebra is fine, somehow. Core lessons have standards alignment when they appear in algebra but not when they appear in DS. Here's a screenshot from [Bar & Pie Charts](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/bar-and-pie-charts/index.shtml?pathway=data-science).

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/80f068e5-cf50-4aad-b87f-7ced6cc3e7e8)

**Comment by schanzer** [comment]
@retabak Here's a screenshot from the same link you posted:
![image](https://github.com/bootstrapworld/curriculum/assets/77126/86418e93-782c-4284-995f-532c2bdfdd45)


Are you sure you're not loading from cache?

**Comment by retabak** [comment]
Turns out I was loading from cache.

Closing. sorry for the false alarm!
