### ISSUE TITLE
Update and Improve "Exploring a Dataset" template 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1451]
When I did PD in July, I was wondering if there was a reason that the "exploring a dataset" template didn't have separate sections for students to make each type of display. There's a section at the top that says, "By the end, you should have at least one..." but only one section to add ALL of those displays.

As a student, this creates challenges. It results in kids producing a whole bunch of displays in one section of the document (as I did, during July PD). When students think they are done, they need to go back and confirm that they have indeed created one of each display. They could quite easily leave one out. It also gives them decision paralysis -- like, "WHAT SHOULD I MAKE NOW?"-- and feels unstructured and too open-ended.

As a teacher, I would also find this annoying. When grading, the charts would all be in the wrong order so I would need to be a detective to figure out what's missing. If there were multiple sections, every kid would have the displays in the same order, and they would be less likely to accidentally omit displays.

Thoughts, @schanzer or @flannery-denny ? Is there a reason we made it the way that it is?

**Comment by schanzer** [comment]
@retabak really good call here. We should explicitly leave space for every possible chart type. Is something you can take on?

**Comment by flannery-denny** [comment]
@retabak I don't have strong feelings about this, but I'm a little concerned about the document becoming even more cumbersome than it already is as a side effect.

We scaffolded the blue sample text in direct response to lots of papers that made displays without thinking about them. I'd like to avoid additional examples if possible.

Here's an [old version](https://docs.google.com/document/d/1NRnVs_E84tHVaKuZd-5nkk9X-dyPmNJSjHbwTVFeWRY/edit#heading=h.mi48l0z1krk1) for comparison.

I wonder if perhaps there's a better way to use our technology to help make subsections more visible?
- if my students were getting lost, I might provide them with a slide template to complete rather than a doc for this kind of thing 
- In my personal recipe docs, I use a table of contents with bookmarks to make it easier to get between sections

Think we should consider either of those options?

**Comment by schanzer** [comment]
@flannery-denny I think a slide format is _fantastic_ for this! Breaking things up into slides makes it much less overwhelming for kids, while also providing maximum space for visuals.

It also provides a nice option for those who want to have their students do their research projects as presentations rather than papers, and also instantly allows student pairs to "present" their initial explorations to the class in a public way.

We did get quite a few comments from teachers in PD this summer than all the blue text is overwhelming and over-scaffolded. I think the slide template would also help reduce the "blue wall" effect we have going on right now.

**Comment by retabak** [comment]
I like the slides idea, too. Here's one more idea:

I'm working on various scripts for facilitators to learn how to facilitate PD. I learned that if you make a document "pageless" (under File -> page setup), then the sub-sections become collapsible and expandable. [Here's an example](https://docs.google.com/document/d/1jt7DvEmBv18heqZy9gZCgJfLCSMF-ThnOShFFzgQdQ4/edit#heading=h.ws2a3klvhz86).

**Comment by flannery-denny** [comment]
Cool! Looks a little more formal than kid-friendly...
How about we take advantage of both!

- make the Exploring a Dataset file into slides? 

- And the Research paper template into a pageless document?

**Comment by schanzer** [comment]
Yes! yes to all of this!

**Comment by flannery-denny** [comment]
@retabak are you excited about working on this? Or would you like me to take all or part of this on?

**Comment by retabak** [comment]
@flannery-denny - I am happy to do it, but am not particularly excited about it. I was wondering if it would make more sense for you to have a go, given that you worked on previous iterations and I did not. In other words - it's all yours if you'd like!

**Comment by retabak** [comment]
Noting here that @schanzer and I discussed this today and have another idea for improving the exploration paper template!

We think the exploration paper should ask “what question does this display answer?” instead of “what does this display tell us?” Then, follow up with, "What is the answer to that question?"

We felt like this gave kids an opportunity to run the data cycle _in reverse_ as a scaffold to actually developing their own questions and considering how to answer them (which is far more challenging).

**Comment by retabak** [comment]
I just reviewed all the lessons where we have "Your Analysis" sections (see my notes [here](https://docs.google.com/document/d/1Aq-EPY-UKkvuggtGrkUgmLLIwg55x1elst5lcEsfR9c/edit), if interested), and have two suggestions for that we might want to add during this exploration paper revamp:

- [ ] There's a "your analysis" section in the Correlations lesson, but no mention of the exploration paper. Do we want to have students write down a statement or two of correlation in the exploration paper? (Maybe like [this](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/correlations/pages/correlations-in-my-dataset.html)?)

- [ ] There's a "your analysis" section in the Threats to Validity lesson, but no mention of the exploration paper. Do we want to have students add some threats to validity in their exploration paper? (Maybe like [this](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/correlations/pages/correlations-in-my-dataset.html)?)

**Comment by flannery-denny** [comment]
Thanks @retabak. Wondering whether what you're working on is likely to turn up more thoughts on this or you're ready for me to begin to synthesize the ideas?

**Comment by retabak** [comment]
@flannery-denny 

I just spent more time going through lessons and updating this [document](https://docs.google.com/document/d/1Aq-EPY-UKkvuggtGrkUgmLLIwg55x1elst5lcEsfR9c/edit) and I do not think any more thoughts will turn up. 

I've updated the comment above (which had a 2-item checklist.... it is now 5 items) and think it's time for you to begin! I actually was thinking that it would be nice to refer to / specifically reference the exploration paper template as I'm updating the "Your Analysis" sections... so I don't see any reason to wait! This is the most important thing I'm working on now, which I think is very important. If any of my comments are confusing, let me know. Happy to discuss over zoom / phone.

**Comment by flannery-denny** [comment]
@schanzer @retabak [Here is the link to the Exploring a Dataset slide deck](https://docs.google.com/presentation/d/1WNSuO7dlMahelCKXJWBZ92UZRy1ZSS4t_gZW4dXfaJ4/edit?usp=sharing). I think it is a servicable improvement, although it does not meet Rachel's request to be completely restructured around the lesson order as I had already implemented the plan from last week before finding that request and she clearly has a massive lesson-structure overhaul in mind that is deeply intertwined with this and they need to be tackled in tandem. Turning my attention to the paper.

**Comment by schanzer** [comment]
@flannery-denny do you mean the research paper or the exploration paper?

**Comment by flannery-denny** [comment]
@schanzer as I understood our plan, we're replacing the exploration paper with the slide deck I shared and the only change I'm making to the research paper is to make it pageless.

Then the work of updating links and references to
them kicks in...

Please lmk what you think of the deck.

I woke up wondering if we should amend the display slide template to get rid of the table cell that says display at the bottom and add the display type to the display title (much larger font, so it's more visible for someone scanning the deck)

**Comment by schanzer** [comment]
@flannery-denny looking good! I left a few comments in the deck.

You can't get rid of the cell that says "display". Right now, that's the only place where students know what is expected of them. But you could specify the display in the _title_ of the slide. It's a little prescriptive, but that might be a bad thing.

**Comment by flannery-denny** [comment]
@schanzer @retabak Here is a link to the pageless version of the research paper. The only other chamnge I made was to update the examples to use the new filter function correctly. 
[https://docs.google.com/document/d/1QBWvIyp1NIJtULHxc6Yt8fuZsxSS3hpyR40-6q-40hQ/edit?usp=sharing](https://docs.google.com/document/d/1QBWvIyp1NIJtULHxc6Yt8fuZsxSS3hpyR40-6q-40hQ/edit?usp=sharing)

Neither the **Dataset Exploration** nor the **Research Paper** have the question format you mentioned wanting to change: 

> “what question does this display answer?” instead of “what does this display tell us?” Then, follow up with, "What is the answer to that question?" 

I'm not sure what you had in mind with regards to that.

lmk when you think the two new documents are ready to replace the old ones in `starter-files.rkt`

**Comment by retabak** [comment]
Re: this - "@schanzer and I think the exploration paper should ask “what question does this display answer?” instead of “what does this display tell us?” Then, follow up with, "What is the answer to that question?" We felt like this gave kids an opportunity to run the data cycle in reverse as a scaffold to actually developing their own questions and considering how to answer them (which is far more challenging). FD - these directions aren't in the Exploration paper - Assuming this is something that has to happen in the paper"

You're right ! That question is posed in the lesson plan, not the project template. Sorry! That said, I believe that this series of questions should appear in the template.

Can we also put some of that blue text in the presenter's notes?
