### ISSUE TITLE
Make 'translate' an alias for 'put-image'

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1454]
- [x] Find-and-Replace `put-image` with `translate` in all our materials 
- [x] make `translate` available in WeScheme
- [x] Make `translate` as an alias for `put-image` in contexts
- [x] Make sure framing of the function is updated appropriately
- [x] Update starter files
- [x] Update desmos
- [x] Decide whether `put-image` or `translate` will be used in Chinese Flag starter file, remove the other, correctly save files in google drive and update the link in `starter-files.js`
- [x] add translate to `.langtable.js`
- [x] use `add-to-lang` to add translate to `contracts-tables-displays`

**Comment by ds26gte** [comment]
- do you mean all occurrences of `translate` in code fragments should become `put-image`?
-  do you mean this should happen only for Pyret, when converting from our common-s-exp language input?

**Comment by schanzer** [comment]
I'm thinking this would happen in our Bootstrap-A and Bootstrap-DS contexts, so as to be entirely transparent (I would have to update WeScheme as well).

And yeah, we'd do a global F-&-R in our materials to remove put-image (perhaps preserving it for a year or two in the contracts list)

**Comment by schanzer** [comment]
Luke is still not responding to email. Moving this to Feb 1

**Comment by schanzer** [comment]
The find-and-replace for this issue has been completed, and resides in the `put-image2translate` branch. Adding this to our curriculum team meeting agenda, to see if we want to move forward.

**Comment by flannery-denny** [comment]
@schanzer Take a look at this [Chinese Flag starter file](https://code.pyret.org/editor#share=1BWLopFBsC5eMLjHsMxtg28mvU-Sfr2aE&v=0c33ff0)! `translate` and `put-image` don't put the images in the same place!

**Comment by schanzer** [comment]
@flannery-denny good catch! 

It looks like Joe may have made `translate` and alias for `place-image` instead of `put-image`. I'll poke him.

**Comment by flannery-denny** [comment]
@schanzer any update on this?

**Comment by schanzer** [comment]
@flannery-denny pyret has it now (albeit too late for fall2024). I've been trying to keep the `put-image2translate branch in sync with `master`, so this should be fairly low-hanging fruit

**Comment by flannery-denny** [comment]
@schanzer starting to work on 2025 datasets. Do you have a new context with this yet?

**Comment by schanzer** [comment]
@flannery-denny 
That to do item has already been checked off. Are you saying that Translate isn't working for you? Can you send me a link to the offending file?

**Comment by flannery-denny** [comment]
@schanzer  just wanted to make sure I was using the right context for the future. My notional machine was broken...  It works :)
