### ISSUE TITLE
We used to teach the geometric proof for the distance formula. Why did we get rid of it?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1455]
We had this lovely section in our pre-remix distance formula unit:
![image](https://github.com/bootstrapworld/curriculum/assets/77126/be084a52-725d-4b4d-9774-0981f857abab)

Is it worth bringing back to our distance formula lesson?

**Comment by flannery-denny** [comment]
@schanzer I was excited to take a look into the way back machine, but I'm not sure this snippet would add much. tova's video is part of the current lesson. open to talking further about tackling teaching the distance formula in a student discovery way rather than a lecture.

**Comment by schanzer** [comment]
@flannery-denny I think students would benefit from a kinesthetic activity where they assemble differently-shaped triangles and see this for themselves, rather than passively watch a video. Why did we get rid of that?

**Comment by flannery-denny** [comment]
@schanzer The wording from the old lesson plan you had linked to doesn't do it for me, but I see the value to the kinesthetic materials you are suggesting including.

I can't answer the question of where old materials went. As a teacher who'd been working with old materials (and didn't have any idea that the lesson plans I was working with were getting updated every year), I remember being appalled when I saw how much of the great stuff I was using with my students had gotten axed for the 2020 release. Those changes happened before my time.  And I have built out a bunch of distance materials since coming on board, because I thought this section was extremely scant. 

I used to teach a different geometric proof of the distance formula to my students... so a little part of me wonders why this is the (only?) one we want to focus on.

**Comment by schanzer** [comment]
@flannery-denny we have some old, hard-coded images [here](https://www.bootstrapworld.org/materials/fall2018/courses/algebra/en-us/resources/images/pythag2.png) and [here](https://www.bootstrapworld.org/materials/fall2018/courses/algebra/en-us/resources/images/pythag1.png). I've seen some really similar - more awesome - Desmos activities that do the same thing as well. I bet @retabak has one or two in mind already that could be used in place of the paper manipulatives.

**Comment by schanzer** [comment]
@flannery-denny and @retabak I LOVE the bananas one. I'd be thrilled if we provided that, with some instruction for what we want kids to DO with it. (Suggestion: "choose one slide that appeals to you, and replicate the transformation by cutting pieces of construction paper and demonstrate the transformation in front of the class."

**Comment by retabak** [comment]
okay, as much as I am a desmos fangirl, I just followed Steve Phelp's link to the geogebra version of this desmos activity (also by Steve Phelps), and I actually think it looks cleaner - and would be more accessible for teachers who might be scared of desmos. Here it is: https://www.geogebra.org/m/jFFERBdd

**Comment by schanzer** [comment]
@retabak @flannery-denny ooooh, even better! Let's use this (with some instruction), and cross this one off the list!

**Comment by schanzer** [comment]
@flannery-denny totally

**Comment by schanzer** [comment]
@flannery-denny if this work now has a required workbook page, should the milestone be moved up to Jan 1?

**Comment by flannery-denny** [comment]
@schanzer the workbook page has already been added. we agreed that the
pythagorean theorem stuff would happen on desmos

**Comment by flannery-denny** [comment]
@schanzer this is ready for feedback

**Comment by schanzer** [comment]
@flannery-denny I made some small formatting/typo fixes, but otherwise this looks pretty good. 

The one problem keeping this from being finished is that you've moved the "Why line-length?" strategy box to the additional exercises section, and offered no explanation in the lesson itself for why line-length is being used. The lesson does a terrific job explaining why we use (x2-x1), and then tells kids "see how we do something different, and see if you can do it too for the second problem".

We need at least one child-facing sentence explaining how line-length _is_ (x2-x1), and why we use it.

**Comment by flannery-denny** [comment]
@schanzer ready for feedback

**Comment by flannery-denny** [comment]
@schanzer just waiting on feedback to close this one

**Comment by flannery-denny** [comment]
@schanzer Close if you're satisfied!
