### ISSUE TITLE
Integrate Exploration Project more closely with DS lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1456]
**General:**
- Need clearer indicator in lesson plans that these sections refer to the exploration paper; add a link to the project exploration page so teachers know what’s up.
- Remove "Optional" from lesson sections, now that the Dataset Exploration Project isn't optional
- Call it the Data Exploration Project

- [x] fix directions in lesson plans that relate to the measures of center table so that they all end up using the same columns

**Lessons with "Your Analysis" sections to be updated:**
- [x] Bar and Pie Charts - RT 
- [x] Choosing Dataset  - RT
- [x] Histograms 
- [x] Visualizing the Shape of the Data
- [x] Measures of Center 
- [x] Box Plots 
- [x] Standard Deviation - RT or FD
- [x] Scatter plots - FD
- [x] Correlations - ES
- [x] Linear Regression - ES
- [x] Grouped Samples - REMOVE from lesson
- [x] Threats to Validity - REMOVE from lesson

**Slides to be updated:**
- [x] Bar and Pie Charts - RT 
- [x] Choosing Dataset  - RT
- [x] Histograms 
- [x] Visualizing the Shape of the Data
- [x] Measures of Center 
- [x] Box Plots 
- [x] Standard Deviation - RT or FD
- [x] Scatter plots - FD
- [x] Correlations - ES
- [x] Linear Regression - ES
- [x] Grouped Samples 
- [x] Threats to Validity 

This issue relates to #1248.

**Comment by schanzer** [comment]
@retabak note that there's _already_ a `project-exploration-paper` lesson!

**Comment by flannery-denny** [comment]
@retabak @schanzer Several different plots are used to complete the five number summary in the Data Exploration Project. That means the directions in those lessons have to point students to use the same columns. I'm noticing this, but am out of steam for sorting this out.

**Comment by retabak** [comment]
Thanks for pointing it out. I took care of it by adding this text to box-plots and standard-deviation.

** _Note: Consider recommending that students choose the same column they used when they found their @lesson-link{measures-of-center}. If students use a different column, they will need to copy/paste additional slides into their slide deck._


I'll power through as many slide updates as I can tonight.

**Comment by schanzer** [comment]
Agreed. @retabak this one is your baby, so close if you think we're ready!

**Comment by retabak** [comment]
Hurrahhhh!!

THANK YOU @flannery-denny and @schanzer for helping push this to the finish line. I am VERY pleased we were able to make this happen.
