### ISSUE TITLE
research paper page revamp

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1457]
- [x] change to a lesson (see #1248)
- [x] explain how the exploration paper can be a bridge to the research paper
- [x] address #1486 - mention / link Research Paper in every lesson that mentions the Exploration Paper
- [x] address #1541 1541

**Comment by schanzer** [comment]
@retabak note that there's _already_ a `project-research-paper` lesson!

**Comment by retabak** [comment]
Linking to #1486

**Comment by retabak** [comment]
Note to get feedback / wish list from Joy re: research paper

**Comment by retabak** [comment]
QUESTION: is it reasonable to ask kids to TELL A DATA STORY, rather than plopping displays into a slide deck in a prescribed order (which is what happens in Joy's slide template)? 

In my view, telling a data story means each display you make is inspired by the previous one... and you may or may not want / need a box plot after you make a histogram.)

Joy's template includes a big warning: "This is just a guide!!!!  You are the master of your presentation.  Use your own creative backdrops and photos.  This just guides you through what information should be organized to tell your data story.  Make sure to include these items, but tell the story your way!! DO NOT use this as a fill-in-the-blank template!!"

That said, all the decks I looked at from her kids go in the prescribed order. (They are very very pretty, though. And thoughtful too!)

my thoughts:
- This approach is MUCH more challenging than dropping some loosely related displays into a slide deck.  Having kids really tell a story would be much more rewarding, I believe. Kids could even include their dead ends in the story.
- The research paper template currently says, "Confirm that you have incorporated at least one interesting pie chart, bar chart, scatter plot, etc." We may need to remove / alter this if we expect kids to tell a story - because who knows what displays will or will not be needed to answer any given question?
- This "telling the story" thing is one of the major differences between the exploration paper and the research paper. I don't think our template or Joy's template gives kids enough support in telling their stories. 
- The other major difference, I believe, is that all displays in the research paper should somehow help students answer one big question, rather than many little - perhaps disconnected - questions.

Anyhow. I want to make sure I understand how we want to approach this before I update the project page (or the template, which needs some updating).

Here's some brainstorming I did (just a start): https://docs.google.com/document/d/1SQkS3ONE_EfnHsULZ7HNUPNCI7lIrd-zEBuOVIx79lM/edit?usp=sharing

and here's joy's template: https://docs.google.com/presentation/d/1jKh2DQUX4I_3r_D4GFiOo0tgivMRnzy9x5ggFE_itPc/edit#slide=id.g78bccb65b3_0_12

@flannery-denny @schanzer - I'm hoping to dig into this at our curriculum meeting.

**Comment by retabak** [comment]
Here's the template for the research project that I made - inspired by our research paper template and also joy's slide deck template. Open to any feedback!

https://docs.google.com/presentation/d/1qNV1mIyfOsp0mpxG0KAVlTISB8asQzxGJtQKrsndzUE/edit#slide=id.g28c03351c64_0_125

I think coaching kids to tell a story (and not randomly make displays) will happen on the Project Page and in the rubric. (Those are in progress.)

**Comment by schanzer** [comment]
@retabak This looks really nice! I left some  small comments in the doc, but otherwise I think you're good to go!

**Comment by flannery-denny** [comment]
@retabak Great start! Left you a number of comments on the deck. Noting that use of "you" really means "we, the Bootstrap team" ;)

**Comment by retabak** [comment]
@flannery-denny - when does my use of "you" really mean "we"? I'm confused!
