### ISSUE TITLE
Get our HoC on Code.org's tracker

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1461]
- [form](https://docs.google.com/forms/d/e/1FAIpQLSfcbWXlJU93DK9s68oCzo6-IUriw9kFy0eA0ArRia7OM-RKPw/viewform)
- [Notes from last year's submissions](https://docs.google.com/document/d/1de8cPF_4Xc0gioTnWrwfOx-pGOBih1ycqV5y938bS6o/edit)

**Comment by flannery-denny** [comment]
@schanzer remembering that they don't have a category for data science. Is that something you could inquire about?

**Comment by flannery-denny** [comment]
@schanzer 
- When should we nudge Dan Schneider again? 
-- It's been 8 days
- At what point should I fill out the form without hearing back? 
- If we can't call HOD data science, I guess we should categorize it as Math/Algebra instead, even though that's a bad fit?

**Comment by flannery-denny** [comment]
@schanzer We need to submit a marketing image for our activities hat will appear alongside images like these.
<img width="846" alt="Screen Shot 2023-08-18 at 11 52 51 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/abdf476e-6df9-4787-8c4f-11388c90ca2f">
Do you have a preference for 
<img width="682" alt="Screen Shot 2023-08-18 at 11 55 10 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ffcb0b30-c7d2-4920-a634-208280a1e98d">
<img width="448" alt="Screen Shot 2023-08-18 at 12 03 03 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b07da769-016f-43d0-917f-d87078c660cd">

<img width="455" alt="Screen Shot 2023-08-18 at 12 08 28 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ca1aaf22-552e-4125-8e2a-4aeb5920eb4f">

**Comment by schanzer** [comment]
@flannery-denny I like the moose!

**Comment by flannery-denny** [comment]
Here's a link for [editing our Hour of Data Submission](https://docs.google.com/forms/u/0/d/e/1FAIpQLSfcbWXlJU93DK9s68oCzo6-IUriw9kFy0eA0ArRia7OM-RKPw/viewform?usp=form_confirm&edit2=2_ABaOnudO7irzEC_DtM2osJEO2QQeZdZK_PqsmiNfOb-TydNixq8kYnfetcQVBHmvy3T7__s)

**Comment by schanzer** [comment]
Thanks, @flannery-denny ! I've reviewed the submission, and the only change I made dealt with COPPA compliance. Since we're no longer a non-profit, we can't check the "exempt" box. Fortunately, all the action happens in Desmos -- and [they are COPPA compliant](https://www.desmos.com/privacyfaqs#coppa).

I think you're ready to roll!

**Comment by flannery-denny** [comment]
@schanzer Thanks for catching the COPPA change.

- When I click the link I added to the issue I can’t see a change to how that question was answered, which is a little confusing to me. Are you sure you clicked submit? 

- The second hour of code activity we want to submit uses parlay - not Desmos. How should I answer the COPPA question for it?

**Comment by schanzer** [comment]
Oh! I didn't submit -- I thought my changes were tracked in the shared URL?

I did some looking about what it takes to be COPPA compliant, and it looks like we are ([reference](https://www.ftc.gov/business-guidance/resources/childrens-online-privacy-protection-rule-six-step-compliance-plan-your-business#step1)). Thank god for not collecting personal information on our users!

**Comment by flannery-denny** [comment]
@schanzer No worries. I just updated it. The shared url is generated when I submit the lesson. If you want to make changes to the next one I post, make sure to click through to the end and click submit so that they get saved.

**Comment by schanzer** [comment]
Closing as submitted

**Comment by flannery-denny** [comment]
It's helpful to remember that we can hack the URL for the alignments page, so that the only lessons it cares about are the one(s) you want. For example: https://bootstrapworld.org/materials/fall2023/en-us/Alignments.shtml?lessons=hoc-data

**Comment by flannery-denny** [comment]
@schanzer when I go to Hour of Code, I cannot find our hour of data lesson by searching for data... I think it's time to nudge your contacts again. Reopening this issue to remain open until we're actually listed.

**Comment by flannery-denny** [comment]
HOC reports submissions will be live 11/7. added to bootstrap calendar so we can confirm.
