### ISSUE TITLE
Brainstorm ideas for Jamboree

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1464]
- [ ] Nov 1 milestone
- [x] New slide infrastructure preview?
- [x] Parlay / examplar preview?
- [ ] close #1518?
- discuss if desmos starter files should be consolidated (one per lesson) or separated (many per lesson)
--> FD's reservations about combining slides are a) can't link to them directly b) if I gave my students access to all of the things that we were going to look at at the beginning of class, it would undermine class discussion 
--> FD is excited to learn more about how Rachel would use our Desmos materials in her teaching. Perhaps there are a number of Desmos features that we aren't optimizing?
- [x] Think about how best to collaborate with Joy and Eric?
- [ ] report back from Rachel's trainings
- [x] Ethics and Data Cycle
- [ ] road test alg 2 materials we have
- [x] The Dept of Ed math gathering?
- [ ] the CODAP simple data types has changed considerably and if we could road test it, that would be helpfuL!

**Comment by flannery-denny** [comment]
Thanks for looking into childcare options, @schanzer! 

Are you up for taking on thinking through how meals will work (whether we go out, order in, cook...) Being at your house is a little different from working in a public space. I know that you love to cook and grill, but don't want you to feel burdened by it. Wondering whether you need us to take any of the meal planning on?

**Comment by schanzer** [comment]
I absolutely love to cook, and it never feels like a burden! And if the weather is it might be fun to grill.

- Monday: I can make a lasagna that morning so it's ready to go for dinner. All I need to do is cook up some veggies.
- Tuesday: Happy to make a bunch of eggs and have bagels and toppings ready to go. If the weather is nice it's no trouble to grill for lunch, but we should definitely go out someplace fun for dinner!
- Wednesday: Pancakes and fruit are easy to throw together as well

Does this sound ok to you, all? Please feel free to push back on any of the food suggestions!

**Comment by retabak** [comment]
I'm getting excited!!! 

@flannery-denny , loving your suggestions of things for us to focus on (above). I'm gonna add one thing to the list.

If you want a break from meal prep @schanzer , I have a pretty solid recipe for pancakes with sourdough starter. (I could bring my starter!) I could also bring a loaf of homemade sourdough (bagels are yummy, though).

Since I'm driving, I'll plan to bring along a salad that we can eat with the lasagna! (I love salad. And prepping salads. And eating salads at all meals.)

(If you had noticed, I enjoy cooking and baking too!)

**Comment by schanzer** [comment]
@retabak sourdough pancakes sound AMAZING! Hell yes, and to salad as well.

I'll let @flannery-denny and @ds26gte weigh in on the bagel issue. ;)

**Comment by retabak** [comment]
Just remembered - I don't think @flannery-denny can do dairy (cheese?) - so lasagna may be a no-go?

**Comment by flannery-denny** [comment]
Sounds delicious! 

Impressed you remember that I'm lactose intolerant, @retabak. 
I love lasagna, but I definitely can't eat ricotta or mozzarella cheese without being really sick. 
- If you're a traditionalist, lasagna is out for me, but it'd be fine to set some of the veggies aside for me and I could try to pick up something simple like trader joe's chicken meatballs to accompany it.
- If you want to get creative, I can eat parmesan (and other aged cheeses like cheddar), goat and sheep cheese, and butter and beans and meat.  

re: bagels and homemade bread, I eat both. Would love to try Rachel's bread at some point.

I'm also on the salad at every meal team. And eat a lot of protein of all kinds... so would ideally make myself a couple of eggs in addition to pancakes on Wednesday ;)

Happy to go out to dinner on Tuesday, but I'll need to take Dacks with me and he'll likely fall asleep on me during that time (we're both used to that). Outdoors is easier acoustically and always my preference if the weather is cooperative.

**Comment by schanzer** [comment]
@flannery-denny ah, I completely forgot about the lactose intolerance! OK, perhaps I'll do enchiladas or a stir fry instead, then. I always make sure there's plenty of protein, so there will be tofu and/or chicken available.

Always down to add eggs for breakfast. And @retabak I think you're clearly on the hook for bread!
