### ISSUE TITLE
proposal: Remove all mentions of "optional" from the Exploration Project directions / sections

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1465]
In the box plots lesson, they are not. (See two examples below.) Wondering if we forgot to make other pages in the "your analysis" section optional??? Need to check.

https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/box-plots/pages/data-cycle-quantitative.html

https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/box-plots/pages/shape-of-my-dataset.html

see #1456

**Comment by schanzer** [comment]
I wholehearted support this!

**Comment by schanzer** [comment]
Closing as duplicative of #1456
