### ISSUE TITLE
Regression: Full @opt-printable-exercise titles should show on links, even when they include commas

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1469]
I'm working on something that I haven't pushed yet, and the link title is coming up as only the first word when I build. 

Another instance where the title should work with commas is found in `Correlations/identifying-form-matching.adoc`. That one appears to still be working, so whatever is broken is inconsistent. Perhaps it's because that one is an `@printable-exercise` rather than an `@opt-printable-exercise`?

If you need a reproducible instance, I expect to have what I'm working on pushed by Monday. This issue can wait until next week to be resolved.

**Comment by schanzer** [comment]
@flannery-denny can you try Dorai's fix? He's pushed it to both master and contracts-dictionary

**Comment by flannery-denny** [comment]
Fixed. Huzzah!
