### ISSUE TITLE
Histograms lesson doesn't include any practice making histograms in Pyret

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1470]
Maybe we could add a worksheet?

There's lots of opportunities for students to interpret them and even a chance to make them manually.

**Comment by schanzer** [comment]
@retabak they already make one manually, as a mandatory part of the workbook. :) 

Flannery has [already added a page](https://github.com/bootstrapworld/curriculum/issues/1414) that has them practice making them in Pyret

**Comment by retabak** [comment]
Flannery's worksheet! You're right. Closing :)
