### ISSUE TITLE
change "paper" to "project" in all instance of "exploration paper" and "research paper" 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1472]
@starter file needs to be changed too.

**Comment by retabak** [comment]
wait, I'm wrong. This is more complicated.

When we refer to the project, are we okay with only linking to the slides? I think that makes the most sense. Otherwise we need to directives, I think? Can we get one directive to have two hyperlinks?

**Comment by schanzer** [comment]
@retabak Just link to slides. Let's get rid of the paper entirely.
