### ISSUE TITLE
@teacher breaks some asciidoc formatting - it shouldn't

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1473]
Here is the code in question:

```
@teacher{

** _Answers will vary, but here are some important points:_
** _One of the pie charts has more categories for race than the other and the bar charts have more categories for race than we see om either of the pie charts._ 
** _In a pie chart, when there isn't any data in a category it goes unrepresented, but in a bar chart its absence is made visible._
** _The scale is different for each bar chart, whereas for pie charts the percentages will always add to 100%._

}
```

Without @teacher it looks as follows:
<img width="770" alt="Screen Shot 2023-08-13 at 5 11 57 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/4326024e-9a8b-4396-bfdf-c870ca9c3bb3">

With @teacher I get
<img width="882" alt="Screen Shot 2023-08-13 at 5 12 40 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/81aa987a-c04c-4bd3-8b1e-9d478262c199">

**Comment by schanzer** [comment]
@flannery-denny I can confirm that this is fixed. Here's what I see after building with Dorai's fix:
<img width="1010" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/53468748-7fad-43b9-a804-1fc5ab1db8d4">

Close if you're happy?

**Comment by flannery-denny** [comment]
@schanzer That page built correctly for you because I removed `@teacher` from it when it wasn't working. 

I am not able to add it back in and get it building correctly. Since we're on master and I don't want to push broken stuff, I've added the relevant code to `zample-page2.adoc` for @ds26gte to work with.

**Comment by schanzer** [comment]
@flannery-denny apropos of our discussion today (where we agreed to not use `@teacher` for Q&A), can this be closed?
