### ISSUE TITLE
Update DS lesson plans to consistently reference Exploration and Research Paper

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1474]
In the video game lessons and starter file we carefully guide teachers through our sequence. 

We need to develop comparable scaffolding for the DS Research paper in our lessons to help teachers understand the scope and sequence of the BIG undertaking of writing a research paper. 

We need to consistently alert them - in the lessons - of when / why they need to allot some time for kids to add to their exploration paper

- [ ] Decide - does this mean we should come up with a consistent My Dataset Exploration section for each related lesson?
**Yes! It does mean that! [Here's the template I made](https://docs.google.com/document/d/1a1rjrT_FN0zZ-tvqiqMLoNIlslbNEFQgZ3DbBAyleMM/edit).**

- [ ] Students can't work with the exploration paper until they choose a dataset. In the current organization of things, that doesn't happen until after Bar and Pie Charts, which means that we can't write about the exploration paper in that lesson. Should we consider reorganizing our lessons?
**I have proposed that we instruct students to add their bar and pie charts during choosing-your-dataset.**

- [ ] Decide whether we should adopt @retabak proposal that the exploration document clearly and obviously follow the same sequence as the relevant lessons (they're all listed [here](https://docs.google.com/document/d/1Aq-EPY-UKkvuggtGrkUgmLLIwg55x1elst5lcEsfR9c/edit).)
**I vote yes. I _think_ @schanzer agrees, but he should speek up if he doesn't!**

- [ ] Make sure directions in lessons match Dataset Exploration (eg. if we scaffold that they need to address at least 2 quantitative columns in exploration paper, also limit scope in lesson)
**I have been working on instructions in lessons. For the lessons that I have already completed, see master (not the website) to know what decisions I've made. I'll also cross reference the template you make as I continue my work!**

**Comment by schanzer** [comment]
@retabak this feels like something you're already working on, no?

**Comment by retabak** [comment]
I'm updating the lessons, but not creating a new slide deck or page less
Google doc.

**Comment by retabak** [comment]
Sorry, previous response was terse and via email. Yes, I am working on this in issue #1456.

Of note, I am *not* updating the lesson plans to mention the research project - only the exploration project.  After some thinking / conversation in issue #1465, we're framing the exploration project as an integral part of the DS lessons, while the research project is being framed as something extra / optional.

I'm going to add some comments to your original post.

**Comment by schanzer** [comment]
Closing as duplicative of #1456 (among others)
