### ISSUE TITLE
Use 2024 ds library in Bar and Pie charts lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1477]
Round two goals as of 9/19
- [x] Update the 2024 branch to use stacked bar charts with percentages from the 2024 DS library in lesson plan and workbook pages.
- [ ] Figure out how to offer up the expanded animals starter file for deeper exploration.
- [x] Make sure the notice and wonder page includes displays that come from big enough datasets to allow for more nuanced discsussion

**Comment by retabak** [comment]
here are some comnents sent via slack re the 2nd half of bar & pie charts re: screenshot below:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/38a22e55-fc26-4e7e-9a1f-79bcd3d659cb)

- the [.lesson-point] should go after the lesson text; seems that they are being used as headers, which is no good.
- I see that the charts make that impossible. How about putting them side by side (in a table), and then saying "Stacked bar chart (image above, on the left) put the totals side by side, so it's easy..." And then "Multi bar charts (image above, on the right)..." This would also solve the problem of wasted white space.
- The lesson points are VERY confusing to me. Do we want "than" or "then"? is it easy or easIER? Is it easier to compare groups than it is to compare subgroups, or is it easier to compare groups first THEN subgroups next? These are all questions that I had. Reading the explanatory text answered my questions, but I was truly confused for a moment.
- "side by side" should be three words. Only hyphenate if it's being used as an adjective (i.e., "side-by-side tables").

**Comment by schanzer** [comment]
@retabak see latest revision, and close if you're satisfied

**Comment by retabak** [comment]
This looks way better! Thanks! 

I'm not sure if @flannery-denny wanted to do a super close read-through (like she did with the first half of the lesson). I wrote up those notes after just glancing at what was there. I'll let her decide if this is adequate.

**Comment by flannery-denny** [comment]
- I see that @retabak wanted the sections of the @opt-printable-exercise section divisions to align with the lesson instruction boxes, which hadn't been my plan so the page didn't correspond to her direction updates. I've adjusted both to achieve her goals.
- [ ] Something I am confused about is why the @optional directive for the @opt-printable-exercise that I made for the `Grouping by Value` section of this lesson was removed. Any objections to me putting that back in @retabak?
- [ ] The formatting of the second half of this lesson reads better, but I it feels like it would also benefit from an @opt-printable-exercise, because we're giving a lot of directions orally that would be much easier for many students to receive in written form. Would you agree @retabak?

**Comment by retabak** [comment]
I've added some comments above! Thanks!

**Comment by schanzer** [comment]
@retabak yes, they're already set to printable in 2024, and I've been keeping that branch in sync with the changes here.

**Comment by flannery-denny** [comment]
@schanzer if you need my help getting this set up so that opt pages aren't opt for fall2024, lmk. Otherwise, ready to close.

**Comment by schanzer** [comment]
@flannery-denny these changes look great. I've updated `fall2024` to be current with `master`. Once you've made the changes to make these pages required on fall2024, we can close this issue.

**Comment by flannery-denny** [comment]
@schanzer The lesson description doesn't make sense to me. I've added discussing and wordsmithing it to our meeting agenda for tomorrow. 

I think I'm done with reordering. Just need to add synthesize questions to the first part.

**Comment by flannery-denny** [comment]
@schanzer I'm not satisfied with the displays in the multi / stacked bar chart notice (currently lots of subgroups are equal or so different that there's nothing tricky that mandates using one display or another to answer questions

I'd vote we either:

- contrive better examples where the values are harder to identify across subgroups 
- cut the page and have them notice & wonder about the displays they're already building.

Preference?

Either way I wonder whether we should offer additional practice using the expanded animals starter file for this section of the lesson.
