### ISSUE TITLE
Unify use of Mode Modes Mode(s)

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1480]
In our measures of center lesson 
- the lesson section is called Modes 
- we refer to a mix of mode, modes, and mode(s) in the text. (Are we ok with this, thinking we probably want to be more consistent?)
- the contract is for modes
- In the Data Exploration Project we use Mode(s)
- In the glossary we define mode.
- I definitely think we should update the way it appears in the glossary to `mode(s)`, but I think it'll require @schanzer or @ds26gte because of the way that the file works.

**Comment by schanzer** [comment]
@flannery-denny I've updated the glossary and streamlined where and when we use mode, modes, and mode(s). Close if you're satisfied with these changes
