### ISSUE TITLE
@show{(contracts need css magic to give a little space between contracts

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1481]
On the web I see
<img width="549" alt="Screen Shot 2023-08-16 at 11 59 30 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/17c47b5a-5afb-47db-9229-af5728be114a">
with the new font, things look very crowded on master
<img width="740" alt="Screen Shot 2023-08-16 at 11 59 23 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/8b6aa73b-1ffa-4f81-8a5e-425f0502a2be">

(you'll also see a bug here, which I reported separately, so that's not the purpose of this issue.)

**Comment by schanzer** [comment]
Where on the web is this? (a link would be helpful)

**Comment by flannery-denny** [comment]
https://bootstrapworld.org/materials/fall2023/en-us/lessons/function-composition/pages/function-composition-your-name.html

**Comment by flannery-denny** [comment]
https://bootstrapworld.org/materials/fall2023/en-us/lessons/advanced-displays/index.shtml?pathway=data-science

**Comment by schanzer** [comment]
@flannery-denny thanks! Just pushed a fix that increases the line-height of code elements from 1.2 to 1.4. Let me know if you think we need even more space? (be aware that this might cause some workbook pages to overflow...)

**Comment by schanzer** [comment]
@flannery-denny see advanced-displays after the tonight's commit

**Comment by flannery-denny** [comment]
thanks @schanzer. looks better!
