### ISSUE TITLE
Final ruby contract cleanup

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1483]
- [x] Replace pathway-specific contracts pages with Contracts.shtml, and adapt the build system to special case this as a multi-page PDF
- [x] Decide what we want to do with row consuming functions and have `@show{(contract` make it so 
-- eg `species-dot {two-colons} **(r {two-colons} Row)** -> Image` found in the `scatter-plot` lesson
-- Here's an example from advanced displays where you can see what it currently looks like and used to look like all at once
<img width="865" alt="Screen Shot 2023-08-17 at 6 15 23 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/7e2d8860-5ac7-4258-a4a5-4706f60adf22">

**FD and ES discussed and we like how Dorai has contracts like the one below working... it'll be ok for the r in (r::Row) to fall away in contracts provided in starter files once we've fully switched to ruby contracts**

![Screen Shot 2023-08-15 at 3 58 24 PM](https://github.com/bootstrapworld/curriculum/assets/66691020/464e168e-e528-468a-9b84-414a615b45c5)

- [x] Decide 
-- The triangle contracts page currently looks like this <img width="819" alt="Screen Shot 2023-08-16 at 3 12 25 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/bf40b9d6-dc99-4534-85d2-fd1c8609e6f4">
-- It would look like this <img width="896" alt="Screen Shot 2023-08-16 at 3 18 29 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/781fe8c9-99cf-4150-b576-2ccccb81e501">
-- If we replace the code with 
```
@show{(contract 'triangle '((size Number) (style String) (color String)) "Image")}

@show{(contract 'right-triangle '((base Number) (height Number) (style String) (color String)) "Image")}

@show{(contract 'isosceles-triangle '((leg Number) (angle Number) (style String) (color String)) "Image")}
```
1) what an improvement!
2) Does it have to wait til next year? **Yes**

- [x] Decide what we want to do about the following pages - **deal with them in 2024**
```
~/Documents/Bootstrap/curriculum/lessons/Core/contracts/langs/en-us/index.adoc:
  218: ** `string-append {two-colons} String, String -> String`

~/Documents/Bootstrap/curriculum/lessons/Core/contracts/langs/en-us/pages/radial-star.adoc:
   13: @show{(code 'radial-star)}`{two-colons} (`

~/Documents/Bootstrap/curriculum/lessons/Core/contracts/langs/en-us/pages/star-polygon.adoc:
   15: @show{(code 'star-polygon)}`{two-colons} (`

~/Documents/Bootstrap/curriculum/lessons/Core/contracts/langs/en-us/pages/triangle-contracts-cont.adoc:
   43: @show{(code 'triangle-sas)}`{two-colons} (`
   46: @fitb{30em}{@ifsoln{`side1`}} `{two-colons} Number,`
   47: @fitb{30em}{@ifsoln{`angle`}} `{two-colons} Number,`
   48: @fitb{30em}{@ifsoln{`side2`}} `{two-colons} Number,`
   49: @fitb{30em}{@ifsoln{`style`}} `{two-colons} String,`
   50: @fitb{30em}{@ifsoln{`color`}} `{two-colons} String`
   65: @show{(code 'triangle-asa)}`{two-colons} (`

~/Documents/Bootstrap/curriculum/lessons/Core/contracts/langs/en-us/pages/pyret/image-contracts.adoc:
    4: Contracts tell us how to use a function. For example:  `ellipse {two-colons} (Number, Number, String, String) ->  
```

**Comment by schanzer** [comment]
@ds26gte the first item on the list will definitely require your help!

The new `Contracts.shtml` file can now take the pathway as a URL parameter (e.g. - `Contracts.shtml?pathway=data-science` will generate the contracts for DS). We should adapt the build system to print this page to a PDF and then link those PDFs into the workbook. It's already set up to print properly, but the tricky part will be breaking the assumption that al wbpages must be 1 page long.

**Comment by schanzer** [comment]
@flannery-denny 

1. @ds26gte is working on this already
2. I'm not sure I understand this one ("Decide what we want to do with row consuming functions"). I really like the way the new formatting looks! if you're asking "do we want to make this switch?" the answer is yes!
3. I'm 100% in favor of changing the triangle contracts to the ruby format, but unfortunately I think we should wait until next year.
4. I don't see a reason _not_ to use rubies in most places. The one concern I have is that we now need to be more explicit about how to translate a Ruby contract into a traditional contract and purpose statement in `functions-dr`. If you agree, let's make a separate issue of this, tag it 2024, and check this one off.

**Comment by schanzer** [comment]
Thanks to some @ds26gte magic, the new contract page is now complete. AND, thanks to @flannery-denny 's new ruby contracts -- they are finally in portrait mode. `Readability++`
