### ISSUE TITLE
The only link to our research paper template is in the teacher resources section... why?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1486]

**Comment by schanzer** [comment]
@flannery-denny because it's not a required project for the class. When @retabak completes the Project lesson, I imagine we'll still want it linked from here. Where else would you put it?

**Comment by flannery-denny** [comment]
The rest of our `@opt-projects` are linked from lesson plans... 
I would certainly put it in the `choosing your dataset` lesson, since the dataset could also be used for the research paper, but I would probably reference it in _every lesson that the data exploration project is referenced from_.

The original intent of the `data exploration project` was to scaffold students exploring displays and assessing whether they were useful and interesting or not... so that by the time they got to the research paper they had documented what was and wasn't useful and could build on that to make a more meaningful presentation... I'm unclear as to why making the `data exploration project` required should make the research paper disappear. As I understand it, it was always optional. And could be improved upon :)

I'm not attached to it's existence, if y'all want to vote it off island, but I don't think it should exist if the only place we reference it is in the teacher resources section.

And, if we're not going to encourage folks to make it past the Data Exploration Project, then I think we have some work to do to take that project a few steps further.

**Comment by schanzer** [comment]
That's a _really_ good suggestion. Linking it in every lesson that also references the exploration project makes a ton of sense.

@retabak I'm adding this to your plate, and it's probably important to do sooner rather than later since teachers will be looking at those lessons soon. Creating an October 1 milestone and adding it there.

**Comment by retabak** [comment]
Closing this, as I've added it to a to-do list in #1457. Trying to consolidate things.
