### ISSUE TITLE
Algebra 2 - workbook pages to create before release

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1487]
What's currently blocking the beta release of our Algebra 2 materials is a lack of low-hanging fruit: the bread-and-butter Algebra 2 standards that could _easily_ be expressed and explored in the context of our explorations, but aren't (yet). Below is a checklist of those exercises.

- [x] Add terminology for these lessons including #1507 and others to `glossary-terms.json` ES
(NOTE: Related to [the original Algebra 2 issue](https://github.com/bootstrapworld/curriculum/issues/1177))

**Image and Table Library**
When creating charts and tables in Desmos, save links to the source files in `lessonName/langs/en-us/authoring/XYZ.adoc**

- [x] 5 quadratic graphs - FD [https://www.desmos.com/calculator/fgjeuvm06o](https://www.desmos.com/calculator/fgjeuvm06o)
- [x] 5 quadratic tables - FD [https://code.pyret.org/editor#share=13MpHDXKdc9fBNUUsflvnhsxl58-plm-8&v=4d870d2](https://code.pyret.org/editor#share=13MpHDXKdc9fBNUUsflvnhsxl58-plm-8&v=4d870d2)
- [x] 5 exponential tables - ES
- [x] 5 exponential graphs - ES - [Random Exponential Generator (Desmos)](https://www.desmos.com/calculator/yd4r4xzomy), [Random Exponential Decay Generator (Desmos)](https://www.desmos.com/calculator/flrdpc9qrv)
- [x] 5 logarithmic tables - ES
- [x] 5 logarithmic graphs - ES - [Random Log Generator (Desmos)](https://www.desmos.com/calculator/4bpzu2bxlk)

**Linear**
- [x] Add opt-printable that brings back the super-scaffolded calculation of the line based on two points.
- [x] Exercises where students distinguish between linear, non-linear, and non-relationship models based on scatter plot. Should follow the model of Linear, Non-Linear, or Bust activities - may even be possible to copy/paste! - FD
- [x] Matching: this graph with labeled points to this standard form equation
- [x] Matching: this graph with labeled points to this point-slope form equation
- [x] Matching: this graph with labeled points to this slope-intercept form equation
- [x] Mixed matching page
- [x] Adjust model-college-v-income pages so that the scaffolded one is optional, looks almost exactly like the unscaffolded one - ES
- [x] Add a page that provides students with 3 sets of details from the dataset, each one better serving a different form of the line. Have students write that form of the line and then transform that form of the line into a pyret function. 
- [x] Add a pedagogy box that flags DC as a consistent outlier of interest for teachers and provides them with a list of relationships to explore that will yield correlations and ones to avoid. - ES

**Quadratics**
- [x] Exercises where students distinguish between linear, quadratic, and non-relationship models based on scatter plot. Should follow the model of Linear, Non-Linear, or Bust activities.
- [x] Exercises where students distinguish between linear, quadratic, and non-relationship models based on table. Should follow the model of Linear, Non-Linear, or Bust activities.
- [x] Exercises where students distinguish between linear, quadratic, and non-relationship models based on definition. Should follow the model of Linear, Non-Linear, or Bust activities. **There is a page with linear & quadratic definitions, but should add an exponential in the mix and make Neither a choice - also currently has directions about form, but not sure we've provided space for that.**
- [x] Exercises where students distinguish between linear, quadratic, and non-relationship models based on a written description of a situation - ES
- [x] Given this form (vertex, factored, etc), what is the vertex? What are the roots?  - FD
- [x] Matching: this graph with labeled points to this standard form equation 
- [x] Matching: this graph with labeled points to this vertex form equation -FD [https://www.desmos.com/calculator/gheewsmiam](https://www.desmos.com/calculator/gheewsmiam)
- [x] Matching: this graph with labeled points to this factored form equation -FD [https://www.desmos.com/calculator/vl7aka4kpp](https://www.desmos.com/calculator/vl7aka4kpp)

**Exponentials** - ES
- [x] Talk about compound interest and radioactive decay
- [x] Show at least one example table, graph, definition and description involving exponential _decay_ (not just growth!)
- [x] Exercises where students distinguish between linear, quadratic, and exponential models based on scatter plot. Should follow the model of Linear, Non-Linear, or Bust activities.
- [x] Exercises where students distinguish between linear, quadratic, and exponential models based on table. Should follow the model of Linear, Non-Linear, or Bust activities.
- [x] Exercises where students distinguish between linear, quadratic, and exponential models based on a written description of a situation
- [x] HSF.LE.A.1.C - Recognize situations in which a quantity grows or decays by a constant percent rate per unit interval relative to another

**Logarithms** - ES
- [x] Exercises where students distinguish between linear, quadratic, exponential and logarithmic models based on scatter plot. Should follow the model of Linear, Non-Linear, or Bust activities.
- [x] Exercises where students distinguish between linear, quadratic, exponential and logarithmic models based on table. Should follow the model of Linear, Non-Linear, or Bust activities.
- [x] Exercises where students distinguish between linear, quadratic, exponential and logarithmic models based on a written description of a situation

**Comment by flannery-denny** [comment]
@schanzer wondering about the way you're naming images. looks like they have spaces in them. I seem to remember that file names with spaces break some of our build?

also, working on images for the pages where there's a graph with two labeled points. is this medium square file really too small? If I make it a big square file, it adds all sorts of extra grid lines that I don't think are helpful...
![lin-1 2x+2 6](https://github.com/bootstrapworld/curriculum/assets/66691020/d893d142-af44-4975-b1c6-b2df9f16e176)

**Comment by schanzer** [comment]
@flannery-denny I don't think filenames with spaces have been a problem for us in the past. If it turns out this is an issue, I'm happy to own the task of renaming.

Medium is fine. :)

**Comment by flannery-denny** [comment]
@schanzer I'm planning to make one more matching activity for linear functions that has a mix of forms. Please confirm that the format of these pages is what you were expecting as I will likely move on to similar pages for quadratic functions tomorrow. Thanks!

**Comment by schanzer** [comment]
@flannery-denny I took a close look at `match-graph-si` and `match-graph-sf` and they both look great. You are rocking this -- keep it up!

**Comment by flannery-denny** [comment]
@schanzer please pull and take a look at `exploring-linear-models/horizontal-shift.adoc`. I think I'm going to make a second page that focuses explicitly on distributing slope to h to find y-intercept, but lmk if it's not necessary. Thanks!

**Comment by flannery-denny** [comment]
@schanzer also, I'm not seeing a use for pregenerating the images and tables we specked so I've removed the linear ones I hadn't made from this issue. 

The random scatterplot generators are very helpful and allow me to easily make the images I need as I need them. I added one to our desmos library for linear scatterplots. 

The plots I've needed for the pages I've made all had particular requirements that I was not aware of until I was in the middle of authoring.

If you disagree, feel free to put making those images back on my to do list.

**Comment by schanzer** [comment]
@flannery-denny 

1. Overall I really like the horizontal shift page! I made a few comments on the commit, and pushed another commit that implements those proposed changes. Feel free to revert if you want to discuss them. I'm interested to see how your quadratics version of this same page evolves, and whether it will make you want to change the focus of this one.

2. I'm totally thrilled that the random generators are helpful! I'm comfortable with you removing the remaining linear ones from your todo list.

**Comment by flannery-denny** [comment]
@schanzer Thanks for the feedback.  I like many of your changes. I've pushed a response based on the following thinking:

- I really don't like how second level section titles read on workbook pages (they're different on html versions and pdf and I don't like either one)
- I reordered exploration 2 to help students focus on one line at a time
- I reworded exploration 3 because I want students to do calculations before playing with a slider.

Happy to name the Desmos link but don't have a good name for the exercise yet.

**Comment by schanzer** [comment]
@flannery-denny Please keep the level 2 section headers on this page consistent with those on other pages. Otherwise these changes all look good.

**Comment by schanzer** [comment]
@flannery-denny these new pages are looking good! 

1. `match-graph-def` seems duplicative of `match-graph-sf`. If you agree, can we remove the first one? 
2. I'd like to see how you would update the lesson to introduce them. (For now, don't worry about it taking longer than one class period)
3. `def-2-points.adoc` looks great, but it feels like a missed opportunity not to use the points that students will have already encountered in the lesson (`alaska` and `alabama`). The whole point of this optional activity, in fact, was for students who struggled to complete the required page that asks them to build a model from those states. Can you update this to use those values instead?

**Comment by flannery-denny** [comment]
@schanzer 
1. one of those pages is mixed forms and the other only uses standard form so I'm

**Comment by flannery-denny** [comment]
@schanzer I'm not into your recent commit to the matching pages that makes the images larger at the expense of having graphs with gridlines that don't line up touching each other... 

I can think of two alternative options for making the images bigger:

- Make the page landscape so the space available for distributing the images isn't limited by directions at the top and footers at the bottom.
- Make new images from the desmos file I've linked.
- Or we could decide to live with the smaller images... I don't have access to a printer at the moment,  so I don't really know how small they are.

Please lmk which works best for you before I tackle any other matching pages. Thanks.

**Comment by schanzer** [comment]
@flannery-denny I'm not seeing them touch each other in the printed version, are you?

**Comment by flannery-denny** [comment]
I thought you fixed the spacing for html and print. This is what I saw on html
<img width="251" alt="Screen Shot 2023-08-25 at 10 32 05 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/3cbb6912-c7b4-4dce-9118-2a104c0534ec">
and if that's how it's going to stay on the web, the current solution doesn't work.
 
I've just made the book at your suggestion and it looks passable in the printed version.

**Comment by flannery-denny** [comment]
@schanzer I'm looking at the State Demographics Starter File and it feels like a mistake that we haven't used `pct` as a prefix for `college-or-higher` and `hs-or-higher` given the way that the other columns are named

> states-table = load-table: state, region, pop-2010, pop-2020, pop-trend, college-or-higher, hs-or-higher, pct-home-owners, num-households, num-housing-units, land-area, pct-non-english-at-home, mean-commute-time, median-income, per-capita-income, veterans, pct-female, pct-older-65, pct-under-18, pct-under-5, pct-in-poverty, poverty-rate

I definitely want to change it for Alg2. 
I'm wondering, can I just change the starter file? Or do I need make an algebra 2 copy?

**Comment by flannery-denny** [comment]
@schanzer after much thought, I don't think the exploring linear models lesson should match the format for the other lessons, because, unlike quadratic, logarithmic and exponential functions, students will already have studied linear functions extensively so we are not introducing them here.

**Comment by schanzer** [comment]
@flannery-denny We're still adding exercises specific to linear functions (like your horizontal and vertical shift) pages, which go deeper into linear functions and their behavior than students will have seen. We're still asking them to think in terms of linearity in scatter plots. We're still asking them to think of linearity _as a category_, alongside nonlinear and nonexistent relationships. 

It still makes sense to file those under a "linear functions" sections, especially for the sake of consistency with other lessons in this pathway.

Please keep the format the same. If you disagree, let's talk about this ASAP.

**Comment by flannery-denny** [comment]
@schanzer In the notes for teachers file that's linked from the teacher resources section, we've suggested some columns for students to build that would make analyzing the states dataset more interesting.

If I understand correctly, Alg2 is working with a copy of the states dataset that everyone else is?
And we're trying to make this dataset rich for people with minimal programming?
That makes me wonder whether we should add these columns to the Alg 2 version of the file?

`pop-density` `pct-change-pop`

fyi - this surfaced because I was wondering about a correlation between veterans and population, but realized I was actually wondering about pop-density... and remembered that I'd just looked at the notes to see if we'd already suggested correlations for people to look for (we hadn't)

**Comment by flannery-denny** [comment]
@schanzer Recommend adding `R^2` to our glossary.

**Comment by flannery-denny** [comment]
Also, when we talked about what graphs we would include, you thought that sideways parabolas were beyond the scope of the lesson... but I'm seeing this in Classifying graphs and am not sure how you would expect people to answer it, which means it either needs to be removed or we need to offer support for teachers in facilitating a discussion about it.
<img width="426" alt="Screen Shot 2023-08-30 at 11 38 53 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b89868af-5e7e-4e9e-81bc-7cb18c224ec5">

**Comment by schanzer** [comment]
@flannery-denny the first table is definitely a typo :) Please feel free to change the tables and graphs as you see fit -- I was under the impression these were on your todo lists anyway.

As for the sideways graph -- yeah, let's get rid of it.

**Comment by flannery-denny** [comment]
Thanks @schanzer
How about this part of the question above?

> I think the choice between linear, quadratic, not a function is too narrow as some appear to be functions that are neither linear nor quadratic

ok to change the third category a catchall "Neither" or is "not a function" a learning goal for this lesson that needs to be maintained?


.

**Comment by schanzer** [comment]
@flannery-denny I'm comfortable with neither.

**Comment by flannery-denny** [comment]
@schanzer Now that I've finally wrapped my brain around what exists in the quadratics lesson and started digging into the work, I need to clarify a few things:

-  are we teaching horizontal and vertical shift everywhere other than in linear functions for this release or are we holding off on teaching it everywhere?
- In the linear lesson we introduce other forms after we introduce modeling - Is there a good reason to introduce them sooner in quadratics?
- I feel like Modeling Fuel Efficiency was much more focused the last time I looked at this lesson. Where would I go to see past work on that file to help me remember what this page used to be accomplishing?

**Comment by schanzer** [comment]
@flannery-denny definitely holding them off for this release, as per our conversation yesterday. You've also convinced me now that it makes more sense to introduce other forms after modeling, so by all means make the switch!

GitHub is always the best place to see prior work. For example, [here's the entire git history for the quadratics lesson folder](https://github.com/bootstrapworld/curriculum/commits/master/lessons/Algebra2/exploring-quadratic-models/langs/en-us).

**Comment by flannery-denny** [comment]
@schanzer I've pushed what I have in case you're excited to take this over the deadline today. Trying to make sense of what was here, what should stay, what should get added, etc. has been really hard.

Please do not put the linear stuff live on the web without looking at this page https://github.com/bootstrapworld/curriculum/commit/fa28bddcb646bd86860996a950e651b9d33bf011 and fixing the formatting.

As for quadratics, I've cut what needs to be cut. What's left feels like a mix of functionally skeletal and fleshed out. If the formatting of which form hadn't broken everything when I tried to make it into a table so that the graphs could be bigger, I probably could have thought through a which form page for quadratics fairly easily. I am happy to work on it next week. But I wanted you to have what I have in case you get a surge of wind and feel great urgency.

I think this would be stronger if it waited for Rachel and I both to have bandwidth to read with more distance.

**Comment by schanzer** [comment]
@flannery-denny what page you do want me to look at? The link you shared is a git commit referencing multiple pages, and I'm not sure which one to check.

**Comment by flannery-denny** [comment]
@schanzer `exploring-linear-models/which-form.adoc`

**Comment by flannery-denny** [comment]
@schanzer - Is the goal for the `Given this form (standard, vertex, factored, etc), what is the vertex? What are the roots?` page to provide practice with this or teach students how to do it?
