### ISSUE TITLE
Decide what kinds of workbook pages require use of level 2 headers and what we want them to look like

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1494]
Currently... 

- there does not seem to be a consistent criteria for when we decide to deploy them
- they look completely different on html than they do on pdf and FD objects to both
- on pdfs they render as a heavy grey box that bumps up against `@fitb`
<img width="1011" alt="Screen Shot 2023-08-24 at 9 48 01 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/f86714c1-999e-4bd5-935e-94f1eb6adc84">

- and is similar to but not quite the same as the formatting of table headers
<img width="1006" alt="Screen Shot 2023-08-24 at 10 21 12 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/fa91ad51-e1c6-47a0-af25-f80f0227fac8">

- on html they render as an extra horizontal line that is inconsistently spaced and slightly differently weighted than the other horizontal lines and makes the page distractingly busy
- it feels like they consume vertical space without creating visual space

<img width="921" alt="Screen Shot 2023-08-24 at 9 50 49 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/99c15b0e-5fab-468d-8e12-5e8fae6bc45f">

We have tried to improve them in the past and there were constraints (which I can't remember) that have hopefully been lifted with recent infrastructure improvements.

Is there a use case where we really need something more than slightly larger bolded text?

_Note to help us find examples for future conversation: This issue was created after ES added 2nd level headers to `exploring-linear-functions/horizontal-shift.adoc`, which FD had made without them and there are many other pages FD has made that aren't using them._

Workbook pages not using 2nd level headers that maybe should:
- [ ] Exploring Linear Models - Looking for Patterns
- [ ] Exploring Linear Models - Interpreting Linear Models
- [ ] Surface Area of a Rectangular Prism - Explore
- [ ] Top Down / Bottom Up
- [ ] Exploring lr-plot

**Comment by schanzer** [comment]
- [ ] Make table headers lighter
- [ ] web view should match print view (different color is allowed, but not size/shading)
- [ ] attempt inverted top-level heading

**Comment by schanzer** [comment]
@flannery-denny please take a look at fall2024, and let me know what you think

**Comment by flannery-denny** [comment]
- [ ] How did we end up with purple?! I can't really weigh in on the relative weights when they're not the color that they'll print, but here are a couple of pages that tell me we have a ways to go:
- [age-dot.pdf](https://github.com/bootstrapworld/curriculum/files/13329973/age-dot.pdf)
- [effect-of-an-outlier.pdf](https://github.com/bootstrapworld/curriculum/files/13329985/effect-of-an-outlier.pdf)
- [ ] I'm going to need a css rule for this page to get the headers to be the same height.
[summarizing-columns-moc.pdf](https://github.com/bootstrapworld/curriculum/files/13329938/summarizing-columns-moc.pdf)

**Comment by schanzer** [comment]
@flannery-denny 
- purple will still print as a medium gray, so I assumed we could just get rid of the style rule and let it be purple until someone prints it on a B&W printer. Why give up color when we don't have to?
- See the style rule on summarizing-columns-moc, and let me know if you have any questions about how it works or what it does
- the 3 colors in effect-of-an-outlier are because we changed the header of reguklar tables, but not the sideways table. Fixed.
- I don't understand the "page starts down" comment?

**Comment by schanzer** [comment]
@flannery-denny ah, now I see what top-down/bottom-up page you meant! You did such a nice job uploading pdfs to report bugs on the other pages...can you do that for all of them in the future? Anyway, it's now resolved.

I've also added special CSS print-only rules to make those purple headers go away on workbook pages. :)

**Comment by flannery-denny** [comment]
@schanzer Thanks for making the 2nd level headers and DR section titles render in black and white on the pdf. 

- All other color used in the workbook (pie charts, data cycle icons, etc) serves a purpose and improves upon the black and white version. 
- The purple version of the page headings are discongruous and distracting. 

Now I can confirm that the relative weights of the shading work for me. I think this year's workbook is going to look much more professional. Thanks for your hard work on this!
