### ISSUE TITLE
@optional appears to swallow a sentence that follows it

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1497]
On master in `contracts-tables-displays/index`

The asciidoc reads:

> @optional If your students would benefit from seeing a few more examples before drawing their own Circles of Evaluation, have them @opt-printable-exercise{matching-coe-to-descriptions.adoc}.
> 
> [.lesson-instruction]
> - Have students complete @printable-exercise{coe-displays.adoc}.
> - Displays are often most interesting when compared with other displays. For example, we may want to see how the age range of the animals adopted quickly compares to the age range of all the animals or of the animals that were adopted slowly. *Consider what display it might be interesting to compare each of the displays on this page with.*
> 
> @optional For more practice making tables and displays by composing functions, have students complete @opt-printable-exercise{coe-displays-2.adoc}
> 
> == Synthesize

But when I make the page, the last line before Synthesize is MIA
<img width="863" alt="Screen Shot 2023-08-25 at 11 27 01 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/282c6c15-67f1-40cc-8f8f-2634463d3b5f">

**Comment by schanzer** [comment]
@flannery-denny I just build off `master` and that line shows up for me. 
![image](https://github.com/bootstrapworld/curriculum/assets/77126/a28f51c1-0dbf-4c90-9be9-38907bf2cfb0)

It also shows up on the web.

Can you try deleting the folder and rebuilding?

**Comment by ds26gte** [comment]
Don't really know why the straightforward translation to asciidoc wasn't working. Changed it to something that the postproc converts to an explicit HTML span. Seems to solve issue.

**Comment by schanzer** [comment]
Confirming this is fixed!
