### ISSUE TITLE
create rubrics for all early math projects in PPS scope and sequence and SOME project pages

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1500]
Alignment guides: [Grade 6](https://docs.google.com/document/d/17xVBukZ55njPAQNVYWaI4DQviQN_LbdvuDF3et-dbO4/edit?usp=sharing), [Grade 7](https://docs.google.com/document/d/1LcsXkNC-IaRbjwPI9z3wyewv56H9LRMo-OACpmNMej8/edit?usp=sharing), and [Grade 8](https://docs.google.com/document/d/11QGTMlxymgB8hGUGcNlLUa9crsChXSPH3tbb_Z8MSbM/edit?usp=sharing)

**Grade 8:**

- [x] Unit 2 Project (~2 days): Students come up with a function of their own, which takes a shape and manipulates it using at least three transformations. They submit their Pyret files, which contain the function definition.
- [x] Note that units 3&4 have no projects. Could there be something?

**Grade 7:**

- [x] Unit 1 Project (~5 days): Making a logo using the shape producing functions, along with rotate, scale, overlay, above, below, and beside. As part of their projects, students should submit: A sketch of the logo they want to draw; A Circle of Evaluation, showing how their functions are composed to make the logo; A working program that generates that logo
- [x] Note that units 3&4 have no projects

**Grade 6:**

- [x] Unit 2 Project: Print, and construct a rectangular prism - how many different nets can you come up with to create the same shape?
- [x] Unit 3 Project: Have students complete [this workbook page](https://bootstrapworld.org/materials/fall2023/en-us/lessons/evaluating-exponents/pages/exponents-variables-table.html), then give them the solutions for the third column. Have them type the code in Pyret and see if they were right. Have teams of students create challenges for one another, using opposites, absolute values, and exponents.

**Comment by schanzer** [comment]
@retabak how is this different from #1495 ?

**Comment by retabak** [comment]
Lol. It is exactly the same. I forgot that I made that. This one is clearly more detailed. Gonna close the old one.

**Comment by retabak** [comment]
Identify projects that will be taught before December.

@schanzer gives me the thumbs up on creating project pages for projects to be taught before December.

**Comment by retabak** [comment]
started doing some thinking here: https://docs.google.com/document/d/1cMjRb13AUW5tcql6x4fm47LSCk7skRbICWzTq-bB-WE/edit
