### ISSUE TITLE
mathjax isn't rendering in fitbruby annotation

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1502]
Here's an example where the @math bleeds through.

`A @fitbruby{10em}{}{@math{\Delta} pct-college-or-higher} change in the percent of the population that attended college or higher translated to a @fitbruby{10em}{}{@math{\Delta} median-income} dollar change in median income.
`
<img width="245" alt="Screen Shot 2023-08-28 at 4 46 48 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/9a675151-3630-47cb-a1df-5190c8bab9b2">

**Comment by flannery-denny** [comment]
@ds26gte reports that this is a systemic failure... but offered the brilliant suggestion that I just use the unicode character `&#916;`

If it's easy to get mathjax working for fitbruby annotation it'll be a win. 

Regardless, we are reminded that leaning on unicode rather than mathjax is good policy.

**Comment by schanzer** [comment]
Yeah, this has never worked before. @ds26gte how much of a headache is it to get mathjax working here? It does seem like it would be good for authors to assume they have the same set of tools regardless of which part of a directive they are editing...

**Comment by schanzer** [comment]
Thanks, @ds26gte !
