### ISSUE TITLE
Review of Exploring Linear Models Lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1505]
This lesson is ready for review.
The three things you can expect to change are:
- We're building a workbook page for the _Other Forms of Linear Models_ section that provides students with 3 sets of details from the dataset, each one better serving a different form of the line. Have students write that form of the line and then transform that form of the line into a pyret function.
- We're adding a pedagogy box that flags DC as a consistent outlier of interest for teachers and provides them with a list of relationships to explore that will yield correlations and ones to avoid.
- By the time you read the lesson, @schanzer will likely had made a commit to the lesson that changes this lesson instruction box in the Fitting Linear Models section so that there are two versions of the page [Build a Model from Samples: College Degrees v. Income](https://github.com/bootstrapworld/lessons/exploring-linear-models/pages/model-college-v-income-A.html), one optional one with significant scaffolding and one without that will be the one included in the workbook.

**Comment by retabak** [comment]
- I very much like that exploring-states has been added to the lesson. I think it's a good opportunity to play around with functions for working with tables + making displays in a relevant context. yay!
- I'm very confused by the flow of the launch in "looking for patterns." It is confusing that all this instruction about scatter plots + variables leads up to a worksheet (exploring-states) that has literally nothing to do with either of those. Similarly, the [instruction-box] that introduces exploring-states says we'll be searching for possible relatinoships within the data! All of this made me feel like I'd opened the wrong worksheet when I fingally clicked on exploring-states. **Can we move things around?** (don't be scared! Not asking for a huge overhaul!) Basically, I propose we open the launch by saying, "Let's review these functions we learned about in the last lesson!" Then kids do exploring-states. THEN provide all of the instruction about scatterplots and variables, which flows very nicely and naturally into looking-for-patterns.
-

**Comment by flannery-denny** [comment]
@retabak can you please push your proposed revision so we can see it?

**Comment by retabak** [comment]
I'm not sure why the circled red part is right here (see screenshot below). It seems to disrupt the flow of the lesson and I'm unclear what purpose it's serving. My best guess is that you're aiming to make sure students understand what each of the columns actually mean? If that's the case, I'd instead put a new [.lesson instruction] that opens with something like, "Let's make sure we're clear on what each of the columns represents...." Then you could put the red-circled questions in the text box, with @teacher{} underneath saying something like, "Invite students to discuss and ask questions about the meaning of any terminology they may not be familiar with."

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/947255c1-3d37-4978-8a48-5f6f92ce8235)

**Comment by retabak** [comment]
looking-for-patterns is solid! I don't remember what it was like the last time I saw it, but I feel like this version is much better! Feels very nicely scaffolded.

**Comment by retabak** [comment]
fyi, @schanzer, I see you commented out the the section on horizontal and vertical shifts, but the Desmos activity and all of the relevant optional worksheets are still appearing on the lesson table.

**Comment by retabak** [comment]
All of the optional matching pages have a typo in the boldface part of the instructions: "*Match each definition below to the linear model describes.*" I was going to fix it, then realized I wanted to change terminology also, and figured that might not sit well with the two of you....

Given that these worksheets look like straight-from-the-alg2-textbook pages, it's weird to see the words "linear model" and "definitions". Feels contrived and even potentially confusing that we're saying the graphs represent a line of best fit derived from data. If it were up to me, I'd just say, "Match each linear equation (in point slope, in standard form, whatever...) to the corresponding graphical representation." I think it's okay for an optional page that is clearly a skills review **not** to connect to data science.

I also wonder if stuents / teachers will know if it's okay to label anything *other than slope-intercept* a definition. (tbh, I wonder about this. School me, please.)

**Comment by retabak** [comment]
Man, sorry all of my comments here are in such a jumble!

I did a bunch of copying and pasting to make the first section of the lesson flow better. Here's my thinking:

(1) Launch - get familiar with the states dataset + starter file, discuss column names / unfamiliar terminology, review table functions 
(2) Investigate - part 1: return to animals as a context for introducing data science content (scatter plots, exploratory and response variables)... part 2: dig back into states dataset
(3) Synthesize

If this feels like too much of a change at the last minute.... feel free to reject! This feels way more coherent to me, though!

**Comment by retabak** [comment]
Last comment in this mess of comments.....

Should we put slope-intercept, point-slope, and standard form to the glossary?

(BTW, we were inconsistent about capitalization of those terms. It seemed like more often than not, we capitalized, so that's what I went with.)

**Comment by schanzer** [comment]
@retabak I think it's fine to capitalize. I've added english definitions to the glossary, and I'm waiting to hear back from Mariana about spanish translations for them.
