### ISSUE TITLE
in our glossary for the correlations lesson, r and correlation both get listed, with different but nearly identical definitions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1507]
clean up 
- [x] correlation definition
- [x] r definition
- [x] R^2 definition
<img width="887" alt="Screen Shot 2023-08-30 at 8 45 09 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ed177a5b-e292-4c83-93b2-7beaa8b7ee11">
 
Current definition of R^2 is: 

> a number between 0 and 1 that measures the strength of a modeled relationship between two variables

Perhaps we want something more like:

> A value ranging from 0 (no correlation) to 1 (perfect correlation) describing the percentage of the variation in the y-variable that is explained by the x variable in our model. e.g. a value of 0.20 could mean that “20% of the variation in median household income is explained by the percentage of college degrees in a state, according to our linear model”. 

While you're in the flow, we should also add definitions for 
- [x] quadratic relationships
- [x] parabola

And I imagine there are a bunch of other definitions to add for
- [x] exponential relationships
- [x] logarithmic relationships

Translate
- [x] add spanish translations for point-slope, slope-intercept, and standard form (linear) - FD

**Comment by flannery-denny** [comment]
@schanzer flagging we can't release beta materials until these vocab words (and I imagine there are others) are added.

**Comment by schanzer** [comment]
@flannery-denny these are ready for review
