### ISSUE TITLE
Find more correlations for modeling lessons

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1508]
Expect this to be interesting and effortful!

Explore possible correlations in the states dataset and make notes that can be used for the following:
- [ ] create a pedagogy box for teachers that will let them know anything you wish you would know as a teacher about fruitful / waste of time searches you conducted. 
- [ ] Identify correlations worth making models for that can be used for fleshing out three scenarios for a page like this `exploring linear models / which form` https://github.com/bootstrapworld/curriculum/commit/28652262123c3050339637d56c78b31c8d04c3c2   **(perhaps this can be accomplished from a single correlation?)**
- [ ] If patterns appear that could be modeled by quadratic, exponential or logarithmic functions, those lessons could use similar pages

**Comment by retabak** [comment]
I am so sorry Flannery, the day slipped away from me. Wish I could have gotten to this. Sigh.

Would love to tackle these next week.

**Comment by flannery-denny** [comment]
This was a specific small issue that I made for @retabak on a week when she thought she had time to support algebra 2 work last summer and we were racing against a big deadline. In the end, she didn't actually have time, so there's no need for the smaller issue and it should have been closed a long time ago.
