### ISSUE TITLE
Review Quadratics lesson

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1509]
- [x] Make sure all pages that need to be in the workbook are
- [x] Audit section overviews
- [x] Make any small changes
- [x] Check with Flannery/Emmanuel if they're online and there's a _big_ change, otherwise just go ahead and make it
- [x] Emmanuel adds annotated table showing growth
- [x] Flannery cuts "other forms" section, adds beta teaser

TAG THIS ISSUE with any related commits

**Comment by retabak** [comment]
first section:
- [ ] In the starter file, we say that speed is "the speed at which the car was tested." We need to specify that it is miles per hour. (I'm assuming that's what it is?) @schanzer - can you update?
- [ ] We need to launch the lesson with some general "hook" questions asking kids what they know about fuel efficiency, e.g. what do they think affects fuel efficiency? Do they know anyone with a fuel-efficient car? Is it possible to be a fuel-efficient driver?
- [ ] I was just wondering if the Fuel Efficiency dataset included hybrid vehicles, so checked the Read Me tab and learned that the dataset is fictional. Perhaps it's obvious (the models are just letters) but I think we need to disclose this in the lesson. I'm actually not sure how, though.  I also do think that kids will want to know if the dataset includes fuel efficient cars. [added this to issue #1345]
- [ ] The revised "Read Me" needs some love. It currently has text about Brown students and COVID data.

second section:
- [ ] changing optional worksheets so that are @printable-exercise

**Comment by retabak** [comment]
OK - my biggest changes involved adding a hook to section 1, moving chunks of text around (within and between sections), clearly flagging for teachers what's coming up next (we were jumping into and out of the dataset without any warning, which was gave me whiplash), changing the formatting of a table in the lesson that looked ugly and wasted white space.... and I think that's about it?

**Comment by schanzer** [comment]
@retabak overall I like the changes in section one. I simplified some of the wording in places (you are so clearly a grad student!), and adjusted some of the voice to be consistent with our other lessons. Overall no major changes on my part. A few questions:

- At one point you ask "What would a table of a _perfect_ quadratic relationship would look like?". Do you expect students to know this already? Even after a fair amount of googling, I'm not even clear on what it means, myself
- I can't help but feel like we're tripping over ourselves to _not_ teach about first and second difference. Consider this text, which is already in the lesson:
![image](https://github.com/bootstrapworld/curriculum/assets/77126/0a859e18-87e2-4764-b5cc-ff2c088603c4)
- I absolutely love the parabolas worksheet! Awesome job, @flannery-denny 
- The modeling section still has some vestigial text from when it came after teaching other forms. Now that it comes first, we don't need to name the form or tell kids why it's a good place to start. I cleaned up this text as well.
- @retabak I notice that you do a lot of telling kids what's coming up. In one of the lesson instructions, for example, you format it as if these are separate instructions. But actually it's just four things kids will do in that one workbook page. We don't really do this elsewhere, do we? It feels jarring to me, and in a classroom setting this is a lot of words that will be lost unless you intended to have them work through it in separate pieces. Is that the intent?
- I'm not ok cutting `graphing-models.adoc` from this lesson -- teachers overwhelmingly thought it was one of our strongest pages in PD, because it really set them up with intuition for fitting their model later. I've brought it back and changed the framing slightly. This also obviates the need for a "translating quadratics" section entirely.

**Comment by retabak** [comment]
Just pushed a commit to respond to your comments, @schanzer. Also typed in some replies above.

**Comment by schanzer** [comment]
- I don't think we should assume kids know what a parabola is before this lesson. But yeah, that doesn't impact the edits in this review specifically.
- I think your new wording for 1st difference is way simpler. Love it! But what I'm getting at is that _you're essentially already teaching 1st difference_. You're just not calling it that. That's why I feel like this lesson is itching for it. And it's not enough to just compute 1st difference and say "welp, it's not constant so it must be quadratic!" That's simply not true -- and telling part of the truth is worse than saying nothing. If we're going to talk about 1st distance, we need to talk about 2nd distance.
- I agree that we want teachers and students to see the big picture, but I don't think you're accomplishing that by telling them how all of the little pictures fit together ("we'll do this, then this, then _this_...). I think we just need a broader summary that gives them an overall sense for what needs to happen.  I'd love to work on that, but I'm too fried right now for wordsmithing. If you want to leave this as a TODO for me tomorrow, that's fine.

**Comment by flannery-denny** [comment]
I've pushed some changes to:

- make sure that lesson dialog does not give away things we're then asking students to think about on workbook pages
- make a note about the fact that the patterns we see in tables of functions will not appear in tables of real world data sets, which don't perfectly fit the model

**Comment by flannery-denny** [comment]
fyi - I decided that since there are optional workbook pages for other forms provided in the Additional resources section and they have the forms described at the top, I wouldn't add the table back into the lesson plan
