### ISSUE TITLE
Review Exponentials lesson

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1510]
- [x] add growth factor to glossary 
- [x] confirm that the tables in `what kind of model (tables)` actually make sense... and that this reference to them in the lesson plan declares the correct tables to be exponential - **ES**
> Exponential functions, like the ones you identified on tables 2 and 6, can be written in the form
- [x] Make sure all pages that need to be in the workbook are
- [x] Audit section overviews
- [x] clear up this wording about r - **FD**

> Discuss in groups or pairs, and prepare to share out to the class:
> 
> Based on the look of this scatter plot, do you think there’s a strong correlation here?
> 
> If we fit a model to this data, would it have a high r- value?
- [x] the link to the full covid dataset from the _Why are we starting from June 9th?!?_ pedagogy box should_ go to a starter file that's ready to use, not the google sheet. - **ES**
- [x] Make any small changes
- [x] Check with Emmanuel if they're online and there's a _big_ change, otherwise just go ahead and make it
- [x] TAG THIS ISSUE with any related commits
- [x] Emmanuel adds annotated table showing growth
- [x] Add discussion of asymptote
@schanzer - didn't add discussion of asymptote, but I agree that it belongs. ALso noting that I think it should go under the instruction box and before the table I made about b (screenshot below). We should also mention it in the answer (in instruction box) to "what does k tell us about an exponential function"

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/3fb1f890-d1ae-4565-9f28-c604289f1575)

**Comment by flannery-denny** [comment]
- [ ] The link to the dataset for all 50 states doesn't work
- [ ] Noting that, if space weren't an issue, exploring the covid dataset would definitely have a part 1 and a part 2. Wondering whether that means that it really should be on two separate pages?

**Comment by flannery-denny** [comment]
@schanzer Would be great if you could tackle some of this before @retabak gives it a read. Moving on to reading and making checklists for logarithmic models.

**Comment by schanzer** [comment]
Thanks, @flannery-denny ! I've pushed a number of changes that address all of these. A few responses/notes:

- I'm not sure I agree that the conversation about quadratics not being a good fit should be rooted in R^2. After all, the R^2 is pretty decent for some of them! I'd argue that the crux of this section is all about using our eyes rather than focusing only on numbers. The R^2 of a linear model can look good for a particular dataset, but the _shape_ of the data is all wrong. Leaving this open for us to discuss.
- Your feedback really made me think that all of the "classifying" pages need different titles. I've pushed that here, as well.
- Grading exponentials should have been removed from the lesson for this release. my bad.
- In "classifying descritions", we're not short on space so there's no harm in leaving part (e) for all. Moving it to a separate section makes is much more difficult for students to express solutions, and hinting that only two are exponential feels like too much of a giveaway.
- I thought about re-ordering the sliders in the desmos activity, but aside from fitting _k_ first I'm not sure there's another, clearer order. Do you have one in mind?

**Comment by schanzer** [comment]
@flannery-denny @retabak I feel like we should be introducing the notion of an asymptote in this unit, rather than in the logarithm unit. If we're going to bring it up at all, it's weird not to explain it in the first place where it shows up.

**Comment by retabak** [comment]
@schanzer - did you make an image with an orange line? The accompanying text refers to an orange line. Hoping an image is saved somewhere and can be added!
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/264fb6ef-eb6f-45a2-a94f-f3a0cac8e412)

**Comment by schanzer** [comment]
@retabak [yes](https://github.com/bootstrapworld/curriculum/blob/master/lessons/Algebra2/exploring-exponential-models/langs/en-us/images/MA-covid-linear.png). You need to rebuild.

**Comment by retabak** [comment]
@schanzer - I like this introductory stuff a lot. But obviously, "What kind of model? (tables)" needs to immediately follow it, given that it is a direct application. I'm going to move some stuff around, and break our pattern of starting with "what kind of model? (descriptions)".

Feels like a no-brainer to me, hope everyone is okay with it!

I haven't gone back and looked at linear models or quadratics, but this conversation should be woven in sooner eventually. (maybe you already did?!)

**Comment by retabak** [comment]
Exponential Functions
- [ ] put "what kind of models" immediately after launch
- [ ] moved direct instruction / key definitions to the earlier in the lesson, where they are needed
- [ ] delete classifying-plots
- [ ] do we need to add "growth value" and "inital value" to the glossary?
- [ ] create a segue leading from launch into the desmos graphing-models activity.... and added segues everywhere.
- [ ] added a narrative and synthesize questions to motivate looking at four different representations of exponential functions ... I suspect we need to do this in all lessons.

**Comment by schanzer** [comment]
@retabak I don't think those two terms are specific enough OR used commonly enough for this concept that we shou;d add them. Really love your rearranging as well!

**Comment by schanzer** [comment]
@retabak discussion of asymptotes added! I think this one is ready for final review as well.

**Comment by flannery-denny** [comment]
@retabak please lmk when you've done the last move of exponential model forms so I can have a final read. Thanks!

**Comment by retabak** [comment]
@flannery-denny - ready for you to review!!

- [ ] noting that classifying-defs answer key needs to provide growth factor and initial value when exponential (I need to get to Logs or I'd fix this! sorry)

**Comment by flannery-denny** [comment]
- [ ] desmos link is broken on linear models for ma-table

**Comment by retabak** [comment]
@flannery-denny - try pulling again. I pushed something pretty recently. LMK if it still doesn't work.

**Comment by flannery-denny** [comment]
- [ ] Seeing this in the rewrite. It's not true. Need to fix wording
<img width="735" alt="Screen Shot 2023-09-13 at 10 19 45 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/98879775-31df-4c63-8e99-611e151c6e9a">

**Comment by schanzer** [comment]
@flannery-denny confirmed. Thanks for catching that!

**Comment by retabak** [comment]
I think it was me! Thank you!
