### ISSUE TITLE
Review Logarithms lessons (both!)

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1511]
- [x] the lesson point that introduces logarithmic form for equations feels very misplaced - where should this actually come into play? - **RT**
- [x] Answer "As a class: why are these coefficients similar to one another?" - **ES**
- [x] Make sure all pages that need to be in the workbook are
- [x] Audit section overviews

- Make any small changes
- Check with Emmanuel if they're online and there's a _big_ change, otherwise just go ahead and make it
- TAG THIS ISSUE with any related commits
- [x] Emmanuel adds annotated table showing growth

**Comment by flannery-denny** [comment]
- [ ] Add to glossary: logarithmic function/relationship, asymptote
- [ ] solution pages are missing
- [ ] Exploring the Countries - exponent from R^2 is landing on the fitb
- [ ] Could we call `Transforming the x-Axis` something more like "Logarithmic scaling"

**Comment by flannery-denny** [comment]
@schanzer I'm going to pick up with this in the am. Can you tell me why these are two separate lessons?

**Comment by schanzer** [comment]
@flannery-denny they _once_ were. No need to continue with them as separate lessons.

**Comment by flannery-denny** [comment]
@schanzer Please have a look at `transforming-data.adoc` and ask yourself whether it really needs to be written with such an unfriendly intro of garbledygook.  I have been seeing an increasing amount of specialty css rules and definitions used in `.adoc` files and would like to encourage you not to use that as your default. It makes it harder/more time consuming for me and Rachel to edit files you've made. And it will make onboarding anyone else much more complicated if they find themselves confronted with files like this one.

**Comment by schanzer** [comment]
@flannery-denny aside from the easily collapsible CSS at the top of the page, can you tell me what you find unfriendly? If it's just the CSS at the top, I can move that to a separate file so you don't need to look at it.

**Comment by flannery-denny** [comment]
The @font-face section is ugly as all get out and goes on for several screens! long enough that it's hard to know whether there will be anything intelligible to follow. 

But the kind of thing that has actually made it time consuming to clean up files you've made recently is css like this:

> ++++
> <style>
> .studentAnswerMedium { min-width: 8em !important; }
> td { padding: 0 !important; }
> body.workbookpage .fitbruby { padding-top: 1.1rem; }
> .center { padding: 0; }
> .shortFitb .fitb { padding-top: 0.5rem !important; }
> .tallFitb .fitb { vertical-align: bottom !important; }
> </style>
> ++++ 

where it's effortful to decide when and when not to keep your special new formatting because I have to figure out how many times it's been applied to a file and whether removing it from the spot I'm working on will break other things.

**Comment by schanzer** [comment]
@flannery-denny thanks - knowing what the problem is makes it much easier to identify a solution. Sounds like you're concerned about three specific files from a different lesson. I'll push a commit momentarily that resolves the issue.

**Comment by flannery-denny** [comment]
Thanks @schanzer. I don't necessarily need a fix in the other files. But I definitely think a fix in the file in this lesson would be worthwhile.  Mostly just wanted to flag that I'm seeing more and more stuff at the top of `.adoc` files and wanted it to be on your radar that, while it serves a purpose, it has an impact on other authors and should be used with that cost-benefit consideration in mind.

**Comment by schanzer** [comment]
@flannery-denny factoring out the CSS and improving the authoring experience required a lot of learning about asciidoctor, but I think the hour was well-spent. I've pushed an update that affects `transforming-axis` and `transforming-data`, which I think will make you happy.

**Comment by flannery-denny** [comment]
@schanzer I love the idea of using `fragments` for this! What an improvement! 

For some reason one of the icons in `transforming-axis` now says `FOO` and the dotted circle is appearing as the inverse version of what it previously looked like.

**Comment by schanzer** [comment]
@flannery-denny I want to push back on the idea that students need to practice building another column their own. This is not a learning goal for the lesson, and level of comfort they need with defining filter and build functions is _very_ minimal. I think adding more practice for them here shifts the lesson more fully in the direction of programming, when it really should stay rooted in logarithms.

**Comment by retabak** [comment]
**Looking for Patterns**
- [ ] the links to the desmos pages in exploring-countries open in the same tab, rather than a new one. Can we fix that @schanzer ?
- [ ] All of the various hyperlinks in exploring-countries go to the same page, and not to individual slides. If we can't change this (I don't think we can?), it would make more sense to say "Advance to the next slides of the Desmos activity, and find the best quadratic/exponential model you can."

**Logarithmic Functions**
- [x] first image feels redundant and extraneous. (Maybe it existed before we had the Desmosm activity in Looking for Patterns?) Deleting it.

**Comment by schanzer** [comment]
@retabak I've updated the exploring-countries page to fix the issues you listed. Thanks for reporting!

**Comment by flannery-denny** [comment]
- [ ] Decide whether we want them discussing shape of the scatter plot for median-lifespan versus pc-gdp in the first or second lesson section. Right now we're discussing twice.
- [ ] I'm seeing a transforming wealth/data practice page in the repo that isn't linked in the lesson plan. Looks good to me. Wondering if there's a reason it isn't linked? Currently there's an optional challenge problem on logarithmic models that I think addresses the same thing, but doesn't provide scaffolding. Need to remove the question from that page if we include the other.

**Comment by schanzer** [comment]
@flannery-denny I believe I've addressed all of these issues. Let me know if some of them still feel undone?

**Comment by flannery-denny** [comment]
@schanzer why are the rows of this table so much taller than others?
<img width="854" alt="Screen Shot 2023-09-15 at 10 24 54 AM"
 src="https://github.com/bootstrapworld/curriculum/assets/66691020/7a666a44-c1de-4741-818d-0abed809e547">
such as this one, using same asciidoc table
<img width="922" alt="Screen Shot 2023-09-15 at 10 24 20 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/7f859521-7555-49b3-9692-0576b7709943">

**Comment by schanzer** [comment]
@flannery-denny I've pushed solutions for all but one of your checkboxes. I don't think it's possible come up with a meaningful set of solutions for the page where students are making models of their own.

Is the lesson ready to have slides made? I feel like now all the feedback is on the workbook pages...

**Comment by flannery-denny** [comment]
ready to ship once @schanzer makes slides and checks solutions
