### ISSUE TITLE
Early Math needs a teacher resource page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1513]

**Comment by retabak** [comment]
The page is not super full of exciting things, but this issue can be closed once @ds26gte looks into the issue with @all-lesson-notes ... Thanks, Dorai!

**Comment by ds26gte** [comment]
We're only including those `notes-*` pages in `@all-lesson-notes` that are valid workbook pages, i.e., are in the lessons's `workbook-pages.txt`. This course's lessons do have `notes-*` pages but they're not workbook pages. Let me know if we need to rethink which `notes-*` pages qualify for inclusion in `@all-lesson-notes`.
