### ISSUE TITLE
bug: @teacher is swallowing bullet formatting

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1514]
I noticed this in the exploring exponential models lesson. changing from `-` to `*` doesn't seem to have any effect

<img width="925" alt="Screen Shot 2023-09-06 at 3 50 21 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/6ab9b961-dc76-48f8-b7c2-9553cb098c8e">
<img width="862" alt="Screen Shot 2023-09-06 at 3 50 30 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d9bda3d2-342b-4c08-9e7e-5994922f90b8">

<img width="846" alt="Screen Shot 2023-09-06 at 3 51 26 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/f1f701d5-9fc2-4dac-91db-a753b1ee21c9">

I solved it by adding a blank line after the opening `{` but in sublime the resulting grey strip makes it look like that would break something...
<img width="913" alt="Screen Shot 2023-09-06 at 3 54 27 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/a0b348ae-20b1-449b-a1be-e76a5d70fc0c">

But, what we actually want here is for the last two bullets to be indented, which usually works when you start with `**` and @teacher seems to break that regardless of whether there's an extra space in the document.
<img width="911" alt="Screen Shot 2023-09-06 at 3 58 58 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b0062ed5-0ec4-434a-93c2-769caafb74b7">
<img width="857" alt="Screen Shot 2023-09-06 at 3 59 30 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/f7ea4a8b-c76f-4d3f-961a-23c6d8a67fe3">

**Comment by schanzer** [comment]
@ds26gte this bit me the other day as well

**Comment by ds26gte** [comment]
`@teacher` wraps a span of class `.teacherNote` around its argument. Obviously, putting a span around a contiguous sequence of items in a list breaks their item-ness in HTML. The intent in this example is perhaps best expressed by wrapping `@teacher` individually around each item in the list.

However, I also note that you're not actually using `.teacherNote` to style anything. What was `@teacher` meant for in the first place anyway?

**Comment by schanzer** [comment]
Ohhhh - I didn't realize this was being used to highlight _part_ of a list. Yeah, @flannery-denny that won't work. We've already talked about needing a more sophisticated solution for Q&A formatting.

@ds26gte as long as `.teachertNote` is preserved as a class, we're good. Just because we don't use it _now_ doesn't mean we won't in the future (we totally will)
