### ISSUE TITLE
nitpicky css problem on graphing-models in exponential lesson

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1515]
Sometimes b jumps up above the rest of the text and looks kind of like an exponent?

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/eb384ea7-bb23-4c79-8fb7-a3c9018a0ef3)

**Comment by schanzer** [comment]
@retabak what do you mean "sometimes"? 

- in some browsers?
- at some zoom levels?
- between forced builds?

Importantly: have you tried printing to a PDF?

**Comment by retabak** [comment]
When I say sometimes, the only instances in my sample size are the ones in the screenshot. B looks okay in 6, but weird in 5.

- at 100% zoom, b is weird. At 125%, it looks normal again.
- in a different browser (edge) it looks exactly the same (weird) as it did in chrome (which I was using for that screenshot)
- in PDF, b looks normal, but YIKES, there are @fitb lines going right through the 2nd level headers - !? I'll attach my PDF. That needs to be addressed. [Graphing Exponential Models.pdf](https://github.com/bootstrapworld/curriculum/files/12552483/Graphing.Exponential.Models.pdf)
- don't wanna do a forced build right now, but can investigate later.

**Comment by retabak** [comment]
update: b still looks funny after forced build. 

The PDF that I built looks fine, though.

**Comment by schanzer** [comment]
@retabak I made some small changes that should make the printing more stable.

The bouncing-b is an interaction between Mathjax and the browser. There's no way for us to fix it.

The good news: it won't matter for printing. 
The better news: #1504 will reduce the places we use MathJax, making this sort of jiggling far less common
