### ISSUE TITLE
guidance / pointers sheet for using desmos

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1520]
Link to this page should be automatically generated for any lesson with desmos activities.

Seeing @flannery-denny's concerns about desmos has me thinking that perhaps it would be helpful to highlight for teachers some of the useful features of desmos. 

That said, while it is not intuitive to *create* desmos materials, it is shockingly easy and intuitive to USE desmos materials in a classroom with stuents. I suspect teachers who are new to desmos will figure out its most useful features almost immediately. 

anyhow, I'm not sure if this is a good idea, but perhaps it merits discussion.

**Comment by retabak** [comment]
see if we can add some text to move teachers from "interested in trying" to "okay, i'm going to give it a try!"

**Comment by retabak** [comment]
@flannery-denny - I started poking around the internet to see if there was anything available on the web resembling what I would want to make, and I found these three guidance pages. Do you think we could just link to them? I was imaging maybe putting the text below into the "Teacher Preparation" section of the lesson table. (Still happy to write something - this just looks better than anything I would be able to create.)

"This lesson includes some Desmos activities. Although it can be intimidating to explore new software, Desmos is fun to use and offers teachers a wealth of information on student learning. If you need some help, check out these three guides: [Getting Started](https://my.amplify.com/help/en/articles/6684337-getting-started-desmos-classroom-activities), [Using the Teacher Dashboard](https://my.amplify.com/help/en/articles/6684323-using-the-teacher-dashboard), and [Classroom Conversations](https://my.amplify.com/help/en/articles/6763511-classroom-conversations)."

**Comment by retabak** [comment]
add these to the lesson table in relevant lessons.

**Comment by flannery-denny** [comment]
@retabak I'm happy to link to the materials you found, but I am still going to need you to draft some text and I will do a better job of describing what it's for in the relevant issue.
