### ISSUE TITLE
Multi-letter identifiers in MathJax

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#1523]
We have very many multi-letter identifiers in expressions such as `seconds`, `height(seconds)`, `line-length`.

As they are, these would typeset as sequences of letters, similar to algebraic multiplication, with no kerning, so they don't look like words.

An allowance has been made for hyphens, which are input as `\mbox{-}`, e.g., `line\mbox{-}length`, so that the hyphen doesn't look like a minus sign.

It may be better to input the examples as 
```
\mbox{seconds}
\mbox{height}(\mbox{seconds})
\mbox{line-length}
```
so you (a) not only get the correct kerning, but (b) they show up as roman, thus adding to their distinction from sequences of single-letter identifiers. If we do want them to be italic, we can use `\mbox{\it seconds}` instead of `\mbox{seconds}`, in which case the only thing distinguishing them from sequences of single-letter identifiers is the kerning.

Let me know which you prefer. The way things stand is not ideal.

**Comment by schanzer** [comment]
@ds26gte I so appreciate you looking into this! Let's go with non-italics for now, as it seems like the cost of switching to italics is really minimal.

**Comment by ds26gte** [comment]
I've tried to search for and push changes for every @math identifier that had this problem. Let me know if I missed aught.

**Comment by schanzer** [comment]
These are looking great, @ds26gte . I'm sure we'll continue to find some places where we need to rewrite the asciidoc/mathjax - and even some places that require further tweaks to the heuristic - I think we're ready to close this out.
