### ISSUE TITLE
fixes from OK PD

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1524]
- [x] domain of half-image should be image
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/6fa4bcf8-58dd-4c67-871c-98801660be63)
- [x] do we have a URL (on the teacher resource page) to the blank contracts page in the back of the workbooks for teachers to print? (Email rachel brainard once we do.)
- [x] should this say "5 times as wide as they are tall"?
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/b18c1bf8-0be6-4dfb-9398-43f754958084)
- [x] @flannery-denny - simple inequalities - The Booleans section of the lesson feels totally redundant, given that Simple Data Types is a Prereq. I think we should delete it entirely and include a note in the second session that says something like, "If you think your students would benefit from a review of Booleans before digging into this lesson, here and here [hyperlinks] are some activities you might consider having them complete." (Noting that Samatha *did* do that section today during PD and I think teachers were bored and confused to be reviewing pretty simple stuff that they already mastered.)
- [x] simple inequalities directions do not mention the starter file, but the lesson explicitly instructs kids to use starter file. I think we might even need to recap HOW to use the starter file to complete this table. Same problem exists in compound-inequality-solutions.adoc @flannery-denny - also see next two items on this list, also concerning compound inequalities
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/d58e3c51-bf55-40c0-a36d-0225b56d78d9)
- [x] compound inequalities slides need to be updated to include links to new worksheets that were previously optional - [particularly this one](https://bootstrapworld.org/materials/fall2023/en-us/lessons/inequalities2-compound/pages/compound-explore.html) 
- [x] compound inequalities - we should also remove the discussion prompts (that are copied from the worksheets) from the lesson plan
- [x] I think we're trying to teach something about functions when we say is-onscreen takes in an X and Y coordinate... but there's no instruction around it / discussion of it anywhere. Teachers did one of two things as a result of the starter file and workbook page saying that is-onscreen consumes an x coordinate and a y coordinate. (1) They tried to write code to detect if Sam was onscreen up, down, left and right. (Waaaaay harder than the intended task.) (2) They defined is-onscreen to have just ONE input, assuming that is-onscreen(x, y) was a typo. 

To be totally honest, I thought two inputs was a mistake until I remembered our discussion / debate around that one item on the algebra misconceptions survey. **Can we add a pedagogy box or a worksheet question specifying what the specific learning goal is with this decision?** I completely missed the mark as a facilitator because there was nothing in the lesson, the slides, or the worksheet explaining what this is about. (It's okay, I'll live... but I'm a little embarassed. It also feels TOTALLY unfair to address this concept on our misconceptions survey if we don't *really* discuss it in this perfectly relevant context.) @schanzer - this feels like something that maybe you should take on?

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/840c2964-c685-499a-b508-447dd6bd7863)

**Comment by flannery-denny** [comment]
I feel pretty confident that this page can be completed without using a starter file ;) FlanneryOn Sep 16, 2023, at 12:44 PM, retabak ***@***.***> wrote:﻿

 domain of half-image should be image

 do we have a URL (on the teacher resource page) to the blank contracts page in the back of the workbooks for teachers to print? (Email rachel brainard once we do.)
 should this say "5 times as wide as they are tall"?

 simple inequalities directions do not mention the starter file, but the lesson explicitly instructs kids to use starter file. I think we might even need to explain HOW to use the starter file to complete this table. @flannery-denny

**Comment by retabak** [comment]
The lesson explicitly instructs students to use the starter file? If you don't want kids to use the starter file, then the lesson instruction needs to be changed. Also, kids aren't doing a whole lot with the starter file if they aren't using it for the worksheet.

**Comment by flannery-denny** [comment]
@schanzer 
- How do you feel about me moving the Booleans section of the Inequalities lesson into a pedagogy box at the start of the lesson? 
- I think I had also considered cutting this at some point since it's inception and you thought it was important to review a complex concept... and argued that teachers might be bored, but students will be experiencing these lessons with more space between them than teachers in pd would. 
- Alternatively, I could move the Booleans materials to the simple datatypes lesson as additional resources.
- Noting that the page that accompanies the starter file is currently included in the Algebra workbook.

**Comment by flannery-denny** [comment]
@retabak Emmanuel wanted us to keep Booleans in the lesson - doesn't necessarily have to be a priority for pd just because it's there. It was missing an overview so I added one which I hope frames it better.

**Comment by flannery-denny** [comment]
I will tackle the last bullet about `is-onscreen`. Trusting you can handle the rest of this?

**Comment by schanzer** [comment]
@retabak I've pushed updated to the slides, and also to the starter file links that eliminate need to add wescheme-specific instructions.  Close if you're happy with this last box being checked?

(And don't worry -- I'm on the plane! Not technically in Cancun yet)

**Comment by flannery-denny** [comment]
@retabak I'm still working on the compound inequality lesson and am going to have to sort out the merge conflict. Give me another hour before reviewing that lesson, please.

**Comment by flannery-denny** [comment]
Sorry that took so long @retabak! so many files to crosscheck! I hope that you will find that the lesson is much-improved.
I haven't built slides in a LONG time. 

Three questions:

- [ ] I built the pyret slide deck from the updated `slides.md` file. The size of the slide deck file is WAY SMALLER than any of the other [files in this folder](https://docs.google.com/presentation/d/1htzeVNLynfiUyawZyMVm_wBQZpgs-kObOfWk9tXBX6o/edit?usp=drive_link). I hope that's ok.
- [ ] I didn't update the wescheme file. Not sure how. Luckily it doesn't impact your training tomorrow.
- [ ] @ds26gte Are links to slide decks automagically generated from the slides.md file or is there somewhere else that I need to update the link?

**Comment by retabak** [comment]
@flannery-denny 

The fixes to the inequalities lessons look great. Thank you! I think it's fine to keep the Booleans section. I didn't facilitate that lesson during PD (a facilitator-in-training did) and when she started the Booleans sections, she treated it as though it was new content, which was weird and bad. I think as long as teachers plan ahead and think about what their kids do / do not need, it's fine to put this here.

I'm looking at the pedagogy box about is-onscreen, and it only tackles the issue from a coding perspective, not an algebra perspective. I'm going to add to it a bit. Take a look and let me know if you think it looks alright. (Maybe you also want to weigh in when there's an opportunity, @schanzer ? )

**Comment by flannery-denny** [comment]
@retabak I'm thrilled out how much better these materials look and that your efforts to train teachers are going to result in more lists of fixes to work on!

@schanzer Feeling good about all of this and closing, but please do read the **Why does @show{(code '(onscreen? x y))} take in both x and y?** strategy box and make adjustments if you think they're necessary.
