### ISSUE TITLE
New bug with @teacher

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1526]
Seeing a new version of `@teacher` gunking up the works on `fall2024` in the `bar and pie chart` lesson 

```
@teacher{Confirm that students have correctly matched the displays on @printable-exercise{matching-bar-to-pie.adoc}.}

[lesson-instruction]
- How is `pie-chart` similar to `bar-chart`? How is it different?
- When would you want to use one chart instead of another?
- What information is provided in bar charts that is hidden in pie charts?
```
<img width="859" alt="Screen Shot 2023-09-18 at 12 43 27 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d93681ba-bfd3-4c19-ad62-910fcbf431af">

**Comment by ds26gte** [comment]
This appears to be an unchecked-in document, but in any case, use `[.lesson-instruction]` (with dot) rather than `[lesson-instruction]`.
