### ISSUE TITLE
update contracts throughout lessons and worksheets to match the new format?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1527]
just encountered this (screenshot below) and wondered if maybe we need to do an audit to update contracts throughout lessons and the workbook to be stylized in the fancy new way?

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/a458f950-9097-42c1-a575-9fe4f42b2e2f)

**Comment by flannery-denny** [comment]
@retabak I've already audited the repository for contracts. The only long-hand versions of contracts are on dedicated workbook pages like that in the contracts lesson and we are leaving them for now.
