### ISSUE TITLE
stacked bar chart not behaving as expected

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1528]
I was thinking that the stacked and multi bar charts might tell more interesting stories in the [expanded animals starter file](https://code.pyret.org/editor#share=1zkT8gS3gHMyLdI7VdrruJZvn4SPQmPDc)... and they might, but 
`stacked-bar-chart(more-animals, "species", "sex")`
yields
<img width="598" alt="Screen Shot 2023-09-18 at 10 13 31 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/045bedb9-d20f-450a-80ef-c03823e52ec9">

**Comment by schanzer** [comment]
@flannery-denny how would you prefer that it behave?

**Comment by flannery-denny** [comment]
This is how they behave in the animals starter file and are depicted in the lesson where we teach about them:
<img width="447" alt="Screen Shot 2023-09-18 at 10 47 22 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/9e75d2ab-d6a3-4a91-a1c8-e937b088cbc6">

**Comment by schanzer** [comment]
Percentages should be for 2024. Moved 2023 back to grouping by value
