### ISSUE TITLE
trace(sam) doesn't seem to be working

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1530]
I found this new comment in the starter file

```
# Use the line below to see a table of all the coordinates
# Sam visited while the program was running
# trace(sam)
```

I was thinking I should add some prose about it to the lesson plan, so I tested it out and moved sam all over the place. 

But when I clicked out of the game, the table just had one point.
<img width="192" alt="Screen Shot 2023-09-20 at 9 31 52 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d58fb4d7-cbc5-49df-bb94-373b72a28d0d">

**Comment by schanzer** [comment]
Thanks for reporting - fixed!
