### ISSUE TITLE
prereqs in my local build are appearing out of order

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1531]
Not sure whether this translates to what would get pushed to the web or not, but I am concerned that it's an indicator that prereqs in the build your own pathway would be generated out of order.

Here's what I'm seeing locally

`lessons/Alegbra/inequalities3-sam` has the following prerequisites listed

`@lesson-prereqs{inequalities2-compound}`

and the following is the bottom of the viewable displayed list
<img width="204" alt="Screen Shot 2023-09-20 at 9 59 15 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/7967f523-0755-4e34-974b-ed15d4bac915">

Notice that compound inequalities is listed well ahead of simple inequalities...

**Comment by schanzer** [comment]
@flannery-denny can you copy/paste the exact URL from your address bar, so I can see what you're looking at?

(I know it's not on the web -- just seeing your local path will help)

**Comment by flannery-denny** [comment]
@schanzer They're not out of order in my current build, but this is the file I clicked on to get to that screenshot. Also discussed with Dorai via zoom this morning, fyi.

`file:///Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/inequalities3-sam/index.shtml`

**Comment by ds26gte** [comment]
A force build didn't give me out-of-order lessons.

Deleting the distribution inequalities3-sam and unforced build didn't create problems. 

Making a nominal change to inequalities3-sam/--/index.adoc and unforced build also didn't create problems.

Not saying there isn't a problem. But we need to know exactly what sequence of builds could cause it.

**Comment by retabak** [comment]
okay, I just saw these mixed up prereqs on the web:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/4ace8e54-0152-48a6-82ea-9da66269989f)

I took a screenshot, then remembered that @schanzer would want a hyperlink, so went back to get it... and now, the prereqs look normal!

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/78fe2487-f75c-4430-ab13-11a331634880)

I suppose it's possible I wasn't in the latest version? Sorry if this is unhelful.

I'm also wondering why we aren't just listing out all of the lessons in the sidebar? (That's what we do elsewhere, right?)

**Comment by schanzer** [comment]
@retabak would you mind posting a link to the page in question?

**Comment by retabak** [comment]
yes! sorry!

https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/project-data-exploration/index.shtml

**Comment by schanzer** [comment]
That looks right to me. All of the lessons on the left are the prerequisites for this project, and they are in the proper order.

How do you feel it should look?

**Comment by retabak** [comment]
lol, realizing my error. The lessons are in the wrong order in BOTH screenshots. "Choosing your dataset" belongs AFTER contracts.

ALSO, in every other lesson's sidebar, I am seeing not only prereqs (as I see for the data exploration project), but every single lesson in the pathway. Which way is it supposed to be / why is it not consistent?

**Comment by schanzer** [comment]
@retabak the version on the Web hasn't been updated in weeks. Are the prerequisites in the wrong order when you run this locally?

No, we do not list all of the lessons _anywhere_, unless you are loading a lesson plan that is accessed from a pathway narrative page.

**Comment by retabak** [comment]
Oops, I forgot that thing about accessing lessons from the pathway. Thanks for reminding me.

Here's my local build after `make clean` then `make`:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/3dbff14f-1374-4a57-bf3b-da61ba16366a)

**Comment by schanzer** [comment]
@flannery-denny you're not crazy - there ARE certain corner cases where we weren't computing the prereqs for lessons. And even in those cases, _most of the time_ it wouldn't trigger this bug.

@retabak thanks for the excellent bug report! This is now fixed on `master`.

BOTH OF YOU: **please test first thing tomorrow morning**, so I can deploy to the web soon

**Comment by retabak** [comment]
@schanzer - looks all good to me! (I only checked Project: Dataset Exploration, though, because I don't think the issue was popping up elsewhere?)
