### ISSUE TITLE
Workbook links in materials section should be for both html and pdf

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1536]
@ds26gte this is hopefully easy and quick to do.

Currently, our links to individual workbook pages look like this:
<img width="330" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/e772678a-b55f-447d-b274-4cf356d4d16f">

We want the workbook links at the top of the lesson to look like this:

- Booleans  [[html](url) | [pdf](url)] (page 11)

**Comment by flannery-denny** [comment]
<img width="507" alt="Screen Shot 2023-10-02 at 11 11 16 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ab7cba02-77ba-4518-98c9-16149a9c9454">

@retabak I think this would look much better if the links came after the page numbers. Would you agree?

**Comment by retabak** [comment]
I do agree!!

**Comment by flannery-denny** [comment]
<img width="405" alt="Screen Shot 2023-10-06 at 11 03 54 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d538cb82-997d-4b1f-a8ab-0287768f835d">

@retabak I thought we'd tabled this for our meeting next week, but here's what I mocked up (beginning with what we have as reference). Should we leave it on next week's agenda or just ask the wizard to make it so?

**Comment by retabak** [comment]
Okay, I was going to offer a quick answer to Flannery's question--but then realized I wasn't totally confident answering. As a result, I started doing some research. I learned a lot! At this point, I'm hoping to launch a bigger conversation, which I think merits discussion at our team meeting....

With respect to the PDFs-in-the-lesson-table issue: I learned that we are the only people listing out each and every workbook page in our lesson plans! (okay, maybe not the only people. I only referenced Eureka and IM.) After much thought, I think we should stop doing it entirely!

Here's how Illustrative Math / Open Up approaches this: 
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/6191660f-587e-402d-ac30-8442adb5663c)

Here's what Eureka Math does:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/f0fe1932-4313-4ac6-a907-2df23e738cb9)

My question for you, @flannery-denny and @schanzer : What's the purpose of listing every page in the lesson table? What need is it fulfilling? (I can't think of that need. But I could very well be overlooking something.) I wonder if just putting ONE file of worksheets would alleviate some of the overwhelm many teachers experience in looking at our stuff. The lesson table is for skimming, right? (Of course we could still include individual hyperlinks to specific pages in the lesson and slides at the appropriate places.)

Even if we _don't_ go this route, while poking around IM and Eurkea, I noticed many other things! Perhaps we could draw some inspiration? (I know we're not going to do all these things, and that not all of these things are appropriate for our curriculum... just throwing them out there for further discussion. Disclaimer: This list does NOT take into account the feasibility of these changes or if they are right for us.)

**Summary of noteworthy things from Illustrative Math**
- provide lesson "cool down" (or exit ticket), which lots of schools require of their teachers. (I also know that folks are often uncertain of how to assess Bootstrap. This would be one way we could help with that. I am also aware that lots of IM math teachers use these as homework, or compile them to create quizzes, assessments, etc.)
- offer "community created resources".  (That link goes to a spreadsheet of resources created by teachers.) I don't think we have enough community-created things, however.
- The "lesson synthesis" actually includes a synthesis/summary of all of the key points in the entire lesson. I think teachers would be grateful for this. (When I used IM, I remember scrolling to this section both to understand quickly what a lesson was about, and also after teaching lesson, to ensure that I had covered all of these points.)
- Provide "practice problems" for each lesson. (These are are basically variants of the worksheets to give students an opportunity to practice what they've learned (as homework, as spiraled practice, before a test, whatever). 
** Adding "practice problems" would respond to feedback that a PPSD teacher gave me: "_I am finding I am creating worksheets to check for understanding past what we cover in the 6th grade book. For example, after students completed Translation Table 1 and 2, I made another one for them to complete without my support to check for understanding. They were not ready to try it on their own in the book. Also, realistically I need worksheets for some things to grade at home. I realistically cannot bring 160 workbooks home to grade at night. I am also finding that I am providing resources for students like the vocabulary related to the math operations."_

**Summary of noteworth things from Eureka**
- Those icons look nice (perhaps we could use similar icons for "PDF" and "html")
- A printable "teacher edition" is provided (that's the whole lesson as a PDF, basically.... lots of veteran teacherslike to have their trusty teacher's edition on hand during class.... not my style, but I'm confident many appreciate that security blanket.)
- Exit ticket and assessment material goes to a 39-page PDF that includes (1) Exit ticket packet, (2) assessment packet (which has a mid-module assessment task and an end-of-module assessment task) -- in sum, Eureka explicitly provides teachers things they can use for additional practice / assessment.

Adopting many of these things would require heaps of time and energy, and obviously they would become their own issues.

**Comment by schanzer** [comment]
@retabak I LOVE the idea of collapsing all the pages into a single PDF. The only place this gets us into trouble is "kitchen sink" lessons like Order of Operations, where the 30+ pages span many years' worth of math and teachers need to see what's available (and y'all know I don't like that lesson anyway!). It's trivially easy to add the lesson plan PDF too, to make a "download everything" packet.

We already have "practice exercises" for many lessons, so we can consider this item crossed off already.

Cool Downs / Exit Tickets are a nice idea, but the volume of work is substantial unless we do some kind of lowest-common-denominator that works for most lessons. And that's not generally our style.

Definitely worth discussing - can you add it to the agenda for our meeting today?

**Comment by schanzer** [comment]
@retabak OK to close?
