### ISSUE TITLE
Make a link for each lesson that downloads all PDFs

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1537]
@ds26gte if you can add a link to the bottom of the materials list (even below the optional pages) on each lesson plan, I can easily write the JavaScript code and attach it to your link. (this implements #1533 )

**Comment by ds26gte** [comment]
You just want an empty link `<a href="download_lesson_pdfs">Download lesson PDFs</a>`, where you will programmatically change the `href`?

**Comment by schanzer** [comment]
@ds26gte exactly

**Comment by flannery-denny** [comment]
<img width="328" alt="Screen Shot 2023-10-02 at 11 14 42 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/716e82c1-ee4b-465f-a595-2f2f5c48b4af">

What happened to this link? I was not meant to disappear with the new pdf compilation.

**Comment by schanzer** [comment]
@flannery-denny it's still there. Are you sure you're viewing the lesson after clicking the link from a pathway? If you're just opening the lesson plan itself, there's no pathway and therefore can be no student workbook

**Comment by flannery-denny** [comment]
Thanks @schanzer. Just checked and it looks good. 

Last request... we had requested that the link which currently reads `Download a PDF of all required pages` would actually read `Download a PDF of all pages referenced in this lesson`. Possible?

**Comment by schanzer** [comment]
@flannery-denny not without Dorai making some upgrades to the info stored in the dependency graph. I'll add to the agenda for this afternoon

**Comment by flannery-denny** [comment]
<img width="405" alt="Screen Shot 2023-10-06 at 11 03 54 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/3d4da9bd-ea1d-4108-8572-738cb2ea1ba7">

**Comment by schanzer** [comment]
Which format do you think our teachers use most frequently? The HTML, or the PDF? I feel like whatever they use most frequently should be the big link, with the alternative in brackets.

**Comment by flannery-denny** [comment]
I’m going to bet that @retabak can better answer that question.

But I don’t think [html] is intuitive. I think it would be more common to see something like [web version]. I guess I expect hot links to take me to  another webpage. people are used to seeing [pdf] as a bonus offering.

**Comment by retabak** [comment]
I added some comments that seem related to this question in #1536. 

I think teachers probably want PDFs more than htmls, because they can easily print PDFs. Even though PDFs are kind of a pain.

**Comment by schanzer** [comment]
Closing now that this is being subsumed by #1571
