### ISSUE TITLE
inequalities3-sam should use a separate starter file in Pyret

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1538]
That way WeScheme and Pyret files are both identical, with 1-arity `onscreen?` functions. 

The 2-arity version becomes a separate starter file in Pyret

**Comment by flannery-denny** [comment]
@schanzer realizing that I can't fix the workbook pages without this starter file. Realistic to think you can make it by Dec 1?

**Comment by schanzer** [comment]
@flannery-denny just pushed a draft of the files to fall2024! :)

**Comment by flannery-denny** [comment]
@ds26gte Not sure whether it's my bug or yours, but in the second section of the `Inequalities3-Sam` lesson on `fall2024`  the `@ifproglang` seems to be messing up the build on this strategy box.

```
@strategy{
@span{.title}{Extension Option}
What if we wanted to keep Sam safe on the top and bottom edges of the screen as well?

- What additional functions would we need?  
- What functions would need to change? 

@ifproglang{pyret}{Students ready to tackle this challenge can open @opt-starter-file{inequalities-samXY} where @show{(code '(onscreen2? x y))} is defined to take in both x and y.} 

Note: In the context of Sam the Butterfly, being able to control x and y coordinates is optimal, but, when we add the @show{(code 'onscreen?)} function to our Game Starter File, other (hidden) functions will control the characters' y-coordinates and we don't want to interfere with them, so it'll be important that we use our @show{(code 'onscreen?)} function and that it only changes the x-coordinate. 

@ifproglang{wescheme}{_We recommend that students tackling this challenge define a new function @show{(code 'onscreen2?)} so that their initial @show{(code 'onscreen?)} code remains ready for them to use in the next section of this lesson._
}
}
```

In addition to missing text and the wescheme stuff showing up in pyret, the opt-starter-file isn't getting added to the materials table.

Please fix and push if you can and I will take a look at the commit to learn what was wrong. Thanks!

**Comment by ds26gte** [comment]
Could you send the offending HTMLs or share screenshots?  

It seems to build correctly for me, both the Pyret and WeScheme versions of this lesson. The opt-starter-file shows up only in the Pyret version, as expected. And I don't see Pyret-only text showing up in the WeScheme lesson or vice versa.

**Comment by flannery-denny** [comment]
@schanzer since you only made 1 wescheme link for the 2 versions of these starter files, I've directed the pyret challenge to happen in a new starter file and left the wescheme challenge to happen in the original starter file with a new function name (which is how it was when I was in the classroom). If you'd prefer that I make wescheme have a separate challenge starter file with the new function name, please reopen this issue.

**Comment by schanzer** [comment]
@flannery-denny when we wrote the issue, you wanted a separate starter file for Pyret and not WeScheme. If you feel differently now,  feel free to go ahead and make a 2nd WeScheme starter file.
