### ISSUE TITLE
Defining Values workbook page confusion - on web 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1547]
I noticed that in "Defining Values," writing-code-using-defined-values.adoc is in workbook-pages.text, but not referred to in the lesson. It is *also* listed under "Additional Exercises."

I actually think it's a really good page and that it should be required. And so, I believe that we need to (1) remove it from additional exercises, and (2) integrate it into the first half of the lesson.

@flannery-denny, I think this was your lesson, so maybe you'd like to do this?

Issue #1548 is related.

**Comment by schanzer** [comment]
@retabak confirming that with Flannery's note, you feel like the web version is sufficient?

**Comment by retabak** [comment]
looks good!
