### ISSUE TITLE
defining values rearrangement for 2024

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1548]
When I create the Flags project page, I would like *all* flags materials to live there. That means there would be a Defining Values lesson that has **absolutely *no* flag-related stuff**. This will require some rearranging! See related issue #1547

These pages STAY in the **Defining Values** lesson:
- coe-why-define-values.adoc 
- @starter-file{defining-values}
- defining-values-explore.adoc
- writing-code-using-defined-values.adoc
- notes-defining-values.adoc

These pages go to **Flags project page**:
- chinese-flag.adoc
- which-value-to-define.adoc

Honestly, this makes more sense, I think

@flannery-denny, this might be of interest to you since these are your lessons! Hoping this feels like it makes sense.

**Comment by schanzer** [comment]
@flannery-denny I'm inclined to agree with you  - the Chinese Flag content is a great motivator for why defining values is useful, and I don't think it adds anything to the Flags project that isn't already there.

@retabak can you say more about why it's harmful for anything flags-related to live elsewhere? Is it that you're trying to make a version of that project that can be used by teachers who _skip_ the defining values lesson?

**Comment by retabak** [comment]
@schanzer - help, I'm so confused by your comment!

First, you should know this: the Flags Project does not yet exist. I plan to create it as part of #1248.  I do not want anyone to skip the defining values lesson.  I made a rubric, but there is no project page. Right now, the project and the defining values lesson bleed together. (Do you want me to make a case for making a project page? I thought we were in agreement there, hence #1248.)

Given that a flags project page doesn't already exist, this statement is also confusing: "the Chinese Flag content is a great motivator for why defining values is useful, and I don't think it adds anything to the Flags project that isn't already there."

As for providing a relevant context - is something like [this page](https://bootstrapworld.org/materials/fall2023/en-us/lessons/defining-values/pages/coe-why-define-values.html) not an adequate context? Seems pretty comparable to the "green triangle" context we offer in "functions make life easier", no?

**Comment by flannery-denny** [comment]
Thanks @schanzer. @retabak I can explain. Easier on a zoom call.
