### ISSUE TITLE
in defining values lesson, add some instruction + an optional page on formatting / indenting code

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1549]
I'm thinking we could address the following:

- What are the rules, e.g. when should you hit enter?
- What can we expect Pyret to do when we hit enter in one location versus another? Why?
- How and why is it actually easier to interpret code when we've used proper line breaks?
- How does this connect to circles of evaluation?

From @schanzer : "But ugly code isn’t just about aesthetics: as you saw, it really can be an obstacle to learning. Whenever I teach the flags project, I talk about indentation. It’s pretty much the only way to make a sophisticated flag."

More @schanzer - "I could even see an optional page where students are shown the solutions to various exercises from the lesson, some of which are indented perfectly, and others, which are indented horribly. All they have to do is circle which one is more readable, and write a note about why It belongs in defining values. That’s the first place where students cross over to the definitions area, and where writing longer code becomes possible/ normal."

**Comment by retabak** [comment]
oooh, I had no idea you did this! Excited to take a peek!

**Comment by retabak** [comment]
@schanzer - I am mostly happy with these updates! Left 2 comments / suggestions.

**Comment by schanzer** [comment]
@retabak would love one last look from you -- I moved the chinese flag exercise later in the lesson as well, so can you let me know if it flows better for you?

**Comment by retabak** [comment]
closing! Love it.
