### ISSUE TITLE
@lesson-instruction directive needed

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1550]
Our repo is lousy with the following:
```
[.lesson-instruction]
- a
- b
- c
```

and 

```
[.lesson-instruction]
--
A

- B
- C
--
```

We need all of them converted into:
@lesson-instruction{
....
}.

When processing this directive in slide mode, `@lesson-instruction{XYZ}` should be translated into `XYZ{style="background-color:lightgray"}`

**Comment by ds26gte** [comment]
`@lesson-instruction`  for non-slides is fine, but what does it mean to attach the `{style ...}` to what is presumably the last item in an itemized list (or a block with both paras and itemized lists) when it comes to slides?  I think the `{style ...}` is only good for the last Markdown block it sees. Should we be adding this `{style ...}` to every block-like element inside the `@lesson-instruction`?

**Comment by schanzer** [comment]
@ds26gte ah, good point! yes, we should add this for every block-like element within `@lesson-instruction`

**Comment by schanzer** [comment]
@ds26gte I think there's some preprocessing going wrong when block markers are used. In `contracts-tables-displays`, for example, the very first @lesson-instruction{}:
```@lesson-instruction{
--
- Open the @starter-file{animals} and click "Run".
- In the Interactions Window on the right type `animals-table` and hit "Enter" to see the default view of the table.
- What do you Notice? (sample answers below)
** _We only see the first 10 rows of the table and would have to click to see the remaining 22 rows._
** _The animals aren't listed in any particular order._
- What do you Wonder? (sample answers below)
** _Is it possible to alphabetize the list, or sort it in other ways?_
--
}
```

Turns into this:

![image](https://github.com/bootstrapworld/curriculum/assets/77126/e48b1e4d-7b6c-46a9-98e5-d5cbc244155a)
