### ISSUE TITLE
Proposed Edits and mistakes reported by Nancy Pfenning

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1551]
### Definition Changes
**explanatory variable**
Current definition: _When modeling a possible relationship between an input and an output (e.g. - height and age), we are curious about how a change in the input (typically graphed on the x-axis of a scatter plot) might "explain" the output (y). When the behavior of the output may be explained by the input, we refer to the input as the "explanatory variable"._

Proposed change: _The variable in a relationship that is considered to cause or at least explain changes in the other variable, such as the variable age (graphed on the x-axis of a scatter plot) explaining changes in the variable height (graphed on the y-axis). In some contexts the explanatory variable is referred to as the “independent variable” or the “input.”_

**y-intercept**
Current definition: _the point where a line or curve crosses the y-axis of a graph_ 
Proposed change: _the point where a line or curve crosses the y-axis of a graph (important because we can uniquely define a line by reporting its slope and y-intercept)_

### Mistakes
- [x] Quadratics: [Matching Factored Form](https://docs.google.com/document/d/1ICSoCoV6_kl88Oh8bnyiTA5xGTVGFQHsEvwbpua0tps/edit)
- [x] Quadratics: [Matching Vertex Form](https://docs.google.com/document/d/15xv5xUu9m_XXqEMM2UVT41OsgGj_5q4wdJe1HM9Lkdk/edit)
- [x] Exponentials: [What Kind of Model? (Definitions)](https://docs.google.com/document/d/19L7IeNjKF7vWzgSGndO4kAm8YUDjRGMffrMsocu_cp0/edit?disco=AAAA6qtNOxI)
- [x] Logarithms: [Graphing Logarithmic Models](https://docs.google.com/document/d/1blq6heqIgxIQ8b3xokPkm4etJBbiwVQztj1dddhVW3A/edit)

### Rewrites
- [ ] We need to revise the SImpson's Paradox wording in exponential models ([see comments here](https://docs.google.com/document/d/19L7IeNjKF7vWzgSGndO4kAm8YUDjRGMffrMsocu_cp0/edit)).

**Comment by flannery-denny** [comment]
@schanzer I feel great about this y-intercept definition change and would suggest we make it right away. I do not like the opening of the proposed explanatory variable definition and am curious why it might be viewed as an improvement. Adding to our meeting agenda.
