### ISSUE TITLE
Try to come up with a better page count mechanism for PDFs

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1554]
Might be part of _another_ rewrite of workbook generation code. Some snippets that look promising:
[Snippet 1](https://stackoverflow.com/a/65555135/12026982)
[Snippet 2](https://github.com/Hopding/pdf-lib/issues/252#issuecomment-635383751)
[Snippet 3](https://github.com/Hopding/pdf-lib/issues/464#issuecomment-643834048)

**Comment by flannery-denny** [comment]
@schanzer In case it's helpful, I'm seeing that this page is "fitting" on one page, but really should be giving me a warning because the line falls on top of the page number in the OK workbook.
[prism-explore.pdf](https://github.com/bootstrapworld/curriculum/files/12798717/prism-explore.pdf)

**Comment by schanzer** [comment]
@flannery-denny @retabak I spent the day completely rewriting all of the workbook code. Can y'all let me know if it feels like the page count accuracy is better?

**Comment by flannery-denny** [comment]
Exciting! I’ll definitely keep an eye out, but I think this will be the kind of thing that will take a couple of weeks to give real feedback on.$

**Comment by schanzer** [comment]
With no feedback or red flags in 3 weeks, I'm going to close this. @flannery-denny feel free to re-open if you see books printing incorrectly.
