### ISSUE TITLE
'color' -> 'make-color' in DS library, documented in advanced-displays

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1555]

**Comment by schanzer** [comment]
@flannery-denny would love to get a quick review of the strategy box text before I close this

**Comment by flannery-denny** [comment]
Based on your description of `make-color` I would expect an error message if the input were greater than 250... but...
<img width="551" alt="Screen Shot 2023-10-03 at 4 51 52 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c572f288-1267-4220-8d3d-34fab9915f3d">

**Comment by flannery-denny** [comment]
I'm about to push updated text. It won't address that.

**Comment by schanzer** [comment]
@flannery-denny love it! And it looks like you found a bug in Pyret, too! Talking to Ben about it now...
