### ISSUE TITLE
Add opt-pages and sections to dependency graph

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1556]
Two new fields need to be added to each lesson object:

1. `opt-pages`, which works just like `pages` but include an array of paths for all `@opt-printable{}`s and `@handout{}`s
2. `sections`, which is an array of all 1st level headings (`==`). Duration does not need to be included

**Comment by ds26gte** [comment]
There is already a field in the dependency graph with name `exercisePages` that lists all the opt-printable-exercise files. I just need to add the handouts to this list and rename this field to `optPages`, right? (Also, we're using camelCase rather than kebab-case for the dependency graph fields.)

**Comment by schanzer** [comment]
@ds26gte  ah yes - I forgot we had those too! Amazing. It looks like your commit does exactly that?

**Comment by schanzer** [comment]
confirmed!
