### ISSUE TITLE
Fix matching cards from order of operations lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1558]
`order-of-operations/matching-coe-exp.adoc`

In the second column, the math is left-oriented instead of centered making it hard to read.

The [web version](https://bootstrapworld.org/materials/fall2023/en-us/lessons/order-of-operations/pages/matching-coe-exp.html) and [matching-coe-exp.pdf](https://github.com/bootstrapworld/curriculum/files/12795979/matching-coe-exp.pdf) are wonky for different reasons.

**Comment by flannery-denny** [comment]
This looks better on the web, but not in the workbook.

**Comment by schanzer** [comment]
@flannery-denny try now? Close if you're happy
