### ISSUE TITLE
draft text for pedagogy box in lesson plan re: "pacing", "sync with me"

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1562]
Here are two specific places that we need words rather than just links. 

@flannery-denny - I tried drafting a text for the preparation section but it got too long and ended up including images. Can you think of anyway that we can make this more concise? You are a whiz at the sort of thing (clear directions). Help!

- [ ] Text for preparation section of lessons that says something like

> - This lesson integrates an interactive Desmos activity. 
> - If you're a first-time Desmos user, fear not! Here's what you need to do: (1) Open the [activity](https://teacher.desmos.com/activitybuilder/custom/65035a85708fbb40f916c2d6). (2) Click on the triangle next to "Assign." (3) From the drop down menu that appears, select "Single Session Code." 
><img width="147" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/87144723/8f630715-611b-4441-b5c7-6a03d5abb00f">

> - A pop-up message will appear. Select "Create an Invite Code."
> - You will see a unique session code appear on the "Activity Page." A link to the session's dashboard also becomes available. Click it.
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/d69d0803-647c-464a-a2ea-77ffec787bbe)

> - When you click "Dashboard," you will see a "Hey, Students!" message. Project the message and instruct students to follow the directions. Alternatively, copy the invitation link and share it with your students.
> - For more guidance on teaching with Desmos, refer to these guides: [Getting Started](https://my.amplify.com/help/en/articles/6684337-getting-started-desmos-classroom-activities)
[Using the Teacher Dashboard](https://my.amplify.com/help/en/articles/6684323-using-the-teacher-dashboard) and [Classroom Conversations](https://my.amplify.com/help/en/articles/6763511-classroom-conversations).

- [ ] Two or three sentences for the activity description on desmos that directs teachers about what settings they should have pacing and sync with me set to in preparation for the start of the activity. This is different if it's for the alg2 lessons where we only want students to access one page of the activity at a time, than it is for something that's self-paced. Please provide text for each.

@flannery-denny - we don't have anything that is necessarily self-paced, do we? I believe that we will need to write unique instructions to match each individual activity. I'm thinking something like this: "You will likely want to give access to the slide deck bit by bit. We recommend allowing students to access slides 1-5; then slide 6; and finally slides 7-9." Or something like that. (Whenever I did a desmos activity with my kids, I'd put a post-it note on my monitor to remind myself which slides were the pause points.)

**Comment by flannery-denny** [comment]
@retabak Please update the text in the issue description as you see fit and lmk when you're done. Thanks!

**Comment by retabak** [comment]
@flannery-denny - just realizing maybe I never alerted you that I worked on this!

**Comment by flannery-denny** [comment]
Thanks @retabak!

**Comment by schanzer** [comment]
@flannery-denny I _think_ Rache's component is finished here, so I'm going to switch the owner over to you. Please let me know if this is a mistake!
