### ISSUE TITLE
reconsider vocab list for contracts lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1563]
Do we feel comfortable removing **error message** and **name** from the glossary? @schanzer @retabak 
They feel self-explanatory to me.

<img width="862" alt="Screen Shot 2023-10-09 at 11 56 09 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/cdbddaf3-e1e1-4ad4-a10a-57044dd4d04a">

**Comment by retabak** [comment]
I definitely vote that we remove "error message"

I'm neutral about "name" - feels *slightly* less self-explanatory to me.

**Comment by schanzer** [comment]
@flannery-denny agreed on "error message". I've pushed a change that removes it from all materials, but preserves the definition in case we need it later. Happy to delete the definition, too.

Re: "name" -- I think this is deeply connected to #1565 . Names _are_ identifiers. Let's discuss.
