### ISSUE TITLE
crazy idea - define fill using true or false instead of "solid" and "outline"

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1564]
true for solid
false for outline

We only have two fill styles. It seems unlikely we'll use more in Image-producing functions

pro: another use case for Booleans, reinforces fill as true, just as with circles used in graphing inequalities on a numberline
con: all of us who have spent hours practicing triangle 20 "solid" "green"

**Comment by schanzer** [comment]
Other con: we break every single contract found in the pyret documentation, and in wescheme. 

Given the enormity of the potential breakage, I believe we should only consider this if the status quo is a serious problem for teachers and students. Does this rise to that level?

(@flannery-denny I'm _really_ glad you're challenging some of our long-held assumptions here. I just happen to feel rather strongly about this one)
