### ISSUE TITLE
Use CSS to turn off header and footer in printed page

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1568]
Use trick from https://stackoverflow.com/questions/1960939/disabling-browser-print-options-headers-footers-margins-from-page

**Comment by schanzer** [comment]
@retabak you seem to be able to reproduce this most reliably. Can you do a fresh pull on `master` and try printing a page? 

(Haven't addressed the "shrunken page" issue yet -- this is just about hiding the links at the top)

**Comment by retabak** [comment]
SUCCESS!!! 

sorry I didn't elaborate earlier on as to why I disliked printing htmls. I feel dumb that we didn't fix this sooner, because it's bothered me for a minute!
