### ISSUE TITLE
Revise Materials links

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1571]
We've decided the lesson table will be as follows

### Materials
- [ ] **Handouts** @ifpathway{**and Pages 11-17** from **the 2023 Student Workbook**} 
(_Note: we need to add Handouts to this pdf!_) 
- [ ] **Starter FileA**
- [ ] **Starter FileB** 
_(Required Desmos activities would appear as Starter Files)_
- [ ] **Slides**
- [ ] **Printable Lesson Plan** (a PDF version of this webpage)

### Supplemental Materials
- [ ] **Optional Project**
- [ ] **Additional Printable Pages for Scaffolding and Practice**
- [ ] **Starter FileA**
- [ ] **Starter FileB** 
_(Optional Desmos activities would appear as Starter Files)_
- [ ] **Online Exercise**
- [ ] Classroom Visual: **Language Table** 

_Sometimes these sections will also appear_

**Comment by schanzer** [comment]
@flannery-denny and @retabak I believe this is implemented successfully. Reminder than PDF downloads won't actually work when running locally, so the feedback I need is about the appearance.

**Comment by retabak** [comment]
In many lessons, there are no optional pages, so it feels odd to see "Required" as a descriptor. Screenshot below is from Data Cycle.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/960d0781-2f99-40c9-a735-55496530b305)

I'm also not sure "pages" works here, as it doesn't carry much meaning to teachers, especially those without workbooks. I'm wondering if "Student Classwork" and "Optional Student Worksheets" would be more descriptive? Wondering what @flannery-denny would prefer. 

I would also opt to put Lesson Plan last, given that we think that is a resource for folks who want to print up the entire lesson. (I don't think that's a large percentage of our teachers.)

and finally, the lesson plan PDF looks wonky. (I did `make book` so I could see it.) Attaching it here, in case you aren't aware that the right side of the text gets chopped off. (Or maybe you are aware, but only wanted feedback on the appearance of the lesson table.)

[index.pdf](https://github.com/bootstrapworld/curriculum/files/12870832/index.pdf)

**Comment by schanzer** [comment]
@retabak ooh, thanks for the bug report about the lesson plan! I've fixed the width issue, but noticed another problematic bug. Adding to our agenda

**Comment by schanzer** [comment]
I'll wait for @flannery-denny to weigh in on the wording -- it's easy to change once I know exactly how it should read.

**Comment by flannery-denny** [comment]
When I view the materials section from within a pathway, this is what it looks like:
<img width="355" alt="Screen Shot 2023-10-11 at 11 02 54 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/a326dc90-13d4-48f2-a779-f6c88895d6ef">

I think we have a ways to go with how it should best be organized. I'll work on a mockup. 

Including the screenshot below to celebrate improvement :) and to help with further thinking

<img width="1314" alt="Screen Shot 2023-10-11 at 11 10 13 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d2cdfa0e-97d5-46ac-ab5f-88c65f982c22">

**Comment by flannery-denny** [comment]
@schanzer @retabak I propose the following organization of the materials section with bold representing hyperlinks.

<img width="571" alt="Screen Shot 2023-10-11 at 11 47 49 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/041ee787-c5a3-4e01-b957-781ea987c39d">

I made it into a checklist in the issue description so that you can drag the pieces around if you want to consider how they might read in another order.

For posterity, the original issue just said
- lesson plan
- required workbook pages
- optional pages

**Comment by flannery-denny** [comment]
@schanzer noticing that currently when I make the @online-exercises aren't getting listed at all.

I moved the NinjaCat Desmos activity to the starterfiles file, but I don't think the google draw template really belongs there. One is getting added and the other is missing. 

<img width="451" alt="Screen Shot 2023-10-11 at 1 18 34 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/36ea023e-dbe6-47d8-b3ad-f6fcfa70f5ea">

**Comment by schanzer** [comment]
@ds26gte see Flannery's comment, above: @online-exercises aren't showing up in the materials list. See the issue content for where they should appear

**Comment by ds26gte** [comment]
@schanzer, in bootstraplesson.js you're explicitly removing the last item in the material-links, assuming it to be a langTable link. Around line 320. 

This is not the langTable link anymore. In this case, it happens to be an online-exercise link, and it gets deleted.

**Comment by schanzer** [comment]
@ds26gte even in lessons with multiple online-exercises (`function-definition-linear`), we aren't seeing any online exercises. Even if my JS is deleting the last link, we should see at least see _some_ online exercises.

**Comment by flannery-denny** [comment]
@schanzer I see how it might have confused you, but this text refers to the @opt-printable pages.
<img width="608" alt="Screen Shot 2023-10-12 at 1 07 26 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c47e6ab7-2e2f-4a3f-a419-08385d19ce34">

**Comment by flannery-denny** [comment]
@retabak I don't think that slides or the printed lesson plan are required to teach our lessons.

Confirming you really think bolded titles would look good in context...
<img width="743" alt="Screen Shot 2023-10-12 at 1 53 29 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0f6986ed-01f2-41f4-a9a3-7ed415a15bae">

**Comment by retabak** [comment]
I definitely think it's a great idea to skip the "Required" heading and only include optional.

Now that you mention it, I'm not 100% sure bolded titles would look good in context. Given my dislike of seeing all those "Optionals", I thought of another idea: maybe it would make more sense to just add an additional row to the lesson table? (One row is "Materials," the other is "Optional Materials"?) 

I think we're getting closer???

and: sorry I'm complicating things!  If others aren't bothered by all those "Optionals",  then I can live with them! I want a beautiful streamlined table without clutter!

**Comment by schanzer** [comment]
@flannery-denny and @retabak Can the two of you find time to hop on and zoom and talk this out before next week? The back and forth comments are making me dizzy. :)

**Comment by flannery-denny** [comment]
@schanzer we only want links to pdfs of workbook pages in the lesson table and we are leaning toward all inline links to pages in lesson plans opening pdfs, unless you know them to be slower to open on old machines with weaker internet connections. (We wouldn't want them to function like the pioneer poster set, for example).

We've decided the lesson table will be as follows

### Lesson Goals
### Student-Facing Lesson Goals
### Materials
- [ ] **Handouts** @ifpathway{**and Pages 11-17** from **the 2023 Student Workbook**} 
(_Note: we need to add Handouts to this pdf!_) 
- [ ] **Starter FileA**
- [ ] **Starter FileB** 
_(Required Desmos activities would appear as Starter Files)_
- [ ] **Slides**
- [ ] **Printable Lesson Plan** (a PDF version of this webpage)

### Supplemental Materials
- [ ] **Optional Project**
- [ ] **Additional Printable Pages for Scaffolding and Practice**
- [ ] **Starter FileA**
- [ ] **Starter FileB** 
_(Optional Desmos activities would appear as Starter Files)_
- [ ] **Online Exercise**
- [ ] Classroom Visual: **Language Table** 

_Sometimes these sections will also appear_
### Preparation
### Key Points for the Facilitator

We want to pay attention to what we're sharing by way of **Supplemental Resources** and wonder whether some of these could be added to Supplemental Materials by hand, become references in preparation, inline or in pedagogy boxes that don't end up in the materials section, or whether we'll end up needing something called **Relevant Resources**

**Comment by schanzer** [comment]
@ifpathway doesn't work for stuff like this, so I'm going to skip that part. Let's also skip the classroom visual part, since that's likely to be removed anyway. A few questions:

- Why are required online-exercises showing up as "Supplemental"? I would think that all required materials should be in the "Materials" section
- Why do the required starter files A and B show up in both "Materials" and "Supplemental"? Shouldn't they only show up in one?

**Comment by flannery-denny** [comment]
@schanzer we agreed last week that if online exercises were required they should be listed in ‘starter-files.rkt’

**Comment by flannery-denny** [comment]
@schanzer Re: starter filesI wroteStarterfileAStarterfileB To clarify that each starterfile referenced in the lesson should be included on its own line in the materials sectionThe supplemental section will include each opt starterfileAlso want to note that we are currently able to unautomate the generation of a materials list (as we do in piecewise functions) by deleting @materials from the materials table. this should be preserved for both of the materials and supplemental materials section.FlanneryOn Oct 15, 2023, at 8:33 AM, Emmanuel Schanzer ***@***.***> wrote:﻿
@ifpathway doesn't work for stuff like this, so I'm going to skip that part. Let's also skip the classroom visual part, since that's likely to be removed anyway. A few questions:

Why are required online-exercises showing up as "Supplemental"? I would think that all required materials should be in the "Materials" section
Why do the required starter files A and B show up in both "Materials" and "Supplemental"? Shouldn't they only show up in one?

**Comment by schanzer** [comment]
@flannery-denny  ah, good point! Thanks, that clarifies the speck.

**Comment by schanzer** [comment]
With all the remaining work described in #1580 - and lessons building with pages that look like the sample in the spec - this is ready to close.
