### ISSUE TITLE
Broken link on web to optional cutouts of Dog, Cat and Ruby in Coordinates lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1572]
Here's the broken link [https://bootstrapworld.org/materials/fall2023/en-us/lessons/coordinates/images/cat.png](https://bootstrapworld.org/materials/fall2023/en-us/lessons/coordinates/images/cat.png)

and where it comes from in the materials section [https://bootstrapworld.org/materials/fall2023/en-us/lessons/coordinates/index.shtml?pathway=algebra-pyret](https://bootstrapworld.org/materials/fall2023/en-us/lessons/coordinates/index.shtml?pathway=algebra-pyret)

If we are going to continue to link to these images, I think this is a use-case for the `@handout` directive

**Comment by flannery-denny** [comment]
@schanzer this is ready to push to the web.

**Comment by schanzer** [comment]
@flannery-denny pushed!
