### ISSUE TITLE
live on the web - navigation bar is missing!

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1576]
https://bootstrapworld.org/materials/fall2023/en-us/lessons/coordinates/index.shtml?pathway=algebra-pyret

<img width="1073" alt="Screen Shot 2023-10-12 at 11 08 10 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0b87b8e4-1d03-484c-9f86-aef23d530b9f">

**Comment by schanzer** [comment]
@flannery-denny here's what that link loads for me:
![image](https://github.com/bootstrapworld/curriculum/assets/77126/9b471424-25f9-448c-a918-00f477843c13)

**Comment by flannery-denny** [comment]
@schanzer works for me now, too. no idea what I did before. sorry.
