### ISSUE TITLE
The order or operations lesson live on the web teaches circles of evaluation using wescheme verbage

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1577]
I am fixing the order of operations lesson on fall2024 and noticing that the rules for circles of evaluation are being introduced in a way that isn't pyret friendly... I feel confident this has been flagged in the past, resolved, and lost again somewhere along the way. It could explain some of the questions that have come in on discourse recently.

**Comment by schanzer** [comment]
@flannery-denny where do you see this on the web? Can you share a screenshot to language that seems WeScheme-specific?

**Comment by flannery-denny** [comment]
@schanzer
<img width="767" alt="Screen Shot 2023-10-12 at 2 40 49 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/bdd93215-046e-46ab-b118-fb54eb779f8d">

**Comment by retabak** [comment]
I know I'm not tagged on this issue, but I am genuinely curious how this is wescheme specific language? I feel like there's something I'm missing. @flannery-denny - can you explain?

**Comment by schanzer** [comment]
@flannery-denny is it that the text refers to division as a _function_? I've pushed an update to address this, so close if this resolves the issue. Otherwise, you may need to explain what the wescheme-specific stuff is.

**Comment by flannery-denny** [comment]
@schanzer Sorry for the wild goose chase. The bold rules themselves also use the word function, but operators are not functions in pyret. If that didn't jump out at you, I'd say it can wait another week for me to finish wordsmithing the lesson on fall2024 and port it over.
