### ISSUE TITLE
Consider what we want to surface with "Classroom Visual"

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1578]
- [ ] perhaps some lessons have more interesting **Classroom Visuals** to share?
- Computing Needs All Voices has the Pioneer Poster Set
- Joy used to have a poster of the Data Cycle
- Mariana has a poster of the Design Recipe
- Threats to Validity links to a poster set of Data Fallacies
- Are there others?

**Comment by schanzer** [comment]
@flannery-denny since we're planning to get rid of "classroom visual" entirely in #1584, is this still something you want to keep open?

**Comment by flannery-denny** [comment]
@schanzer is there a way to link directly to the pioneer poster set or is this link the best we can do? `@lesson-link{computing-needs-all-voices/pages/computing-pioneers.adoc}`

**Comment by schanzer** [comment]
@flannery-denny the PDF is just another file in the pages directory, so `@lesson-link` or `@handout` should work fine. Since it's optional and not really a printable exercise, I think @handout{pages/computing-pioneers.pdf} is the way to go. But if you don't want it included in the "download optional PDFs" link, then yeah I think you can safely fall back on `@lesson-link`

**Comment by flannery-denny** [comment]
@schanzer please do a fresh build of fall2024 and see what happens when the link you propose gets deployed. If it's possible to make it work, please fix it! If not, please remove it. Thanks!

**Comment by schanzer** [comment]
@flannery-denny What did you want the link to look like?

**Comment by flannery-denny** [comment]
@schanzer I want it to open a PDF of all the posters.

**Comment by schanzer** [comment]
@flannery-denny I'm not seeing that PDF anywhere. Are you sure we even _have_ a poster set file?

**Comment by flannery-denny** [comment]
@schanzer We don't. That's why I wrote to ask you if there was a better link than linking to the computing pioneers page, which has a button that compiles a pdf. I don't understand how the button works or why it would possibly be preferable than having a stable pdf of the current set of pioneers posters.

Here's the code that makes it happen. 

```
<span id="OnscreenInstructions">
Click on any thumbnail below to read about the contributions of the pioneer and download a full-page, printable version of the poster. You can download all of the pages as a single PDF by <a href="javascript:printPioneers()">clicking here</a>. We will be expanding this collection over time and are open to <a href="https://docs.google.com/forms/d/e/1FAIpQLSesCHpWZFuD4HE-im9qwjQZpw6pG2ESS5s-DfxfhACV-wQo0Q/viewform?usp=sf_link"> suggestions</a>!
</span>
```

**Comment by schanzer** [comment]
@flannery-denny sorry about that - when you asked for a way to link I didn't realize you were asking to link to a dynamically-created page. That took a much longer time to implement, but I've just pushed a commit that does exactly what you want

**Comment by flannery-denny** [comment]
Thanks @schanzer. I haven't yet figured out how to get the link to read inline. Just pushed a commit. Any ideas how to improve on it?

**Comment by schanzer** [comment]
@flannery-denny looks great to me! Anything else you want done before the issue is closed?

**Comment by flannery-denny** [comment]
In both places where we're linking to the poster set, I'd like the link to be on the same line rather than a new line. Ideas on how to make that happen?
<img width="861" alt="Screen Shot 2023-10-30 at 11 18 24 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d15bf9f4-e4dd-4070-b51a-de812df39eaf">

**Comment by flannery-denny** [comment]
@schanzer Please see the comment above. Also wondering where Mariana and Joy got the giant posters they use in their classrooms. Is there a link we could be sharing? Should I tag Joy in a comment in this issue?

**Comment by schanzer** [comment]
@flannery-denny no ideas. I think tagging Joy and writing to both her and Mariana would be a great idea.

**Comment by flannery-denny** [comment]
@ds26gte Any idea how to get these links to appear on the same line rather than a separate line?
`fall2024/computing-needs-all-voices/index
`lines 39-59

```
* *Classroom Visual*: 
+
++++
<a href="javascript:printPioneers()">Downloadable Poster Set</a> of all Computing Pioneers
<div id="msg">
	<p id="text"></p>
	<span id="statusbar"></span>
</div>
++++

| Preparation
|
* Figure out what structure you will use to engage students with  @printable-exercise{pages/computing-pioneers.adoc, these pioneers}. If a gallery walk works for your students, print a set of 
+
++++
<a href="javascript:printPioneers()">Pioneers in Computing and Mathematics Posters.</a> 
<div id="msg">
	<p id="text"></p>
	<span id="statusbar"></span>
</div>
++++
```
<img width="861" alt="Screen Shot 2023-10-30 at 11 18 24 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d15bf9f4-e4dd-4070-b51a-de812df39eaf">

**Comment by flannery-denny** [comment]
@ds26gte @schanzer I've also tried this version of the code
```
| Classroom Visual
| 
* 
++++
<a href="javascript:printPioneers()">Downloadable Poster Set of Computing Pioneers</a> 
<div id="msg">
	<p id="text"></p>
	<span id="statusbar"></span>
</div>
++++
```
Which I think would be preferable, but generates something even uglier if we can't get the java script to happen inline
<img width="570" alt="Screen Shot 2023-10-30 at 2 48 08 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d58d9ab7-c443-45ad-ac4f-202c025794c0">

**Comment by flannery-denny** [comment]
```
| Classroom Visual
| 
++++
* <a href="javascript:printPioneers()">Downloadable Poster Set of Computing Pioneers</a> 
<div id="msg">
	<p id="text"></p>
	<span id="statusbar"></span>
</div>
++++
```

<img width="570" alt="Screen Shot 2023-10-30 at 2 48 08 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/3f246ede-e107-412a-aecd-3f3af4d1a6a9">

lmk if this is impossible and I'll rewrite the lesson plan as if that's the case

**Comment by ds26gte** [comment]
`*` on a line by itself becomes verbatim star, not an item marker.  Also, not sure what the intent with the verbatim HTML is, but I see `<div>` and `<p>` -- both are block-izers, so will generate newlines.
