### ISSUE TITLE
Repurpose @ifpathway

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1582]
- [x] @ds26gte will change the behavior so that it merely wraps its contents in a span whose class is `pathway-<pathway name>`
- [x] @ds26gte will make a directive @ifnotpathway that wraps contents in a span like `notpathway-<pathway>`
- [x] @schanzer will write some JS code to show/hide based on class name
- [x] @flannery-denny will remove all current uses in the repo - there are only two and we decided to leave them because the infrastructure update will magically fix them :)

The following use-cases are needed:

- In the materials section, we should generate prose about pages and workbooks that is specific to the pathway, if it exists
- Some lessons contain content that should only be visible if accessed from within pathway A, B, etc. If no pathway is defined, the content should be invisible
- Sometimes we want prose that is only accessible from within ANY pathway. For this, we already have the `@pathwayonly` directive

**Comment by flannery-denny** [comment]
@schanzer I found the directive that works the way I kept trying to use `@ifpathway`. It's called `@pathway-only`

**Comment by schanzer** [comment]
@flannery-denny these directives should now work the way you want them to! See Dorai's examples in `zample-lesson.adoc`
