### ISSUE TITLE
Add @lang-table{....} directive

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1584]
We currently generate the following HTML as part of the @materials-list:
```
<a href="javascript:showLangTable()">Language Table</a>
```

- [x] We want to _remove_ this from the @materials-list
- [x] We want to add a _new directive_, `@language-table{XYZ}`, which generates the same link using `XYZ` as the link text
- [ ] We need to use this directive in a number of lessons -- anywhere teachers should explicitly care about the table!
- [ ] check that contract is given in student-friendly way in every lesson where a new function is introduced

**Comment by schanzer** [comment]
@retabak Dorai has completed the infrastructure part of this. Putting the execution of your vision here on our December 1 milestone.

**Comment by retabak** [comment]
Hi, @ds26gte ! 

At the moment, when I type `@lang-table{XYZ}` into a lesson plan's asciidoc, I see this:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/5d67b1ca-5aa2-4ddf-b1ba-0e1b75d0852b)

When I click on the link ("XYZ"), I do not see a language table. (Am I missing something? Or is it supposed to do nothing?)

I see now that the specs were not especially clear, so I will try again!

- The directive `@language-table{XYZ}` should produce a link that just says "Language Table" (e.g., no bullet, and no "Classroom Visual:"
- After clicking on "Language Table", a visual of the language table should appear

I'm also curious to know if something ELSE is possible re: this directive. As you know, different words are added to the language table during individual lessons. I was wondering if it would be possible to have the *new* words only to appear italicized and bold? (I think this is a significant change from the past behavior of the language table, where new words from one lesson were only added to the table during the _subsequent_ lesson? I may be getting this wrong. Hoping @schanzer can correct me if I am.)

**Comment by retabak** [comment]
@schanzer - I wrote up a proposal for how I want to integrate @language-table. 

Here it is!
https://docs.google.com/document/d/1nOLahJvkWBipLaClOvr5wHjHynhty1jSOfDIVlfNDFk/edit

I think it's a big improvement. LMK what you think.

**Comment by schanzer** [comment]
@retabak if only I could see it!

**Comment by retabak** [comment]
Oops, didn't realize I made this in my personal Gmail. Sorry!

**Comment by schanzer** [comment]
@retabak added some comments. I can make language table display the current lesson's additions in bold or whatever, but not until you finish adding the explanation someplace appropriate.
