### ISSUE TITLE
wording/formatting adjustment on lesson table of lessons accessed via pathways

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1589]
This is what shows up now:

<img width="589" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/87144723/d180e47c-f5e4-4b56-9631-fe6627edb280">

Here's what I would like to show up:

**PDF of all Handouts** (pages 17-20 of the **Student Workbook**)

I've bolded what I would like to be hyperlinked. Right now, it looks like the PDF includes the handouts _and_ p17-20, which is wrong and confusing.

I would also vote that we delete "(a PDF of this webpage)" after printable lesson plan. I think it's redundant.

**Comment by flannery-denny** [comment]
I'm ok with the proposal... but, to clarify, the PDF of all Handouts includes both handouts and student workboook pages.

Also, I'm noticing that for lessons with optional starter files and other online exercises, they are being italicized in the list.
<img width="868" alt="Screen Shot 2023-10-18 at 3 26 34 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/493150d5-fd45-40de-83b6-40c9f3a46274">

**Comment by retabak** [comment]
oooh, I thought we said "PDF All Handouts" in the non-pathway lessons. Didn't realize pages was in there anyhow. OK, so, I have a new proposal!

**All Student-Facing Material** (pages 17-20 from the **Student Workbook**)

I don't think most teachers know that there's a difference between a "handout" and a "page".  What you think, @flannery-denny? 

And, I definitely agree with getting rid of italicization (except for _Optional:_)

**Comment by schanzer** [comment]
I'm going to ignore this until you both tell me that you have arrived at a FINAL proposal. ;)

We really have WAY too many important things to do than spend all this time wordsmithing links that be changed at literally any time in the next year.

**Comment by flannery-denny** [comment]
closing because this will be subsumed by #1620
