### ISSUE TITLE
research project slide deck improvements

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1590]
these come from @flannery-denny in her comments on the research project slide deck!

- flesh out threats to validity section of the paper for 2024, perhaps including some of the questions from the ADSA lenses (see #1382)
- As a long term goal, we could consider adding another slide to this section [why is the topic interesting to you / your community?] about how their positionality with regard to the topic might influence their engagement with the data, per ADSA lenses.
- A question I have is whether there is some way to connect this section to the structure of a five paragraph essay: Thesis, 3 Topic Sentences, Each with supporting evidence, and a Conclusion. I'm not suggesting that it's an essay, and I haven't thought through how it would relate to this deck, so we can save it for another day if it feels like a stretch at the moment, but the way my students structured their projects for our social justice data fair in trifold form had a big title and 3 subtitles each with supporting displays and discussion. For a number of them working within that structure transferred back to improvement in both their writing and thinking about how to tell a story / make a case for something

**Comment by flannery-denny** [comment]
subsumed by work on #1616
