### ISSUE TITLE
when no supplemental materials are present in a lesson, do not include the supplemental materials section of the lesson table 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1592]
Here's what I'm seeing in the Computing Needs All Voices Lesson
<img width="880" alt="Screen Shot 2023-10-18 at 11 51 15 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/28c615bc-ae45-4f82-add3-ece28eba22bd">

**Comment by schanzer** [comment]
@flannery-denny I don't think there's anything Dorai can do here. Like the materials section, it's up to authors to decide when one is needed. 

If @ds26gte went ahead and implemented this somehow, then a lesson with no auto-generated supplemental lessons would have no row for authors to manually add content to. I think this is in our wheelhouse to address.

**Proposal:** keep the current behavior unchanged, but have the build script generate a _warning_, so the authors can go in and manually remove the row if it's blank. What do you think?

**Comment by flannery-denny** [comment]
I would think that he'd be able to detect that we'd added something in the table row. True @ds26gte?

eg. 
This row only includes `@opt-material-links` and there aren't any so it would be deleted (@ds26gte is currently revealing the text "This lesson has no supplemental materials (yet!)"

```
| Supplemental Materials
|[.material-links]
@opt-material-links
```

But this row doesn't include any automatically generated materials but there are some that were manually added so it stays.

```
| Supplemental Materials
|[.material-links]
@opt-material-links
* @link{https://www.google.com/search?q=random+number, Random Integer Generator}
```

**Comment by schanzer** [comment]
@ds26gte  doesn't add the row at all, so there's no way for him to "not add" it. This is a pretty significant ask, and it opens many cans of worms. For example, why do this for opt-materials but not for materials? 

Dorai - auto-detecting empty table rows in asciidoc is nontrivial and (likely) error-prone, no?

**Comment by ds26gte** [comment]
If the author took the trouble to write `| ...`, they're expecting a row, innit?

However postprocessing is a possible route. It may be possible to add some JS that looks for rows with no innards (or with some well-defined innards, like `DELETE ME`) and removes them from the DOM. It is unfortunately not possible with pure CSS, because CSS won't let you select a parent in order to make it invisible.

**Comment by flannery-denny** [comment]
Thanks for your patience, all. Based on what I've just learned from you,

- If @ds26gte is only showing this text "This lesson has no supplemental materials (yet!)" when authors haven't added something to the row, a warning in the build would be helpful.
- Otherwise, let's not waste any time on adding more detection to be able to throw a useful warning and authors can remove the row of the table by hand before pushing lessons to the web.
- Either way, let's stop showing the message in the table row.

**Comment by schanzer** [comment]
@flannery-denny close if you're satisfied with Dorai's latest push?
