### ISSUE TITLE
using shift click on a section header should not open a new window 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1593]
It is very helpful when searching a lesson plan to have all of the sections open with a single shift click. Thank you! For some reason that functionality is working correctly. And then, additionally, the lesson plan with all sections closed is being opened in a new window.

**Comment by schanzer** [comment]
@flannery-denny I'm not able to replicate this in Brave. What browser are you using? And where _exactly_ are you clicking?

**Comment by schanzer** [comment]
For historical purposes: 
- Shift-clicking on links is _supposed_ to open them in a new window or tab, so this behavior is correct
- Shift-clicking on banners is supposed to collapse/expand all sections
- The confusion comes from the fact that the link is also part of the banner, so clicking the link does **both**.

I've pushed a commit that eliminates the confusion.
