### ISSUE TITLE
Live on the web - wescheme version of simple inequalities starter file doesn't work

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1597]
Need to switch `range1` to `testA`

**Comment by flannery-denny** [comment]
@schanzer please test the link and click "Run" to confirm it works. I'm pretty sure it's ready to deploy to the web, but couldn't remember how to build wescheme versions of things.

**Comment by flannery-denny** [comment]
@schanzer I can confirm that the link works and can be pushed to the web

**Comment by schanzer** [comment]
@flannery-denny pushed!
