### ISSUE TITLE
bug in coe build

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1601]
On `fall2024` in the `order-of-operations` lesson plan, I am trying to build some circles of evaluation with empty components using `?ANS` (see `line112` and `line113`), but the circles aren't building. Here's the racket code:

`(coe '(- 10 (?ANS ?ANS ?ANS)))`

I want it to generate an outer circle with the `-` and `10` visible, as well as an inner-circle with an empty function and empty arguments. Here's what I get instead:

<img width="326" alt="Screen Shot 2023-10-24 at 1 21 19 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/62deac04-787f-4a29-b46f-83c5969e6dfa">

Would love your help!

In case it's useful, I found this css in the `complete-coe-from-arith.adoc` , but it didn't solve the problem

```
++++
<style>
  div.circleevalsexp .value,
  div.circleevalsexp .studentBlockAnswerFilled { min-width:unset; }
</style>
++++
```

even though the circles on that page with missing components are building correctly.

<img width="211" alt="Screen Shot 2023-10-24 at 1 29 01 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ef55c566-49c7-486b-a24e-d4bd95b51a9e">

**Comment by ds26gte** [comment]
`?ANS` is used like a "function call", i.e., `(?ANS 9)`. This renders as blank in student-mode and 9 in solution-mode.

So you want to use something like `(?ANS _)`.  Since this is in a lesson plan, there is no solution mode, so it will show up with a blank in place of the `(?ANS _)` as you wanted. (If there was a solution-mode, it would show up as `_`.)

I take it you don't want this functionality in a workbook page, i.e., with the blank showing up in both the student- and solution-mode?  If so, we may need to come up with a `?BLANK` that shows up as a genuine empty space.

**Comment by schanzer** [comment]
@ds26gte I think it's more basic than that, and I don't think there's any difference between wbpages and lesson plans. I think Flannery's wbpage reference may have thrown you off. :)

The fundamental question is "what should `(?ANS ?ANS ?ANS)` produce?" Right now it produces a single blank. Flannery and I would expect it to generate an empty circle.

**Comment by ds26gte** [comment]
To address the specific examples:
```
- outside in: @show{(coe '(- 10 (?ANS ?ANS ?ANS)))}
- or inside out: @show{(coe '(?ANS ?ANS (+ 5 3)))}
```
should be rewritten as
```
- outside in: @show{(coe '(- 10 ((?ANS +) (?ANS 5) (?ANS 3)))}
- or inside out: @show{(coe '((?ANS -) (?ANS 10) (+ 5 3)))}
```

**Comment by flannery-denny** [comment]
Thanks @ds26gte! Worked like a charm. One last question before I close this issue.
- Do I, as an author, have any control over the size of the COE? Noticing that these three circles are representing the same thing, but they are all very different sizes. I think it would make more sense to someone new to COE if they were the same size...
<img width="247" alt="Screen Shot 2023-10-26 at 9 17 23 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/da7da48a-56fd-41f2-ae4d-79388d4069ec">

-

**Comment by ds26gte** [comment]
> Thanks @ds26gte! Worked like a charm. One last question before I close this issue.
> 
> * Do I, as an author, have any control over the size of the COE? Noticing that these three circles are representing the same thing, but they are all very different sizes. I think it would make more sense to someone new to COE if they were the same size...
> 
> <img alt="Screen Shot 2023-10-26 at 9 17 23 AM" width="247" src="https://user-images.githubusercontent.com/66691020/278373453-da7da48a-56fd-41f2-ae4d-79388d4069ec.png">

Typically CoEs show up with slightly more generous fill-in-the-blanks in non-solution mode, so the student has enough elbowroom to hand-write the answer.  However, in lesson plans, it looks like you're using CoEs with "holes" only for illustration, so in this particular case at least, the student-mode CoE and solution-mode CoE (often depicted immediately next to each other) can be of the same size. I can special-case this scenario. It will be valid only in lesson plans. Is this an ok heuristic? (Addressed to @schanzer also.)

**Comment by schanzer** [comment]
@ds26gte I've pushed a 1-line CSS fix that does what we want here, but that actually exposed a _different_ issue:  I am fairly certain that the parsing of tables within `QandA`s is chopping off the column formatting that sets things like width, text alignment, etc. 

In the same QandA flannery is talking about above, we end with a table. Here's the asciidoc:
```
@Q{Take another minute and see if you can figure out what expression each of the Circles of Evaluation on @printable-exercise{coe-notice.adoc} represents.
}
@A{ {empty}
[cols="^1a,^2a,^2a,^3a,^3a", options="header"]
|===
...
|===
```

You would expect to get a table with different column widths, all with text aligned-center. Instead, we get this:

![image](https://github.com/bootstrapworld/curriculum/assets/77126/e7ecddd9-4c44-42b1-9dad-9fda2a0bf625)

**Comment by ds26gte** [comment]
I'm not too sure why the following fix works, but here it is:

Instead of 
```
@A{ {empty}
[cols=etc]
|===
...
|===
}
```
have
```
@A{ {empty}
+
[cols=etc]
|===
...
|===
}
```

I.e., have a continuation line (with the `+`) immediately before the table start.

This also puts the item marker directly to the left (but aligned top) of the table instead of on top of it. I think it looks more meaningful actually.

![Screenshot from 2023-10-29 15-15-12](https://github.com/bootstrapworld/curriculum/assets/3708729/aeed5933-13c2-436b-8b3f-efbee890fe33)

**Comment by schanzer** [comment]
Thanks, @ds26gte ! Bizarre that it works, but thanks for finding the hack to make it so. @flannery-denny , I think the original issue is long since addressed. Close if you're satisfied?
