### ISSUE TITLE
on the web - starter files not appearing on teacher resource page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1603]
https://www.bootstrapworld.org/materials/fall2023/en-us/courses/data-science/resources/index.shtml?pathway=data-science

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/20ebe365-289e-41aa-85ec-a1f26ef2508c)

**Comment by schanzer** [comment]
@ds26gte I thought we were going to include the new `starterFiles.js` in all of our pages? I wrote the JS code that's failing here because I assumed it would be in scope.
