### ISSUE TITLE
formatting of textbook alignment guide PDFs needs tweaking

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1608]
https://bootstrapworld.org/materials/fall2023/en-us/textbooks/IM-grade-7.pdf

something weird is happening where top / bottom margins are appearing in the wrong places (e.g., they are interrupting tables.) The images are *way* bigger than we opted for them to be in the final draft, so I suspect that this is the source of the problem.

Also noting that on the [algebra teacher resource page](https://bootstrapworld.org/materials/fall2023/en-us/courses/algebra-pyret/resources/index.shtml?pathway=algebra-pyret), clicking either "PDF" or "HTML" takes users to the html version. 

This is *not* the case on the [early math teacher resource page](https://bootstrapworld.org/materials/fall2023/en-us/courses/early-math/resources/index.shtml?pathway=early-math)... where, tbh, these alignment guides probably shouldn't even be included.

**Comment by schanzer** [comment]
This is the correct behavior, as long as we want to avoid browsers adding headers and footers. Either we revert [that change](https://github.com/bootstrapworld/curriculum/issues/1568) and fix this, or we keep these alignment guides exactly the way they are.

**Comment by retabak** [comment]
The PDFs look embarrassingly terrible. How about we only offer them as HTML?

**Comment by schanzer** [comment]
The lesson PDFs are embarrassingly terrible, too. This is the end result of our distaste for heads and footers. We need to choose which one we care about.

Either way, this issue is moot. Zero tweaks are needed to fix the issue you're describing.
