### ISSUE TITLE
Add Circles of Evaluation to inequalities2-compound

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1613]
Circles are critical to Sam, because they are so gosh-darned useful for visualizing the structure of compound inequalities! The compound inequalities lesson, however, doesn't use them _at all_.

The lesson should include this discussion, _and_ a printable page to scaffold it. If this issue can be done in time, it can be added to the workbook. If not, it'll be an `@opt-printable`.

**Comment by retabak** [comment]
This is already done in the lesson! Closing.
