### ISSUE TITLE
CSS/HTML formatting for @teacher{...}

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1615]
@teacher{...} should now include `[.teacherNotes]` in lesson mode, and `.teacherNotes` should have CSS rules that make it stand out

**Comment by schanzer** [comment]
@retabak @flannery-denny I've had a proposal for this live in fall2024 since November. Are we happy with it? If so, feel free to close this issue

**Comment by flannery-denny** [comment]
@retabak I am fine with it. Close if you’re satisfied.
