### ISSUE TITLE
Read new lesson projects

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1616]
- [x] beautiful data
- [x] design a survey - should we reformat rubric? offer checklist?
- [x] threats
- [x] function
- [x] infographic
- [x] logo
- [x] data exploration 
- [x] research paper #1590 
- [x] video game

**Comment by retabak** [comment]
you actually don't need a checklist! I'm realizing you can go to lessons and look at anything that starts with project- or is in the Projects folder.

**Comment by flannery-denny** [comment]
@retabak @schanzer has deprioritized this on my todo. triple checking that nothing from these projects is in workbooks.

**Comment by retabak** [comment]
@flannery-denny The only change that will affect workbooks is the splitting of the flags into 1 lesson + 1 project-lesson, as laid out in #1673. Nothing NEW is added to the workbook, but decomposing-flags did become a part of the project-lesson.

**Comment by schanzer** [comment]
@flannery-denny so there's a slight re-ordering issue, but no pages added or removed. It sounds like we need to read the flags _lesson_ should be re-read so that it stands on its own. Otherwise we're ok.

**Comment by flannery-denny** [comment]
@schanzer I made some big changes to what was left of the flags lesson. It is not titled Transforming and Composing Images if you'd like to have a look.

**Comment by schanzer** [comment]
@flannery-denny Overall I really like this! Small nits:

1. Can we rename the lesson folder to match the new title? (don't forget to update `lesson-order.txt` in various pathways)
2. It looks like we are likely to make `translate` an alias for `put-image`. I'm assuming we want to wait until CPO and WeScheme are officially updated to make that shift in our lesson materials, but we could potentially switch this over early.

**Comment by flannery-denny** [comment]
@schanzer1. I’d love that! Thought you and Rachel had made a decision to leave it and thought it was confusing. Will address.2. After pushing these updates, the one thing that haunted me was that I wasn’t more ruthless in addressing the way translate is confusingly used in this lesson. I’ll add it to our one-on-one agenda to discuss.On Jan 14, 2024, at 7:28 PM, Emmanuel Schanzer ***@***.***> wrote:﻿
@flannery-denny Overall I really like this! Small nits:

Can we rename the lesson folder to match the new title? (don't forget to update lesson-order.txt in various pathways)
It looks like we are likely to make translate an alias for put-image. I'm assuming we want to wait until CPO and WeScheme are officially updated to make that shift in our lesson materials, but we could potentially switch this over early.

**Comment by flannery-denny** [comment]
@schanzer I just rewrote how the function is introduced in the lesson… but I’m clarifying that if we follow through with the proposal to replace put-image with translate 
- do we really want to replace put-image with translate in every starterfile in this lesson(7 + desmos), the flags project, the game statrerfile.... I’m ok with that. Just confirming it’s really what you want.
- Is there a reason we want to keep `put-image` alive in the minds of new users?
- Does WeScheme also have translate in its library or do I need to make this change be pyret only?

**Comment by schanzer** [comment]
@flannery-denny The first Launch section still explains `put-image` in terms of `overlay`. Didn't you want to change that?

WeScheme and Pyret _should_ have translate defined as an alias of put-image, but given Luke's track record we may want to hold off until we pull the trigger. Let's hold off on moving ahead until both platforms have the `translate` function defined.

**Comment by flannery-denny** [comment]
I didn't push, because the dependencies starting feeling big and I thought you might opt to hold off.

Here's what I drafted for future reference:

> == Layering Images @duration{20 minutes}
> 
> === Overview
> Students learn about the `translate` function, which uses coordinates to place the center of an image in a specific location on a background image, thinking of the bottom left corner of the background as the origin. Students reason about which coordinates should be used to locate a solid red circle in a variety of different positions on a rectangular background. 
> 
> === Launch
> As you've already seen, `overlay` sticks two images together, so that the _center_ of the first image is placed exactly on top of the _center_ of the second image. But what if we want to put the dot somewhere besides the center?
> 
> @proglang has another function `translate` which takes in two images and an x-coordinate and y-coordinate. It locates the bottom left corner of the background image at the origin (0,0) of a grid of pixels and translates the center of the top image from that same origin using the x-and y-coordinates provided.
> 
> @lesson-point{
> Think of the background image as a sheet of graph paper with the @vocab{origin} (0,0) in the bottom left corner.
> 
> The numbers in `translate` specify the point on the paper where the center of the top image should be placed.
> }

**Comment by flannery-denny** [comment]
@retabak I am working on Project: Create Your Own Function and wondering 

- Do you have a copy of the My Function Starter File. Currently the link goes to the Functions Starter File.
- How attached are you to the structure of this lesson? Will you be disappointed if I rethink and rewrite some things? Specifically...

1. There are no solutions provided on the Sample Function Study and I honestly don't know what answers you would expect for some of the questions.
2. I do not believe that students can follow these quoted instructions to facilitate the conversation you're asking them to have after completing the first section of the Sample Function Study. 

> @teacher{After this refresher on how to use a defined function (`maroon-square`, invite students to find a partner. In each partner group, one student will pose the questions below and the other will answer them. If you prefer, you can pose these questions to the class and call on individual students.}
> 
> @QandA{
> Turn and talk to a partner. One student will ask questions, and the other will answer. The student who is asking the questions should point to the line of code in the @starter-file{functions} that the the question refers to.
> 
> @Q{In the first example, how did we decide what number to use as the input for `maroon-square`?}
> @A{We randomly chose the number! We can use any number.}
> 
> @Q{How did we decide on the output for `maroon-square`?}
> @A{We thought about "what our actor would need to say" or looked at the directions.}
> 
> @Q{How would we decide what to circle in the examples?}
> @A{We would look to see what changes.}
> 
> @Q{How did we decide on our function definition?}
> @A{We looked at the examples. We wrote down everything that remained the same, and we used what we circled as our variable.}
> }

My first thought was to copy the questions into an adoc to link to. Then I wondered why they aren't just on the Sample Function Study page itself. I started editing it and decided I should check in. Perhaps I'm missing something that you're trying to get at?

FYI - I've reworked the Pyret version of the starter file and have moved work on this issue to its own `projects` branch.

**Comment by retabak** [comment]
Here is the My Functions starter file: https://code.pyret.org/editor#share=1Cv5gmq6FmMq_LwUKOvvWXLbi8v_wDSqh&v=0c33ff0 - thanks!

I am not attached to the lesson structure. Have at it! THANK YOU. Eager to see it improve :)

**Comment by flannery-denny** [comment]
@ds26gte I'm on the `projects` branch and have
`modified:   lessons/Projects/project-infographic/langs/en-us/pages/challenger-case-study.adoc
`
I cannot for the life of me figure out why I'm getting this message
`WARNING: Lesson project-infographic: handout refers to nonexistent file distribution/en-us/lessons/project-infographic/pages/challenger–case–study.adoc`
Is it possible there's a bug in the script that's dropping the language from the `@handout` directive?

**Comment by ds26gte** [comment]
The `@handout` call in the lesson plan uses an en dash (U+2013) instead of a true hyphen (U+002D).

```
@handout{challenger–case–study.adoc}   ;what's in there

@handout{challenger-case-study.adoc}    ;what's should be there
```

If you squint, you should be able to see that the "hyphens" in the first line have more girth than the real hyphens in the second line.

**Comment by flannery-denny** [comment]
@retabak Is there anything I should know about why the research project slide deck doesn't include scaffolding about the code that generated the displays?

**Comment by flannery-denny** [comment]
@joystraub please read these two projects

- [Dataset Exploration](https://bootstrapworld.org/materials/fall2024/en-us/lessons/project-data-exploration/index.shtml?pathway=data-science)
- [Research Capstone](https://bootstrapworld.org/materials/fall2024/en-us/lessons/project-research-paper/index.shtml?pathway=data-science)

And either
- close this issue if you're satisfied with them or
-  leave me feedback on how to improve them

Thanks!

**Comment by joystraub** [comment]
Oh my gosh, Flannery!!  These are SOOOOO much better.  Very clear, mapping out all of the options and way to incorporate each of these.  I LOVE them!!!!  I think they are definitely going to be more useful to the teachers in this form.  Closing the issue.  :)
