### ISSUE TITLE
add missing functions to contracts dictionary

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1617]
- [x] string-contains
- [x] triangle-sas
- [x] triangle-asa
- [x] image-url
- [x] and
- [x] or
- [x] stdev
- [x] num-sqr
- [x] num-sqrt
- [x] num-expt
- [x] all operators (+, -, *, /)

Noting that and, or, and all operators will not appear on the language table, and that is intentional!

**Comment by flannery-denny** [comment]
@schanzer `triangle-sas` , `triangle-asa` , `and`, `or`, `image-url` and `string-contains` are all already in the `lang-table.js` file. The only one that seems to be missing is `stdev`... Wondering why they aren't appearing in the autogenerated contracts page. Is this a bug?

**Comment by schanzer** [comment]
@flannery-denny `stdev` should definitely be in the `langtable.js`! Its omission is a bug.

As for the others: _there is no autogenerated contracts page_. It's literally a blank page! Instead, that table is _dynamically generated_ based on the `pathway=XYZ` argument in the URL. If those functions aren't added to the table (`@add-to-lang{}`) in the lessons plans, then they will never show up in the dynamically generated page.

**Comment by retabak** [comment]
Ah, that makes sense! So I need to add all of those functions to the lesson
table. I'll add it to my list :)

I'm also pretty sure I saw stdev added to the language table as st-dev.
Guessing that's the source of the problem. I will fix.

**Comment by retabak** [comment]
but wait....

All of the operators are in the language table, and they still don't appear in the contracts dictionary. What's the deal with that?

**Comment by schanzer** [comment]
@retabak they [absolutely are in the contracts dictionary](https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-wescheme).

**Comment by retabak** [comment]
right, for wescheme only... and now I understand why!

**Comment by flannery-denny** [comment]
@retabak I just pushed a commit that will likely fix things and forgot to tag you. I haven't had a chance to test. Dacks is up and I'm running him to daycare. I'll check in when I'm back and see whether or not this resolved the issue. (I'm not totally sure where to look, so if you have a chance to check, please do.)

**Comment by flannery-denny** [comment]
Closing this as @retabak's task is done.
