### ISSUE TITLE
Make design recipe and baby design recipe shading colors match (lighter is better!)

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1622]

**Comment by schanzer** [comment]
@flannery-denny I've pushed this to `fall2024`. Close if you're happy?

**Comment by flannery-denny** [comment]
They do all appear to be the same purple, but that is not the desired outcome.

**Comment by schanzer** [comment]
@flannery-denny I forgot that we use the baby DR in another lesson. Thanks!

What's wrong with purple?

**Comment by flannery-denny** [comment]
Looks like we also use something different it in top down/bottom up

**Comment by schanzer** [comment]
@flannery-denny I'm not seeing what you mean here. We don't even use the design recipe on that page
<img width="1074" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/cb2cdf7d-c216-4329-95a6-0dc2cf02597a">

**Comment by schanzer** [comment]
@flannery-denny this should now be resolved. I forgot that we have _two_ such pages, and now knowing which lesson the wbpage was from led me astray. :) Sorry for the delay!
