### ISSUE TITLE
Could wescheme be updated to take in hyphenated color names?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1626]
- [ ] Just noticing that Pyret can take in either "dark-green" or "darkgreen" and WeScheme only accepts "darkgreen". This means that we as authors (me!) sometimes write WeScheme examples that wouldn't actually work. If it would be easy to make WeScheme also accept hyphenated versions of those strings it would make authoring less error prone.
-  ~Separately, wescheme takes in `isosceles-triangle` and `radial-star` but for some reason uses `triangle\asa` and triangle\sas`. I imagine this is as confusing to teachers and students as it is to authors. Please add hyphenated versions of these function names.~
-  ~Once you add those hyphenated names, please update Dorai's sexp list to point to the hyphenated version for wescheme~ 
- ~And do a find and replace in the repository to only show the hyphenated versions of these function names. (l think we have to keep the `/` versions in the dictionary for those who remember them, but they should be less discoverable since they are less consistent)~

**Comment by schanzer** [comment]
@flannery-denny the last checkbox should be removed. Anything using `@show{(code..)}` needs to use `/`, not `-`

**Comment by flannery-denny** [comment]
Adding this issue to the curriculum team agenda
