### ISSUE TITLE
Throw warnings for @add-to-lang errors

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1627]
If an author uses a function name that is not in the 'langtable.js' could we throw a warning?

Here's an example of something that could happen without throwing any warnings

`@add-to-lang{NotARealFunction}`

**Comment by flannery-denny** [comment]
Closing this as I have just learned that @schanzer and @retabak have decided to completely remove the language table for now, so this part of the lesson plan is probably doing absolutely nothing and it's hard to understand why we were even discussing `@add-to-lang` today.

**Comment by retabak** [comment]
@flannery-denny - we were discussing `@add-to-lang` because `@add-to-lang` is how things get added to the searchable contracts dictionary.

**Comment by schanzer** [comment]
Nicely done!!!
