### ISSUE TITLE
@dist-link{Contracts.shtml, Contracts Pages} build issues

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1628]
`@dist-link{Contracts.shtml, Contracts Pages}` is supposed to 

1. Link to a searchable list of Contracts 
2. That list of Contracts should be appropriate for the pathway

Currently:

- [x] When the link is used in [https://bootstrapworld.org/materials/fall2023/en-us/lessons/making-game-images/index.shtml?pathway=algebra-pyret]( https://bootstrapworld.org/materials/fall2023/en-us/lessons/making-game-images/index.shtml?pathway=algebra-pyret), which is not missing any functions.

- [x] When the link is used in [https://bootstrapworld.org/materials/fall2023/en-us/lessons/making-game-images-wescheme/index.shtml](https://bootstrapworld.org/materials/fall2023/en-us/lessons/making-game-images-wescheme/index.shtml) it also goes to [https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml](https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml), which is in Pyret even though it should be in WeScheme.

- [x] At the bottom of [https://bootstrapworld.org/materials/fall2023/en-us/courses/algebra-wescheme/](https://bootstrapworld.org/materials/fall2023/en-us/courses/algebra-wescheme/) (which I believe is autogenerated so I can't see the asciidoc to know whether or not it's pointing to `@dist-link{Contracts.shtml, Contracts Pages}` it goes to [https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-wescheme](https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-wescheme), which is missing
-- `triangle/asa` 
-- `triangle/sas`
-- `sqrt` 
-- `image-url`
-- `expt`
-- currently incorrectly provides `string-contains` instead of `string-contains?`, which would ostensibly would be fixed if the updates on master were to make it to the web, because I fixed that in `langtable.js` today

- [x] At the bottom of [https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-pyret](https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-pyret) (similarly generated) it goes to [https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-pyret](https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-pyret), which is missing 
-- `triangle-asa` 
-- `triangle-sas`
-- `stdev`
-- `num-sqr`
-- `num-sqrt`
-- I know that operators shouldn't be listed in pyret, but what about `and`, `or`, `<`, `<=`, etc.?

**Comment by flannery-denny** [comment]
@schanzer @ds26gte I think I may have cracked part of the mystery on why some terms aren't showing up. Noticing that in `langtable.js` the functions that appear on the list as missing are written like this

> {"name": **"num-expt"**,
>        "domain": [{"name": "base", "type":"Number"}, {"name": "power", "type": " Number"}],
>        "range": "Number",
>        "example-pyret": "num-expt(3, 4)",
>        "example-wescheme": "(expt 3 4)",
>        "comment" :  "three to the fourth power"},

Such that the "name" is being given in pyret rather than wescheme. I am going to push a fix.

**Comment by flannery-denny** [comment]
And I think that the missing `image-url` may be related to this
<img width="188" alt="Screen Shot 2023-11-10 at 2 06 43 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/aa51b023-1e4c-485e-bf8d-9dc3d0c74913">
but I'm not sure how to fix it.

**Comment by flannery-denny** [comment]
@ds26gte @schanzer Now that the contracts pages are building again, I can confirm that 

1. the change I pushed resolved the missing the functions
2. the bad news is that for functions that have different names in pyret than they do in wescheme, the contract is providing the wrong function name!
<img width="782" alt="Screen Shot 2023-11-10 at 2 33 27 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/e68474cf-8bd1-421b-874f-1584cec158ea">

**Comment by ds26gte** [comment]
Commit a75770490 -- in tandem with @schanzer's embedding the `?pathway=...` URL postfix inside `@ifproglang`s -- should correct which version of the Contracts.shtml is pointed to.

**Comment by schanzer** [comment]
@ds26gte thanks for the fix! 

One small nit: We're now getting the following build warning:
```
WARNING: Lesson plan distribution/en-us/lessons/making-game-images-wescheme/index.adoc: @dist-link: Missing file ./Contracts.shtml?pathway=algebra-wescheme
```

Not sure if this is easy to correct. Maybe strip the URL params before checking for the existence of the page, then putting them back?

**Comment by schanzer** [comment]
(@flannery-denny note that `stdev` should _not_ show up in your list above, since it's not used inside the algebra pathway)

@ds26gte I've just pushed a commit that _should_ add `stdev` to the Contracts page when `pathway=data-science`. However, it's not showing up. A quick inspection of the graph (after a `make clean`) shows that no primitives are added in the `standard-deviation` lesson...which can't be right, since that lesson uses the appropriate directive. Can you take a look, when you have a chance?

**Comment by schanzer** [comment]
@ds26gte nevermind -- this is now resolved. @flannery-denny I believe this issue can be closed, if you want to give it a once-over?

**Comment by retabak** [comment]
@flannery-denny - fyi, `and, or, <, <=`, etc. should not be listed in Pyret (which is annoying!).

**Comment by flannery-denny** [comment]
@schanzer This looks better.

For some reason that I haven't found a logic for... 
- [ ] the drop down menu in the supplemental materials section sometimes does what it should and sometimes automatically opens and lists the pages in larger font. 

I accessed the screenshots below by clicking on links to lesson from the course landing page [_file:///Users/flannery/Documents/Bootstrap/curriculum-review/distribution/en-us/courses/data-science/index.shtml_](file:///Users/flannery/Documents/Bootstrap/curriculum-review/distribution/en-us/courses/data-science/index.shtml)
<img width="874" alt="Screen Shot 2023-11-13 at 11 54 54 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/065f4248-9aee-4dc1-acb6-bc4d78744579">
<img width="870" alt="Screen Shot 2023-11-13 at 11 55 18 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/646cfb61-6482-4270-b08e-c9c7896df992">
<img width="867" alt="Screen Shot 2023-11-13 at 11 55 31 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/4a5eed07-3b03-42b0-aa6c-5fccf3fb27a2">

**Comment by flannery-denny** [comment]
closing as the remainder is on #1635
