### ISSUE TITLE
codapify data cycle 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1629]
This entails removing the "Analyze Data" row.

(Another option is to change the prompt to say something like "what menu options will you need to select?" but that feels a little half-baked.)

**Comment by schanzer** [comment]
@retabak I'm not able to see what the issue is here. Here's a screenshot from `lessons/choosing-your-dataset-codap/pages/data-cycle-categorical.html`:

<img width="423" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/c6c14a17-2d47-417a-94fb-15d8c9612aee">

Can you give me a specific page or screenshot where you see this row?

**Comment by retabak** [comment]
This is what I see. I'm on the branch codap-display-lessons. Here's the URL for my local build:
file://wsl.localhost/Ubuntu/home/retabak/curriculum/distribution/en-us/lessons/choosing-your-dataset-codap/pages/data-cycle-categorical.html

Happy to zoom if that would be useful!

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/78571424-0a56-495d-b98d-444898d963c8)

**Comment by schanzer** [comment]
@retabak Not seeing it. Please do a fresh pull, then `make clean` and `make`. If you're still seeing it, let's zoom sometime before 2:30 ET?

**Comment by retabak** [comment]
NVM!
It looks right now. I swear I did all of the steps you recommended before... but I did it again and all is well.

**Comment by retabak** [comment]
@schanzer don't worry - this still works!

I'm codapify-ing the data cycle lesson, and noticing that the analyze phase of the data cycle isn't just about writing code, but about choosing the display type. 

Instead of removing the 'analyze' row from the codap data cycle pages, what if we included a line with this prompt: _"What table or display do you want to create (i.e., bar chart, pie chart, etc.)?_

**Comment by schanzer** [comment]
@retabak done. You can tweak the wording in `shared/langs/en-us/curriculum.css`
