### ISSUE TITLE
2nd level headers break .FillVerticalSpace

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1631]
I'm in the contracts lesson on `fall2024` and second level headers are doing something strange with vertical space. Notice that there is a lot of space between the title and the first second level heading.
[text-coe.pdf](https://github.com/bootstrapworld/curriculum/files/13340986/text-coe.pdf)

Update: I'm working to add second level headers to pages that should be using them. Here's the before and after for Notice and Wonder. Linearity from the `Functions can be linear` lesson on `fall2024`
<img width="595" alt="Screen Shot 2023-11-13 at 5 38 53 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/27371c59-f589-4590-97c8-cb3b4be77ff5">

<img width="444" alt="Screen Shot 2023-11-13 at 5 38 02 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/dbaf2f46-d89d-4624-ba18-81172f04d403">

**Comment by schanzer** [comment]
@flannery-denny unfortunately, these two cannot be used together. If you want to use second-level headers, you'll need to control the height of the tables by hand.

**Comment by flannery-denny** [comment]
Good to know, @schanzer.
Now, as for the solution. 

- My guess is that the right thing to do is to use the second level headers (because you asked for them to be used consistently) and know that we can't use `.FillVerticalSpace` on those tables.

Before I make that fix, confirming that you wouldn't rather see `.FillVerticalSpace` than second level headers for some reason that I can't think of?

**Comment by schanzer** [comment]
Confirmed. :)

**Comment by flannery-denny** [comment]
@schanzer Curious which of these rules on Decomposing Flags breaks `.FillVerticalSpace` and whether it's still preferable
```
++++
<style>
#content img { border: solid 1px black; }
#content .centered-image { margin-bottom: 10px; }
#content td * { padding: 0; margin: 0; text-align: center; vertical-align: middle; }
#content tr { height: 2.3rem; font-size: 0.9rem; }
</style>
++++
```
