### ISSUE TITLE
distance-coe.adoc needs some tlc

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1632]
compare the `fall2023` version on the web with how it's building on `fall2024`

**Notice the following**

- [x] The square root bar isn't extending over the expressions
- [x] @schanzer's css rule for making big work with unicode (borrowed from the order of op lesson plan) doesn't pick up the exponents 
`.big .mathunicode {font-size: 3em !important; color: black;}`

<img width="615" alt="Screen Shot 2023-11-13 at 6 05 44 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/db5c7dcc-59e3-4763-87ff-568bd1337e7b">
<img width="586" alt="Screen Shot 2023-11-13 at 6 00 20 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/fd47d341-11b8-445d-b8e6-690d21346335">

**Comment by schanzer** [comment]
@ds26gte I think the mathunicode conversion needs to be updated to include vertical bars. The _lesson plan_ includes the following:

`@math{\sqrt{{\lvert x_2 - x_1 \rvert}^2 + {\lvert y_2 - y_1 \rvert}^2}}  }`

But it renders as

![image](https://github.com/bootstrapworld/curriculum/assets/77126/615b3328-98fe-472d-b330-27de2ae227f1)

**Comment by flannery-denny** [comment]
The square root line is currently cutting off the exponents
<img width="949" alt="Screen Shot 2023-11-14 at 12 28 53 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/2ea891e0-c791-4ca0-a7fe-1dc5a8615fdf">

**Comment by schanzer** [comment]
@flannery-denny Is this in the workbook page? Here's what I see

![image](https://github.com/bootstrapworld/curriculum/assets/77126/262519f4-63a5-4e37-bcf1-d1d026669bf8)

**Comment by schanzer** [comment]
@flannery-denny I'm not seeing this. Confirming you're on a fresh pull?

![image](https://github.com/bootstrapworld/curriculum/assets/77126/89b38b21-eb20-46fb-940f-51640f890000)
