### ISSUE TITLE
AI literacy lesson brainstorm

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1634]
- [ ] Generate a list of questions that we would want to know about AI that Shriram can use to think about what else we should talk about.

**Notes from conversation with Shriram**

To be literate, people would understand 
- A little about what the tech does
- A little about what it doesn’t do
- A little about what can go wrong

We could touch on 

- the misconception that chatgpt works like a search engine
- how an image query works
- [clustering](https://docs.google.com/document/d/10M-msfm6pTYLLsIwR7zSmfO07UVRZnuyoz59p6sEQCE/edit#heading=h.za2lqlebr3e4) v classification
- supervision v nonsupervision
- natural language processing, vision, text

Other providers to investigate:
- https://ai-4-all.org/resources/
- https://ai4k12.org/

[List of questions for Shriram](https://docs.google.com/document/d/1ZlDPLJniDn8a28w6-VEKON63qfD9oQVwoUFOV4mcYJc/edit?usp=sharing)

**Comment by flannery-denny** [comment]
@shriram a first few questions

- What are the similarities and differences between the chatbot who replies to my customer service request on a website and the automated assistant who attempts to intuit why I'm calling looking for a live representative by phone?
- I notice that google makes suggestions about replies to emails. How is that different from what it returns from a google search?
- Amazon has started offering AI generated summaries of customer reviews. Is this the equivalent of an embedded autoupdating chatgpt widget?

**Comment by shriram** [comment]
Great questions (and of course I can only partially answer them because some of these things are proprietary info, etc.).

I'm wondering if this is the right format? Should we maybe do a GDoc where we can interleave questions and answers (and link it here so we can find it later)? I'm worried that after 3-4 of these posts, what "it" is referring to will become very, *very* confusing.

**Comment by retabak** [comment]
just read this article that had a lot of potentially great ideas so I took some notes here.

[AI Literacy, Explained](https://www.edweek.org/technology/ai-literacy-explained/2023/05) 

- Why it's vital to have a basic understanding of how AI works
> AI is "really advanced guesswork" - we need to undestand the weaknesses it has (errors, misinformation, bias)

- Give students hands-onopportunities to understand how the tech works

> One hands-on lesson for more advanced students: Give them a flawed historical dataset on which to train an AI system, Partovi said. For instance, students could create a program that gives suggested salary ranges for a company’s employees.

> If that program is informed using data in which women are paid less than men for doing the same job, the technology will probably propose lower salaries for female employees than for male workers. But if women are at salary parity with men in the dataset, the results will be more equitable.

- Discuss and analyze ethical questions about the technology
> e.g., is it safe for passengers to fall asleep in the backseat of a self-driving car as it goes down the road?; should states ban facial-recognition software until it becomes more accurate?

- How to interact effectively with AI
> think about how the prompt given to ChatGPT influences the response

- Let students know that AI skills are not just for computer science experts
> AI works best when it is designed by people who belong to the community the tool is aimed at serving. Having people from a variety of backgrounds can help root out biases.

**Comment by flannery-denny** [comment]
This is not a question, but rather a stashing of information about an event for educators focused on AI that happened in NYC this month in case it becomes relevant down the line. 

> EdTech entrepreneurs Abran Maldonado and Kanene Ayo Holder are hosting an event to discuss how artificial intelligence can be used in ethical way to increase creativity and productivity. 
> Our BIPOC startup Create Labs Ventures is an innovative GenerativeAI company dedicated to creating inclusive and equitable solutions in tech. 
> We have presented at educational conferences including SXSW EDU in the past and would love for educators to attend our event!
> It’s a great opportunity to learn more about AI and its impact on jobs, education, marketing and entrepreneurship before the holidays! 
>

**Comment by schanzer** [comment]
@flannery-denny @retabak linked the [question document](https://github.com/bootstrapworld/curriculum/issues/1634) from the description. Please take a moment to review/add sometime before Friday?

**Comment by shriram** [comment]
Who is this directed to?

**Comment by flannery-denny** [comment]
Hi @shriram! In our curriculum meeting I proposed that we should make the googledoc you asked us for before your semester finishes so that we don't miss out on your pre-sabbatical availability.  Emmanuel put together a first draft based on our conversation and we will add some more to it before the end of the week. Ultimately, the document represents questions we'd love to hear from you about. Written responses would be helpful, but, if you read the questions and decide you'd rather make a time to talk about it with us in January, that would work for us, too!

**Comment by shriram** [comment]
I get all that. I'm just referring to Emmanuel's latest message. He said "please take a moment" without saying who he wanted to take a moment. I am guessing he didn't mean you and Rachel because he explicitly mentioned you in the previous sentence and not in this one, but I couldn't tell who else he was addressing — me? It's very confusingly worded for me.

**Comment by schanzer** [comment]
@shriram I tagged Rachel and Flannery, to indicate that this comment was aimed at them. In our repo, we try to always tag comments to indicate who they are intended for. Sorry for any confusion.

**Comment by retabak** [comment]
[Here are notes from today's meeting!](https://docs.google.com/document/d/1oFJoAQieG5ApBPqlwmanPyrMZsLicRFp9NBgx7kNUwA/edit?usp=sharing)

**Comment by shriram** [comment]
Thanks! I went and cleaned it up a bit and answered the last few questions.

**Comment by shriram** [comment]
Here's an article you should consider reading. It's written by an actual AI prof (Mark Riedl), so he fully knows what he's talking about, and tries its best to break down LLMs into something hopefully understandable:

https://mark-riedl.medium.com/a-very-gentle-introduction-to-large-language-models-without-the-hype-5f67941fa59e

**Comment by shriram** [comment]
This NYT piece may also be helpful:

https://www.nytimes.com/interactive/2023/04/26/upshot/gpt-from-scratch.html

**Comment by schanzer** [comment]
@shriram thanks for these! the medium article was really helpful for me, but I also know _just_ enough for it to "land". The NYTimes article is _fantastic_ - that's a seriously terrific piece!

**Comment by schanzer** [comment]
[Video from the meeting](https://youtu.be/KDyhKKBfrPk)

**Comment by schanzer** [comment]
Now that the brainstorming is complete, we've collated the links from this issue and comment thread into #1750. Work on that lesson will be tracked there.
