### ISSUE TITLE
Fix alphabetization of pyret contracts

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1635]
@schanzer We could live with this. 

- [ ] The one weird thing is that the pyret contracts are alphabetized by the wescheme name, so `num-expt` is with the `e` functions and `num-sqr` is with the `s` functions. 
-- Fixable? 
-- If not, it'll do.
- [ ] Also, I wonder if it would be possible to acknowledge that these contracts are language specific somewhere at the top. On our lesson plans we have a link to the `wescheme` version. I think that would also make sense on this page if it's not a pain. 
**"Note: These are `pyret` contracts. If you're looking for the `wescheme` version, click here."**

**Comment by schanzer** [comment]
@flannery-denny the page is only accessed by clicking a link with a `pathway=XYZ` link, so unless someone does url hacking they will ALWAYS be looking at the correct table for their proglang

**Comment by flannery-denny** [comment]
@schanzer I think teachers who teach in wescheme might mistakenly open the algebra-pyret pathway and not notice that it was in pyret. Then click on the contracts link and not know that they were looking at pyret contracts. That’s happened with nancy cousins on discourse, for example. 

Even if we don’t want to link to the other, it would help to subtitle the page with its language.

**Comment by schanzer** [comment]
@flannery-denny done!
