### ISSUE TITLE
allow lessons in one proglang to exclude workbook pages / starter files from another proglang

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1636]
When I build on codap-display-lessons branch, I'm getting these warnings:

```
WARNING: Lesson distribution/en-us/lessons/linear-regression-codap/solution-pages/age-v-height-explore.adoc: @starter-file height missing for codap

WARNING: Lesson distribution/en-us/lessons/linear-regression-codap/solution-pages/olympics-project.adoc: @starter-file olympic-records missing for codap

```

...but age-v-height-explore.adoc is an optional pyret-only activity, just like olympics-project.adoc. 

We'd like to be able exclude an activity from one proglang and keep it in another.

**Comment by schanzer** [comment]
@retabak can you close if this is now fixed?
