### ISSUE TITLE
2nd level headers also seem to break @fitb{}{}

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1640]
Take a look at how this code renders.

```
== Defining Faces

*Find PART 1 in the Definitions Area of the starter file (on the left). You will see a definition for `front` and `back`.*

@n How did the author know to use width and height as the dimensions for `front` and `back`?

@fitb{}{}

@fitb{}{}

@n Why are `front` and `back` defined to be the same thing?@fitb{}{@ifsoln{_In a rectangular prism, parallel faces are all identical._}}
```

<img width="624" alt="Screen Shot 2023-11-15 at 9 51 32 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/6247cae9-c58a-4729-bcac-31e6eeb6d110">

[prism-explore.pdf](https://github.com/bootstrapworld/curriculum/files/13366787/prism-explore.pdf)

I'm pretty sure it's why the pages that 2nd level headers got added to are wonky in length.

Lmk 

- [ ] is what you would expect?
- [ ] would you like me to continue adding 2nd level headers to workbook pages?
- [ ] Do you happen to know how many `em` the a full-page-width `@fitb` needs?
- [ ] If we are going to continue using 2nd level headers for workbook pages, I need to do an audit for double height `@fitb{}{}` on these pages. Can you please remind me what search to do in sublime to get a full list of workbook pages only that use `==`? ie. which of these icons should be selected?
 <img width="380" alt="Screen Shot 2023-11-15 at 9 57 36 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b2b5da40-149d-41ed-9147-b355ea6f6480">

**Comment by flannery-denny** [comment]
@schanzer this is an issue with html only. they look fine on pdfs. see prism explore as an example.

**Comment by schanzer** [comment]
@flannery-denny I would expect it to look like this:
![image](https://github.com/bootstrapworld/curriculum/assets/77126/82d6116c-6d0d-4fbf-870b-a78cfcadd9ac)

Which is how it looks on both master and fall2024. Where are you seeing this? 

And yes, please continue adding 2nd level headings. And don't do any audits until we actually find out what's going on for this one.

**Comment by flannery-denny** [comment]
Closing until it pops up again.
