### ISSUE TITLE
Pages with lots of empty space should shove it to the bottom, instead of distributing evenly

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1641]
Here are three pages to compare.
[lr-plot-explore.pdf](https://github.com/bootstrapworld/curriculum/files/13366936/lr-plot-explore.pdf)
[drawing-predictors.pdf](https://github.com/bootstrapworld/curriculum/files/13366941/drawing-predictors.pdf)
[which-questions-make-sense.pdf](https://github.com/bootstrapworld/curriculum/files/13366967/which-questions-make-sense.pdf)

**Comment by flannery-denny** [comment]
yes.  I was just about to share some other pages that showed inconsistency around my previous claim, but I think you've probably cracked it.

**Comment by schanzer** [comment]
We do this already on a few pages (see `advanced-displays/pages/beautiful-data-project.adoc`). 

You need to override the default display type (flex) with something different (block). You can do this with:
```
++++
<style>
	#content { display: block !important; }
</style>
++++
```

**Comment by flannery-denny** [comment]
@schanzer can you give me an example of a workbook page where it is beneficial for flex to be the default. I can't picture why it would be an improvement to not have things consistently located.

**Comment by schanzer** [comment]
@flannery-denny If we drop flex, we lose FillVerticalSpace. And that's used in a _ton_ of places. It's also needed for many of the vertical-flexibility solutions you've asked me to write.

This problem only shows up on pages that aren't (mostly) filled up with content. We don't have a ton of those, and I think we should be skeptical of pages with large amounts of "dead air".

**Comment by flannery-denny** [comment]
ok. I'll audit and fix with the rule. Thanks for clarifying. It's been driving me nuts to have a moving target without explanation.

**Comment by flannery-denny** [comment]
[lr-plot-explore.pdf](https://github.com/bootstrapworld/curriculum/files/13368657/lr-plot-explore.pdf)

**Comment by schanzer** [comment]
@flannery-denny please use the folllowing rule:

```
	#content { display: block !important; }

```
