### ISSUE TITLE
@hspace either is never working or is working inconsistently on fall2024

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1642]
Using `@hspace` does nothing to shift the text or code block to the right in at least the following two instances:

- the `prism-explore` page in `surface-area-rect-prism` lesson (see commit below)
- In the `contracts` lesson plan in the `composing with circles` section.

```
What if we wanted to see your name written on a diagonal? 

* We know that we can use the `text` function to make an Image of your name.

@hspace{2em} @show{(contract 'text '((message String) (size Number) (color String)) "Image")}

*  @ifproglang{pyret}{Pyret}
@ifproglang{wescheme}{WeScheme}
also has a function called `rotate` that will rotate any Image a specified number of degrees.

@hspace{2em} @show{(contract 'rotate '(Number Image) "Image")}

_But how could the `rotate` and `text` functions work together?_


```
<img width="747" alt="Screen Shot 2023-11-15 at 12 05 54 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/873a2feb-0861-477a-b879-dc65ec991315">

**Comment by schanzer** [comment]
@flannery-denny do a fresh pull on fall2024 and see if this resolves the issue?

**Comment by schanzer** [comment]
@flannery-denny done!

**Comment by flannery-denny** [comment]
Merci!
