### ISSUE TITLE
[.indentedpara] isn't achieving indentation

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1643]
This used to work.

[.indentedpara .forceShading]
--
``fun is-cat(r): r["species"] == "cat" end
lr-plot(filter(animals-table, is-cat), "name", "age", "weeks")
``
--
[lr-plot-explore.pdf](https://github.com/bootstrapworld/curriculum/files/13368742/lr-plot-explore.pdf)

And I've been noticing the same issue in other files.

**Comment by schanzer** [comment]
@flannery-denny I just looked at the adoc for the page you shared. If you want to declare multiple classnames, you need to use this:

`[.indentedpara.forceShading]`

I suspect this may be the case elsewhere, too. When used properly, the indentation works as expected.
