### ISSUE TITLE
expected behavior if lesson's prereq is in lessonsToIgnore?

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#1649]
`bootstraplesson.js` defines a list `lessonsToIgnore`, all of whose members are pruned from the dependency graph when chasing down lesson prerequisites.  

When such an "ignored" lesson is claimed as prereq in some other lesson, it causes an "unknown lesson" error (thrown by `getTransitivePrereqs()`). 

Do we want this behavior, so that the author gets a heads-up that she's using an ignored lesson as prereq? Should it be downgraded to a warning, or even completely ignored?

The particular example: The lesson plan in `project-research-paper` has prereq `project-data-exploration`. `project-data-exploration-codap` is an "ignored" lesson. This causes `bootstraplesson.js` to throw an error for `project-research-paper-codap` not being able to find `project-data-exploration-codap` .

**Comment by schanzer** [comment]
@ds26gte if `project-data-exploration-codap` is complete, then it should not be on the `lessonsToIgnore` list. @retabak can you confirm that it's ready to go?

**Comment by ds26gte** [comment]
What is the rationale for putting WIP lessons in `lessonsToIgnore`? I thought the latter was only for bogus lessons used for debugging, like `[sz]ample*`.

**Comment by schanzer** [comment]
We don't want WIP lessons to show up on the website after being deployed.

**Comment by ds26gte** [comment]
This is throwing error during development builds. At least we should downgrade it to a warning so it doesn't interrupt development with hard-stop errors, no?

**Comment by retabak** [comment]
@schanzer - yes, project-data-exploration-codap is ready to go!
