### ISSUE TITLE
Data Science notes from a MI teacher

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1658]
Russell Maciag was a standout teacher among standout teachers in Michigan last summer, asking incredible questions and pointing out both statistical and pedagogical corner-cases we'd missed. He was so damned good that I offered him a gift card for reviewing some of our lessons.

[Here's what he came back with](https://drive.google.com/drive/folders/10b3f6R5v0caFDARr9vvyVK8Nrn5VHRNB). Would love to have someone take a pass at this, implementing low-hanging fruit and providing recommendations about the bigger stuff.

- [x] Make the Fair Coins Starter File use different color coins: 
- [x] Change the Fair Coins Starter File so that coin1, coin2, and coin 3 are not in the same order as the options on the worksheet, which is fair, 75%, 90%
- [x] In lesson plan and on slides 2,3,5 that currently have an image of heads from the starterfile, either
-- add an additional image of the tail side of the coin from the starter file
-- replace the heads image with a head and tail image of a real coin
- [x] Add IQR and Range to Pyret box-plots?
- [x] #1698
- [x] Glossary: in the definition for “distribution” the phrase “relative probabilities” seems unnecessary. Instead “relative frequency” or just “percentages”? simplify it. 
- [x] Decide whether the context for the probability lesson should be a hussler in a back alley or a casino and stick with it. Currently references both. Neither is likely to work for antigambling people. - FD on master
- [x] get rid of IDS and Gaise reference using [*] and replace with inline ()
- [ ] Update the definition for null hypothesis to be approachable at the start of the probability lesson.
> null hypothesis the claim that there is no difference or relationship in the larger group(s) from which we sampled. For a single variable, this claims that a summary like the mean or proportions of a population equals a proposed value. For multiple variables, this claims that no relationship exists between those variables in the larger population
- [x] update data cycle to say "which rows" instead of "what rows"
- [x] These next two bullets should either be addressed now or added to #1674 
- [x] How to Spot a Scam - Synthesize (Slide 9): "how many samples" is confusing since up until this slide/portion we have been measuring sample size. The rest of the explanation then continues to talk about sample size, not number of samples. 
-  ~Probability v. Inference - Launch (slides 10 & 12): I get the point of “forwards” and “backwards” but I feel that it’s not necessarily helpful to students. Instead, for “forwards” say “inwards”, we are looking in at an event we already have data on, and for “backwards” say “outwards” since we are looking at events we don’t have data about specifically.~
- [x] Add data cycles for use with each of the Design Recipe telephone sets in the Defining Row Functions lesson.
- [x] There is no glossary for Defining Table Functions - Identify words that are worth defining - The lesson uses **Row-based Functions**
- [x] Sort out DR Telephone in this [lesson section](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/defining-table-functions/index.shtml?pathway=data-science#_design_recipe_telephone_duration40_minutes) of  Defining Table Functions
<img width="853" alt="Screen Shot 2023-12-07 at 1 27 10 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b57b4332-3800-4994-8efa-f43bf9d0476b">

has a link that appears like it will take us to a relevant workbook page, but instead it just directs users to another lesson!
The same section has a conflicting set of directions for what to you finish the Design Recipes
> When you’ve finished all three Design Recipes, turn to the Data Cycle for your set and work as a team to complete it!
What do we want them to do? 

In the Algebra version of DR Telephone, we made a specialized starter file that pairs with the DR pages. That doesn't make sense here.
- [x] Separate range definitions for algebra and ds using shadow glossary? _modified DS definition instead_
- [x] why is there no definition for alternative hypotheses? Usually knowing the definitions for both terms is useful in understanding the other. **Not doing this.**

Lessons where feedback has been dealt with
- [x] Visualizing the shape of data
- [x] Advanced Displays
- [x] Probability Inference Example
- [x] Defining Table Functions (other than comments that remain above)

**Comment by flannery-denny** [comment]
@schanzer @ds26gte Can our glossary handle “range (of a function)” and “range (of a dataset)” as separate entries that are both sometimes referenced as just “range” within a lesson? 

Asking because from a DS teacher perspective,

> it’s unnecessary to have both definitions of range here. We are not using the range (of a function) during this lesson so there isn’t a need to have that definition here. Students can handle (or need to learn how to handle) using words that have multiple meanings. If both must remain please use “range (of a function)” and “range (of a dataset)”

**Comment by schanzer** [comment]
@ds26gte this is an interesting idea. Could `@vocab` be extended to take an optional argument (like we do for other directives) that overrides the normal text displayed in the lesson, but allows the full vocab name to show up in the glossary?

@flannery-denny slides are statically generated, and therefore cannot have page numbers

**Comment by flannery-denny** [comment]
@schanzer Our current definition of conditional reads

> a code expression made of questions and answers

Russell asserts this isn't helpful, and I agree we can do better. What are your thoughts on his proposed replacement?

> a code expression that will only run if a stated condition is met or is true. Conditional statements are often written in “if, then” form”

**Comment by flannery-denny** [comment]
@schanzer what to do you think of the proposal to change the data cycle wording from
<img width="439" alt="Screen Shot 2023-12-01 at 12 20 37 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/2fb9eb8c-51f8-4cf3-8b0c-a568f6eaea0d">

to

> We "Ask Questions" - after reviewing and closely observing the data. These questions can come from initial wonderings, or as a result of previous data cycle.
> We "Consider Data" - by determining which parts of the data set we need to answer our question. Sometimes we don't have the data we need, so we conduct a survey, observe and record data, or find another existing dataset. 
> We "Analyze the Data" - by completing calculations, creating data displays, creating new tables, or filtering existing tables. The result of this step are calculations, patterns, and relationships. 
> We "Interpret the Data" - by answering our original question and summarizing the process we took and the results we found. Sometimes the data cycle ends here, but often these interpretations lead to new questions... and the cycle begins again.
>

**Comment by schanzer** [comment]
@flannery-denny I think this is an upgrade!

**Comment by flannery-denny** [comment]
@schanzer  What do you think about replacing this
<img width="823" alt="Screen Shot 2023-12-01 at 12 47 37 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/2d2716d2-2d82-439d-b0a9-1aaa33f340ed">

with this 

> Lookup questions: Answered by only reading the table, no further calculations are necessary! Once you find the value, you're done! Examples of lookup questions might be “How many legs does Felix have?” or "What species is Sheba?" (I would also argue here that a questions like "Who is the heaviest animal?" or "Who is the tarantula?" are both lookup or at least "reverse" lookup)
> Arithmetic questions: Answered by doing calculations with values from only one single column. Possible calculations you have to do are: comparing, averaging, or totaling. Examples of arithmetic questions might be “How much does the heaviest animal weigh?” or “What is the average age of animals from the shelter?”
> Statistical questions: Answered by doing calculations with values from multiple columns. These often involve multiple steps and numbers in order to answer the questions; these are not simple! Remember, statistics are numbers that represent a data set. So when we compare two statistics we are actually comparing two data sets. If we ask "are dogs heavier than cats?", we know that not every dog is heavier than every cat! We just want to know if it is generally true or generally false!

**Comment by schanzer** [comment]
@flannery-denny 

- **Lookup questions:** Answered by only reading the table, no further calculations are necessary! Once you find the value, you're done! Examples of lookup questions might be “How many legs does Felix have?” or "What species is Sheba?" 
- Arithmetic questions: Answered by doing calculations (comparing, averaging, totaling, etc.) with values from one single column. Examples of arithmetic questions might be “How much does the heaviest animal weigh?” or “What is the average age of animals from the shelter?”
- **Statistical questions:** These often involve multiple steps to answer, and the answer isn't black and white.When we compare two statistics we are actually comparing two data sets. If we ask "are dogs heavier than cats?", we know that not every dog is heavier than every cat! We just want to know if it is _generally_ true or _generally_ false!
- Questions we can’t answer: We might wonder where the animal shelter is located, or what time of year the data was gathered! But the data in the table won’t help us answer that question, so as Data Scientists we might need to do some research beyond the data. And if nothing turns up, we simply recognize that there are limits to what we can analyze.

**Comment by schanzer** [comment]
@flannery-denny Here are my proposed replacements:

- an expression containing a list of boolean-producing "questions" (known as conditions), and answers that are evaluated if the answer to the condition is `true`

- in contrast conventional functions that have a single "rule" used for every input in their domain, these functions divide their domain into "pieces" and use a different rule for each piece.

**Comment by schanzer** [comment]
@flannery-denny box-plots now contain the range and IQR!

**Comment by schanzer** [comment]
@flannery-denny I've updated the glossary definition for distribution -- I think Russell is right. 

I don't agree with his distinction between "sample size" and "number of samples". From everywhere I've looked, these seem to be the same thing.

That just leaves the "null hypothesis definition should be approachable" item, and I think the lesson currently introduces the vocabulary word using an extremely approachable example. If you agree, I think this issue is ready to close!

**Comment by flannery-denny** [comment]
@schanzer this wording is very clear

> Our assumption that there is no bias towards "heads" or "tails" is our null hypothesis.

but the glossary definition is not 

> the claim that there is no difference or relationship in the larger group(s) from which we sampled. For a single variable, this claims that a summary like the mean or proportions of a population equals a proposed value. For multiple variables, this claims that no relationship exists between those variables in the larger population

**Comment by schanzer** [comment]
@flannery-denny how about this:

The null hypothesis claims that in the larger population of interest, there is "nothing special going on": no difference from a proposed parameter (like mean or proportion), or no relationship between variables.

**Comment by flannery-denny** [comment]
@schanzer This definition still feels like it's in the clouds rather than
tailored to our students.  Are we going to do something with the null
hypothesis outside of this probability lesson?  We currently only reference
the null hypothesis in this one lesson, which doesn't connect it to mean or
proportion or variables, so it's confusing why you would be talking about
them. If you want to teach about all of that in this definition, I think
you're going to have to teach about it in the lesson.

Here are all of the current references in our curriculum:

   - In general, we assume that in the long run, an ordinary coin will land
   on "heads" 50% of the time. Our assumption that there is no bias towards
   "heads" or "tails" is our *null hypothesis*. A weighted coin, on the
   other hand, might be heavier on one side, creating a bias toward one side!
   And since we lose money on heads, we’re worried about bias in favor of
   heads.
   - In Statistics and Data Science, samples like these don't *prove*
   anything about the coins! Instead, they either produce enough evidence to
   reject the *null hypothesis*, or fail to do so. If the *null hypothesis*
   is actually false, larger samples give us a better chance of producing
   evidence to reject it.
   - Statisticians would explain this as follows:
     "If the* null hypothesis* were true, then the probability of getting
   sample results at least as extreme as the ones observed is 0.001."
     ...
     Statisticians use formal language to express the probability of
   obtaining sample results at least as extreme as the ones observed, under
   the assumption that the *null hypothesis *is true for the population.
   They call this probability a "p-value", and typically report it as a
   decimal.
   - Just like our coin-flip, we can start out with the *null hypothesis*:
   assuming that the vote is split equally. Flipping a coin 10 times isn't
   enough to infer whether it's weighted, and polling 10 people isn't enough
   to convince us that one candidate is in the lead. _But if we survey enough
   people_ we can be fairly confident in inferring something about the whole
   population.

**Comment by schanzer** [comment]
@flannery-denny I took a stab at simplifying Nancy's latest definition:

**Null Hypothesis** - The claim that “there's nothing special going on” in a population we are sampling. This claim could mean “the coin isn’t biased towards heads” In a sample of coin flips, or “breed has no impact on adoption time” in a sample of dogs. But if a sample of coin flips lands mostly on heads, or a sample of dogs found that one breed is usually adopted last, this could lead us to reject the null hypothesis.

--
As for where we use this -- once upon a time I had a whole section of the scatter plot lesson devoted to the null hypothesis, but cut it. Think we should bring it back? Here's the gist of it, below:

We start out assuming there is no relationship in a particular population, and that a scatter plot of every single person would have no pattern at all - just noise. But of course we can't see that scatterplot! All we can do is _sample_, creating a scatter plot as we attempt to measure trends in the real world. 

Suppose I select 2 samples. Since our samples are real too, each of these 2 points is also a point in the random noise plot. What are the chances that - maybe just maybe - I picked 2 points that fall in a straight line? 100%! Literally any two points define a line! :) 

But okay, suppose I selected 10 samples. Or 100. What are the chances they all fall in a straight line? Increasingly small, but technically not impossible. This is where p-value and null hypothesis come in: as the chances of randomly picking a line from noise get smaller and smaller, we are more and more likely to reject the null hypothesis.

-- 
We could do the same for measures of center, histograms, and box plots: if we assume species doesn't affect adoption time, then two box-plots of `weeks` for cats and dogs should be very similar. Ditto for mean, median, mode, etc.

**Comment by flannery-denny** [comment]
@schanzer I do actually think that this is interesting. Probably belongs in a pedagogy box so that it's there for those who are looking to deepen their understanding and be able to make connections between things, but not overwhelming to teachers of younger grades who are digging in for a lesson or two. That said, I don't think it's as much of a priority as getting AI into our curriculum for 2024, for example, so I'd suggest putting it on a DS wishlist.

**Comment by schanzer** [comment]
@flannery-denny sounds good. I've copy/pasted that text into the [DS wishlist issue](https://github.com/bootstrapworld/curriculum/issues/155). If you're happy with the revised definition, we can close out this issue!
