### ISSUE TITLE
Handouts are not being compiled/included in materials section of lessons live on the web.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1659]
I'm looking at [https://bootstrapworld.org/materials/fall2023/en-us/lessons/function-composition/index.shtml?pathway=algebra-pyret](https://bootstrapworld.org/materials/fall2023/en-us/lessons/function-composition/index.shtml?pathway=algebra-pyret)

I would expect the Function Card handout to be available by clicking the link that says "PDF of all handouts and pages 27-31", but it's not there. It also isn't anywhere else...

<img width="456" alt="Screen Shot 2023-11-27 at 4 47 23 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/738eda43-0cce-411e-b68e-c62cab38e28b">

The `adoc` says 

```
== Composing Functions @duration{10 minutes}
Students are given a scaffolded activity that forces them to use the output of one function as the input to another - to _compose_ them.

=== Launch
@teacher{
Divide students into groups of 3-4, and distribute a set of @handout{function-cards.adoc} to each group.
```

**Comment by ds26gte** [comment]
When you click the downward-facing triangle, a link for the handout is indeed  visible. The PDF itself doesn't contain the handout -- probably because handouts are not part of the PDF? (In which case the link text is a misnomer.)

**Comment by flannery-denny** [comment]
Interesting. And confusing.

**Comment by schanzer** [comment]
@flannery-denny the PDF contains the handout. Here's what I got just now, clicking your link:

[ac3cf5a8-c8d9-4f08-b3b9-874153ea6fbe.pdf](https://github.com/bootstrapworld/curriculum/files/13482805/ac3cf5a8-c8d9-4f08-b3b9-874153ea6fbe.pdf)

See the last page.

Are you getting something different?
