### ISSUE TITLE
List of allowable bin sizes for histograms

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1660]
A request came in from a teacher for a list of allowable bin sizes students can use for the histogram.  Can that list be added to the lesson page on histograms?
I know 1, 2, 5, 10, 20, 40, etc. work and numbers in-between cannot.  Might be nice to mention this in the lesson for teachers.

**Comment by schanzer** [comment]
@joystraub confirming you mean bin _sizes_, and not _number of bins_?

**Comment by joystraub** [comment]
Yes, the size of the bin that gets entered into the function.
