### ISSUE TITLE
alaskan flag starter file problems

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1663]
is this starter file supposed to contain all of the solutions? Right now, there is nothing at all for students to do.

I'm thinking there needs to be a hidden alaska-flag that produces an image of the flag, and then students actually work on their own to define alaska.

Q2 also asks students to describe the alaska flag before they've seen it. 

I would fix this if I knew how!

https://code.pyret.org/editor#share=1f3sX5IaNDKd3l6QFFblRHvyLFKVQXYvX

**Comment by flannery-denny** [comment]
@retabak I didn't intend for students to write code in this starter file. It was made for the purpose of engaging them with reading code and comments, and as an example of how defined values get used. Looking back at it, I think perhaps some of the comments should be rewritten. And it probably makes most sense as a file that is linked to from a page that students respond to questions on. I can tackle it.

**Comment by retabak** [comment]
That's good to know - it was not clear to me at all. Glad it will get a revamp!
