### ISSUE TITLE
"Out of date" materials banner

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1664]
- [x] On this [page](https://bootstrapworld.org/materials/fall2021/en-us/courses/algebra-pyret/), the "out of date" warning's hyperlink goes [here](https://www.bootstrapworld.org/materials), which produces "403 Forbidden." (screenshot below)
- [x] Same issue as above for fall2018
- [x] the blue hyperlink text (screenshot below - from fall2021) is too difficult to see / read
- [x] why don't we have the "Out of Date" warning on other out-of-date pages? I clicked a few (spring2022, spring2016, spring2020) and didn't see the warnings. (I did not click on each and every year's landing page. If you want me to, I can.)

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/7db6a818-0367-450c-b63e-4aef229cada7)

**Comment by schanzer** [comment]
@retabak I've changed the link color for fall2024, and gone back to older releases from 2021 onwards and changed that link color too. I've also fixed the issue you identified, that was causing some of the older releases to not show the outofdate warning.
