### ISSUE TITLE
Switch entire bar and pie chart to make use of expanded animals starter file

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1667]
- [x] update images
- [x] make a data cycle page that motivates use of each new chart type
- [x] add loud announcement about the fact that this lesson uses a dataset with way more animals

**Comment by flannery-denny** [comment]
@schanzer While using a larger dataset is really useful for understanding these displays, I have a slight nagging feeling that using the expanded animals file before the random sampling lesson undermines the fact that there are species that students didn’t even know existed until then…

**Comment by schanzer** [comment]
@flannery-denny You were the one who argued that our regular dataset is too small for multi/grouped bar charts. Sounds like we need to pick our poison. I defer to you on which one is best.

**Comment by flannery-denny** [comment]
Thanks @schanzer. I'm going to stick with the assertion that multi and stacked displays need the bigger dataset.

**Comment by flannery-denny** [comment]
@schanzer Please confirm that this data cycle page works for you (flagging a few things below). Close if you're satisfied.

[data-cycle-categorical.pdf](https://github.com/bootstrapworld/curriculum/files/13677532/data-cycle-categorical.pdf)

1. Does this work for you as something they will see before being introduced to the Data Cycle?
2. Does the title work for you?
3. Does the wording of the directions at the start of each data cycle make sense to you?
4. OK to let them choose the variable for the second question or would it make more sense to predefine it? 
5. Would you agree that the first question is arithmetic and the second is statistical?
6. Ok to leave sentence stems off of this one or would you rather see this split into two pages, each with sentence stems?

**Comment by schanzer** [comment]
@flannery-denny 
1. I _think_ so. Something about it still feels weird, but I know we've talked it over and agree to move ahead on this
2. Yes
3. It wasn't clear to me that the first set of instruction was for the _whole page_ until I got to the second half. I think this could be clearer
4. This early? I'd give them a second variable. We can always point teachers to the Blank Data Cycles if they want kids to have more autonomy
5. No - both are arithmetic
6. I'd like to see the sentence stems added

**Comment by flannery-denny** [comment]
@schanzer Wondering if perhaps it makes sense not to title the data cycle for this lesson Data Cycle. Does this work for you? If so, I think I'll make a second of these pages for this lesson that asks them to make a multi-bar-chart and then asks them pick one of their other questions to investigate for the fourth.
[data-cycle-fixed.pdf](https://github.com/bootstrapworld/curriculum/files/13688314/data-cycle-fixed.pdf)

**Comment by flannery-denny** [comment]
@schanzer after building the lesson and/or checking out all of today's commits, close if you're satisfied

**Comment by schanzer** [comment]
@flannery-denny this looks great. Nice work!
