### ISSUE TITLE
flags project / flags lesson tweaking

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1673]
Flannery feels like flags are a cornerstone of our curriculum (I agree) and she wants everyone to be exposed to it! She doesn't want teachers to skip it because they don't think they have time for a project. (Projects are generally considered a thing you maybe are gonna do, but maybe you won't.)

We have a proposal for the fate of Flags! In fall2024, I would like to do the following:

- [x] "Putting Images Together" (currently section 1 of Flags) becomes its own lesson
- [x] add Puerto Rico starter to be a required activity in "Putting Images Together" to lengthen the lesson and also give kids exposure to a more interesting flag (we think the awesome starter files are probably sadly glossed over currently)
- [x] "Making Flags" (currently section 2 of Flags) becomes its own lesson, to be titled "Project: Make a Flag"
- [x] RT can tweak wording and lesson table in "Making Flags" to be a bit more aligned with the other project-lessons (e.g., explain when a teacher might introduce the project, explain potential variations to the project, etc etc.)

@schanzer - we wanted to see how you feel about this. LMK.

**Comment by schanzer** [comment]
I love it
![image](https://github.com/bootstrapworld/curriculum/assets/77126/402798b0-68d9-4614-8fc9-261bf641bfb7)
