### ISSUE TITLE
DS recs for 2025

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1674]
For 2025:
- [ ] It would be useful to have a visual representation of the median. Even if it’s just a depiction of students lined up by height with a line dividing them into halves. 
- [ ] show datasets with the same range but different IQRs to emphasize the need for more sophisticated measures of spread than just range. 
- [ ] Reach out to [press@ctbuh.org.](mailto:press@ctbuh.org) re permission to use [this image](https://images.adsttc.com/media/images/55e8/8ceb/6c9d/b57a/9900/000f/newsletter/diagram_tallestskyline_cctbuh.jpg?1441303781) 
- [ ] Making Box Plots - Launch (slide 2): instead of just telling students, they could observe multiple graphs that all have the same center, but different spreads. (This could be used as a way to reinforce sample size, the graphs could be from the same population but different samples of size 10, 20, and 100). 
- [ ] Interpreting Box Plots (whole lesson): students only had to make ONE box-plot this entire lesson prior to the optional project and the data exploration project. That is a shame. It would be better, to have an activity like “Identifying shape - box plots” where instead of pre-made box plots, students were given the column to use in a data set and then had to determine shape from their own box plots. It would be EXTRA GREAT, if there was an example were it was hard to tell shape, like if the left whisker and right half of box were both quite long (so then students would hopefully look at the histogram to see if that had a more clear shape).
- [ ] [Data Cycle](https://docs.google.com/document/d/10w7OPRQGi_hH-oglpwRrYsrQ82XGk_wV_Eo4iFFfBNI/edit) - 

> OVERALL: I think this lesson needs to be refocused. The activities in this lesson well exceed the times given and in my opinion the focus on the question types detract from the Data Cycle. Another way to include those back in and for them to be actually helpful to students, would be to provide sentence stems for each type of question. That way there's less ambiguity and more structure for how to ask the question types (if students still feel that they are arbitrary). If that is provided elsewhere, I don't believe it is linked anywhere on the lesson plan.
- [ ] [Standard Deviation](https://docs.google.com/document/d/1t-cWurdcMBtI2ELhmkyvARQgI9ndPyL7rzJzmOIHsyM/edit) - lots of heavy assertions here need @schanzer to weigh in
- [ ] Probability Inference Sample - consider rewriting the How to Spot a Scam section, which has been flagged as
quite high level and unapproachable, especially if students have minimal probability background.

**Comment by flannery-denny** [comment]
Since Russell owns the files through a school account that may not be live when we get to working on this in the future I am copying the suggestions from the linked files above here.

**DATA CYCLE**
- [ ] I am still uncomfortable with the ASK QUESTIONS section. The whole point of going over this with students and asking them to categorize questions in this lesson should be to get students to know what their next step is in the data cycle. After that, the point is for them to see that there are different types of questions that require different data, and some questions are outside the scope of the given data set. The way the definitions are given in this lesson originally and in my edits might still bog students down with the vocabulary instead of the bigger takeaway. Lots of clarifying questions and arguments can unfold since this just aren't clearly (or purposefully) explained here. Examples: Finding the "average" is a statistical question since the average is a statistic. You aren't doing arithmetic (add, subtract, multiple, divide) to find the heaviest, and so-on. I think a better alternative to this ENTIRE SECTION would be to have students focus in on identifying what the question is asking them TO DO: read (the table), simple compare (aka, using values in the same column), complex compare (aka using values across different columns), calculate (a specific value or statistic), infer (predict value, or use what they think the best value is), or contextualize (related to the metadata). Refocusing this lesson to this would not only get rid of some of the issues with the definitions and frustrations felt during the training, but it is more focused on what students have to DO after identifying the question type.
- [ ] Ask Questions - Investigate & Consider Data - Investigate - Which Question Type worksheet: The column "Column(s)?" should be "Which Column(s)?" for clarity. Wartotle is spelled incorrectly in the solution for #3. #4 should be reworded to "What is the mean of all of the defense scores?" (see my comments below). It's unclear to me why #2 and #11 have different solutions. Even when thinking about the code further into the year, the filter function needs access to all the rows (and the speed column) to find the rows with speed=43. I just don't get the specification here of "rows where speed=43" for any purpose besides being pedantic. The computer needs all the rows initially to do this filter, just like in #2. We also need the speed column. (AND why don't we need the name column for #2 like #11?) Related, #11 should be Lookup since there is no arithmetics happening since comparison is not arithmetic (the way arithmetic is taught to primary and secondary students, and how it's understood to most people). Again, these ill-defined vocabulary terms for Question Types are getting in the way of the point: students need to know what their next step in the Data Cycle is going to be! 
- [ ] Ask Questions - Common Misconceptions/Slide 9 Footnotes: Students might struggle with asking statistical questions since the definition of Statistical Questions hasn't been given. Even the notes here are confusing. In statistics, it's stressed that "average" can imply mean, median, or mode. Average just means typical, before HS usually students know mean as the only average. Instead of the way it's worded now, I would encourage my edit above to avoid this completely. Again, if we stress WHAT the question is asking you to do, then students can choose what they want to do and then ask the question that does that. Seems like we are asking students to figure out HOW the question is asked, instead of WHAT the question is asking. (Example: if a student wants to "complex compare" between cats and dogs, they will know that they have to choose a column to do this and could ask "Which are more likely to be fixed, dogs or cats?") It gives more structure to the question asking process that the 3 labels (and 2 definitions) do not. To stress again, I find the description of average here factually incorrect and that should be addressed if no bigger change is made. 
- [ ] Ask Questions - Synthesize: It's hard to come up with complex questions about data sets we haven't seen. The third bullet point of this section just seems so difficult for students to start. There are just so many students that students have to think about in order to get a response. Like what subsets do we have in these data sets, what columns might we have, what is actually interesting to me, what is actually interesting to the class, etc... An alternative could be: What statistical questions would you wish I asked as your teacher using the data I already know about you or from our gradebook? It's more approachable, it's more limited in scope, and it can open up some more future conversations about equity and inclusion. This third question might be better placed after the next section after students get more comfortable with identifying rows and columns that are needed for different questions.
- [ ] Consider Data - Launch: I think it would be useful here to include language around subsets for which rows are needed. A question like the following would be useful to include in the 4th paragraph of this section: "Do we need all of the rows of the data set, a subset (a specific amount of rows related somehow), or just 1 (or a few) rows that we can name before we start?"
- [ ] Consider Data - Launch: For the row explanation, it might be hard for students to visualize what this data set looks like to realize that "particular time" is an individual and not a characteristic. Instead, it would be nice to at least first describe what the rows are in the Animal Data Set. Then to provide a SECOND example that still could be this temperature example, or about something else that is easier to relate to when learning the definition (like the sport team in a sport team database, the pokemon in the pokemon database, etc.)
- [ ] Consider Data - Launch: Again, in the examples provided, it would add clarity to just used the word subset so students can start building that knowledge.
- [ ] Consider Data - Launch: Is there a reason why the material uses "what" columns instead of "which" columns during this section (and on slide 14)? 
- [ ] Consider Data - Launch: Examples (and slide 14), it feels weird to have the past tense as the 3rd example. I would suggest putting it first.
- [ ] Consider Data - Investigate - Data Cycle:Consider Data worksheet: It's awkward that the "Question Type" field is at the right, it makes it easy to miss for students that didn't read/hear the instructions. I would suggest putting it on the left before the question, or left of the "what rows" and "what columns" fields.
- [ ] Consider Data - Investigate - Data Cycle:Consider Data worksheet: Again, is there a reason why it's written "what rows" and "what columns" instead of "which rows" and "which columns"?
- [ ] Consider Data - Investigate - Data Cycle:Consider Data worksheet: I'm confused why the solution is "any column / all columns" for the second question when we do at some point during the answering process need the "species" column. This kind of answer just doesn't match the level of understanding students are at this early in the process (they haven't been introduced to filters yet). It also implies that students understand that we have a subset of just dogs that we're counting, and a separate subset of just cats that we're counting (aka we can use any column to count as long as we have these 2 separate subsets). This would be very difficult for a teacher to explain to students (or for teachers to agree upon what the correct answer is...)
- [ ] Consider Data - Investigate - Data Cycle:Consider Data worksheet: It would be nice to provide teachers with some questions to give students if that kind of scaffolding is necessary, especially considering questions that students might come up with might not have as much nuance or complexity as ones experts come up with that challenge their understanding on this standard. 
- [ ] Consider Data - Common Misconceptions (Slide 15 footnotes): Extra explanation of why then #12 (Which Question Type? worksheet) isn't also "all rows" is needed here to assist teachers.Analyzing Data - Overview: a space is needed between "step" and "with"

- [ ] Analyzing Data - Investigate - Data Cycle:Analyzing with Displays worksheet: the second example should require a different amount of rows than all. That way students can see possible solutions. If they can't do that at this point, it seems like that should be addressed to the teacher in the slide footnotes and on the lesson plan. 

- [ ] Analyzing Data - Investigate - Data Cycle:Analyzing with Displays worksheet: Again, as a scaffold some questions should be provided to the teacher so students who are struggling to come up with their own can get a quick question. (I don't think the question asking is the focus of this worksheet...)

**Comment by schanzer** [comment]
@flannery-denny once #1956 lands, can you check off the items here that are addressed, and move any un-addressed items into #155?

**Comment by flannery-denny** [comment]
all remaining issues moved to #155
