### ISSUE TITLE
Flesh out teaching about shape from box plots on fall2024

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1675]
In addressing #1658 on fall2024, I've cut a bunch of words from the second section of the lesson that weren't accomplishing much. Now that the section is pared back to its essence, it's obvious that we're not teaching much about shape at all!

At a minimum we need to
- [x] provide examples of skew before students are working independently
- [x] teach about symmetry

But I imagine we should also be teaching about 
- [ ] how the iqr relates to the range
- [ ] where the median falls

ES - asking you to either flesh out the spec of what you think the scope of the section should be or take a stab at editing the text yourself.

**Comment by flannery-denny** [comment]
@schanzer I think this is a significant improvement. I wonder about describing symmetric and even distribution in box plots and whether we need to call them "apparent" in that the box plot could be symmetric even if the data isn't fully? I defer to you. Close if you're satisfied.

**Comment by schanzer** [comment]
@flannery-denny this is definitely a major upgrade. I think the language being used is sufficient, but I'll ask Nancy Pfenning for a second opinion
