### ISSUE TITLE
Slide conversion of asciidoc tables

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1677]
md2googleslides is already terrible at handling tables due to Google's limited API. Add the fact that Markdown tables look completely different than AsciiDoc tables and this was bound to break when we tried to automate.

@ds26gte created the @table directive for slides.md files, which we used to write by hand until now. But now that we don't edit those files anymore, we need to do this conversion automatically.

Two options present:
1. Upgrade the `@table` directive to be expressive enough to replace the asciidoc version, then replace every table in every lesson with the upgraded directive. That's a ton of error-prone work.
2. Automatically convert asciidoc tables to `@table` when generated the .md file, stripping out all the stuff markdown can't handle.

Option 2 seems _vastly_ better.

The tricky part is detecting when a table has a header or not, but that doesn't seem insurmountable

**Comment by schanzer** [comment]
@ds26gte can you provide an example of how to use this directive in one of the sample lessons?

**Comment by ds26gte** [comment]
I've taken out the no-op `@table` kludge.

So, `make-slides.lua` now analyses the information in the `[...cols...]` line to figure out 
- number of columns
- if the table needs a header

and inserts the appropriate `@table{...}` line in `zlides.md`.

`@table` is no longer a valid directive for our AsciiDoc source.

Note that some AsciiDoc tables may still be too much for zlides, especially those with big table cells containing multiple blocks and enumerations. In such cases, you may want to use the provided `@ifslide` and `@ifnotslide` directives to write tables separately for the two intended outputs, but you only need to do it in these extreme cases.

**Comment by schanzer** [comment]
@ds26gte this is _fantastic!_ Thanks for putting in the time to tackle it -- I think it's a vastly smoother ride.
