### ISSUE TITLE
Improve scaffolding around Piecewise functions in Advanced Displays

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1678]
Improve teacher notes and possibly error messages for [piecewise displays starter file](https://code.pyret.org/editor#share=1XK78l3FOYzmKPWrYmYBMUumvEWtwN03b)

> when I “turned off” line 45, per the directions on 
> [piecewise-explore.pdf](https://github.com/bootstrapworld/curriculum/files/13529445/piecewise-explore.pdf)
> I got an error message since the snails didn’t fall into any of the conditions. 
> 
> Was that what was supposed to happen? Since there aren’t any teacher notes about this in the slides, lesson plan, or solutions I’m unsure what the student take-away here is.
> 
> Is the conditional piecewise function explored more later on? In this example there is no “else:” shown. I feel like that is a HUGE component of conditionals that could have been highlighted easily here to show what to do if you only care about cats and dogs, but want everything else to be all the same color.
>

**Comment by schanzer** [comment]
@flannery-denny see recent commit

**Comment by flannery-denny** [comment]
Thanks @schanzer. 
- Want to offer any further explanation about the error in the lesson plan?
- Want to address or ignore his request for adding "else" to this starter file?

**Comment by schanzer** [comment]
@flannery-denny done!
