### ISSUE TITLE
Slide audit

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1679]
**Depends on #1864**

Teacher feedback includes requests to
- [x] make sure images of graphs are big enough
- [x] make sure text fits on the slide
- [x] make sure every lesson section has a synthesize slide
- [x] make sure slides are set to viewable by everyone!

**Comment by schanzer** [comment]
@flannery-denny I don't see this as an issue in its own right -- these are things we already have to do do when we generate slides. How is this different from the slide tracking issue(s) we already have?

**Comment by flannery-denny** [comment]
@schanzer All of these mistakes exist in our current slides because there wasn't a checklist of things to look for when they were reviewed, even though people theoretically know that they have to happen.  We need to keep lists of the things that we are supposed to audit for so that we are reminded of the process when the time comes. I have added the issue for the June 1 milestone. And have had to add to it as I continued working today. If you have another place where you would like me to make this list, please let me know where it is.

**Comment by schanzer** [comment]
@flannery-denny This feels like it belongs in #1669

**Comment by schanzer** [comment]
Slides are done, and this audit was part of that work. Closing!
