### ISSUE TITLE
Compiled PDFs linked from lesson materials section don't have the right page numbers

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1680]
As noted by a teacher re: the [data cycle lesson](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/data-cycle/index.shtml?pathway=data-science)
The pages in the pdf are numbered 1-4
The pages in the workbook he's using with students are 6, 8, 23, 25.

**Comment by flannery-denny** [comment]
Only if the teacher is actually working with a workbook. For teachers working without workbooks having pages for a lesson numbered 6,8, 23, and 25 would be pretty confusing. 

And both of said teachers would be accessing the lesson through the same pathway so it's  hard to make the use cases match. 

I vote no page numbers - all of the pages have very clear titles. But you are welcome to add it to next week's curriculum team meeting for discussion.

**Comment by schanzer** [comment]
@flannery-denny the reasoning in your first comment doesn't make sense to me. If you're teaching without a workbook and you really don't want page numbers, then we should get rid of page numbers from all of our lesson plans.

And if they aren't annoying in the lesson plan, then they won't be annoying on the printed PDF.

The page numbers stay. I've updated the issue title accordingly.

**Comment by flannery-denny** [comment]
No objections. The reason I originally suggested getting rid of them is that this is not the first time that they've been flagged as wrong.
