### ISSUE TITLE
@indented directive?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1684]
The one `[. `] I find myself still using is `[.indentedpara]` . 

It gets used in so many different ways that I think if we want to replace it with `@indented{}` it probably needs to be able to work inside of other directives. 

There are tons of examples if you do a search in sublime. 

It mostly gets used 
- for code blocks
- for notes among lists of questions
- for subsets of directions that are tables
- or subsets of directions that are bulleted lists
- because it works in some places that `@hspace{}` does not. For example you can't put `@hspace{}` in front of a bullet, but you can use `[.indentedpara]` around an entire bulleted list.

**Comment by schanzer** [comment]
Thanks, @flannery-denny . This is really helpful, and definitely justifies a maximally-permissible directive. @ds26gte can you add `@indent{...}` with the same parsing characteristics as `@teacher{...}`?
