### ISSUE TITLE
Errors in answer key Effects of an Outlier DS Workbook page

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1692]
Effects of an Outlier workbook solution page has the following errors:
7)  should be 207.6 (not 304) for the sum of the squares
8) should then be 20.76 (not 30.4) when dividing by N-1
9) should be be ~4.56 (not 5.83) for the standard deviation
(errors reported by Justin Meyer a Utah participant.  I calculated the math to get the numbers above)

**Comment by schanzer** [comment]
closed by 8c43573a
