### ISSUE TITLE
Add interpretation stems for many other displays

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1697]
https://docs.google.com/document/d/1nIX8Um9mtx9FqJqfs3C-mceVfULTOJPgAPfgAaECAYQ/edit

- [x] Histogram: ~Describe shape, center, and possible outliers in context, and spread (variability) (SOCS).~ 
Shape: The shape of the histogram is _____(skewed left, skewed right, symmetric, bi-modal, multi-modal, uniform). There are peaks at ____ and gaps at _____. This shape tells me ____. 
Outliers: There are potential outliers at ______ OR There do not appear to be any outliers.

~Center & Spread (Variability): 
Median & IQR
Mean & Standard deviation
More on Measures of Center: “Since the mean is ____________ compared to the median, this suggests the shape of the distribution is ______________________.~
_added this to summary pages_

- [x] More on Spread: Box Plot: “The box plot for x-variable in context is shape.  The 5-number summary of x-variable in context is min=____, Q1=____, median=____, Q3=____, max=____.   
IQR: The middle 50% of the data lies between ______ and ______ and has an IQR of _____.  
Consider statements like:  75% of the data fall below ________ OR The top 25% of the data fall between ___ & ____.
 
~More on Spread: Standard Deviation: “The column(variable name) typically varies by SD from the mean of mean”.  A majority of the column (variable name) data will typically occur between one SD below  and one SD above the mean of mean.~ _ignore_ 

- [x] Pie chart: The pie chart shows _______________. I noticed that ____. 
Consider statements like: There is an even distribution of _________ OR _________ was the most frequent response at ______%.

- [x] Bar chart: The bar chart shows _____________.  I noticed that _______.
Consider statements like:  There are # more/less  value of the variable than another value of the variable.  

- [x] Scatterplot:  ~Correlation - DUFS (Direction, Unusual Points, Form, Strength)~
There appears to be a ________________ (strong, weak, moderate), _____________ (positive, negative, no) _____________ (linear, non-linear) relationship between x-variable and y-variable.  Some possible outliers can be _____________. 

~Linear regression: I performed a linear regression on a sample of (dataset or subset) and found a (weak/strong/moderate (R=... positive/negative) correlation between (x-variable) and (y-variable). I would predict that a 1 (x-axis units) increase in (x-axis) is associated with a (slope, y-units) (increase/decrease) in (y-axis).  When there is 0 x in context, it’s estimated that there will be y-in context.
***  This is the narrative now used with the addition of interpreting the y-intercept - a must in AP Stats.~

**Comment by flannery-denny** [comment]
@schanzer 
I'm seeing the proposal for us to add the final sentence on interpreting the y-intercept - a must in AP Stats. 

> Linear regression: I performed a linear regression on a sample of (dataset or subset) and found a (weak/strong/moderate (R=... positive/negative) correlation between (x-variable) and (y-variable). I would predict that a 1 (x-axis units) increase in (x-axis) is associated with a (slope, y-units) (increase/decrease) in (y-axis).  **When there is 0 x in context, it’s estimated that there will be y-in context.**

Checking in as to whether you really want me to add that.  This is a generic scaffolding to be used with lots of different datasets and we emphasize that it doesn't make sense to infer things that are outside of the sample range. 

On the example page we already have in the correlations lesson, we would have to write something like.

> It is estimated that if the animal is 0 years old it would take 2.3 weeks to be adopted.

Thoughts?

**Comment by schanzer** [comment]
@flannery-denny yeah, let's not add that

**Comment by flannery-denny** [comment]
@schanzer Slowed down on this because the path forward became less clear. Wondering how committed you are to incorporating all of this and if there might be some you'd rather just cross off the list.

1. We currently have a data cycle that give students a choice between boxplots and histograms. Assuming it's ok to narrow the focus to incorporate this feedback?
2. Not sure what to do with the feedback on measures of center. 
-- The current data cycle pages in measures of center proscribe the questions that students will think about. Do you want me to make additional Data Cycle pages that make use of this feedback.
-- We just rewrote the Summarizing Columns pages, but perhaps this feedback could somehow be incorporated on those pages.
3. The standard deviation data cycles currently have the following scaffold. Should I replace it with the suggestions?

> Turn the Data Cycle above into a Data Story, which answers the question __"If the average adoption time is 5.75 weeks, do all the animals get adopted in roughly 4-6 weeks?"__

4. Do you have thoughts on where in the Curriculum we might offer up the ideas listed under General Observations?

**Comment by schanzer** [comment]
@flannery-denny 

1. totally ok
2a. I think additional (optional) DC makes sense
2b. I like this idea - would love to see what you do with it?
3. I'm inclined to leave it as proscriptive, but not married to it
4. Punt to post-Jan (not in workbook)
