### ISSUE TITLE
switch default ordering of stacked and multi bar charts to alphabetical

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1700]
Our bar charts are sorted alphabetically, but our stacked and multi bar charts are not.

I don't love that all of the hermaphrodites are clustered at the front of these displays and, in my experience, students need to be able to engage with data displays that aren't presorted like this for them. 

I also think it could generate some misconceptions if the order of the stacked bar charts seems to give away which population is smallest or largest.

Strongly recommend switching to alphabetical ordering unless you have a strong objection - in which case I am excited to hear your thinking! 
![image](https://github.com/bootstrapworld/curriculum/assets/66691020/c85b25c3-1a12-425e-b7ed-0881eaddcf9d)
![image](https://github.com/bootstrapworld/curriculum/assets/66691020/46be8bb3-b5e5-4e4e-87f1-dd746e82dfe8)

Also curious whether there could be a way for students to have control over how the table is sorted? Like the sorting would be based on how they sorted the table?

While images are included in the lesson plan, they aren't included in the workbook, so this could wait until after Jan 1.

**Comment by schanzer** [comment]
@flannery-denny groups are now alphabetized for the fall2024 library.

Having students choose their own sorting mechanism is a non-starter.

**Comment by flannery-denny** [comment]
Thanks!
