### ISSUE TITLE
add @define{varname}{... text ...}

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1701]
```
@define{varname}{... text ...}  and then be able to refer to this text via the dynamically created directive @varname. Then
@ifnotslide{@varname}
@ifslide{@teacher{@varname}}
```
to avoid need for duplicative text for lesson plan stuff that doesn't belong in @teacher but also doesn't belong on a slide. 
eg.

> @ifnotslide{When you first build a bar chart or pie chart in pyret, they are interactive displays. That means that you can mouse over a bar to reveal the label, as well as the number of animals in that species. We can also resize the window by dragging its borders. This allows us to experiment with the data before closing the window and generating the final, non-interactive image.}
> 
> @ifslide{
> @teacher{When you first build a bar chart or pie chart in pyret, they are interactive displays. That means that you can mouse over a bar to reveal the label, as well as the number of animals in that species. We can also resize the window by dragging its borders. This allows us to experiment with the data before closing the window and generating the final, non-interactive image.}

**Comment by schanzer** [comment]
@flannery-denny if it's deployed, is there more work this issue needs to be closed?

**Comment by flannery-denny** [comment]
@schanzer @ds26gte Until slides are buildable it’s impossible to weigh in on whether it’s doing what it’s supposed to. Assuming neither of you are able to build slides, either?On Dec 13, 2023, at 3:00 PM, Emmanuel Schanzer ***@***.***> wrote:﻿
@flannery-denny if it's deployed, is there more work this issue needs to be closed?

**Comment by flannery-denny** [comment]
I don't know how to see the slides, but it looks right in `zlides.md` :)
Thanks for your quick turnaround on designing and implementing this @ds26gte !
