### ISSUE TITLE
Make `zlides-pyret.html` file in lesson distribution on `fall2024` so authors can see how the markdown file translates

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1708]

**Comment by flannery-denny** [comment]
@schanzer is there a good reason to keep `slides.md` and `slides-pyret.html` files on `fall2024`

**Comment by schanzer** [comment]
@flannery-denny The value is being able to compare the auto-generated output to the handmade output, but an author could also just view the `slides.md` file on Github. Is the presence of those files a problem for you? If so, I'm comfortable deleting them

**Comment by schanzer** [comment]
@flannery-denny You already have this file!

 `slides-pyret.html` will _always_ be updated with the most-recently generated deck, whether that is done using `./build-slide <lesson-name>` or `./build-slide -z <lesson-name>`
