### ISSUE TITLE
stacked and multi-bar charts should be ordered numerically as bar chart is rather than by first digits 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1711]
<img width="682" alt="Screen Shot 2023-12-15 at 12 37 15 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0620b866-f3c2-42d5-8f42-bbf2958aa112">
<img width="678" alt="Screen Shot 2023-12-15 at 12 02 50 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/db910e89-963d-4d26-98ce-c5fa51b53d2b">

These are sorted by their first digit:
1, 10, 11, 12, 13…
2, 24…
3, 30…

**Comment by schanzer** [comment]
@flannery-denny I've updated the library for fall2024 to use more intelligent sorting. Close if you're happy?
