### ISSUE TITLE
Refine/Update Slide Building Infrastructure

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1714]
- [x] bootstrapworld/md2googleslides#23
- [x] bootstrapworld/curriculum#1915 
- [x] bootstrapworld/curriculum#1903 
- [x] bootstrapworld/curriculum#1922
- [x] bootstrapworld/curriculum#1918 
- [x] bootstrapworld/curriculum#1917
- [x] bootstrapworld/curriculum#1916 
- [x] bootstrapworld/curriculum#1914
- [x] bootstrapworld/curriculum#1910
- [x] bootstrapworld/curriculum#1908
- [x] bootstrapworld/curriculum#1907
- [x] bootstrapworld/curriculum#1905
- [x] bootstrapworld/curriculum#1904 
- [x] bootstrapworld/curriculum#1902 
- [x] bootstrapworld/curriculum#1901
- [x] bootstrapworld/curriculum#1767 
- [x] bootstrapworld/curriculum#1849
- [x] bootstrapworld/curriculum#1858
- [x] bootstrapworld/curriculum#1861 
- [x] bootstrapworld/curriculum#1859 
- [x] bootstrapworld/curriculum#1856 
- [x] bootstrapworld/curriculum#1852 
- [x] bootstrapworld/curriculum#1845 
- [x] bootstrapworld/curriculum#1841
- [x] bootstrapworld/curriculum#1836
- [x] bootstrapworld/curriculum#1833
- [x] bootstrapworld/curriculum#1806 
- [x] bootstrapworld/curriculum#1805
- [x] bootstrapworld/curriculum#1807
- [x] bootstrapworld/curriculum#1804
- [x] bootstrapworld/curriculum#1803 
- [x] bootstrapworld/curriculum#1802 
- [x] bootstrapworld/curriculum#1794 
- [x] bootstrapworld/curriculum#1771 
- [x] bootstrapworld/curriculum#1778 
- [x] bootstrapworld/curriculum#1779
- [x] bootstrapworld/curriculum#1777 
- [x] bootstrapworld/curriculum#1775 
- [x] bootstrapworld/curriculum#1776 
- [x] bootstrapworld/curriculum#1780
- [x] ~Numbered lists should not restart from 1 just because a non-list item interrupts them~
- [x] escape carets so as not to trigger inline_html parsing (for example, List<Number> should be `&lt;Number&gt;`)
- [x] In lessons `__text__` renders as italicized. It should do the same in slides, but is currently rendering as bold.
- [x] ~support for `@lesson-roleplay` (pending design discussion on Tuesday)~ -> that directive will be 100% student-facing, so no slide support is needed
- [x] GSlides cannot handle tables containing non-text content (e.g. - images, COEs). Could we instead generate HTML equivalent to a web page containing these tables, and then use `$$$ html` to force an image out of them, like we do for COEs? If not, can we instead get a commandline warning that the whole table will need to be manually translated?
_You will know you have succeeded if we can build the table at the end of Bar and Pie Charts._
- [x] If a slide from the Investigate sections contains 2 images, please use layout Investigate2 (We don't seem to have 2 images per slide in other lesson sections)
_There is an example in bar and pie charts_
- [x] auto-sizing is WAY too conservative (multiple slides have this problem)
- [x] In the Choosing Your Dataset lesson, `@include{fragments/dataset-table.adoc}` renders as `@include` rather than as the table. I assume there will be other fragments that will have similar issues.  For this specific case, I'm not sure the table will fit, but it would be nice to be able to link to the table from the slide. Perhaps we could use something like @ifslide{@lesson-link/choosing-your-dataset/dataset-table} - @ds26gte can we issue a warning when we see an 
- [x] `Unable to generate slides: Error: detected an html fence with no html inside` (Order of Operations Lesson)
- [x] Can there be a way to shrink the font size of some lesson section titles? One of the lessons I just build slides for had two lesson section titles that did not fit onto the top of the slide deck, so I had to reduce the font size manually on the majority of slide titles.
- [x] Using `@table` on rich tables (from Equivalence lesson in Early Math),  `@table` appeared in the lesson.
- [x] bootstrapworld/curriculum#1782
- [x] `@big`

**Things we can't/won't do**
-  Is there a way to indicate whether a deck in Projects belongs to Algebra or DS? If not, can there be?
-  I'm 99% certain this is impossible, but am gonna ask anyhow: Is there a way to automatically make the slide decks viewable to anyone with the link? (The default is that everything is editable by anyone at bootstrap, I think.) I have led early summer PD where all slide decks are not viewable to anyone... embarrassing! It would be nice if we didn't need to remember to change this setting manually.

**Comment by schanzer** [comment]
@retabak we have to share slides manually, but this shouldn't be hard! Just select all the slide decks at once and modify the sharing settings.

**Comment by schanzer** [comment]
@retabak I spent most of today working on auto-fitting text. Please don't get too excited: this will _never_ be perfect, but the hope is that it will be "good enough" to work for 90% of use-cases.

Fortunately, a simpler form of auto-fitting is "auto-fit a single line", which happens to be exactly how titles work. I updated md2googleslides [in this commit](https://github.com/bootstrapworld/md2googleslides/commit/bd189369e1bf95955897601e41bcd7af676225d3) to do exactly that, and tested it with `associative-property` to confirm that it works. I need to update our master template so that every title placeholder has a consistent font size. Right now they don't, so you may find some wonky title sizes until that's complete.

Hopefully this work can be generalized across multi-line text blocks, so an entire slide body's worth of text can be nudged a few sizes down to make things fit.

**Comment by retabak** [comment]
omg, I had no idea you could change sharing settings of multiple slide decks at a time.

**Comment by retabak** [comment]
Re: auto-resizing...

Font size is occasionally being needlessly reduced.  Both examples below are on identity-prop branch + identity-property slides.

- [ ] Text wrapped in @ifnotslide{} - in this case, a table - seems to be adding to the slide word count, triggering font size reduction. The font size below was reduced to 13.5, even though everything would fit properly using size 16.

```
@slidebreak

Or like this:

@ifnotslide{
[.embedded, cols="^.^3,^.^1,^.^3", grid="none", stripes="none" frame="none"]
|===
|@show{(coe '(+ 3 q))}	| @math{=} | @show{(coe '(+ 0 (+ 3 q)))}
| @math{3 + q} 			| @math{=} | @math{0 + (3 + q)}
|===
}

The Identity Property will hold no matter what values we substitute in for @math{q} or for @math{t}. Although computation can help us test equivalence, there's no way to test every possible value. The Identity Property lets us prove that these expressions are equivalent _even with variables_.
```

- [ ] Text that wrapped in @A{} (as part of @QandA) seems to be adding to the slide word count and triggering font size reduction, along with text wrapped in @teacher{}. The font size below was reduced to 12, even though everything would fit properly using a font size of 16.

```
@slidebreak

@QandA{
@Q{What do you Notice? What do you Wonder?}
@A{Possible responses: All three Circles include @math{12 + 4}. All three Circles evaluate to @math{16}.}
}

@lesson-instruction{
- Study the counter-examples in Q2. Explain why each Circle of Evaluation does *not* represent the Identity Property.
- Complete the page by filling in the blanks in Q3 so that the value of the Circles of Evaluation does not change.
}

@QandA{
@Q{What did you observe about the Identity Property for division? Subtraction?}
@A{Possible responses: I can multiply or divide by @math{1} and get an equivalent result. I can add or subtract @math{0} and get an equivalent result. I need to remember that Commutativity does not apply for division and subtraction!}
}

@teacher{Confirm that students understand the main idea about the Identity Property:}

@lesson-point{
Multiplying or dividing an expression by 1 does not change its value; similarly, adding or subtracting 0 results in the original value.
}

@teacher{Students will apply this knowledge throughout the lesson.}

=== Investigate

```

**Comment by schanzer** [comment]
@retabak I just built the slide deck for `identity-property` on my machine, and [here's the result](https://docs.google.com/presentation/d/1liSYLPO6RbaWWZtlR1ikC2NnfO3Z2HdLXuu61h8HCpY/edit#slide=id.1048ca97-b150-11ee-a3e1-9dfc5a090857).  I'm not seeing that slide with text of size 13.5pt.

md2googleslides never sees anything inside @ifnotslide, and it never uses @A{} text when calculating size. List bullets are incredibly hard to estimate, but I'll see if I can improve it next week

**Comment by schanzer** [comment]
@flannery-denny and @retabak I updated md2googleslides to disallow text from shrinking below 12pt. This should mostly fix the situations where slides where you're seeing the text get too small, though please do continue to send me bug reports

**Comment by schanzer** [comment]
Posting @flannery-denny 's comment from above for historical purposes:

Number in slides should work as it does in lessons - currently resets when there's a break from rebulleting (Here's an example from contracts-tables-displays)
```
1) Every Circle of Evaluation must have one - and only one! - function, written at the top.

2) The arguments of the function are written left-to-right, in the middle of the Circle.

Values like Numbers, String, and Booleans are still written by themselves. It’s only when we want to _use a function_ that we need to draw a Circle, and write the values inside from left-to-right.

3) Circles can contain other Circles!
```
<img width="752" alt="Screen Shot 2024-01-22 at 8 53 50 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/55a59ee2-e94b-4f88-a621-4759c11bbf12">
<img width="847" alt="Screen Shot 2024-01-22 at 8 54 05 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/bf0b022c-6712-4f20-9ff6-08a54a3229e7">


Google Slides itself does not support numbered lists that are interrupted this way. Unfortunately the only way around it is to simulate the numbers ourselves. The above example would then be (notice the numbers!):
```
(1) Every Circle of Evaluation must have one - and only one! - function, written at the top.

(2) The arguments of the function are written left-to-right, in the middle of the Circle.

Values like Numbers, String, and Booleans are still written by themselves. It’s only when we want to _use a function_ that we need to draw a Circle, and write the values inside from left-to-right.

(3) Circles can contain other Circles!
```

**Comment by flannery-denny** [comment]
@ds26gte 
Here's what Investigate2 looks like in last year's deck
<img width="1142" alt="Screen Shot 2024-01-24 at 2 12 09 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/3eb67c9e-0874-459a-9254-77beb39ef952">

Here's slide 5 from this year's Bar-and-pie-charts deck
<img width="1146" alt="Screen Shot 2024-01-24 at 2 12 18 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/46274f16-5a8a-4847-8359-46e1651faf7c">

**Comment by schanzer** [comment]
@flannery-denny and @retabak I've almost finished working through the Reactive slides (GOD those lesson are a _mess_ compared to our stuff), and I'm not seeing any show-stopped slide infrastructure issues anymore. Is this issue *gasp* ready to close?

**Comment by flannery-denny** [comment]
@schanzer I vote we close and open smaller issues if need be.

**Comment by retabak** [comment]
sounds good to me! 
also, WOW, this issue was epic. RIP issue #1714.
