### ISSUE TITLE
link contracts page from every lesson plan

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1717]
probably from materials section

**Comment by schanzer** [comment]
@flannery-denny Dorai can add this, but we need to be super clear about what we're linking and when.

**What**

- Are we linking to the Contracts page _as it would appear from this point in the pathway_, the Contracts page _for the whole pathway_, or _the entire Contracts reference for all of Bootstrap_?

**When**
- Certainly not for CODAP
- What about for lessons where no programming has been introduced?

**Comment by flannery-denny** [comment]
We discussed this in December and decided that we would link the Contracts page for the whole pathway. And, I guess if a lesson plan is accessed from outside of a pathway we should link the Contracts for all of Bootstrap.
