### ISSUE TITLE
Include general DS question stems

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1718]
General Observations
Use these sentence starters to help students describe patterns, make predictions, find comparisons, share discoveries, formulate hypotheses, and ask questions .

Patterns:
I noticed a pattern when I looked at the data. The pattern is...
I see a pattern in the data collected so far. My graph shows....

Predictions:
Based on the patterns I see in the data collected so far, I predict that...
My prediction for (blank) is...

Comparisons:
When I compared (item 1)  and (item 2), I noticed that...
There are similarities [or differences] between…

Surprises and Discoveries:
I discovered that...
I was surprised by...
I noticed something unusual about…

Hypotheses: (Possible Reasons for Data)
A possible explanation for what the data showed is...
A factor that affected this data might have been...
I think this data was affected by…

Questions:
I wonder why...
I wonder how...
How are (blank) affected by...
How will (blank) change if...

**Comment by schanzer** [comment]
@flannery-denny this feels like either a TR page _or_ a back-pages kind of thing. I'm leaning towards the former. What do you think?

**Comment by flannery-denny** [comment]
I think they'd be most useful if we offered them in both places! That way teachers see that we're suppporting them with additional scaffolds and students have access to using them when they're stuck - good idea :) I'll get on it.

**Comment by schanzer** [comment]
@flannery-denny this looks like a job for `/shared/langs/en-us/docroot/pages/`! Follow the pattern I used for the desmos-instructions file.

**Comment by flannery-denny** [comment]
@schanzer I'd also like to include these in the back of the DS workbook. Should I just copy the page to backmatter and add it to `workbook-pages.txt` or is there a way to include it directly from the docroot folder?

**Comment by schanzer** [comment]
Copy

**Comment by retabak** [comment]
@flannery-denny - thanks for doing this! sorry I didn't get around to it.
