### ISSUE TITLE
lesson table small fixes

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1719]
I'm on fall2024. I notice that under materials, the lessons say "PDF of all Handouts and Page" -- we want it to say "Pages". Here's an example from function-composition:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/8d988576-2de4-4088-9ebf-1211e2494bb7)

Also noticing that for function-notation, the little clickable triangle is not present (I'm assuming because we've included text saying "This lesson is unplugged"). Assuming this is the case with other unplugged lessons? Screenshot below:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/fecb4464-f755-46e2-82ae-bc68129f9233)

**Comment by schanzer** [comment]
@retabak fixed -- thanks for reporting, and for the excellent bug report!
