### ISSUE TITLE
mathjax problem? (on web and fall2024)

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1720]
`@math{x \geq -40}` is showing up like this:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/1fb78902-03e9-46a6-be22-e9e4495959fe)

To be honest, I do not know if there is an error here! I did "find in files" and just found this one instance of "geq".

**Comment by ds26gte** [comment]
Use `\ge`. If needed, I can add `\geq` as an acceptable alternative.
