### ISSUE TITLE
Directive parsing swallows whitespace that comes after?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1722]
See the following asciidoc, taken from [this file](https://github.com/bootstrapworld/curriculum/blob/additive-inverse-new-idea/lessons/Early-Math/additive-inverse/langs/en-us/index.adoc?plain=1#L251) on the additive-inverse-new-idea branch:

`a @ifproglang{pyret}{hash}@ifproglang{wescheme}{semicolon} at the start of a line`

When building in Pyret, I expect it to generate `a hash at the start of a line`. Instead, I get `a hashat the start of a line`. Note that the space between "hash" and "at" has been ellided.

What's strange is that I _don't_ see this behavior anywhere else.

**Comment by ds26gte** [comment]
Hopefully the fix solves this once and for all, *for all* `@if...` directives (not just `@ifproglang`) that are followed by spaces/newlines. The heuristic: For an `@if...` that is being skipped,

- *Do not* skip any non-newline spaces, ever
- *Do* skip one (but only one) following newline if present. This skipped newline may be preceded by spaces (which are retained per previous rule)
- If a newline was skipped by previous rule, then set possible-new-line flag to true, so any AsciiDoc commands that start on the first column (like `|===`) are recognized

This should be less kludgy than previous solutions to this problem, but check for possible unintended consequences.
