### ISSUE TITLE
request: vertical centering when only 1 bullet in @lesson-instruction or @QandA

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1723]
Here's a screenshot that has examples of each.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/e41f4ee1-64e9-4546-8069-2bd7278b58a6)

Wouldn't it look nicer to avoid all that empty grey space beneath the single sentence?

If possible (not a big deal): I also would like if one bullet `@lesson-instruction`s and `@QandA`s were automatically *not* bulleted. (Bullets belong on lists, not single items, IMHO.) By just not putting a bullet or a @Q, we can make this happen, but I suspect we will sometimes forget.

**Comment by retabak** [comment]
Sorry, maybe I was unclear! Seeing that I asked for vertical SPACING when I meant CENTERING. Anyhow: Can we vertically center the text rather than chop off the bottom of the grey space?

**Comment by schanzer** [comment]
@retabak ahhh, I see. Unfortunately, there's really no easy way to do this. The CSS display class we use on QandA is finicky (a simpler one wouldn't work correctly for the trick we use to make adjacent callout boxes blend in a lesson plan and still split across slides). I don't think there's any easy way for me to vertically center using this display class. :(
