### ISSUE TITLE
Data Science Lesson slide edits needed

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1726]
In the [Filtering and Building lesson slides](https://docs.google.com/presentation/d/1MsvNasjGgDvuBIhCcxJq_0urGjbH3Qpth1iOMXvCxs4/edit#slide=id.5ffef3f7-f5a0-11ed-a74b-5316ab2226c2) I believe a slide needs to be deleted.  Slide #10 describes the students activity with only one student as filter.  That was the old way that activity was done.  Slide #9 describes the activity the way we currently teach it with two students:  helper function and filter.  Slide #10 should be deleted.
In the [Grouped Samples lesson slides](https://docs.google.com/presentation/d/1Cn6ocPNhQWTaLL6am7AWE-kg4l4uJ_rAi6uLe2qjkiM/edit#slide=id.g27c9f80f45e_0_87), slides #17 & 18 are repeated and one of them needs to be deleted.

**Comment by schanzer** [comment]
Oooh, thanks for bringing this to our attetion, @joystraub ! Fixed.
