### ISSUE TITLE
@teacher-@lesson-instruction-@teacher sandwich creates slide problems

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1727]
I've encountered something we didn't plan for when building slide decks.

On this slide (below), there is a @teacher - @lesson-instruction - @teacher sandwich. When we use this, the first @teacher is appearing ON the slide (viewable to students) and a little stray arrow (like this: -->) is appearing in the deck. Additionally, part of the first @teacher{} is NOT appearing in the teacher notes.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/4d7ef5d4-f9dd-4748-83e2-6164c76cbee5)

Here's the culprit text if you don't understand what I mean by "the sandwich":

```
=== Launch

@teacher{
Explain to students that they are about to learn to play two different games, which they will revisit periodically throughout this course. The first is "True or False?"

@strategy{
@span{.title}{Pedagogy Note: Viewing the Equal Sign as Relational}
These activities are designed to help students develop a relational view of the equal sign. Students often interpret the equal sign operationally, or they think of it as an instruction that means "now get the answer." Students with an operational view of the equal sign often solve solve 8 + 4 = ? + 5 incorrectly, as either 12 or 17.

Conversely, students who have a relational view of the equal sign recognize that a relationship exists between the numbers or expressions on either side of the equal sign. Decades of @link{https://link.springer.com/content/pdf/10.1007/BF02655897.pdf, "research"} suggest that students who interpret the equal sign to mean "the same as" are better positioned to think algebraically down the road.
}}

@lesson-instruction{
- Let's play a round of @printable-exercise{true-or-false.adoc}!
- Look at the first pair of Circles of Evaluation on the page.
- Use computation (or any other strategy) to determine if the statement of equivalence is true or false.
- Now complete the rest of @printable-exercise{true-or-false.adoc}
}

@teacher{
The Circles of Evaluation in this activity were designed to support students in practicing various mental math strategies. If students can recognize structure and avoid computation, that's fine too!}

=== Investigate
```

**Comment by ds26gte** [comment]
The error is happening because the first `@teacher{}` encloses a `@strategy{}`.  Both of these are considered Teacher Notes, and enclosing a Teacher Note inside another causes a nested HTML comment which causes barfage.

I could allow for teacher notes directives to enclose themselves without error, but why?  Is there a reason not to write the `@strategy` outside the first `@teacher`?

**Comment by schanzer** [comment]
@retabak Dorai right - @strategy should not be enclosed within @teacher

**Comment by retabak** [comment]
you are right! Thanks, Dorai!
