### ISSUE TITLE
page numbers for handouts in lesson materials pdfs should be blank rather than "undefined" 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1729]
Checkout the pdf from this page for an example [https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/ds-intro/index.shtml?pathway=data-science](https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/ds-intro/index.shtml?pathway=data-science)

**Comment by schanzer** [comment]
@flannery-denny thanks for bringing this to my attention! I wound up rewriting the page numbering code to do even better than blank pageNums: now all handouts will say `(handout i)` (roman numeral'd). I did the same thing to opt pages as well, and I think the end result is super nice.
