### ISSUE TITLE
remove extraneous @opt-project references

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1733]
I'm sorry about the lame issue title, but I'm not sure what the actual issue is. (Hoping Rachel can clarify, retitle and perhaps reassign.)

In my memory the new projects as lessons stuff was being saved for the fall... In this materials table there's one opt-project being linked the old way and one being linked the new way. Not sure what's supposed to be happening but this surely isn't it. 

https://bootstrapworld.org/materials/spring2024/en-us/lessons/threats-to-validity/index.shtml?pathway=data-science
<img width="405" alt="Screen Shot 2024-01-03 at 11 37 14 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/e60523e5-4861-4c67-972d-856550bc8d74">

**Comment by retabak** [comment]
@flannery-denny - Thanks for catching this! 

FYI - In fall2024, the project-lessons will appear as lessons in their pathways. Right now, the project-lessons are live, but have not been added to pathways as stand-alone lessons. They are accessible in the same way that they always used to be and not from the course landing page. (We decided the minimalist OG projects with hardly any scaffolding / teacher guidance would not be missed.)

Also, confirming that `master` was the correct place to fix this?

**Comment by flannery-denny** [comment]
Got it. I was working on master. Sounds like you're not listing the
projects in the pathways for January but you have linked to the project
pages from within lessons so I will definitely give them all a read this
week!

**Comment by retabak** [comment]
I've removed extra @opt-projects, but want to note that @opt-project is still used for a few projects that we've opted not to revamp, but do not want to remove completely (stress/chill, food habits, olympic records).

**Comment by flannery-denny** [comment]
@schanzer Since `@opt-project` remains active, we need to update the formatting for them in the materials section of the lesson plan so that it matches the following. Thanks!
<img width="780" alt="Screen Shot 2024-01-05 at 11 04 18 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/80a868b0-7038-439f-8774-26aeb8160f81">

**Comment by flannery-denny** [comment]
yes. All projects should be consistently appear in the same place in the list. It looks like that comes after starter files.
