### ISSUE TITLE
contracts fall2024 error

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1734]
oopsies! This needs to be fixed.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/427c6cf3-8999-46d1-ab3f-b152ef37ceb9)

**Comment by flannery-denny** [comment]
@retabak Where are you seeing this? Here's what I see on `file:///Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/contracts/pages/text-coe.html`
<img width="956" alt="Screen Shot 2024-01-04 at 1 56 34 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b0a4eed3-6199-4389-9c55-e5cab1bc2324">

**Comment by flannery-denny** [comment]
@retabak Never mind. Found it.
