### ISSUE TITLE
Bail out to mathjax if a fraction is raised to an exponent

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1737]
From the first Investigate section in the [probability lesson](https://bootstrapworld.org/materials/fall2023/en-us/lessons/probability-inference/index.shtml?pathway=data-science):

![image](https://github.com/bootstrapworld/curriculum/assets/77126/6d75528a-dc86-4141-9c31-a9ed6c09ce4f)

Not only is this _difficult_ to read, but it's also _ambiguous!_ Is it one-divided-by-two-to-the-10th-power? Or one-half-to-the-10th-power?

This fix should be done on both master and fall2024

**Comment by ds26gte** [comment]
I don't think mathjax is any better without explicit parens here. I.e.
```
@math{({\frac{1}{2})}^{10}}
```
