### ISSUE TITLE
contracts dictionary looks weird [reported by PPSD teacher] + error for rhombus contract

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1739]
Here's the screenshot he sent me. Found out yesterday that the screenshot is from this URL: https://bootstrapworld.org/materials/fall2023/en-us/Contracts.shtml?pathway=algebra-pyret

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/a90de1d0-88d3-4054-bd70-7ab184cc80f7)

**Comment by schanzer** [comment]
@retabak rhombus contract has been fixed. CC me if you want to ask him about the weird way it's showing up for him
