### ISSUE TITLE
Searchable Glossary Page

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1742]
Just like Contracts.shtml, but uses _only the lesson URL parameter_ to display terms for a specific lesson. If none is provided, it displays all the words.

Once the feature itself has been approved, Dorai can remove all the glossary-handling code from the build script

**Comment by ds26gte** [comment]
Please note that if we're avoiding creating little glossary `.html` files, we need to ensure that glossary database contains the descriptions in HTML and not AsciiDoc.
