### ISSUE TITLE
@math{sqrt}} isn't translating to math and exponents are landing too low on the base

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1744]
I'm seeing this in the distance lesson on fall2024
<img width="162" alt="Screen Shot 2024-01-10 at 8 16 14 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/8d1be98f-65c9-4ca0-90dc-0ee95c0a2c31">

**Comment by schanzer** [comment]
@flannery-denny I bumped the the exponents up a little higher. Close this issue if you're happy with their positioning now.

As for the math display: 
- You need to use proper mathjax syntax. your `sqrt{a^2 + b^2}` is missing the starting `\` at the beginning
- You indented the mathjax inside a `@lesson-point{}`, but indenting means something very specific in asciidoc that I don't think you meant

I pushed a fix for the mathjax and asciidoc formatting, which makes the math display correctly.
