### ISSUE TITLE
clean up logo starter file

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1745]
[This code in this file could and should be so much cleaner!](https://code.pyret.org/editor#share=1GaRxWxlWCpKvsNC4-qY19hkHcf4mz4q_)

**Comment by flannery-denny** [comment]
@retabak I would expect the pyret starter file for this project to be housed within the Projects folder in the Curriculum Folder.  I reorganized that folder to have a Slide Decks folder and a [Libraries and Starter Files](https://drive.google.com/drive/folders/1d_dLSX2enoBd9ycZyV0fvAm3FucAa0U6?usp=drive_link) folder to math the organizational structure of the other files. Curious where you've saved it?

**Comment by retabak** [comment]
let me add it! I was unaware of our organizational system for starter files until *very* recently (eek) and have quite a bit of catching up to do.

**Comment by flannery-denny** [comment]
@retabak Here's a comparison between the way the code appeared in [the file that was linked](https://code.pyret.org/editor#share=1PoNRQt4zvVzpL0y2u9bFKlfaO3dK09b6&v=78aeaeb) and [how it got cleaned up](https://code.pyret.org/editor#share=1S3W4BmngMw-RJco2RejWuZe5uabHuXnS&v=78aeaeb).
