### ISSUE TITLE
organize starter files that didn't get saved in proper folders

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1746]
I need to do a lot of this....

**Comment by flannery-denny** [comment]
@retabak While you're at it, please make sure that all starter files are linked to lesson plans using `@starter-file` and are listed in `starter-files.js`. Adding the logo starter file now.

**Comment by retabak** [comment]
Wait, it is in `starter-files.js` and linked using `@starter-file`! are you seeing that it is not?

**Comment by flannery-denny** [comment]
My sublime settings were set to match capitalization and the names you were using didn't match exactly in the file, so it didn't come back with anything for logo. I've renamed them to match. It looks like you probably were doing this, but figured it was worth flagging as something to check while you're deep in it.
