### ISSUE TITLE
make image layering in WeScheme match Pyret

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1747]
<img width="873" alt="Screen Shot 2024-01-12 at 11 15 39 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0fb26928-c3ea-41d6-92b0-370e9654ca05">
<img width="923" alt="Screen Shot 2024-01-12 at 11 15 59 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/03229509-1078-430a-afab-456c5957c362">

**Comment by schanzer** [comment]
@flannery-denny this is't a curriculum issue, but it's a good incentive for us to start tracking issues in other repos!
