### ISSUE TITLE
Incorrect Code in Composing Table Functions Lesson Slides

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1751]
In the Data Science Composing Table Functions Slides deck https://docs.google.com/presentation/d/16E4VGlEuKY-ov4smqcnRfK7MIZgoPZNU-NP8kP64Jl4/edit#slide=id.ce81ce6c-11cf-11ee-a9c0-6d7c0ac91bb1 the code on Slide 18 does not match the circle of evaluation.
It says:  box-plot(filter(animals-table, is-young), "age")
But should be: box-plot(filter(filter(animals-table, is-dog), is-young), "age")
to match the Circle of Evaluation it is describing on slide 17.

**Comment by schanzer** [comment]
Fixed - thanks, @joystraub !
