### ISSUE TITLE
weschemify projects, add to pathways

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1756]
- [x] flags
- [x] functions
- [x] logo
- [x] video game

**Comment by flannery-denny** [comment]
@retabak I'm confused by this issue. A number of these projects are data projects. And WeScheme doesn't have any capacity to make displays.

**Comment by retabak** [comment]
woops! I unthinkingly copied all of the projects here. WIll revise my list. Thanks.
