### ISSUE TITLE
update Dataset Notes page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1757]
It hasn't been touched for a while!

**Comment by schanzer** [comment]
@flannery-denny Rachel and I discussed this today, and we're not sure this actually _needs_ to be updated!

The datasets haven't really changed since the notes document was created, so what is there to update?

**Comment by flannery-denny** [comment]
@schanzer If there's anything you know about the ign reviews dataset please update the corresponding fragment. Otherwise, this is ready to close.
