### ISSUE TITLE
Redo Box plot images

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1763]
@joystraub reported a critical issue today, which is that every box plot starts at zero. This was done intentionally, to make a comparisons between different kinds of box plots easier.

But with certain data sets that have ONLY high values, this messes up the scale so badly that the box plot becomes unreadable. 

I've updated the DS2.1 context to do something better, and Joy has confirmed that it works as advertised. Unfortunately, that means we need to check all of our box plot images and see if they need to be redone.

We can push this off to next month's milestone, if necessary, but we don't have a ton of box plots in our materials and it might just be something that can be done quickly.

**Comment by schanzer** [comment]
I did a search of our repo for any image file with the word `box` in it, and it turns out there are only two Pyret-generated boxplot images. And it just so happens that both of them have low values that allow us to keep those images without modification. Phew!

**Comment by flannery-denny** [comment]
@schanzer fyi - there are several boxplot images in the box plots lesson that aren't titled with the word box... not actually sure what change to be looking for.

**Comment by schanzer** [comment]
@flannery-denny we're all set
