### ISSUE TITLE
Error in instructions on Analyzing Survey Results When Data is Dirty workbook page

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1764]
Question 3 on [Analyzing Survey Results when Data is Dirty](url) https://bootstrapworld.org/materials/fall2023/en-us/lessons/data-collection/pages/survey-analysis.html says Shani has made a bar-chart - then it asks the students to "make the pie-chart".  I think this should say bar-chart here, not pie-chart to match what is going on in that question.

**Comment by schanzer** [comment]
Thanks, @joystraub !
