### ISSUE TITLE
Some lessons contain Preparation Sections - the bullets from these should end up in teacher notes for the title slide.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1767]
- noting that not all lessons contain a preparation section
- when they do, ideally there'd be a title "Before Teaching this Lesson:" above the bulleted list
- also noting that our current template already has text in the presenter notes section on how to work with peardeck - not sure whether peardeck is still a thing?

**Comment by schanzer** [comment]
Confirming PearDeck is very much a thing! :)

**Comment by ds26gte** [comment]
I don't see in any lesson (in branch `fall2024`) a title to the effect `Before Teaching This Lesson`. I do see a row whose first column says `Preparation`. Is the second cell to be slurped up as a teacher note?

**Comment by schanzer** [comment]
@ds26gte here's one: https://bootstrapworld.org/materials/spring2024/en-us/lessons/choosing-your-dataset/index.shtml?pathway=data-science

**Comment by flannery-denny** [comment]
@ds26gte Clarifying that the idea is:
If a lesson plan has a row titled "Preparation", then...
the title slide should have a presenter note titled "In Preparation for Teaching this Lesson:" that is followed by all the text that gets "slurped up" from that row of the lesson plan. 
If possible, this note should go above the note about teaching with Peardeck that is currently included in the presenter note for every title slide.

**Comment by schanzer** [comment]
@flannery-denny does Dorai's commit do what you want it to do?

**Comment by retabak** [comment]
@ds26gte - Just tested this. I see the word "Preparation" - yay!  The Preparation text, however, is *after* the Peardeck text. Is it possible to insert it above the text about Peardeck? If not - maybe there could be a single blank line after the Peardeck text so they don't bleed together?

**Comment by schanzer** [comment]
Confirmed fixed!
