### ISSUE TITLE
Slide building should preserve common misconceptions as a teacher note

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1777]
See `bar-and-pie-charts` for an example of a lesson that silently drops this section when converting to slides. Instead, the Common Misconception text should show up as a teacher note on the first Synthesize slide

**Comment by flannery-denny** [comment]
Common Misconceptions is missing from Measures of Center. Perhaps it doesn't know which slide to put it on because there's already a Q&A in the footnote?
