### ISSUE TITLE
@Defined asciidoc snippets must be nestable

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1779]
Likely similar to other directives-not-nesting issues we've see in the past.

This
```
@define{about-template}{
- Blue text is included to provide examples.

- Slides can be duplicated if students want to add additional displays or interpretations.
}

@ifnotslide{
@teacher{
Encourage students to familiarize themselves with the template, highlighting some important features:
@about-template
}
}

@ifslide{
Notice:
@about-template
}
```
is currently rendering as follows
<img width="869" alt="Screen Shot 2024-01-22 at 11 28 37 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/e58bcf3e-e51a-43ab-b834-54ca8088b972">

**Comment by schanzer** [comment]
@ds26gte I think solution 2 is the right one -- we will _only_ be using that directive as a block

**Comment by schanzer** [comment]
@flannery-denny I added your sample asciidoc to `choosing-your-dataset` and confirmed this fixes the issue, but I didn't check it in because I wasn't sure if you just made that as an example or if you actually _wanted_ that

**Comment by flannery-denny** [comment]
Thanks!
