### ISSUE TITLE
If the slidebuild stops before it finishes working through the lesson plan, we should get a warning! 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1785]
We definitely don't want an author to think they've successfully built a slide deck, when it only has half of the lesson content!

I have fixed this code, but here's an example of code that stopped the slide build without a warning.

```
@QandA{
@Q{Can you spot the problem?}
@show{(code '(+ 1 "Zari"))}
@show{(code '(triangle "50" "solid" "blue"))}
@show{(code '(or "true" false))}
}
```

**Comment by ds26gte** [comment]
I tried plugging this example in a lesson. It doesn't seem to make an incomplete slide. Is there another example that creates an incomplete slide (silently)?

**Comment by flannery-denny** [comment]
Weird. I've had a number of slide decks stop building halfway through. I'll let you add an example here the next time it happens.

**Comment by flannery-denny** [comment]
@ds26gte The version of the contracts lesson I just pushed is stopping the build before the final slide which should be Additional Exercises.

**Comment by flannery-denny** [comment]
@ds26gte the correlations lesson stops building slides at the synthesize slide of `Summarizing Correlations using r-values` and there's a whole other section to the lesson.
