### ISSUE TITLE
Errors in Contracts that need to be fixed - online search and in Student Workbook pdf

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1787]
A teacher (Roger Hunter) shared the following mistakes he found in our on-line contract listing & in the back of the student workbook pdf:

line-graph is missing the labels argument in the contract, however, it appears in the example
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/32c1cb83-3077-469c-91c2-ddd2f235cea0)

mean lists the 2nd argument as a Number - but it should be a String (the name of the column, again the example is correct.
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/dd731d44-602d-44f7-8f81-7be4c3338a15)

sum shows the incorrect Range of Table, when it should be Number.  (This is in the pdf of the student workbook contract section only - not acccessible in the online contract search)
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/5f1da8a2-9007-4bcb-9c27-291f810a48e7)

**Comment by schanzer** [comment]
Thanks, @joystraub ! Tell Roger it's fixed, and that he's been credited with reporting the bug!
