### ISSUE TITLE
Inequality1 (v.fa24) starter file isn't working

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1792]
[https://code.pyret.org/editor#share=1YMSkIfzhfb9ykOhG7ToBjROwp3-TjeOE](https://code.pyret.org/editor#share=1YMSkIfzhfb9ykOhG7ToBjROwp3-TjeOE)

**Comment by schanzer** [comment]
Oooof. Not related to our work. It's a CPO problem. I've opened an issue there. Hopefully it can be fixed, and FAST

**Comment by flannery-denny** [comment]
Huzzah! I was pretty surprised that I hadn't left it in working order.
