### ISSUE TITLE
Slide Build should not be using DS Title and Body from Theme Builder

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1794]
I'm looking at the Computing Needs All Voices slide deck and was about to file it as all issues resolved... but a whole bunch of these slides have the Data Science logo in the top left corner instead of the lesson section symbols.
<img width="191" alt="Screen Shot 2024-01-25 at 11 17 26 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d31f3acf-e8ae-414a-aca9-5e0f33c2b0a1">

**Comment by schanzer** [comment]
@flannery-denny This issue is now resolved!
