### ISSUE TITLE
Tables are building with image descriptions instead of images of displays

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1795]
Seeing this in `correlations` and `bar-and-pie-charts`
<img width="895" alt="Screen Shot 2024-01-25 at 4 18 22 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/26e6199f-c068-4798-92c4-ac81475666c4">

**Comment by schanzer** [comment]
Confirmed fixed on `correlations`!

**Comment by flannery-denny** [comment]
This isn't fixed in bar and pie charts.

**Comment by schanzer** [comment]
@flannery-denny the issue really _was_ fixed, I swear!

The problem you're seeing in bar-and-pie-charts is for a totally different reason: our slide-building script was grabbing images from our website, but using the `latest` folder. As a result, images that are unchanged from `fall2023` worked...but new ones that are stored in `fall2024-beta` did not. 

I've pushed a fix that forces slides to use whatever season and year the environment variables are set to, and confirmed that bar-and-pie charts builds with the correct images in the slides.
