### ISSUE TITLE
Text that is bold in lesson plans is rendering as italicized in slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1796]
In lessons this renders as bold. In slides it renders as italicized.
`*With or without replacement?* `

This is in `combinatorics-permutation`

**Comment by schanzer** [comment]
This may require some regex-fu: we need to match anything between _single_ asterisks, and turn them into _double_ asterisks.

`*hello*` should become `**hello**`
`**hello**` stays the same

The same is true for double-underscores in reverse: __hello__

**Comment by schanzer** [comment]
Confirmed fixed in `combinatorics-permutation`!
