### ISSUE TITLE
Review 2024 Algebra materiels

### ISSUE THREAD

**Issue by er1c456** [bootstrapworld/curriculum#1798]
- [x] computing-needs-all-voices
- [x] numbers-inside-video-games
- [x] project-video-game
- [x] coordinates
- [x] order-of-operations
- [x] simple-data-types
- [x] contracts
- [x] function-composition
- [x] project-logo
- [x] defining-values
- [x] surface-area-rect-prism
- [x] transform-compose-images
- [x] project-flags
- [x] making-game-images
- [x] functions-make-life-easier
- [x] functions-vertical-line-test
- [x] function-notation
- [x] functions-examples-definitions
- [x] project-function
- [x] functions-can-be-linear
- [x] function-definition-linear
- [x] functions-dr
- [x] functions-for-character-animation
- [x] problem-decomposition
- [x] inequalities1-simple
- [x] inequalities2-compound
- [x] inequalities3-sam
- [x] piecewise-functions-conditionals
- [x] player-animation
- [x] distance-formula
- [x] inequalities-collision

**Comment by er1c456** [comment]
- [] Computing Needs All Voices 
- [] The Numbers Inside Video Games 
- [] Project: Build a Video Game 
- [] Coordinates and Game Design 
- [] Order of Operations 
- [] Simple Data Types 
- [] Contracts 
- [] Function Composition 
- [] Project: Create Your Own Logo 
- [] Defining Values 
- [] Surface Area of a Rectangular Prism 
- [] Transforming and Composing Images 
- [] Project: Make a Flag 
- [] Making Game Images 
- [] Functions Make Life Easier! 
- [] The Vertical Line Test 
- [] Function Notation 
- [] Functions: Contracts, Examples & Definitions 
- [] Project: Create Your Own Function 
- [] Functions Can Be Linear 
- [] Defining Linear Functions 
- [] Solving Word Problems with the Design Recipe 
- [] Functions for Character Animation 
- [] Problem Decomposition 
- [] Simple Inequalities 
- [] Compound Inequalities: Solutions & Non-Solutions 
- [] Sam the Butterfly - Applying Inequalities 
- [] Piecewise Functions and Conditionals 
- [] Player Animation 
- [] Distance In Video Games 
- [] Collision Detection - Distance and Inequality

**Comment by er1c456** [comment]
@schanzer @retabak I believe you are the correct tags for Algebra review thoughts. Please confirm.

I am not very deep into my review, so I am just now encountering some need for clarification of the scope of what would be helpful. 

As I'm reviewing I am making changes in the branch associated with this issue for small fixes. At the same time I am encountering much bigger ideas about the flow of lessons or larger missing sections. I will describe my thoughts in comments here, but won't attempt to rewrite a lesson or add a large section.

Please guide how to handle larger thoughts about structure, flow, or objectives of a lesson in a way that would be helpful. My presumption is that you aren't interested in ideas for big changes at this time, but maybe live somewhere that you access during another development cycle.

**Comment by schanzer** [comment]
@er1c456 I'm assuming you haven't had a chance to do any further review, correct? Are there changes you'd like to merge in, before we go to print in a few weeks?

**Comment by er1c456** [comment]
I'm really just getting up to speed working through at repository level,
but given one more week I could process through a chunk of material. Would
commits next week be acceptable with a pr at the end of the week?

**Comment by schanzer** [comment]
@er1c456 absolutely! Make sure you merge from fall2024, as there have been a lot of changes every week :)

**Comment by schanzer** [comment]
@er1c456 great catch! pushed a fix to `fall2024`

**Comment by schanzer** [comment]
Closing since #1949 has landed
