### ISSUE TITLE
@clear is bleeding through to slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1799]
<img width="1134" alt="Screen Shot 2024-01-25 at 12 44 13 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0af68c87-831f-467c-b632-fe0b4b948460">

This is from the permutations lesson

**Comment by schanzer** [comment]
Thanks! Confirmed fixed by building the same lesson.
