### ISSUE TITLE
Add lesson title to page footer?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#18]
This can (hopefully) be copied from the pdftk commands in the old repo

**Comment by schanzer** [comment]
From a conversation with @BootstrapJen: it would be nice if the footer of the page had the page number on the outer edge (or at least one side), and the _title of the associated lesson_ on the other. This will help teachers orient to which pages connect with which lessons.

**Comment by schanzer** [comment]
@ds26gte is it possible to have the page numbers also include the lesson title, if one exists?

**Comment by ds26gte** [comment]
The lesson plan (the one that becomes an HTML page) has a title, but the workbook pages contributed by the lesson to the workbook PDF don't necessarily have any title. They're just a series of single pages (some directly PDFs, not even adoc that can be mined for possible titles). Do you want the title in the footer to be taken from the related lesson plan? Even though it may not be embedded in the lesson body text as it occurs in the workbook?

**Comment by ds26gte** [comment]
Footer of pages in workbook (except for first two pages as usual) now contain the associated lesson title on the left side and the page number on the right side.

Pls let me know if you want the relative positions of these two bits of info changed for even/odd pages.
