### ISSUE TITLE
When QandA only has one Q render it without a bullet in slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1804]
_Here's an example from permutations_
```
@QandA{
@Q{What are some other real world examples that require permutation?}
@A{Password strength, guessing combination locks...}
}
```

**Comment by ds26gte** [comment]
What about the single `@A`?  How do we distinguish the single `@Q` from its single `@A`? Currently, they're distinguished because `@Q` are bullets and `@A` are _sub_-bullets.

**Comment by flannery-denny** [comment]
@ds26gte only the Q ends up on the slide. The rendering in the slide notes and in the lesson plan is perfect.
Also, FYI @schanzer asked me not to distract you with this this week, hence the not urgent label ;)

**Comment by ds26gte** [comment]
Ah, special treatment only for slides. OK, sound good.

**Comment by schanzer** [comment]
@flannery-denny close if you're happy :)
