### ISSUE TITLE
bar and pie charts still isn't picking investigate2

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1807]
Here's what Investigate2 looks like in last year's deck
<img width="1142" alt="Screen Shot 2024-01-24 at 2 12 09 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/3eb67c9e-0874-459a-9254-77beb39ef952">

Here's slide 5 from this year's Bar-and-pie-charts deck
<img width="1146" alt="Screen Shot 2024-01-24 at 2 12 18 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/46274f16-5a8a-4847-8359-46e1651faf7c">

**Comment by schanzer** [comment]
@flannery-denny try now?

**Comment by flannery-denny** [comment]
@schanzer Still not working

**Comment by schanzer** [comment]
@flannery-denny are you sure? [Here are the slides that I built just now](https://docs.google.com/presentation/d/1kM7AEFKpeZWdPMFQSVU5lHN_YPuUTBWTFSiy1lYtbAc/edit#slide=id.95a7ff71-bd81-11ee-9632-ff20817a9af5). You can see that the layout is indeed `Investigate2`, and that both images have been scaled to fit their bounding boxes. Are you seeing something different?

**Comment by flannery-denny** [comment]
@schanzer it's working now. As of this morning it was still producing the image in the screenshot above.
