### ISSUE TITLE
make-slides.lua doesn't recognize asciidoc tables with classnames

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1810]
**The problem:**

In `Algebra/functions-can-be-linear`, we have the following asciidoc:
```
[.graph-table, stripes="none", frame="none"]
|===

| @image{images/constant-linear.png}
  @image{images/num-abs.png}
  @image{images/num-sqrt.png}

| @image{images/negative-linear.png}
  @image{images/positive-linear.png}
  @image{images/num-sqr.png}
|===
```

The lua script doesn't realize this needs to be converted to `@table`, and puts the asciidoc into the resulting `zlides.md` file verbatim.

**The solution:**
We should try to get the lua reader to identify these tables. 
In an _ideal_ world we would preserve the classname as well, and pass any custom CSS rules declared with `++++` over to the html generator.

**Comment by ds26gte** [comment]
I have to somehow figure out number of columns. Is it the case that any ad-hoc table classes like these (`.graph-table`, `.small-table`) can be assumed to have only one column. Also, can we ensure that such class names will always have the `-table` suffix?

**Comment by schanzer** [comment]
@ds26gte these are not safe assumptions, unfortunately. We _could_ add an author requirement here, but I think that's just plugging cracks in the dike. We need to let asciidoctor generate the HTML here.

**Comment by schanzer** [comment]
Confirmed fixed
