### ISSUE TITLE
Disambiguate Contracts Lessons

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1813]
- [x] Change "Catching bugs" in DS to use DS functions
- [x] Add @teacherNote to DS contracts

**Comment by flannery-denny** [comment]
@schanzer close if you're satisfied with the new page.

**Comment by schanzer** [comment]
@flannery-denny Looks good! 

I just pushed a commit that tweaks the titles of the pages, and adds some formatting. Close if you're comfortable with those changes.

**Comment by flannery-denny** [comment]
@schanzer I'm fine with the title changes but that dotted line formatting is horribly busy with everything else that is happening on these pages. If you want to add formatting, please shade.

**Comment by schanzer** [comment]
@flannery-denny good call. just pushed updated CSS that switches to gentle shading. Close if happy?
