### ISSUE TITLE
pages that need css rules

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1818]
- [x] functions-can-be-linear/notice-wonder-linearity I added rows to the tables, but they are shorter than the others.
- [x] Surface Area of a Rectangular Prism Explore. The current rule is doing a nice job of providing space above second level headers, but it's swallowing the fitb on question 2.
- [x] coe-why-define-values is spilling onto 2 pages. The css rule fd came up with broke the landscape build. es will probably be more efficient at tackling this.
- [x] surface area of a prism practice. I want the lines students are filling in to be at the bottom. fill vertical space makes it impossible to do that with asciidoc table orientation. `.>`
- [x] tree diagrams 2 doesn't need css - but it needs help! Looks like the word problem got rewritten for 3 ice cream flavors but the solutions are for the old problem, which included rocky road? not totally sure what we want to have happening here... but I know that what we have is wrong.
- [x] combinations - space out the math vertically
- [x] data cycle notes. How do I get the image to appear to the right of the block of text without making a table?
- [x] histograms notes - added a table for the last bullet but the existing css is leaving a big space before it.

**Comment by schanzer** [comment]
@flannery-denny a few things:
- I'm not seeing the 2-page warning for `coe-why-define-values` (see attached PDF)
- I assume `notice-wonder-linearity` is part of the `functions-can-be-linear` lesson. In the future, would you mind letting me know what lesson these are from? Anyway, I don't see any changes made to that file in the last 3 months, so I can't see the rows you added.
- I can't find a wbpage titled "surface area of a rectangular prism", and I checked all of the ones in the lesson to find a swallowed fitb with no luck. Can you tell me the exact lesson and page title for this?
- Doesn't look like any CSS rules are needed for tree-diagrams 2
- I don't see wbpage called `combinations`, but I'm assuming you're looking at the `combinatorics-combinations` lesson and the `combination` file?
- data cycle notes: use `@right{...}` around the image, just like it does in this page.
[coe-why-define-values.pdf](https://github.com/bootstrapworld/curriculum/files/14165717/coe-why-define-values.pdf)

**Comment by schanzer** [comment]
(I've also fixed tree-diagram2.adoc, but really that doesn't belong in this issue since it's not a CSS thing)

**Comment by flannery-denny** [comment]
@schanzer 
1) Thanks.
2) I'm only working on the workbook branch right now.
3) I didn't assign this to you and am just chronicling the things that need to be revisited. Thought we might do them together tomorrow.

**Comment by schanzer** [comment]
@flannery-denny ohhh! I'm sorry - my mistake. (And here I was trying to get ahead of stuff...!)

**Comment by schanzer** [comment]
@flannery-denny made a bunch of fixes. Question: shouldn't the 2nd notes page for measures-of-center be moved to box-plots?
