### ISSUE TITLE
@indented should be compatible with a broader spectrum of inputs

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1822]
- Currently it works with `*` bullets but not `-` bullets
- Currently it sometimes only indents the first line of a paragraph.
- Currently `@indented{}` can't handle this, but `[.indentedpara]` can

```
# species-dot :: (Row) -> Image
fun species-dot(r):
  if      (r["species"] == "dog"):       square(5, "solid", "black")
  else if (r["species"] == "cat"):       square(5, "solid", "orange")
  else if (r["species"] == "rabbit"):    square(5, "solid", "pink")
  else if (r["species"] == "tarantula"): square(5, "solid", "red")
  else if (r["species"] == "lizard"):    square(5, "solid", "green")
  end
end
```

- Here's another instance @indented doesn't handle from contracts-tables-displays
```
@indented{If we want to see the ten youngest animals, our diagram would look like this.}

@do{
(define exp1 '(first-n-rows (sort animals-table "age" true) 10))
}

@show{(coe exp1)}
}
```

**Comment by schanzer** [comment]
@flannery-denny is this in lesson plans _and_ slides? or just slides?

**Comment by flannery-denny** [comment]
@schanzer currently working on workbook pages.

**Comment by schanzer** [comment]
Confirming that @flannery-denny 's example in contracts-tables-displays works correctly now
