### ISSUE TITLE
Fix title of contracts page for Oklahoma workbook

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1824]
<img width="981" alt="Screen Shot 2024-02-05 at 10 44 59 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/243b652a-500c-4d09-a1a2-8ef5e2e0377f">

**Comment by schanzer** [comment]
@flannery-denny close if you're happy?

**Comment by schanzer** [comment]
@flannery-denny done! Now it just says "Contracts"
