### ISSUE TITLE
add negate to wescheme

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1828]
and then @retabak can create the appropriate starter files required for the two absolute value and opposite lessons!

**Comment by schanzer** [comment]
@retabak this is now working on a [not-yet-deployed version of WeScheme](https://300-dot-wescheme-hrd-2.appspot.com/openEditor). Test it out, and close if you're happy?

**Comment by retabak** [comment]
Yay! Works great, thanks.
