### ISSUE TITLE
trace doesn't work in sam the butterfly starter file on the web

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1832]
https://bootstrapworld.org/materials/fall2023/en-us/lessons/inequalities3-sam/index.shtml?pathway=algebra-pyret

and also rewrite text on line 34 to be more clear -- needs to say "uncomment" somewhere!

**Comment by schanzer** [comment]
@retabak I've fixed the file and improved the instructions. If this works for you, go ahead and close

**Comment by retabak** [comment]
Look good!
