### ISSUE TITLE
some tables not building correctly

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1833]
@ds26gte - tables in slide decks have been working BEAUTIFULLY.... until I got to this one (below). It is in the lesson absolute-value-and-opposites-2 in Early Math on `fall2024`.

```
[.embedded, cols=">.^3,^.^1,<.^3", grid="none", stripes="none" frame="none"]
|===
| @show{(coe '(negate (abs 4)))} | @math{+≠+} | @show{(coe '(abs (negate 4)))}
|===
```

In the slide deck, the code above showed up like the pic below:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/22c0f286-9ea1-42b6-bf1a-71f2dfc40738)

In the lesson, it looks like this (desired output):
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/7e521de8-eaf0-4451-9982-7f452767d441)

@schanzer says you are going to LOVE this one ;)

**Comment by retabak** [comment]
@ds26gte - I just ran into another table that doesn't work. This instance occurs in evaluating-exponents lesson on the exponents branch.

```
[.embedded, cols="^.^5,^.^1,^.^5", grid="none", stripes="none" frame="none"]

|===
| @math{2^5}
|
| @math{2 \times 2 \times 2 \times 2 \times 2}

| @show{(coe '(expt 2 5))}
| @math{=}
| @show{(coe '(* (* (* (* 2 2) 2) 2) 2))}
|===

```
produced this: 

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/67295343-bbba-482e-9c4a-17bb093c9edb)

**Comment by retabak** [comment]
hm, I'm not sure if this is the same concern that @flannery-denny expressed in #1836 or not.

**Comment by ds26gte** [comment]
It just looks like the table row is too big for the HTML's britches

**Comment by schanzer** [comment]
@ds26gte but if the columns were set exactly the way they were in asciidoc....

**Comment by ds26gte** [comment]
The slides HTML looks like it has less text width to work inside in than the browser HTML
