### ISSUE TITLE
Make permutation language consistent

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1837]
I'm seeing various names referring to the same thing in permutations and combinations - not sure why the've changed and which direction they're headed in
<img width="987" alt="Screen Shot 2024-02-08 at 1 08 27 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/3aa6d596-74a1-4385-87dc-2055cb36c449">

**Comment by schanzer** [comment]
@flannery-denny GOOD CALL. I've pushed a commit to address this.  Close if you're happy.
