### ISSUE TITLE
rewrite the mode(s) section of measures of center to teach about mode(s) of data that isn't numerical

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1839]
- [x] https://github.com/brownplt/code.pyret.org/issues/510

- [ ] Currently the Modes section is confusing. We either need to be more specific with our wording or expand what we teach and how the DS teachpak works. 
<img width="885" alt="Screen Shot 2024-02-15 at 11 17 29 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d1f3a524-1cd9-4913-943c-0e359ba48b8f">
<img width="657" alt="Screen Shot 2024-02-15 at 11 16 56 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b5e3478d-65b9-4ebd-8628-ab0c08ade619">

**Comment by schanzer** [comment]
This is partially blocked on https://github.com/brownplt/code.pyret.org/issues/510. I could write my own workaround, but I'm hoping the actual Pyret API can be updated in time for release.

**Comment by flannery-denny** [comment]
@schanzer any sense of when the pyret end of this work is likely to happen?

**Comment by schanzer** [comment]
@flannery-denny Pyret has been updated to support this!  🎉

Again, not in time for fall2024, which means the helpful error message I put in our library (and the check required to trigger it) needed to stay. I could take the check away and things would magically start working...which would make our lesson wrong. 

We'll need a new version of the library (v2.2) which takes out the check, now that Pyret itself no longer requires numbers.
