### ISSUE TITLE
should we offer a sam starterfile where Sam's image is replaceable?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1840]

**Comment by schanzer** [comment]
I absolutely love this. In fact, we just had a [teacher ask about this same thing](https://discourse.bootstrapworld.org/t/sam-the-butterfly-code/2704/1) on Discourse!

I've updated the starter file accordingly. Please update the lesson as well, then close the issue.

**Comment by schanzer** [comment]
Actually nevermind - I'll take care of this, and fix the top/bottom challenge wording and starter files as well.

**Comment by flannery-denny** [comment]
@schanzer I know you made a new file, but I'm not seeing it in our shared fall2024 starterfile folder. Please move it there. Thanks!

**Comment by schanzer** [comment]
@flannery-denny It's already there. You made two sub-folders: "Files" and "Published Files". Both are where they ought to be.
