### ISSUE TITLE
Need to turn on warning about writing over slide decks

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1844]
Every deck we are building right now is generated using ` ./build-slide -z`.

in the effort to maintain the old infrastructure in case we can't get the new infrastructure to do everything we need it to, we are circumventing systems we designed to make sure the humans interacting with our automated stuff don't mistakes.

1. We need to be generating the same warnings that `./build-slides` generates.
2. With the workarounds I'm concerned we might not be saving slide ids for decks that have been checked off in the right place.

**Comment by schanzer** [comment]
@flannery-denny is right - the slides have reached a level of maturity where `-z` is no longer "experimental". Let's switch this over to the default behavior, and have -z just bring up a warning about deprecation for now.

**Comment by schanzer** [comment]
@flannery-denny test and close if you're happy?

**Comment by schanzer** [comment]
I'm going to go ahead and close, since this warning has saved me repeatedly already!
