### ISSUE TITLE
If the only image on a slide is in the Q we should not be selecting a slide format with an image

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1845]
For an example see Contracts-Tables-Displays

**Comment by schanzer** [comment]
@flannery-denny I checked out [the slides for that lesson](https://docs.google.com/presentation/d/1GVGeLvaIUc8aURiFOxFn2-2iOTK-VBDldjhZv_CvFbU/edit#slide=id.31eeceb1-c771-11ee-8702-ab1f4cf92e76) but don't see an example of this. Which slide number should I be looking at?

**Comment by flannery-denny** [comment]
@schanzer check out slide 18 - the second bug hunting slide - after a fresh pull.

**Comment by schanzer** [comment]
@flannery-denny here's the asciidoc that I think you're talking about:
```
@QandA{
@Q{What _hint_ does the error message give us about how to use this function?}
@A{@image{images/sort-error.png, 650}}
@A{The the sort function expects 3 arguments and its Domain is Table, String, Boolean. If we don't give it those three things we'll get an error instead of the sorted table we want.}
}
```

There are no images in the @Q at all! I'm pretty sure you meant to open this issue about @A, right?
