### ISSUE TITLE
benny-benson.jpeg has no attribution in lesson-images

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1846]
Now that Dorai has fixed the image building stuff, we're getting proper warnings about images again. Looks like we have one image that was added recently, without providing attribution in the `lesson-images.json` folder for `transform-compose-images`.

Flannery, were you the one who added this image? If so, hopefully you have the sourcing information!

**Comment by flannery-denny** [comment]
@schanzer I've just pushed an attribution, but it feels pretty unlikely that I didn't update the lesson-images.json file when I originally added the image in the fall... which makes me a little nervous. Is there anyway to go back to the commit when the image was added and verify?

**Comment by schanzer** [comment]
@flannery-denny I started at [the page itself on github](https://github.com/bootstrapworld/curriculum/blob/fall2024/lessons/Algebra/transform-compose-images/langs/en-us/images/lesson-images.json), and then clicked the "history" button
![image](https://github.com/bootstrapworld/curriculum/assets/77126/28595661-5b8b-4763-9b50-0a1256e6b26c)


I walked backwards through the commits, and [found this one](https://github.com/bootstrapworld/curriculum/commit/4d46c4f981dec5aac6bd1bf3d915cdea972e63a4) where you added the info!

Looks like this was [lost during a merge conflict](https://github.com/bootstrapworld/curriculum/commit/e0f06a05b4b28b018161bbd9647639115d384ada) when the flags project was updated.
