### ISSUE TITLE
add instruction to flags project re: 2 approaches

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1848]
show side-by-side code screenshots

**Comment by retabak** [comment]
@schanzer - I'm working on this text and find that I'm running into an issue, namely: are we contradicting ourselves?

In response to a question from Nancy Cousins on [discourse](https://discourse.bootstrapworld.org/t/interesting-approach-i-think-i-like-it-is-there-a-reason-why-i-shouldnt/2622) - "Interesting Approach - I think I like it, is there a reason I shouldn't?", you said this: 

---

Here’s the algebraic equivalent of these two solutions. See if you can spot which one your students are using:

**Method 1**

- x = f(5)
- y = g(x)
- z = h(y)

**Method 2**

- z = h(g(f(5)))

Both are totally correct, so your students of course deserve full credit! But you asked what the difference is, and @Joy_Straub hit the nail on the head: is function composition part of your learning goals? There’s no right or wrong answer that fits everyone – it’s entirely about what’s in the critical path for you.

---

Here's my issue. The text that I was planning to write re: "two approaches" was going to state that Method 1 is *NOT* function composition... but the first section of the function composition lesson - which we call "**Composing** Functions" - uses Method 1! We even throw around the term "path."

Maybe we should change the name of this section to "Chaining Functions"? Then, we could add some text (or even a Circle of Evaluation?) showing the chained functions being _composed_? Or, we could add this text + Circle to the Launch of the second section - "Composing Functions in Code"?

I can attempt to do this if you think it is a good idea. If you think I've confused myself and am too in the weeds, please tell me. Either way, let me know!

**Comment by schanzer** [comment]
@retabak the opening activity in that lesson doesn't say anything about "saving" the intermediate steps. It's exclusively about the order of function cards the kids would "play". The very next section ("diagramming") explicitly connects this to things like f(h(x)). 

I think adding a circle of evaluation to the first section, showing an example of how 2-3 cards could be played to get from one number to another is a GREAT IDEA. Go for it.

**Comment by retabak** [comment]
Huh. I'm genuinely surprised that you don't think "saving" is implied in an activity about "playing the cards".

I will add a Circle, though!

**Comment by schanzer** [comment]
@retabak I mean, do we explicitly tell kids to write the intermediate values anywhere? And more importantly, do we ever tell them to come up with unique names for each of the values?

**Comment by retabak** [comment]
Hey, @schanzer ! just added and checked something to address this. Take a look - send any feedback my way (or feel free to make changes).

**Comment by schanzer** [comment]
@retabak looks great! I left a comment about a typo, but otherwise this is ready to close!
