### ISSUE TITLE
Add new layout to slide builder: Investigate2T

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1849]
It's not uncommon for us to have a text box, an image below that, and a second text box below the image. Flannery has created a Layout for this, called `Investigate2T`.

Here's an example uses-case from contracts-tables-displays

```@slidebreak

@indented{
If we wanted to get extra fancy and see the species count for the youngest ten animals, we could add another layer to our Circle of Evaluation.

@show{(coe exp2)}
}

__Note: Values like Numbers, Strings, and Booleans are still written by themselves. It’s only when we want to use a function that we need to draw a Circle.__

@slidebreak```

The heuristic is "if there text, followed by an image or COE, followed by _more_ text...use Investigate2T"

**Comment by flannery-denny** [comment]
@schanzer So far I've only noticed two separate lesson instruction sections with an image in between in Investigate.  I've added a slide layout called **Investigate2T**. Please add it to the buildslide infrastructure

**Comment by schanzer** [comment]
@flannery-denny can you specify EXACTLY what a slide has, which will determine that it needs `Investigate2T`? Remember, we use heuristics to determine the best layout, so we need to know what to look for. Also helpful to identify which two lessons you're seeing it used

**Comment by flannery-denny** [comment]
@schanzer looks like the spec I wrote for this in #1714 got lost.

Most often we have:

> text - image - slidebreak.

This slide layout should be used when we have:

> text - image - text

Here's an example from `contracts-tables-displays`

```
@slidebreak

@indented{
If we wanted to get extra fancy and see the species count for the youngest ten animals, we could add another layer to our Circle of Evaluation.

@do{
(define exp2 '(count (first-n-rows (sort animals-table "age" true) 10) "species"))
}

@show{(coe exp2)}
}

__Note: Values like Numbers, Strings, and Booleans are still written by themselves. It’s only when we want to use a function that we need to draw a Circle.__

@slidebreak
```

**Comment by schanzer** [comment]
@flannery-denny I'm still not morally opposed to making another layout, but we agreed that we'd try really hard to stick to only the use cases that show up a reasonable number of times. If it's really just 2 times, then I think it's still worth exploring a workaround. The following works pretty well for me:

```
@slidebreak

@indented{
If we wanted to get extra fancy and see the species count for the youngest ten animals, we could add another layer to our Circle of Evaluation. +
@do{
(define exp2 '(count (first-n-rows (sort animals-table "age" true) 10) "species"))
}
@show{(coe exp2)}

@ifslide{
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty}
}
__Note: Values like Numbers, Strings, and Booleans are still written by themselves. It’s only when we want to use a function that we need to draw a Circle.__
}

@slidebreak
```

**Comment by flannery-denny** [comment]
@schanzer It happens enough times that after making the change by hand a
lot of times I proposed the fix - you asked me to flag things that occurred
repeatedly and I thought could be handled more efficiently with
improvements to the build script.

Because I was making the change by hand, I didn't track where they were.

I'm not sure where you got the idea that this happens twice. Perhaps
because I wrote that this is an issue when a slide has 2 text blocks?

@retabak and I can work with your workaround on all slides that have two
text blocks with an image in between for now and if you want to investigate
whether it's worth deploying a new layout in the future we can do a search
to see how often it gets used.

**Comment by schanzer** [comment]
@flannery-denny you wrote: 
> @schanzer So far I've only noticed two separate lesson instruction sections with an image in between in Investigate. I've added a slide layout called **Investigate2T**. Please add it to the buildslide infrastructure

I thought that meant you've only seen two separate instructions with an image in between _across all lessons_. Now I see you meant _in investigate_. :)

OK, if this is common then I think we should move forward. @ds26gte , I'll update the issue description.

**Comment by ds26gte** [comment]
This is going to very hard to devise a heuristic for?  I take it the image can be `@image` or something generated through `@show{(coe ...)}`, i.e., something that generated  a `$$$ html`?

I can think of counting blank lines (at least two successive newlines), and using it alongside number of images.  If there are at least two blank lines, and only one image (or `$$$ html`), and we know it is an `Investigate` and there is no other suffix generated by other means, I could make it an `Investigate2T`. Would that be good enough?

Another option, especially if this situation is very rare, is to use a directive that identifies the style. This directive will be a no-op for the usual preproc, but will come into its own only for slides.

RFD.

**Comment by schanzer** [comment]
@ds26gte could @slidebreak take an _optional_ argument, allowing authors to hardcode the layout?

**Comment by schanzer** [comment]
@flannery-denny I'm pretty sure this resolves the issue, but let us know if there's something that needs to be adjusted

**Comment by flannery-denny** [comment]
Thanks, @ds26gte! this is very exciting and will satisfy one of @retabak 's wishes from months ago. I've tested it with a number of layouts (including driver navigator) and it works great... except for with this one. 

The current functionality would clue authors in that they need to sort something out, and that's an improvement over what was happening, but I wonder if it could actually do what we want it to do?

Here's the asciidoc for the slide in question:

```
@slidebreak{Investigate2T}

@indented{
If we wanted to get extra fancy and see the species count for the youngest ten animals, we could add another layer to our Circle of Evaluation.

@do{
(define exp2 '(count (first-n-rows (sort animals-table "age" true) 10) "species"))
}

@show{(coe exp2)}
}

__Note: Values like Numbers, Strings, and Booleans are still written by themselves. It’s only when we want to use a function that we need to draw a Circle.__
```

and here's how it renders in slides.
<img width="1133" alt="Screen Shot 2024-02-23 at 9 45 27 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c0752afb-ceb0-47ed-b0d0-cd3fd681b64e">

See how there's an empty text field? I would expect the first set of text from the asciidoc to end up in that text field.

> If we wanted to get extra fancy and see the species count for the youngest ten animals, we could add another layer to our Circle of Evaluation.

**Comment by ds26gte** [comment]
@schanzer , is this your wheelhouse? The slides.mkd looks ok to me -- I don't know why an empty text box is being created

**Comment by schanzer** [comment]
@ds26gte @flannery-denny ooooof, this one's a doozy. Here's what's going on:

md2googleslides takes the result of `slides.mkd` (you can see it in the lesson folder inside `distribution`), and parses it to figure out the structure of the document. The parser is _really_ simple and primitive, and so far none of the improvements I've made to md2googleslides has required me to improve on that code. **Until now**

The issue is that the parser treats all the text in a slide as _one block of text_, even if it's interrupted by an image. So when it sees the slide in question, it thinks "okay, I've got one image and one big block of text with a few newlines between one paragraph and another." Changing the parser to treat these as separate blocks is hard, because what about slides like `LaunchR` where the image appears in the middle of the slide text? We want the image to go into the placeholder on the right, but in that case we _don't_ want to split up the text into separate blocks.

This is going to take some serious time on my part, and I'm running PD all day tomorrow and also trying to move ahead on some algebra2 authoring.  It's doable, but I can't promise to have it done this week. I suggest making this an April 1 milestone issue.

**Comment by flannery-denny** [comment]
@schanzer If it takes that much work, I vote we ask authors to deal with these slides by hand this year and revisit how much work it was next year.

**Comment by schanzer** [comment]
That is an _enormous_ relief. YES PLEASE! 🙏
