### ISSUE TITLE
get rocket-height starter file working with new context

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1854]
[https://code.pyret.org/editor#share=1MeDd3RYbJrxnkK3FmnXu5uMYRKRJ_PPw&v=0c33ff0](https://code.pyret.org/editor#share=1MeDd3RYbJrxnkK3FmnXu5uMYRKRJ_PPw&v=0c33ff0)

still works with 1.6 context

**Comment by schanzer** [comment]
@flannery-denny select "choose context" from the pyret menu, then paste in the Algebra 1.8 context.

**Comment by flannery-denny** [comment]
@schanzer - sorry to bother you with this. I had selected the context in the teachpak, but there were conflicts. Didn't realize you'd eliminated the need for the teachpak. Thanks!
