### ISSUE TITLE
@ifpathway not generating errors or behaving as expected in slide decks

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1857]
ds-intro on fall2024 has two instances where `@ifpathway` was used incorrectly and no error messages popped up after `make clean` and `make`. Can we make it so they do? I only discovered the incorrect uses because a stray @ifpathway appeared in a slide deck!

The incorrect use was this: @ifpathway{blah, blah, blah} rather than @ifpathway{data-science}{blah, blah, blah}

UPDATE .... hm, even after I corrected the misuse of `@ifpathway`, it still appeared in the slide deck.

**Comment by ds26gte** [comment]
How do we want to treat `@ifpathway` in slides? As far as I can tell, there is no way for the slide-making code to predict which pathway to use...

**Comment by retabak** [comment]
Agreed. I think the best option is to have it disappear completely from slides? But maybe @flannery-denny or @schanzer want to weigh in?

**Comment by schanzer** [comment]
@ds26gte can we have that content moved to presenter notes, prefixed with "IF PATHWAY = XYZ{.....}

**Comment by schanzer** [comment]
@ds26gte can we get a warning if the directive is used improperly?
