### ISSUE TITLE
can code text appear in slides the same way that it does in lessons?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1858]
In grouped-samples on fall2024, the text below appears with correct line breaks and in code font in the lesson:

```
  name = "Flannery"
  age  = 16
  logo = star(50, "solid", "red")
  sasha= row-n(animals-table, 0)
```

In the slide deck, however, the font is still Century Gothic and there are no line breaks. Again, it's not much trouble to fix this manually, but calling it out anyhow in case it can be fixed.

**Comment by ds26gte** [comment]
If using AsciiDoc's block indent method to generate code displays, please use four spaces so they are valid for Markdown. Otherwise, use AsciiDoc's `----` (four hyphens) as code fences, and they will be appropriately converted.

**Comment by schanzer** [comment]
@retabak can you test this out and close if it's fixed?
