### ISSUE TITLE
images wrapped in @ifproglang not triggering correct slide layout

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1861]
In linear-regression (fall2024):

For slides 11 through 14 (asciidoc lines 168-220), I use this code repeatedly:
```
@ifslide{
@ifproglang{pyret}{@right{@image{images/lr-explained.png, 400}}}
@ifproglang{codap}{@right{@image{images/codap-lr-explained.png, 400}}}
}
```
Each time that I use it, the image is randomly positioned on the slide, on top of the text. 

I would expect it to be on the right of the slide, using the LaunchR template. (See it on slides 11-14 [here](https://docs.google.com/presentation/d/1O6y3VnXma1MJOrvziQFGInh94NcSmEIwcMd1o2EoHZA/edit#slide=id.f8de4d06-d00b-11ee-a445-037a6c95b1f2).)

To test whether @ifproglang might be the source of the issue, Emmanuel tried using this code instead: `@right{@image{images/lr-explained.png, 400}}` on slide 10 (asciidoc lines 158-166). As you can see, the proper layout was triggered on slide 10.

**Comment by schanzer** [comment]
@ds26gte it looks like wrapping the image inside @ifproglang caused the parser to miss the image positioning hint
