### ISSUE TITLE
@opt rendering correctly in slides but not in lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1863]
In box-plots fall2024, this asciidoc text 
```
- @opt{Complete @opt-printable-exercise{pages/matching-boxplots-to-histograms-2.adoc} and/or the Matching Box Plots to Histograms slide of @opt-starter-file{boxplots}}
```

does what I would expect in the slide deck ( a teacher note beginning with _Optional_ )... but in the lesson, here is what I'm seeing:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/a81e9bf5-b9b0-4b6e-8080-5c8c41f3c940)

Not sure if this is an issue elsewhere.

**Comment by schanzer** [comment]
Confirmed fixed!
