### ISSUE TITLE
Save slide decks on Google Drive and update slide ids

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1864]
**This should not be completed until after** 
- [x] #2002

**_When this issue is complete, read and close #1679_ **

RT 

- [x] advanced-displays
- [x] bar-and-pie-charts 
- [x] checking-your-work
- [x] contracts 
- [x] contracts-tables-displays 
- [x] contracts-wescheme
- [x] coordinates
- [x] coordinates-wescheme
- [x] defining-table-functions
- [x] defining-values
- [x] defining-values-wescheme
- [x] distance-formula
- [x] distance-formula-wescheme
- [x] inequalities-collision 
- [x] inequalities-collision-wescheme
- [x] inequalities1-simple  - some weird stuff happening
- [x] inequalities1-simple-wescheme - weird stuff
- [x] inequalities2-compound
- [x] inequalities2-compound-wescheme
- [x] inequalities3-sam
- [x] inequalities3-sam-wescheme
- [x] making-game-images
- [x] making-game-images-wescheme
- [x] numbers-inside-video-games
- [x] numbers-inside-video-games-wescheme
- [x] order-of-operations
- [x] order-of-operations-wescheme
- [x] piecewise-functions-conditionals
- [x] piecewise-functions-conditionals-wescheme
- [x] player-animation 
- [x] player-animation-wescheme
- [x] function-composition
- [x] function-composition-wescheme
- [x] function-definition-linear
- [x] function-notation
- [x] function-notation-wescheme
- [x] functions-can-be-linear  - pending #2047
- [x] functions-can-be-linear-wescheme
- [x] functions-dr
- [x] functions-dr-wescheme
- [x] functions-examples-definitions
- [x] functions-examples-definitions-wescheme
- [x] functions-for-character-animation
- [x] functions-for-character-animation-wescheme
- [x] functions-make-life-easier
- [x] functions-make-life-easier-wescheme
- [x] functions-vertical-line-test
- [x] functions-vertical-line-test-wescheme
- [x] problem-decomposition
- [x] problem-decomposition-wescheme
- [x] surface-area-rect-prism
- [x] surface-area-rect-prism-wescheme
- [x] threats-to-validity
- [x] transform-compose-images
- [x] transform-compose-images-wescheme
- [x] composing-table-operations

ES

- [x] standard-deviation
- [x] standard-deviation-codap
- [x] scatter-plots
- [x] scatter-plots-codap
- [x] histograms
- [x] histograms-codap
- [x] linear-regression 
- [x] linear-regression-codap 
- [x] measures-of-center 
- [x] measures-of-center-codap
- [x] box-plots  
- [x] box-plots-codap
- [x] ds-intro
- [x] ds-intro-codap
- [x] dot-plots-bar-charts-codap
- [x] grouped-samples
- [x] grouped-samples-codap
- [x] probability-inference
- [x] probability-inference-codap
- [x] data-cycle 
- [x] data-collection
- [x] visualizing-the-shape-of-data
- [x] visualizing-the-shape-of-data-codap
- [x] correlations 
- [x] correlations-codap 
- [x] choosing-your-dataset 
- [x] choosing-your-dataset-codap
- [x] data-collection-codap
- [x] data-cycle-codap
- [x] ethics-privacy-bias-codap
- [x] ethics-privacy-and-bias
- [x] codap-building-codap
- [x] codap-composing-codap
- [x] codap-dot-plots-bar-charts-codap
- [x] codap-exploring-codap
- [x] codap-filtering-codap
- [x] lookups
- [x] simple-data-types
- [x] simple-data-types-wescheme
- [x] combinatorics-combination 
- [x] combinatorics-combination-wescheme
- [x] combinatorics-permutation 
- [x] combinatorics-permutation-wescheme
- [x] debugging 
- [x] debugging-wescheme
- [x] computing-needs-all-voices 
- [x] computing-needs-all-voices-wescheme
- [x] distributive-property
- [x] computing-needs-all-voices-codap
- [x] associative-property
- [x] equivalence
- [x] evaluating-exponents
- [x] exponent-expressions-with-negatives
- [x] identity-property
- [x] commutative-property
- [x] translating
- [x] variables
- [x] absolute-value-and-opposites
- [x] absolute-value-and-opposites-2
- [x] additive-inverse
- [x] multiplicative-inverse
- [x] exploring-exponential-models
- [x] exploring-linear-models
- [x] exploring-logarithmic-models
- [x] exploring-quadratic-models
- [x]  re-adding-collisions
- [x] re-adding-levels
- [x] re-build-your-own-animation
- [x] re-functions-that-ask-questions
- [x] re-intro-to-data-structures
- [x] re-key-events
- [x] re-making-pong
- [x] re-nested-structures
- [x] re-refactoring
- [x] re-scoring
- [x] re-structures-reactors-animations
- [x] re-timers
- [x] re-your-own-drawing-functions

No Slides To be Built
- [ ] hoc-data
- [ ] hoc-wescheme-intro
- [ ] hoc-winter
- [ ] hoc-winter-parley

**Comment by retabak** [comment]
@schanzer - I am done! ... except for functions-examples-definitions (pyret & wescheme), because I cannot figure out what is going wrong in those slides.  Can you take a look?

https://docs.google.com/presentation/d/1hdK_ghMv5JnwyZors3GYWyscwRsURfWpyPTVw5oZNNY/edit#slide=id.b3189c03-04de-11ef-8aa9-e59f29e48509
