### ISSUE TITLE
Make Videogame pathway

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1865]

**Comment by flannery-denny** [comment]
@schanzer I really think we need to make Sam the Butterfly independent of the fleshed out simple and compound inequality lessons

**Comment by schanzer** [comment]
@flannery-denny Take a look at [this commit](fb497f97780322cc8c37293acc085f9113dce545), and let me know if it does what you want?

**Comment by flannery-denny** [comment]
@schanzer that link doesn't work, but I just looked at the pathway and made a few adjustments. I am satisfied.
