### ISSUE TITLE
table from @strategy box needs to make it to slide deck, even if only as a link

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1868]
bar and pie charts slide 10 has an optional extension that is described in a strategy box which includes the table and that table is missing

**Comment by schanzer** [comment]
@flannery-denny strategy boxes are not supposed to wind up in slides, right? If this is supposed to be student-facing, it should not be in a strategy box

**Comment by schanzer** [comment]
@flannery-denny also, it looks like you wrapped that strategy box in @ifnotslide on Jan 18th, which would guarantee that it will never show up on slides at all.

**Comment by flannery-denny** [comment]
@schanzer I thought we decided that all strategy boxes are supposed to end up in presenter notes, which is what's happening. I removed the @ifnotslide because it's no longer necessary.

**Comment by schanzer** [comment]
@flannery-denny ah, NOW I understand what you're saying. The issue title and description totally threw me off. I'm going to open a new issue and close this one (see #1876).
