### ISSUE TITLE
Histogram lesson asks kids to make box plots

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1869]
Not sure how this happened, but it should be fixed ASAP.

<img width="773" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/de354bc2-3ac0-4b3d-a91c-4c34242dc625">

The linked wbpage above isn't even from this lesson, but it IS listed as required here.

**Comment by flannery-denny** [comment]
@schanzer I had flagged this in the workbook pages a while back and I'm pretty sure you tackled it...

**Comment by flannery-denny** [comment]
Possible it only got updated on fall?
