### ISSUE TITLE
Workbook cover/front matter/formatting fixes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1870]
- [x] Title page of the solution book says "Student Workbook w/ Solutions" - cover should do the same
- [x] Currently front cover is appearing on the back
- [x] update workbook version
- [x] remove colleen murphy
- [x] landscape pages should have titles oriented toward the spine of the book

**Comment by schanzer** [comment]
@flannery-denny what does the first checkbox mean?

The cover already says "Student Workbook w/ Solutions".

![image](https://github.com/bootstrapworld/curriculum/assets/77126/e3025de4-cab6-4cc2-acc6-abdbc3ba2e5f)

**Comment by flannery-denny** [comment]
@schanzer Not for Oklahoma
![IMG_1236](https://github.com/bootstrapworld/curriculum/assets/66691020/045978b6-217e-4758-ad8b-4a66218ed281)

**Comment by schanzer** [comment]
@flannery-denny confirming this is fixed. Ready to close?
