### ISSUE TITLE
Standardize solutions for matching activities

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1871]
@ifsolnchoice has done a beautiful job of consistently and clearly rendering multiple choice solutions with a checkmark.

We need to come up with a similar directive for matching activities that standardizes formatting and make it more readable.

Currently I see all of the following in the workbook:

- 1 _(A)_
- 1_(A)_
- 1- _A_
- 1- _(A)_

Honestly, none of them are easy to read. 
A directive would allow us to make the visual clearer. Perhaps adding an arrow? or a box?

**Comment by schanzer** [comment]
Closing as fixed in the PR
