### ISSUE TITLE
Every Data Cycle wbpage should include a @teacher{} that gives away the question type

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1872]
Without having thought about it very hard, I would guess that most of the time, even if we don't know what student a question is going to write on a datacycle we can predict what the question type will be, given what we've asked them to do. 

Are there any other parts of the data cycle that we could fill in for teachers?

**Comment by retabak** [comment]
FYI - I think this is a good idea. You might want to check out #1888, as it is data cycle-focused. I'm making sure that there are always 2 animals data cycle preceding the "chosen dataset" data cycle. On the animals data cycles, we are also always providing the first *question* - which means we can also provide solutions for the first data cycle.

This is part of a bigger goal to make sure students are prepared to write appropriate questions for each given display (which I think is one of the most challenging steps).
