### ISSUE TITLE
Bug in code rendering

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1873]
` @showsoln{(code expr1 #:parens true)}`

is currently rendering `{zwsp}` for many of the parentheses on several pages in the workbook, including

- [ ] order-of-operations/complete-code-from-coe-parens
- [ ] logic errors 2
- [ ] logic errors 3

**Comment by ds26gte** [comment]
Where is this `{zwsp}` showing up? I can't see it in either the HTML or the PDF version of the first example cited

**Comment by flannery-denny** [comment]
@ds26gte Interesting. On my local build I see the first instance:

- the html version in the solution pages folder of order-of-operations/complete-code-from-coe-parens
- in the OK workbook-soln 

Interestingly, when I look at the individual PDF version in the solution pages of the lesson folder, the solutions are completely missing!

**Comment by schanzer** [comment]
@flannery-denny this is actually the correct behavior for how the document is written: you're using the "helpful" asciidoctor shortcut that shows everything vebatim (including zero-width-spaces!): you've chosen to indent the `@showsoln` directive.

I'm guessing that's not what you meant, so I removed the indentation and everything looks like it should. I also took the liberty of adding a CSS rule to format the code-missing-parens text as code

**Comment by flannery-denny** [comment]
Thanks @schanzer! looks great :)
