### ISSUE TITLE
Consider where else solution pages should visibly say "Teachers:"

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1874]
I'm seeing this formatting used in the Order of Operations lesson. It is quite effective! 

@ifsoln{*Teachers:* the answers below are shown with only the _necessary_ parentheses. If a student chooses to add additional (correct) parentheses, they will still have the correct answer.}

1. I would encourage us to use it more!
2. I wonder whether we should have a new directive `@ifsolnnote` that standardizes formatting for sentences we add for teachers that aren't actually solutions.

**Comment by schanzer** [comment]
@flannery-denny this has been implemented in d7d38ce04

**Comment by flannery-denny** [comment]
@schanzer It looks like `@teacher` adds extra vspace between the lines. 
See order-of-operations/ 3 columns 3
On workbook pages, spacing of directions to the student and these notes to the teacher should be identical.

**Comment by schanzer** [comment]
@flannery-denny Where do you see extra vspace being added? All I see is "more lines of text = longer page = doesn't fit"

**Comment by schanzer** [comment]
@flannery-denny now that the vspace issue is fixed, I assume you no longer need me attached to this issue?
