### ISSUE TITLE
Deploy @ifsoln choice on the following pages

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1875]
- [x] Identifying Functions from Graphs
- [x] Identifying Functions from Graphs (2)
- [x] How Tables Fail the Vertical Line Test
- [x]  Identifying Functions from Tables
- [x]  Identifying Functions from Tables & Graphs
- [x] Are all graphs linear?
- [x] Linear nonlinear or bust?
- [x] What kind of error?
- [x] Permutation
- [x] Combinations

**Comment by schanzer** [comment]
@flannery-denny ready for your review

**Comment by flannery-denny** [comment]
@schanzer thanks. These are much clearer.
