### ISSUE TITLE
Add CSS rules to put solutions at bottom of table

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1879]
- [x] Circles of Evaluation - Notice and Wonder
- [x] Expressions -> Circles of Evaluation

@schanzer I'm working on these pages on the `wkbk-solns` branch

**Comment by schanzer** [comment]
@flannery-denny I never got to ask you in our zoom -- there are a ton of files matching the second checkbox, but the solutions there are all Circles of Evaluation, which are positioned in the center of the table cells. Am I interpreting this correctly?

**Comment by schanzer** [comment]
@flannery-denny code inside solutions is now italicized (see more-practice-w-lookups)!

**Comment by flannery-denny** [comment]
@schanzer please apply the same change to math expressions. Right now numbers inside @ifsoln are italicized but number formed by way of @showsoln{expr1} don't get italicized.

**Comment by schanzer** [comment]
@flannery-denny I can't style those due to a separate issue, which I'm tracking here on https://github.com/bootstrapworld/curriculum/issues/1886
