### ISSUE TITLE
make book COURSE=algebra-pyret is not consistently generating new pdfs after changes in asciidoc

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1880]
I am getting updated html versions when I `make book COURSE=algebra-pyret` and not necessarily getting updated PDFs of the solution pages.

I made some changes to the directions of image-contracts. saved an built and the html updated by the pdf did not.

I did the same on the wescheme version of the file and `make book COURSE=algebra-wescheme` worked as expected.

After several attempts, currently making clean to see the pyret version of the pdf.

**Comment by schanzer** [comment]
@flannery-denny can you provide some more detail, to help Dorai and I reproduce this?

**Comment by ds26gte** [comment]
I found a bug related to solution-pages by experimenting -- but it seemed to affect HTML too, not just PDF (so `make book` wasn't necessary to witness it). Not 100% sure it's the same bug as yours. Please pull and re-try

**Comment by schanzer** [comment]
Tagging @flannery-denny to make sure she sees this

**Comment by flannery-denny** [comment]
Sorry for the slow response on this @ds26gte. I don't know how to test it. I'm going to close and will let you know if it resurfaces.
