### ISSUE TITLE
Add comments to css rules in asciidoc to track what they're inteded to do.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1885]
- [x] Alg2 pages have large chunks of CSS at the top. Please annotate them.

I was thinking about how to achieve something with css today and looked for a page that might have pulled something similar off. I came across two different pages that might serve as a reference and noticed that one of them actually had comments in the css!

```
/* Give more space for the bottom row */
table { grid-template-rows: 2fr 3fr !important; }

/* Force the code solution to the bottom of the row */
.content .paragraph:nth-child(3) p { position: absolute; bottom: 0; }
```

We teach that it's important to leave comments, but very few of the css rules that get added to pages get anotated in a way that humans can follow them. 

As a result:

1. It's hard for new to css authors to learn from what's there.
2. We regularly end up with old css rules that don't serve a purpose but don't get deleted because nobody knows what they're intended to be doing so we just keep adding, rather than pruning.

**Comment by retabak** [comment]
I like this idea! I feel like I'm making bad guesses about CSS rules all the time.

**Comment by flannery-denny** [comment]
@schanzer I've added comments to the css I've written... I think the rest is you... for someday when you're not sure what to do with all your spare time and energy ;)

**Comment by schanzer** [comment]
@flannery-denny what does "done" look like here? Every single rule has a comment? Some of them?

**Comment by flannery-denny** [comment]
step 1: comment all rules as we add them moving forward.
step 2: comment all rules/groups of rules that get used multiple times throughout our materials
step 3: add comments to one-off css rules any time a page gets reworked.

Would it be helpful if @retabak and I make a checklist in this issue, adding specific pages as we encounter ones with lots of css we're not clear about?

**Comment by schanzer** [comment]
@flannery-denny oooooh YES

**Comment by schanzer** [comment]
@flannery-denny FYI I've now completely commented everything in Algebra 2 that I can imagine being in need of a comment. :)

**Comment by flannery-denny** [comment]
@schanzer thanks for this!  @retabak fyi - I'm closing this in favor of making issues about specific files in need of rules as they pop up.

Moving forward let's all try to get better about commenting as we add rules
