### ISSUE TITLE
please add css to shade the code block in chinese flag

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1894]
I tried a lot of things... and can't wait to see what you come up with :)
<img width="970" alt="Screen Shot 2024-02-23 at 2 01 18 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ebaf9129-f206-4494-a847-85a410374605">

**Comment by schanzer** [comment]
@flannery-denny take a look at the commit?

**Comment by flannery-denny** [comment]
Shading looks great. Thanks!
