### ISSUE TITLE
Rethink @Q{What do you notice? _Answers will vary._} convention

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1897]
We agreed as a team that we would format questions with varied responses as follows:

```
@QandA{

@Q{What do you notice? _Answers will vary._}
@A{Both of the examples do the same thing, even though the numbers are given in a different order.}
@A{It's a piecewise function!}
@A{It uses inequalities.}

@Q{What do you wonder?}

}
```

but that means that slides look like this, which feels odd to me. 

<img width="884" alt="Screen Shot 2024-02-24 at 5 09 32 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/e76442ac-39ed-4cb0-b057-25b05d6ae102">

I believe that @schanzer objected to putting _Answers will vary._ as the first A for some reason?

**Comment by schanzer** [comment]
@flannery-denny honestly I don't remember ever agreeing to that convention! Or objecting to having that as the first `@A`, for that matter. And if we DID agree to it, that clearly needs to change for slides.

Let's make this the `@A`. Change as you see fit.

**Comment by retabak** [comment]
I don't quite remember agreeing to that either! I've been adding _Answers will vary_ to the first @A (I think!?). I'll make sure to be consisten about it moving forward.

**Comment by retabak** [comment]
@flannery-denny @schanzer - I just discovered that, in the past, when answers in @QandA have varied, I have often started the @A with "Possible responses:" or "Possible response:"  (There are 32 instances of this - mostly me!) Should I got back and change this wording to say "Answers will vary"? Is that the exact wording we want every time?

**Comment by schanzer** [comment]
@retabak @flannery-denny personally I'm not bothered by prose differing slightly, but I don't feel strongly either way. I say pick a phrasing that works, and standardize it across the materials. I'll open a Git issue for it, since this one is complete
