### ISSUE TITLE
comments are passing through to slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1898]
Here's an example from the distance-formula lesson
<img width="650" alt="Screen Shot 2024-02-24 at 5 16 55 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/4ee70baa-789b-4cc5-98fe-28698470bd5f">

**Comment by schanzer** [comment]
lua parsing again!

**Comment by schanzer** [comment]
Confirmed fixed!
