### ISSUE TITLE
\sqrt isn't rendering in slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1899]
This code looks fine in the distance-formula lesson plan

```
@center{@big{@math{c = \sqrt{a^2 + b^2}}}}

@QandA{
@Q{How could we use the equation to find the distance between these two pyret characters?
@center{@image{images/characters-on-grid.jpeg, 400}}}
@A{@math{c = \sqrt{8^2 + 6^2}}}
@A{@math{c = \sqrt{64+36}}}
@A{@math{c = \sqrt{100}}}
@A{@math{c = 10}}
}

```

but here's what I'm seeing in the slides 
<img width="1029" alt="Screen Shot 2024-02-24 at 5 20 50 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/8253281c-8bbe-43c4-afa0-186b0c5707e0">

**Comment by schanzer** [comment]
@ds26gte definitely in your wheelhouse...

**Comment by ds26gte** [comment]
The Unicode version of `\sqrt` was using enclose-span which won't work for slides.

I've added a fix whereby any `@math` with `\sqrt` uses mathjax for slides, but if there is a way to get the CSS class `.overbar` working in slides, we could once again use Unicode
