### ISSUE TITLE
Google import issues

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#190]
Depending on how involved this gets, we may need to create a separate adoc->html generator for the google-importable pages. 
- [x] generate absolute URLs (can this be done serverside with `mod_substitute`?)
- [x] in lieu of the standards menu in the lesson summary table, just print "standards", and then list *all* of the standards.
- [x] Remove `<!-- include /menubar.ssi -->`
- [x] Generate this button on *all* exercise/workbook pages.
- [x] Wrap all `<h2>` tags inside `<strong>`

**Comment by ds26gte** [comment]
Wrapping `<strong>` around `<h3> ... <h6>` too.

**Comment by schanzer** [comment]
Closing this, since all the critical stuff is resolved. I'll re-open separate issues in the future as they arise, but none are as high priority as what was completed here.
