### ISSUE TITLE
@centered-image directive isn't working in slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1900]
Here's what I'm seeing on  inequalites2-compound 
<img width="858" alt="Screen Shot 2024-02-26 at 1 01 25 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/5ae3c063-1f1e-4cdf-9120-c6c92ff49492">

**Comment by retabak** [comment]
@ds26gte - this feels similar (but definitely not the same) to what I reported in #1891

**Comment by schanzer** [comment]
Confirmed fixed
