### ISSUE TITLE
Please add investigate-rp to slide build 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1902]
I noticed that we weren't getting `Investigate-RP` for a slide on inequalities3-sam that had a role play... in looking up what the theme name should be from the theme builder I realized template didn't exist! 

I've added it to the deck.

Please add it to the list of choices being utilized in the behind the scenes magic. Thanks!

**Comment by schanzer** [comment]
Confirmed fixed
