### ISSUE TITLE
Multiple issues in slide generation for lookups lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1904]
**Issue 1:** nested presenter notes on a slide are incorrectly treating an image as being part of the presenter notes (see below)

Here's what I'm seeing on the slide deck for Lookups from this code

```
@QandA{
@Q{How many rows do we need to answer a Lookup question?}
@A{Just one! Lookups can be answered just by finding the right row!}
}

@teacher{
Make sure sure students understand we only need one row!
}

@right{@image{images/AskQuestions.png, 100}}
**What code can we write, to let us define a single row?** 
```

<img width="880" alt="Screen Shot 2024-02-26 at 1 44 20 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/63b2c4e6-9a8e-496e-8fa5-135bc213266d">

**Issue 2:** image links that belong in teacher notes are not being displayed as links, but rather just the URL as text

**Issue 3:** image links that belong in teacher notes are not being anonymized

**Comment by ds26gte** [comment]
Added fixes for (sub-)issues 1 and 3.

Re (sub-)issue 2: Since teacher notes are HTML comments, the image files they refer to are just URLs, no? How can they be (clickable) links?

**Comment by schanzer** [comment]
@ds26gte they are not HTML comments. It's pure coincidence that the md2googleslides spec uses the same delimiters for presenter notes.

**Comment by ds26gte** [comment]
Wrapping a link URL in `<...>` is the Markdown idiom for a link whose link text is the link URL itself. I've used this format to translate images in teacher notes. Please check if it is satisfactory.

**Comment by schanzer** [comment]
@ds26gte Much better. Hate to ask for more, but...can we use "click to see embedded image" as the linktext?

**Comment by schanzer** [comment]
@ds26gte see my latest commit - it certainly resolves this issue, but I'd like to make sure you don't see it breaking anything else. Close if you're happy?

**Comment by ds26gte** [comment]
LGTM
