### ISSUE TITLE
Can we throw a better warning for stray quotation marks?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1906]
```
@teacher{
Some students should have nothing to do. Others should look confused as to what to do. They may be wearing sneakers and pants and not be able to put their hands on their head and on their hips at the same time. They may be wearing a T-shirt and not be able to make a T and an O with their arms simultaneously.

Observe that this set of rules doesn't seem to have worked quite as well as the last. Debrief how students decided what to do. Example Questions:

- Ask a student wearing a T-shirt with their arms making an O... "I see that you're wearing a T-shirt - why aren't you making a T with your arms?"
- Ask a student wearing pants and sneakers... "Why don't you have your hands on your head and your hips?"
- Ask a student who isn't doing anything... "Why aren't you doing anything?""

}
```

That extra closing quote broke my build and had me chasing all over the place. 

The errors I got were quite unhelpful

```
ERROR: ERROR: read-group: Runaway directive teacher in "distribution/en-us/lessons/piecewise-functions-conditionals/index.adoc"

asciidoctor: ERROR: .index.asc: line 7: include file not found: /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/piecewise-functions-conditionals-wescheme/.cached/.index-sidebar.asc
asciidoctor: ERROR: .index.asc: line 40: include file not found: /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/piecewise-functions-conditionals-wescheme/.cached/.index-extra-mat.asc
asciidoctor: ERROR: .index.asc: line 7: include file not found: /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/piecewise-functions-conditionals/.cached/.index-sidebar.asc
asciidoctor: ERROR: .index.asc: line 40: include file not found: /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/piecewise-functions-conditionals/.cached/.index-extra-mat.asc

```

**Comment by ds26gte** [comment]
- Would you like the reading of things like `@teacher`'s arg to be lax about quotation marks? (They are more important really for the arg of `@show`, because that is a Scheme expression, and matching quotation marks are more important there. **_--OR--_**

- Would you like the error message to explicitly mention the possibility that there could be a stray quotation mark?

**Comment by schanzer** [comment]
@ds26gte I vote for being lax about quotation marks, but I could live with amending the error to suggest looking for unmatched quotes

**Comment by retabak** [comment]
I do not have a strong opinion! Sorry. Fine either way.

**Comment by ds26gte** [comment]
Made reading of `{...}` argument lax w.r.t. quotation marks except when it's known to be reading Scheme code.

(This does mean that any mismatched quotation marks will make it into the final output. This is not necessarily wrong, as English prose does allow use of unmatched quotation marks.)

**Comment by flannery-denny** [comment]
@ds26gte I think it would be better not to be lax! and to throw a better warning.

**Comment by schanzer** [comment]
OK, well close when you're happy :)

**Comment by flannery-denny** [comment]
Sorry. Didn't realize I was disagreeing with @schanzer here... Authors can fix stray quotation marks that make it through. Great not to have the build break.
