### ISSUE TITLE
can slides preserve line breaks in `@show{(code` blocks?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1907]
This code

```
@show{
(code '(define (red-shape shape)
  (cond
    [(string=? shape "circle")     (circle 20 "solid" "red")]
    [(string=? shape "triangle")   (triangle 20 "solid" "red")]
    [(string=? shape "rectangle")  (rectangle 20 20 "solid" "red")]
    [(string=? shape "star")       (star 20 "solid" "red")]
	[else (text "Unknown shape name!" 20 "red")])))
}
```

Renders beautifully in the lesson plan

<img width="504" alt="Screen Shot 2024-02-27 at 7 22 48 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/6ee529a6-63ba-474f-a0fd-dfc7417d1d7c">

but produces a giant runon in slides
<img width="726" alt="Screen Shot 2024-02-27 at 7 24 28 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/95d76e63-1234-415e-9098-d92d0988efd5">

**Comment by retabak** [comment]
@flannery-denny - you might want to try out the fix in #1858 ?

**Comment by flannery-denny** [comment]
Thanks @retabak. This code is being generated differently than that, but it was worth a look!

**Comment by ds26gte** [comment]
Oy vey, this is a tough one. The code is being passed through a Scheme->Pyret translation, and that output is set my codemirror, which we don't have in slides.

**Comment by schanzer** [comment]
@flannery-denny shouldn't be too tricky

**Comment by schanzer** [comment]
@ds26gte I've pushed a first pass at this. There's a good chance I'm not using `stdin` and `stout` properly, but I'm sure a quick zoom between us can resolve that.

**Comment by ds26gte** [comment]
@schanzer, am using new branch `slides-codemirror` so that we can ensure the handshake between the JS and Racket code can be debugged thoroughly before being pushed to `fall2024`

**Comment by schanzer** [comment]
Woohoo! confirmed fixed
