### ISSUE TITLE
`{two-colons}` is passing through as words to slides rather than as ::

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1908]
This renders as expected in the function-composition lesson plan but not in slides. 
@show{(code 'image=?)}`{two-colons} Image, Image -> Boolean`

I'm going to swap out the code for `@show{(contract 'image=? '(Image Image) "Boolean")}` but flagging in case it might have other repercussions

**Comment by ds26gte** [comment]
Hmm, I first thought this was an autogenerated `{two-colons}`, but it's an explicitly written in the source...? 

I can still modify it. Are we using any other explicit `{...}` AsciiDoc attributes in our source files?

**Comment by flannery-denny** [comment]
Honestly not sure. We used to have a lot of {two-colons} before you made the contract directive. I'd guess that the instances where we can't use `@show{(contract` are in workbook pages, which are irrelevant for slides. Perhaps we can resolve all of the instances in lesson plans by deploying `@show{(contract`?  

My find and replace skills aren't up to that being a very efficient task.

**Comment by schanzer** [comment]
Confirmed fixed!
