### ISSUE TITLE
`[.sideways-pyret-table]` is bleeding through to slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1910]
I'm seeing this in `function-definition-linear`
<img width="1324" alt="Screen Shot 2024-02-27 at 10 41 11 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b3ac99a6-a6b0-4d67-8b76-8c0a4ec80bae">

**Comment by schanzer** [comment]
@ds26gte hoping this is easy to regexp for...
