### ISSUE TITLE
@image text creates an extra (unneeded) line break in slide decks

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1916]
I've encountered this many time, but here is one example from identity-property on fall2024:

asciidoc text:
```
We just talked about four different functions. Each one consumed a number and produced a number. But what about functions that consume images? Can the Identity Property apply to those?

@QandA{
@right{@image{images/dog.png, 125}}

@Q{What functions do you know that will transform this image?}
@A{Sample responses: `scale`, `rotate`, `overlay`, etc...}
@Q{What is something we can do to this dog (right) that will _transform_ it... but still result in the *exact same image*?}
}
```

Image in lesson:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/4a7271d9-df39-4779-861d-0616768a22f3)

Image in slide deck:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/05ea9e9a-4bca-4db7-ba1d-d20a4e09b8c0)

it's not that much trouble to delete the extra line break manually, but if we didn't need to, that would be great!

**Comment by ds26gte** [comment]
This is actually correct behavior: The image is set above the list, and is then moved and floated right, but it can't eat any block-separators in its original location.

A remedy is to place the `@image` call in a position where it won't harm, e.g.,

```
@QandA{
@Q{What functions do you know that will transform this image?@right{@image{images/dog.png, 125}}}
@A{...}
@Q{...}
}
```

I think it even makes sense to keep the `@image` call close to where it's referred to.

**Comment by retabak** [comment]
Thanks, @ds26gte ! This is helpful.
