### ISSUE TITLE
in slide decks, can COEs always have a white background?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1917]
In lesson plans, it makes sense for the background to sometimes be grey, because the COEs are in @lesson-instruction{} or @QandA{}

In slide decks, the background is  *always* white and *never* grey, so it looks weird when COE images have grey backgrounds. 

Screenshot from evaluating-exponents lesson:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/8f925186-2b45-45af-b159-f1c1cdfb86ce)

and from the slide deck:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/b56b45da-cf6a-4af4-927e-f4ef4c47c88e)

**Comment by schanzer** [comment]
@retabak the circles in your screenshot clearly have white backgrounds. Is your concern that the _Q&A blocks into which the circles are embedded_ have gray backgrounds?

**Comment by schanzer** [comment]
@retabak and @flannery-denny I fixed what I think the real issue is. Let me know if I misunderstood?
