### ISSUE TITLE
in lessons, big COEs build with nested circles side-by-side... but in slide decks, circles get stacked vertically!

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1919]
is that expected?

example below from distributive-property (fall2024):

lesson:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/d00bfa4a-d573-4104-90c4-7dca8d9b9e95)

slide deck:
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/bb068a4b-9bfa-4e5a-b16d-20f694a85f9a)

**Comment by schanzer** [comment]
@retabak I'm not able to duplicate this. [Here's the deck I just built right now](https://docs.google.com/presentation/d/1KaPw14x3fvOIUnkMZoPRpUzB_wUAX3a2SnoYwBXVMHM/edit#slide=id.cc2c3df2-d685-11ee-9263-e1f697644851). Can you make clean and try again, and see if it persists?

**Comment by retabak** [comment]
@schanzer Just tried again. Got the same issue. [Here's a link to the deck](https://docs.google.com/presentation/d/1SFD8Ab_8PSNrJ8Ox7mz4kOPDBXyVCG38RSP2tZfQClY/edit#slide=id.dff46ef5-d5fb-11ee-a124-8bb73f0e7ca8).
