### ISSUE TITLE
Throw an error when a @slidebreak occurs inside any other directive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1920]
I just wasted a significant amount of time because an unclosed directive broke my second level bullet build and there was no warning so I was looking in all the wrong places.

Here's a common scenario

```
@lesson-instruction{
x
y
}
```

gets changed by an author to

```
@lesson-instruction{
x
@slidebreak
y
}
```

when the change should be

```
@lesson-instruction{
x
}
@slidebreak
@lesson-instruction{
y
}
```
no warnings are issued... and a variety of seemingly unrelated things break. 
I can't tell you how many times this has happened to me and taken significant time to resolve.

Please be less lax and more direct with warning / error communication.

**Comment by schanzer** [comment]
@ds26gte any reason not to _also_ do this in `preproc.rkt`? This is the kind of thing authors should be warned about early and often

**Comment by ds26gte** [comment]
This issue has now ballooned into a bigger feature request: We do want `@slidebreak`s (and indeed all AsciiDoc headers) inside `@ifproglang` to be significant slide separators

**Comment by schanzer** [comment]
@flannery-denny can you confirm that the use-case you opened the issue with is now resolved?

**Comment by flannery-denny** [comment]
thanks @ds26gte! So helpful!
