### ISSUE TITLE
Code in slides doesn't exhibit same line breaks as in lesson plans

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1922]
This is from the lookups lesson plan

<img width="358" alt="Screen Shot 2024-02-28 at 8 46 30 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/efaf9162-cd89-496c-a523-22930534ce45">

On the slide we see
<img width="610" alt="Screen Shot 2024-02-28 at 8 48 45 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/1cfefe87-c607-4279-af74-329f5bc0ed0e">

Is there additional formatting authors need to add to the adoc?

```
  row-n(animals-table, 0)["name"]
  row-n(animals-table, 0)["age"]
  row-n(animals-table, 0)["fixed"]
```

**Comment by schanzer** [comment]
Ooooh, this looks like a a regression that cropped up yesterday when I added syntax highlighting. Hopefully an easy fix, once I can pinpoint where the slide generator is losing the content

**Comment by schanzer** [comment]
@flannery-denny authors shouldn’t have to do anything extra here. I’ll investigate.

**Comment by schanzer** [comment]
@flannery-denny the asciidoc convention of "indent a block of text and it turns into code" isn't supported by markdown. 

You have two other methods that work just fine, however:
```
----
row-n(animals-table, 0)["name"]
row-n(animals-table, 0)["age"]
row-n(animals-table, 0)["fixed"]
----
```

Or using the triple-backtick (```) above and below the code.

I've updated the lesson plan accordingly, but we should be on the lookout for other instances like this.

**Comment by schanzer** [comment]
@flannery-denny I went ahead and fixed every other use of this shortcut. Fortunately there were only a handful - I think most of the time we're using explicit fences around code blocks, and this indenting trick is super rare

**Comment by flannery-denny** [comment]
Thanks!
