### ISSUE TITLE
Add testing table to glossary and update other Bootstrap-specific definitions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1924]
- [x] testing table
- [x] contracts
- [x] circles of evaluation
- [x] design recipe
- [x] continuous (use it in functions-can-be-linear and piecewise-functions)

**Comment by flannery-denny** [comment]
@schanzer Does it make sense to you that we'd acknowledge Bootstrap terms at the end of their definitions, as follows?

> a statement of the name, domain, and range of a function. (This is a Bootstrap-specific term.)

**Comment by flannery-denny** [comment]
@schanzer How about this definition?

Testing Table: A thoughtfully constructed table that is representative of the whole, small enough to reason about, and designed to test whether code does what it's supposed to do.

**Comment by schanzer** [comment]
@flannery-denny 

1. Here's what I'd use for Testing Table: _a carefully-selected sample from a dataset, which is designed to test a particular table operation for correctness_
2. Let's just end the Bootstrap-specific definitions with "(Bootstrap-specific)"

**Comment by flannery-denny** [comment]
@schanzer Assuming these terms are also Bootstrap-specific? 

- Interactions Area
- Definitions Area
- Contract Error

Noticed a few definitions without Spanish translations and translating them makes me wonder if we should add the following improvements:
- Multiplicative Inverse - Multiplying a number **(other than zero)** and its reciprocal always produces 1
- When fitting a model to the data, the residual is the difference between the predicted value and the actual value of the response variable. **The predicted value comes from the regression line and the actual value comes from the dataset.** 

Make sense to you?

**Comment by flannery-denny** [comment]
@schanzer Here are some phrases other people use to describe continuous: 
- continuing without stopping
- uninterrupted in time, sequence, substance, or extent.
- a line or curve that extends without a break or irregularity.
- a real-valued function whose graph does not have any breaks or holes
- when the graph is a single unbroken curve
- a function is continuous on an interval if we can draw the graph from start to finish without ever once picking up our pencil.

How about
Continuous: Uninterrupted. On a graph, they appear as an unbroken curve. Some functions are described as being continuous over a specific interval, although they are not continuous in their entirety.

**Comment by schanzer** [comment]
@flannery-denny I dig it. Small tweak:

_Continuous: "Uninterrupted". On a graph, continuous functions appear as an unbroken curve. Some functions are continuous everywhere, while others may only be continuous over a specific interval._

**Comment by flannery-denny** [comment]
@schanzer I'm not totally sure deploying continuous where I did in piecewise functions jives with our definition. Please have a look and close if you're satisfied or adjust / lmk where else you would have suggested using the word continuous in the lesson.

**Comment by schanzer** [comment]
@flannery-denny Yeah, that jives beautifully. I think we're good to go!
