### ISSUE TITLE
rewrite line graph explanation to reflect that they time is not the only use-case

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1929]
```
@strategy{What about Line Graphs?}{


Line graphs and scatter plots have a lot in common! They both visualize the relationship between two columns, and both columns must be quantitative.

There is an important difference, however, in that **line graphs are typically used when the x-axis measures __time__ **. Only in this situation can it be appropriate to "connect the dots", because they represent the __rise__ and __fall__ of a measure over time. Without time, there's no notion of "slope"!

@ifproglang{pyret}{For students who want to use line graphs, the Contract is:

@show{(contract "line-graph" '("Table" "String" "String") "Image")}}

@ifproglang{codap}{For students who want to use line graphs, create a scatter plot, then open the `Measure` menu and select Connecting Lines.}
}
```

I think this is an oversimplification and my middle schoolers were able to think about whether or not to connect dots with more nuance. Time doesn't have to be the variable on the x-axis for connecting dots makes sense. The question is whether the variables are changing continuously. If we had water flowing from a source, we might measure the volume vs. the height it's reached in a bucket or the cost of it.

**Comment by flannery-denny** [comment]
@schanzer Does this work for you?

**Comment by schanzer** [comment]
@flannery-denny love it! But I think we should add _continuous_ as a vocab word, and then use it in our piecewise lesson as well

**Comment by flannery-denny** [comment]
adding continuous to #1924 and closing this issue
