### ISSUE TITLE
add "function composition" to the glossary

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1932]
I'm working on #1848, therefore thinking about function composition. Its definition is not in our glossary. **Let's add it!** Also, the definition that we offer in the lesson (which is sort of burried) does not seem like the best one out there. 

Here's what we have: 
_We can also compose functions, meaning that the output of one is immediately passed into another._

My favorite alternative is this: *The range of one function becomes the domain for the next.* (...unless we are intentionally avoiding using the words "domain" and "range" for some reason that I don't understand?) This should be more prominent in the lesson, too.
@flannery-denny @schanzer - are you comfortable with this definition?

Another note:

I'm not sure how to revise this text, but the way we have "add 6 4" (below) is totally confusing. (I don't think that's a standard way of showing that `add 6` takes in 4?)

_For example, we could compose `add6` `4` and `double`, so the `10` gets passed into the next function, and doubled to produce 20._

_And, if we composed `add6` `4` with `double` and with `half`? We’d get 10._

**Comment by flannery-denny** [comment]
@retabak The text you have excerpted is describing an activity that precedes a formal discussion of function composition. I'm not saying it couldn't be improved upon, but it is not indented to be something standard! 

@schanzer Perhaps we need images of the cards here instead of using code block?

**Comment by retabak** [comment]
@flannery-denny - right, but where is the "standard" definition of function composition, then? I don't see it.

**Comment by flannery-denny** [comment]
@retabak re: the definition you propose, I don't think it tells the whole story.

I would describe function composition as: 
- Stringing two or more functions together such that they work together to produce the desired outcome. The output of one functions is used as the input of the next. 

I don't feel great about using domain and range here.

The interwebs describes function composition
- An operation that takes two functions and produces a new function that passes the outputs of one function into the next

**Comment by schanzer** [comment]
@retabak and @flannery-denny Agreed that using exclusively Domain and Range is a bad idea, but I would be fine with them used _in addition_ to more accessible, plain language.

Flannery, I particularly like the first definition you propose. I'd make the following tweak:

Function Composition: The act of connecting two or more functions so that they work together to produce the desired outcome. The output ("range") of one function is used as the input ("domain") of the next.

**Comment by schanzer** [comment]
If there was no desired outcome, how would a student in an algebra class know which functions to compose?

**Comment by retabak** [comment]
Their textbook would tell them which ones? Isn't that the most common
algebra class use case? What am I forgetting about algebra class (which I
have never taught)? Seriously!

**Comment by retabak** [comment]
Function Composition: The act of connecting two or more functions so that they work together to produce an outcome. The output ("range") of one function is used as the input ("domain") of the next.

@flannery-denny - @schanzer and I had our one-on-one and agreed to this definition. Cool with you?

**Comment by flannery-denny** [comment]
@retabak sure. glad you sorted it out before I wrote you an essay on algebra and why lame textbooks shouldn't be our least common denominator ;)

**Comment by retabak** [comment]
@flannery-denny, Lol. Glad you were spared from the essay. ;)

Also, re: "Add 6 4", I like @flannery-denny's proposal to use images of the cards. @schanzer , what do you think?

**Comment by schanzer** [comment]
@retabak make it so!
