### ISSUE TITLE
convert peardeck interactive function activity to desmos

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1933]

**Comment by retabak** [comment]
This is finished. Took a minute to figure out the computation layer stuff. Hoping to road test and receive feedback during 3/12 curriculum meeting. Should only take a few minutes.

https://teacher.desmos.com/activitybuilder/custom/65e8c6054aef5dc85d3a9bae

**Comment by flannery-denny** [comment]
@retabak what is this attribution about?
<img width="380" alt="Screen Shot 2024-03-07 at 10 19 33 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/61859cd0-0d50-4b46-883d-7feab5bbc33d">

**Comment by retabak** [comment]
It appeared automatically like that because I started with someone else's
activity to borrow and edit some of his code. I can + will make it go away.

**Comment by retabak** [comment]
@flannery-denny - I believe this issue is ready to be closed. Can you review my work to confirm that the Desmos instructions (on the activity and in the lesson) are up to par with the other Desmos activities you've cleaned up + make sense to you?
