### ISSUE TITLE
Contracts not in the Contracts Reference Link under Other Resources

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1940]
I was demonstrating the Contracts Reference link in the Other Resources section of DS main page.  The following contracts do not come up:   above, overlay, put-image.  They are in the contracts section of the workbook, but not searchable in this tool.

**Comment by schanzer** [comment]
@joystraub I'm not seeing any of those functions in the contracts section of [the workbook](https://bootstrapworld.org/materials/spring2024/en-us/courses/data-science/workbook/workbook.pdf).

**Comment by flannery-denny** [comment]
@joystraub We could add those functions to the DS contracts, but I can't think of where they're used. What is the use-case for those functions in Data Science?

**Comment by joystraub** [comment]
Those contracts are in the back of my workbook, which is the first version from the summer.  Maybe they were dropped after that edition?
There is an infographic assignment.  Some teachers just have students create logos.  This does not connect to DS, but is excellent practice for students learning the contracts.  I added it to my contracts lesson to get them very familiar with reading contracts.  It is engaging.  Many use put-image, overlay, and beside, above, etc. to create the infographic/logo.

**Comment by flannery-denny** [comment]
@joystraub Rather than write you an essay, let's find a time to chat! I'm going to shoot you an email.

**Comment by joystraub** [comment]
Also - my students used above (or below) to put two displays together.  They also use put-image or overlay to put text onto their displays.
