### ISSUE TITLE
wrong table is building in functions can be linear

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1942]
The single table on slide 3 of [this deck](
https://docs.google.com/presentation/d/10aAvqMdWR3RXc078HANwIp5gD3uVL1a4FpZfn9Rfsq0/edit#slide=id.139f6fc1-dbba-11ee-9d3d-2de735153b50) is being generated by the code below, which renders as side by side tables in the lesson plan

```
[cols="^.^1a,^.^1a", frame="none"]
|===
|
[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! x ! y
! 1   ! 2
! 2   ! 3
! 3   ! 4
! 4   ! 5
! 5   ! 6
!===
|
[.pyret-table.first-table,cols="^1,^1",options="header"]
!===
! independent ! dependent
! 1 ! 20
! 2 ! 17
! 3 ! 14
! 4 ! 11
! 5 ! 8
!===
|===

```

**Comment by schanzer** [comment]
Ooooh, good find! @ds26gte I think this is in your wheelhouse

**Comment by ds26gte** [comment]
I've pushed a fix using a smaller example lesson to test. The lesson `functions-can-be-linear` seems to cross the allowed image limit for me at least

**Comment by schanzer** [comment]
@ds26gte ooooh, nested tables! _Of course!_ Great catch, and great reporting, @flannery-denny !

Confirmed fixed on `functions-can-be-linear`
