### ISSUE TITLE
[.graph-table, stripes="none", frame="none"] is bleeding through onto slide

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1943]
See slide 9 of  [this functions can be linear deck](https://docs.google.com/presentation/d/10aAvqMdWR3RXc078HANwIp5gD3uVL1a4FpZfn9Rfsq0/edit#slide=id.139f96d0-dbba-11ee-9d3d-2de735153b50)

**Comment by schanzer** [comment]
@flannery-denny just a reminder to also include the lesson name in these issues. Yeah, Dorai and I can click on the slide link and select the right google login, then view the name. But if it's top-of-mind for you anyway at the moment you write the issue, it would be nice to save us that step!

**Comment by schanzer** [comment]
confirmed fixed!
