### ISSUE TITLE
Generate reasonable titles for all charts

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1946]
- [ ] update the image of a pie chart in the data cycle lesson plan when this is working
- [ ] It's much less confusing to see these results as Booleans when the column title is included as CODAP does. 
Not sure whether this would be a Bootstrap:Data Science or Pyret level ask.
<img width="873" alt="Screen Shot 2024-03-06 at 1 19 40 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/a4495ba6-4dc3-4641-a358-3fc452d88296">
<img width="296" alt="Screen Shot 2024-03-06 at 1 19 25 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/63e6c6b0-627c-4e17-87ee-356ed0f2cd99">

**Comment by schanzer** [comment]
@retabak and @joystraub , I'd love for you to weigh in on this before I make the change

**Comment by retabak** [comment]
@schanzer - I think it's a great suggestion. Do you have qualms about it?

**Comment by schanzer** [comment]
@retabak 

1. Most kids will be using the interactive mode to look at data, so they won't even _see_ the word "Cases" in the title.
2. This introduces an inconsistency, where the thumbnail doesn't look exactly like the chart. Even worse, that inconsistency happens for some charts, but not for others.

**Comment by flannery-denny** [comment]
@schanzer I was eager to read your qualms, but I am underwhelmed by them.

And I disagree with #1.
The interactive displays are cool. But I think most of the work is done with static versions of the displays. Students are asked to collect displays in both of the major DS projects that they will refer back to and write about. 

Other displays include clues that let us know what columns were used, eg. legends and wedge labels. But when there's a Boolean column involved, without a label like "Fixed", students could end up swapping one for another.

**Comment by schanzer** [comment]
@flannery-denny I'm underwhelmed too. Just wanted to make sure you're both aware of the inconsistencies before I go and implement the request.

**How should we auto-title bar charts? Pie charts?**
- I would suggest "cases for 'XYZ'", but I'm open to other options

**Should we also auto-title other charts?**
- If so, how? 
- If not, why not?

**Comment by retabak** [comment]
Okay, all this talk about auto-titles made me realize that I misread @flannery-denny's initial post! 

To me, the biggest difference between the pyret and codap displays is not the title, but the way that one chart has a column name ("Fixed") and the other doesn't.  

Tbh, I think this is a more important addition to the Pyret display than "Cases" (although it would be nice to add that as well!). Without any indication of the column, the bar graph means literally nothing when removed from a context.

**Comment by flannery-denny** [comment]
I was actually referring to the axis title "Fixed" and not a chart title. Looks like @retabak and I are on the same page. Sorry for the confusion @schanzer.

**Comment by schanzer** [comment]
@flannery-denny @retabak not sure what confusion you're talking about? My comment this morning already included using the column name in the title. 

I not uncomfortable doing this piecemeal. Teacher will immediately want to know why we have titles for some charts, and not for others. Let's think this through before we move ahead, and if there isn't enough time then let's table the whole issue until 2025.

**Comment by retabak** [comment]
@schanzer - We aren't proposing adding a title (which I think of as going
at the TOP of the display). We want the attribute name to appear UNDER the
display. Does that help? Or are we still talking in circles?

**Comment by schanzer** [comment]
@retabak Ah, NOW I understand. So yeah, I was definitely confused. :-P 

Attached are images that do what I _believe_ you want, for bar charts and pie charts.
<img width="1011" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/73af24f4-caac-417d-8db4-c27239d6f27e">
<img width="885" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/e50e679a-4448-469d-9491-08f374311ce8">

1. I think the column name looks genuinely bad in the pie-chart, but nice in the bar-chart
2. I don't love how much space there is between the bar chart and the column name (and it's not fixable!)

**Based on this, I'm really not excited about the feature.**

But my misunderstanding has whet my appetite for automated titles - a _longstanding_ wish from teachers. That would also address _this_ issue, while taking care of something for which know there's a huge need.

**Proposal for Auto-Title-ing (using columns from the animals dataset as examples)**

- Bar and Pie Charts: "Distribution of `Species`
- Stacked and Multi Bar Charts: "Distribution of `Species` (by `Sex`)
- Histograms and Box Plots: "Distribution of `Pounds`"
- Scatter and LR plots: "Relationships between `Age` and `Weeks`

If this gets you and @flannery-denny interested, let's close this issue and open a separate one.

**Comment by retabak** [comment]
Agreed that the bar chart looks good and the pie chart looks bad. The legend in the pie chart seems adequate, anyhow. 

Regardless...

**I am interested in auto-titling!** I like your proposal. Here's my only possible revision to your proposal: I wonder if for Scatter and LR plots, there is some way to help students recognize which variable is explanatory / response (or which is independent / dependent). Maybe: "Does Weeks Respond to Age?" or "Does Weeks Depend on Age?" Perhaps this is *too* helpful, but my students have historically had a tough time distinguishing between these two.

**Comment by joystraub** [comment]
@schanzer @flannery-denny @retabak 
Just read all of this - I love the idea of having the column name under the bars, if possible.  That sure helps.  I agree that the pie looks a little wonky with it so far away.  My students were always using the text function with put-image &rotate to get a title at the top and labels on the axes.  I would have loved that to have been more automatic for them.

**Comment by flannery-denny** [comment]
@schanzer This would be fantastic!

I am also nonplused by the Scatter plot / LR title... and...

1. I wonder if a more precise title might undermine transfer to a less scaffolded environment by denying them practice at recognizing the question?
2. I don't like any of @retabak 's proposals.

I propose we either:
1. Don't provide a title for Scatterplots and LR plots... because, unlike the other displays, these displays already have labeled axes... and encourage students to generate their own titles.
2. use Might Age explain Weeks?
3. stick with Relationships between Age and Weeks

**Comment by schanzer** [comment]
@flannery-denny From experience, if we title _some_ charts and not others, we're in for a full year of teachers asking why other charts don't have titles. We need to do this everywhere or nowhere.

It sounds like everyone is onboard with the proposals for 1-dimensional displays! That feels like progress to me.

As for scatter/LR plots -- apparently there's some consensus in the field about this! 10m of google searching found almost identical recommendations from [Chemistry](https://chemistry.stackexchange.com/questions/35793/naming-convention-for-graphs#:~:text=Once%20you%20have%20clearly%20understood,Dependant%20variable%20vs%20Independent%20variable.&text=Essentially%2C%20you%20want%20to%20summarise,sample%20is%20in%20the%20title.), [math resources](https://sciencing.com/proper-way-label-graph-5195234.html), [game design](https://gamefaqs.gamespot.com/boards/282-science-and-technology/70334091), and more:  "`Dependent` v. `Independent`". 

This is both accurate, non-suggestive, and a nice excuse to passively review vocabulary. How do y'all feel about this?

**Comment by flannery-denny** [comment]
@schanzer works for me!

**Comment by schanzer** [comment]
@retabak and @joystraub, can you live with this?

**Comment by retabak** [comment]
I like it!

**Comment by schanzer** [comment]
@retabak @joystraub @flannery-denny [Feedback welcome!](https://code.pyret.org/editor#share=1_Hk0XTcd1hxD9Pp4amXozjSsnlAdEp0C&v=0c33ff0)

**Comment by flannery-denny** [comment]
@schanzer still like this. particularly like the legend for "data" and "model" on the lr plot. lmk when I can go ahead and update the images used in the lesson plan.

**Comment by schanzer** [comment]
@joystraub , speak now or forever hold your piece... ;)

**Comment by joystraub** [comment]
@schanzer I like it.  It helps!!

**Comment by schanzer** [comment]
@flannery-denny Looks like we have consensus! Closing the issue, since now we have reasonable titles for all charts.
