### ISSUE TITLE
Function definition template is hard coded for Pyret. Needs to be wrapped.

### ISSUE THREAD

**Issue by er1c456** [bootstrapworld/curriculum#1948]
https://github.com/bootstrapworld/curriculum/blob/3b4bdfa3998ac37c7b029772a5bd2aa8429f9a43/lessons/Core/functions-make-life-easier/langs/en-us/pages/define-your-own.adoc?plain=1#L62

I'm not sure how to wrap this in a directive.
`*fun* @fitb{5em}{} (@fitb{8em}{}) *:* @fitb{8em}{}(@fitb{22em}{}) *end*`

I thought perhaps
`@show{ (code '(define ( @fitb{5em}{} ) ( @fitb{22em}{} ) ) ) }`
, but I'm getting empty list contract violation.

**Comment by schanzer** [comment]
@er1c456 great catch!

If my fix works for you, close the issue. Otherwise, you can revert and replace it with two language-specific options, each wrapped inside @ifproglang{XYZ}{....}.
