### ISSUE TITLE
fix the wording on the data cycle so that there's a category that `count` fits into

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1952]
The current data cycle asks

"What code will make the table or display you want?"

And the first data cycle we are going to have them use is to `count` ...

**Comment by schanzer** [comment]
@flannery-denny I don't see what's wrong here?

**Comment by flannery-denny** [comment]
@schanzer count is neither a table nor a display

**Comment by schanzer** [comment]
@flannery-denny the result of `count` _is_ a table
