### ISSUE TITLE
Should we allow @proglang to be used inside @ifproglang?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1957]
Slight update from ES, 3/8 - if this should not be allowed, we should throw an error for this. If it _should be_, then this is a parsing bug

---------------------------------
Currently, code like this (which there is no need to allow authors to write!)
```
@teacher{
If you'd like to start your students with a mini version of the Data Cycle, have them complete @printable-exercise{analyzing-with-count.adoc}@ifproglang{pyret}{and test their code in @proglang}.
}
```

results in this unhelpful message.

```
lua: ...ery/Documents/Bootstrap/curriculum/lib/maker/readers.lua:101: attempt to index a boolean value (local 'c')
stack traceback:
	...ery/Documents/Bootstrap/curriculum/lib/maker/readers.lua:101: in function 'read_word'
	...Documents/Bootstrap/curriculum/lib/maker/make-slides.lua:144: in upvalue 'scan_directives'
	...Documents/Bootstrap/curriculum/lib/maker/make-slides.lua:174: in local 'scan_directives'
	...Documents/Bootstrap/curriculum/lib/maker/make-slides.lua:315: in upvalue 'get_slides'
	...Documents/Bootstrap/curriculum/lib/maker/make-slides.lua:330: in local 'make_slides_file'
	...Documents/Bootstrap/curriculum/lib/maker/make-slides.lua:401: in main chunk
	[C]: in ?
```

Could it instead say "ERROR: @proglang is used in @ifproglang"?

**Comment by retabak** [comment]
Wow, that is a strange error and I suspect that it is mine! I think it was a consequence of sloppily using Control+F in effort to efficiently remove any reference of "code" and "pyret" from the codap lessons.

Although using @proglang inside @ifproglang is obviously pointless, does it do any harm?

**Comment by ds26gte** [comment]
Good catch. This was actually a bug where read_word() was failing when reading the last directive (in a file, or in the more frequent case while scanning a string inside a directive argument, as in the example cited).

I've gone ahead and added a translation for `@proglang` anyway.
