### ISSUE TITLE
These fractions from functions-can-be-linear need to be vertical rather than diagonal

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1958]
Here's the code from line 446 of the lesson plan

`This strategy is often described by the algorithm @math{\frac{\mbox{ChangeInY}}{\mbox{ChangeInX}}} or @math{\frac{\mbox{rise}}{\mbox{run}}}.`

It's currently rendering as a diagonal fraction, which is very hard to read.
<img width="541" alt="Screen Shot 2024-03-08 at 8 03 32 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/699dcd6a-e804-4ede-b2d7-712d8577b3df">

The fractions directly beneath these in the lesson plan render as expected and I can't figure out why these don't.

**Comment by schanzer** [comment]
Hmmm, looks like our heuristic for when to fall back to MathJax needs to be tightened for fractions!

@flannery-denny currently we avoid MathJax for fractions that involve "atomic" numerators and denominators (i,e. - numbers or identifiers, but not whole expressions).

@ds26gte I propose we fall back to MathJax when ANY of the following conditions are met for the numerator OR denominator:

- Non-atomic (e.g. - `1 + 2`, `x * y`, etc.)
- Negative denominator
- Longer than 3 chars (e.g. - `1234`, `rise`, `ChangeInX`, etc)

**Comment by ds26gte** [comment]
`\frac` is a lifelong resident of Diagon Alley. The fractions are meant to be shortish.

If you want the horizontal rather than the diagonal bar, use `@math{numerator \over denominator}`. This looks fine in the HTML, however @schanzer may need to do some styling for the slides as it renders way too huge (at least for me)

**Comment by schanzer** [comment]
@ds26gte I'd completely forgotten about `\over`. This is perfect. Thank you!
