### ISSUE TITLE
Spurious Correlations Link has Changed

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1963]
The Spurious Correlations link provided in the Correlations lesson is no longer a link to the page we used to view.  He has created a whole new list of spurious correlations at this link: [](https://www.tylervigen.com/spurious-correlations)
So this needs to be updated in the lesson plan and slides.  (I uncovered it prepping for coaching!)

**Comment by joystraub** [comment]
Looks like the link did not post for some reason:
https://www.tylervigen.com/spurious-correlations

**Comment by flannery-denny** [comment]
@joystraub It's was updated for the next release a while back. I've just pushed a fix to master which @schanzer can push to the web if he wants.

**Comment by schanzer** [comment]
@joystraub I've updated the spring 2024 correlations lesson to this link. Thanks!
