### ISSUE TITLE
Slides are not processing` \over` in `functions-can-be-linear` of the `linear` branch

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1964]
I switched lines 443-463 from `\frac` to `\over` per @ds26gte's instructions.

```
This strategy is often described by the algorithm @math{{\mbox{ChangeInY}}\over{\mbox{ChangeInX}}} or @math{{\mbox{Rise}}\over{\mbox{Run}}}.

[.sideways-pyret-table]
|===

| x | **3** | **20** | 5  |  9 | 1
| y | **5** | **56** | 11 | 23 | -1
|===

Taking the first two pairs of values in the the last table on @printable-exercise{slope-int-tables-intro.adoc, the page}, gives us:

@indented{@math{{56 - 5}\over{20 - 3}}}
@indented{We can simplify that to @math{{51}\over{17}}, for a slope of @math{3}.}

We would get the same answer for this example if we subtracted the coordinates in the opposite order... 

@indented{@math{{5 - 56} \over {3 - 20}} = @math{{-51} \over {-17}} = 3}

But if we mixed subtracted the x values in a different order than we subtracted the y-values, we'd get the wrong answer! 

@indented{@math{{56 - 5} \over {3 - 20}} = @math{{51} \over {-17}} = -3}

```

They now look great in the lesson plans 
<img width="909" alt="Screen Shot 2024-03-12 at 10 13 18 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/a1c4c29f-9b1c-4a65-a3e9-5eb1c8eb7faf">

But are unreadable on slides
<img width="968" alt="Screen Shot 2024-03-12 at 10 16 32 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/55d7e2a6-2ea5-4d51-9ee0-c0b1772226de">

**Comment by schanzer** [comment]
@ds26gte this is definitely your department -- we need to fall back to mathjax in this situation

**Comment by flannery-denny** [comment]
@schanzer I'm not able to build slides to test this. Lmk when you think slide build should be working again.

**Comment by schanzer** [comment]
@flannery-denny slide building works fine for me. What error are you getting?

**Comment by schanzer** [comment]
@flannery-denny I just built this deck using [zample-lesson](https://docs.google.com/presentation/d/1Id1RPHXvw9tRPvj79rNvhuXW8iOF1eN0fs_zDonKis8/edit#slide=id.bdf50371-e148-11ee-8696-7ff3d2e82d75), and it looks like `\over` is doing the right thing. What error do you get when you try to build the deck for this lesson?

**Comment by flannery-denny** [comment]
the same image one I already reported to you.

**Comment by flannery-denny** [comment]
@schanzer You just wrote me on slack to tell me that I shouldn't expect this deck to build correctly because of the image count issue.

**Comment by schanzer** [comment]
@flannery-denny ah, it didn't occur to me that you'd be testing this on the one lesson that you know doesn't build! This is one of the things like `zample-lesson` or `__sample-lesson` are perfect for: they allow you to test a specific feature request to make sure it does exactly what it's supposed to.

I'm going to go ahead and close this. Feel free to reopen if you're unable to get `\over` to work properly in a deck for which slide building works.
