### ISSUE TITLE
Should our fill-in-the-blanks be solid black?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#1968]
@er1c456 pointed this out in an earlier issue, and reiterated this on Slack:

> Lines restrict writing and teachers like them because they improve readability. I prefer something that suggests lines like dots or ticks, but that is a personal preference.

He's got a point. I tested this out with dotted and dashed lines, and it doesn't look great. But perhaps we could change it from black to gray? Or even light-grey?

Here it is in grey, and I have to say I like it:
<img width="960" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/77126/2b21bb4e-79f6-43f8-a7d6-d986e43b5a26">

**Comment by flannery-denny** [comment]
@schanzer I'm definitely in favor of lighter lines. I'm not sure that lighter rubies work for readability, though. The font size is already really small.  Please share a pdf I can print.

**Comment by retabak** [comment]
I have no opinion on the appearance of this. 

That said, if lighter lines save teachers from using up printer ink, then I'm in favor - unless the rubies are more difficult to read!

**Comment by schanzer** [comment]
Here's particularly busy example, which I think will stand out as the worst-case scenario for gray lines:

[Data Cycle_ Regression Analysis.pdf](https://github.com/bootstrapworld/curriculum/files/14590756/Data.Cycle_.Regression.Analysis.pdf)

**Comment by flannery-denny** [comment]
Thanks @schanzer. I printed that pdf and I think it's an improvement.
