### ISSUE TITLE
Update Contracts pages so that, while printed materials only include contracts from the pathway, all Bootstrap contracts are discoverable 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1969]
- ideally the search bar would engage with the full Bootstrap contracts
- if that's not possible we should provide a link to the full Bootstrap contracts from contracts pages.

**Comment by flannery-denny** [comment]
@schanzer No. The request is to 
- **show** only the contracts in the pathway 
- **search** all Bootstrap contracts. 

(I know that didn't used to be possible, but we agree it's what would be best, and you and Dorai are constantly making things more robust so maybe it is possible now?)

If it's not possible, change this text
<img width="831" alt="Screen Shot 2024-03-13 at 1 50 11 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b937fac5-c56a-4775-997a-c81229a4a819">
so that it reads:

> Jump to any function used in this course `[ Type it here!      ]`
> Looking to push the limits? Here's a link to all of the functions in the Bootstrap library!

**Comment by schanzer** [comment]
Ah, that's a _very_ cool proposal! I think I've implemented it the way you describe. Feedback welcome!

**Comment by flannery-denny** [comment]
looks great, @schanzer! Thanks! @retabak and @joystraub will both be very happy with this improvement :) might even be worth updating https://bootstrapworld.org/materials/fall2024-beta/en-us/courses/data-science/

**Comment by schanzer** [comment]
Cherry-picked this commit to `master`, and updated the website accordingly.

**Comment by joystraub** [comment]
Thanks for making this possible!!
