### ISSUE TITLE
Update Desmos activity descriptions to move "At Bootstrap... " to the end.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1970]

**Comment by retabak** [comment]
also add some content explaining that this activity is just one piece of a bigger lesson

**Comment by flannery-denny** [comment]
@retabak Desmos Activity descriptions already include this wording:

> This activity was designed to support the learning goals of the [Bootstrap:Data Science](https://www.bootstrapworld.org/materials/latest/en-us/courses/data-science/) lesson on [Measures of Center](https://www.bootstrapworld.org/materials/latest/en-us/lessons/measures-of-center/index.shtml?pathway=data-science).

What would more would you expect to address your comment above?

**Comment by retabak** [comment]
Ah. @schanzer and I decided to close issue #1741 thinking that perhaps we could instead explain that the Desmos activity is not a whole lesson, it is just one activity of many. We were acknowledging that two Desmos slides is not that much different than one.

**Comment by flannery-denny** [comment]
@retabak Does the sentence I quoted suffice?
