### ISSUE TITLE
add section to codap lesson "dot plots and bar charts" discussing stacked bar charts

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#1972]
Just discovered that CODAP can do stacked bar charts!

Once this issue is closed, I can complete #1951.

Note: currently investigating if multi charts are possible. Couldn't figure it out on my own, but I see one single image of a CODAP multi bar chart (from Bill Finzer) when I do a google image search.

**Comment by retabak** [comment]
Hey. I'm playing around in CODAP with stacked and multi charts and discovering that they are quite different from what we get in Pyret. 

Below, I've summarized some of the ways CODAP can make displays for subgroups. Please read and let me know how you think I should proceed, @schanzer ?  

FWIW, I think we should use "stacked bar chart w/ percent" as a stand-in for the pyret stacked bar chart, and then use "stacked bar chart w/ count" as a stand-in for the pyret multi bar chart.  I think the comparison between displays that is in the Pyret lesson could (for the most part) remain the same for CODAP if I go this route.

It is very easy to toggle between a stacked bar chart with a "count" and a stacked bar chart with "percent." It takes one click. The default is "count". (Two screenshots below.)
![image](https://github.com/bootstrapworld/curriculum/assets/87144723/f7207fa2-6eac-48f2-8215-4ad6bdc7e0a1) ![image](https://github.com/bootstrapworld/curriculum/assets/87144723/28b04a08-a885-4dcc-b1b8-1c44474adb60)

I could not create a multi bar chart, but the ability to transform the stacked bar chart so easily makes me think multi bar charts are unneeded?

There were a bunch of variations on a multi bar chart that I could produce, but they're all kinda weird.

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/b119d066-d432-4fa7-ae3e-f68d09c30d92)

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/ebb38409-c10e-4734-93f1-78990d8ef0bd)

**Comment by schanzer** [comment]
@retabak the last screenshot is a multi-bar-chart. That's the correct equivalent, as opposed to the stacked bar chart that measures by count. If this issue will take more than a few hours of your time, I would push this off to a summer milestone, since we have bigger fish to fry right now.

**Comment by retabak** [comment]
this is done, but the lesson / worksheet text needs to be updated to reflect the fact that stacked charts use count, not percent.

**Comment by retabak** [comment]
ready for you to review @schanzer !

**Comment by schanzer** [comment]
@retabak I think this is a good place to leave the lesson. Nice work! Close and be merry.
