### ISSUE TITLE
glossaries aren't building on lesson plans

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1974]
Here's the entry in `glossary-terms.json`

```
{
    "en-us": {
      "keywords": [[ "vertical line test" ]],
      "description": "a strategy for determining whether or not a graph represents a function by confirming that no vertical line can be drawn such that it would pass through 2 points on the plot. In a function, each x-value may only correspond to a single y-value." },
    "es-mx": {
      "keywords": [[ "prueba de la línea vertical" ]],
      "description": "establece que una gráfica representa una función si y solo si todas las líneas verticales intersectan la gráfica a lo más una vez"
    }
  },
```
And here's it being used on line 87 of the `index.adoc` file

`@vocab{vertical line test}`

But there is no glossary between the materials table and the lesson plan...
<img width="893" alt="Screen Shot 2024-03-14 at 12 34 42 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/5de338d5-7959-4202-a36c-b6952444b09e">

**Comment by flannery-denny** [comment]
@schanzer Sorry for not thinking to double check. I had made the false assumption that it had something to do with it being a 3-word vocab word. I've tested three lesson and none have glossaries rn.

**Comment by ds26gte** [comment]
We decided that we won't have glossary text immediately after the initial table. Instead the Lesson Glossary shall be a link in the Materials row.
![gloss](https://github.com/bootstrapworld/curriculum/assets/3708729/cacb6c7c-e808-4b69-9f85-0181899e7dc2)

**Comment by flannery-denny** [comment]
Thanks for the memory jog @ds26gte
