### ISSUE TITLE
COE count is off in order-of-operations

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1975]
These circles are missing from slide 7 of [the deck](https://docs.google.com/presentation/d/1ZXVqXJVTGihHOda3U_ClHBHvImtMG1JaDAGw_pQeYkY/edit#slide=id.656ffb46-e276-11ee-b622-a5d4c67596c8).

```
@ifslide{
It depends! We can either work

- outside in: @show{(coe '(- 10 ((?ANS +) (?ANS 5) (?ANS 3))))}
- or inside out: @show{(coe '((?ANS -) (?ANS 10) (+ 5 3)))}

@teacher{The Circle of Evaluation for @math{10 - (5 + 3)} is shown on the next slide.}
}
```

Instead, we circles that we shouldn't see... 
Fingers crossed that all of the count issues in the deck are being caused by these missing COE.

Noting that these COE didn't used to appear on slides, so this is a new issue, but, once the deck was building, I realized that we needed to pull them out of the `@A` for slides, because they're an important visual for facilitating the discussion.

**Comment by schanzer** [comment]
Agreed - this very much looks like a count issue.

**Comment by schanzer** [comment]
@flannery-denny this appears to be fixed. can you confirm?

**Comment by flannery-denny** [comment]
@schanzer it's better, but [the circle on slide 16](https://docs.google.com/presentation/d/1W_dbRQJbCDGM81Xxloc-oBuArrlCa-qMkKkGA_qKSF0/edit#slide=id.c5502c91-e534-11ee-a5ae-139a648d74f0) should not be 5 * 6

**Comment by schanzer** [comment]
@ds26gte Flannery is right - the count for circles is still off. The selector I'm using counts _all_ circles (even the ones nested within tables). I think the lua script is not counting circles that appear inside tables.

An ideal solution would be to modify the selector to ignore circles that fall within tables (same trick we used to simplify table indexing, by ignoring nested tables), but table cells have an inconsistent DOM structure that depends on the vertical-alignment setting in the raw asciidoc. I'm afraid the only way to do this is to make sure we count every single circle in the slides.lua pass

**Comment by schanzer** [comment]
@flannery-denny can you check with the latest commit? It's looking good on my end.

**Comment by flannery-denny** [comment]
Still seeing the same issue on slide 16.

**Comment by flannery-denny** [comment]
@ds26gte I've checked out to master and I'm seeing something newly strange in the [OoO slide](https://docs.google.com/presentation/d/1nHS0FpD3alEUw-dpYAQ83_mXhTUAUmgsmTE_u-9Uu_E/edit#slide=id.3087568b-e61d-11ee-99ec-014ae56cde72) build

Slide 16 has 7 + (3 * 2)
(7 + (3 * 2)) bleeding through

<img width="687" alt="Screen Shot 2024-03-19 at 1 22 42 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/1a17ed50-4f17-4b27-ae56-dc4462eef662">

Slide 24 has a bunch of ````` bleeding through.
<img width="678" alt="Screen Shot 2024-03-19 at 1 23 45 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/fd8ba88c-169e-4298-9c70-96ddf6124ae1">

```

@ifproglang{wescheme}{
[cols="^1,^2", grid="none", frame="none"]
|===
| @show{(coe `(* 10 -4))}	| @show{(coe `(text "Good work!" 50 "red"))}
|===
}

@ifproglang{pyret}{
[cols="^1,^2", grid="none", frame="none"]
|===
| @show{(coe `(* 10 -4))}			| @show{(coe `(text "Good work!" 50 "red"))}
| Code: @show{(code `(* 10 -4))}	| Code: @show{(code `(text "Good work!" 50 "red"))}
|===
}
```

lmk if I should close this issue and open a new one.
