### ISSUE TITLE
Can we do better with large chunks of @math{} in functions can be linear

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1977]
Earlier this week I was having difficulty getting long math expressions with `\over` to render correctly in the functions can be linear lesson, so I split 

`@indented{@math{{5 - 56} \over {3 - 20} = {-51} \over {-17} = 3}}`
 
which was rendering as

<img width="492" alt="Screen Shot 2024-03-15 at 12 30 37 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/1e0893d2-c38a-4600-a3be-f320199c05c8">

into shorter math expressions like this

`@indented{@math{{5 - 56} \over {3 - 20}} = @math{{-51} \over {-17}} = 3}`

and got the lesson plan building correctly... but the result [on slide 25](https://docs.google.com/presentation/d/1BH8OtVx5Iem8yLZkm0MREaukrUtVPQrg9bHckYrriZA/edit#slide=id.057d2c4e-e2ed-11ee-930a-6d076ab44d88) is untenable.
<img width="1059" alt="Screen Shot 2024-03-15 at 12 01 54 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/6523f487-6597-4a5d-a0da-96b83f691369">

I started thinking through disambiguating between @ifslide and @ifnotslide, but am realizing that before I come up with additional work arounds I should just ask whether it's possible for build to get it right in both the lesson plan and on slides?

Here's the asciidoc snippet for you to work with in your zample lessons

```
@math{{\mbox{ChangeInY}}\over{\mbox{ChangeInX}} or {\mbox{Rise}}\over{\mbox{Run}}}.

@slidebreak

[.sideways-pyret-table]
|===

| x | **3** | **20** | 5  |  9 | 1
| y | **5** | **56** | 11 | 23 | -1
|===

Taking the first two pairs of values in the the last table on @printable-exercise{slope-int-tables-intro.adoc, the page}, gives us:

@indented{@math{{56 - 5}\over{20 - 3}}}
@indented{We can simplify that to @math{{51}\over{17}}, for a slope of @math{3}.}

We would get the same answer for this example if we subtracted the coordinates in the opposite order... 

@indented{@math{{5 - 56} \over {3 - 20} = {-51} \over {-17} = 3}}

But if we mixed subtracted the x values in a different order than we subtracted the y-values, we'd get the wrong answer! 

@indented{@math{{56 - 5} \over {3 - 20} = {51} \over {-17} = -3}}
```

**Comment by schanzer** [comment]
@flannery-denny was there a reason you broken up those @math expressions? or were you just trying anything you could think of to get them to build correctly?

**Comment by schanzer** [comment]
@flannery-denny I'm assuming you were just trying to get it to build, right? The fix you used requires tons of separate images, which as you point out is a headache. 

The real problem here is just that mathjax has a nontrivial learning curve. It took me a few tries to get it building correctly _without_ breaking everything up, but I think it's a lot closer to what you want how.

**Comment by ds26gte** [comment]
`\over` looks to an unmatched `{` to its left and an unmatched `}` to its right to figure out the relevant numerator and denominator. So you could write
```
@math{ { 5 - 56 \over 3 - 20 }  = { -51 \over -17 } = 3 }
```
In general, you're allowed to use `{}` to clump things together logically. They won't show as braces in the rendered output

**Comment by flannery-denny** [comment]
Thanks. Looks like it works in both places :)
