### ISSUE TITLE
Algebra 2 Errors in Answer Key Better Modeling: College Degrees vs. Income

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1980]
Errors in the workbook solution key to Better Modeling: College Degrees vs. Income:
1) the data entered for MA and NV is actually the data used for AK and AL in the earlier workbook page.  
The data should be: MA (39.4, 66866) and NV (22.4, 52800)

2) so then g(x) was calculated using incorrect values and is actually printed here the same as the f(x) from the previous page.
Should be: g(x) = 827.41x + 34266.05
When fit-model is run using g, the R-sqr is 0.28411, not the 2.84 that is listed in the answer key.

**Comment by schanzer** [comment]
@joystraub  Algebra 2 no longer uses r-squared.

**Comment by joystraub** [comment]
No - I am using the link you sent me earlier in the school year.  I entered "latest" in the URL before starting to go through the lessons (for my own learning).  If there is a different link to materials for this summer, I don't recall receiving it.

**Comment by schanzer** [comment]
@joystraub this summer we'll be training teachers on the Fall2024 curriculum, so Spring2024 is definitely not where you want to be spending your time. You've got a lot on your plate right now, so I would strongly recommend skipping Algebra 2 for a few weeks.

**Comment by schanzer** [comment]
Fixed by 946b7b73944af2b6409f67b8600a39b19e00bb6f, which accidentally also looped in a merge commit :P 

Thanks for reporting, @joystraub !
