### ISSUE TITLE
Optimize Desmos Instructions for Exploring Exponential Models lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1982]
- [x] FD- Update links on all workbook pages to refer to specific slide titles of the starter file
- [x] FD - Add preparation instructions to lesson plan
- [x] RT - Confirm wording fd used in preparation instructions makes sense
- [x] RT - Update `shared/langs/en-us/docroot/pages/desmos-instructions-alg2.adoc` to have more relevant screenshots for alg2 teachers - they will definitely be syncing

Once this lesson looks like we want it to, FD will update the remaining Alg2 lessons accordingly.

**Comment by flannery-denny** [comment]
Thanks @retabak! Please check out my latest commit which directs teachers to advance to the relevant slides throughout the lesson plan and confirm that the wording makes sense. Close or adjust and close when you're satisfied.

**Comment by retabak** [comment]
Looks good! :tada:
