### ISSUE TITLE
Link to Blank Starter File in Teacher Only Resources goes to a v1.6 starter file - needs updating to 2.0

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#1983]
In the current version of Data Science Teacher-Only Resources, the link to a Blank Starter File in the Project dropdown menu takes teachers to a version 1.6 starter file, not the 2.0.  
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/8435f6bf-8c95-44d0-bf8f-38fd7ad53ece)
This needs to be updated, as teachers are having trouble with the new filter, sort, etc. functions not working.  I have directed them to get the blank starter files from the Choosing Your Dataset lesson where it is the correct version, but it would help to have this link also be current.

**Comment by flannery-denny** [comment]
@joystraub Good catch and thanks for writing such a clear git issue!

**Comment by flannery-denny** [comment]
@schanzer sounds like joy straub needs this to be cherrypicked to the web.

**Comment by flannery-denny** [comment]
@schanzer Doing some cleanup on the DS resource page to better utilize our systems to autoupdate links.

Could any of these four links be converted to `@lesson-link` or `@dist-link` - 
- `@include{../../../lessons/choosing-your-dataset/fragments/dataset-table.adoc}`
- **Contracts** [@link{solution-pages/Contracts.pdf, link}] - A PDF of the contracts pages from the back of the student workbook.
- **Glossary** [@link{../../../Glossary.shtml?pathway=data-science, link}] - All of the vocabulary words (and their definitions) used in this pathway.
- **Bilingual Glossary of Bootstrap Terms (English-Spanish)** [@link{../../../lib/bilingual-glossary.html, PDF}] - For teachers with ELL/ESL students, we provide a bilingual glossary for all of the terms used across our curriculum library.
