### ISSUE TITLE
New bug in project-beautiful-data slides and pages

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1985]
I'm on the branch `project-slides` building `project-beautiful-data`

1. I'm getting the following error

```
lib/maker/make-json-dict.lua distribution/en-us/lib/dictionaries.js
newline: contract violation
  expected: output-port?
  given: #f
  context...:
   /Users/flannery/Documents/Bootstrap/curriculum/lib/slides-preproc.rkt:581:0: expand-directives
   /Users/flannery/Documents/Bootstrap/curriculum/lib/slides-preproc.rkt:807:8: temp112
   body of "/Users/flannery/Documents/Bootstrap/curriculum/lib/slides-preproc.rkt"
```
2. I'm noticing that on the page `beautiful-data-reflect.adoc` `@n In @starter-file{program-list}` is being swallowd.

**Comment by ds26gte** [comment]
This encloses a `@slidebreak` inside a `@teacher`. Does this make sense? Doesn't `@teacher` rely on there being an enclosing slide to which its argument can be added as a note? How can it itself contain a slide?

**Comment by flannery-denny** [comment]
@ds26gte valid point. But when I decided to enclose the Synthesize section in @teacher I was thinking about other constraints... and when I got the error it was unparsable because I had made a lot of other changes.  Can you throw about error message? Something like
"@teacher may not contain slide break"
thanks!

**Comment by ds26gte** [comment]
`make` already produces a warning for `@slidebreak` inside any other directive (including `@teacher`)

**Comment by schanzer** [comment]
@flannery-denny , close if you're happy? :)

**Comment by flannery-denny** [comment]
The swallowing issue got fixed. Thanks, @ds26gte 

But I tested to see whether I would get a coherent message by inserting the following code

```
@teacher{
=== Synthesize 

@ifslide{
Use the @handout{beautiful-data-rubric.adoc, "rubric"} to assess and revise your work.
}
}
```

and instead of getting an error I got this undesirable output
<img width="858" alt="Screen Shot 2024-03-25 at 8 30 05 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ef87700b-d63f-4315-85db-764f7e59ef29">

I guess it's better than an unparsable error, becuase at least my build isn't broken and if I look I'll see that it's not what I want, but I expect @schanzer will want to weigh in.

**Comment by ds26gte** [comment]
Warning added for `=` style header inside any other directive too (in this case, `@teacher`)

**Comment by schanzer** [comment]
@flannery-denny in my own testing these look like they've resolved the issue. Can you confirm?
