### ISSUE TITLE
Resolve "Not Set Yet" warnings and issues

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1991]
**Warnings need to be resolved and are also not necessarily flagging the lessons that need to be flagged.**
_Authors do not know how to resolve the warnings. Lmk if you'd like to zoom to resolve them together._

- [x] With a make clean I get the following warnings:
```
WARNING: Unknown slide template: notsetyet in /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/inequalities3-sam-wescheme.
Falling back to notsetyet
WARNING: Unknown slide template: notsetyet in /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/contracts.
Falling back to notsetyet
WARNING: Unknown slide template: notsetyet-DN in /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/contracts.
Falling back to notsetyet
```

- [x] While Defining Table Functions is not issuing a warning, Slides in Defining Table Functions say "Not Set Yet" where the section title belongs, this section of the lesson is titled "Reviewing Function Definition"
<img width="912" alt="Screen Shot 2024-03-28 at 6 43 09 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0fb0f899-65a7-4384-9b9a-c7aa248df432">

**Comment by flannery-denny** [comment]
With a make clean I get the following warnings:
```
WARNING: Unknown slide template: notsetyet in /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/inequalities3-sam-wescheme.
Falling back to notsetyet
WARNING: Unknown slide template: notsetyet in /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/contracts.
Falling back to notsetyet
WARNING: Unknown slide template: notsetyet-DN in /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/lessons/contracts.
Falling back to notsetyet
```

**Comment by flannery-denny** [comment]
@ds26gte Noting that the warnings we're getting for "notsetyet" slide decks do not include the issue I'm reporting int he Defining Table Functions slide deck. That feels extra concerning.

**Comment by ds26gte** [comment]
Fixing #1993 fixed this too.

BTW, the warning message did mention the lesson: it gives its pathname in the distribution. (Of course, there are no warnings now, as the problem is resolved.)

**Comment by flannery-denny** [comment]
Thanks, @ds26gte I knew which lessons were the problem... but I didn't know how to fix the Not Set Yet warnings.
