### ISSUE TITLE
Resolve @starter-file warnings

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1992]
I don't think we should issue warning for pages that direct students to use the editor. Can we squash these?

- [x] WARNING: @starter-file{editor} used in additive-inverse's workbook page but not in lesson plan
- [x] WARNING: @starter-file{editor} used in additive-inverse-wescheme's workbook page but not in lesson plan
- [x] WARNING: @starter-file{editor} used in choosing-your-dataset's workbook page but not in lesson plan
- [x] WARNING: @starter-file{editor} used in choosing-your-dataset-codap's workbook page but not in lesson plan
- [x] WARNING: @starter-file{editor} used in project-beautiful-data's workbook page but not in lesson plan
- [x] WARNING: @starter-file{editor} used in function-composition's workbook page but not in lesson plan
- [x] WARNING: @starter-file{editor} used in function-composition-wescheme's workbook page but not in lesson plan

These should be addressed by authors
- [x] WARNING: @starter-file{expanded-animals} used in data-cycle's workbook page but not in lesson plan
- [x] WARNING: @starter-file{expanded-animals} used in data-cycle-codap's workbook page but not in lesson plan
- [x] WARNING: @starter-file{negation} used in absolute-value-and-opposites's workbook page but not in lesson plan
- [x] WARNING: @starter-file{negation-2} used in absolute-value-and-opposites-2's workbook page but not in lesson plan
- [x] WARNING: @starter-file{negation-2} used in absolute-value-and-opposites-2-wescheme's workbook page but not in lesson plan
- [x] WARNING: @starter-file{negation} used in absolute-value-and-opposites-wescheme's workbook page but not in lesson plan
- [x] WARNING: @starter-file{animals} used in box-plots-codap's workbook page but not in lesson plan
- [x] WARNING: @starter-file{new-animals} used in data-collection's workbook page but not in lesson plan
- [x] WARNING: @starter-file{new-animals} used in data-collection-codap's workbook page but not in lesson plan
- [x] WARNING: @starter-file{olympic-records} used in linear-regression's workbook page but not in lesson plan
- [x] WARNING: @starter-file{cats-only} used in linear-regression-codap's workbook page but not in lesson plan
- [x] WARNING: @starter-file{dogs-only} used in linear-regression-codap's workbook page but not in lesson plan
- [x] WARNING: @starter-file{flags-ak} used in transform-compose-images's workbook page but not in lesson plan
- [x] WARNING: @starter-file{flags-ak} used in transform-compose-images-wescheme's workbook page but not in lesson plan

**Comment by retabak** [comment]
will do this today, thanks!

**Comment by retabak** [comment]
This is ready to close once @ds26gte squashes the unnecessary warnings.
