### ISSUE TITLE
 @link-instuction{} directive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#1999]
Rachel and I talked and agree that the most important thing is consistency.

We think instructions on workbook pages would work well as follows:
<img width="912" alt="Screen Shot 2024-03-29 at 12 40 36 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/a6265274-8f92-483f-8f8e-3c9298b72e5b">

As far as we can tell, this is not currently possible with `[.linkInstructions]` and think it's time to upgrade to a directive where we can define the start and end of the text to be formatted.

The following three options render as captured below.

```
[.linkInstructions]
For this page, you'll need to have **Exploring Quadratic Functions(Desmos)** open on your computer. 
The parabola you'll see is the graph of @math{f(x) = x^2}. Another, **identical** parabola is hiding behind it. This second parabola is written in Vertex Form: @math{g(x) = a(x - h)^2 + k}. Each coefficient starts at values to make @math{g(x)} equivalent to @math{f(x)}.

@vspace{1ex}

[.linkInstructions]
For this page, you'll need to have **Exploring Quadratic Functions(Desmos)** open on your computer. 

The parabola you'll see is the graph of @math{f(x) = x^2}. Another, **identical** parabola is hiding behind it. This second parabola is written in Vertex Form: @math{g(x) = a(x - h)^2 + k}. Each coefficient starts at values to make @math{g(x)} equivalent to @math{f(x)}.

@vspace{1ex}

[.linkInstructions]
For this page, you'll need to have **Exploring Quadratic Functions(Desmos)** open on your computer. + 
The parabola you'll see is the graph of @math{f(x) = x^2}. Another, **identical** parabola is hiding behind it. This second parabola is written in Vertex Form: @math{g(x) = a(x - h)^2 + k}. Each coefficient starts at values to make @math{g(x)} equivalent to @math{f(x)}.
```
<img width="916" alt="Screen Shot 2024-03-29 at 12 43 20 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/d786b74b-198b-4f22-81b3-6e334d1c199a">

we are adding this to the curriculum team agenda.

@ds26gte we know you will be tempted to tackle this, but @schanzer has been resistant to creating this directive in the past so please wait for the go ahead. Danke!

in case it's useful the example is found in `exploring-quadratic-models/graphing-models`

**Comment by schanzer** [comment]
At some point we need to stop building new things for the workbook, and save this for 2025. I'm making an executive decision and picking the date.

If it can be COMPLETED by 4/1, I say go for it.

**Comment by flannery-denny** [comment]
@ds26gte We've been given the go ahead, if you have bandwidth. But please don't touch this before tackling #1993

**Comment by ds26gte** [comment]
Would using a `--` block not suffice? E.g.,
```
[.linkInstructoins]
--
paragraph

paragraph

paragraph
--

**Comment by flannery-denny** [comment]
@ds26gte When I use

```
[.linkInstructions]
--
Open the @starter-file{inequalities-sam} starter file and click “Run”. (Hi, Sam!)
--
Move Sam around the screen using the arrow keys.
```

What I get back is the same as if I hadn't used `--`

<img width="462" alt="Screen Shot 2024-03-30 at 1 54 15 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c2664e08-92e9-481c-81a2-15bf7f522d36">

The desired output would be:

<img width="797" alt="Screen Shot 2024-03-30 at 1 54 21 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/28ba889b-5d4a-473b-919c-c27869a8c49f">

**Comment by ds26gte** [comment]
I think I don't understand what the grail is here. The style `[.linkInstructions]` affects the following block, which is either a paragraph or a `--` environment containing multiple paragraphs. So I would write
```
[.linkInstructions]
--
Open the @starter-file{...} ... 

Move Sam around...
--
```
I.e., the `--` pair encloses all the desired instructions.

If you want the style to affect only the first paragraph, but you don't want a paragraph separation between that and the subsequent text:
```
[.linkInstructions]##Open the ...## 
Move Sam around...
```
or, to be more robust:
```
{empty}[.linkInstructions]##Open the ...##
Move Sam around...
```

Do you merely want `@link-instructions` to set an in-text style around its argument. I.e., no implicit block?  (Please note I have not been privy to any verbal consensus you (F + E + R) have reached, so I don't know which one of several reasonable options is desired here.)

**Comment by flannery-denny** [comment]
Those ideas worked (see commit @retabak) Thanks, @ds26gte!

**Comment by flannery-denny** [comment]
@schanzer @ds26gte Noting that this solution remains brittle and error prone. I can't think of any other `[. ]` that only works if we use `##...##`
<img width="726" alt="Screen Shot 2024-05-02 at 1 51 59 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ad4eb007-f515-4006-acc8-86de61e798ba">

<img width="915" alt="Screen Shot 2024-05-02 at 1 51 46 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b9e6c284-f8c6-4199-91ac-2b3b0a508e59">
<img width="774" alt="Screen Shot 2024-05-02 at 1 54 17 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/0078c192-3e52-4165-bc08-4a80a517a4e8">
<img width="916" alt="Screen Shot 2024-05-02 at 1 53 43 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/56319f25-58f6-4ed8-80ca-2cb0e23b98e9">
<img width="791" alt="Screen Shot 2024-05-02 at 1 54 56 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/89102900-601c-4c57-9d2c-c2bb8d40688e">
<img width="686" alt="Screen Shot 2024-05-02 at 1 55 05 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/57cb12d1-7d92-4c04-be53-8ca38a01d1c8">

**Comment by ds26gte** [comment]
Which of the three example uses do you consider "wrong"? They seem to do the expected stuff for me. (The second usage is considered syntactically unviable.)

**Comment by flannery-denny** [comment]
@ds26gte If you look at the first example above, the part that begins with `@n` is producing `2)` on the same line as the italicized directions from `[.linkInstruction]`.

This is not desired. And it was really hard to catch.

We have reached a tipping point!

Emmanuel now agrees that the `@link-instruction{}` we originally asked for would be preferable to using `[.linkInstruction]` and having it sometimes swallow lines when the instructions end with a `}` 

Please make it so resident wizard! Danke.

**Comment by ds26gte** [comment]
The first example ends in an `@ifproglang` call, which causes eatage of the following newline. I already suggested wrapping the paragraph following the `[.linkInstructions]` inside `--`s, i.e.,
```
[.linkInstructions]
--
Open @starter-file{my-function} on your computer. @ifproglang{pyret}{Select "File", then "Save a Copy."}@ifproglang{wescheme{Click "Save".}
--

@n At the top of the starter file we've defined two functions for you to write examples with.
```

If you don't want to use the `--` fence for a single paragraph, you can end the paragraph with `{empty}`, which prevents the final `@ifproglang` call from eating the following line. I.e.,

```
[.linkInstructions]
Open @starter-file{my-function} on your computer. @ifproglang{pyret}{Select "File", then "Save a Copy."}@ifproglang{wescheme{Click "Save".}{empty}

@n At the top of the starter file we've defined two functions for you to write examples with.
```

**Comment by schanzer** [comment]
@flannery-denny let Dorai know if this fits the bill?

**Comment by flannery-denny** [comment]
Works like a charm. Merci!
