### ISSUE TITLE
Audit synthesize sections to confirm that they have questions and move lesson points made in them into the Investigate section

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2002]
Lesson plans that need attention
- [x] order-of-operations - something strange is going on
- [x] functions-can-be-linear - second section is missing a synthesize. looking more closely, I'm not sure that the first and second section should be two separate sections. the workbook pages in the first section don't actually seem to address the concepts that are being addressed in the lesson plan and the synthesize questions at the end of the first section are probably the ones that I would use for the second section.
- [x] box-plots - rethink the synthesize section for interpreting box plots
- [x] scatter-plots - needs a synthesize question for Looking for Trends
- [x] measures-of-center - Median needs synthesize questions
- [x] ds-intro
- [x] visualizing-the-shape-of-data

Lesson plans that haven't been checked but can wait until after 4/15
- [x] absolute-value-and-opposites
- [x] additive-inverse
- [x] multiplicative-inverse
- [x] associative-property
- [x] codap-building-codap
- [x] codap-composing-codap
- [x] codap-dot-plots-bar-charts-codap
- [x] codap-exploring-codap
- [x] codap-filtering-codap
- [x] commutative-property
- [x] distributive-property
- [x] equivalence
- [x] evaluating-exponents
- [x] exponent-expressions-with-negatives
- [x] translating

Lesson plans that are done
- [x] advanced-displays
- [x] bar-and-pie-charts 
- [x] checking-your-work
- [x] combinatorics-combination 
- [x] combinatorics-permutation 
- [x] computing-needs-all-voices 
- [x] contracts
- [x] contracts-tables-displays
- [x] coordinates
- [x] correlations 
- [x] data-cycle
- [x] debugging 
- [x] defining-table-functions
- [x] defining-values 
- [x] distance-formula 
- [x] inequalities-collision 
- [x] inequalities1-simple 
- [x] inequalities2-compound 
- [x] inequalities3-sam 
- [x] lookups 
- [x] making-game-images 
- [x] numbers-inside-video-games
- [x] piecewise-functions-conditionals 
- [x] player-animation 
- [x] function-composition
- [x] function-definition-linear 
- [x] function-notation 
- [x] functions-dr 
- [x] functions-examples-definitions
- [x] functions-for-character-animation
- [x] functions-make-life-easier
- [x] functions-vertical-line-test
- [x] problem-decomposition 
- [x] simple-data-types 
- [x] standard-deviation
- [x] surface-area-rect-prism
- [x] threats-to-validity 
- [x] transform-compose-images
- [x] histograms
- [x] grouped-samples
- [x] linear-regression - interpreting linear regression section needs to be reworked
- [x] ethics-privacy-and-bias
- [x] composing-table-operations
- [x] data-collection
- [x] identity-property 
- [x] variables 
- [x] probability-inference
- [x] absolute-value-and-opposites-2
- [x] exploring-logarithmic-models
- [x] exploring-exponential-models
- [x] exploring-quadratic-models
- [x] exploring-linear-models
- [x] choosing-your-dataset

**Comment by schanzer** [comment]
@flannery-denny , can you say what's weird about Order of Operations? The synthesize sections there look fine to me.

**Comment by flannery-denny** [comment]
@schanzer please check out that last commit and close if you're satisfied

**Comment by schanzer** [comment]
@flannery-denny aside from the double underscores, this is great.
