### ISSUE TITLE
DS-long workbook should include handouts

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2005]
I noticed that we have students engage with Design Recipes for `is-young` and `is-cat` twice 🤦🏽‍♀️ and got to wondering how that happened without being caught while I was looking at workbooks...

In the `Defining-table-functions` lesson, these functions occur as `handouts` for the Design Recipe Telephone activity. 
In the `filtering-and-building` lesson they are `opt-printable-exercises`

So, I wondered, do handouts make it into `workbook-long`?

I built the workbook... and, it turns out, the answer is no. I'm pretty sure the answer should be yes. Here's my logic:
- Handouts are pages that we want teachers to print because they are integral to the lesson but students will interact with them by cutting or folding and so they can't be bound in the workbook --> They do not belong in workbooks!
- As far as I know, the primary usecase for the `workbook-long` build is for authors to doublecheck our work before release. We need to be reviewing all handouts and if they aren't included we don't ever review them!
- The secondary usecase for the `workbook-long` is that a teacher may save a copy of the pdf for an overview of all of the required and not required materials in our course. They would also want to see the handouts.

**Comment by schanzer** [comment]
Confirmed fixed! Thanks, @ds26gte
