### ISSUE TITLE
Add codap directions re: googlesheets instead of starter files in choosing your dataset

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2007]
I'm cleaning up the choosing your dataset lesson and seeing that codap users are being directed to use google sheets. This isn't what we normally send them to. Why do we do it here? If I can't figure that out, I imagine teachers will also need some guidance...

**Comment by retabak** [comment]
I honestly have no idea why I would have done this other than not thinking or extreme laziness? (Both are a little embarassing, but  I hope it's not the latter.) In any case, it is now fixed.
