### ISSUE TITLE
Cleanup Data Science - Codap Teacher Resources Page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2010]
Please bring this page as closely in line with the other Data Science teacher resources pages as makes sense for CODAP. It hasn't kept pace with our improvements.

**Comment by schanzer** [comment]
@retabak I did some work on this page as part of my overall review of teacher resource pages this morning. Hopefully it's pretty close to done?

**Comment by retabak** [comment]
forgot to tag the commit: 
https://github.com/bootstrapworld/curriculum/commit/344aa64ba76a43a411e3766ba2028fded0df544b
