### ISSUE TITLE
starter-file and opt-starter-file are reversed in the Materials table of Filtering and Building

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2013]
aciidoc reads

```
@lesson-instruction{
- Load the @starter-file{table-functions}, go to the File menu, and click "Save a Copy".
```

Materials table builds like this:
<img width="668" alt="Screen Shot 2024-04-02 at 1 03 11 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/dcfe13b0-7335-4730-903f-ca811f3b249c">

**Comment by schanzer** [comment]
@flannery-denny is this after a clean `make`? I can't replicate what you're seeing

(also - this isn't an issue for Dorai)

**Comment by schanzer** [comment]
And a fresh pull?
