### ISSUE TITLE
Make use of ** and _ consistent

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2016]
Authors used to use `*`bold`*` and `_`italic`_` in adoc 

When adoc first started to be turned into md automagically, `*`bold`*`was rendering as italics in slides.

To counter this @flannery-denny  changed lots of `*`bold`*` to `**`bold`**` and lots of `_`italic`_` to `__`italic`__`

meanwhile, @ds26gte made more magic happen that automatically converts `*`bold`*` to `**`bold`**` when generating the md file from the adoc

So, there's cleanup to do:
- [x] all `**`bold`**` in adoc files should be replaced with `*`bold`*` (we can safely do this in all files as there is no potential loss)
- [x] replacing all `__`italics`__`  with `_`italics`_` comes with greater risk of loss so since 95% of changes happened in lesson plans we should limit automatic replacement to lesson plans and Flannery will deal with the fall out.

**Comment by schanzer** [comment]
Closing, now that this has been completed on the [`doublestar`](https://github.com/bootstrapworld/curriculum/tree/doublestar) branch
