### ISSUE TITLE
CODAP version of Measures of Center is currently referring to Pyret code 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2022]
- [x] I haven't done a full audit, but this is definitely true of the Summarizing Columns page and the text in the Mode(s) section of the lesson plan
- [x] The same change was made to the Measures of Spread workbook page in the Box Plot lesson. Wait to address this until #1675 is closed.

**Comment by retabak** [comment]
Thank you! WIll fix. 

(In my defense, I just checked out a printed copy of the fall 2023 workbook and that row with the code did not exist; there was just what is now the bottom row - space to write a solution.)

**Comment by flannery-denny** [comment]
Thanks for being the master of resolving CODAP bilingualism issues @retabak! You're right that this lesson got a lot of work this year... and that code got added per your request to make this lesson more usable by younger grades. Not surprising that some steps forward resulted in some steps back. I'm putting my thinking cap on about building a better system to flag lessons that need bilingual attention.
