### ISSUE TITLE
slides-pyret.html files are now requiring me to sign in after every build

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2023]
for example: [https://docs.google.com/presentation/d/1U_kVv73zT4MU4OY5zaiD5-XIz5U3GW_5lOp9Pz7qxx8/edit?pli=1#slide=id.4b4207f0-f81e-11ee-90ca-257d0402aef8](https://docs.google.com/presentation/d/1U_kVv73zT4MU4OY5zaiD5-XIz5U3GW_5lOp9Pz7qxx8/edit?pli=1#slide=id.4b4207f0-f81e-11ee-90ca-257d0402aef8)

**Comment by flannery-denny** [comment]
And, whereas a few minutes ago I could see the slides, I am now being asked to verify that I am sys admin
<img width="900" alt="Screen Shot 2024-04-11 at 11 31 28 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c0953bf0-e7ec-451c-b76c-7a7409932775">

**Comment by schanzer** [comment]
@flannery-denny can you open gmail and log in as sys admin? I'm wondering if the login has simply expired

**Comment by flannery-denny** [comment]
resolved. thanks!
