### ISSUE TITLE
Second level bullets in box plots lesson plan aren't making it to slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2024]
Here's what I see on slide 6 of this [this slide deck](https://docs.google.com/presentation/d/1B664B3WaXyZW9ooD3YlP8Fn36--1MuWjHmEZj7rZZcU/edit#slide=id.93a508e5-f82c-11ee-96e9-c9ea8aa7def8)
<img width="759" alt="Screen Shot 2024-04-11 at 12 57 47 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/ed990cee-7dcc-4af7-aadf-eed7460e9f31">

And here's what I see in the lesson plan
<img width="811" alt="Screen Shot 2024-04-11 at 1 01 34 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c5d7af29-bfea-4e56-8c14-ec98d440cfe9">

**Comment by ds26gte** [comment]
Those aren't actually second-level bullets. They are first-level bullets encased inside an `@indentpara`.   Markdown does accept some verbatim HTML in the doc, so maybe we can insert some `<blockquote>` or somesuch...

**Comment by flannery-denny** [comment]
@ds26gte interesting! Thanks! I wonder why. Let me investigate first.

**Comment by flannery-denny** [comment]
@ds26gte that resolved it. Danke. #notabug ;)
