### ISSUE TITLE
Supplemental Materials audit

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2026]
I just discovered that the piecewise functions lesson was missing the supplemental materials section even though it had both opt-starterfiles and opt-printable exercises.

Wondering if there are other lessons with this issue? And if there's a faster way to double check than to build and open all of the lessons.

**Comment by schanzer** [comment]
@flannery-denny I spoke with @ds26gte about this, and wrote the following commandline script to check for instances where `@opt-printable` or `@opt-starter-file` is used, but the "Supplemental Materials" section is missing:

`find lessons -name "index.adoc" -exec grep -rL '@opt\-' {} \; | xargs grep 'Supplemental\ Materials'`

It appears this was the only such lesson, so I'm closing.
