### ISSUE TITLE
fix caption formatting

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2035]
- [ ] when they take up more than one line there should be enough vertical space between the lines that they don't overlap
- [ ] Ideally, the width of the caption would be limited to the width of the image
<img width="851" alt="Screen Shot 2024-04-18 at 11 13 25 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/662e4ccd-0ff8-49db-9a34-29221c01271b">

Note: this instance is from unpushed materials in the AI lesson on decision trees which will get pushed eventually.

**Comment by schanzer** [comment]
@flannery-denny I pushed this to master, and then sync'd master with the ai-lesson branch to propagate the fix here.
