### ISSUE TITLE
Check additions to multilingual lessons, warn if no @ifproglang

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2039]
Explore the possibility of running a Git hook that does the following:
- checks if the lessons's proglang.txt has more than one language
- if so, checks if there are more than _n_ new lines added (probably 20+)
- if so, checks if those new lines include @ifproglang or @proglang anywhere
- if **not**, generates some kind of notification (e.g. - email the author, create a git issue, whatever)

**Comment by ds26gte** [comment]
The solution uses a Git hook called `pre-commit` placed in `.git/hooks` in your local clone. This file location can be pushed into the repo (security risk). The cloner will have to manually install the hook. I've added a script `set-hook` that can be called in the top directory and that installs the hook (if there isn't already a `pre-commit` hook already sitting there).

This need be done only once. The hook stays in place in your clone thereafter, even if you change branches. You would need to `set-hook` again if you re-cloned the repo.
