### ISSUE TITLE
Text on Slide 5 of Threats to Validity slide deck is is missing.

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2041]
The 5th slide in the slides deck for Threats to Validity says at the bottom:
More examples of confounding variables can be found in.
I went to the lesson, and I think it should say:
More examples of confounding variables can be found in the [correlations lesson](https://www.bootstrapworld.org/materials/spring2024/en-us/lessons/correlations/index.shtml): [Correlation Does Not Imply Causation!](https://www.bootstrapworld.org/materials/spring2024/en-us/lessons/correlations/pages/correlation-is-not-causation.html)
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/9fa90b73-0693-40a6-a2ca-499ae4b8e85b)

**Comment by schanzer** [comment]
@joystraub is this the 2022 deck? 2016? 2030? Make sure you're using the most current one!

**Comment by retabak** [comment]
I'm reviewing slides and think we should move this text to the teacher notes, anyhow. 

Confirming that you agree, @schanzer ?

**Comment by joystraub** [comment]
This is in the Spring2024 version - which also populates when I type latest.  It is in the version teachers are selecting from the lesson plan.

**Comment by schanzer** [comment]
Not even a little :)
