### ISSUE TITLE
Unforced make doesn't take new slide-ids into account

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2046]
@retabak  stumbled onto this one, so she gets all the credit!

TO REPRODUCE:
1. `make clean`, then `make`
2. Change the slide-id file for any deck in the `lessons/` folder
3. Run an unforced `make`

EXPECTED:
The lesson plan link (and direct slide link, if it exists) now points to the new deck

ACTUAL:
Nothing changes

**Comment by ds26gte** [comment]
`slides-pyret.html` is made/updated by `build-slide`, not `make`. 

Where is this lesson plan link? From the course page?

`dependency-graph.js` may be tough to track every file contributing to it. (We don't do it anyway because of we allow restricting `make` to particular courses.)

**Comment by schanzer** [comment]
@ds26gte Rachel ran `git pull`, which updated the slide IDs on almost every lesson folder. She re-ran `make`, but not `make clean`. She assumed that the `slides-pyret.html` would be updated as a result, but it was not.

Should it be? If not that's ok -- just want to make sure authors know what to do. Heck, maybe we even want to run `make clean` as a hook for pulls?
