### ISSUE TITLE
functions can be linear - formatting issues, redundancy?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2047]
seems like someone has a specific vision for the investigate in the first section of this lesson (Is it you, @flannery-denny ?), but the table is broken due to formatting (is there an easy way to fix this?) and it seems like there's some redundancy built into the lesson around the tbale. Wondering if the author perhaps never finished updating this lesson?

pausing slide-polishing here for now. Will complete when this is closed.

**Comment by flannery-denny** [comment]
@retabak good catch. I just wanted the 6 graphs to be numbered in the lesson plan as they were on the workbook page and somehow the numbering broke the table. Pretty sure this resolves the issue you were seeing so I'm closing it, but hit me up if there's something wonky that I missed.
