### ISSUE TITLE
automatically remove extraneous slide that results from forcing a slide template at the beginning of a lesson section

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2048]
While building slides for inequalities1-simple, I had to force the Launch template for the first slide of the launch section (it was defaulting to LaunchR). That worked great, except that it caused an unnecessary blank slide to be added to the slide deck because of the location of @slidebreak{Launch}. Here's a screenshot:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/edc542a7-6ab0-4ef2-9ab8-d47fabf15786)

Is there anyway that you can add code to detect this situation and remove the unwanted blank slide? 

Thanks!

**Comment by schanzer** [comment]
@ds26gte I guess the logic is "only insert a slide break after a chapter break if it's not immediately followed by a @slidebreak in the adoc.

**Comment by ds26gte** [comment]
Having two known slide-break creators, viz., `===` and `@slidebreak`, in the text , and then expecting one of them to fall on the sword doesn't seem very transparent to me. I'd rather the rewrite have `===` as is, then followed by a new directive call,  `@slidestyle{Launch}` which changes the style of the currently prevailing slide. I.e.,

```
=== Launch

@slidestyle{Launch}

@lesson-instruction{To get ourselves warmed up et cetera
```

**Comment by flannery-denny** [comment]
Isn't it a little late in the game for this, folks? Sounds like a wishlist item we asked for a long time ago and can wait for next year at this point...

**Comment by schanzer** [comment]
A new directive seems harder for authors to remember, but it's such a rare case that I think it's fine.

**Comment by schanzer** [comment]
Thanks, @ds26gte !
