### ISSUE TITLE
bug - make is building wescheme version using pyret content

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2053]
I'm on master in `project-flags-wescheme` looking at `composing-two-methods` and even though I've written the asciidoc to say `@ifproglang{wescheme}{(define step 1...} @ifproglang{pyret}{step1 =}` I'm seeing `step1 =` in the wescheme version

after a fresh `pull` `make clean` and `make`

**Comment by ds26gte** [comment]
Good catch! My typo (missing `\` in pathname) while moving over to the Lua-based setup script. Fixed

**Comment by schanzer** [comment]
Thanks, Dorai! Confirming we now see wescheme in the appropriate file
