### ISSUE TITLE
Run spellcheck on commits

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2054]
Totally not urgent, so please ignore for now!
-------
There are quite a few npm packages that will run spellcheck on a string, and report back on any misspellings. It would be nice to add this to the commit hook, so that authors have to manually sign off on any unrecognized words. This will help to prevent misspellings from working their way into the repository in the first place while they're fresh in the author's minds, rather than having to sniff them out in a giant copy-editing pass in the Spring.

I'd recommend using [this package](https://www.npmjs.com/package/spellchecker), and using [`setSpellCheckerType`](https://www.npmjs.com/package/spellchecker#spellcheckerspellcheckersetspellcheckertypetype) to force it use the `hunspell` dictionary so it matches Sublime's behavior.

**Comment by ds26gte** [comment]
Wouldn't a spellcheck give a lot of false negatives, given that our prose is not just English but also math and code?

**Comment by schanzer** [comment]
@ds26gte the `hunspell` package can take a configuration JSON, which tells it which words to ignore. I've already created one locally while using it to spellcheck all of our lesson plans, and it correctly ignores directives, classnames, filetype suffixes, and more. 

Of course, it's not perfect. HOWEVER - we'd only run the spellchecker on _changed/added_ lines from each file (just like the commit-hook you already wrote), so I don't expect that many false negatives. And authors can always ignore the warnings, if they think they are bogus! It would just be nice to get a printout like:

```
**Possible misspellings found in the following files:** 

lessons/Algebra/abc/langs/en-us/index.adoc
 - 1px, .codetwo, Hypoteneusse, Zari

lessons/Algebra/xyz/langs/en-us/index.adoc
 - 4a, 2em, stdev
```

An author need only scan the output to find "Hypoteneusse", and then go fix it.
