### ISSUE TITLE
Project lessons should not have slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2062]
It was decided that projects would not have slides.
But I'm seeing a link to lesson slides in `project-dataset-exploration` and the link doesn't work...

I expected to find a closed issue about this that I could reopen, but I'm not.

**Comment by flannery-denny** [comment]
@ds26gte I am on master and I've done `make clean` and `make` and I'm still seeing slides.

**Comment by schanzer** [comment]
@flannery-denny Are you actually seeing `slides-pyret.id` in the lesson folder or distribution folder? Or are you seeing `zlides.md` inside distribution? What is it that's making you say "I'm still seeing slides"?

**Comment by schanzer** [comment]
@flannery-denny nevermind - now I see it's literally just the link that you're talking about. Now that we're generating all of the materials section in Javascript from the dependency graph, this is my bug to fix.
