### ISSUE TITLE
Generate Alg2 glossary

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2067]
- [x] ES make a list.
- [x] Flannery translate.
- [ ] address duplicate definitions discovered

**Comment by schanzer** [comment]
@flannery-denny looks like I already did, back when I was working on this. Go to [the glossary json file](https://github.com/bootstrapworld/curriculum/blob/periodic-models/lib/glossary-terms.json), and search for `TODO(Flannery)`

**Comment by flannery-denny** [comment]
@schanzer I think we need to add the word "model"

**Comment by schanzer** [comment]
@flannery-denny agreed! make it so :)

**Comment by flannery-denny** [comment]
We have two entries for line plots. Do you have a preference for which one I leave?

>  "en-us": {
      "keywords": [["line graph", "line plot"]],
      "description": "a graph that uses lines to connect individual data points, displaying quantitative values over a specified time interval."
    },

> commonly drawn to show information that changes over time, by drawing continuous lines between data points"

**Comment by flannery-denny** [comment]
@schanzer We have two entries for line plots. Do you have a preference for which one I leave?

- a graph that uses lines to connect individual data points, displaying quantitative values over a specified time interval
- commonly drawn to show information that changes over time, by drawing continuous lines between data points

**Comment by schanzer** [comment]
@flannery-denny I dig the second one

**Comment by flannery-denny** [comment]
@schanzer Found another repeat entry - is there some way for build to let us know that we've repeated ourselves? 

{
    "en-us": {
      "keywords": [[ "maxima", "maximum" ]],
      "description": "the largest y-value produced over the domain of a function"
    }
  },
  {
    "en-us": {
      "keywords": [[ "minima", "minimum" ]],
      "description": "the smallest y-value produced over the domain of a function"
    }
  },
  {
    "en-us": {
      "keywords": [[ "maximum" ]],
      "description": "the largest value in a quantitative dataset"
    },
    "es-mx": {
      "keywords": [[ "máximo" ]],
      "description": "el mayor valor dentro de un grupo de números cuantitativos"
    }
  },

**Comment by flannery-denny** [comment]
@schanzer and do you have a preference for which definitions of minimum and maximum we keep?

**Comment by flannery-denny** [comment]
@schanzer fyi - leaving this open to make sure we address the duplicates I discovered and asked about above, but the original essence of the issue has been completed.

**Comment by schanzer** [comment]
@flannery-denny unfortunately JSON is designed for maximum simplicity, and standard offers no way to check for duplicates. :( 

I'd use the following (spanish translations removed for brevity):

```
{
  "en-us": {
    "keywords": [[ "maxima", "maximum" ]],
    "description": "the largest value(s) in a selected range of a set (e.g. - the outputs of a function or a list of values)"
  },  "en-us": {
    "keywords": [[ "minima", "minimum" ]],
    "description": "the largest value(s) in a selected range of a set (e.g. - the outputs of a function or a list of values)"
  }
},
```

**Comment by schanzer** [comment]
@flannery-denny close when you're ready :)
