### ISSUE TITLE
find ferris wheel animation connected to graph of altitude over time

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2068]
- [Human-powered ferris wheel video - no graphs](https://youtu.be/0FjddxnLMmY?si=db8D-DzYT_Etis-d)
- [The London Eye... Modelling Ferris Wheel Rider Height Using Trig Functions -Real World Math!]( https://youtu.be/MJ22Sbb3CEI?si=6l2SzTKpZlrxwrBr) - good youtube video to set the stage - shows video and graph side by side, but there's plenty of narrative and it eventually goes into a discussion of how to solve the problem.
- [geogebra ferris wheel applet 1](https://www.geogebra.org/m/uGkXufJt) and [applet 2](https://www.geogebra.org/m/dQNWHC7S) - sliders and graphs... but the equation is visible
- Two guided desmos activities [teacher made](https://teacher.desmos.com/activitybuilder/custom/58b9e79aa768561a1916da92) and 
[teacher made based on dan meyer's prompt](https://teacher.desmos.com/activitybuilder/custom/587b33d71384defc0d1daed9?collections=5ea4c252c2ed747cf4cb9d9d)

**Comment by flannery-denny** [comment]
@schanzer lmk if any of these scratch the itch or if there's something more specific you're looking for.

**Comment by schanzer** [comment]
@flannery-denny thanks for finding these! The Geogebra applets would be perfect IF they didn't show the equation :P

**Comment by flannery-denny** [comment]
I haven't played around in Geogebra much, but I bet there's a way to edit
them! I can play around with that if I knock the other things off the other
things on my todo list.

**Comment by schanzer** [comment]
@flannery-denny I found a Desmos animation that isn't a _ferris wheel_, but I think works well for the lesson. I'm going to close this for now, but if you disagree strongly when you get there it's fine to re-open it
