### ISSUE TITLE
css spacing around lesson points seem to have gotten lost

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2070]
- This screenshot is from `exploring linear models` and the lesson point butts directly against a table and an image above and below it. I would expect some white space both above and below the black lines delineating the lesson point.
<img width="875" alt="Screen Shot 2024-06-03 at 1 54 57 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/5f3d1141-e470-404f-a0b6-3f28de733053">

- In the same lesson plan, we can see that the lesson point butts up against the graph above it but there is some white space (as expected) before the text that follows.
<img width="885" alt="Screen Shot 2024-06-03 at 1 59 53 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/69a195c2-efe8-4440-8068-a965b80358d6">

- Below is what the first example looks like when I add in `@vspace{1ex}` - obviously not the way to go.

<img width="886" alt="Screen Shot 2024-06-03 at 1 55 59 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c3bc14aa-2abb-4ff7-9e5f-7c390c29e699">

**Comment by schanzer** [comment]
@flannery-denny I've pushed an update that I believe addresses the issue, and it's on both `periodic-models` and `master`. I tried it out the lesson and I think it addresses the issue. Close if you're happy?

**Comment by flannery-denny** [comment]
Thanks @schanzer.
- I'm not seeing any improvement here: the borders all still land on top of each other
<img width="888" alt="Screen Shot 2024-06-05 at 9 38 17 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/60fd18f5-c82d-45dc-a06e-40bead4c9035">

- but this looks much better
<img width="883" alt="Screen Shot 2024-06-05 at 9 39 53 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b096ff07-1f5f-432a-858e-0895deccbdb1">
<img width="883" alt="Screen Shot 2024-06-05 at 9 39 53 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/b096ff07-1f5f-432a-858e-0895deccbdb1">

**Comment by schanzer** [comment]
@flannery-denny aha! this was more subtle than I expected. OK, try now?

**Comment by flannery-denny** [comment]
worked, once I merged master into the periodic-models branch. thanks
