### ISSUE TITLE
add @pd-slide directives to relevant lesson plans

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2071]
DS:
- [x] intro to DS
- [x] simple data types
- [x] contracts: making tables + displays
- [ ] probability
- [ ] functions make life easier
- [x] solving word problems
- [x] row/column lookups
- [ ] filtering and building
- [ ] the data cycle
- [ ] choosing your dataset
- [x] histograms
- [x] visualizing the shape of the data
- [x] measures of center

Algebra:
- [x] order of ops
- [x] function composition
- [ ] defining values
- [x] function notation
- [x] transforming and composing images
- [ ] functions make life easier
- [x] functions: contracts, examples, defs
- [x] solving word problems with DR

**Comment by schanzer** [comment]
I've added all available PD slides to the relevant lessons. Note that not all of the checkboxes here actually represent real content that was created!
