### ISSUE TITLE
Every image link in slide presenter notes is wrong

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2078]
We inexplicably use _relative paths_ for images that appear in teacher notes. For example: `http://images/AUTOGEN-TABLE1.png`. This, of course, is nonsensical.

This will require us to regenerate every single slide deck. @ds26gte , it would be _extremely helpful_ if you could write some quick script that identifies all the decks for which this is a problem.

------ Dorai compiled a list of lessons that need their notes fixed -------

RACHEL
- [x] absolute-value-and-opposites
- [x] absolute-value-and-opposites-wescheme
- [x] codap-dot-plots-bar-charts-codap
- [x] codap-filtering-codap
- [x] evaluating-exponents
- [x] evaluating-exponents-wescheme
- [x] exponent-expressions-with-negatives
- [x] exponent-expressions-with-negatives-wescheme
- [x] identity-property
- [x] identity-property-wescheme
- [x] multiplicative-inverse
- [x] multiplicative-inverse-wescheme
- [x] measures-of-center-codap
- [x] probability-inference-codap
- [x] bar-and-pie-charts
- [x] contracts-tables-displays
- [x] data-cycle
- [x] distance
- [x] distance-wescheme
- [x] function-notation
- [x] function-notation-wescheme
- [x] making-game-images
- [x] making-game-images-wescheme
- [x] measures-of-center
- [x] order-of-operations
- [x] order-of-operations-wescheme

EMMANUEL
- [x] exploring-linear-models
- [x] exploring-linear-models-ca
- [x] re-structures-reactors-animations
- [x] advanced-displays
- [x] defining-table-functions
- [x] probability-inference

------ Original issue, filed by Joy --------
Fall 2024 Bar and Pie Chart Lesson [Slide deck](https://docs.google.com/presentation/d/11nUYCPJyiWgMh5sRoYWjog6coDaCyN2or_9k3r9DrJ0/edit#slide=id.13ce0d54-059d-11ef-acc7-eba6125bf430) slide 10 in the notes there is a link under Optional Extension that says click here for an image.  It goes to an error screen.  It is supposed to be an image for summarized data.
Same thing happens in the [Data Cycle slides](https://docs.google.com/presentation/d/1PTWbP-5DxZT3Z50shZWctTRiGbUA-tmAfEWtokAYRtQ/edit#slide=id.20af2f17-04dd-11ef-a052-8d506921f294) Slide 8.

**Comment by schanzer** [comment]
Oh _NO_. This is actually much worse than that. 

It looks like all of the image links in the presenter notes are screwed up in the same way. :( 

We can regenerate these slides for the future workshops (and teachers!), but this is a major re-work that's going to take serious time to redo.

**Comment by joystraub** [comment]
Oh no!!!  Glad I found it????  Maybe not!!

**Comment by schanzer** [comment]
No, it's a good thing -- better now than later!

**Comment by schanzer** [comment]
@ds26gte I just tried rebuilding, and it looks like we lost the title of the slides?

![image](https://github.com/bootstrapworld/curriculum/assets/77126/89e79221-01d6-4164-b86d-882326b0cd79)

Screenshot taken from https://docs.google.com/presentation/d/1qVyS3xHj4815SRYyZs_aLsKyA9BsEe33Sq6re0DpLTQ/edit#slide=id.def67914-280f-11ef-a29f-153a6b2af3fd

**Comment by ds26gte** [comment]
Seems unrelated?

**Comment by schanzer** [comment]
@ds26gte could it be related to the `[.beta]` at the top of the lesson plan itself?

**Comment by schanzer** [comment]
@retabak Dorai has fixed the title bug! You can start cranking on this whenever you're ready
