### ISSUE TITLE
Update Duration Estimates

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2080]
CORE
- [ ] computing-needs-all-voices 
- [ ] contracts 
- [ ] debugging 
- [ ] defining-values
- [ ] function-composition
- [ ] functions-dr
- [ ] functions-examples-definitions
- [ ] functions-make-life-easier
- [ ] piecewise-functions-conditionals
- [ ] simple-data-types

ALGEBRA
- [ ] combinatorics-combination 
- [ ] combinatorics-permutation 
- [ ] coordinates
- [ ] distance-formula
- [ ] function-definition-linear
- [ ] function-notation
- [ ] functions-can-be-linear
- [ ] functions-for-character-animation
- [ ] functions-vertical-line-test
- [ ] inequalities-collision 
- [ ] inequalities1-simple  
- [ ] inequalities2-compound
- [ ] inequalities3-sam
- [ ] making-game-images
- [ ] numbers-inside-video-games
- [ ] order-of-operations
- [ ] player-animation 
- [ ] problem-decomposition
- [ ] surface-area-rect-prism
- [ ] transform-compose-images

DATA SCIENCE
- [ ] advanced-displays
- [ ] bar-and-pie-charts 
- [ ] box-plots  
- [ ] checking-your-work
- [ ] choosing-your-dataset
- [ ] composing-table-operations
- [ ] contracts-tables-displays
- [ ] correlations
- [ ] data-collection
- [ ] data-cycle 
- [ ] defining-table-functions
- [ ] ds-intro
- [ ] ethics-privacy-and-bias
- [ ] filtering-and-building
- [ ] grouped-samples
- [ ] histograms
- [ ] linear-regression 
- [ ] lookups
- [ ] measures-of-center 
- [ ] probability-inference
- [ ] scatter-plots
- [ ] standard-deviation
- [ ] threats-to-validity
- [ ] visualizing-the-shape-of-data

CODAP
- [ ] codap-building
- [ ] codap-composing
- [ ] codap-dot-plots-bar-charts
- [ ] codap-exploring
- [ ] codap-filtering

EARLY MATH
- [ ] absolute-value-and-opposites
- [ ] absolute-value-and-opposites-2
- [ ] additive-inverse
- [ ] associative-property
- [ ] commutative-property
- [ ] distributive-property
- [ ] equivalence
- [ ] evaluating-exponents
- [ ] exponent-expressions-with-negatives
- [ ] identity-property
- [ ] multiplicative-inverse
- [ ] translating
- [ ] variables

ALGEBRA 2
- [ ] exploring-exponential-models
- [ ] exploring-linear-models
- [ ] exploring-logarithmic-models
- [ ] exploring-quadratic-models
- [ ] exploring-periodic-models

**Comment by flannery-denny** [comment]
@schanzer confirming that we're supposed to imagine Algebra 1 students who've already completed prealgebra when we write durations?

**Comment by schanzer** [comment]
Confirmed

**Comment by flannery-denny** [comment]
@schanzer we are going to need a new branch where durations are made visible in order to tackle this. Is that something you can make or should I talk to Dorai about it?

**Comment by schanzer** [comment]
@flannery-denny `git checkout -b duration` will make a new branch called `duration`

**Comment by flannery-denny** [comment]
@schanzer I know how to make new branches. I don’t know how to make the durations we’ve hidden on master visible on another branch. The question is whether that is your territory or Dorai’s territory.

**Comment by schanzer** [comment]
@flannery-denny oh! apologies -- see the new `duration` branch has those durations restored
