### ISSUE TITLE
Scan Fall2024 lessons on the web for Issues

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2081]
CORE
- [x] computing-needs-all-voices _Add pioneer images to slide deck!_
- [x] contracts 
- [x] debugging 
- [x] defining-values
- [ ] function-composition #2115 
- [x] functions-dr
- [x] functions-examples-definitions
- [x] functions-make-life-easier
- [x] piecewise-functions-conditionals
- [x] simple-data-types

ALGEBRA
- [x] combinatorics-combination 
- [x] combinatorics-permutation 
- [x] coordinates
- [x] distance-formula
- [x] function-definition-linear
- [x] function-notation
- [x] functions-can-be-linear
- [x] functions-for-character-animation
- [x] functions-vertical-line-test
- [x] inequalities-collision 
- [x] inequalities1-simple  
- [x] inequalities2-compound
- [x] inequalities3-sam
- [x] making-game-images
- [x] numbers-inside-video-games
- [x] order-of-operations
- [x] player-animation 
- [x] problem-decomposition
- [x] surface-area-rect-prism
- [x] transform-compose-images

DATA SCIENCE
- [x] advanced-displays
- [x] bar-and-pie-charts 
- [x] box-plots  
- [x] checking-your-work
- [x] choosing-your-dataset #2113
- [x] composing-table-operations
- [x] contracts-tables-displays
- [x] correlations
- [x] data-collection
- [x] data-cycle 
- [x] defining-table-functions
- [x] ds-intro #2110 #2109 #2112
- [x] ethics-privacy-and-bias
- [x] filtering-and-building
- [x] grouped-samples
- [x] histograms
- [x] linear-regression 
- [x] lookups
- [x] measures-of-center 
- [x] probability-inference
- [x] scatter-plots
- [x] standard-deviation _waiting on ES to clean up SD MAD pedagogy box_ 284dd277872220ded6c1b0ae9894c76b71fadc60
- [x] threats-to-validity
- [x] visualizing-the-shape-of-data

CODAP
- [x] codap-building
- [x] codap-composing
- [x] codap-dot-plots-bar-charts
- [x] codap-exploring
- [x] codap-filtering

EARLY MATH
- [x] absolute-value-and-opposites
- [x] absolute-value-and-opposites-2
- [x] additive-inverse
- [x] associative-property
- [x] commutative-property
- [x] distributive-property
- [x] equivalence
- [x] evaluating-exponents
- [ ] exponent-expressions-with-negatives
- [x] identity-property
- [x] multiplicative-inverse
- [x] translating
- [x] variables

**Comment by flannery-denny** [comment]
@schanzer Do you think *Posn* belongs in the glossary?

**Comment by flannery-denny** [comment]
@schanzer Noticing that debugging is only in the OK pathway

**Comment by flannery-denny** [comment]
@retabak I've cast an eye on all algebra and DS lessons. I'm removing Alg2 lessons from this list because they're still being written. I'll let you decide whether it makes sense for you to look at CODAP and Early Math on the web or remove them from this issue.

**Comment by schanzer** [comment]
@flannery-denny thanks for this thorough audit! I've updated the wording for the standard deviation lesson, so I think the remaining items here are on @retabak 's plate

**Comment by retabak** [comment]
I've looked at the CODAP and Early Math lessons. 

The one thing I noticed is that I somehow never got around to writing a "programming exploration" for exponent-expressions-with-negatives. I'm not sure how high-priority that is at the moment. I'll create an issue for it now.

**Comment by schanzer** [comment]
@retabak does this mean we can close the issue? (@flannery-denny note that the issue keeping `function-compostion` as unfinished has now been resolved)
