### ISSUE TITLE
opt-starter-files don't show up in the dependency graph

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2082]
The defining-values lesson has an @opt-starter-file{} directive, but in the graph the `optStarterFiles` field is an empty array

**Comment by ds26gte** [comment]
It's possible the `dependency-graph.js` file you're looking at is stale. I'm seeing the field correctly populated.

**Comment by schanzer** [comment]
@ds26gte ah - I forgot that that an unforced `make` doesn't automatically re-do the dependency graph! Apologies
