### ISSUE TITLE
Data Science Answer Key Errors

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2084]
- [x] The answer key for Fall 2024 Data Science Workbook page 25 [Which Question Type?](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/data-cycle/solution-pages/which-question-type.html) has an error in number 11 the 3rd column.  Under Which Column? it says Name.  But you are looking at Speed.
- [x] Then on page 95 [Let's Define Some More New Functions!](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/functions-make-life-easier/solution-pages/sun.html), the very last function gr says: gr(length, width): rectangle(height, width, "solid", "green").  It should say gr(height, width):  Length cannot be used as a variable - plus height is used in the 2nd part of the function.
- [x] Page 119 [Putting it All Together](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/filtering-and-building/solution-pages/putting-it-all-together.html) the sticker-table definition says to use the function sticker - there is no such function.  The function should be label.  And then for the helper function month, it asks to create a table - it names it months.  It cannot be named months since the function is months.  Perhaps this should be changed to months-table = ...
- [x] And then for number 6 on that page it should be pie-chart(fixed-dogs, "sex").  The answer given will only give fixed animals and not fixed dogs, which has already been defined earlier in a table.
- [x] Then number 7 says box-plot (sticker-table, "months").  The months column is not in the sticker-table, Perhaps this should be the months-table, if it is renamed this as I mentioned above.

**Comment by schanzer** [comment]
Thanks, @joystraub !!!!
