### ISSUE TITLE
add section or worksheet on "variability" to "visualizing the shape of the data" 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2085]
In her review of Kathi's DS diagnostic, Flannery wrote this: "I'm not convinced that our work with histograms would help teachers to answer the scores / frequency question. The only place I see the term *variability* referenced in our histogram lesson is in the standards alignment to C.SP.A"

While working on the histograms formative assessment, I just arrived at the same conclusion. Our stuff discuss SHAPE but never variability. We definitely have students think about variability (like on that awesome matching page!), but I think the connection needs to be more explicit, given that both the standards and the literature use the term VARIABILITY often. I know this I was poking around in the literature to see what the common misconceptions were around histograms, in order to write the formative assessment. Here's a nice summary that I encountered:

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/1a6b554f-7018-4c9d-b9da-bb6332d3b858)

In a similar vein:  lots of good higher order thinking can happen when students are asked to consider mean, median, and mode with respect to histograms. I propose a section or lesson called "tying it all together: measures of center and histograms" where students compute mean, median, and mode from histograms and think about statements like "the median of a histogram is always in the center bar" (which about half of our respondants so far have indicated is true). I'll screenshot some nice Qs below (from [here](https://www.tandfonline.com/doi/epdf/10.1080/10691898.2017.1321974?needAccess=true)).

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/8894042d-b58e-4509-aab3-011d2d1d09c8)

![image](https://github.com/bootstrapworld/curriculum/assets/87144723/ac82ece9-7e6e-494b-86d1-1f5cfa8d8ccb)

and check out the Q on page 24 - for sixth grade! on a CC-aligned Smarter Balanced practice test: https://portal.smarterbalanced.org/library/en/grade-6-math-practice-test-scoring-guide.pdf

Curious about your thoughts on this, @flannery-denny and @schanzer .

**Comment by schanzer** [comment]
@retabak GREAT idea. Tracking this issue at https://github.com/bootstrapworld/curriculum/issues/155 as well.

**Comment by flannery-denny** [comment]
@schanzer Noticing that this 6th grade cc standard explains statistical questions using variability:

> [CCSS.MATH.CONTENT.6.SP.A.1](https://www.thecorestandards.org/Math/Content/6/SP/A/1/)
> Recognize a statistical question as one that anticipates variability in the data related to the question and accounts for it in the answers.

Our curriculum references statistical questions in all of the following places. 
- Any reason not to work variability into all of those?
- Any reason not to define statistical questions in our glossary?

> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/choosing-your-dataset/langs/en-us/index.adoc:
>    67: @A{Lookup, arithmetic, and statistical questions.}
>    69: @Q{What's the difference between arithmetic and statistical questions?}
>    70: @A{A statistical question does not specify a particular arithmetic process, while an arithmetic question does.}
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/data-cycle/langs/en-us/index.adoc:
>     3: @description{Students are introduced to the Data Cycle, a four-step scaffold for answering questions from a dataset...and then generating the next question! Students learn to identify - and ask - statistical questions, by comparing and contrasting them with other kinds of questions. }
>    21: - Tell the difference between Lookup, Arithmetic, and Statistical questions
>    22: - Come up with their own examples of Lookup, Arithmetic, and Statistical questions
>   222: - *Statistical questions* - These kinds of questions are the most interesting! And are often best asked with "in general" attached, because the answer isn't black and white. If we ask "are dogs heavier than cats?", we know that not every dog is heavier than every cat! We just want to know if it is _generally true_ or _generally false_!
>   236: @A{It's a _statistical question_ because we are wondering what is happening in general.}
>   252: Students generally struggle to make the leap into asking statistical questions. It's worth taking time on this, to support them coming up with better (and more engaging!) questions later.
>   254: - They may think that "What's the *average* weight of the animals?" is a statistical question, because "average" is a term that shows up in statistics. But computing the average is just pure arithmetic!
>   259: - How would you explain the difference between Lookup, Arithmetic, and Statistical questions?
>   261: - What are some examples of statistical questions the owner of a sports team might ask? Or a researcher who is trying to see if a cancer drug is effective? Or a principal who wants to know what will help their students the most?
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/data-cycle/langs/en-us/pages/notes-data-cycle.adoc:
>    30:   * *Statistical questions* - These often involve multiple steps to answer, and the answer isn't black and white. When we compare two statistics we are actually comparing two data sets. If we ask "are dogs heavier than cats?", we know that not every dog is heavier than every cat! We just want to know if it is generally true or generally false!
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/filtering-and-building/langs/en-us/pages/stress-project.adoc:
>    71: - Explain how the plot and numerical summary answer your statistical questions.
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/probability-inference/langs/en-us/pages/food-habits-project.adoc:
>    26: === 2. Asking a Meaningful Statistical Question
>    27: Once you have all of your data and have looked at several graphics online about America’s snacking habits, you will declare your statistical question for this project. Some suggestions are below, but feel free to develop your own based on your analysis of the data.
>    42: - A strong statistical question based on the data that you collect.
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/probability-inference/langs/en-us/pages/rubric-food-habits.adoc:
>    35: | My statistical question and its answer (slideshow and writing)
>    36: | I developed a compelling and interesting statistical question based on the data I collected. I clearly answered that question by presenting plots, tables, photos and thoughtful written analysis.
>    37: | The statistical question I chose is not fully answered by the data presented. I have put in some effort to answer the question with plots, tables, photos and written analysis, but more detail is needed.
>    38: | My statistical question is simple and straightforward, and answering it did not require much critical analysis by me /// My statistical question was not adequately answered by my graphics and written analysis.
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/probability-inference/langs/en-us/pages/rubric-time-use.adoc:
>    36: | My statistical question and its answer (slideshow and writing)
>    37: | I developed a compelling and interesting statistical question based on the data I collected. I clearly answered that question by presenting plots, tables, photos and thoughtful written analysis.
>    38: | The statistical question I chose is not fully answered by the data presented. I have put in some effort to answer the question with plots, tables, photos and written analysis, but more detail is needed.
>    39: | My statistical question is simple and straightforward, and answering it did not require much critical analysis by me /// My statistical question was not adequately answered by my graphics and written analysis.
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/probability-inference/langs/en-us/pages/time-use-project.adoc:
>    26: === 2. Asking a Meaningful Statistical Question
>    27: Once you have all of your data and have looked at several graphics online about America’s time use, you will declare your statistical question for this project. Some suggestions are below, but feel free to develop your own based on your analysis of the data.
>    40: - A strong statistical question based on the data that you collect.
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/threats-to-validity/langs/en-us/pages/project-threats-to-validity.adoc:
>    22: You and a partner will choose a statistical question that you would be interested in exploring. (Note, you will not actually be investigating this question in full. Rather, you will be developing a faulty plan to answer the question.) Be sure that your question is one that could be answered by closely analyzing data, which also lends itself to many threats needing to be addressed.
>    25: You and your partner will develop a faulty plan to research your statistical question. Remember, your goal here is to use data to misconstrue and mislead. Be sure to describe in detail how you will incorporate each of the following threats to validity.
> 
> ~/Documents/Bootstrap/curriculum/lessons/Data-Science/threats-to-validity/langs/en-us/pages/rubric-threats-to-validity.adoc:
>    10: | Statistical question
>    11: | The students developed a statistical question that lends itself to many threats needing to be addressed.
>    12: | The students developed a statistical question that was somewhat conducive to developing a faulty research plan.

**Comment by schanzer** [comment]
By all means, definitely integrate this! And as always, if it affects the workbooks, do it on a branch.

**Comment by retabak** [comment]
just throwing this here for future reference

[527-Article Text-2410-1-10-20220424.pdf](https://github.com/user-attachments/files/16732038/527-Article.Text-2410-1-10-20220424.pdf)
