### ISSUE TITLE
Data Science Workbook Errors on Making Connections & Defining Rows

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2087]
1) [Making Connections workbook page](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/defining-table-functions/pages/making-connections.html) errors:  question 2 instructs them to make a radius the number of weeks, but then the header of the chart says "age", while the example then uses "weeks". Header should say "weeks".
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/71026046-e104-4561-ae98-05787af14831)
question 2 also says to make the circle green, but then the example in the chart uses blue - should be green, as the Pyret file uses green.
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/950829fb-4c06-4424-bc6d-ff8664adf806)
Question - do you mean for the purpose statement in the associated [Row Functions Starter file](https://code.pyret.org/editor#share=1AqRli9LkPdkkNP2KDp20hkjwepS3JAyp) to state purple while the code states green?  Is that so students fix it to make the purpose and code match?? 
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/ef15dcb9-2fcd-404a-a6eb-35daf51b4181)
 There were just too many things different here causing a lot of confusion.

2) Defining Rows workbook page error: The top line says: "We’ve already given you two row definitions, cat-dog and dog-row:"  cat-dog should say cat-row. ( _I had a teacher stuck during PD thinking she was in the wrong start file, because she never found cat-dog_.)

**Comment by schanzer** [comment]
@joystraub I've made the following changes:

- changed the making-connection page to say `"weeks"` instead of `"age"`
- changed the making-connection page to say use `"green"` instead of `"blue"` in the examples
- changed the defining-rows page to say `cat-row` instead of `cat-dog`

It looks like the Row Functions Starter FIle has already been updated to use `"green"`. @flannery-denny did you tackle this already?

**Comment by schanzer** [comment]
@flannery-denny ignore me - I own the file :P
