### ISSUE TITLE
All of the Data Science Workbook Page Numbers are off by one in the lesson plans

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2088]
The Data Science Workbook starts at page 1, but when page numbers were posted in the lesson plans, they started at page 2. For example:
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/4879d280-cab2-4b1f-83f2-34a11d0a1745)
This continues throughout the entire set of lessons - 
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/4f495483-d274-408a-a143-5f94d02d6064)

**Comment by schanzer** [comment]
@joystraub This was an _embarrassingly_ stupid bug on my part, but you're the only one who caught it so thank you!!
