### ISSUE TITLE
@slidebreak needs some special post-processing in HTML lesson plans

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2091]
`@slidebreak` used to be a no-op in HTML mode, resulting in just..nothing. 

In the common cases where a `@QandA` or `@lesson-roleplay` needed to span multiple slides, this meant adjacent blocks in HTML, and we could use a clever CSS rule to make them appear to be one big one.

Recently, we changed this behavior so that `@slidebreak` would automatically insert a span that cleared any floated element. The thinking was that @slidebreak could also be used as a semantic hint, so there was no need for authors to manually add `@clear` if there was already a slidebreak.

Of course, that broke the CSS rule and now we have two seemingly-adjacent blocks. This makes our lessons look busier, and more importantly it feels like something is _missing_ in between the blocks:

![image](https://github.com/bootstrapworld/curriculum/assets/77126/d9d14b8b-c5f9-4d2b-8271-6423a39ad870)

We have a few ways to solve this:

1. **Don't care** -- maybe the adjacent blocks don't bother other people as much as they bother me?
2. **Revert** -- maybe writing @clear isn't so bad after all?
3. **Post-process** -- we could identify a span with class `.slidebreak` in the post-processor, and just remove the damned thing. This would let the old CSS rules come back to life.

**Comment by retabak** [comment]
I definitely care; adjacent blocks bother me. That said, I don't think I have a strong opinion between options 2 and 3.

**Comment by ds26gte** [comment]
#3 -- removing a `.slidebreak` via the postproc -- is equivalent to not generating it in the first place. This is easy enough. Is there a reason that the `.slidebreak` span should be created in the HTML at all?

**Comment by schanzer** [comment]
@ds26gte That would be even better! I didn't know that was an option!

**Comment by ds26gte** [comment]
I'm concerned that there was a reason we generated that `span` in the first place.

**Comment by schanzer** [comment]
@ds26gte that was me -- I added the span to enforce `clear: both` via CSS. In this situation, we don't need/want that anyway

**Comment by schanzer** [comment]
@ds26gte I was able to figure out a more complex CSS selector that resolves this issue. I've rolled back your changes in the closing commit
