### ISSUE TITLE
Algebra 2 Lesson ToDos

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2092]
ALL

- [x] When opening a starter file, include standard prose that lays out what each column means - along with any additional context
- [x] Add space at bottom of contracts page, with blanks
- [x] Game: write a _linear or quadratic_ function, graph it in desmos, then - on a separate sheet of paper - draw a scatter plot with a strong correlation to match. Switch graphs. Can you figure out the other teams' function? (should immediately follow the graphing activity and discussion of coefficients)
- [x] Ask a synthesize question about interpreting models outside the span of the data
- [x] #2119 
- [x] Teach into horizontal shift and why we often start fitting models assuming it to be zero.
-- [We've drafted these slides](https://teacher.desmos.com/activitybuilder/custom/6697de266df88d2584d1f41c) that can be added to the corresponding slide decks, but we need to decide when and how we want to direct teachers to use them in each of the lesson plans.
-- There is already scrubbed text in exploring linear models from a previous iteration.
- [x] Once we finalize Desmos slides, Update Slide Numbers in Workbook page directions
- [x] Once we finalize Desmos slides, Update Slide Numbers in Desmos Directions in Lesson Plans

LINEAR

- [x] Add horizontal shift section to "other forms of linear models"

QUADRATIC

- [x] Add "Other Forms of Quadratic Models" to the lesson plan, and then add optional pages to the book
- [x] Add a page for deriving the quadratic model from three points
- [x] add opportunity to predict
- [x] "what type of model?" -- the empire state bldg questions assume knowledge that should NOT be assumed.
- [x] Add fourth-level headings for quadratic coefficient, horizontal shift, and (vertical shift), in keeping with the other models

EXPONENTIAL

- [x] For "What Kind of Model? (Tables)", shrink the tables to leave room AND add instructions to hint about drawing arrows for 1st and 2nd difference
- [x] In Desmos, make kids try to find the y after x=big. They'll have to scroll WAY up, and guessing won't work either. (pick it back up in logs)
- [x] Not everyone knows what "New England" means!
- [x] "Exploring the Covid Dataset" -- change scale to 200, not 250
- [x] In the tables showing growth, add the kind of growth to the image itself
- [x] In "Quadratic Models for MA-Table", use the extra space to review quadratics! "Did your parabolas open up or down? Where were the vertices? What was the horizontal shift? Would another form have been more useful than vertex form?"
- [x] Break classifying-defs.adoc into two pages, with LOTS of space. Make the second one optional. Insert an initial questions about increasing v. decreasing Also make sure there's a discussion or reminder of initial value before this page.
- [x] In classifying-defs and classifying-plots, add space and ask kids _why_ they selected the form they did
- [x] Make sure an asymptote is visible in classifying-tables and/or classifying graphs. Ask kids to find it.
- [x] Bring back the roughnum discussion in the lesson plan (maybe it was accidentally deleted?)
- [x] Bring back _(1 - r)_ in the lesson plan, during discussion of growth rate
- [x] Can we end with a cliffhanger, where the numbers get so big so fast that we can't even reason about them

LOGARITHMIC

- [x] Do we want to at least acknowledge that there's a horizontal shift?
- [x] In discussion of _a_, explicit relationship with _b_ --> Desmos acticity where there's a "reference line", and kids can move one line by changing b and another by changing a
- [x] New coefficients need to be re-evaluated
- [x] `log-base` should check for integer answers (thanks, Ben!)
- [x] get consistent in lesson plan about use of exponential / logarithmic as what we changing the scale from linear to. For an example see the launch of "Fitting by transforming data".
- [x] `log-base` isn't in the contracts table!
- [x] `Evaluating-log-expressions.adoc` - Read left to right: "The power you rase <base> to get <:input>". 
- [x] [Does Wealth impact lifespan equally if there’s Universal Healthcare?](https://github.com/bootstrapworld/lessons/exploring-logarithmic-models/pages/transforming-wealth-practice.html) 
- [x] In "Fitting Models for the Countries Dataset", add a space for students to put in the S-value of the optimal linear model they made in Desmos! - _Fitting the linear desmos model is optional - the page only asks them to do it with lr-plot and there's a spot to record s_
- [x] In "classifying-plots.html", shift the origin so there's always room to draw a reflection. Then make solution images with that reflection
- [x] Need to introduce the headache: "after how many minutes will there be 932 bacteria?" If modeled exponentially, this emphasizes the weirdness of the power and opens up the symbolic challenge.
- [x] In "What Kind of Model (Descriptions)", give some sample points
- [x] Start with "What Kind of Model? (Tables)" 
- [x] The x-axis on "exploring countries" still has dollars, instead of thousands of dollars! Fix it.

PERIODIC

- [x] Graphing pages should all start with "fit the model", and experiment from there. In period page, encourage clicking on peak in Desmos
- [x] Fix sin(PI)
- [x] Manipulatives (learning chopsticks)
- [x] Graphing Models: one coefficient per page, four charts per coefficient. Make them much wider! Also pre-populate the x-axis marks to match desmos, which should be set to convenient numbers
- [x] Go straight to fitting the ferris wheel data in desmos!!! THEN make sense of it, THEN do the graphing models page using the same desmos slide!!
- [x] "In Graphing Periodic Models", that math for peaks and troughs is WAY too messy. Two possible fixes: ask when it crosses the x-axis, OR use cosine. In question 3, suggest students try a _different a_ to answer about the distance.
- [x] Add "variability" to the glossary and discuss it before just using it as a known commodity in Modeling periodic relationships. Discuss in "periodic relationships".
- [x] AUDIT: d and c -> h and k
- [x] Better final synthesize questions
- [x] In "Modeling Recent CO2 Levels", the x-axis is _date_, not year! Also, the table on the page doesn't match the graphed table in pyret. The table on paper is the TRUTH - make the rest match
- [x] FD will add fourth level headers in the other lesson plans to discuss the coefficients, and add diagram to accompany them
- [x] on modeling the ferris wheel / translating from sine to cosine I would suggest that we provide them with 2 sine models to translate to cosine and ask them to generate a third. will make it easier for the class to discuss their findings
- [x] explicitly call out the pythagorean theorem in QandA before setting students loose to calculate x and y values of unit circle
- [x] Bring back color-coded COEs for combined model
- [x] And, this is where we should bring back scaffolding for comparing s-values.
- [x] Modeling periodic relationships needs a synthesize section
- [x] Take out "half" times!
- [x] we need to scaffold connecting the linear and periodic functions! I would definitely not expect students to be able to make this leap on their own and we'd much rather have the majority of them be successful with it and be able to add it to their pyret file! ES took a first stab at this. FD wants to hear how it went. My gut is that we should overhaul the second section of Modeling Historical Carbon Dioxide.

**Comment by flannery-denny** [comment]
@schanzer please let me know your final thoughts on which general form of a sinusoidal function you'd like me to finalize materials with before tomorrow. (see info on slack) Thanks!

**Comment by schanzer** [comment]
@flannery-denny just got back to the hotel -- I say use the IM form. ;)

**Comment by flannery-denny** [comment]
@schanzer confirming this wording from yesterday's commit work for you.

- @vocab{Peaks} - the highest points on the wave (also called @vocab{Crests}) 
_Since periodic functions rise and fall repeatedly, there isn't a maxima, but math books sometimes refer to each peak as a local maxima_

Noting that IM uses maximum and minimum in their trig function glossary
<img width="664" alt="Screenshot 2024-06-24 at 10 59 13 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/1636cd94-5ef4-482b-b1d7-de34500558a3">

**Comment by flannery-denny** [comment]
@schanzer I tried to tackle your request re: starter file prose.
- [ ] What do you think about [annotating the columns ](https://code.pyret.org/editor#share=1ZhMIricSR89-NZq1pgZWP_memefAJw65&v=e8968a4) as we import them?
- [ ] There were a few columns I had questions about, so I went to the [README tab of the spreadsheet](https://docs.google.com/spreadsheets/d/14fRmjAiCqGNI5Zr5kGSDjMavln7ILqhSX3N3zGd8CAU/edit?gid=578475144#gid=578475144). And there aren't better descriptors of what the columns mean (eg. poverty rate). And when I click on the links to source data in that file I don't seem to get anywhere.

**Comment by flannery-denny** [comment]
@schanzer there are two fuel efficiency starter files owned by teacher success, neither is the OG file and I'm not sure that either of them are actually the file linked in the `starter-files.js` file. Please check your files. Thanks

**Comment by flannery-denny** [comment]
@schanzer noting that it was important to you to avoid maximum and minimum in the lesson plan, but here is what I found (and just translated) for midline in our glossary

> the horizontal line that passes exactly in the middle between the graph's maximum and minimum points

**Comment by schanzer** [comment]
@flannery-denny What's the problem? One of them is descriptive, and the other is vocabulary. There's no conflict here.

**Comment by schanzer** [comment]
@flannery-denny 

1. The wording from yesterday's commit looks terrific. thanks!
2. I LOVE the way you annotated the columns. One of our participants actually commented on how much nicer the countries starter file was than the other ones, and was thrilled when I told him the other ones were updated to be just as good.
3. I'm afraid I don't have any more knowledge than you do about the columns in the state demographics file :(
4. I saw two files in the "PUBLISHED" folder. One of them is actually the OG file, so I moved it out to the parent folder. I found the published version, switched ownership to teachersuccess@BSW, moved it to the "published" folder and now everything works as expected.

**Comment by flannery-denny** [comment]
Thanks @schanzer. Really helpful to know that the new formatting works for participants. Not sure why I never thought of writing them like that before. Seems so much clearer than repeating the list of names in separate comments... but I wasn't 100% sure it would work for newbies.

**Comment by schanzer** [comment]
@flannery-denny finally done with Bay City and have the space to process. Right now the most helpful items above are:

- Audit the periodic models unit, making sure coefficients match IM. We had some teachers in Riverside complain that what we have is inconsistent with the normal conventions. They felt that _d_ and _c_ should actually be _h_ and _k_. Can you confirm this is what IM does, and adjust accordingly?
- Can you double-check the coefficients for the logarithm unit as well? There were some inconsistencies that tripped people up.
- Do you remember what happened to the "other forms of linear models" section of the linear unit?

**Comment by flannery-denny** [comment]
@schanzer - Feeling Confused - I caught that c and d inconsistency for periodic models before the Alg2 pd and changed them to h and k in the workbook, lesson plan and desmos files. Where did c and d resurface? Were you in a DS training using old versions of things?

**Comment by flannery-denny** [comment]
As for logarithmic models, there seems to be even less standardization and many sites don't try to describe the form with letters standing in for constants at all.

Ours seems to be more complex than [what IM uses](https://im.kendallhunt.com/HS/students/3/4/18/index.html), so I'm not sure what letter to use for the final coefficient
<img width="132" alt="Screenshot 2024-07-13 at 12 11 44 PM" src="https://github.com/user-attachments/assets/b9ccb4dd-d0a8-47d4-9348-5a5d7500265d">

I'm finding [this on wikipedia](https://en.wikipedia.org/wiki/Logarithm):
<img width="88" alt="Screenshot 2024-07-13 at 12 52 53 PM" src="https://github.com/user-attachments/assets/da95dac0-08e6-4463-924b-0527088a0cec">

And [this](https://math.libretexts.org/Courses/Monroe_Community_College/MTH_165_College_Algebra_MTH_175_Precalculus/04%3A_Exponential_and_Logarithmic_Functions/4.04%3A_Graphs_of_Logarithmic_Functions):

> The general form of the common logarithmic function is  𝑓(𝑥)=𝑎log(±𝑥+𝑐)+𝑑
>  , or if a base  𝐵
>   logarithm is used instead, the general form would be  𝑓(𝑥)=𝑎log𝐵(±𝑥+𝑐)+𝑑
>  .

**Comment by schanzer** [comment]
@flannery-denny unfortunately I can't recall where the periodic inconsistency cropped up in Riverside. I suppose it's possible that the DS training used the old version of things, so let's ignore this and see what happens next week.

I'm starting to develop convictions about these coefficients in general: _every_ model has a horizontal and vertical shift, but it looks like math textbooks use these shifts entirely inconsistently! I'm increasingly of the opinion that our modeling approach is forcing standardization across these various formulas, and that's _really_ good for us to do so.

Here's what I'm thinking:

- f(x)=m(x-h) + k
- f(x)=a(x-h)^2 + k
- f(x) =a*b^(x-h) + k
- f(x) = a*log_b(x-h) + k
- f(x) = a*sin(b*(x-h)) + k

This way _k_ is universally identified as the vertical, _h_ as the horizontal. Students learn to pick them out in every model they see, and they don't get hung up on which letter is which. We can explicitly point out that many models have zero for _h_ or _k_, and ask them to rewrite the form to see what they look like without those terms.

I could even see a page where we show them variations on the models where the letters are just _different_ (both using standard coefficients from books and using totally-random ones!), asking them to identify what goes with what. This would be both a fantastically-useful page to develop a higher-level, structural understanding AND a nice way to get around complains like "but textbook XYZ uses different letters! 😩"

**Comment by flannery-denny** [comment]
@schanzer I think I'm generally in agreement, but there is a lot of consistency about the forms linear functions take and I don't see math teachers buying into use of a fourth and different one.

> Slope-Intercept Form: This form is written as y = mx + b, where m is the slope of the line and b is the y-intercept. It provides information about the slope and y-intercept of the line.
> Point-Slope Form: This form is written as y - y1 = m(x - x1), where (x1, y1) is a point on the line and m is the slope. It provides information about a specific point on the line and its slope.
> Standard Form: This form is written as Ax + By = C, where A, B, and C are constants. It provides information about the coefficients of the variables and the constant term.

We could acknowledge that the forms are conventions, some of which are more agreed upon than others, and state that, for lines, tracking horizontal shift is redundant so this form isn't really used.

I always felt comfortable telling my students that "if I were in charge" m and b would not be the convention used, but I wasn't around when the convention was formalized, so I want them to know what they'll be confronted with. And it definitely won't be h and k for linear functions.

**Comment by schanzer** [comment]
@flannery-denny ok, so it sounds like we're in agreement about everything _except_ linear models. Can you start a separate branch to do this switch, since I'm teaching this coming week?

As for linear models -- I would argue that f(x) = m(x - h) + b isn't really new. It's just an acknowledgement that horizontal shifts are real.

**Comment by schanzer** [comment]
@flannery-denny I've moved the non-critical items out of this issue and into #1345 , which we can revisit when planning for Fall2025. Most of what's left here is covered by your `coefficient` branch, which I'm hoping we can merge tomorrow.

**Comment by flannery-denny** [comment]
@schanzer Looking t close this issue, but I see 4 remaining items that haven't been checked off.
- [ ] LINEAR Add horizontal shift section to "other forms of linear models", and make that section required
_I've added it, but not made the section required as I'm pretty sure we decided otherwise in our most recent conversation. Do you agree?_
- [ ] QUADRATIC "Graphing Quadratic Models" -- Desmos activity: (1) remove minor gridlines, and (2) change scale so the graphs for numbers 4 and 6 fit. only need two graphs for H and K, but more for A. Leave space to write function under each graph
_Did you do this and forget to check it off or has it been added to the other list and can safely be deleted here?_
- [ ] LOGARITHMIC In discussion of a, explicit relationship with b --> Desmos activity where there's a "reference line", and kids can move one line by changing b and another by changing a
_Not seeing this in the desmos file - is this a priority or has it been added to the other list and can safely be deleted here?_
- [ ] PERIODIC Check solutions for correctness
_This would require me working through the entire unit - is this a priority or has it been added to the other list and can safely be deleted here?_

**Comment by flannery-denny** [comment]
Thanks @schanzer. Noting that if you add new Desmos activities to the existing files anywhere other than the final slide, slide numbers will have to be updated in both the lesson plans and workbook pages for all of the slides that follow. 
- Doing that with find and replace, requires starting from the end of the deck. 
- Inconsistencies make it hard to catch everything in one pass.

**Comment by schanzer** [comment]
@flannery-denny moving "check solutions for correctness" to a separate issue and closing this one!
