### ISSUE TITLE
Links to Workbook Pages in Data Science Lesson Pages gives 404 Error

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2094]
In each data science lesson plan where the dropdown arrow for student workbook pages is, this is a link that when clicked on goes to an error 404 page.  There really is no need to click on that link - teachers just need to click on the arrow to reveal the individual pages.  Is there anyway to delete the links on the lesson page?  It is confusing to teachers.
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/914f745a-ab7c-4e94-937a-90c72960d8f6)
![image](https://github.com/bootstrapworld/curriculum/assets/147871687/2e5d14d0-0d72-4d49-a8c7-353d85dda938)

**Comment by schanzer** [comment]
@joystraub I'm confused by this - you want to delete the links to download the student workbook?

**Comment by schanzer** [comment]
@joystraub are you sure it's not working? I fixed the link this morning.

**Comment by joystraub** [comment]
I have not been back in this today. I was just responding to your question.
You were correct that I should have written to correct the download able
link rather than to delete the link. Glad it got fixed.
