### ISSUE TITLE
slide-preproc needs to handle [super|sub]script in page titles differently

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2096]
In `exploriong-exponential-models`, we have a workbook page with a math function in the title. This function happens to have a superscript.

Right now slides-preprock does the same thing as preproc: it surrounds the superscripted item with `^`, which asciidoctor recognizes. For example: `f(x) = ab^x^ + k`

md2googleslides, however, has no idea what to do with this!  Instead, we need to surround it with `<sup>` tags:  `f(x) = ab<sup>x</sup> + k`

The same is true for subscripts, which show up in `exploring-logarithmic-models`

**Comment by schanzer** [comment]
Thanks, @ds26gte !

**Comment by flannery-denny** [comment]
The way this got fixed is breaking titles for some Alg 2 workbook pages
<img width="403" alt="Screenshot 2024-06-26 at 11 41 25 AM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/83cbf43c-842f-40c8-b0c8-9363a6d08f45">

**Comment by schanzer** [comment]
Confirmed fixed. Thanks, @ds26gte !
