### ISSUE TITLE
Preview: State Demographics Starter File

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2098]
It doesn't have alabama and alaska defined, but it needs both for the accompanying workbook page

(And can we move this into the Curriculum / Algebra2 folder?)

**Comment by flannery-denny** [comment]
@schanzer I may have successfully resolved this? Or you made need to republish and update the starterfiles.js file.

**Comment by schanzer** [comment]
Yep! The file was magically updated and it works great now.

I take it those files were only in that folder temporarily? Once you've moved them where they need to go, this issue can be closed.
