### ISSUE TITLE
regression in build-slide: inferring title slide layout

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2103]
`./build-slide -f order-of-operations` should assign "Algebra" as the pathway, and use that to autoselect the appropriate title slide. Instead, it's selecting the one for Data Science!

Hopefully a very small regression.

**Comment by ds26gte** [comment]
I'm getting `layout = A Title Slide` (`A` = `Algebra`) on a recent run.  Is there anything other than the title slide that needs this check?

**Comment by schanzer** [comment]
@ds26gte Aha! When we started using the Algebra title slide for Early Math and Algebra2, we changed the slide layout title to "Math Title Slide" but never updated the lua script accordingly. Will push a fix momentarily...
