### ISSUE TITLE
box plots worksheet needs to switch lesson sections

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2104]
All of the instruction required for students to complete this page - https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/box-plots/pages/identifying-shape-boxplots.html - happens in the first section of the lesson... so it is a little surprising to find it in the *second* section of the lesson.  Can I move it to the first lesson section?

I also think we need to add an explanation (for teachers) explaining at least one of the solutions to Matching Box Plots to Histograms. We could add it as an italicized sub-bullet in the @lesson-instruction box where the worksheet is instroduced. There's not a whole lot of instruction / guidance on this page, and it is not an easy one.

@schanzer - I'm happy to make these changes if you give me the go-ahead. (Would I do so on master? Or elsewhere?)

**Comment by schanzer** [comment]
@retabak any change that makes things better without modifying the workbook is always welcome. I say go for it. No harm in using a separate branch - I think that's the right impulse. Go for it.
