### ISSUE TITLE
Bring back link attribution

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2109]
I'm looking at `ds-intro` live on the web. I would expect to see (NYTimes) after the **What's Happening in this Graph?** link. 

<img width="875" alt="Screenshot 2024-07-10 at 1 51 44 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/4a4a6f8d-4a57-4dbf-93b4-b74c22553f5d">

Did we lose Dorai's magic when we got rid of opt-online-exercises?

**Comment by flannery-denny** [comment]
I'm seeing this in the correlations lesson, so am adding (NYTimes) by hand.

```
- @link{http://tylervigen.com/, Spurious Correlations (tylervigen.com)}
- @link{http://guessthecorrelation.com/, Guess the Correlation (guessthecorrelation.com)}
```

But, for the record, @schanzer, It looks to me like getting rid of `opt-online-exercise` was a mistake and presents a maintenance risk.

**Comment by schanzer** [comment]
@flannery-denny thanks for flagging - I still think the reduction in complexity was the right call. Let's see if this presents a headache beyond these two links, and if it does we can think of a better way to address it.
