### ISSUE TITLE
Let's have students make box blots during "Making Box Plots"!

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2111]
It seems odd that we don't, especially when we *do* have students draw histograms by hand. I think actually going through the process of making the display yourself builds intution. 

Oooh, or, even better!: We could have students create histograms and box plots for the SAME (very small, very simple) datasets. For the histograms, we would give them structure (e.g. bin size provided, y-axis intervals labeled) like we do on [making-histograms](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/histograms/pages/making-histograms.html).

Match box plots and histograms is quite challenging; I think an exercise like this could build intution around the connection between box plots and histograms. Currently, I'm not sure that we offer enough guidance for teachers on how to do this / support students who are struggling with it.

For the time being, this could be an optional page which gets added to the workbook in the future.

**Comment by schanzer** [comment]
@retabak don't they draw them [here](https://bootstrapworld.org/materials/fall2024/en-us/lessons/box-plots/pages/summarizing-columns-mos.html)?

**Comment by retabak** [comment]
Tbh, I thought the purpose of that page was to have students try out the `box-plot` function in Pyret. That worksheet is, in my opinion, pretty close to useless. The only questions that require any thinking at all are Q4 and Q8. Kids are literally just copying information. 

Here's the sort of problem that we need (from Illustrated Math, 6th grade):
![image](https://github.com/user-attachments/assets/beaf58c9-8121-448a-ae65-6e2a16666150)

Making a box plot is not terribly complicated; if we're worried about it taking too much time, we could order the numbers least to greatest.

We are TELLING students that each section of the box plot represents 25% of the data, but they never actually see that for themselves. 

I also proposed, in my original message, that we have students create histograms from the same small & simple datasets, which would help with matching box plots and histograms.

**Comment by flannery-denny** [comment]
I agree that students should make a box plot from a dataset and I'll tackle it.

I disagree that the page already in the book is useless. I don't think the connection between the 5-number summary and the box-plot is fully intuitive and I think having students find the information in pyret and forge that connection might help them know what all of the terms mean and all the places they can look to find them.

**Comment by retabak** [comment]
@flannery-denny - maybe we should modify the existing page to NOT use pyret at all. I don't think that students are "forging a connection" because they don't actually need to create the boxplot themselves; they can just sketch the boxplot that appears in Pyret.

**Comment by schanzer** [comment]
@retabak this is a good idea! And since we're still uploading new drafts of the workbook, maybe there's a way to change this page such that:

- teachers using the current version aren't disrupted
- teachers using the new version get the new-and-improved stuff

**Comment by retabak** [comment]
whoever works on this should also address #2118 !
