### ISSUE TITLE
Blank DS Starterfile currently isn't blank

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2113]
In the tutorial video students are instructed to replace everything in the starter file in all caps. [This starterfile](https://code.pyret.org/editor#share=1xu1XQQr9cYbCJaidK6n-NhvKFC-Xe296) links to a specific spreadsheet.

**Comment by flannery-denny** [comment]
@schanzer I modified the [published file](https://drive.google.com/file/d/1xu1XQQr9cYbCJaidK6n-NhvKFC-Xe296/view?usp=drive_link), but couldn't find the OG file. Any chance you have it, and could update and transfer ownership to teacher success?

**Comment by schanzer** [comment]
@flannery-denny for some reason Google isn't letting me change the permissions. I've been getting this for the last two days

<img width="653" alt="image" src="https://github.com/user-attachments/assets/985018fa-2a60-4f37-9f2c-b1a53c9a0a79">


But it looks like you already made a new version from the Teacher Success account, and updated the starter-files.js dictionary. Any reason for me not to just delete my version of the published file?

**Comment by flannery-denny** [comment]
@schanzer I've encountered the same issues when trying to transfer ownership. I just have a published file at the moment. And I made and saved the updates in it. Fine by me to delete the other as long as that works for you.
