### ISSUE TITLE
scatter-plot contract should show up in the annotated form in the lesson plan, not the old text-only form

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2114]
Be sure to update public slide deck

**Comment by flannery-denny** [comment]
@schanzer It looks annotated to me.
<img width="746" alt="Screenshot 2024-07-11 at 12 00 53 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/c925d2c9-e0f8-4541-8af9-8aacf2e3055d">

**Comment by flannery-denny** [comment]
@schanzer but the contract for `line-graph` was wrong. I've fixed it in the lesson plan, but not in slides. Have to say that it feels strange to offer up this contract here, in that there is no sensible use-case for it presented in the lesson.

**Comment by schanzer** [comment]
@flannery-denny ah, good point! This was the first time the issue has come up, since the other contracts we introduce via slide don't use "extended" comments. Wrapping it in a 1-cell table forces our slide generator to turn it into an image, which is exactly what we want.

As for `line-graph`, this was included to let teachers know it _exists_ -- there's no use for it in this lesson, but it's come up in enough PDs that it's clearly on some teachers' minds.
