### ISSUE TITLE
@indented should be a no-op in slide mode

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2115]
I'm in `function-composition` on `master`.
I noticed this repetition in the lesson plan <img width="785" alt="Screenshot 2024-07-11 at 2 23 34 PM" src="https://github.com/bootstrapworld/curriculum/assets/66691020/08de0d33-8e10-4fbf-912b-83701e892e69">

And here's what I see in the file. I don't understand why `@ifslide` is being used here, but, since it is, I would expect only the second of these to show in the lesson plan. So, rather than deleting the first to resolve the issue, I wanted to flag this in case it's a bigger issue.

```
@ifslide{
@indented{
[cols="^.^6a,.<1,^.^3a", frame="none", stripes="none"]
|===
| *Three Steps*
|
| *Three Circles*

|
[cols="2a,3a", grid="none", frame="none", stripes="none"]
!===
!`step1 = add1(4)`      ! _(Start with `4`, and now we have `5`)_
!`step2 = double(step1)`! _(now we have `10`)_
!`step3 = half(step2)`  ! _(now we're back to `5`)_
!===
| *...or...*
|
@show{(coe '(half (double (add1 4))))}

_half( double( add1(4) ) )_
|===
}}

@slidebreak

@indented{
[cols="^.^6a,.<1,^.^3a", frame="none", stripes="none"]
|===
| *Three Steps*
|
| *Three Circles*

|
[cols="2a,3a", grid="none", frame="none", stripes="none"]
!===
!`step1 = add1(4)`      ! _(Start with `4`, and now we have `5`)_
!`step2 = double(step1)`! _(now we have `10`)_
!`step3 = half(step2)`  ! _(now we're back to `5`)_
!===
| *...or...*
|
@show{(coe '(half (double (add1 4))))}

_half( double( add1(4) ) )_
|===
}
```

**Comment by schanzer** [comment]
@ds26gte it appears that nesting @indented inside @ifslide causes the outermost directive to be overridden

<img width="603" alt="image" src="https://github.com/user-attachments/assets/e8beca8b-9639-4bb6-84a8-b9e110732d67">

I've removed the @indented directive from the slide-only table, which fixes the immediate issue in the lesson. But this is not a general solution, and kudos to @flannery-denny for finding it!

**Comment by flannery-denny** [comment]
@ds26gte the solution we would like it to make @indented a no-op inside @ifslide and warn authors
