### ISSUE TITLE
Use MathJax font in .mathunicode where appropriate

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2117]
I think this is different from the tiny h issue we've seen elsewhere?
<img width="304" alt="Screenshot 2024-07-12 at 12 41 16 PM" src="https://github.com/user-attachments/assets/9a816fa9-b2dd-4881-9901-ed07df5327b8">

**Comment by retabak** [comment]
wow! this look crazy! This looks different from anything I've seen.

**Comment by schanzer** [comment]
@flannery-denny Which is uglier: this new _h_ or the weirdly-small old one?

**Comment by flannery-denny** [comment]
@schanzer This one is definitely worse.FlanneryOn Jul 12, 2024, at 2:16 PM, Emmanuel Schanzer ***@***.***> wrote:﻿
@flannery-denny Which is uglier: this new h or the weirdly-small old one?

**Comment by schanzer** [comment]
@flannery-denny I just pushed an experimental fix on the duration branch, so as not to screw up master. Let me know what you think? The spacing between characters is a little off, but the letters look better overall.

**Comment by flannery-denny** [comment]
@schanzer Just checked it out on `duration` and that is a huge improvement!

**Comment by schanzer** [comment]
@ds26gte any downside to this commit thaty you can imagine? I _think_ the MathJax font is only available for pages that require mathjax. If we have a page with tons of @math, but 100% of it resolves to mathunicode...does it still load mathjax?

**Comment by ds26gte** [comment]
To do: Add CSS styling for the selector `.mathunicode i` to use your (@schanzer's) preferred font from MathJax or wherever. Thx.

**Comment by schanzer** [comment]
@flannery-denny and @retabak would love to get your feedback on a fresh pull and clean build. Specifically, check out `inequalities2-compound` and see if the mathy expressions look better

BEFORE (live on the web):
![image](https://github.com/user-attachments/assets/b77ce39c-1da7-47f5-b3eb-d45c9c5ab405)

AFTER:
![image](https://github.com/user-attachments/assets/df58785b-d8e4-455a-919d-1693badfb185)

**Comment by ds26gte** [comment]
Opening double quotes jar!

**Comment by flannery-denny** [comment]
@schanzer I have to agree with @ds26gte about the open quotes. But the letters look much better than they have in a long time!

**Comment by ds26gte** [comment]
I could special-case the quotes. What do we want them to be -- some sort of  "straight" quotes? Do we want to distinguish opening and closing quotes?

**Comment by schanzer** [comment]
Straight quotes would be great! Directional quotes opens up a whole can of worms and expectations for how we support other things in the future

**Comment by ds26gte** [comment]
The double-quote in the HTML is the standard straight one, but you're using a MathJax font that has no concept of a straight quote, but converts it always to an opening quote. Is it necessary to use a MathJax font for things outside `<i>`? We only need the MathJax italic font, right, for the alphabetic chars?

**Comment by schanzer** [comment]
@ds26gte good point! YES, let's use the standard font for quotes or apostraphes. I wouldn't use italics as a guide, since in theory we can have non-italic mathjax.

**Comment by ds26gte** [comment]
My original suggestion was that you style only for the CSS selector `.mathunicode i`.  I can add a special class, say `.usemathjaxfont` that I can add to the `<i>` tag and also anything else that you feel should get the mathjax font (whether italic or not).

**Comment by schanzer** [comment]
Ok, in that case I'd say it's _just_ the character list you have right now. Let's go with that see what shakes out.

Probably best to do this on a separate branch, since there is likely to be some trial-and-error

**Comment by schanzer** [comment]
@ds26gte I've added CSS rules and an additional font, which uses MathJax bold if a MathJax element falls within a `<b>` tag. It does the same for `.usemathjaxfont` elements that have a parent `<b>` tag. `i.usemathjaxfont` will use the italic font, and `.usemathjaxfont` with use the regular mathjax font

**Comment by flannery-denny** [comment]
@schanzer @ds26gte I can't follow this issue because there's no checklist in the description, but I think this note belongs here rather than in a new issue?

<img width="588" alt="Screenshot 2024-07-24 at 9 57 13 AM" src="https://github.com/user-attachments/assets/83571338-54fa-432b-b7ac-59d4faa5f583">

@schanzer loves to use build when he writes lesson plans. (I'm constantly removing it ;)
And @math doesn't render as bold in his bolded sentences.

**Comment by ds26gte** [comment]
I think this works as expected in the yet-to-be-merged `mathjax-font-for-mathunicode` branch: 
<img width="582" alt="Screenshot 2024-07-24 at 11 15 06 AM" src="https://github.com/user-attachments/assets/dc881ed2-ba89-4096-84e1-10848c19a7e4">

**Comment by schanzer** [comment]
This is now complete, but I won't merge until after the next round of workbook updates
