### ISSUE TITLE
fix "summarizing columns with measures of spread" answer key

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2118]
We chose to use intervals of 37.5 for a box plot drawn by hand? I don't think anyone in their right mind would do that. 

Noticing that we also chose to round the values on the numberline so it appears that we are *not* using consistently sized intervals? If I had to draw by hand a box plot with a spread of 172, I would opt to do intervals of 25, I think?

OMG, upon closer inspection, the minimum, Q1, and the median are completely wrong also. 

![image](https://github.com/user-attachments/assets/e4cc51d8-c6a0-49b9-a25f-bd4d14d9b71c)

**Comment by schanzer** [comment]
@flannery-denny hope you don't mind if I assign this to you? trying to make sure you're not stuck waiting on me for stuff over the next 10 days
