### ISSUE TITLE
rubys are sometimes landing on fitb after most recent merge of `master` into `coefficients`

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2121]
This example is from the *Exploring Exponential Models* lesson `quadratic-models`
<img width="376" alt="Screenshot 2024-07-19 at 6 18 23 PM" src="https://github.com/user-attachments/assets/8beb50ca-bf33-45e5-a0fd-2661e776a88b">

**Comment by schanzer** [comment]
Looks like I forgot to push an important CSS fix! Thanks
