### ISSUE TITLE
identify an accessible subset of pioneers to highlight for struggling readers

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2124]
- [ ] Find icon to denote EZ pioneer
- [x] Identify EZ pioneers
- [x] Infrastructure to tag pioneers as EZ

**Comment by flannery-denny** [comment]
@schanzer let's discuss how best to make this subset discoverable in our meeting today:

- Mark Dean
- Ajay Bhatt
- Ellen Ochoa
- Evelyn Granville
- Katherine Johnson
- Robert Moses
- Chieko Asakawa
- Jerry Lawson

**Comment by flannery-denny** [comment]
Saving some icon options here. Will add more. I would suggest whichever we pick also gets used to denote our starter datasets. @Retabak guessing you may have ideas / opinions but don't get lost down a rabbit hole thinking about it, please.

![image](https://github.com/user-attachments/assets/9eb1f99d-1f37-40a3-9255-c8a9daaf84ea)
📚
🏫
![image](https://github.com/user-attachments/assets/d54937a2-d1a4-4330-b544-b81596151af5)
😉
![image](https://github.com/user-attachments/assets/805f0bee-1996-4e62-9cce-9f9319d178f2)
![image](https://github.com/user-attachments/assets/280988a8-4d4c-4ab9-a3cb-406e97466711)

![image](https://github.com/user-attachments/assets/32f91cd0-7640-4691-8038-d0f691b0c45d)

![image](https://github.com/user-attachments/assets/632908fc-09f2-4bee-894d-91387c81dc5f)

**Comment by schanzer** [comment]
I LOVE the growing plant -- to me, that totally communicates that it's for "growing readers". @retabak , any objection?

**Comment by flannery-denny** [comment]
@retabak No matter what icon we choose, we would definitely tell teachers
to look for it, just as we currently do with the starred datasets. The
motivating factor for identifying an icon indicating an entry level subset
is that our use of stars is inconsistent in that we mostly use them to
indicate challenge problems.

I have no attachment to the growing plant icon.

I learned this week that the Japanese have a standard icon for "beginner"
that looks like this 🔰. It doesn't mean anything to Americans, but that
doesn't mean we couldn't tell our teachers to look for it.

**Comment by schanzer** [comment]
Let's keep this simple - "good place to start" or bust. 

Some other proposals:

# 🧸
# 🧒
# 🧑‍🎓
# 😌
# 🐣
# 🚸
# 🔅

**Comment by schanzer** [comment]
@retabak and @flannery-denny what do y'all think of the proposed logos?

**Comment by retabak** [comment]
of these, the only one that didn't make me giggle or scratch my head was the sunshine at the bottom.

**Comment by flannery-denny** [comment]
I'm fine with the cloud that's being used as place holder until we come up with something better. But, since it's mostly white, I'm not sure it will really print well in workbooks. Currently leaning toward that Japanese symbol for beginner 🔰, because it isn't trying to be anything in particular (Much like an asterisk and a star aren't trying to be anything in particular, so we can define them to serve the purpose we're using them for.) and there's no risk of us wanting to use that same symbol to mean anything other than beginner

**Comment by retabak** [comment]
Totally works for me.
