### ISSUE TITLE
Standard 8.F.A.1 should be explicitly demonstrated alongside Contracts

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#213]
CCSSM 8.F.A.1 - Understand that a function is a rule that assigns to each input exactly one output. The graph of a function is the set of ordered pairs consisting of an input and the corresponding output.

The first half of this standard should be explicitly demonstrated for students/teachers when Contracts are introduced in `alg-domain-and-range`

**Comment by schanzer** [comment]
Also, we really need to bring back the function-machine concept, which is both super-common in math books and directly connects to contracts. (Why was it cut from the old lessons?)
