### ISSUE TITLE
@indented issue with slides? -> Refactor directives

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2133]
In [exploring-logarithmic-models slide 44](https://docs.google.com/presentation/d/1lEUP3puYnMwGJuOy312pIckwgBYTMbWnwcie7EWZtQU/edit#slide=id.6524d1f2-4e65-11ef-84e3-a312bccf5d50), it looks like something is being processed incorrectly...

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/dab3f924-7194-4410-9390-102756dd7da6">

Here's the asciidoc:
```
== Additional Exercises

For more practice transforming data and programming with filters: 

@indented{
@opt-printable-exercise{transforming-wealth-practice.adoc} is a guided activity that repeats the Data Science and Linearization techniques used here, but with the idea of exploring the relationship of universal healthcare with respect to wealth and median lifespan.
}

@strategy{Coming Soon!}{

We are working on collecting more datasets that can be modeled with logarithmic functions so that we can offer students more practice with using linear regression to build logarithmic models.
}
```

**Comment by flannery-denny** [comment]
The last time we discussed the fact that `@indented` was breaking things with slides we decided that it should be treated as a no-op

**Comment by schanzer** [comment]
Additional debugging! It has to do with the `@strategy` directive. Changing it to something else resolves the issue:

```
== Additional Exercises

For more practice transforming data and programming with filters: 

@indented{
@opt-printable-exercise{transforming-wealth-practice.adoc} is a guided activity that repeats the Data Science and Linearization techniques used here, but with the idea of exploring the relationship of universal healthcare with respect to wealth and median lifespan.
}

@teacher{

We are working on collecting more datasets that can be modeled with logarithmic functions so that we can offer students more practice with using linear regression to build logarithmic models.
}

```

**Comment by ds26gte** [comment]
Note that using `@pd-slide` in the last `Additional exercises` creates other problems, viz., because it creates a new last slide.

**Comment by schanzer** [comment]
@ds26gte this seems to have broken other stuff. [Here's the result of running the revised script on exploring-logarithmic-models](https://docs.google.com/presentation/d/1A5p92g8gIlozy3FoMdPUpRDKwHyEjpRmWzjSz4E6bSI/edit#slide=id.b884d82a-5452-11ef-bab1-47925a82d4bb). Note that slides 43 and 44 are now _blank_, 45 is missing a title, and 46 and 47 are also blank when using @strategy. 

Did you check out the MKD file? Here's what it shows:

```



---

{layout="Math Title and Body"}
# 




---

{layout="Math Title and Body"}
# 




---

{layout="Synthesize"}
# 


- Why is the <b><i>S-value</i></b> for our logarithmic model the same as the <b><i>S-value</i></b> for our linear model after transforming?
- Why were our coefficients for linear and logarithmic models the same, even though they were for different terms?
- Why do you think the relationship between wealth and median lifespan is logarithmic?
- Suppose all the tech companies in the Bay Area (Google, Apple, Facebook, etc.) decided to secede and form their own country with a `pc-gdp` far, far beyond the range of the rest of the data. Would it be appropriate to use our model to predict the `median-lifespan` for their employees? Why or why not?



---

{layout="Math Title and Body"}
# 




---

{layout="Math Title and Body"}
# 



```

You may want to confirm the MKD file looks right before future commits.

**Comment by schanzer** [comment]
@flannery-denny and @retabak This issues has been changed and retitled, and I wanted to document _why_:

- It actually has nothing to do with `@indented` at all!
- The problem is that `== Additional Exercises` and `@strategy` are both handled specially to make our lives easier (and Dorai's harder), and it turns out that both "special" uses stomp on one another. 
- Dorai did a ton of work under the hood to make the "special" stuff less painful, but ultimately there's a conflict of behaviors here that just cannot be resolved without us losing two very valuable authoring conveniences. 
- The end result is that the underlying code is a lot cleaner (benefits to that down the road!), but for authors we just have to avoid using `@strategy` inside `== Additional Exercises`. 

This feels like a minor issue, since it's only ever come up in this one lesson. And in fact, some of the work Dorai did allows us to still do this is we truly need to, but in general we should avoid this.
