### ISSUE TITLE
HTML entities are being translated verbatim in google slides

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2134]
In [exploring exponential models](https://docs.google.com/presentation/d/1VtAkrRUJUw-1ugTpqSyPCpgZTpAuFnqPzzp1u-KUhpc/edit#slide=id.g2ef78ab9c7b_0_59), the `~` character is being translated verbatim

**Comment by ds26gte** [comment]
They get translated verbatim only when they're within backticks, which always signals verbatim in Markdown. AsciiDoc allows expansion unless double-backticks are used. In this case the source contains
```
the use of `&#126;1` to tell Pyret
```
The backticks don't prevent conversion of the `&#126;` in AsciiDoc but do so in Markdown. While I can postproc it away inside `make-slides.lua` for this case, it doesn't seem right.  (For instance, in the rare case where the AsciiDoc source contained double-backticks, we would still convert any enclosed HTML entities, as it's too difficult for the postproc to keep track of the number of enclosing backticks if any.)

My suggestion is to rewrite the original as
```
the use of ``~1`` to tell Pyret
```
and avoid using HTML entities inside single-backticks at all.

**Comment by schanzer** [comment]
Confirmed fixed. Thanks, @ds26gte !
