### ISSUE TITLE
Defining image widths for tables that render as images in slides

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2147]
@ds26gte @schanzer 

- We are able to define an image width and have that width transfer to slides. 
- Some slide images come from tables.  As far as I know we are not yet able to define the width of an image on a slide that is generated from a table. 
- Would it be easy to add this feature? If so, it would improve our slide-build automation.

**Comment by schanzer** [comment]
Unfortunately it's not possible -- once we take the screenshot of the table, the width is fixed. Can you send me a link AND a screenshot to an egregious example? Maybe there's something we can change on the authoring end.

**Comment by flannery-denny** [comment]
Hi @schanzer.
Here's [slide 30](https://docs.google.com/presentation/d/1JXzA3UV9D7aGjE2Ekxe09KUY6ROGEkMB1YDoBC7l2wY/edit#slide=id.g2f2e251d814_0_1099) from the boxplot deck after I adjusted it by hand
<img width="869" alt="Screenshot 2024-08-15 at 10 48 52 AM" src="https://github.com/user-attachments/assets/4fd33dd1-cf9a-468e-9914-2a27a867f371">

This is how [slide 30](https://docs.google.com/presentation/d/11qpBtL1Wb7mRRa7SOxEDi-UxiNShyAZcByLDgdXegSk/edit#slide=id.fdd9e09a-5b15-11ef-b935-ab6b6d8b639f) renders by default
<img width="869" alt="Screenshot 2024-08-15 at 10 53 12 AM" src="https://github.com/user-attachments/assets/62e69aea-1fc2-4f2d-ab66-239ba5bfa495">

Can't promise the link to that deck will remain active forever as it's an auto-gen slide we should delete.

**Comment by schanzer** [comment]
@flannery-denny unfortunately, the only solution here is to stop using tables when you really want to just glue two images together.
