### ISSUE TITLE
Add anchor links to each section (including additional exercises)

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#215]
I find myself wanting links not just a lesson, but to a specific section _within_ that lesson. It would be great to auto-generate these anchors using anything with a Level-2 heading!

For example:

```
<h2 id="_identifying_dynamic_patterns_duration_30_minutes_">
    Identifying Dynamic Patterns
    <span class="duration">30 minutes</span>
</h2>
```

Could become:

```
<a name="_identifying_dynamic_patterns_duration_30_minutes_"/>
<h2 id="_identifying_dynamic_patterns_duration_30_minutes_">
    Identifying Dynamic Patterns
    <span class="duration">30 minutes</span>
</h2>
```

**Comment by ds26gte** [comment]
The presence of the `id=` inside the `<h2>` already functions as an anchor. You don't need an additional `<a name=...>`.
