### ISSUE TITLE
When titling PDFs, grab the filename and replace dashes with spaces, put in title case

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2150]
whereas `.adoc` files begin with a `= Title` that the build system can utilize, the only place for us to name a pdf is either in the file name itself (which always utilized `-`) or in the lesson plan. 

Given this, I would expect the file referenced as `@printable-exercise{boxplot-vocab-map.pdf, Box Plot Vocab Concept Map}` to be listed in the materials table as **Box Plot Vocab Concept Map**. Instead it appears as **boxplot-vocab-map.pdf**

I suspect the authors failed to write a spec for `pdf` files so Dorai is following the `adoc` spec here?

**Comment by ds26gte** [comment]
Hm. Not able to replicate on `master`. Which branch is it failing on?

**Comment by schanzer** [comment]
Confirmed fixed!

**Comment by schanzer** [comment]
@ds26gte this seems to have added a `0` to the end of other filenames:

<img width="482" alt="image" src="https://github.com/user-attachments/assets/676e403d-964e-4235-ba82-b3489501f047">

As a result, they appear in the lesson plan with a zero at the end of the title

**Comment by schanzer** [comment]
Odd - this appears to have returned to normal. Chalking this one up to an unclear `make` on my part!

**Comment by schanzer** [comment]
@ds26gte some more debugging information:

- With this commit in place, `make book` does not complete. It throws errors when trying to collate:

```
Not making workbooks for distribution/en-us/courses/algebra-pyret as it's missing the following workbook pages:
- distribution/en-us/lessons/distance/pages/Distance-bw-Two-Points-Multiple-Representations.pdf
Not making workbooks for distribution/en-us/courses/algebra-wescheme as it's missing the following workbook pages:
- distribution/en-us/lessons/distance-wescheme/pages/Distance-bw-Two-Points-Multiple-Representations.pdf
Not making workbooks for distribution/en-us/courses/data-literacy as it's missing the following workbook pages:
- distribution/en-us/lessons/box-plots/pages/boxplot-vocab-map.pdf
Not making workbooks for distribution/en-us/courses/data-science as it's missing the following workbook pages:
- distribution/en-us/lessons/box-plots/pages/boxplot-vocab-map.pdf
- distribution/en-us/lessons/checking-your-work/pages/ai-article-register.pdf
Not making workbooks for distribution/en-us/courses/data-science-codap as it's missing the following workbook pages:
- distribution/en-us/lessons/box-plots-codap/pages/boxplot-vocab-map.pdf
Not making workbooks for distribution/en-us/courses/math-grade7 as it's missing the following workbook pages:
- distribution/en-us/lessons/box-plots/pages/boxplot-vocab-map.pdf
Not making workbooks for distribution/en-us/courses/math-grade8 as it's missing the following workbook pages:
- distribution/en-us/lessons/distance/pages/Distance-bw-Two-Points-Multiple-Representations.pdf
Not making workbooks for distribution/en-us/courses/ok as it's missing the following workbook pages:
- distribution/en-us/lessons/box-plots/pages/boxplot-vocab-map.pdf
- distribution/en-us/lessons/checking-your-work/pages/ai-article-register.pdf
Not making workbooks for distribution/en-us/courses/reactive as it's missing the following workbook pages:
- distribution/en-us/lessons/distance/pages/Distance-bw-Two-Points-Multiple-Representations.pdf
Not making workbooks for distribution/en-us/courses/videogame as it's missing the following workbook pages:
- distribution/en-us/lessons/distance/pages/Distance-bw-Two-Points-Multiple-Representations.pdf
make[1]: Leaving directory '/Users/schanzer/Documents/Bootstrap/Development/curriculum'
```

- Flannery, Rachel and I haven't been able to come up with a pattern that is reliably reproducible, but the "zero-ending page titles" seem to happen at least 20-30% of the time after a series of forced or unforced makes

**Comment by schanzer** [comment]
Closing now that #2163 is tracking the issue
