### ISSUE TITLE
bug - When I click on a link from a workbook page, the link should open in a new window

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2151]
I am on the AI branch in the decision tree lesson.
`level-1.adoc` as a link to `decision-tree-data.adoc`. Users need to be able to view these two documents simultaneously, but when I click on decision tree data it replaces the window I have open for level-1.

**Comment by schanzer** [comment]
@flannery-denny do you want this to be the case for ALL links in workbook pages? I don't think that's the spec right now, but it's an easy change to make as long as we're comfortable doing it everywhere.

**Comment by flannery-denny** [comment]
I'm pretty sure it should be. Can't think of a reason why not. Adding it to the curriculum meeting agenda so that @retabak can weigh in and you can make a counter argument if you have one.

**Comment by retabak** [comment]
I think I agree with @flannery-denny but curious if you have a counter-argument, @schanzer.

**Comment by schanzer** [comment]
Nope

**Comment by ds26gte** [comment]
Actually, it works as requested already for me, on `ai-lesson`.  I.e., it opens in a new tab.

**Comment by schanzer** [comment]
Confirmed fixed on `ai-lesson`
