### ISSUE TITLE
Explore the feasibility of recreating Desmos assessments in MD quiz

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2156]
- [ ] currently running `npm exec vite build` only builds the `.toml` file titled `sample-quiz`
- [ ] How do we control answer order for multliple choice?
-- currently they are sometimes reordered based on something happening behind the scenes
-- this is incompatible with offering choices like "both" or "all of the above"
-- authors should have control, which it seems could be accomplished by allowing two different blocks of `prompt.distractors = [ ]`
- [ ] authors should not be responsible for generating random ids for each question
- [ ] Get a complete list of currently available question types. From the example quiz we are able to see 3 question types:
-- multiple choice (clear how to use this)
-- short answer (clear how to use this)
-- tracing (need more info! **Guessing this question type is a subset of a different question type that is actually what authors should be using?**
)
The tracing question type appears to be the most exciting option because it gives the quiz taker a chance to justify an answer... but... in it's current state it is completely unusable by Bootstrap authors because some of the question text is under the hood. Here's what we have access to:

> [[questions]]
> type = "Tracing"
> prompt.program = """
> something sensible
> """
> answer.doesCompile = false
> answer.lineNumber = 4
> context = """
> This is a compiler error because line 4 tries to mutate `x` when `x` is not marked as `mut`.
> """
> id = "bba6a299-b20f-4685-934a-792a591df3c0"

and below is a screenshot of what it generates - _Note that we have zero questions we want to ask about compilers, and that text is prepopulated from somewhere._  
<img width="774" alt="Screenshot 2024-10-10 at 11 51 13 AM" src="https://github.com/user-attachments/assets/eb4cb3f9-91a1-4bfe-8fbc-a674bf1f91c3">

- [ ] it is not currently possible to put a second question on the page. would it be easy to make that possible?

---
_If it is not feasible, develop a better system for ourselves to draft assessments that will get published on Desmos so that_ 
- we are saving editable files accessible to all authors
- we have version control

**Comment by schanzer** [comment]
We've determined that it's feasible. Closing
