### ISSUE TITLE
\mbox text needs to be italicized

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2159]
Noticing that when I use `\mbox`, the text inside `@math{}` is not being italicized. This happens for both fractions and non-fractions (see p(spider | swallowed) for a non-fraction example where italics are missing).

The example below is on `ai-lesson` branch, in the lesson `ai-statistical-language-models`, on the worksheet `stat-lang-model-intro.adoc`

![image](https://github.com/user-attachments/assets/d61f7ba2-af77-44fa-a3ba-8cc1a742ddeb)

**Comment by schanzer** [comment]
Based on this [typographical reference](https://www.shearsoneditorial.com/2012/07/typographical-conventions-for-mathematics/), multi-letter identifiers should NOT be italicized.

However, going down this rabbit hole was helpful!

- LaTeX supports an alternative to `mbox` called `text`, which is way more readable for authors
- It _also_ supports `textit` for italicized, or `textbf` for boldface
