### ISSUE TITLE
soekia change request

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2161]
Hey @ds26gte !

In Soekia, for all the n-grams, it says "1er", "2er", "3er", etc - which doesn't really work in English.

Can you submit a request to change the English version so that it makes more sense? Maybe "1st", "2nd", "3rd"? This request comes from Shriram. 

Oh! Another one: Shriram and I both dislike the how Soekia uses the phrase "Choose yourself" (which makes us think of not making the choice on one's on, but choosing one's self). Shriram says, "Dorai loves messing around with words - he'll love reading the German and deciding on a better translation... perfect nerd sniping for him."

![image](https://github.com/user-attachments/assets/2c549763-3c2a-45f1-b751-f520c1ebff6a)

**Comment by ds26gte** [comment]
Our local fork has both changes now.

**Comment by flannery-denny** [comment]
@retabak close if you're satisfied

**Comment by ds26gte** [comment]
@retabak, you can check on this fix on bootstrapworld.org/SoekiaGPT (our Hostinger-based version of our Soekia fork).
