### ISSUE TITLE
review AI landing page content

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2162]
Shriram has signed off on [this draft](https://docs.google.com/document/d/1Xl5kqAbdor6P80WfdWotaJUDIHZslX1YDZO5BLbb5C0/edit?usp=sharing) of the course landing page text for BS:AI.

If y'all want to take a peek and offer any improvements or suggestions, please do. Shriram would like me to send it to Jojo by the end of the day (let's say 8pm Eastern?). If you'd like to weigh in, this is time sensitive. If you don't have time, I am comfortable with it as is and happy to let it be.

PS - I'm marking this urgent, but please know that I do not perceive it to be super super important.

**Comment by schanzer** [comment]
@retabak this all looks great! No notes.

**Comment by flannery-denny** [comment]
@retabak I left you some comments and suggestions in the document

**Comment by retabak** [comment]
Thanks, both of you.
 
@schanzer - this doesn't exist on the repo. I shall make it so, but have a question! AI falls under the umbrella of DS, therefore all AI lessons live in the DS folder.  Should I give BS:AI its own unique folder in `pathways`, with its own `lesson-order.txt` ?

**Comment by flannery-denny** [comment]
@retabak I already made an AI pathway on your branch. Please update that for now.

**Comment by retabak** [comment]
okay! Will close this, then.
