### ISSUE TITLE
Filenames0 (with 0 appended)

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2163]
One thing I'm noticing is that if I've already made a lesson plan and then I add a new page and link to it using `@handout` and make without making clean I get the filename link with a zero at the end in the body of the lesson plan. `make clean` then `make` resolves the issue.

(I know there's some other issue for this, but the title doesn't help me identify which issue it's for.)

**Comment by ds26gte** [comment]
<img width="812" alt="Screenshot 2024-08-29 at 11 32 40 AM" src="https://github.com/user-attachments/assets/089d5a61-0882-49ee-9b9d-e036b6326cd4">

I copied an existing handout page, renamed it, and had index.adoc refer to it. Don't see the attached 0.

**Comment by schanzer** [comment]
Try as I might, I can no longer reproduce this with @ds26gte 's fix. I'm going to optimistically close this.
