### ISSUE TITLE
add @teacher{} notes re: FAs to lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2166]
( pending approval of histograms lesson from @schanzer )

- [x] histograms
- [x] box plots
- [x] threats
- [x] regression

**Comment by retabak** [comment]
@schanzer and @flannery-denny -

I'm done integrating the formative assessments into the lesson plans. @flannery-denny - can you check out the branch and review the updates I've made? Would love a second pair of eyes before we merge this.

**Comment by flannery-denny** [comment]
@retabak could you please open a pull request so that I can see the differential?

**Comment by retabak** [comment]
Done. Closing this issue, as I think we can have any further conversation about this issue via comments on the PR.
