### ISSUE TITLE
Dedicated Domain and Range lesson

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#217]
Firmly in the math realm, hit set mappings harder (one to one, onto, etc).
Domain and Range exercises focused on math. ("if we divide x by f(x), and f(x) = x^2 + 1", will there ever be a division by zero?")

**Comment by schanzer** [comment]
This one has NOT been requested by OK, and was more of a conversation between @BootstrapJen and I. Moving this out of the milestone, and potentially closing pending discussion with @flannery-denny about whether this is truly needed

**Comment by flannery-denny** [comment]
![Uploading Screen Shot 2020-12-01 at 1.13.02 PM.png…]()

**Comment by flannery-denny** [comment]
![Screen Shot 2020-12-01 at 1 13 02 PM](https://user-images.githubusercontent.com/66691020/100786658-13055080-33d8-11eb-8d27-4bc802c3c3f7.png)

**Comment by flannery-denny** [comment]
@schanzer Looking at the current domain & range lesson and the linearity lessons, I think the current d&r lesson should be renamed contracts (the world already used for all of the sub-headings)

The d&r lesson we're building should incorporate a little bit of the current d&r lesson - the part about functions being like machines - and connect to the kinds of thinking above (domains that are discrete v continuous, infinite v bound). This is another opportunity to hit on what makes a function a function and discuss why computers can only interface with functions / need for piecewise functions.

**Comment by schanzer** [comment]
FRAGMENT that was split off for Fall2021:

[.lesson-point]
For each input to a function, there is exactly one output.

@span{.right}{ @image{images/VerticalLineTest.png, "Source: Wikipedia", 250} }
Functions are a lot like machines: values go in, something happens, and new values come out. Let's start with an example of a function we all know: adding two numbers! Addition is like a machine that takes in pairs of numbers and produces a sum.

Whenever we use any machine, we always think about what goes in and what comes out. A coffee maker takes in coffee beans and water, and produces coffee. A toaster takes in bread and produces toast. We don't have to know exactly how coffee makers or toasters work in order to _use_ them. All we need to know is what type of thing goes in and what type of thing should come out!

In our coffee-maker example, we expect to get the exact same coffee out if we use the exact same beans and water each time. If you put bread in a toaster and got a bagel out, you'd be pretty surprised! __Functions work the same way:__  no matter how many times you plug in the same number, you will _always_ get the same result. And if you don't? *It's not a function!*

Consider the graphs on the right: for every input on the x-axis, a function will produce a _single_ output. If we draw a vertical line and it hits the graph more than once, it means there is __more than one output__ for the same input. Like any good machine, function machines must be *reliable*.

=== Investigate

We use something called a @vocab{Contract} to keep track of what goes in and out of these machines called functions. Contracts are like a "cheat sheet" for using functions. Once you know how to read one, you can quickly figure out how to use a function just by looking at its contract!

**Comment by schanzer** [comment]
@flannery-denny I think the new function lessons capture a lot of the spirit of this issue now, and do so in a much more coherent way. Any objection to me closing this?
