### ISSUE TITLE
on the web - margins are too wide in collecting-data lesson

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2170]
@schanzer - when this bug resolved itself the last time I noticed it, you were annoyed.... so I found it again for you!

ETA - this seems to be the norm in many (all?) fall2024 lessons, but fall2023 looks correct.

![image](https://github.com/user-attachments/assets/0ba7adea-ba69-4f31-8276-1ac8b70cb835)

**Comment by schanzer** [comment]
@retabak how odd! I can't for the life of me figure out why this is happening. I reduced the left-padding to 0, which mitigates the issue somewhat. What do you think?
