### ISSUE TITLE
Research whether there is a way for teachers to share their Desmos data?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2171]
- [ ] Is there a way?
![image](https://github.com/user-attachments/assets/93ba8c4c-f900-42f2-a761-d0152b87983b)
- [ ] Draft prose asking teachers to share their data with us and add it to the four assessments / lesson plans.

**Comment by retabak** [comment]
Agree with @flannery-denny that the message will be a no go.

I did some research and cannot find any easy way for teachers to share data.
