### ISSUE TITLE
Make and Use Learning Objective dictionary

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2172]
For Emmanuel:
- [x] Compile all learning objectives into a single file
- [x] Structure the file to make a JS dictionary where the same prose shows up as the key and in the value
- [x] Make `@learning-objective` directive, which for now just consumes and produces identical strings. (In the future, the keys will become more key-like and the values will be refined.)
- [x] Replace all LOs in lessons with directives that insert the prose

**Comment by flannery-denny** [comment]
Looking at that dictionary makes this work feel even more important.

**Comment by schanzer** [comment]
right???
