### ISSUE TITLE
populate assessments folders in lessons for first 4 assessments

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2174]
Histograms
- [x] upload image files (fd already uploaded some)
- [x] add links to adoc

Linear regression
- [x] upload image files
- [x] add links to adoc

box-plots
- [x] upload image files
- [x] add links to adoc

threats to validity
- [x] upload image files (flannery already uploaded one)
- [x] add links to adoc

**Comment by retabak** [comment]
@flannery-denny - Do you have images for the recently reworked box plots? Or Pyret files? If so, can you add them (or slack them to me and I will add)?

This is ready to close once box plots images are taken care of.

**Comment by retabak** [comment]
Noting that FD already added the images! Closing.
