### ISSUE TITLE
Linear regression lesson should not depend on correlations

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2175]
In reading through the AI materials, I found myself in a familiar place: wanting kids to know linear regression but not caring if they know how to interpret correlations!

I am now more firmly convinced that the LR lesson could include a single paragraph that explains `r`, which would be a review for kids who completed correlations but introduce _just enough_ information that a student could complete the LR lesson without ever doing correlations.

This would benefit both AI and Alg2, and requires minimal effort.

**Comment by retabak** [comment]
The linear regressions lesson incorporates lots of review in the first section. Students make scatterplots, and think about `r` on both lr-plot-intro and drawing-predictors!

**Comment by schanzer** [comment]
@retabak thanks for flagging that! In that case, I actually think the ONLY change needed is to adjust the prereq list. 

I've pushed this change in 7ff6fdb56.
