### ISSUE TITLE
rework Formative Assessment objectives

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2176]
- [x] add objectives to formative assessments in desmos
- [x] add objectives to checkpoints in desmos
- [x] #2174

draft - please comment @flannery-denny and @schanzer!

https://docs.google.com/document/d/1AH-tZ8jaFHfEXPnUfsKX01NN_78em1e3dLSBo2MGNRM/edit?usp=sharing

**Comment by schanzer** [comment]
@retabak Done. Flannery got there first, and I agree with almost all of her suggestions.

**Comment by retabak** [comment]
Y'all are too fast! I had not yet tackled the last lessons (but see now that I didn't communicate that). I will add your suggestions, and maybe ask for a second review in a little bit.

**Comment by retabak** [comment]
OK - feedback is incorporated and I gave linear regression and threats to validity a first pass. (Sorry I preemptively requested feedback, earlier! Was pulled away from my computer and unable to finish.) Take a look when you can, @flannery-denny and @schanzer .
