### ISSUE TITLE
Dedicated Inequalities lesson

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#218]
- [x] make slide decks 
- [x] weschemify
- [x] add and/or to compound inequality lesson
- [x] make a workbook page where students write the code to define the compound inequality pictured.
- [x] Firmly in the math realm, factoring out Sam into separate lessons which do not introduce the topic. 
- [x] Talk about union and intersection, and show the graph.
- [x] Booleans-Intro worksheet needs to be beefed up (see @BootstrapJen 's comments)

**Comment by flannery-denny** [comment]
- [ ] I wonder if it might be worth making a more explicit connection in the workbook between the functions they've written to keep Sam safe and the way that inequalities get graphed on a number line?

**Comment by flannery-denny** [comment]
Inequalities lesson that has nothing to do with sam the butterfly. Number lines with overlapping ranges.
Can we do solving inequalities stuff?

**Comment by flannery-denny** [comment]
@schanzer where do I find the comments you're referencing. I've looked at the OK issue and linked files... **" Booleans-Intro worksheet needs to be beefed up (see @BootstrapJen 's comments)"**

**Comment by flannery-denny** [comment]
@schanzer Thinking a bunch about how we introduce Booleans. The notes say that Booleans read like questions... but the inequality symbols are just symbols.  I know that (< 2 3) means is 2 less than 3, but it's pretty abstract as an introduction.

In Data Science there are more concrete examples, like is-cat and is-dog... 

wondering if we can build in a more concrete example in algebra... here are two possibilities...

- is-perfect-square?

- is-congruent? for something like...

- > (rectangle 200 400 "solid" "red")
- > (scale 2(rectangle 100 200 "solid" "red"))

**Comment by flannery-denny** [comment]
@schanzer fyi done with slide decks for these lessons. we should definitely confirm that links work in January.

**Comment by flannery-denny** [comment]
@schanzer Trying to add that and/or section into the lesson and it appears that pyret can't handle function names that begin with numbers.  you had proposed 5to15. I'm having to use fiveto15. Do you think that's something worth trying to change?

**Comment by schanzer** [comment]
Yes, it's worth changing to make sure it's the same function name in both languages￼

**Comment by flannery-denny** [comment]
I meant, do you think it's worth letting the pyret team know that function names starting with numbers would be useful?

**Comment by schanzer** [comment]
They already know. They made a design decision that prevents them from allowing them￼, so there's nothing we can do here.￼

**Comment by flannery-denny** [comment]
got it

**Comment by flannery-denny** [comment]
@schanzer This is issue is ready for closing, pending your read of the materials.

- [ ] If you send me the Desmos password, I'll add an activity - I have images saved already.
- [ ] I wish I knew how to center the text in the cells in the right column of the compound-inequality-functions page. Do you?

**Comment by schanzer** [comment]
@flannery-denny done and closing! Nice work!
