### ISSUE TITLE
find more compelling examples of misleading use of displays

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2182]

**Comment by flannery-denny** [comment]
@retabak I think you will find that Q4 is an improvement. And I'd guess that you might want to edit some of the wording.
[threats to validity](https://teacher.desmos.com/activitybuilder/custom/66c391955b3af1281567a903. close if you're satisfied.

**Comment by flannery-denny** [comment]
@retabak @schanzer Please check out [card six of this desmos file](https://teacher.desmos.com/activitybuilder/custom/66c391955b3af1281567a903) and consider which graphs you think are misleading. Then check out the answer key.If you disagree with any of my choices, please pair down the cards and adjust the word six in the subtitle directions on the computation layer. If you find yourself wishing you could make something else from the data, [here is the link to the file](https://docs.google.com/spreadsheets/d/17zzKtHpomQJ7CI4VcFEnZCersl-iqFRdiY1of-LJxN8/edit?gid=1206766104#gid=1206766104).

**Comment by flannery-denny** [comment]
@schanzer @retabak Could one of you please review the cards on slide 6 per the above comment and close if the questions works for you.

**Comment by retabak** [comment]
I'm not totally comfortable with slide 6. 

Wouldn't we need a claim to accompany each of these displays in order for them to be misleading?

Also, we need to discuss "constrained x axis" and "constrained y axis" if this is something we are going to discuss. Full disclosure, I had no clue how to match these cards until I looked at the answer key.

**Comment by flannery-denny** [comment]
@retabak Adding it to the curriculum team meeting agenda.
The claim is in the title.
I meant for the wording re: the axes to be the same as what you had used previously. (It means the same thing in my head.)

**Comment by retabak** [comment]
Let's discuss in person, but:

- I see what you're going for but I wouldn't call that a claim.
- In the lesson, we talk about "changing the scale of a chart", not constraining. We also have zero examples of it in the lesson, not even on [this page](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/threats-to-validity/solution-pages/fake-news.html). (I'm making an issue to address this, #2185)
