### ISSUE TITLE
Pitch AI module as Hour of Code

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2188]
- [ ] Complete the form they post
-- Here are the [notes we have about completing the past submission form](https://docs.google.com/document/d/1de8cPF_4Xc0gioTnWrwfOx-pGOBih1ycqV5y938bS6o/edit)
-- It's fine to pitch it as in development (we can allocate time in November to push something over the finish line if it gets accepted)
-- If it requires a link, please discuss what we could link to with ES
-- Unless you think we could easily repurpose the [Schanzer Slide / Parlay infrastructure](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/hoc-winter-parley/index.html) to actually make a one-hour lesson, it's fine to pitch a multi-lesson option
- [ ] Poke ES to follow up with his contacts

**Comment by flannery-denny** [comment]
@retabak please check in with ES re what he's learned from our hour of code contacts before working on this.

**Comment by retabak** [comment]
Just noting here that I will put this issue on hold until we learn if it's worth filling out the form.

**Comment by schanzer** [comment]
@flannery-denny based on our discussion in RI, this feels like it can be closed?
