### ISSUE TITLE
on the web - winter hour of code doesn't load

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2189]
the editor never loads!

https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/hoc-winter-parley/index.html

@schanzer - not assigning you because I'm not sure who can fix this, but tagging you because my best guess is that it's you.

**Comment by retabak** [comment]
This seems to have reverted. I just see snowflakes, no editor.

**Comment by flannery-denny** [comment]
Same for me. Also, while we're at it. Should we refer to the editor as Anchor instead of
Parley?

**Comment by schanzer** [comment]
@flannery-denny not sure what you mean. Where are we calling it Parley, aside from the URL?

**Comment by flannery-denny** [comment]
@schanzer
<img width="374" alt="Screenshot 2024-09-19 at 10 44 14 AM" src="https://github.com/user-attachments/assets/99f0792a-4ebc-4e34-a273-cf419532a862">

**Comment by schanzer** [comment]
Ah yes! I would just call it "an embedded version of our Pyret Editor"

**Comment by schanzer** [comment]
@ds26gte this looks like a permissions issue -- is there a way to tell rsync to make permissions set to 644 for everything?
