### ISSUE TITLE
Add "live surveys" to pyret

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2191]
ES estimates this will take one hour - describes it as DS meets reactive - with the reactive stuff hidden. FD and RT are thrilled!

The feature would allow teachers to create a google form, run a pyret starter file and watch the display automatically generate in pyret

One application could be adding live surveys to our DoNow sections to lessons where displays are being introduced.

**Comment by schanzer** [comment]
Bad news. 

When we made the jump to simpler functions for visualizations, it was a HUGE boost for simplicity and a relatively minor loss of power. At least...that was true for our entire curriculum's use-cases.

What I forgot is that the live-survey demo I made years ago relied heavily on some of the power that we've now removed. So that means the only way to do this today would be to show teachers and students a TON of pretty confusing code. 

There aren't any good options here that I can envision, so I'm afraid there's just no way to implement this without practically rewriting our curriculum to use a much harder set of contracts. :(

**Comment by flannery-denny** [comment]
@schanzer The idea was students would see a Google survey and the results displayed as the first data visualization they encountered of its kind. Students never need to see the starter file. so it can use a different library than the one students have access to. I would love to see your demo before we rule out that this is too heavy of a lift for teachers. This is not only a thing @retabak and I see as a huge game for teachers and a thing that shriram's been dreaming about, it is also a thing teachers have explicitly asked us for in the interviews we've conducted this month.

**Comment by schanzer** [comment]
@flannery-denny ok, this is definitely the best I can do! I spent quite a few hours to get here, and it required multiple undocumented, secret Pyret features that Ben helped out with:

- [Here's the survey](https://docs.google.com/forms/d/e/1FAIpQLSeInd7zrtbyS3P6PVS5rjwDMokHqZFTLZtL12zbsosMXROdRg/viewform)
- [Here's the spreadsheet](https://docs.google.com/spreadsheets/d/16i6lwzyxxdrdFkY8Szyt3uJY3iEOIMUshs2Ea7fgW7Q/)
- [Here's this program](https://code.pyret.org/editor#share=1AcMYL98deqJVjFjpwD1sTOABVgCqEN7x&v=dc8be4e)

Note that this ONLY works if the spreadsheet has at least one entry already -- Pyret doesn't support loading empty spreadsheets, apparently (?!?!). 
It looks like Google has slightly tweaked the way form submission works, where the spreadsheet becomes unavailable for just a microsecond. In rare cases, this can crash the Pyret program when it tries to update and can't find the file.

**Comment by flannery-denny** [comment]
@schanzer I think it's exciting! Directions to the teacher would state 

> This starter file is beyond the scope of the programming involved in Bootstrap:Data Science, but "Fear not! 
> All you have to do is click "Run". As long as you leave the pie-chart open, you'll be able to watch your students' google form entries populate it live!

**Comment by schanzer** [comment]
@flannery-denny if you're happy, I'm happy. ;)
