### ISSUE TITLE
Fast functions arrows in contracts show as squares

### ISSUE THREAD

**Issue by jpolitz** [bootstrapworld/curriculum#22]
![image](https://user-images.githubusercontent.com/119891/56923736-27f16380-6a80-11e9-91c2-6447df9e942a.png)

**Comment by jpolitz** [comment]
This is in the current version of the workbook linked from https://bootstrapworld.github.io/curriculum/distribution/bs-game-pathway/langs/en-us/workbook/workbook.pdf

**Comment by edcamposjr22** [comment]
I fixed these arrows and it looks to be all good now.
