### ISSUE TITLE
Standardize use of chart / display / graph / visualization for "Dot plots, Scatter plots, Histogram, Lr-plot, box-plot"

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2208]
- Be specific when possible: Refer to histogram, box plot, scatter plot, lr plot, dot plot, etc.
- Use data visualizations or visualization when we're looking for a catchall term
- Remove plot or chart or graph as catchalls
- Use graph when you're graphing a function
- display the data and plot the data are fine when they're used as verbs
- [x] Replace noun-use of `plot` with `(data) visualization`
- [x] Replace `data display` with `data visualization`
- [x] Rename files? (data-displays.adoc)
- [x] Rename desmos slides

**Comment by flannery-denny** [comment]
Some Food For Thought:

"When somebody asks me about my profession and I tell them that I’m a data visualization designer, most people have no clue what I’m actually doing. Data visualization helps tell the story of the data and puts information into a context, making it easier to understand for your audience."

9 Types of Data Visualization:
1. [Chart](https://www.datylon.com/blog/9-types-of-data-visualization#chart)
2. [Animated chart](https://www.datylon.com/blog/9-types-of-data-visualization#animated-chart)
3. [Interactive chart](https://www.datylon.com/blog/9-types-of-data-visualization#interactive-chart)
4. [Dashboard](https://www.datylon.com/blog/9-types-of-data-visualization#dashboard)
5. [Report](https://www.datylon.com/blog/9-types-of-data-visualization#report)
6. [Presentation](https://www.datylon.com/blog/9-types-of-data-visualization#presentation)
7. [Infographic](https://www.datylon.com/blog/9-types-of-data-visualization#infographic)
8. [Data story website](https://www.datylon.com/blog/9-types-of-data-visualization#data-story-website)
9. [Data art](https://www.datylon.com/blog/9-types-of-data-visualization#data-art) 

<img width="1145" alt="Screenshot 2024-10-08 at 10 08 57 AM" src="https://github.com/user-attachments/assets/91bb3ddf-38a0-4408-9580-21e1b39cba20">

<img width="1140" alt="Screenshot 2024-10-08 at 10 09 19 AM" src="https://github.com/user-attachments/assets/a382775f-7696-45d7-a871-b1771476dc0e">

<img width="1147" alt="Screenshot 2024-10-08 at 10 09 51 AM" src="https://github.com/user-attachments/assets/11e0d85d-6b34-4d06-be14-ff7be6c28b7a">

"While many people use ‘graph’ and ‘chart’ interchangeably, they are different visuals. Charts are tables, diagrams or pictures that organize large amounts of data clearly and concisely. People use charts to interpret current data and make predictions. Graphs, however, focus on raw data and show trends over time."

**Comment by schanzer** [comment]
@flannery-denny note that the following regexp will find all instances of " plot" (note the 1 space!) that do NOT follow "scatter":

`\w*(?<!scatter)\s{1}plot`

**Comment by schanzer** [comment]
Wording changes are now complete! 

We have a few files called `data-displays`, `contracts-tables-displays`, etc. I've already changed the titles of these files, but not the filenames. Should we change the names, too? There's a very small reason _not_ to: teachers who use our links might be tempted to just change `fall2024` to `fall2025` when they want to update. Changing the filenames will break those links. Do we care?

I _think_ we also have some Demos activities that might use this language? Making a note to check those as well.

**Comment by schanzer** [comment]
@flannery-denny including changing the lesson name from `contracts-tables-displays` to `contracts-tables-visualizations`?

**Comment by schanzer** [comment]
I went ahead and audited the ds-desmos starter files, and it looks like we never use "data displays" there. Phew!
