### ISSUE TITLE
Automate display of learning objectives

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2209]
One of our goals for LOs is that authors think about them with respect to a lesson _section_, rather than to an entire lesson. That means declaring them elsewhere in the lesson adoc, but having the build script automatically compile them in order and list them at the top of the summary table (where they are now).

This will likely require an `@objectives` (plural!) directive at the top of the table, which expands to a table cell containing a bulleted list of all the LO texts.

Needless to say, the display behavior of `@objective` (singular!) should be a no-op - it's only used to collect the LOs for the list at the top.

**Comment by flannery-denny** [comment]
When I update one learning objective and shift it to the appropriate lesson section, but don't tackle all learning objectives in the table I get the following warning.

> WARNING: Lesson plan distribution/en-us/lessons/codap-filtering-codap/index.adoc: Undefined @objective Write Purpose Statements and expressions to be used in Transformers.
> 
> WARNING: Lesson plan distribution/en-us/lessons/codap-filtering-codap/index.adoc: Undefined @objective Identify examples of Booleans and recognize what makes them unique.

If this is not easy to resolve, we might need to work on a separate branch. While I see the advantages of that, I can also come up with many disadvantages of that.

**Comment by flannery-denny** [comment]
@retabak fyi - Turns out these warnings were caused by me adding periods to the unedited objectives while I was in the file, which was such a minor change that I'd forgotten I'd made it by the time the warnings appeared and the periods were messing with build's ability to find the strings.

**Comment by flannery-denny** [comment]
@ds26gte When the objectives are gathered in the materials landing table, they should be gathered in the order that they appear in the lesson plan (which is where authors are thinking through the order by attaching them to lesson subsections). It seems that they are currently being generated in the order that they appear in the json file.

**Comment by schanzer** [comment]
Confirming that these are now in the right order! Thank you, @ds26gte !!
