### ISSUE TITLE
Multi Bar & Stacked Bar Charts - Notice and Wonder Workbook page error on 2nd Subtitle of Graphs

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2211]
On the [Multi Bar & Stacked Bar Charts - Notice and Wonder Data Science workbook page](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/bar-and-pie-charts/pages/stacked-and-multi-notice.html), the 2nd section of graphs is titled: "Distribution of sexes across Cats, Dogs and Rabbits".  However, on the axes of the graphs the labels are "rabbit", "tarantula", "lizard".

**Comment by schanzer** [comment]
@joystraub can you post a link to the page in question?

**Comment by joystraub** [comment]
done
