### ISSUE TITLE
Algebra - Circles of Evaluation- Notice & Wonder workbook page Question

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2212]
Question came in from Rachel B. about one of the problems at the top of the [Circles of Evaluation - Notice and Wonder workbook page ](https://bootstrapworld.org/materials/fall2024/en-us/lessons/order-of-operations/pages/coe-notice.html)(currently p. 11).  The 4th circle over is different from all the others.  It resolves to 5* 2 instead of 5* 6. It is her belief that all of these should resolve to the same, which is the point of the lesson. Is that correct?  If so, then that 2 should be changed to a 6.  If not, then why is only one of them not the same?

**Comment by schanzer** [comment]
@joystraub can you post a link to the page in question?

**Comment by joystraub** [comment]
done

**Comment by schanzer** [comment]
Thanks, @joystraub ! @retabak or @flannery-denny , can one of you weigh in on this?

And either way, the column headings of that table should be centered, not left-aligned.

**Comment by flannery-denny** [comment]
@joystraub I understand why she raised the question, but I'm not sure that the page would actually be better if we changed it. What's wrong with noticing that all of the circles except for the 4th one resolve to 5*6?  I see some advantage to forcing students not to make the assumption that they've found a pattern that will hold without actually thinking each of the problems through. I don't have a strong opinion here. If someone else does, lmk. Either way, it's not a mistake. And the page won't change this year.

@schanzer Interesting that you think Notice and Wonder tables should have centered headings. I'll make an issue to scan the workbook and confirm that principle is followed consistently.

**Comment by schanzer** [comment]
@flannery-denny I had a feeling this was intentional, and I'm totally cool with it. I could see an argument for making a _different_ circle resolve to a number other than 30, but I think we're ok where we are.

**Comment by retabak** [comment]
Fine with me as is, too!
