### ISSUE TITLE
Investigate how to improve file usage for cloud-based schools

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2217]
When we got rid of save to drive, we didn't consider whether there might be a better way for cloud users. It's time to look into that. At least 3 of FD's interviewees have expressed it would be the number one thing they would change about our current materials.
Currently people can either view our PDFs as webpages or download them to a computer. 

1. Could we offer an option to "Save the PDF to Google Drive"?
2. Google Schools are used to having students annotate PDFs with application like [Kami](https://www.kamiapp.com/). For some reason our PDFs are incompatible. Is this something we could change?

**Comment by flannery-denny** [comment]
@schanzer Here's what I heard back from Stefanie D.

> Here is a [quick video](https://app.screencastify.com/v3/watch/fyWjzATA7b3QEEcla0Q9) of what my options are and how I see/interact with the bootstrap worksheets.
> 
> Here is an [add on video](https://app.screencastify.com/v3/watch/2RUTAWTO7QbN3GKRImrP)... I kept exploring.
> 
> It seems that Kami is not an option for me when I click on the links for the PDFs in Bootstrap. I would love to see how Emmanuel is interacting with Kami.
> 
> What I am trying to avoid is having to download a PDF, then uploading it to Kami, then uploading it to Google... which is what I have to do now. It is time consuming and clunky.

Feel free to close this issue if you think #2230 will address all of her concerns.

**Comment by schanzer** [comment]
@flannery-denny ok, so in other words "Bootstrap PDFs work fine in Kami. Separately, I'd like an easy way to add PDFs to Google Drive".

Yeah, #2230 is what she's asking for.

**Comment by flannery-denny** [comment]
@schanzer I know that we decided yesterday that we won't really care how she was trying to save the pdf, but to answer the question, did you notice that she tried to save the pdf by right clicking on the document?

**Comment by schanzer** [comment]
@flannery-denny I don't see her trying to save the pdf anywhere. I watched both videos, and never saw a PDF once!

**Comment by flannery-denny** [comment]
The way she expects it to work is:
- open up the workbook page
- right click on it
- select print
- be able to save to cloud from there

Just wanted to answer the question about what she was expecting. Doesn't
mean we have to solve it that way.

**Comment by schanzer** [comment]
@flannery-denny the workbook page is not a pdf document. Just letting you know
