### ISSUE TITLE
On the web: function-notation still talks about the function card game

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2221]
In the [last section of the lesson](https://bootstrapworld.org/materials/fall2024/en-us/lessons/function-notation/index.shtml?pathway=algebra-pyret#_diagramming_function_composition_duration15_minutes), we talk about the function card game kids "just" saw. 

Unfortunately, that game isn't part of the lesson at all!

**Comment by flannery-denny** [comment]
@schanzer It looks like that last section was literally just cut from from the function composition lesson and pasted onto the end of the function notation lesson. As far as I can tell, function notation only exists (and would only make sense) in a pathway where function composition has already been introduced. If you can live with that assumption, I will resolve the issue by replacing

> Three of the function cards we just used were for the functions f, g and h:

with 

> Suppose we had the following three function cards for the functions f, g, and h:

Does that work for you?

**Comment by schanzer** [comment]
@flannery-denny  That replacement works perfectly

**Comment by flannery-denny** [comment]
@schanzer done. please close once you've pushed it to the web.
