### ISSUE TITLE
S is landing on top of right parentheses in (S)

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2225]
I'm on the `alg2-split` branch in the `fitting-models` lesson and this is what I'm seeing - checkout the last character in the screenshot.
<img width="907" alt="Screenshot 2024-10-08 at 10 02 34 AM" src="https://github.com/user-attachments/assets/367e4392-5c72-4602-8adf-c78745301833">

**Comment by schanzer** [comment]
@flannery-denny I've pushed a conservative fix:

![image](https://github.com/user-attachments/assets/40b0de1f-56f0-49d9-b989-13d352f2fb8c)

If this looks good to you, please close the issue.
