### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#223]
- [x] Introduce comments here
- [x] Be explicit about how graph paper plays into things
- [x] Real scaffolding of put-image
- [x] Use "japan" as a worked example
- [x] Use Flannery's broken PR activity [wescheme version](https://www.wescheme.org/view?publicId=AoxnqQyxlY)
- [x] Turn 'em loose!
- [x] Explain the optional ratio/proportion activity in a strategy box, but maybe split this off into a separate lesson later?

**Flannery's Notes:**
Flags of the world resource: 
 -  Perhaps worth a sentence about what the ratios mean?
 -  Not sure Georgia belongs on the list?  And if they're not using bitmap-url, not sure they can build Taiwan. 
 -  How about adding: 
  - To First  list: Aland Islands, Cape Verde, Central African Republic, Pan-African Flag, Pride Flag, New Mexico, Alaska
  -  To Second list: South Africa
  - I think flags are a great time to teach the bitmap-url function.  If you're open to a list that would use that, I would suggest adding:  India, Lebanon, Uruguay, Rwanda

- [x] Make tables for decomposing flags worksheet: shape, color, width, height, x-coord, y-coord

- [x] I think that fixing broken code is an incredibly powerful learning activity. I have made lots of broken codes for students and would be happy to share them in the resource section of this lesson. 

I've also written some code that works but is clunky and I have students slim down to make it more elegant.

**Comment by schanzer** [comment]
Suggestion from the Oklahoma research team: have Jessica (OK teacher) review the revised lesson.

**Comment by flannery-denny** [comment]
Does that mean anytime before January or are they interested in
implementing it sooner?

**Comment by schanzer** [comment]
I think this is the only issue remaining:

- [ ] "Estimating Coordinates" is listed as optional, but the lesson refers to it explicitly. Either it shouldn't be optional, or it the lesson plan instructions should include the "optional" tag.

**Comment by flannery-denny** [comment]
How about this?- Distribute
@exercise-link{japan-estimating-coordinates.adoc} or project the flag
images from the peardeck.
