### ISSUE TITLE
Bring back "Save to Drive" button....with a twist

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2230]
Before @ds26gte has a heart attack....**WE ARE NOT BRINGING BACK GDRIVE VERSIONS OF HTML!!**

Instead, we should just point the button to the _pdf_ version of our pages. This would allow users to open those PDFs in Kami. (See #2217)

**Comment by ds26gte** [comment]
Could you give some indication of where the button should go, indeed an easy-to-follow spec (what the URL in the link should be, etc). It's been a while since I saw the Save to Drive button, and reproducing it (just for comparison) is painful (because it was even before the makefile makeover I think).

**Comment by schanzer** [comment]
@ds26gte all of the relevant changes are a subset of those in https://github.com/bootstrapworld/curriculum/issues/1614.

We want literally reverted, EXCEPT:

- no need to generate gdrive-import.html files (that's most of the build script complexity!)
- the gdrive-import button that we insert (see [this line](https://github.com/bootstrapworld/curriculum/commit/b4843cb7368860a1ad5d1bdcf5d9fa54b038c02e#diff-7d1256b1266a5dc6baa14aa1200e055fb6539a735e0fe9fe5ab1af7fecc9c790L201)) should insert a link to `filename.pdf`, instead of `filename-gdrive-import.html`.

**Comment by flannery-denny** [comment]
@schanzer Here are some notices and wonders - not sure which are in whose wheelhouse.

- The button currently says "Save". 
-- Guessing it should be more explicitly say "Save PDF" or "Save PDF to your Google Drive"
- When I click on it, the following text appears:

> Bootstrap, Brown University (null) would like to save an item to your Google Drive.
Note that Google cannot verify the identity provided by this website.
**The Math Inside video games** will appear in:
My Drive(change)

Noting the following: 
- (null)
- Note that Google cannot verify the identity provided by this website.
- In my distribution **The Math Inside video games** is titled `notes-intro.pdf`

So far the button is there but doesn't do anything.

**Comment by schanzer** [comment]
@flannery-denny 

- We are not in control of the button text, so it's going to have to stay "save"
- All of the other issues are related to you trying to the button locally, when it only works on a server. [Try this page instead](https://bootstrapworld.org/materials/fall2024/en-us/lessons/__sample-lesson/pages/exerA3.html).

**Comment by flannery-denny** [comment]
very cool! thanks :)

**Comment by flannery-denny** [comment]
@schanzer What's standing between this working on the link you shared and it being live on the web?

**Comment by schanzer** [comment]
@flannery-denny being able to build the workbook
