### ISSUE TITLE
Upload poster set to print on demand site

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2234]
Since there is text seeking funders for this on the new website, we need to have the poster set uploaded correctly by the time the new website launches.
- [x] upload
- [x] figure out how much it costs to print a set (so we know - and perhaps can offer it as an incentive to future interviewees)
- [ ] seek funder to offer poster sets to teachers for free

**Comment by schanzer** [comment]
[This service appears to offer what we want](https://support.artstorefronts.com/hc/en-us/articles/6655817359515-Upload-Images-for-Print-On-Demand-Products). A TON of other places are limited to 8.5x11". @flannery-denny , if you're comfortable keeping this on letter-sized paper I believe we can get a much better price for teachers.

**Comment by flannery-denny** [comment]
@schanzer I'm not sure the posters will look very good if printed larger than 8.5 x 11

**Comment by schanzer** [comment]
Update - I've uploaded the files to https://www.printme1.com/, which can hosts them and offers print-on-demand for people who wish to purchase. Should get approval sometime next week.

**Comment by schanzer** [comment]
@flannery-denny our print-on-demand link is [https://www.printme1.com/1100aa4996](https://www.printme1.com/1100aa4996). I think the last checkbox (look for a funder) is more of an ongoing thing, and should not prevent us from closing the Git issue. 

I'll let you decide what you want to do with this link, but suggest we close now.

**Comment by flannery-denny** [comment]
Thanks for researching this @schanzer. I'm sorry to say that looking at the uploaded file revealed that our poster css needs some tlc.

1. I think the css rules have changed since the last time we worked on the layout together.  The current design is leaving a larger amount of white space below the footer than above the image. I would expect the footer to be much closer to the bottom.
[guillermo-camarena.pdf](https://github.com/user-attachments/files/17442555/guillermo-camarena.pdf)

2. The page size on the service you found differs from the page size the posters  are designed to be so the pdf on their server includes even more white space at the bottom.
![Checkout](https://github.com/user-attachments/assets/46f9e07e-4875-4b9d-8857-45efcab9c2a8)

**Comment by schanzer** [comment]
@flannery-denny This whitespace looks identical to [the space we had back in 2022](https://bootstrapworld.org/materials/fall2022/en-us/lessons/computing-needs-all-voices/pages/guillermo-camarena.pdf). I can move the footer lower, certainly, but I'm not seeing the difference you describe.

**Comment by schanzer** [comment]
@flannery-denny finding a funder for this is going to be difficult given the current climate. And even if we do, it's likely that they'll give us a fixed amount and then we'll need to re-open the issue when it runs out! I vote we close this, since the part our team can control is finished.

**Comment by flannery-denny** [comment]
@schanzer I can't remember. Have we added links to the print on demand site to teacher resources pages and/or the computing needs all voices lesson?

**Comment by flannery-denny** [comment]
If so, fine to close!

**Comment by schanzer** [comment]
Done!
