### ISSUE TITLE
Resolve friction between Bootstrap materials and Peardeck

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2235]
In Karen Villegas' school, other peardecks open, but Bootstrap files do not - unless she opens them directly from our website.  Her sub had the same issue from his account there. Joy worked with her to try and get it to work.  "The only thing we could do was to get her to the website and have her enter that way."

**Comment by schanzer** [comment]
What does "open" mean? And how could ANYONE get to our peardecks without going to the website?

**Comment by flannery-denny** [comment]
@joystraub can you clarify?

**Comment by joystraub** [comment]
It means they can directly operate Peardeck from within the Google Slides files by opening the PearDeck extension within Google Slides and starting the session that way.  That is the easiest way to do it. 
![image](https://github.com/user-attachments/assets/73337c16-179d-47cd-88bc-5ff688199bdd)

**Comment by joystraub** [comment]
The extension is not allowed for her for some reason in Bootstrap files only,  It is in other Google slides she uses.  If she goes to the PearDeck website and opens the Google Slides deck directly there, then she can run PearDeck for her class that way.  It is just a little more work for her.

**Comment by schanzer** [comment]
@joystraub Rachel Brainard is hitting the same issue. I've escalated both to PearDeck engineering, and they're looking into it. Whatever this isolated issue is, it doesn't appear to be on our end.
