### ISSUE TITLE
make Aaron Judge starter file

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2244]
- [x] Polish [the dataset](https://docs.google.com/spreadsheets/d/1L4kRfeYtVOE7yam0kmgVEntIg7Yz8saS/edit?usp=sharing&rtpof=true&sd=true)
- [x] Make a README following the protocol
- [x] Make starterfile with variable list annotated

**Comment by schanzer** [comment]
@flannery-denny See https://code.pyret.org/editor#share=1wEShSWdI8Kk_SIlP3ce-ortWkp5hy29y

Still working on the README

**Comment by schanzer** [comment]
README is complete. [New spreadsheet can be found here](https://docs.google.com/spreadsheets/d/1TUbw1Jg-zrzIyoY-uCiliqJ3EwpurgWe0aQn0GSPAKQ/edit?gid=943166541#gid=943166541).
