### ISSUE TITLE
prevent committing invalid JSON files

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#2247]
There is no reason for a syntactically invalid JSON file to be in the repo.  If one is about to be committed, use a Git commit hook to prevent this tragedy and issue an error message.

**Comment by ds26gte** [comment]
My solution does require the presence of the command `jq`.  If you don't have `jq` installed, then the check isn't done and potentially invalid JSON files will get committed.

**Comment by schanzer** [comment]
Thanks, @ds26gte ! OSX has it, and @retabak is installing it on WSL via `apt`. I've also added this tool to the README
