### ISSUE TITLE
Establish scope of Gold Standards project and intermediate deadlines - link google docs

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2248]

**Comment by retabak** [comment]
Various documents:
- [misconceptions research](https://docs.google.com/document/d/1WETxJ01Kzmhu-GTukS6aBzWbCB653v9s6VFvmT8iX9Y/edit?usp=sharing)
- [objectives](https://docs.google.com/document/d/19yyvXASNoezMV1_E7w9LjQvIx4dmf4z7vLGqS6ZF_zI/edit?usp=sharing)
- [histograms assessment items from research](https://docs.google.com/document/d/1PEnwKQua8MdJ1LiFMoEx8o_QkGWQtonvKjjgfKQmJJo/edit?usp=sharing)
- [measures of center lesson outline](https://docs.google.com/document/d/15W-O5EblDGTPK4poaPO4TnFteV19CG1TSkiOkP1t6AU/edit?tab=t.0)
- [measures of center assessment items from research](https://docs.google.com/document/d/1zNtS5ZTqo1o3zocAw37nVFGX8ri_On0Hb3VJtt_65Vg/edit?tab=t.0)
