### ISSUE TITLE
Audit: Are we asking students to create something by the end of all of our lessons?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2251]
- [ ] absolute-value-and-opposites
- [ ] additive-inverse
- [ ] multiplicative-inverse
- [ ] associative-property
- [ ] codap-building-codap
- [ ] codap-composing-codap
- [ ] codap-dot-plots-bar-charts-codap
- [ ] codap-exploring-codap
- [ ] codap-filtering-codap
- [ ] commutative-property
- [ ] ds-intro
- [ ] visualizing-the-shape-of-data
- [ ] distributive-property
- [ ] equivalence
- [ ] evaluating-exponents
- [ ] exponent-expressions-with-negatives
- [ ] translating
- [ ] advanced-displays
- [ ] bar-and-pie-charts
- [ ] checking-your-work
- [ ] combinatorics-combination
- [ ] combinatorics-permutation
- [ ] computing-needs-all-voices
- [ ] contracts
- [ ] contracts-tables-displays
- [ ] coordinates
- [ ] correlations
- [ ] data-cycle
- [ ] debugging
- [ ] defining-table-functions
- [ ] defining-values
- [ ] distance-formula
- [ ] inequalities-collision
- [ ] inequalities1-simple
- [ ] inequalities2-compound
- [ ] inequalities3-sam
- [ ] lookups
- [ ] making-game-images
- [ ] numbers-inside-video-games
- [ ] piecewise-functions-conditionals
- [ ] player-animation
- [ ] function-composition
- [ ] function-definition-linear
- [ ] function-notation
- [ ] functions-dr
- [ ] functions-examples-definitions
- [ ] functions-for-character-animation
- [ ] functions-make-life-easier
- [ ] functions-vertical-line-test
- [ ] problem-decomposition
- [ ] simple-data-types
- [ ] standard-deviation
- [ ] surface-area-rect-prism
- [ ] threats-to-validity
- [ ] transform-compose-images
- [ ] histograms
- [ ] grouped-samples
- [ ] linear-regression - interpreting linear regression section needs to be reworked
- [ ] ethics-privacy-and-bias
- [ ] composing-table-operations
- [ ] data-collection
- [ ] identity-property
- [ ] variables
- [ ] probability-inference
- [ ] absolute-value-and-opposites-2
- [ ] choosing-your-dataset
- [ ] order-of-operations
- [ ] functions-can-be-linear 
- [ ] box-plots
- [ ] scatter-plots 
- [ ] measures-of-center

**Comment by schanzer** [comment]
@flannery-denny why do we care?

**Comment by schanzer** [comment]
This issue should be closed:

- If we define "creating something" as writing code or filling out a wbpage, then obviously we already do this
- If we define it as some kind (any kind!) of independent, creative work, then we already do this
- If we define it as some kind of project or substantive creation, then we don't...and I'd argue it's a terrible constraint to force!
