### ISSUE TITLE
`code` formatting in rubies is landing on top of the fitb

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2255]
<img width="678" alt="Screenshot 2024-10-29 at 10 58 23 AM" src="https://github.com/user-attachments/assets/b1616fb6-4eff-434e-8540-f1a32c01e53d">

Here's an example from the `alg2-split` branch in the file `lessons/Algebra2/periodic3-fitting-models/langs/en-us/pages/modeling-recent-co2.adoc`

Noting that it wouldn't totally bother me if code used within a ruby just rendered as normal text.

**Comment by flannery-denny** [comment]
@schanzer the initial issue is resolved but the subscript in ruby formatting is getting cut off. see the commit above.

**Comment by flannery-denny** [comment]
Also, @schanzer what do you suggest we do to address the resultant page overflows?

**Comment by schanzer** [comment]
@flannery-denny I've just pushed a commit which moves the rubies up _half a pixel_, which is enough to show subscripts. If we need anything more, however, I'm going to have change how tall rubies are allowed to be...which is going to break a TON of pages.

None of the changes that I've made here result in page overflows.
