### ISSUE TITLE
Add "epilogue" to bottom of DS pathways

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2264]
- Data Literacy should point to functions, and link to full DS
- Data Science should point to Algebra 2

**Comment by schanzer** [comment]
@flannery-denny feel free to revise the text, or close if you're happy

**Comment by flannery-denny** [comment]
Nice work @schanzer. 
I think Data Science is ready to go.
For Data Literacy, I wonder whether you object to using @lesson-link for the three lesson you mentioned and am inclined to add text suggesting that they can pick and choose what to add using our build-your-own-pathway. Do those ideas work for you?

**Comment by schanzer** [comment]
@flannery-denny done! close if you're happy
