### ISSUE TITLE
Should Boolean in animals table be capitalized?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2265]
While I’m triple-checking that I haven’t messed up anything with the original animals, I’m noticing that booleans are lowercase in the [animals table](https://www.bootstrapworld.org/materials/fall2024/en-us/courses/data-science/back-matter/pages/animals-dataset.html) and upper class in the[ animals dataset](https://docs.google.com/spreadsheets/d/1VeR2_bhpLvnRUZslmCAcSRKfZWs_5RNVujtZgEl6umA/edit?gid=0#gid=0)…

**Comment by schanzer** [comment]
@flannery-denny the current behavior is correct

**Comment by flannery-denny** [comment]
@schanzer I would love to understand why they get capitalized in the sheet and not in the table. FlanneryOn Nov 4, 2024, at 11:31 AM, Emmanuel Schanzer ***@***.***> wrote:﻿
@flannery-denny the current behavior is correct

**Comment by schanzer** [comment]
Bullets are capitalized in Google sheets, and lowercase in Pyret
