### ISSUE TITLE
New Fitting Models Lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2266]
This lesson belongs in the DS pathway, before linear regression. It should be written with that in mind.
We know that switching datasets introduces a pretty large barrier of entry. 
- [x] Make a new version of **How could we Measure Whether a Model is a Good Fit?** using a subset of the animals - this is a win for DS and Algebra :)
- [x] #2228
- [x] Make a new starterfile that surfaces the subset we want to focus on.
- [x] Figure out how to keep the materials that use the cheerios dataset as optional resources for teachers
- [x] Develop optional materials (`from-lines-to-functions.adoc`) that support students in defining functions for their guessed models that they can test with fit-model. Perhaps have them use clownfish first (since it only has two points and everyone will use the same ones). Something like [this page](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/exploring-linear-models/pages/model-college-v-income-1-scaffolded.html)? 
- [ ] have students complete workbook pages about the animals dataset that look much like what they will do with the states dataset
-- [exploring-states](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/exploring-linear-models/pages/exploring-states.html)
-- [looking-for-patterns](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/exploring-linear-models/pages/exploring-states.html)
- [ ] When we're finished consider whether the linear lessons also work for *algebra-pyret*

**Comment by flannery-denny** [comment]
@schanzer I'm 100% sure this lesson is headed for the space between scatter plots and lr. Can you confirm that you imagine correlations will go before it?

**Comment by schanzer** [comment]
@flannery-denny the more I think about it, the more I think this should actually go _before_ the correlations lesson.

- we already can't discuss leave-plot in this lesson, because linear regression has its own lesson
- That means kids never actually see any output involving R or R squared
- Calculating the slope of all these lines actually gives kids better intuition about the sign of R, _before_ they learn about R
- this would allow an algebra two teacher who is pressed for time to skip the correlations lesson entirely, which is a good thing since they don't use R _at all_

Happy to discuss if you disagree, but this feels like a useful switch

**Comment by flannery-denny** [comment]
@schanzer 
Here are the characteristics of the cheerios starterfile I’ve been striving to reproduce.

- roughly 10 data points
- axes can be labeled with whole numbers (neither the range / nor the domain is less than one)
- preliminary linear models have whole number y-intercepts and slopes that could easily be represented by whole numbers or fractions

I have come up with several subsets from the expanded animals table that don’t meet this criteria.

- kittens and puppies are much larger datasets (I think this is detractive for the purpose of having kids look at the points printed on the workbook page and describe why one model is better than the other)
- other animals weigh so little that the function definitions are much harder for students to parse

I’m leaning toward using the [first ten-rows of teenage cats](https://code.pyret.org/editor#share=1MIyvTZKy7-7dYSupBV6wXxmJNpBf76lS&v=dc8be4e).
The values include decimals to the tenths place, so it’s a little more complicated than cheerios, but feels usable.
![image](https://github.com/user-attachments/assets/a663fe75-4414-464c-ae11-0b6d96748fb7)

Work for you?
Thoughts on how much of the filtering is hidden vs. visible? I could always copy these ten rows into a new tab of the sheet and import is a table named "teen-cat-sample"

**Comment by schanzer** [comment]
@flannery-denny this _mostly_ works for me, but I really dislike giving kids non-integer values. Would pounds v. weeks give us whole-number values?

**Comment by flannery-denny** [comment]
I'm actually glad to hear that. I was checking in because I wanted to make sure I wasn't wasting time by continuing to look for something better.

Lizards only have whole number weights. Here's what we get with the first-10 lizard rows. If it works for you, I'll tackle it.

![image](https://github.com/user-attachments/assets/cea907cb-b62e-419a-bf78-7bd11c13fca4)

**Comment by schanzer** [comment]
@flannery-denny I love it! Do we have wiggle room to move one of those outliers (the bottom left) so it's not quite as insane of an outlier?

**Comment by flannery-denny** [comment]
@schanzer Unfortunately, that point is from Buddy - a lizard that is in the original dataset so the plan is not to change him. 

- Option 1: If it's ok with you for the subset of animals to come from a separate tab in the sheet, instead of by way of filter functions in the starter file, I can just pick a different lizard to include.
- Option 2: I bet you could write a more sophisticated filter than `first-n-rows`, which is what I used.

**Comment by flannery-denny** [comment]
@schanzer That would be great! Are you game to make the whole tab? Or do you need me to put 10 lizards in to get you started?

**Comment by schanzer** [comment]
@flannery-denny please get me started with the lizards you want :)

**Comment by flannery-denny** [comment]
@schanzer I think [this lizard-sample sheet](https://docs.google.com/spreadsheets/d/1CsTAFDzOMXbhVznQcuekbyrPsH9CibReU0DYD71rv4M/edit?gid=722151103#gid=722151103) should work

**Comment by flannery-denny** [comment]
@schanzer I've pushed a draft. Decisions to be made:
- should we remove r-sqr from `fit-model` in pyret if we’re introducing it before correlations and lr-plot
- does it make sense to have them try drawing their own line of best fit before working with f and g on `how-could-we-measure-good-fit-lizard.adoc`
- I'm not sure whether I want to scaffold having them define their own model on a page where 
-- part 1 is clownfish and part 2 directs them to look back at the scatter plot for the points
-- move the scatterplot currently on `how-could-we-measure-good-fit-lizard.adoc` to a separate page and have the second part of that page be about defining the model. 
-- Either way I want to model how to define a model using the clownfish before asking them to define their own

**Comment by flannery-denny** [comment]
@schanzer Checking. Do you imagine this lesson is supposed to also work in codap?

**Comment by flannery-denny** [comment]
@schanzer Closing this and opening a pull request to merge alg2-split. Noting that there are two check boxes that have not been completed. If either feels important, feel free to reopend the issue or address it yourself!
