### ISSUE TITLE
macOS click behavior on CODAP graph

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#2273]
In https://www.bootstrapworld.org/materials/fall2023/en-us/lessons/codap-dot-plots-bar-charts-codap/index.shtml?pathway=data-science-codap, it is stated that

> Holding the shift button allows students to select multiple dots in the graphical display, or multiple rows in the table.

On macOS, Shift-click works like this only on the graph. On the table, Shift-click selects all rows from the clicked row to the nearest adjacent selected rows on both sides. Cmd-click does have the intended effect of adding just the clicked row to the selection. 

However, Cmd-click can't be used with this intention on the graph: It has the same effect as a regular (unshifted) click. Thus, Cmd-click won't work as a universal replacement for Shift-click on macOS.

**Comment by schanzer** [comment]
@retabak Dorai is right -- you'll need to add an extra sentence or two about this. I'll file a bug report with the CODAP folks as well.

**Comment by retabak** [comment]
Will do. Thanks! (I think maybe you mentioned this a while ago and I failed to update. I appreciate the reminder.)
