### ISSUE TITLE
QandA stitched across a slide break is leaving a big vertical space

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2278]
<img width="896" alt="Screenshot 2024-11-05 at 10 52 01 AM" src="https://github.com/user-attachments/assets/edcdfa7a-ceab-4a05-a62f-1d70cf91217c">

Here's what I'm seeing in scatterplots on the `alg2-split` branch

**Comment by schanzer** [comment]
@flannery-denny there's a minimum height to each Q&A block, and the one on top is already at the minimum. The best I can do is shave off maybe another 20pixels, but the real problem is that the space isn't being used.

**Comment by flannery-denny** [comment]
@schanzer Why is there an arbitrary minimum height limit that is smaller
than what we'd need for a one line question and one line answer?

**Comment by schanzer** [comment]
@flannery-denny because otherwise the icon gets cut off, and looks utterly bizarre:

![image](https://github.com/user-attachments/assets/fabf80ef-80df-4b2d-ba56-c55822e9e4a5)

(Don't forget that not all Qs have an A!)
