### ISSUE TITLE
Expressions & Equations: Evaluating Exponents - Workbook Page Error on Which One Doesn't Belong

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2284]
In the Expressions & Equations curriculum and the Evaluating Exponents lesson on the [Which Onehttps://bootstrapworld.org/materials/fall2024/en-us/lessons/evaluating-exponents/pages/wodb.html Doesn't Belong](url) workbook page, there is a typo on question 5.  The 2nd circle of evaluation diagram is missing num in front of -expt in the inner most circle.

**Comment by schanzer** [comment]
Thanks, @joystraub ! I've updated the website with the fix
