### ISSUE TITLE
Desmos Activity: Matching Examples to Contracts & Examples has incorrect answer key on 2nd slide

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2285]
The answer key on the 2nd slide of Matching Examples to Contracts & Examples Desmos activity shows this pair as incorrect:
![image](https://github.com/user-attachments/assets/8b8cefc0-093c-4b6f-837b-d2782a4c4caa)
When students click on the option to show correctness, they see this:
![image](https://github.com/user-attachments/assets/815beaa6-f992-4fbf-9ec3-37e580d31c16)
However, these are correctly matched.
This Desmos activity is found in the Data Science Functions: Contracts, Examples, & Definitions lesson.

**Comment by schanzer** [comment]
Assigning to @retabak (the queen of Desmos!)
