### ISSUE TITLE
Make sure that exercises in threats to validity actually provide examples and practice for each threat.

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2294]
While making the assessments in summer 2024 Rachel flagged that the work we're asking students to do on the pages in this lesson doesn't align with instruction

**Comment by retabak** [comment]
@schanzer - reopening this as we discussed. 

Here's what I slacked you: At the end of our conversation, you said, "Now I feel even more strongly that there needs to b content in the lesson about incorrect use of charts" - after we discussed how the two sections have very different goals.

**Comment by retabak** [comment]
OOPS, closing. I see this is a duplicate. Sorry!
