### ISSUE TITLE
Confusion in the Scatterplot Lesson with the Explanatory Variable

### ISSUE THREAD

**Issue by joystraub** [bootstrapworld/curriculum#2295]
In the Data Science Scatter Plot Lesson plan and slides the explanatory variable for the animals example switches back and forth between pounds and weeks, when it should all be age and age.
In the [lesson plan](https://www.bootstrapworld.org/materials/fall2024/en-us/lessons/scatter-plots/index.shtml?pathway=data-science) it switches back and forth:
![image](https://github.com/user-attachments/assets/c41cdaf0-8b89-4dc3-8c9a-b060eaf34fe2) All references to weight should be changed to age.
And in the [Google Slides](https://docs.google.com/presentation/d/1gjS0ZoaVymcTSq_u1LcWvMNFDdEObbZEitJrtoJvbpQ/edit#slide=id.e4ba12a2-3fcd-11ef-ae6d-75db4f0aaaf2) it starts off with age and weeks on slide 2 but then says weight in slide 4, with back to age in slide 5 and beyond. So I think that slide 4 needs to be changed to say: In this case, are we suspecting that an animal’s **age** can explain how long it takes to be adopted, or that how long it takes to be adopted can explain how **old** an animal **is**?

**Comment by flannery-denny** [comment]
Thanks @joystraub  In case someone else gets to this before I do, I caught this while doing a significant rework of this lesson and have fixed it for fall 2025 on the `alg2-split` branch. If I'm remembering correctly, the issues was bigger than what Joy is reporting and includes replacing images. Maybe worth looking to see whether my whole fix could be cherrypicked for release in January?
