### ISSUE TITLE
Improvements to dist-link and lesson-link

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2297]
- [x] `@lesson-link{distribution/en-us/lessons/exploring-periodic-models/#_hybrid_models}` fails for two reasons, one of which is because Racket considers everything after the `#` to be part of the filename. The build script should strip off the `#...` from the end of the string before checking.
- [x] `@dist-link{courses/hour-of-code}` fails for the same reason as the first link: the path is to a _directory_, not a file.

Can we fix these?

**Comment by ds26gte** [comment]
The second subitem is solved by writing `@dist-link{courses/hour-of-code/}`, i.e., with a trailing slash that identifies the last part as a directory, not a file. Is this onerous to do?

**Comment by schanzer** [comment]
Not onerous. :) Thanks, @ds26gte !
