### ISSUE TITLE
I'm seeing the description from the lesson-images.json file showing up on the workbook page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2299]
There’s something very strange happening with the image at the top of `lessons/Data-Science/fitting-models/lines-to-functions on the `alg2-split` branch. 

1. The description from the `lesson-images.json` file is showing up on the page 
2. I’m not able to change the size of the image. 

When I inspect I see the following:

- Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (’file://’) does not match the recipient window’s origin (‘null’).
- Deprecated feature used.

**Comment by schanzer** [comment]
@flannery-denny those JS console lines can be safely ignored - they're unrelated to this issue.

The problem is that image titles _must be plain text_. Removing the ` characters from the description string in lesson-images.json appears to fix the issue.
