### ISSUE TITLE
bottom of subscripts from unicode characters are getting cut off on rubies

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2300]
I'm in `lessons/Data-Science/fitting-models/lines-to-functions` on the `alg2-split` branch.
I've tried using:
`&#8322;` and `~2~` 
Either way, the bottom of the 2 gets cut off.
`Second point: (@fitbruby{2em}{@ifsoln{5}}{x&#8322;}, @fitbruby{2em}{@ifsoln{4}}{y&#8322;})`

**Comment by schanzer** [comment]
@flannery-denny This one required that I work in _tenths of a pixel._ We are dangerously close to having to make rubies themselves taller, which will likely cause many pages to overflow. If that's needed, so be it -- but just letting you know that future ruby-related issues will not be so easy a fix!

**Comment by flannery-denny** [comment]
Thanks @schanzer
