### ISSUE TITLE
please mirror pyret's count function in the BSDS context to replace the default column header "value" with the column name

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2312]

**Comment by schanzer** [comment]
This is now complete, using v2.2 of the DS library. Try evaluating `count(more-animals, "species")` in [this file](https://code.pyret.org/editor#share=1tx1Ix2HEkYH4K0HBv4WclmBv86-wdlQt&v=dc8be4e)

**Comment by flannery-denny** [comment]
@schanzer sounds like we need to update all of the DS starterfiles for 2025. True? Or has that already happened?

**Comment by schanzer** [comment]
@flannery-denny unfortunately, we'll need to update all the starter files. I'll open a git issue for that...
