### ISSUE TITLE
... in a lesson plan is rendering as i.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#2321]
I'm seeing this in Measures of Center on gold standard
<img width="888" alt="Screenshot 2024-12-17 at 11 50 14 AM" src="https://github.com/user-attachments/assets/5118c679-a3de-4e2a-ac70-ea5988a0e151" />

**Comment by schanzer** [comment]
@flannery-denny I'm not seeing this.  Can you add a screenshot so I have a sense of  where to look?

**Comment by flannery-denny** [comment]
@schanzer done

**Comment by schanzer** [comment]
Thanks, @flannery-denny ! `...` is an asciidoc command (much like `::`!), so we need to "escape" it by adding a backslash to the beginning. The attached commit does this.
