### ISSUE TITLE
table issues in workbook-long-sols.pdf for Oklahoma on master

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#2327]
- [x] p85: this would look better if the nums and @fitbs were at the same vertical height
![image](https://github.com/user-attachments/assets/30525ab0-ff03-4a30-8562-e16eaa2859e4)
- [x] p89: positioning of fitb expressions makes it look like the fitb correlates with the graph beneath it. Can we bump to top or center vertically?
- [x] p7: bullets shouldn't appear? probably shouldn't be centered either.
![image](https://github.com/user-attachments/assets/a6e64b06-6353-41b5-87b3-22d174ca114a)
- [x] p10: mystery weird little scribbles (overlapping text) 
![image](https://github.com/user-attachments/assets/e2a13afc-a2af-4128-8fc1-57be41962b49)
- [x] p16: squashed numbers
![image](https://github.com/user-attachments/assets/3cd29fca-7d6b-4cff-9bb3-da78cb0f2841)
- [x] p42: suspecting this used to be centered; if not, it should be! (perhaps make middle column wider)
![image](https://github.com/user-attachments/assets/6c11da6d-e61f-46ca-b6d5-ffb01265bcbf)
- [x] p55: solution missing (not a table problem, but let's fix)
![image](https://github.com/user-attachments/assets/0835f92f-e15a-48f1-81b9-4d115639a939)
- [x] p57: is there any way the font can be bigger? also, why not code font?
![image](https://github.com/user-attachments/assets/86b20d5a-dcd7-49bc-9a14-5fb6d69b832f)
- [x] p61: can the font in the grey box be larger. Also, why isn't it code font?
![image](https://github.com/user-attachments/assets/df999bf8-5dd4-499b-9df8-d85b30424792)
- [x] p68 - I thought this page was optional?
- [x] p71 - code not appearing in code font
- [x] p78: checkmarks are green + much more visible on webpages
![image](https://github.com/user-attachments/assets/fe98efc6-dd89-4985-a49e-e2b51cb81f5f)
- [x] p83: the numbers and letters should be further left and right (respectively), so they are closer to the definition / table that they refer to
![image](https://github.com/user-attachments/assets/3700fa35-a471-4c40-b93d-faca30b1eda8)
![image](https://github.com/user-attachments/assets/5f4e5487-67e8-4633-9c54-6791e34db35f)
- [x] p90: can the numbers be moved farther to the left?
![image](https://github.com/user-attachments/assets/69fa8bd3-6444-41eb-bf49-46d4902aa22d)
- [x] p149 - move numbers farther left
![image](https://github.com/user-attachments/assets/4785d5a1-adef-4e86-b686-f19237f605d3)
- [x] `zwsp` bug on "Logic Errors" 1, 2, and 3 (p151-153)
- [x] p163 - are there supposed to be gaps between the table rows?
![image](https://github.com/user-attachments/assets/6cd575f0-f09e-4159-ba6b-6a451c8361d2)
- [x] p178 - vertically center numbers
![image](https://github.com/user-attachments/assets/ffef9f31-8b69-4d03-a4f0-43511e5831f9)
- [ ] p181 - this needs solutions for the tree diagrams
![image](https://github.com/user-attachments/assets/eeccb4d9-7979-4e05-a167-c2832fc18c55)
- [x] p182 + 186 - should vertically center everything (including word probs and solutions) for consistency
![image](https://github.com/user-attachments/assets/442c31ec-435a-4ec1-aca0-83dcb7329523)
- [x] p189 - "categorical or quantitative" - numbers are cut off
![image](https://github.com/user-attachments/assets/f2aa9295-7486-442b-b6ae-155b8dc80665)
- [x] p198, 200 - instructions need to be above the image of the solution, images should be centered
![image](https://github.com/user-attachments/assets/79fd953e-b4ec-41e8-855e-cf6934a8fae9)
- [x] p217 - all text on table should be vertically centered
![image](https://github.com/user-attachments/assets/700b81c4-262e-49e5-b7b2-c58e700a1d69)
- [x] p280 - planning table operations - numbering cut off
- [x] p279-282 - the text in the COEs is very small (& p278 suggests that it need not be so small)
![image](https://github.com/user-attachments/assets/cff95c39-5b6a-44f3-8691-d87826bbb95a)

**Comment by schanzer** [comment]
These are being addressed on the `gold-fixes` branch
