### ISSUE TITLE
Table Functions Pathway

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#2332]
Currently we have a four-lesson sequence:
```
lookups
functions-dr
defining-table-functions
filtering-and-building
```

There's a lot of overlap between the every adjacent pair of lessons. 

Read through all four lessons, and see if they can be combined into three.

**Comment by flannery-denny** [comment]
@schanzer a perhaps relevant comment from Joy "I taught piecewise functions with the table functions just before filter and build"

**Comment by schanzer** [comment]
Closing now that #2341 is ready for review
