### ISSUE TITLE
Add navigation sidebar

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#239]
![image](https://user-images.githubusercontent.com/77126/114604621-20c0c180-9c67-11eb-93b5-23e44a2a1a8c.png)
Proposal, April 13th, 2021 Flannery, Dorai and Emmanuel:

- [x] Add sidebar (css fixed, glued to the right of the screen). (html `id="sidebar"`)
- [x] Add a sidebar section for Standards (html `id="standards"`), and include a dropdown menu with the list of standards (CC-Math, OK, etc). When a selection is made, populate this section with the individual standards
- [x] Add a sidebar section which lists all of the lessons in the pathway, in order. These lessons should be clickable links (see #441). Some of these links should have `class="prerequisite"`, based on the **transitive** dependencies. (emphasis on transitive!) 
- [x] Remove prerequisites and preparation rows from main table
- [x] Add "Practices" row, which will be populated with badges

**Comment by schanzer** [comment]
![image](https://user-images.githubusercontent.com/77126/114604621-20c0c180-9c67-11eb-93b5-23e44a2a1a8c.png)
Proposal, April 13th, 2021 Flannery, Dorai and Emmanuel:

- [ ] remove prerequisites and preparation rows
- [ ] add "Practices" row, which will be populated with badges
- [ ] add sidebar (css fixed, glued to the right of the screen) with sections for standards, and navigation sidebar
- [ ] color the sidebar based on transitive prerequisites (see #441)

**Comment by schanzer** [comment]
@ds26gte the sidebar is currently rendering as empty, with all the desired content being rendered as _siblings_ - rather than children - of the sidebar.

![image](https://user-images.githubusercontent.com/77126/120905602-27453700-c621-11eb-99a4-d647583621cd.png)

**Comment by schanzer** [comment]
- [ ] Add heading for "Pathway" (under which are UL/LI elements for each link)
- [ ] Add heading for "Standards" (under which is the old multiselectable TEXTAREA)

**Comment by schanzer** [comment]
Making the sidebar work requires some significant changes to the website's CSS. It was never designed with a fixed-side right-hand panel in mind. This work is now complete.

**Comment by schanzer** [comment]
Closed by d440412c17f4622bb76711e461a7da15e77352eb
