### ISSUE TITLE
Add additional forms of data to Intro to DS lesson

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#241]
Consider enhancing the initial question-asking activity with having students look at data visualizations or conclusions (news headlines?) to generate discussion on additional information and relationships, with the goal of reaching NGSS-HS-SEP1-2: Ask questions that arise from examining models or a theory, to clarify and/or seek additional information and relationships.

**Comment by schanzer** [comment]
I'm slotting this into the big "Ideas for DS 1.6" issue (#155 ), which I'll unpack when it's time to start thinking about the next revision. Closing this issue for now, to keep the list easier to manage
