### ISSUE TITLE
"Math text" is showing up twice 

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#268]
This screenshot is from DS - Applying Functions.  It looks like the math text is being formatted correctly but the original text is still showing up next to it.

<img width="871" alt="Screen Shot 2020-06-17 at 12 35 10 PM" src="https://user-images.githubusercontent.com/43153234/84930720-57ee3280-b097-11ea-8ee4-0b65f570f186.png">

**Comment by ds26gte** [comment]
615d6c02 should have fixed this.
