### ISSUE TITLE
Math text triggering a line break in lesson PDF files

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#269]
"Math text" seems to be triggering line breaks in the PDF versions of the lessons.  

From DS - Applying Functions:

<img width="620" alt="Screen Shot 2020-06-17 at 5 30 59 PM" src="https://user-images.githubusercontent.com/43153234/84957476-e75c0b80-b0c0-11ea-8051-ba376b8ebd57.png">

**Comment by schanzer** [comment]
I don't see this on my machine. @BootstrapJen , how are you creating this PDF?

**Comment by BootstrapJen** [comment]
/Bootstrap/curriculum/distribution/en-us/courses/data-science/lessons/ds-applying-functions/index.pdf

I did try deleting my `distribution` folder and rebuilding, and I still see this.

**Comment by schanzer** [comment]
Huh. Can you type `wkhtmltopdf -V` into terminal and copy/paste what you get back? Also, can you attach the HTML and the PDF for the lesson plan here, so I can dig in a little?

**Comment by BootstrapJen** [comment]
[index.pdf](https://github.com/bootstrapworld/curriculum/files/4805719/index.pdf)

**Comment by schanzer** [comment]
Hi @BootstrapJen  - can you attach the HTML for the lesson plan here?

**Comment by schanzer** [comment]
I'm going to close this for now - if the issue remains (esp after upgrading to wkhtmltopdf 0.12.6), we can re-open.
