### ISSUE TITLE
Distance and Collision lesson updates

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#279]
- [x] Could we add an image of the word problem or a place for students to sketch the story? It's complicated! 
- [x] Also there's an is in the wrong place and I didn't find the file to fix it yet.
- [x] be explicit about `line-length`, with a callout box to teachers explaining why
- [x] Add a game screenshot with the triangles
- [x] add line-length to workbook
- [x] Add a coordinate grid in the graph quadrant of the distance-multiple-representations
- [x] Change coordinate pairs for distance-multiple-representations to (1, 3) and (5, 0)
- [x] Change coordinate pairs for distance scaffold

**Comment by schanzer** [comment]
@flannery-denny I added a ton of missing stuff from the old version. What connections did you have in mind?
