### ISSUE TITLE
Boxplot definition hard to find (and maybe use?)

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curriculum#281]
Where are teachers/students supposed to learn what a boxplot is? It isn't in the Pyret documentation, and there are no links to the Glossary from the lesson plans. The glossary is the only place I find any defn of boxplot (and that was after my searching for one for several minutes).

This came up when looking at workbook page 14.

**Comment by schanzer** [comment]
We have this [written up in the lesson](https://www.bootstrapworld.org/materials/fall2020/en-us/courses/data-science/lessons/ds-measures-of-spread/index.shtml#_measures_of_spread_duration_30_minutes_).

Happy to take suggestions on improving the level of detail we go into.

**Comment by schanzer** [comment]
Closed in cfd9e0235
