### ISSUE TITLE
How we introduce functions in DS -- couple of concerns

### ISSUE THREAD

**Issue by kfisler** [bootstrapworld/curriculum#283]
The use of gt to introduce functions in DS seems like a missed opportunity. Here we are in a context where variables arise naturally (from the observations in a dataset), and rather than make that connection, we're starting with gt? 

Then the remix notes skip the part about circling and naming, which seems an essential justification for the DR.

It feels like we're missing an opportunity to really work with the function concept here, perhaps because we decided to reuse a lesson from Algebra. Not sure that reuse is doing DS due service though.

**Comment by schanzer** [comment]
We ran a few iterations of this, where the first function students write is a lookup function that works with rows. The cognitive load of learning the design recipe is high enough, without introducing lookup syntax. And then there's the fact that the examples are a lot more complex than in algebra, and ultimately do _not_ get circled and labeled.

We needed a gentler introduction to functions, and going from numbers to strings to rows was a good slope.

**Comment by schanzer** [comment]
@kfisler does this make sense? OK to close?

**Comment by schanzer** [comment]
Closing, especially in light of the upcoming Great Examples Refactor in 1.6 (see #155)
