### ISSUE TITLE
Change gender to sex on all workbook pages and supporting datafiles

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#287]
- [x] Change gender to sex on all workbook pages (Flannery)
- [x] Change gender to sex on all datafiles (Emmanuel)

**Comment by schanzer** [comment]
The data files are already fixed. We just need to update the links to those files in the lessons.

**Comment by schanzer** [comment]
Fixed by bb6a27f8 and bc0c1dd5
