### ISSUE TITLE
Revisions to Table-methods starter file

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#289]
- [x] Animal A and Animal B in this file share a lot of common traits. Let's choose more distinct animals to test with.
- [x] To avoid confusion, let's switch Animal A and Animal B in this file to Animal Y and Animal Z
- [x] If we do that we also have to make the switch on workbook pages.
- [x] Add examples into starter file
- [x] And we have to make the switch in peardeck pages.

**Comment by flannery-denny** [comment]
The file I'm looking to update isn't in the DS-1.5 Starter Files folder.

It includes directions such as...
########################################################
# Part A - write examples for all the functions above
# don't forget: examples do NOT include column lookups!

########################################################
# Part B - Using those functions...

# example - Make a table of only dogs (define it as "dogs")
dogs = animals-table.filter(is-dog)

# 1 - Make a table of only fixed animals (define it as "fixed")

# 2 - Make a table of only fixed dogs (define it as "fixed-dogs")

# 3 - Add a column called "sticker", containing a label for every animal

# 4 - Make a pie chart showing the gender..of only fixed dogs

# CHALLENGE - make a table of old, fixed dogs...with a "sticker" column!

#######################################################
# Part C - Making functions of your own!
# For each item below, type the FULL design recipe:
# Contract, Purpose, Examples and Definition

# 1 - write `is-young`, which takes in an animal and
# returns true if it is less than 2yrs old

# 2 - write `kilos`, which takes in an animal and 
# produces an animal's weight in kg

**Comment by flannery-denny** [comment]
I suggest using Felix old fixed cat and Midnight young not-fixed dog for the predefined animals.

animalX = animals-table.row-n(4) 
animalY = animals-table.row-n(13)

When I get the green light, I can update them in the google folder and on page 27 (Reading Function Definitions). And in the Defining Table Functions Lesson Plan.

If I understand correctly, the Design Recipe pages 29, 30, 33, 34 should refer to Animal X and Y in the table-methods starter file or to Animal A and Animal B in the animals starter file.  There are also peardecks pages that correspond to this... so I don't want to make the change til I get the green light.

**Comment by schanzer** [comment]
You’ve got the greenlight. Go! We can redo the peardecks once all the changes are made

**Comment by flannery-denny** [comment]
Think we're ready for peardeck changes.

- I changed both table methods starter files. 
- **Do we need to keep both?** (They are the same - except for one is v1.5 and one is v1.5.1. )
- I changed the Defining Table Functions Lesson Plan.
- I changed the Design Recipe for pages 30 and 31.
- Page 33 and 34 weren't listed under this lesson so I decided maybe it was ok for them to work with Animal A and Animal B?

**Comment by flannery-denny** [comment]
I added all 3 forms of examples for Animal X into the starter file as well as note to find Animal X and Animal Y on the data table and label them in the margin. Please confirm language is ok.

**Comment by schanzer** [comment]
Don't change both! Please go back and put v1.5 back to where it was. Remember when I told you I needed to make a new spreadsheet and starter file when I added the snail? That's where 1.5.1 came from. We _cannot_ change a starter file once it's being used by teachers.

Update 33 and 34 as well.

I don't see the instructions to label them in the margin?

**Comment by flannery-denny** [comment]
I reverted v1.5.

The instructions re: the margins in 1.5.1 are in line 21.

Flannery 

> On Jul 21, 2020, at 6:29 AM, Emmanuel Schanzer <notifications@github.com> wrote:
> 

﻿
Don't change both! Please go back and put v1.5 back to where it was. Remember when I told you I needed to make a new spreadsheet and starter file when I added the snail? That's where 1.5.1 came from. We cannot change a starter file once it's being used by teachers.

Update 33 and 34 as well.

I don't see the instructions to label them in the margin?

**Comment by schanzer** [comment]
Re: PearDeck - do you mean the PD deck, or the lesson deck? Because I don't think that file is referenced anywhere in the lesson, so it wouldn't be appropriate to update that slide deck.

**Comment by schanzer** [comment]
I'm going to be rebuilding the PearDeck slides from scratch once July is over, so this will be updated automatically.
