### ISSUE TITLE
DS workbook page 8 - Booleans update

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#291]
This page goes very quickly for some and very slowly for others. Can we add a challenge to the bottom? And/or refer people to explore the Boolean operators page when they're done on the corresponding Peardeck slide for PDs?

**Comment by schanzer** [comment]
Love both ideas. Add the PearDeck idea to that issue so we don't lose it. What challenge would you consider?

(Idea: remove `<>` entirely, and make figuring out what it does the challenge. Hardly anyone uses it anyway, so it doesn't necessarily deserve to be in the required exercises.)

**Comment by schanzer** [comment]
Actually, I like your idea of putting the Boolean Operators link on the PD deck even better. Done!
