### ISSUE TITLE
DS workbook page 9 - Catching bugs

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#292]
- [ ] This is a page that some people complete very quickly and some people need time to complete. Can we add a challenge to the bottom - maybe encouraging people to explore the other shapes from their contracts page in pyret while they wait?
- [ ] I love this page... and most people complete it without using pyret.  In PD it always feels like Emmanuel imagines this as a page to get people to read error messages. We need to make another page that actually gets people curious about error messages.

**Comment by schanzer** [comment]
@flannery-denny how about we revise it to be a matching activity, where teachers have to match the buggy code with the error it generates? That will force them to read the errors, and we can add an instruction to *try solving it before typing them in*.
