### ISSUE TITLE
Measures of Center and Spread update

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#293]
This is a topic that most teachers don't understand so notes have to be particularly broken down.

- [x] Ideally the notes section would include a small data set, maybe just 12 or 16 numbers from which all of the math of how the box plot is generated gets explained.
- [x] Currently page 61 of the workbook expects students to use pyret to generate the info to make a boxplot and page 62 expects them to do the whole thing by hand.  While I like the context of income for page 62, the numbers in this dataset are cumbersome for working by hand. I would suggest making another data set with smaller numbers from which students generate the mean, median, mode and 5 number summary by hand and turning these numbers into another starter file that students can use to complete this page using pyret
- [x] In PD, people quoted Emmanuel's explanation "There are the same number of data points in each bin." as being very helpful.
- [x] Add description of pizza dough activity

**Comment by schanzer** [comment]
@flannery-denny I've updated page 62 to use far more "comfortable" numbers. All the calculations work out to nice round numbers, and require no more than adding 2 and 3 digit numbers. Does this get us to where we need to be?
