### ISSUE TITLE
Split Identifying Form into two pages (r on it's own page)

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#295]
In both PDs I've been part of at least one breakout room has gotten into a conversation about r before you wanted them to as a result of this page.

I really think that if you want people to hold off on estimating r, it shouldn't be included on this workbook page. Many grownups and kids don't do well with being told to do only part of a task and "we'll come back to it." 

(I'm still disappointed in my 8th grade writing teacher that he would "save" the end of a story or article we were reading for another day to switch tasks.)

**Comment by schanzer** [comment]
Would it be better to just go through ALL of the content, and then have students/teachers do that page all at once?

**Comment by flannery-denny** [comment]
Yes. But that doesn’t mean there can’t be other pages to complete along the way.
Flannery 


> On Jul 19, 2020, at 11:38 AM, Emmanuel Schanzer <notifications@github.com> wrote:
> 

﻿
Would it be better to just go through ALL of the content, and then have students/teachers do that page all at once?

**Comment by schanzer** [comment]
Does adding more pages meaningfully contribute? Every time we've done this page, people jump into it so quickly that - as you've observed - they wind up pushing ahead anyway. If it's not that hard, maybe adding more scaffolding is unecessary?

**Comment by flannery-denny** [comment]
We could

- reorder so that drawing predictors comes before Identifying form Direction and Strength 

- or we could leave Identifying form Direction and Strength where it is without r and then make another similar page, either for estimating r or with lr plots

**Comment by schanzer** [comment]
Turns out we already have an optional exercise that sort of does this! I've added it to the workbook so it's no longer optional, and update the lesson plan to match.
