### ISSUE TITLE
contracts page formatting

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#296]
Update this page to include the word example on each blank line. and leave a column for notes on the right.

**Comment by schanzer** [comment]
I want to push back here. Some people want to use the entire line for notes, and others need a lot of room to write an example.  Let's give them the freedom to use this space however they want.

**Comment by flannery-denny** [comment]
At the very least, we need to update the directions to encourage people to write examples and notes. 
And I think that adding an example of how to translate the first contract to code would be helpful.

I think that a visual encouragement to write something down for each line would increase the odds of people doing so.  

In our last PD it was Tyler's suggestion to make the columns a little narrower and add a fourth column on the right for notes.

In my googledoc version of the pyret code contracts page from the Oxnard PD, I have two lines for many of the contracts, one for examples and one for notes. Ideally, I think I'd make this contract sheet that way and write Examples and Notes at the front of the lines.

If you object to committing the space for two blank line or to inserting the words "example" and "notes" at the start, I'm not super attached to it.

**Comment by schanzer** [comment]
Yeah, I'm not comfortable with that. And each page _does_ have an encouragement to write down notes and/or examples. And we can't make the columns narrower than they already are. As it is, the contract for image-scatter-plot barely fits!
