### ISSUE TITLE
workbook font and spacing

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#299]
- [x] Insert a space between the title and the first row of text on each page.
- [x] Insert a space between bullet points in the notes sections.
- [x] Increase font size, particularly for notes and numbers. examples: 
- [x] page 2 - Font for "what do you notice?" 
- [x] page 8 - numbers in arithmetic column (why does it say processing math 100% at the bottom of the page?)
- [x] page 9 - numbers in the circles of evaluation could be bigger
- [x] Could all fonts be as big as page 25, 48, 49?

**Comment by schanzer** [comment]
Let's revisit this when you've seen the current build of the workbook. Many of these may no longer be an issue.

**Comment by schanzer** [comment]
I'm fairly confident the new font sizes are a whole lot better. Closing, but if the new sizes aren't enough we can revisit the issue.
