### ISSUE TITLE
Dissecting and Designing a video game

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#302]
The closing (below) for Dissecting and Designing a video game asks questions that seem to belong after the coordinates lesson...
Options:

Exit Slip: what role do coordinates play in videogames?

Discussion: what do you think the equations are, that govern the movement of characters in the game?

Share-back: have students share their video game designs with the class.

Also, since so many of us don't play video games, I love that there's a chance to concretize the conversation in ninja cat and hit or miss, but I've never played hit or miss, there's no chance to play it, and there's no key, so I don't know which of the squares are hits and which are misses and that makes it difficult to notice and wonder.

(Big picture we might want to think of some clearer scaffolding for the conversation around videogames that students actually play that makes sure that students who don't play videogames have enough of an understanding of what it being discussed to also benefit from that conversation.)

**Comment by schanzer** [comment]
Totally agree, Flannery. None of these questions belong in that lesson. I've removed them, and I think just leaving it as "have students share their game ideas" is totally fine.
