### ISSUE TITLE
Algebra workbook update priorities

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#303]
**Most Urgent**

- [x]  In general, this workbook could use more practice for the math connections. Explore the materials that already exist and add relevant ones to workbook-pages files.  Think about which others should be created.
- [x] Expand distance section.
- [x] Decide which notice and wonder pages to keep. Add context to those. Remove the others.
- [x]  Get rid of page 25 - Solving Word Problems with the Design Recipe.  Make them into a series of Design Recipe pages. 
- [x]  Adjust restating the problem lesson plan directions accordingly.
- [x]  Look at the scaffolds on page 30-35 and make sure that the lesson plan justifies their inclusions
- [x]  Add notes for Inequalities and Compound Inequalities.  Coding with And / Or is not intuitive!  If there's not going to be a notes page, we need clearer instructions on workbook materials (esp. page 45 - inequalities practice)
- [x]  Is there a good reason that none of the flag work is in the workbook?
- [x]  Collision Detection lesson plan has broken links to "earlier lessons" and "an entire lesson plan". Do these need to be written or just linked?

**Order of Operations**
- [x] Order of Operations lesson plan: why repeatedly refer to PEMDAS? 
- [x] Order of operations. Do you want a notice and wonder or something more scaffolded? Make sure lesson plan reference matches.
- [x] We've included COE to Code 2, because 1 was broken, but it doesn't make sense for the workbook page to read 2
- [x] Fix the additional practice pages that had examples repeat
- [x] Creating Circles of Evaluation from Math Expressions (2) problems 1 and 2 are the same
- [x] Evaluating Circles of Evaluation (1) the last 3 are the same
- [x] Translating Circles to Code w sqr roots: Is it really not possible to extend the square root symbol across the expression? I think it's important to help students recognize radical signs as grouping symbols.
- [x] Exploring Image Functions: I'd suggest including regular polygons... they'll get to text in a couple of pages.
- [x] Exploring Image Functions: Add directions for students to add these functions to the contracts page

**Domain & Range**

- [x] Add a matching activity to get students to look at error messages?
- [x] 13- Reading for Domain & Range: numbers 5-7 not sure how students would know this - don't think they've used these functions yet?

 **Function Composition**
- [x] Should we rename function composition 1 as function composition?
- [x] page 17 - composing image functions - Update directions to add contracts and examples to their contracts page
- [x] page 18: I made some changes. Added a spot to write out the code. Not sure how much it matters whether text is purple or black, but I'm not sure how to control it.

**Defining Values**
- [x] **CHECK TO SEE IF EMMANUEL's UPDATES ADDRESS THIS - page 15 & 18 - Function Composition Practice and Defining Value Practice ask us to do the same things with a solid green star size 50** 

**Restating the Problem**
- [x] Put two DRs on each page

**Comment by flannery-denny** [comment]
**Tackled Notice and Wonders**

- Added context to Ninja Cat intro notice and wonder
- Removed notice and wonder Coordinates because it wasn't referenced in the lesson plan
- [ ] Order of operations lesson plan references Notice and Wonder page that's not in the workbook. I think we should eliminate the workbook reference. What do you think Emmanuel?
- Removed notice and wonder from Defining Values because it wasn't referenced in the lesson plan.
- Removed notice and wonder for rocket-height. Seemed like a spoke reference in the lesson plan. Happy to put one with context back in if you'd like.
- Removed the distance notice and wonder because it's clear from the lesson plan that it's meant to be a conversation.

**Comment by flannery-denny** [comment]
Emmanuel - Is it ok for me to make these page 12 changes?
Exploring Image Functions - mystery functions!
 
- I'd suggest changing text to regular polygons... because it also gives students something open-ended to explore and  they'll get to text explicitly in a couple of pages.

- Add directions for students to add these functions to the contracts page

**Comment by flannery-denny** [comment]
Change page 18 to be outline fuchsia star

**Comment by schanzer** [comment]
@flannery-denny We refer to PEMDAS several times, because we need to explain how the CoE fit into the PEMDAS concept teachers already know. Is there a harm here that you see?

**Comment by flannery-denny** [comment]
Most great middle school math teachers do not teach PEMDAS. We teach Order of Operations.

1- parentheses and other grouping symbols, including fraction bars, sqrts (why it was important to me to fix them visually), absolute value bars, brackets, etc.

2- exponents

3- multiplication and/or division from left to right 

4- addition and/or subtraction from left to right

PEMDAS exists as a mnemonic device used in the world. We understand that. But we see the ways that it confuses students and do our best not to reinforce it. I might say something that acknowledges that people use the phrase PEMDAS, but you are using it as if it means the same thing as order of operations and that doesn’t sit well, and I think you lose some clout as a result. If a math teacher (even one who says PEMDAS all the time) can’t also feel comfortable reading the phrase order of operations, they are either eager for folks to model better language or I do not expect them to be likely to bring bootstrap into their classrooms.

> On Jul 24, 2020, at 6:25 AM, Emmanuel Schanzer <notifications@github.com> wrote:
> 

﻿
@flannery-denny We refer to PEMDAS several times, because we need to explain how the CoE fit into the PEMDAS concept teachers already know. Is there a harm here that you see?

**Comment by schanzer** [comment]
Ahhh, I see. So find-and-replace "PEMDAS" -> "Order of Operations" seems to address the issue, yes?

**Comment by flannery-denny** [comment]
yes

**Comment by schanzer** [comment]
@flannery-denny done! 

Since there's already an issue open for expanding the Distance lesson, we can probably either remove that checkbox or at least check it off (I added a bunch of content for that lesson this morning).

Can you say more about the math connection pages you'd like to see added? Teachers are going to start planning and printing shortly, so any _workbook_ changes are going to have to be made ASAP.
