### ISSUE TITLE
Flags of the world resource updates

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#308]
Flags of the world resource: 
 -  Perhaps worth a sentence about what the ratios mean?
 -  Not sure Georgia belongs on the list?  And if they're not using bitmap-url, not sure they can build Taiwan. 
 -  How about adding: 
>  - To First  list: Aland Islands, Cape Verde, Central African Republic, Pan-African Flag, Pride Flag, New Mexico, Alaska
>   -  To Second list: South Africa
>  - I think flags are a great time to teach the bitmap-url function.  If you're open to a list that would use that, I would suggest adding:  India, Lebanon, Uruguay, Rwanda

I think that fixing broken code is an incredibly powerful learning activity. I have made lots of broken codes for students and would be happy to share them in the resource section of this lesson. 

I've also written some code that works but is clunky and I have students slim down to make it more elegant.

**Comment by schanzer** [comment]
Closing, since this is duplicated in #223
