### ISSUE TITLE
New Data Sets for Data Science

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#310]
** see https://github.com/rfordatascience/tidytuesday ***

- [x] Add Data Set one-pager to Supplemental Materials
- [x] Once we've added a few more datasets, remove the least great of the data sets

- [x]  [I'd love to see us build some materials like these for specific data sets that push into thinking we don't get to with animals and not all students and/or teachers? will think of independently](https://docs.google.com/presentation/d/1FLqZBTxmB3AJNrw7yl3qSMe_6k1KKU-67dKcUmuidMA/edit?usp=sharing)
_________

- [x] 2016 Presidential Elections by state: 
> - Columns: Voting Age Population, Number of votes cast, number of felons disenfranchised, % non-citizen, Voting eligible population that didn't vote, number of votes the state's popular vote was won by, number of votes for third party candidates, who won the popular vote, electoral college delegates for Clinton, electoral college delegates for Trump
> - [Here's the sheet:](https://docs.google.com/spreadsheets/d/1WP-aE8jLa6fAWntG-qukev1nGAe3xO1RX7AMUZWOXEY/edit?usp=sharing)
> - Anything you would add?
> - Preference for quantities vs. percentages?

- [x]  Voter demographics 1986-2018  
> -  [Here's the sheet:](https://docs.google.com/spreadsheets/d/1wr65EkLFAIuTHpP_TWMNjFUZ-UOF-Yvo9xKpxwioegE/edit?usp=sharing)
> - Is this useful? 
> - Do I need to switch columns and rows?

- [x] **PERMISSIONS** I used columns from sheets for both of these from The United States Election Project.  Do you think we need to ask permission as an organization based on the blurb below? If so, should I reach out or would it be better for someone else to?

> Do I have permission to use the voter turnout data and graphics appearing on this website? 
> Yes. The voting statistics provided on this website are generally licensed under a Creative Commons Attribution 3.0 Unported License. Unless otherwise specified, other information provided here is not covered by this license. 
> 
> EXCEPTION: Organizations must obtain prior permission to use the information presented here in a report or other substantial work. Individuals and media organizations are welcome to use the data for their research or other projects, as long as adequate citation is provided.
> 
> If you have any questions about whether data presented here falls under this license, please contact Michael McDonald.
michael.mcdonald@ufl.edu

- [ ] Demographics of US Congress or world leaders?

- [ ] Look at links at [Measure of America](https://measureofamerica.org/)

- [x] Environmental Justice / Climate Change

- [ ] School-to-prison-pipeline / Access to Quality Education

- [ ] Immigration : [labor force
](https://www.americanimmigrationcouncil.org/research/impact-immigrant-women-americas-labor-force)

- [ ] Covid-19? / Healthcare / other pandemics?

- [x] Nutritional value snacks and beverages (coke, diet coke, orange juice, gatorade, water, coffee, tea, milk, starbucks frappuccino, lacroix, chipotle )

- [x] Police Brutality / [Stop and Frisk](https://www.nyclu.org/en/Stop-and-Frisk-data) data

- [ ] Pop Culture? - I don't feel great about the music and movies and pokemon data sets... and I'm pretty checked out of pop culture... wondering what other more meaningful data sets might be out there?

- [ ] Could videogames spreadsheet look more at change over time? Size of development team? 

[data set compilation list](https://corgis-edu.github.io/corgis/csv/)

**Comment by flannery-denny** [comment]
I completed turning the two sheets I made on the 2016 elections into pyret starter files and saved them in the shared DS folder.

- [ ] Where should I save the corresponding sheets.

- [ ] Can we please remove the 2016 primary election file?

**Comment by schanzer** [comment]
Corresponding sheets should go in this [GDrive folder](https://drive.google.com/drive/folders/1xiTi7kfhppTfYxVLVGSzXQYitNxFNVt6).

Let's definitely remove that file. Feel free to remove it from the lesson plan _and_ the teacher resources page (see `pathways/data-science/resources`)

**Comment by flannery-denny** [comment]
Crowdscourced suggestions:
Favorite social media app
How often various age groups post on social media
Android or iPhone
Extracurricular activities popular with teens
Average time spent watching television per night

**Comment by flannery-denny** [comment]
[environmental data sets](https://www.sciencebase.gov/catalog/)
[more envtl data sets](https://datadryad.org/stash)
