### ISSUE TITLE
Half of this page has solutions and half does not - is this intentional?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#312]
[Questions and Columns or exploring-animals-dataset in intro](https://www.bootstrapworld.org/materials/fall2020/en-us/courses/data-science/lessons/ds-intro/pages/exploring-animals-dataset.html)

**Comment by schanzer** [comment]
I assume you mean "one question on this page has answers filled in, and the rest don't - is this intentional?" :)

And yes, it is. The first set of answers are they to provide a template for what we want.
