### ISSUE TITLE
Booleans page text confused teachers today

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#313]
They wondered whether [Number 10 on this page](https://www.bootstrapworld.org/materials/spring2020/courses/datascience-remix/en-us/lessons/ds-pyret-intro/pages/booleans.html) really means... What are different types of string values that are allowable?

They also thought number 9 was confusing, but didn't offer other wording.

**Comment by schanzer** [comment]
@flannery-denny interesting. Do you have any suggestions for new wording?

**Comment by flannery-denny** [comment]
I just noticed that the wording from the inequalities page in the algebra workbook might solve the problem.
