### ISSUE TITLE
Reading histograms worksheet should not have axes labeled at all

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#316]
[reading histograms workbook page](https://www.bootstrapworld.org/materials/fall2020/en-us/courses/data-science/lessons/ds-histograms2/pages/reading-histograms.html)

We should check whether that's true for other histograms workbook pages

**Comment by schanzer** [comment]
Why?

**Comment by flannery-denny** [comment]
Because a teacher in this week’s workshop pointed out that if the stories they are matching the plots to involve rating movies on a scale from 1 to 10, using bin size of 1 is confusing cause it’s basically a bar chart.

Flannery 

> On Jul 31, 2020, at 5:52 AM, Emmanuel Schanzer <notifications@github.com> wrote:
> 

﻿
Why?

**Comment by schanzer** [comment]
I think this is another good argument for why we should just dispense with axes altogether in this worksheet. Bin problem solved!
