### ISSUE TITLE
Blank Starter File for turning sheets into pyret code has columns all caps

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#317]

**Comment by schanzer** [comment]
What's wrong with this?

**Comment by flannery-denny** [comment]
All of the files students use have all column titles in lowercase and we had to change some files to match that formatting for consistency, because when I was working with them I realized that inconsistency in formatting was leading me to get a lot of error messages. When I used the blank starter file to add new datasets, the all caps led me to think I was supposed to write column names in all caps.

Flannery 

> On Jul 31, 2020, at 5:51 AM, Emmanuel Schanzer <notifications@github.com> wrote:
> 

﻿
What's wrong with this?

**Comment by schanzer** [comment]
I think lowercase is more likely to get _overlooked_, which is arguably worse than someone writing perfectly fine code that happens to have a lot of capital letters. But I don't feel strongly about it, and I'll defer to your intuition!

Updated to use all lowercase.
