### ISSUE TITLE
Word Problem Section of Algebra workbook

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#319]
After fast functions, we enter a large section of the workbook dedicated to word problems.  The pages for this section still do not align with the lesson plan. The lesson plan makes one vague reference to the purpose statement organizer and no references to the mapping examples with circles of evaluation page. 

Whereas the Design recipes in this section are all filled in with word problems, there are blank templates for writing quality purpose statements and mapping examples with circles of evaluation spaced between them with no reference as to what they are to be used for.

- [x] If we're including both, they should both be referenced in the lesson plan.  And if they're an optional scaffold, perhaps just one copy of each belong before the design recipe pages begin?

- [x] If your goal is for people to use them for each problem, perhaps the word problems should be split so that there is one scaffold for each word problem? Instead of them being inserted after every two problems?

- [x] If we're sticking to two word problems per page, they should print so there is a visual separation between the first and second problem.

**Comment by schanzer** [comment]
The lesson plan _does_ refer to them: https://www.bootstrapworld.org/materials/fall2020/en-us/courses/algebra-wescheme/lessons/alg-restating-the-problem/index.shtml

The current workbook (which I know you're not able to build) has one of each scaffold page in between each DR page.

**Comment by flannery-denny** [comment]
I've read and reread these lesson plans and have yet to find a reference to mapping examples with circles of evaluation. I also don't see it linked in the materials. We can revisit when we talk this afternoon.
