### ISSUE TITLE
word problems order, update-player, line-length all have a hanging pair of )) on the last line

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#338]
I'm not sure where that comes from the in the code since these pages are pieced together out of various components

**Comment by schanzer** [comment]
Those match the open parentheses before `cond` and `define`. The reason they're on the next line is a limitation in our Design Recipe rendering code, that makes it impossible to cram them on the last condition. I've added this to the list of bugs to fix on #228
