### ISSUE TITLE
Simplify DR CSS Rules

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#342]
- [x] put the `proglang` in the BODY tag's classList
- [x] in the build script, assign the same classNames to all DR elements regardless of `proglang`
- [x] in `shared.css`, simplify rules a lot

**Comment by ds26gte** [comment]
I think the spirit of the second square is done in 2cdb599.  The build script _per se_ doesn't contain DR class names that need modifying, but it's taken care of in the Racket code.

**Comment by schanzer** [comment]
I think I'm mentally merging the Racket code with the build script. :)
