### ISSUE TITLE
Lessons for Graphing Functions in Pyret

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#343]
8th and 9th grade teachers would like more lesson materials based on defining math-focused functions in Pyret, graphing, and looking at tables to build understanding of the connections between the three.

A basic teachpack and student-facing starter file already exist and are available for Remixing or building up further:
[Student starter file](https://code.pyret.org/editor#share=1l6DfxUy8qD_h6y4O-yyiqOnPdktS1zfn&v=ebd213d)
[Teachpack](https://code.pyret.org/editor#share=1Zuqv5rua4xJe8CgqrCaGvuWF7KPP_jnG&v=ebd213d) - Note that this teachpack is using DS 1.4 currently.

In the 8th grade, there is a focus on differentiating between linear and non-linear functions and diving deeper into linear functions - slope, intercepts, etc.  

In the 9th grade, students begin getting into quadratics and exponentials, and might go further with higher-order functions, absolute value, etc. Focus on evaluating functions - drawing connections back to order of operations, function notation, identifying functions from their graphs, etc.

Check out this Open-Up Resources lesson [Connecting Representations of Functions](https://access.openupresources.org/curricula/our6-8math-nc/en/grade-8/unit-5/lesson-7/index.html) for ideas on where the focus would be for the 8th grade.

Check out this lesson [Multiple Representations of Functions](https://betterlesson.com/lesson/421244/multiple-representation-of-functions?from=search) to see what a typical 9th grade curricular focus looks like.

Notice and Wonder would be a great addition here, as well as more opportunities for student exploration and discovery in keeping with the modern spirit of the math classroom.

**Comment by flannery-denny** [comment]
@schanzer one thing I'm noticing here is the request for non-linear graphs
![Screen Shot 2020-10-20 at 11 28 42 AM](https://user-images.githubusercontent.com/66691020/96615854-d53ce480-12cf-11eb-9020-ff4a5be6d102.png)

**Comment by flannery-denny** [comment]
@schanzer And when they talk about multiple representations, they mean writing a function to describe a graph or a table. Do we have anything where we write a function to describe a visual. The prompts I can think of translate words --> functions --> images.

**Comment by schanzer** [comment]
@flannery-denny no, we don't have any material where students come up with a function based on a visual -- but I LOVE the idea! This also feels like something that should be scaffolded with a Desmos matching activity _first_, where students match visuals to a set of functions. After that, we can turn students loose to come up with a function given only the visual.

**Comment by flannery-denny** [comment]
@schanzer I'm new to making desmos activities.  Here's my first attempt. Not sure it's getting at what you were thinking [Matching functions to graphs](https://teacher.desmos.com/activitybuilder/custom/5fb7eb9e0595090d3adc48e2)

**Comment by schanzer** [comment]
@flannery-denny PERFECT!

I would make 2-3 more just like this, but with at _most_ half the number of functions. Make at least the first one linear-only.

**Comment by flannery-denny** [comment]
[Matching Linear functions and graphs](https://teacher.desmos.com/activitybuilder/custom/5fbe72167f5cee0d57130b96)

[Matching Linear functions, graphs and tables](https://teacher.desmos.com/activitybuilder/custom/5fbe74ac877d890d3e1a49cc)

**Comment by flannery-denny** [comment]
@schanzer [Bootstrap Function Card Match Collection](https://teacher.desmos.com/collection/5fbe7484d81cab0ca7a8bcfb)

**Comment by schanzer** [comment]
Notes from 11/27

Tables <-> Graphs (linearity!)
- [ ] Add table to graph matching activity
- [ ] Add table to graph defining activity
- [ ] Need exercises for matching and summarizing where the _scale_ is the same, but the _line_ is different
- [ ] Show linear tables with xs that aren't ordered by 1
- [ ] Add teacher notes, explicitly calling out the need to look at the scale
- [ ] Add desmos links
- [ ] Add linear .v non-linear lesson

Functions <-> Tables
- [ ] Not All Tables needs to be properly formatted as a matching activity
- [ ] Talk about repeated-x in tables vs. vertical line test 
- [ ] Add desmos links

Functions <-> Graphs 
- [ ] In "Match Graphs with Functions", graphs need to be precisely on the line (from tables<->graphs)
- [ ] In "Summarizing Graphs with Functions", graphs need to be precisely on the line (from tables<->graphs)
- [ ] WB page guiding them through ("type in `table1`. is it linear? make a graph of it")

**Comment by flannery-denny** [comment]
@schanzer I still think it's important to show a nonlinear graph like the one in this git issue

**Comment by flannery-denny** [comment]
@schanzer 

In tables - graphs you introduced linear relationships, slope and y-intercept.
In tables to functions you aren't connecting back to any of that. You   send them off to write functions from tables without offering any strategies.
I'd suggest providing one sideways table in the lesson plan (since that's how all of the tables in the worksheet are oriented) where you explicitly talk about how the input row goes into the function and yields the output. Alternatively, there could be more instruction on the worksheet itself.
I like to show multiple strategies for finding the rule from a table... rate of change & y-intercept / input --> output
Building tables from functions matching exercise should have at least some tables with the same start and end point, because otherwise they won't read the rest of the code.

will continue reading and add to this list, but it should get you started

Perhaps get to line 85 and build on it before you send them off to practice

**Comment by schanzer** [comment]
@flannery-denny I don't see ANY strategies discussed in the graphs-to-functions lesson. Or maybe I'm thinking of something different when you say "strategy"?

**Comment by schanzer** [comment]
- [ ] rename linearity-1, linearity-2, linearity-3

**Comment by schanzer** [comment]
Significant rewrite in d1dd7887a:

Condensed all three lessons into two, named `ds-linearity` (introduces the concept in terms of number sequences and straight lines on a graph) and `ds-linearity-2` (formalizes to slope and y-intercept, introduces function definitions). 

Remaining work:
- [ ] Figure out how the starter file is going to be used
- [ ] Get feedback from @flannery-denny 
- [ ] Make slides
- [ ] Align to standards

**Comment by flannery-denny** [comment]
@schanzer 
*Defining Linear Relationships*
_Slope and y-intercept_
- [ ] I think the starter file for exploring linearity in tables is super cool!  But I'm not sure you're doing the most productive thing with it. I think the directions should say something more like "plot the tables 1 at a time. Decide whether or not you think it represents a linear relationship. If it's linear, what is the rate of change? If you don't think it's linear, what tipped you off? try to imagine what it might look like. Then type plot-to-graph(table1) and check your prediction. I wouldn't worry about y-intercept here. The graphs are strange.
- [ ] Exploring linearity with graphs needs some work... graph 1 and 6 come up empty. And I would be hard pressed to find the slope or y-intercept from any of them. It's cool that there's such a range of graphs. Maybe you could cut the two missing graphs and use this for a bigger picture thinking activity on linear v non-linear, function or not, negative, positive or no slope?
- [ ] The workbook page linked as Identifying Slope and y-intercepts (Graphs) has 4 graphs and two are the same.

_Defining Linear Relationships_
I really like the visible / invisible tables.

- [ ] I know I previously was excited about this visual ![image](https://user-images.githubusercontent.com/66691020/102632262-78657b00-4114-11eb-9aaa-82b33c5b6f31.png) but, technically x isn't part of the slope and lots of students think it is. Could you rework it so the red box only goes around the twos?
- [ ] "If the line is perfectly flat the slope will be zero, making the term "invisible"! In the example below, a linear function with a slope of zero is shown with and without this term:"  Please work the word **horizontal** into this statement.

Jumping on a call with Brown students. Will try to look at the rest of the files linked in this section later.

**Comment by flannery-denny** [comment]
Linked files don't appear to be listed in the correct order in the materials section ![Uploading Screen Shot 2020-12-18 at 9.27.07 AM.png…]()

**Comment by schanzer** [comment]
@flannery-denny the duplicate images seem to be an artifact of the recent image anonymization code. The source files are not duplicated. Similarly, the order of materials links is in the build system - I can't control that. I posted in the slack remix channel earlier and Dorai said he'd look into it.

What do you mean " Exploring linearity in definitions starter file link doesn't work"? It loads for me, and running seems to work just fine.

**Comment by flannery-denny** [comment]
@schanzer just pushed a commit with feedback on the first linearity lesson.
Also, Linear, non-linear or bust needs a little work. I'm not sure that x=y^2 really counts as something with no pattern...
I also struggle with the spacing... ideally the choices (linear, nonlinear or bust) in the first column would align horizontally with the choices in the right column.

**Comment by flannery-denny** [comment]
> What do you mean " Exploring linearity in definitions starter file link doesn't work"? It loads for me, and running seems to work just fine.

Perhaps it works fine if you live somewhere with high speed internet, but, while I have enough bandwidth to load all of the other pyret files and zoom and share my screen with students in China and India and I am not able to load the pyret file...

The first time it just gave me an error message, but this evening the pyret spun spun and spun while I took a 10-minute break and when I came back it was still trying to load hoist the sail.

**Comment by schanzer** [comment]
Note to self: Don't embed the matching Desmos Activities in slides
