### ISSUE TITLE
Data Science Workbook Fixes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#344]
**Questions for Emmanuel to weigh in on / have a conversation about.**
- [ ] Do you think the new data set to box plot page goes in the workbook? Is so, where?
- [x] p.2 - It would probably be better if Billie were not the very last pet on the list.
- [x] Is there any reason why it's useful to have  and AnimalX/AnimalY?  Or do the same animals appear in all of the starter files and we predefine AnimalA/AnimalB in the Table Methods starter file instead of Animal X/Y? 

- [x] p27 reading function definitions refers animalA and animalB and the table methods starter file, which has animalX and animalY in it. Determine whether there is a good reason to not have everything use animal A and animalB. _(ES - no reason. We'd always used A and B, but you seem more drawn to X and Y? I say pick one and stick with it)._
- [x] p29 lookup fixed refers to animalx and animaly (change if we change the starter file).
- [x] p30 ibid
- [x] p33 & p34 are back to Animal A and animal B
- [x] should p 55 & 56 be switched? _(ES - no. 55 is a review of material covered in the previous lesson, whereas 56 in based on new content)_
- [x] p75 directions for teachers don't belong in workbook - also I made this in direct response to a request from teachers in the ds training to have a page like the one before without choices... _(ES - oops - that sentence should only be in the teacher-facing version! fixed)_
- [x] I think we should do both this page as it was and the page we talked about for r-value estimation. And the page where we first introduce r estimation should remind them about the range. _(ES - we discussed having one page that was scaffolded and one that was open-ended, and that's what we have now. I'm not sure what your proposal is exactly?)_

========
**Fixes for Emmanuel to tackle:**
- [x] p19 the page number appears on the last line for code. see if adjusting directions solves the problem or cut another table. If you cut one, leave 2 scatterplots. That contract is hardest for people so they could use the extra practice. _(ES - Good point. I'll replace the second histogram example with the second scatterplot example)_
- [x] p 73 - Creating a Scatter Plotmove directions above the graph - I was going to do this but there's a comment about a bug and I'm not sure what it means, so I'm leaving it to you.

========
**Quick fixes either of us can work on.**

- [ ] contracts pages would read better if the 3 lines dedicated to directions were broken up more intentionally
- [ ] is there a reason not to put r on 78? _(ES - great idea!)_
- [x] p38 extend notice and wonder table on mood generator page
- [x] p42 - grouped samples make more room for the last code to be written.
- [x] p84 threats to validity notes - staying FROM the shelter longer
- [x] p87 fake news #3 remove is
- [x] p88 remove 1 in directions or get directions on two rows
- [x] p23 - remove scaffolding for bc
- [x] p80 & 81 regression analysis. period repeatedly falls in the wrong place.
- [x] p62 Summarizing Columns in the Animals Data Set - be consistent about box plot v box-plot

========
**Focus for Flannery**
- [x] P.8 Booleans -  it should have a more opened question like the previous page on operators. "what can you conclude?" or "in your own words, describe what <= does" and a few of the other less math matching symbols like <>
- [x] p9 - under each line of code there were two lines. 
- [x] What bug do you see? - Type the buggy code into Pyret and write down what Pyret returns
- [x] p.14 - Exploring Displays - Fix strange line break for all "What do you think this display tells us?" - 
- [x] Plural / singular inconsistent on p.14 and p.15 Preferable to use box plot or box plots
- [x] p15 - linear regression box says scatter plot
- [x] p20 lookup questions - change the title of the table from animals table to something else
- [x] p26 -Defining Row Functions & Using Table Methods - Fix formatting
- [x] p41 make sure that the percentages listed are correct!
- [x] p46 - reorder the My Dataset page.
- [x] p51 - bigger toe on the right - get rid of s
- [x] p63. Interpreting Spread - Move the part about thousands of dollars to the interpretation section.
- [x] p64 - Identifying shape measures of spread -  directions grammar
- [x] p43 - Displaying Data. Should we add a line of code for this to match p.19 Data Displays? _(ES - yes!)_

**Comment by schanzer** [comment]
Closing, since this seems to be subsumed by #356
