### ISSUE TITLE
Fix to pyret algebra workbook

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#346]
- [x] p19 says wescheme
- [x] p20 # 4 code line is positioned strangely
- [x] p21 notes - second to last bullet says why and should say what
- [x] p23 #3 missing the word that
- [ ] p36 &43 does x-coordinate need to be a different font
- [x] p45 it is confusing that the function is and and the directions use AND is there another way to emphasize this?
- [x] p47 alice's restaurant - "an" item... add colons to bottom boxes.
- [ ] p51 not sure EXAMPLEs belong in all caps

**Comment by schanzer** [comment]
I don't think _x-coordinate_ needs to be in a different font.
And on page 51, the examples aren't in caps (perhaps you fixed this already?)

**Comment by flannery-denny** [comment]
The word EXAMPLEs appeared in the directions last I checked.
