### ISSUE TITLE
algebra pyret workbook fixes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#349]
- [x] Credits page says "Based	on	a	work	from www.BootstrapWorld.org."
- [x] page 2 "Notice"s - put s inside quotes.

- [x] page 7 - bullet Images - takes in a Number. Number is capitalized. String, image, etc. are not capitalized on this page. Number is not always capitalized on this page.
- [x] page 9 directions are missing a period.
- [x] page 9 column header says math expression instead of arithmetic expression.
- [x] page 10 column header says math expression instead of arithmetic expression.
- [x] page 12 capitalize circle of evaluation and code in directions.
- [x] page 13 capitalize code in directions.
- [x] page 15 capitalize code in directions.
- [x] page 17 capitalize code in directions.
- [x] page 17 - Every time I reread this page I wonder why the directions mention 3 shapes that only require inputting one dimension. It would be stronger if we suggested ellipse or rectangle.
- [x] page 19 capitalize code in directions.
- [x] page 20 capitalize code in directions... or uncapitalize code on the lines that ask for it.
- [x] page 12 3rd to last bullet 
- [x] missing "to" The	second	step	is	write	at	least	two	Examples"
- [x] consistency of what and which? "and	see	what	parts	are	changing	and	which parts aren't"
- [x] page 23 capitalize code in directions... or uncapitalize code on the lines that ask for it.
- [x] p.31 returns the 15% tip of that meal always sits poorly with me. Maybe returns the 15% tip for that meal
- [x] p.32 I also always have to read globogym twice. 	"Write a	function globo-gym that	takes	in	a	number	of	months	and	produces	the	cost	for	attending	the	gym	t**hat	manymonths**	when	there	is	a	$150	initiation	fee	and a monthly fee of $45/mo". Can we cut the bolded text?
- [x] p.33 	change to : Write	a	function	lawn-area	that	takes	in	a	length	and	width	of	a	rectangular lawn	and	returns	its area.
- [x] p41 #14 add entire to universe for last question
- [x] page 44 capitalize code in directions.
- [x] p 52 line-length - add comma in directions.
- [x] page 48 - Alice's Restaurant Explore - Is a circle of evaluation the right thing to ask for for the tax? could be contract and examples or COE and code? not sure just COE makes the most sense in the sequence of where we're at.
- [x] page 25 Mapping examples with circles of evaluation (also currently on page 29...) - I talked to Jen and finally understand how it should work - It belongs near GT and BC and we should scaffold GT on the page.  Could also go on page 24 with a scaffold for (3 scale prizestar)
- [x] *contracts page - num-sqr example might not be the most useful choice*. I haven't taught bootstrap in pyret yet, but that contract doesn't have a single comma in it ... as compared to contracts for pyret in DS... and, in wescheme, sqr is one of the only predefined functions I can think of that has a single input. *Suggest changing example to ellipse*. Done for wescheme.
--
- [x] p.26 & 27 I think the first appearance of the Design Recipe should have some scaffolding - Put an example on fast functions. rocket-height? seems to be the first Design Recipe?
- [x] p42 - Did you want to include Keeping Ninja Cat in the Game in the workbook? If so, seems to me it would go between Sam Intro and Safe-left?
- [x] page 46 add line break in piecewise functions notes so that 1) and 2) appear on separate lines?
- [x] p 53 It would be a HUGE IMPROVEMENT if this page subscripted the number in x1 y1, etc.
- [x] Top Down /Bottom Up - an elastic IS anchored
- [x] I'm not sure it's necessary to include 3 blank design recipes at the end. Maybe just one? As a teacher, if I were going to use this for other problems, I would probably find it more useful to distribute copies that I've already added directions to.
- [x] p 50 it looks like the second to last end is sitting on the line. Is there a way to change that?
- [x] The pdf I'm looking at says "processing math 100%" on page 7, 11, 15
- [x] update pyret contract page

**Comment by schanzer** [comment]
@flannery-denny I think we should make keeping-ninjacat-in-the-game an optional exercise. There's already been some negative transfer in PD for teachers who wrote `safe-top` and `safe-bottom`, who instinctively believe they NEED to write it in the game. I want to be conservative and give it a few more PDs to see what's going on before we add it.
