### ISSUE TITLE
Last algebra pyret workbook list 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#351]
- [x] Page titles - all caps or use function name? Seems almost all Word Problem pages have the function name lower-case in the title corresponding to how it will be written in code (works for me). BUT Challenges for Update Player has the function name in caps without a dash (p51)
- [x] Distance Formula (multiple representations) F should be capitalized
- [x] p 23 prize star "As the pink outline of a star of size 50" Better? Also looks like the code line for #3 is still too high.
- [x] p25 Did you want to add the code to gt?
- [x] p29 mapping circles of evaluation scaffold - boxes for drawing circles in could be significantly bigger given the space available on the page. (Flannery changed this but pdf printed funky - please check pdf and adjust if necessary).
- [x] Design Recipe spacing of second problem looks better on p.30 than the 3 pages that come after it.
- [x] p51 Update Player Challenge. All 4 prompts are sentences, which should be capitalized at the beginning and end with periods.
- [x] the HTML version of the pyret workbook has an extra a in the footnotes "Based on a work at www.BootstrapWorld.org"

**Comment by schanzer** [comment]
You already fixed the extra 'a'. The build system will not regenerate an HTML file unless the original source has changed, so you may want to do a force build just to start from a clean slate.
