### ISSUE TITLE
Oklahoma (Tracking Issue)

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#354]
### For the [Oklahoma Pathway](https://www.bootstrapworld.org/materials/fall2020/en-us/courses/ok)

Overview:
Oklahoma wants integrated math/CS lessons for 8th and 9th grade that directly complement their existing framework while covering 50% of the CS standards for 8th grade and 50% of the CS standards for 9th.  

[Oklahoma CS Standards Alignment](https://docs.google.com/document/d/1Xa6VeTsOIhYQROYZOcdOkWxv0aSvMGaBYL0t-EcCY8E/edit?usp=sharing)

Lessons in the Remix have been aligned to where they fit in the OK Framework for pre-algebra.

[Oklahoma Math/CS Resources](https://docs.google.com/document/d/1hmc0PgdR4hSx1SzULGhBL0tWACsJ2UYIU7rpFTeBwGY/edit?usp=sharing)

Game integration is treated as an extension project in the scope of the OK Framework.   

[OKMath Framework for Pre-algebra](http://okmathframework.pbworks.com/w/page/118991889/Pre-Algebra%20Learning%20Progression%20(v2))
[OKMath Framework for Algebra I](http://okmathframework.pbworks.com/w/page/118991895/Algebra%201%20Learning%20Progression%20(v2))
[OK CS Standards for grades 6-8](https://sde.ok.gov/sites/default/files/documents/files/OAS-CS%20-%206-8.pdf)
[OK CS Standards for grades 9-12](https://sde.ok.gov/sites/default/files/documents/files/OAS-CS%20-%20HS.pdf)

Needs (from teachers and from OK team):

- More practice activities, worksheets, or visual/kinesthetic activities to help engage more learners - including accelerated and special ed
- More CS-focused lessons that reach the 9th grade CS standards (see OK CS Standards for grades 9-12, Level 1)
- A clear path for the data science material that can fit into a 3-4 week window
- Additional practice for design recipe practice - geometry formulas, slope calculations, etc
- Probability lessons, if possible

**Comment by schanzer** [comment]
Sequence:

- Circles and Flags
- Word Problems and Defining Functions
- Tables and Charts

**Comment by flannery-denny** [comment]
Could you please give me access to Oklahoma Math/CS Resources

**Comment by schanzer** [comment]
Done

**Comment by kfisler** [comment]
Did you give Flannery access to the entire OK directory? I had given her
access just to the curricular materials directory. I believe the entire
directory has some more private files related to the grant (potentially
including some salary info). Does she need more than the curricular
materials?

**Comment by schanzer** [comment]
Pizza dough was added in e753ed809

**Comment by schanzer** [comment]
With only one remaining item (which has [it's own issue](https://github.com/bootstrapworld/curriculum/issues/396))
