### ISSUE TITLE
DS Workbook list 2

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#356]
- [x] p1 Intro Notes remove comma in first bullet and before the and in second bullet.
- [x] p4 The solutions given are inconsistent in font. Maybe they should all be bold or italicized? 
- [x] p6 Intro to programming notes. "Jen and Ed" isn't formatted like the others.
- [x] p8 Should Number, String, Boolean by bolded in the questions?
- [x] p9 Catching Bugs isn't vertically centered in the black stripe. Also, Flannery forgot to adjust the directions when she adjusted the activity.
- [x] p10 Some of the bolded words are capitalized. Some aren't. Should they be consistent? _(ES - Types are capitalized, key words in the question are bolded. Some key words happen to be types)_
- [x] p13 Plotting & displaying data notes - Barcharts - last bullet should say shown not show
- [x] p17 Data Displays and Lookups notes. The second set of examples used probably shouldn't repeat row-n(0)
- [x] p23 Remove scaffolding on bc (I know this is a repeat from previous list) (ES - what scaffolding? it's all gone.)
- [x] p29 & 30 - Confirming that it's ok to say that Animal A and Animal B are defined as Felix and Midnight, respectively. _(ES - no, we need to make it clear that they are rows. I've updated the wording to match.)_
- [x] p33 & p34 - I would suggest pairing is-female with is-dog and moving is-old to the following page.
- [x] p35 - probably want to change this code to something else t.order-by("gendr", false)
- [x] p41 - sampling and inference. inconsistently uses small-sample and large-sample and tiny-sample and small-sample
- [x] p42 - last box needs a longer line for writing code - I'd suggest putting it as fit-bit under the pretyped code. _(ES - switched to landscape, so this should add more room for every line)_
~depending on the goal of the last two questions, we may want to ask that one column be quantitative and one column be qualitative.~ _(ES - let's leave this open for teachers to specify, if they want)_
- [x] p47 Do you want to remind them what a subset is - refer them back to another page where they worked with subsets from the animals table. (ES - this should have said "grouped sample". Fixed!)
- [x] p48 & 49. Every time I look at these pages i have to do a double take about whether the words "table and" are the answer that has been pre-filled in for the students.  Perhaps add some more spaces around those words to distinguish them from the fitbits.?
- [x] p51 - Might be worth acknowledging that finding the right bin size isn't necessarily something kids should be certain about at the start and might take a little trial and error.
- [x] p57 - I think the directions would read more clearly they started with Make a histogram, showing the distribution of pounds from the shelter. The other column in the animals data set I'd like to summarize by making a histogram is ______. Alternatively, add a spot for them to write the code for the column that you've assigned them to make to engage them with it. As it currently reads, I think many kids won't bother to make the first histogram.
- [x] p67 - Seems this matching exercise belongs before the whats on your mind page.
~Did you decide not to include data set to box plot in the workbook?~ _(ES - not in this iteration)_
- [x] p68 - you could sentences are missing periods. 
- [x] p69 - Insert a vspace before #2. 
~p73 - I imagined the table and graph would fall between #1 and #2.~  _(ES - that would make it more difficult for students to draw connections between the two)_
- [x] p74 - want to include a reminder about r in the directions that -1 is a strong negative correlation 0 is no correlation, etc.
- [x] p76- I think this "a subset of extension of my data" (which appears several times) is supposed to say something else 
- [x] p77 - the computing relationships notes come after r is introduced in the workbook (p 74) - Do you want to move the notes on r up to the previous notes section and just leave this section to talk about regression and slope?
- [x] p78 - you wanted to add r to this? maybe you could give the challenge of asking them to approximate the slope of the predictor line they drew?
- [x] p81 - Not sure what you think about this, but it would support teachers in supporting students if the pages like this that are about their dataset started with. My dataset is _______________ so that as teachers are viewing googledocs or workbooks they know what the student is looking at.
- [x] p.83 Similarly, this page would benefit from Our Case Study is:_____________.
- [x] p.83 There is a "." before R that doesn't belong there. 
- [x] p.84 Rather than referring to the mean and the median in #3, I would say 7 out of 10 animals took at least 7 weeks to be adopted.
- [x] p.88 There is a "." before R that doesn't belong there.
- [x] p95 & 96 Choose an example for the contracts page that includes at least one comma in the contract.

**Comment by flannery-denny** [comment]
p29 & 30 - Confirming that it's ok to say that Animal A and Animal B are defined as Felix and Midnight, respectively. (ES - absolutely!)
To be clear, the question here was about technical language. making sure that the wording doesn't need to define them as the rows that correspond to the animals with those names.

**Comment by schanzer** [comment]
@flannery-denny ah, I see. No, we need to explain that these are the rows. We didn't do this in the past, and it let to a lot of misconceptions.
