### ISSUE TITLE
Fixes from comparing algebra workbook & solutions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#359]
For Emmanuel to weigh in on or resolve:
- [ ] p56 word problem distance - solution is illegible because it lands on other text - is it possible to override the design recipe formatting for a problem to space this page out? _(ES - working on it. Need Dorai's help)_
- [x] p25 mapping examples w coe - add code. (it's a pdf & FD doesn't have access.)
- [x] p41 Inequalities notes - inequalities in COE do not match the inequalities in the notes. Not sure what to do since workbook has already gone to printer. _(ES - match the stuff that's printed)_ **(FD - The stuff that's printed is wrong.)**
- [x] p42 Inequalities launch - Solutions page has 8 items in the table. The student workbook pdf you sent me has 6 items in the table, but the fragments on my computer's student workbook have 7 or 8 items, depending on whether it's the wescheme fragment or the pyret fragment. Given that things have gone to the printer, do you want me to cut the material from the solutions or include the material in the student workbooks? _(ES - definitely.)_ **(see comment below about the complexities of this)**

- [x] p11 - matching circles of eval and alg expression - the pdf of the student workbook you sent me is missing arithmetic expressions. the pdf on my computer shows empty circles of evaluation... the ascii file looks fine... something's getting stuck. _(ES - That's weird - the arithmetic renders fine on my machine. Let's set up a zoom to investigate?)_
- [x] p10, p16,  fyi - solutions says processing math _(ES - try now? I added another second to the javascript delay when building, and spot checks on these pages seem better)_ **Adding that second to javascript delay seems to have solved the first two bullets**
- [x] p16 solutions - why does code say sqrt 9 for all of the problems? ascii file looks right... _(ES - ascii file was buggy.)_
- [x] 15 - arith to coe - all code is the same on the workbook page, but ascii file looks right to FD...
- [x] p45 printed "&amp;" instead of & in number 4. _(ES - that's not what prints for me. I don't see the quotes)_
- [x] p54 distance between (0,2) and (4,5) - circle of evaluation isn't showing. code is all using xs. should use ys for one parentheses.
- [X] p55 - Distance  Multiple Representations - add solution
-  [x] I updated the examples on the contracts pages, but it meant that the directions took one more line in the pyret version. Please confirm that contracts don't run onto page numbers)

There are lots of pages in the solutions book with no additional guidance for teachers. What is the guiding principal as to when you offer "sample responses" for open-ended things and when you don't?

- [x] p22 - Defining Values Explore - should we add circles of eval for these? _(ES - no.)_

- [x] p49 - Alice's restaurant explore - Should we add sample response for #4 ? _(ES - no.)_

____________________
Flannery's list:

- [x] p52 - Challenges for update player - Should we add sample response? _(ES - definitely.)_

- [x] p3 - Reverse Engineer a Videogame - add sample response

- [x] p4 - Coordinates - add sample response

- [x] Should we populate the contracts pages with examples? _(ES - definitely.)_

- [x] p17 update solutions page!

- [x] p19 Composing image functions - insert vspace

- [x] p20 - Function Composition Practice - is missing solutions
- [x] p20 - Function Composition Practice - add Vspace after fitbit for problem 1.

- [x] p22 - check that defining values - explore says "A solid,	red	triangle appears" in wescheme version

- [x] p23 solutions shift to pink outline star

- [x] p42 - Inequalities launch - space solutions better

- [x] examples on contract pages don't match.

**Comment by flannery-denny** [comment]
The examples removed from p.42 Boolean intro / Inequalities launch to match the pdf are:
|7) `(string-length "bat")` will be @fitb{4ex}{3}
|8) `(string=? "dog" "cat")` will be @fitb{4ex}{false}

**Comment by flannery-denny** [comment]
@schanzer  The problem with removing those examples is that there is a question on the page that asks students:

	What	does	the	function	(string=?)	do?

Also problematic, directions say "Write the	contract	for the functions	that	produce	Booleans you’ve seen	above	in	your	Contracts	page."  Which I now know shouldn't be asked for the pyret version... 

Should I delete it from the pyret version because it doesn't belong there or leave it because pyret version workbooks have already been printed?

**Comment by schanzer** [comment]
@flannery-denny got it - thanks for the explanation! I've got what I _think_ is a good solution. Curious to know what you think!

**Comment by schanzer** [comment]
I'm closing this issue, since the only remaining item now has its own (#363).
