### ISSUE TITLE
Defining Values

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#36]
**`define` does NOT require a function call. For example `(define x 4)`**

Is it really worth asking how it's similar to or different from a function? The depth of understanding required for a student to answer _either_ of those questions seems pretty steep. Why not just come out and say "it may look like a function because of the parens, but it's not and here's why"

**We never actually show a definition!**
Not in the lesson, and not in the slides. Or are the slides not done?

**Comment by BootstrapJen** [comment]
Removed the erroneous response.  However, I do still think it's useful to have a conversation with students about define vs function, rather than just telling them.  

Yes, we do show them a definition, it's on the first workbook page during the Explore.

Ed is in charge of Slides.

**Comment by edcamposjr22** [comment]
See my comment on the Slides issue.
