### ISSUE TITLE
bitmap-url in pyret should be image-url?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#361]
I'm working on writing sample code for the bootstrap algebra contracts page and I testing it in pyret. 

- I've tried loading several different libraries and *bitmap-url* continues to be *unbound*.
- image-url("https://www.bootstrapworld.org/images/icon.png") works fine.
- I think that means I have to change *bitmap-url* to *image-url* in the pyret algebra contracts page.
- Dorai says maybe, but the cpo source lists bitmap-url alongside image-url

**Comment by schanzer** [comment]
Fixed by bac9fdb15
