### ISSUE TITLE
Fixes to Algebra Pyret Lesson Plan Materials lists 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#368]
**Flannery**
- [x] Definining Functions - Fix column width of "Matching Examples and Function Definitions" from 
______________
**Emmanuel**
- [x] Not convinced it makes sense to have these links on every lesson... For a textbook-like version of materials similar to these, you may wish to see the prior unit-based version. _(ES - for now we need them, since a lot of teachers miss our old stuff. Hopefully in a year we can take them out.)_
- [x] making game images - Is there a linking images guide for pyret?
- [x] saving game images - Is there a saving images guide for pyret?
- [x] Closing on Reverse Engineering a Videogame lesson doesn't make sense. _(ES - removed)_
- [x] collisions - Unless I'm missing something, the last sentence of this lesson with a link to manhattan distance should be cut. _(ES - actually, the last sentence is very useful! It shows how to compute distance for images that are very tall or wide)_
- [x] Character animation - Should the supplemental lesson on 2-D animation be linked at the top? _(ES - I don't think so. It doesn't really fit as a material or preparation, and it's not a supplement to the lesson as much as it is a whole new lesson)_
- [x] Order of operations materials list is very long - are you ok with this formatting? or should we make some of them @links... instead of @exerciselinks
- [x] Order of operations - Can we get rid of "this graphic organizer" - the lesson plan really doesn't assign its use to a problem. If you want to keep it, I think we need to offer better directions... either in the lesson plan or on the worksheet.
- [x] building teacher resources: algebra-pyret → resources → index.adoc WARNING: Page resources: @link refers to nonexistent file BuggyRecipes/pages - Flannery can't find the resources file...
- [x] WARNING: Lesson plan lessons/alg-function-composition: No standards specified
- [x] These links don't work - Optional: cutouts of the Cat, Dog, and Ruby from the NinjaCat game. _(ES - you seem to have a lot of broken links that I don't. We may need to schedule a zoom to see what's going on)_
- [x] Order of operations - Optional includes link to graphic organizer that says PEMDAS & should say Evaluate or Order of Operations _(ES- fixed)_
- [x] Flags of the World Resource link is broken (and #223 includes a bunch of updates needed for it...)  _(ES - you seem to have a lot of broken links that I don't. We may need to schedule a zoom to see what's going on)_
- [x] Solving Word Problems - Should additional practice word problems be reformatted to print 2 to a page? _(ES - no)_

**Making Game Images**
- [x] Links to Linking Images guide are broken _(ES - you seem to have a lot of broken links that I don't. We may need to schedule a zoom to see what's going on)_
- [x] Links to saving images guide are broken _(ES - you seem to have a lot of broken links that I don't. We may need to schedule a zoom to see what's going on)_
- [x] Shouldn't materials also require their completed planning materials from the workbook and google draw? _(ES - yes)_

- [x] Should supplemental resources at the top list only the Desmos, Geogebra, etc, files referred to in the lesson plan or all of them, regardless of whether or not they're listed in the lesson? **(ES - delete them)**
- [x] Both the Rocket-height and Sam the Butterfly pyret code work, but say big bang in the window that opens when you run them.
- [x] In Converting Circles of Evaluation with Booleans to Code "string-length" doesn't quite fit in the COE _(ES - can't fix without a monumental amount of work)_
- [x] Based on our conversations about distance, I'm not convinced that we want all of these links ... either way, they should be reordered and the first one is about line-length not absolute value _(ES - yeah, cut 'em)_
- [x] Do you want the contracts page listed if it's referenced? _(ES - no)_
- [x] Do you want some supplemental materials to repeat from one lesson to another? _(ES -only if they're good )_
- [x] Should additional exercises at the bottom just be bootstrap pages? _(ES-no)

- [x] If there are no additional exercises listed, can I cut that section from the lesson plan or should I flag the lessons that we need to populate additional exercises for? _(ES - cut it)
- [x] There are several lesson plans with links to wikipedia pages. When I click them I am met with a nearly full-screen fundraising pitch. Confirming we still want to be sending people to wikipedia. _(ES - if you can find better, replace!)_

Additional Materials
- [x] List all starter files in the materials list
- [x] Number inside video games - Change name of boat coordinate game to submarine coordinate game in lesson plan
- [x] Order of operations there's a double negative "doesn't not" that needs to be fixed.
**Restating the Problem**
- [x] Some of the supplemental resources repeat. Do we want that?
- [x] There are no Additional Exercises. Can we cut that section? Do you want to populate it with something?

**Distance Formula**
- [x] Rename multiple representations file to include points and make it consistent in the lesson.

**Simple Inequalities**
- [x] Add the word code to the lines in Converting Circles of Evaluation with Booleans to Code - _not going to mess with this kind of coding_
- [x] Fix numbering on keeping ninjacat in the game (missing 3)
**Compound Inequalities
- [x] Fix BOUNDARY Detection title spelling

___

- [x] Alg-coordinates - Do the cutouts feature somewhere in the lesson plan?
- [x] domain & range - Identifying Parts of Expressions (2) - fix column width

**Comment by schanzer** [comment]
Now that Ed's links to quizziz and desmos activities have their own issue, I'm closing this one since everything else is complete
