### ISSUE TITLE
Pyret ninjacat game linked in lesson doesn't match workbook or wescheme game. 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#369]
- [ ] The linked pyret ninjacat game has a slow moving cat and a gold coin...

**Comment by schanzer** [comment]
JFC WTF

**Comment by schanzer** [comment]
Rewrote the entire NinjaCat file from scratch, and now it does the right thing. Will close when I change the URL in the lesson plan

**Comment by schanzer** [comment]
closed by 3054d58ed
