### ISSUE TITLE
List all prerequisites for a lesson, instead of the immediately preceding one

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#371]
It looks to me like the prerequisites list is populated by the previous lesson rather than by the lessons required for making sense of a given lesson.  We know that lots of teachers don't do all of the lessons. Thinking it would best support them if we actually made lists here of the 2 or 3 or 10 lessons? you actually needed to do before engaging with a particular lesson.

**Comment by schanzer** [comment]
@flannery-denny I think there's some background context you should be aware of, which might influence your thoughts on whether or not to keep this issue open.

Every lesson, as you know, lists one or more dependencies in its asciidoc file. During the build process, this allows us to build a _dependency graph_, which is generated but currently not exposed on our website.  The only hint of this graph is in the lesson plans themselves, which merely list their _immediate dependencies_: if lesson X depends on lessons A and F, it will list only A and F -- even if F itself depends on B and C.  The thinking is that when a teacher is looking at a lesson they're about to teach, what they care about most is whether they've recently taught the lessons required to get there.

"Did I teach what I needed to start this?" is a very different question than "What do I need to cover to get to _this_ point?" The current implementation is designed to answer the first question. I think the spirit of the entire issue you opened, however, is more about the second.

Our longer-term plan is to expose the **entire** dependency graph, showing an icon for every single lesson and allowing the user to click on a lesson and see the entire transitive dependency tree highlighted. This is impractical to do at the lesson level (see comment above about this list being long), and also not as useful when a teacher is preparing to teach lesson X. However, from a planning perspective it would be very useful to see the entire pathway laid out, with the ability to click a "destination lesson" and see only the lesson required to get there.

@ds26gte has already built the infrastructure to do this: the data is there! What's missing is the user interface, which is probably not something we can prioritize until a lot of our other issues are closed. 

After reading this, let me know if you still feel that you want to keep this issue open?

**Comment by flannery-denny** [comment]
Glad to know the infrastructure exists and the work doesn't have to be
redone! I'm happy to close this git issue if there's another git issue
somewhere that keeps the goal of creating a lesson pathway flow chart (or
clickable interactive version thereof) on our longterm to do list.

**Comment by flannery-denny** [comment]
Also, perhaps, in the lesson plan it should say something like "This lesson follows..." instead of "prerequisites"

**Comment by schanzer** [comment]
New issue created as #384

**Comment by schanzer** [comment]
@flannery-denny I suppose we could do that, but that kind of breaks down if we have more than one lesson listed as a prerequisite. The term “follow” is also misleading, as there may be several lessons that could follow applying functions, without there having to be a strict order.

I think teachers are pretty familiar with the “prerequisites“ term, no?

**Comment by flannery-denny** [comment]
I'm not attached to what word we use. It's just a matter of precision
(which I know you like to attend to and is exactly why you shot down the
idea "follow"). If there are 10 prerequisites and we are listing only one
of them in a category with a plural title it leads me to believe there is
only one.

**Comment by schanzer** [comment]
How about parens around the s?
