### ISSUE TITLE
Re-examine Order of operations lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#378]
- [x] Expression --> COE --> Code sequencing.  I know we can't change it NOW, but I am still not happy with the three-column page coming last. _(FD - Sure! I've only ever used three column materials with students and I'd be ok with redesigning this so that all materials in the workbook are 3 column unless they're matching... and that the 2 column materials either go away or are available for download for teachers looking for slower-paced scaffolding
- [x] Order of operations I want to talk about this section of the lesson at some point "Circles of Evaluation help us get the correct answer"

**Comment by schanzer** [comment]
@flannery-denny I know we spoke about this lesson in the call before last. What else remains to close this issue?
