### ISSUE TITLE
Final algebra lesson plan fixes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#386]
- [x] subscript x1 and x2 in distance and collision lessons
- [x] Add these pages in to Order of operations lesson: 9, 10, 11, 12 14
- [x] thought we were deleting manhattan distance...

In case we want it back, this is what I took out of the collision lesson.
`== Additional Exercises:
For characters that are much taller than they are wide (or wider than they are tall!), using the radius to determine collision won't work very well. Have students compute the @link{https://en.wikipedia.org/wiki/Taxicab_geometry, Manhattan Distance} to take the more-rectangular dimensions of their characters.`

**Comment by schanzer** [comment]
oh! OK, sure go ahead and remove it
