### ISSUE TITLE
Solutions should indicate which parts are the ones students filled in

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#387]

**Comment by schanzer** [comment]
I'm not even sure this is feasible. What would this look like for CoE?

**Comment by flannery-denny** [comment]
In the solutions book for every page except or these ones that are autogenerated _solutions are italicized_ or **BOLDED AND CAPITALIZED IN MATCHING ACTIVITIES**
As a teacher looking at the solution book, I want to be clued as to which information was preprovided to my students so that I can easily find the part that they are sharing back to me if we're having a conversation about it. 

I have an idea. Don't know if it will work.  Let me see if I can figure it out.

**Comment by flannery-denny** [comment]
I figured out that you can define an expression with bolded numbers, but they bold in the original expression and the COE so it's not very useful...

**Comment by flannery-denny** [comment]
@schanzer There are only 3 files for which this is an issue.
Completing partial code from circles of evaluation - if we could make it so the solution page of this file was not autogenerated, I could definitely write the solution code in mathjax in the ascii doc. It would look like this.
`@math{(+ \mathbf{ 16 } \; (* 6 \quad \mathbf{-3}))}`

**Comment by schanzer** [comment]
Unfortunately, this is simply not possible - unless we want to do everything by hand, which quickly turns into a maintenance nightmare. We can talk more on out call in a few min.

**Comment by schanzer** [comment]
Subsumed by #388
