### ISSUE TITLE
Final DS Lesson plan fixes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#389]
**Introduction**

Fix: 
> Turn to page Categorical or Quantitative? (Page 3), and answer the questions 1-5
> 
> Sometimes it can be tricky to figure out if data is categorical or quantitative, because it depends on how that data is being used!
> 
> On Questions and Column Descriptions (Page 4) in your Student Workbook, fill in the blanks for questions 8-13.

- [x] Page 4 isn't numbered. Not sure whether there's a reason that you wanted to direct students toward particular questions... whether perhaps all of these directions actually refer to page 3?  
- [x] Please change peardeck accordingly
- [x] fix directions in defining table functions around lookup-fixed to better match workbook

**Comment by schanzer** [comment]
@flannery-denny I'm removing the link warnings, since they can be safely ignored. Due to the way the build system works (`pages` directories first, then lessons, then workbook), not all files are actually generated at the time where the link checking occurs.

**Comment by schanzer** [comment]
@flannery-denny just checking if you are fixing this as part of your slide work?

**Comment by flannery-denny** [comment]
@schanzer Nope. Definitely leaving aligning Table Functions slides/lessons/workbook to you!
