### ISSUE TITLE
Algebra peardecks

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#391]
**Compound Inequalities**

- [x] Slide 2 This is not an inequality "Are the cookies finished baking?       timer = 0?" (ES - why not?) **FD - It looks like a statement of equality rather than INequality to me. Maybe I'm missing that it's code that's testing whether or not the two items are equal? rather than stating that they're equal?**
- [x] Slide 6 - "As a group, decide when you want to compare DR notes."  Not sure what this is referring to. (ES - removed)
- [x] Slide 6 - I might be wrong, but I think this is the first slide that uses driver navigator terminology & it assumes that the students already know what those words mean.  I think the only other slide when this terminology is used is slide 3 of piecewise functions. (ES - somewhat mitigated)

**Defining Functions**
- [x] If [this link](https://teacher.desmos.com/activitybuilder/custom/5cdcaea0b4b8576069fdca4f) is in the additional practice slide we should probably add it to the lesson plan

**Order of Operations**
- [x] Not sure why slides 7 & 8 get interactions windows . Just in case? or did you mean to offer directions?

**Making Game Images**
- [x] I'm not able to remix on slide 5 and then I'm not able to load slide 8.
- [x] Images on slide 8 are quite small.  Perhaps make this two slides where the first doesn't have an interactions window & ends with let's try it out... and the next has the little version and the interactions window.
- [x] Assume you meant to ditch slide 9

**Comment by schanzer** [comment]
@flannery-denny are you sure about slides 7+8 in OoO? I just checked, and they definitely load the definitions area and the toolbar.

I ditched slide 9 from Making Game Images, and spread slide 8 out across three slides. Better?

All of the "can't remix, doesn't load" issues are probably related to Chrome. Can you try one or two of them in Firefox?

**Comment by flannery-denny** [comment]
@schanzer There aren't any directions in OoO slides 7+8 that require the use of the definitions area and the toolbar. I was confirming that it's intentional to include them and not ask people to engage with it.

**Comment by schanzer** [comment]
Correct - we actually used to just show the interactions area for slides like this, but teachers found it harder to orient. In this situation, consistency seems to trump screen-area efficiency.
