### ISSUE TITLE
Not urgent - Is it possible to have subfolders in pyret?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#393]
Educators end up with lots of files in Pyret and, while we can make subfolders in our googledrives for how they're stored, when we access our programs in Pyret the subfolders disappear and we're back to one really long list of every pyret file we've ever accessed and saved.  When facilitating, this slows down finding the resources we need to support students and other educators. I know that Jen and I both struggle with this. Could the infrastructure be adjusted to allow for this?

**Comment by schanzer** [comment]
Filed as https://github.com/brownplt/code.pyret.org/issues/346
