### ISSUE TITLE
Design Recipe practices for geometry formulas, slope calculations, etc

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#394]
For Oklahoma (see #354)

- [x] Waiting on #401

- [x] waiting on #407 

- [x] Convert prisms starter file to wescheme

- [x] convert [slide deck](https://docs.google.com/presentation/d/1uiEYy7o2Gm96HhThLvr1RLp5b7d1HaEK9qHZ4dLOq7k/edit?usp=sharing) to wescheme

**Comment by flannery-denny** [comment]
see page 32, 35 & 36 of Algebra workbook.

**Comment by flannery-denny** [comment]
@schanzer [This googledoc](https://docs.google.com/document/d/1swnDvNSMeSSjhQdB3oEafjvhp6kSreVHYIu9dLoBrRM/edit?usp=sharing) includes all of the design recipe problems currently available in the OK workbook and a bunch of problems I wrote today **(they're the bulleted ones in each section).**  

- If you think that this is enough and they're good to go, I will put them in ascii docs for the January release and integrate them with the other DR problems for the June release. 
- If you think we need more for any particular section, I'm happy to add them. 
- If you think any of them are too complicated, let me know. 
- Open to any and all feedback. Figure it's easier to sort out the problems before I start messing with bigger systemic stuff.

**Comment by schanzer** [comment]
I _love_ this - especially the negative slope problems. I'm really happy with all of it, including the progression. 

Just a reminder that these will have to be added as _exercises_ in the Spring2021 branch. We can add some or all of the to the Fall 2021 branch.

**Comment by flannery-denny** [comment]
Possible coding activity to reinforce surface area of a prism. [https://code.pyret.org/editor#share=1qU_aWQgfHLX5vRsFiFPK8JxUUXXAu1Ha&v=8c4da7d](https://code.pyret.org/editor#share=1qU_aWQgfHLX5vRsFiFPK8JxUUXXAu1Ha&v=8c4da7d)
