### ISSUE TITLE
Extra worksheets/practice/kinesthetic

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#395]
More practice activities, worksheets, or visual/kinesthetic activities to help engage more learners - including accelerated and special ed

- [x] more 3 column order of operations practice with integers and exponents and brackets

- [x] WAAAAY more card-sorting activities
(For Oklahoma #354)
- [x] play dough histograms and boxplots lesson (Emmanuel will do this)
- [x] more flags!

scatterplots
- [x] sort by direction 
- [x] sort by strength

Visualizing the shape of data
- [x] identifying form: skewed left / skewed right / symmetric (boxplots, histograms)

- [x] Connect 5 number summary to box-whisker plot image and terminology

- [x] something like [mellow yellow](https://learningcenter.dynamicgeometry.com/AlgebraActivities.htm)? [desmos](https://teacher.desmos.com/activitybuilder/custom/58797d35d81a612605304b1f?collections=5da6476150c0c36a0caf8ffb)
- [x] showercurtain graph seems a little too prep intensive, but maybe it can be adapted somehow? Convert to peardeck dragging activity in linearity lesson. [Interactive Peardeck Function activity](https://docs.google.com/presentation/d/1IW5uMg491e33Av_XdGSivsAy28S9QSVivEYonpjTeF8/edit?usp=sharing)

**Comment by flannery-denny** [comment]
@schanzer For desmos activities involving code, is it ok if they're just typed into desmos [like this](https://teacher.desmos.com/activitybuilder/custom/5fc536c0e2f06d0cd3992c68) or do I need to take screenshots so that colors match?

**Comment by flannery-denny** [comment]
@schanzer does this kind of code read ok to you in desmos? [https://teacher.desmos.com/activitybuilder/custom/5fc53aeef328540d3ad2123c](https://teacher.desmos.com/activitybuilder/custom/5fc53aeef328540d3ad2123c)

**Comment by flannery-denny** [comment]
@schanzer and another [https://teacher.desmos.com/activitybuilder/custom/5fc5415a24be4c0d054d73b2](https://teacher.desmos.com/activitybuilder/custom/5fc5415a24be4c0d054d73b2)

**Comment by schanzer** [comment]
@flannery-denny Totally fine to type code into desmos, but I worry about the text breaking out of the box.
And the flag code reads great to me. :)

**Comment by flannery-denny** [comment]
@schanzer I tried doing screenshots for the code that didn't fit in the box neatly.  Looks pretty small to me. Do you think it's workable... or should I not make card sort activities that need code this long? [https://teacher.desmos.com/activitybuilder/custom/5fc536c0e2f06d0cd3992c68](https://teacher.desmos.com/activitybuilder/custom/5fc536c0e2f06d0cd3992c68)

**Comment by flannery-denny** [comment]
- [Matching code to images](https://teacher.desmos.com/activitybuilder/custom/5fc90a1937b6430d836b67e7)
- [Matching code to images using overlay and put-image](https://teacher.desmos.com/activitybuilder/custom/5fc90f1289c78e0d2a5bccfc)
add these to DS-Pyret Intro and Alg-Flags?

Add to tables-graphs-functions lessons
- [Linear Function card sorting collection (10)](https://teacher.desmos.com/collection/5fbe7484d81cab0ca7a8bcfb)
- [Not just linear card sort collection (2)](https://teacher.desmos.com/collection/5fc266e34666f00d51454bc8)

**Comment by schanzer** [comment]
@flannery-denny has MORE than covered the goal of this issue as it applies to the Jan 1 milestone. Instead of closing it, I'm going to simply remove it from the milestone so that she can keep tracking the Desmos todo list.

**Comment by flannery-denny** [comment]
@schanzer Do you think this could work as an optional stand alone deck or do you want to incorporate it into linearity?
[interactive peardeck function activity](https://docs.google.com/presentation/d/1IW5uMg491e33Av_XdGSivsAy28S9QSVivEYonpjTeF8/edit?usp=sharing)

apologies if I already messaged you about this. Thought I had, but I'm not seeing it so decided I just meant to ;)
