### ISSUE TITLE
print-images teachpack/library

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#401]
Given a list of images....
1.  Rotate to maximize height
2. Sort by height
3. Build a row of them until a max length, then another row, then another...
4. Glue rows together and produce a single, printable image

**Comment by schanzer** [comment]
@flannery-denny try this file: https://code.pyret.org/editor#share=1sr2IfQY_HqL84sPeZXfwVMifpW6ErXSI&v=8c4da7d

It exposes a function called `print-imgs`, which I believe does what you want. If it's good to go, you can make a new Pyret file and add `include shared-gdrive("Print Images Library", "1sr2IfQY_HqL84sPeZXfwVMifpW6ErXSI") as P` at the top. This will allow the new file to use `print-imgs`

**Comment by flannery-denny** [comment]
Thanks! It does a good job of sorting them by height... but it would be
really hard to cut out what it returns. I updated the file to include 6
images from which a student could build a rectangular prism so that you can
see what it looks like. I think there needs to be a space between each side
by side image and a vertical space between the lines of images.

https://code.pyret.org/editor#share=1LQSvpmGPezwtR4heNusRbU_-16NsIFwj&v=8c4da7d

**Comment by flannery-denny** [comment]
It would be infinitely cooler if the rectangles could have a text layer on
them where they were labeled with their length, width and area...

**Comment by schanzer** [comment]
Added a space above and below. If you want to add more, change the size of `padding` at the top of the file.

Unfortunately, the the only shapes for which we can compute that are rectangles.

**Comment by flannery-denny** [comment]
@schanzer I upped the spacers to 10. I think students will be able to cut between shapes now... But, I can't figure out how to add the space between the first row and the second row. [updated code](https://code.pyret.org/editor#share=1k14ArC40wvOnOHz_w0m3mOoinVPv6D-K&v=8c4da7d)

**Comment by schanzer** [comment]
See line 28? Where we add “beside“ and the padding on both sides of the image? We need to do the same thing with “above“. You can do that now yourself, or I can get to it a little bit later this afternoon.

**Comment by flannery-denny** [comment]
@schanzer Thanks! I got your first message about how to fix it and figured it out before I realized that you'd done it... 
Been thinking about how to label the print-outs.  Realizing I could have students write it themselves.  Wish I could wrap text to two lines... Like one of these options better as a suggestion to students? 

[https://code.pyret.org/editor#share=1k14ArC40wvOnOHz_w0m3mOoinVPv6D-K&v=8c4da7d](https://code.pyret.org/editor#share=1k14ArC40wvOnOHz_w0m3mOoinVPv6D-K&v=8c4da7d)

**Comment by flannery-denny** [comment]
@schanzer I made a copy of your new code and added it to the shared google folder curriculum/math/algebra3.1/prism.
I made this starter file.  [https://code.pyret.org/editor#share=1qU_aWQgfHLX5vRsFiFPK8JxUUXXAu1Ha&v=8c4da7d](https://code.pyret.org/editor#share=1qU_aWQgfHLX5vRsFiFPK8JxUUXXAu1Ha&v=8c4da7d)

Three questions:

- [ ] Why do I get this error message? I also get it when I include the link you originally suggested including...
![Screen Shot 2020-10-24 at 2 03 58 PM](https://user-images.githubusercontent.com/66691020/97091528-6ed6ff80-160a-11eb-994d-c6d8e654a17f.png)
- [ ] How much of this file should I be converting to an activity sheet?
- [ ] Do you feel good about including a static image of a prism? or should we have a prism that changes as they adjust the length, width and height?

**Comment by schanzer** [comment]
@flannery-denny is there anything more you need on this?
