### ISSUE TITLE
Inequalities Teachpack

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#405]
Students create a list of eight points (four of which are true and four of which are false)
They pass their function and these two lists into the teachpack

Teachpack should plot those points on a number line, showing them in red and green depending on true/false.

Ideally it could also work with compound inequalities. I imagine that as two inequalities boxing the intersection when given and... not sure what it would do with or.

**Comment by flannery-denny** [comment]
[sketches of teachpack](https://pyret.slack.com/archives/D0187PPEZRT/p1603129351006000)

**Comment by flannery-denny** [comment]
![IMG_5453](https://user-images.githubusercontent.com/66691020/98010774-1dc2ca80-1dc5-11eb-9af5-c4adbf8b1813.JPG)
![IMG_5454](https://user-images.githubusercontent.com/66691020/98010805-27e4c900-1dc5-11eb-8b0e-7aba9f794e1c.JPG)
![IMG_5451](https://user-images.githubusercontent.com/66691020/98010845-329f5e00-1dc5-11eb-946d-c5aa61af0dc3.JPG)
![IMG_5452](https://user-images.githubusercontent.com/66691020/98010873-39c66c00-1dc5-11eb-9f2f-1157e0881e3d.JPG)
![IMG_5450](https://user-images.githubusercontent.com/66691020/98010905-41861080-1dc5-11eb-8187-56ee2e284a4e.JPG)

**Comment by schanzer** [comment]
![image](https://user-images.githubusercontent.com/77126/99199519-c120c180-276d-11eb-92f5-970f7d39e347.png)

@flannery-denny how's this?

**Comment by flannery-denny** [comment]
Cool. 

- Do you think there's a way to put an arrow at the end of the number line with the green dots?
- Can there be an error message if they don't use the number in the inequality (e.g. 3 if it's x<3)
- will they be able to graph two inequalities simultaneously?

**Comment by flannery-denny** [comment]
I think one above and one below would be good. Let's talk about what you mean by we can't inspect the function this afternoon.

**Comment by schanzer** [comment]
Note to self: Add intervals

**Comment by schanzer** [comment]
Added intervals 
![image](https://user-images.githubusercontent.com/77126/99474244-36c99080-291a-11eb-8d8e-34072a1fa353.png)

**Comment by schanzer** [comment]
Added shaded "true" range
![image](https://user-images.githubusercontent.com/77126/99555290-2521d080-298e-11eb-994f-d71dd5beba39.png)

**Comment by schanzer** [comment]
Added support for two functions

![image](https://user-images.githubusercontent.com/77126/99666632-3aa00480-2a39-11eb-9b01-9807fb4e0ca6.png)
![image](https://user-images.githubusercontent.com/77126/99666641-3d9af500-2a39-11eb-8460-7d68480183a4.png)

**Comment by schanzer** [comment]
@flannery-denny [the WeScheme teachpack version of the file is here](https://www.wescheme.org/view?publicId=otEfL7wp4J), and [the CPO library is here](https://code.pyret.org/editor#share=1Q6TQBWfe54N86s8GtWN4n_zsQeVntxB5&v=8c4da7d).

**Comment by flannery-denny** [comment]
@schanzer These look awesome! 
The compound inequality feature works really well when there is an intersection... but 

- [ ] when the sets don't intersect the error message makes no sense (I just switched the functions to (< x 5) and (> x 15).  

- [ ] Also, your notes for the stand alone inequality lesson include discussion of union and intersection.  I've messed around with the file a little and it only seems capable of working with intersections. true? 

- [ ] How do I include this teachpak in my starter file?

**Comment by schanzer** [comment]
1) The error being "need 8 to pass"? In your spec, this was a requirement. How would you like to change it?
2) It works with intersections just fine -- it draws the gradients for both. What's missing?
3) In WeScheme? Put `(require wescheme/XYZ123)`  at the top of the file, where XYZ123 is replaced with the `publicId` of the shared program

**Comment by flannery-denny** [comment]
The way it draws intersections is great.  But how do we tell it if we're actually looking for the union?
I was expecting students to have input the words AND and OR in when they wanted to see the graphs of compound inequalities.
The need 8 to pass error message works great for simple inequalities. I'm not sure it works for compound inequalities. 
Is it possible to make 2 separate teachpaks? So that the error message would be on for simple and off for compound? 
The ideal error message for compound inequalities would require the program to identify whether it's a null set situation, an all real numbers situation, a split solution situation or a bounded solution situation and I'm pretty sure it can't do that.

**Comment by schanzer** [comment]
- [ ] change `test` to `inequality`, and have it take in only a single function and list. Check the list for pass/fail.
- [ ] `and-intersection` , takes in _two_ functions and a list, draws a box for overlapping ranges and shows an error if there are none.
- [ ] `or-union`, takes in two functions and a list, and does what `test2 does`. Prints out "all shaded regions are part of the solution"

**Comment by schanzer** [comment]
@flannery-denny printing out the boxed area is just not going to happen unless I drop more balls to make time for it. [I've implemented something that I hope is "close enough" in WeScheme](https://www.wescheme.org/view?publicId=CBuJTN45Bi) - can you tell me if this will work? If so, I'll port it to Pyret and we can close the issue.

**Comment by flannery-denny** [comment]
Looks good!
I like the messages you inserted into the code for me :)

I also love that the endpoints of the intersection appear red or green when students include them in their lists!

Flannery 

On Nov 21, 2020, at 10:22 AM, Emmanuel Schanzer <notifications@github.com> wrote:

﻿
@flannery-denny printing out the boxed area is just not going to happen unless I drop more balls to make time for it. I've implemented something that I hope is "close enough" in WeScheme - can you tell me if this will work? If so, I'll port it to Pyret and we can close the issue.

**Comment by schanzer** [comment]
SWEET! Here's a Pyret [Starter File](https://code.pyret.org/editor#share=1y6Wfp3ZREl8MuVl_idMq3rm7dyr7o2_i&v=8c4da7d) for inequalities as well. Close whenever you're ready!

**Comment by schanzer** [comment]
Updated the Pyret teachpack and starter file to make the list of `points` the last input.
New WeScheme teachpack: https://www.wescheme.org/view?publicId=HcSWAWd1aG
New WeScheme Starter File: https://www.wescheme.org/view?publicId=2UrrD5By5D

**Comment by schanzer** [comment]
Confirmed fixed via Slack. Closing!
