### ISSUE TITLE
Function Applications 2

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#41]
- [x] Don't take a volunteer for `make-game`. Not only is that asking for trouble in the classroom when the _teacher_ could be calling it out, but it gives a very incorrect view for waht `make-game` actually does. (make-game is NOT responsible for calling out to update-danger!)
- [x] Shouldn't function names be formatted as code?
- [x] Errant underscore: "_Answers will vary..."

**Comment by BootstrapJen** [comment]
Do you have a suggestion for what could make a better role play or example scenario?  We were looking for something that would take the element of "magic" out of update-danger and update-target, something that would make it clear WHY we need the computer to automate this process for us.
