### ISSUE TITLE
Boolean worksheet for wescheme inequalities lesson - which code will get added? which will we cut from wescheme materials?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#410]
Below is the weschemified version of the pyret inequality / boolean workbook page that will need to be added to the **June workbook**. 

Some of the functions from pyret don't exist in wescheme... yet.
- [x] Will we add a not equal function to wescheme or keep using `(not(= 3 3))`? 

>  I think it would better support the math learning goals to add not equals code if it's not a huge deal.  

- [x] Will we allow inequalities to compare strings? 
> Currently, whereas pyret can process "a" < "b" using variables in inequalities, wescheme returns error messages expects a number as 1st argument, but given: "a"

`= Inequalities

@vspace{1ex}

Boolean expressions are yes-or-no questions and will always evaluate to either `true` (“yes”) or `false` (“no”). What will each of the expressions below evaluate to? Write down the result in the blanks provided, and type them into WeScheme if you’re not sure.

++++
<style>
/** fitb CSS experiment **/
td:nth-of-type(even) p { display: table; width: 100%; }
td:nth-of-type(even) .fitb { display: table-cell; width: 90%; }
</style>
++++

[cols="1,.>2,2,.>2", frame="none", stripes="none"]
|===
|1) `(<= 3 4)`		| @fitb{}{}		|7) `(> "a" "b")`		| @fitb{}{}
|2) `(= 3 2)`		| @fitb{}{}		|8) `(< "a" "b")`		| @fitb{}{}
|3) `(< 2 4)`		| @fitb{}{}		|9) `(= "a" "b")`		| @fitb{}{}
|4) `(not(= 3 3))`	| @fitb{}{}		|10) `(not(= "a" "b"))`	| @fitb{}{}
|5) `(>= 5 5)`		| @fitb{}{}		|11) `(not("a" "a"))`	| @fitb{}{}
|6) `(>= 4 6)`		| @fitb{}{}		|12) `(= "a" "a")`		| @fitb{}{}
|===

[cols=".>7, .>6", frame="none", stripes="none", grid="none"]
|===
|13) In your own words, desribe what *>* does.				| @fitb{}{} 
|14) In your own words, describe what *<=* does.			| @fitb{}{} 
|15) In your own words, desribe what *not* does.			| @fitb{}{} 
|16) How many *Numbers* are there in the entire universe? 	| @fitb{}{} 
|17) How many *Strings* are there in the entire universe?	| @fitb{}{} 
|18) How many *Images* are there in the entire universe?	| @fitb{}{} 
|19) How many *Booleans* are there in the entire universe?	| @fitb{}{} 
|===`

**Comment by schanzer** [comment]
WeScheme already has string equality. In the `cost` and `update-player` functions, for example, WeScheme uses the function `string=?` to perform equality tests. Similarly, there are functions for greater-than and less-than:

`(string<? "a" "b")`
`(string>? "a" "b")`
`(string<=? "a" "b")`
`(string>= "a" "b")`


**I have added the following functions to WeScheme:**
```
; <> : Number Number -> Boolean
; checks if two or more numbers are not equal

; string<>? : String String -> Boolean
; checks if two or more strings are not equal

; string-ci<>? : String String -> Boolean
; checks if two or more strings are not equal, regardless of case
```
