### ISSUE TITLE
Jan->June changes

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#412]
Since we can't change the workbook page ordering in the Jan release, there are a lot of "papercuts" to be taken care of in preparation for June. This issue is to track those and make sure we don't forget!

- [x] We have a LOT of materials for the order of operations lesson and we should think carefully about what of it belongs in the workbook (select top 6, prioritize 3-column practice). What of this can be desmosified?
- [x] Integrate new Distance materials into the lesson plan.
- [x] weschemify slides for new inequalities lessons & add them to the lesson plans
- [x] Combine sam lessons into one, removing the material that is now covered in the inequalities lessons
- [x] We need a "Why not spreadsheets?" page on DS
- [x] Switch `@exercise-page` links to `@workbook-page` ones, and adjust `workbook-pages.txt` for inequalities, inequalities-2, tables-and-graphs, tables-and-functions, functions-and-graphs, flags, distance
- [x] Add the flags lesson to the algebra pathway
- [x] Maybe some infrastructure work so that web links can be picked up by the `@materials-list` directive?
- [x] ds-method-chaining: more open-ended exercises (word problem -> code)
- [x] Do we want defining values to reference flags now that there's a flags lesson? (no - there's no guarantee flags will always be in the same pathway as defining values)

**Comment by flannery-denny** [comment]
only thing left was moving booleans from one lesson to another and that's part of another issue
