### ISSUE TITLE
Anonymize images

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#413]
To make authoring easier, it's handy to have the function notation for a graph image _as the title of the file_. Unfortunately, clever students could access this title and skip over the activity to get the answer in some cases.

@ds26gte , can we simply number the images in a given folder/lesson? That way, the distribution directory would contain images with nothing but numbers in the titles, but the lessons directory would preserve the (extremely useful) titles.

**Comment by ds26gte** [comment]
A solution in 8b9076c (Jan-2021 branch).

1. Done only for images sourced via `@image` and `@centered-image`.  Images sourced via `image:` (the Asciidoctor directive) are not touched.

2. If an image file exists in the codebase but is not sourced anywhere, its name won't be anonymized. (We could do a post-translation sweep-up that deletes all unused images, i.e., image files whose names don't look anonymized, if it's really urgent, but it will take non-0 time.) 

2. I didn't use numbering to generate anonymous filenames, as it's sensitive to reordering, and won't work if we're editing a lot. Instead I git-hashed the file's basename to a 16-char hex number that's guaranteed to be a (math) function of the filename, while remaining practically impossible to decode.

3. If a non-existent image file is sourced, the original name remains, but a non-existence warning is issued. (There was no such warning before. This gave the opportunity to do so.)

**Comment by schanzer** [comment]
Closed by dc1b148267ab98011dbab3cb79e85b36f8e4b167
