### ISSUE TITLE
Exercise / Activity / Paper directive renaming

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#417]
As the ontology of linked materials grows, we now have five distinct uses cases:

1. `@link{url, linkText}` - an unchecked, unformatted link to an arbitrary URL. No checking or special formatting needed. (currently implemented. no work needed.)

2. `@online-exercise{url, linkText}` - a _required_ desmos, quizziz, etc exercise that lives online (currently implemented as `@activity-link`). Appends the domain name to the linkText. Resulting link should read: "Matching X and Y (desmos)" if the link is of the form `www.desmos.com/*`

3. `@opt-online-exercise{url, linkText}` - an _optional_ desmos, quizziz, etc exercise that lives online. Shows up with the CSS class "optional" on the parent of the link. Appends the domain name to the linkText.  (not implemented. a twist on`@activity-link`)

4. `@printable-exercise{path, [linkText]}` - a _required_ page (usually asciidoc) that lives in the workbook, but could also be printed to PDF, or imported into GDocs. Gets checked against `workbook-pages.txt`, grabs the page title as default link text (can be overridden), and uses the page number from the generated workbook. (currently implemented as `@workbook-page`)

5. `@opt-printable-exercise{path, [linkText]}` - an _optional_ page (usually asciidoc) that does NOT live in the workbook, and can also be printed to PDF, or imported into GDocs. Grabs the page title as default link text (can be overridden). Shows up with the CSS class "optional" on the parent of the link. (currently implemented as `@exercise-link`)

In the `@materials-links` content generation, they should be listed in the following order:
printable-exercises
online-exercises
opt-printable-exercises
opt-online-exercises

This results in a few TODOs:

- [x] find/replace `workbook-page` with `printable-exercise`.
- [x] find/replace `exercise-link` with `opt-printable-exercise`.
- [x] find/replace `activity-link` with `online-exercise`.
- [x] implement `@opt-online-exercise`
- [x] replace `ExerciseLink` classname with `optional` in the rendered output and CSS file
- [x] add domain appending code to `online-exercise` and `opt-online-exercise`

**Comment by schanzer** [comment]
@flannery-denny ready for comment

**Comment by flannery-denny** [comment]
@schanzer - Do we need to specify how it appends the domain name for Dorai. In parentheses? With a dash? or will Dorai be happy to make that decision

**Comment by schanzer** [comment]
Good call. Added an example to text

**Comment by flannery-denny** [comment]
@schanzer Added a final bullet to todos. Does it make sense?

**Comment by ds26gte** [comment]
I take it you want 2-5 to appear in the Materials row, and in that order?

**Comment by flannery-denny** [comment]
Order in materials section should be
@printable-exercise
@online-exercise
@opt-printable-exercise
@opt-online-exercise
