### ISSUE TITLE
Function composition 3

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#42]
- [ ] Where is the link to Lemonade WODB?
- [ ] Where is the link to Sally's Lemonade WB page?
- [ ] The lesson references "sample responses below", but none are there.
- [ ] Where is the discussion of why one version of `profit` is preferable?

**Comment by BootstrapJen** [comment]
Most of these are in Issue #32 - because this lesson is probably going to get axed and redistributed amongst the Defining Functions lessons and Sam.  There's just not enough here for a full lesson.

**Comment by BootstrapJen** [comment]
Decision was made to incorporate this lesson into DefiningFunctions3 as a lead-in to Inequalities.
