### ISSUE TITLE
check we have up to date solutions pages for... 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#425]
- [x] lessons/alg-compound-inequalities/langs/en-us/pages/onscreen.adoc
- [x] lessons/alg-inequalities-2/langs/en-us/pages/and-or.adoc
- [x] lessons/alg-inequalities-2/langs/en-us/pages/boolean-coe-to-code2.adoc
- [x] lessons/alg-inequalities-2/langs/en-us/pages/compound-inequality-functions.adoc
- [x] lessons/alg-inequalities-2/langs/en-us/pages/pyret/compound-inequalities.adoc
- [x] lessons/alg-inequalities-2/langs/en-us/pages/wescheme/boolean-functions.adoc
- [x] lessons/alg-inequalities/langs/en-us/pages/pyret/boolean-functions.adoc
- [x] lessons/alg-inequalities/langs/en-us/pages/pyret/simple-inequalities.adoc
- [x] lessons/alg-inequalities/langs/en-us/pages/wescheme/boolean-functions.adoc
- [x] lessons/alg-inequalities/langs/en-us/pages/wescheme/simple-inequalities.adoc
- [x] lessons/alg-simple-inequalities/langs/en-us/pages/keeping-ninjacat-in-the-game.adoc
- [x] lessons/alg-simple-inequalities/langs/en-us/pages/sam-intro.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/definitions-from-graphs.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/definitions-from-tables.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/linear-nonlinear-bust.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/match-definitions-graphs.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/match-definitions-tables.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/slope-and-y-def.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/slope-and-y-graphs.adoc
- [x] lessons/ds-linearity-2/langs/en-us/pages/slope-and-y-tables.adoc
- [x] lessons/ds-linearity/langs/en-us/pages/linear-nonlinear-bust-2.adoc
- [x] lessons/ds-linearity/langs/en-us/pages/linear-nonlinear-bust.adoc
- [x] lessons/ds-linearity/langs/en-us/pages/match-tables-graphs.adoc
- [x] lessons/ds-linearity/langs/en-us/pages/match-tables-graphs2.adoc

**Comment by flannery-denny** [comment]
@schanzer I looked at the first linearity solution page and it didn't look like you'd made the answer key yet.  Before I go open all the pages and solution pages and compare them, double checking that you think these are complete.

**Comment by schanzer** [comment]
￼I'm working on the linearity solutions, but haven't checked them in yet. Don't spend time comparing those files yet.￼
