### ISSUE TITLE
Discuss how we want COE pages authoring to work when we don't want all of the parentheses to show

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#426]
I just started working on the additional circles of evaluation pages and was reminded that Emmanuel wasn't sure whether we should be relying on mathjax for this kind of thing. In January let's make a decision.
- Are we ok with using mathjax for showing arithmetic?
- Do we want to make changes to infrastructure?

**Comment by schanzer** [comment]
See #388
