### ISSUE TITLE
Officially retire the alg-, re-, and ds- prefixes

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#427]
These were never meant to be longterm anyway. Let's rip them out. Some things to consider:

- [x] Don't forget to change `lesson-order.txt` in all the pathways
- [ ] Don't forget to change the `lessons-and-standards.rkt` file
- [x] solutions-pages
- [ ] slide decks
- [x] Maybe finally unify the `applying-functions` and `defining-functions` lessons across Algebra and Data Science?
- [x] Standardize contracts across pathways

**Comment by flannery-denny** [comment]
- [ ] Move Boolean page from DS Pyret Intro to Inequalites?

**Comment by flannery-denny** [comment]
@schanzer here's a start...
![Screen Shot 2021-02-03 at 2 36 29 PM](https://user-images.githubusercontent.com/66691020/106807512-def41900-662e-11eb-9c53-d5deeb0b48e5.png)

**Comment by schanzer** [comment]
Most of your renaming proposals also make sense, although I'm curious how you would rename "Player Animation" and "Problem Decomposition". But feel free to rename these lessons asap.

I agree that "Starting to Program", "Defining Functions, "Applying Functions", "Defining Values" and "Function Composition" should all be shared. There's some work to be done making that possible, though. We could probably make "Measures of Center" available as a math lesson as well -- it's fairly self-contained, including the workbook pages.

I don't agree with the list of lessons that are more CS than math. We should discuss at our next meeting.

**Comment by flannery-denny** [comment]
@schanzer 

- I'm seeing three special OK lessons: intro to coe, intro to contracts, intro to pyret... wondering if there's a reason they're different from regular intro to pyret... should we add this to our tuesday call?
- are you sure you want the reactive lessons to also not have re-prefixes?
- what does hoc stand for?

**Comment by schanzer** [comment]
1. Those are super old, and can definitely be deleted

2. Good point, let's keep the reactive lessons as is

3. Hour of code￼￼￼

**Comment by flannery-denny** [comment]
@schanzer pushed a first pass at renaming files

**Comment by schanzer** [comment]
I like the renaming thus far! Let's discuss the "cross-pathway" lessons in our call this week.

**Comment by flannery-denny** [comment]
@schanzer I started working on lesson ideas in googledoc and it doesn't feel like the right strategy. I'm working on an inventory of what would happen if we merge the lessons and will complete it here

- [ ] I'm thinking that it would make more sense to make 6 new asciidoc files where I try to merge the material than to try to mock things up in googledocs. Work for you? 

The files I propose making are:
- Values & Operators
- Defining Values
- Contracts
- Defining Functions
- Leftover fragments to incorporate into other DS lesson
- Leftover fragments to incorporate into other algebra lessons. 

**Values and Operators**
- Order of Operations and intro to pyret discuss definitions area / interactions area
- The Order of Operations lesson has a section on Numbers
- Intro to pyret introduces numbers, strings & booleans... but numbers & strings are treated separately from Booleans... perhaps they don't have to be part of this lesson? 
- [ ] Algebra introduces booleans through circles of evaluations, DS does not.It wouldn't make sense  I'm not sure it's important that Booleans be introduced through COE.  Thoughts?
- The new inequalities lesson initially introduces Booleans with the Booleans starter file and Boolean functions (about a 5-minute exercise) that are not inequalities... perhaps this could stay in the intro and inequalities could be saved for the inequalities lesson in algebra and table methods in DS?
- Intro to pyret has students look at how the column titles are listed in the starter file. I think this could easily move to another lesson.

**Defining Values**
- Intro to Pyret has a defining values section that is not DS specific
- Algebra does a better job of talking about why it's useful to define values to avoid duplicate code
- Algebra also gets to cleaning up code
- Algebra materials include prize-star

**Applying Functions / Contracts**
- Both versions look at contracts / domain & range / functions
- Algebra has great machine input output context that would be good for both
- Both versions get to contracts for images 
- Vocab lists are quite similar. Algebra version includes language table - would be good for both.
- Looks like materials overlap
- DS opens with f(x)=x^2… while I know we wanted to include advanced examples, it’s not the most user-friendly opener for algebra… but also if DS is being used for younger kids, it’s also not the most user-friendly for DS. _Both lessons reference domain & range of square and square root later in the lesson plan_
- The Algebra version opens with graphs function v not a function… not an ideal opener for DS, either… t_his could move to the new Domain & Range lesson._
- We’d have to shift Data Science workspace from animals starter file to CPO to generalize the lesson
- Algebra Materials list:
-- Blank Contracts Page
-- Exploring Image Functions (Page 16)
-- Reading for Domain and Range (Page 17)
-- Matching Images to Code (Desmos)
-- Domain and Range Frayer model
-- Identifying Parts of Expressions
-- Identifying Parts of Expressions (2)
Matching Expressions and Contracts
- Data Science Materials list:
-- Applying Functions (Page 9)
-- Practicing Contracts (Page 10)
-- Matching Expressions and Contracts (Page 11)
-- Fun with Images
-- Practicing Contracts (2)
-- Matching Expressions and Contracts (2)

**Defining Functions**
- The core of both the Algebra & DS lessons are green triangles. They both refer students to the Design Recipe.  Vocab is almost the same. The language table for DS includes Boolean, but it doesn't actually appear in the lesson.
- DS gets to defining functions over other datatypes (sticker, nametag) and custom image scatter plots. We’d have to move this somewhere else.
- Algebra Materials list: 
-- Mapping Examples with Circles of Evaluation (Page 27)
-- Fast Functions (Page 28)
-- Matching Examples and Function Definitions (Page 29)
-- Review: Define Values & Fast Functions (Desmos)
-- Creating Contracts From Examples
-- Creating Contracts From Examples
-- Bug Hunting in WeScheme (Wescheme)
- Data Science Materials list:
-- The Design Recipe (Page 23)
-- The Design Recipe (Page 24)
-- The Design Recipe

**Comment by schanzer** [comment]
I think this is a fine approach. For now, can you focus on a strong 1st draft for the first two lessons? And I would also add a bug-hunting activity to both, similar to what we have now in DS: lots of simple syntax errors.

**Comment by flannery-denny** [comment]
@schanzer 
Looking at the materials for combined intro to pyret lesson. I think the Boolean page has been really well developed. I'm a little less sold on our materials for introducing numbers and strings.

2 options:
- get rid of notice and wonder page for this lesson and make better scaffolded page for numbers and strings
-  open ended notice and wonder for numbers &  better scaffolded materials for strings that don't all focus on numbers.

preference?

**Comment by schanzer** [comment]
If these are my options, my preference is the first one. Numbers just aren't that exciting for kids, so restricting notice and wonder to numbers alone feels like leaving them hanging.￼

**Comment by flannery-denny** [comment]
Cool. That was my inclination, too. The existing notice and wonder is not very inspiring to wonder about.

**Comment by flannery-denny** [comment]
@schanzer 

- [ ] In the workbook pages currently linked to contracts there are questions like _What is the domain of the outermost function being used in:_`scale​(​2, circle​(​40, "solid", "blue"​)​)`
Do you think we should be getting to that level of complexity in this lesson?  I'm inclined to think not. 
- [ ] Also, does it feel ok to you to introduce contracts for functions that aren't built in in this lesson? DS has a file on matching expressions and contracts that includes stuff like make-id :: (first :: String, last :: String) -> Image  make-id("Jessica", "Jones", 32) seems ok, but not totally sure.

**Comment by flannery-denny** [comment]
@schanzer  I'm looking at the new Order of Operations page and it links to some Quiziz files. 
- [ ] Noticing that one of them asks students to write circles of evaluation from verbal expressions like _"Five plus the product of ten and negative two"_. This is a learning goal that none of our other materials address. Wondering if we want to commit to making some materials for problems like this? Maybe matching activities between verbal expressions and circles or code? Not attached to the idea. Just seems weird to throw something into quizziz that we don't address anywhere else so wondering...
- [ ] Also, we have very few Quizizz materials and none of them are very well conceived. Thinking we should get rid of all of them and either commit to making new ones for many of our lessons or stop repping ourselves as offering them.

**Comment by flannery-denny** [comment]
@schanzer There's a bullet in the original issue about standardizing contracts across pathways.  I don't know what that means.

**Comment by schanzer** [comment]
@flannery-denny 

1) I answered the big comment via an in-line edit.
2) Yeah, the quizziz stuff is pretty lame. I say get rid of them. Someday we might use them, but I'm a lot more excited about Desmos for now because it gives us the opportunity to actually collect research data!
3) The DS lessons include the name of the variable as part of the contract. The algebra ones don't. This is something you and I should discuss on a call.

**Comment by flannery-denny** [comment]
@schanzer I'm looking at the _applying functions_ page. It's currently set up to ask students to type the buggy code in, record the error message, and explain what's wrong. I would like to propose that we instead create a page that includes both the buggy code and the error messages and asks students to identify the problem... Objections?

**Comment by schanzer** [comment]
No objections :)￼

**Comment by flannery-denny** [comment]
**add to contracts lesson**
string-append
isosceles-triangle
right-triangle
triangle-sas
triangle-asa
polygon-star
line
fillmode

**add to function-composition lesson**
frame
scale-xy
above
beside
overlay

**Comment by flannery-denny** [comment]
Contracts Lesson:

_- Matching expressions uses fictional functions
- Practicing contracts uses fictional functions_
- **Think carefully about which functions to use for Domain & Range** and **how to scaffold using contracts**
-

**Comment by flannery-denny** [comment]
closing with #476
