### ISSUE TITLE
linearity

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#428]
- [x] linear, non-linear or bust 1 and 2 and the one that focuses on definitions (which could use a more distinctive title). One asks "not a function" the other asks "no rule". I don't think you actually want either of these choices. Pretty sure students are just prepared to identify whether or not it's linear. And some things that aren't functions have rules... 
- [x] We should make a second page of linear-nonlinear or bust with just graphs so that we include vertical, horizontal and one of the graphs that Jen suggested
- [x] linear, non-linear or bust pdf is on 2 pages
- [x] matching tables to graphs 2 - I think there's a mistake in the second table.
- [x] Summarizing tables with function definitions. Am I missing something here?
![Screen Shot 2020-12-28 at 12 45 12 PM](https://user-images.githubusercontent.com/66691020/103236553-cba4ae00-490a-11eb-8367-9c1a6dcf2f3c.png)
Won't they just end up writing the same thing twice?
- [x] There are a few more desmos activities I made for the linearity stuff. Are some of them intentionally left out?
- [linearity collection](https://teacher.desmos.com/collection/5fbe7484d81cab0ca7a8bcfb)
- [not just linear collection](https://teacher.desmos.com/collection/5fc266e34666f00d51454bc8)

**Comment by flannery-denny** [comment]
@schanzer making sure you haven't forgotten about this

**Comment by schanzer** [comment]
@flannery-denny I've pushed a few commits that should address all of these. Close if you feel they are satisfied.
