### ISSUE TITLE
update animals dataset links in all pd peardecks

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#440]

**Comment by schanzer** [comment]
I think we can close this. There aren't really "PD Peardecks", since we're copy/pasting from the lesson slides.

**Comment by flannery-denny** [comment]
@schanzer It doesn't help people to look at old versions of files. And I also think it's healthy for them to engage with the hermaphrodite animals while they're not with kids.  

I know that all of the starter file links have been updated since Fall2020. Either **you are using old PD peardecks and we should update them**, which is my best guess as to how that bug happened... or you should be copying and pasting from current slide decks.  If you're using old PD decks, please tell me where they are and I will be happy to update them for you. I put it on our list to discuss on Tuesday.

**Comment by schanzer** [comment]
Oh, I'm not saying people are helped by looking at old versions!!

That was a stupid mistake on my part, copying an old PD deck from last year. Moving forward, I'm just deleting all the slides and replacing them with the slides from the spring 2021 lesson plans.

Do you have any concerns with this approach?￼

**Comment by flannery-denny** [comment]
Works for me. Just wanted to make sure the strategy had shifted.
