### ISSUE TITLE
Dataset transformation recommended by Nancy Pfenning

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#446]
- State Demographics: Let's keep this.
- [x] We can call poverty rates low (less than 12%), medium (12% to 18%), and high (greater than 18%).
- _Decided not to do this rec_ male/female could be categorized as majority male (if % female is below 50%) or majority female (if %female is above 50%).
- [x] Population increasing or decreasing from 2010 to 2014.
- [x] update starter file

Esports dataset
- [x] make release-date categorical, with three categories: pre-2000, 2000-2010, post-2010.
- [x] update starter file

MLB data
- [x] create a column for region of the U.S. Maybe [this map](http://www.stadium-maps.com/sports-maps/major-league-baseball.html) would be helpful? 
- [x] update starter file

Music.
We can kill two birds with one stone to address two problems with this dataset, namely
1. It's too huge.
2. There are too many different categories in the "form" column: A pie chart will have too many slices, and a bar chart will have too many bars.
- [x] What I suggest is to extract the most common forms, such as pop rock and hiphop and a few others, and jettison all the songs that don't fall into those categories. It should be easy enough to sort the whole file according to "form", then choose the top several categories to keep.
- [x] Here's how to create a second categorical column: transform loudness into loud (0 to -5), medium (-5 to -15) and soft (below -15). I'm pretty sure that's how the loudness variable works but it would help if you double-check.
- [x] An additional categorical column could be constructed from duration (less than 180 seconds i.e. three minutes, and so on up to something like greater than five minutes).
- [x] Yet another could be created from beats-per-minute: crate some ranges to categorize as slow, medium or fast.
- [x] update starter file

Voter turnout.
The current dataset doesn't work well, because the "individuals" are just a few groups of people classified according to age, and the "variables" are years. Perhaps the attached Table 04a would be better, if you delete the margin of error columns. The individuals are states, the main variables are: Percent Registered Total, Percent Registered Citizen, Percent Voted Total, Percent Voted Citizen.
- [x] An interesting categorical column can be added by scrutinizing attached table 04b and determining whether Percent Voted (Total) was higher for White Only or Black Only.
- [x] Yet another categorical column could be for whether the percentage voting in that state was below or above the national average of 56%.
- [x] update starter file

Arctic Sea Ice:
- [x] Whether Global Mean Sea Level Variation is negative or positive.
- [x] Average Sea Ice Extent..group into five categories:  <4, 4 to 5, 5 to 6, 6 to 7, and >7. 
- [x] update starter file

"January Average Global Temperature Anomaly (C)": what does this even mean? I really don't like the idea of having students manipulate data that doesn't make sense to them. Or am I missing something? If it doesn't seem meaningful to you either, maybe we should ditch those 12 columns, as well as the Month Minimum and Month Maximum columns, for reasons I gave in a recent email. It's better to have a few columns that are worthwhile instead of a lot of extra columns that are cryptic or trivial.

**Comment by flannery-denny** [comment]
Nancy made a bunch of suggestions about categorizing states by region. I've been looking at maps of the US. There seems to be a lot of disagreement about how to sort us!

**Comment by flannery-denny** [comment]
@schanzer I updated the states dataset.

- [ ]  last population column is for 2014. do you think we should add 2018?
- [ ] nancy suggested a majority male v majority female category. I'm not sure that I can get behind those categorizations when the range is only from 47.4 to 51.5 % female. What do you think?

**Comment by schanzer** [comment]
@flannery-denny I think adding 2018 would be a good idea. And I agree that Nancy's suggestions don't feel right when the range is so tight.

**Comment by schanzer** [comment]
@flannery-denny and I spoke, and this seems like a great project for Nick Bousquet!

**Comment by flannery-denny** [comment]
@schanzer Here's an updated Voter Turnout sheet. Anything you'd add or delete before I make the starter file? https://docs.google.com/spreadsheets/d/1uhnZVz9OFsnI8rNpdIiw5ZcxnstaKMAE8BQ285KZxfQ/edit?usp=sharing

**Comment by schanzer** [comment]
I think the columns you added are terrific. The one tweak I might make is changing the cutoff in the last column from 10% to 15%, but that's super nit-picky.

**Comment by flannery-denny** [comment]
@schanzer I could make that a categorical column… <10, bw 10 & 15, > 15…

Flannery

**Comment by flannery-denny** [comment]
@schanzer Nancy suggested that we slim the categories for this file. Do you think I've slimmed them enough or should I eliminate a few more?

https://code.pyret.org/editor#share=1Q0BZa2nyfoMfoW6hwAyCqR_jqOIRXxkG&v=1904b2c

![Screen Shot 2021-09-15 at 1 53 25 PM](https://user-images.githubusercontent.com/66691020/133515070-1f6a3814-dfe2-4b10-9131-a7a1821012ff.png)

**Comment by flannery-denny** [comment]
@schanzer Nancy suggested trimming the number of categories for the music file. Do you think this is few enough? or should I be more ruthless?

https://code.pyret.org/editor#share=1Q0BZa2nyfoMfoW6hwAyCqR_jqOIRXxkG&v=1904b2c

![Screen Shot 2021-09-15 at 2 08 49 PM](https://user-images.githubusercontent.com/66691020/133516506-89f16767-075a-45cc-a981-214dccbad185.png)

**Comment by schanzer** [comment]
It still feels a little big to me, but this is definitely an improvement. I'm comfortable signing off on this one.

**Comment by schanzer** [comment]
I think it's fine to put this out there - if it turns out to be unpopular or we hear negative feedback, we can always remove it.

Closing. Nice work!
