### ISSUE TITLE
Some Reactive images unavailable (maybe due to G drive owner change?)

### ISSUE THREAD

**Issue by jpolitz** [bootstrapworld/curriculum#448]
An image in this program is failing to load:

https://code.pyret.org/editor#share=0B9rKDmABYlJVNDdsNDBNcHdSVWs

https://code.pyret.org/shared-image-contents?sharedImageId=0B9rKDmABYlJVY21Ldk9UX1ppbEE

It looks fine in Drive:

https://drive.google.com/file/d/0B9rKDmABYlJVY21Ldk9UX1ppbEE

<img width="332" alt="image" src="https://user-images.githubusercontent.com/119891/108742264-645f4080-74ec-11eb-9357-dc7b8a9bc160.png">

However, I bet what happened is that it was previously owned by a specific @bootstrapworld user, then got changed to “Sys Admin” so somehow the sharing is either no longer “public on the web” or it's trying to use an expired access token and can't get the new access token, because the Sys Admin user has never logged into CPO and explicitly shared this image to register that image/account pair with the server.

I think double-checking that these are set to “Public on the Web” (not just “Anyone with the Link”) _should_ work, but need to verify that, and if that doesn't fix it in-place, may need to do another fix.

Other files with the same issue:

https://drive.google.com/file/d/0B9rKDmABYlJVQzllekZsZjZ3M2c/edit
https://drive.google.com/file/d/0B9rKDmABYlJVZG40T2d5QVRLcFU/edit
https://drive.google.com/file/d/0B9rKDmABYlJVb0syVUhIX0hmZ00/edit
https://drive.google.com/file/d/0B9rKDmABYlJVbXloR04zNlRqSVk/edit
https://drive.google.com/file/d/0B9rKDmABYlJVNGVsM2kzTklOaG8/edit
https://drive.google.com/file/d/0B9rKDmABYlJVTmxoY0dDdWsyN0k/edit

On the bright side, this was caught by integration testing of the curriculum links in CPO.

**Comment by jpolitz** [comment]
@blerner FWIW this has to do with the flaky tests on @brownplt/code.pyret.org – these tests _and the tests immediately after them_ are failing on my local build.

**Comment by jpolitz** [comment]
(Well, since there were flaky tests a while ago, and that was for a different reason, I'm not totally sure. But it's helpful nonetheless.)

**Comment by blerner** [comment]
Is this the same as we fixed with BS:P flakiness in tests?

**Comment by schanzer** [comment]
As per @jpolitz 's instructions, I just created a new file, logged in as the owner of those images. I can confirm they all load in CPO when that file is run. Hopefully this will resolve the issue for the integration tests?

**Comment by schanzer** [comment]
Confirmed fixed by Joe
