### ISSUE TITLE
Address verbal expressions like "Five plus the product of ten and negative two" 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#450]
write circles of evaluation from verbal expressions like "Five plus the product of ten and negative two"? 
This is a learning goal that none of our other materials address.

**Comment by schanzer** [comment]
@flannery-denny is this a learning goal for high school, or more for earlier grades? If it's the latter, we should fold this in with Rachel's work on early-grade lessons

**Comment by flannery-denny** [comment]
This is definitely assessed before high school. Great idea to add it to what @retabak is thinking about.

**Comment by schanzer** [comment]
Closing, now that this is addressed in #1170
