### ISSUE TITLE
audit language tables

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#452]
we're moving things around and when we're done we need to make sure the language tables match.

**Comment by flannery-denny** [comment]
@schanzer Thanks for explaining the language table. 

I am proposing that we automate the inclusion of the language table in a lesson plan rather than update separate files for each lesson.

- we already format `functions` specially in lesson plans and could just as easily tag them @function
- as I understand it, the Boolean type and values do not change from one lesson to another in the language table as new functions are added. They could stay static and the list of functions could be populated to include all of the @functions tagged in lessons that precede a given lesson in the lesson.order file
- this feels particularly useful as we head into using core lessons that precede and follow different lessons depending on the pathway and students may have encountered different functions before arriving at the lesson...

Not stuck on it. But wonder how complicated it would be. And think there's significant work involved in bringing language tables up-to-date for the next release either way so am proposing it before that work begins.

**Comment by schanzer** [comment]
This isn't a bad idea, but consider:

- Authors will have to remember to tag functions using `@function{}`. Failing to do so (or accidentally removing that formatting) will cause the function to disappear from every lesson.
- Authors will have to _use_ a function in order for it to show up. We can't just add a function or two hoping that curious students will explore them.

As long as you're OK with this, I can see this being valuable.

**Comment by flannery-denny** [comment]
I see the risk of the first concern, but it seems less risky than the alternative. Auditing a file to make sure that all @functions are tagged correctly seems easier to me than auditing all of the lessons that come before or after a lesson in multiple pathways.

Also, I imagine most functions appear multiple times so the odds of them being untagged every time they're used seems slim.

As for the second point, I have no idea how often you've done that. It doesn't seem impossible to add a sentence plan that says...

"Curious students may also want to investigate @function{}"

**Comment by schanzer** [comment]
I agree with your assessment, and I'm all for it. I *suspect* that scanning all pages (not just lessons) will add an extra second or two to the build-time, which would be well worth it.

@ds26gte , let's discuss at our next curriculum meeting.

**Comment by schanzer** [comment]
@flannery-denny , OK to close in light of #455 ?
