### ISSUE TITLE
Automated Language Table generation

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#455]
Maintaining the language tables by hand is getting increasingly difficult, and will soon be impossible now that we're starting to realize the Remix dream and use the same lesson across multiple pathways. At this point, we need to start thinking seriously about having them generated programmatically _per-pathway_.

**Proposal: @function{....}**

- Authors need to wrap all functions in a `@function{...}` directive (including operators, since WeScheme treats those as functions). 
- Somewhere in `lib`, we maintain a file that maps datatypes to functions (e.g. - `Number` maps to `num-sqrt`, `num-sqr`, etc....), as well as example values for those types (`4.2`, `1/2`, `-99`, etc)
- The build script keeps track of which functions have been tagged as it works through the lessons in-order.
- When building a lesson, the script generates the table by finding out which types are represented, then adding a row for each type. In that row, it prints out all the functions for that type and the example values.

Two additional wrinkles:
- Presumably these function names will need to be passed through the `sexp->code` converter. 
- Operators should not show up in the language table when proglang = pyret

@ds26gte , what do you think?

**Comment by schanzer** [comment]
@ds26gte There's still something buggy about the way these tables are constructed. 

In the algebra pathway, lessons like "simple data types" have no table at all, despite following "order of operations" (which does have a table).

**Comment by flannery-denny** [comment]
@ds26gte Please let me know when you think the language tables are building correctly and I will double check that they are doing what we expect them to.  As of right now, they still aren't building the way that we discussed in our meeting on Tuesday. I expect that's because you've been focused on other things.

**Comment by ds26gte** [comment]
Lesson plan's Language Table row doesn't automatically include primitives introduced in current lesson plan.  Pushed 4/20/21.
