### ISSUE TITLE
Core Lesson Rewrite Feedback request

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#457]
Open to incorporating as much feedback as you want to give to get these right... and looking forward to moving some of these out of the sample pathway build as soon you think they're good enough. 

Looking forward to feedback on 

- overall learning goals of the lessons being achieved
- do you agree with which pages are optional and which pages end up in the workbook?
- how does the formatting feel?
- how to do the vocab lists for each lesson look?
- overviews of each section (reused a lot of stuff here and didn't give them a lot of attention - wondering whether they're good enough or I should delete the overviews and rewrite them)
- style - am I talking about workbook pages enough, not enough, too much?

_(Will circle back to solution pages after we agree that the lessons and their pages are hitting the mark)_

- [x] Last Section of Order of Operations
- [x] Simple Datatypes
- [x] Contracts
- [x] Function Composition _(The last page linked from this lesson **More than one way to compose** isn't ready yet.)_
- [x] What do you think about sharing [this video](https://youtu.be/i9-ZPGp1AJE ) about plimpton 322 as additional resources in the Distance Lesson?

**Comment by schanzer** [comment]
**Order of Operations**

- [ ] Is Order of Operations capitalized or not? I would capitalize them, and do it consistently.
- [ ] Looks like you're missing a paragraph at the beginning: "Humans also use verbs...". Was there something about nouns that should have gone first?
- [ ] The sandwich analogy paragraph reads a little strangely to me. I'll push a proposed draft.
- [ ] Why not wrap "Circles can contain other Circles" in a `lesson-point`? That seems very significant.
- [ ] In the "Completing Circles of Evaluation from Arithmetic Expressions" page, why center the column titles but not the column contents? Also, the word "Challenge" is creating up a TON of blank space. What about replacing it with a star?
- [ ] The "translate" exercises seem to start with 3 & 4. What happened to 1 & 2?
- [ ] I still feel like we need the first exercise to be purely about translation - but I won't die on this hill if you feel strongly. :)
- [ ] As I'm lookin at the Circles of Evaluation, I feel like we could squeeze some space out of them. I've pushed a change, but if it doesn't look good it's easy for me to undo it.
- [ ] Last section: you say the function is called `string`, when it's actually `text`. Also, can we replace "Try replacing it with different values, and see what you get" with "Try different values"?

**Comment by schanzer** [comment]
**Simple Datatypes**
- [ ] Suggest rewriting "In English the order in which we arrange the words in a sentence is important! `The cat sat.` is a sentence, whereas `The sat cat` is nonsense, even though the syntax of all the words is valid!" to "`The cat sat` is a sentence, whereas `The sat cat` is nonsense, even though all the words are valid syntax. The order of the words matters!"
- [ ] The Booleans Overview doesn't really add new information. Suggest adding an extra sentence for the teacher, explaining why Booleans are different and why it matters.
- [ ] The Booleans Launch has a nice description, but that doesn't feel like a launch activity. I think what's missing at the top is something along the lines of "What's the answer: is 3 greater than 10?"

**Comment by schanzer** [comment]
**Contracts**
- [ ] "What is the contract for star? `Star : Number String String : Image`" is incorrect. star should be lowercase, and we need an arrow before the Range.
- [ ] Do we want to be so prescriptive about what the blank line is for? The lesson plan says it's for an "example", but maybe we should suggest using it for notes as alternative?
- [ ] In the "Using Contracts" pages, I don't love the "what variable changes..?" wording. I _think_ you mean "what changes about the shape?"
- [ ] In the "Triangle Contracts" page, what are you hoping to get for #3? This didn't seem clear to me.
- [ ] Confirming that including triangle/sas, triangle/asa in the workbooks won't freak out middle school teachers? Remember, this lesson often comes early in the year as well.
- [ ] Not sure I love the title "Using Contracts Increases Efficiency". How about "Contracts Help Us Write Code?"

**Comment by schanzer** [comment]
**Function Composition**
- [ ] The wording around "translating from function composition to order of operations" needs work. I revised it somewhat, but I think it needs further workshopping.
- [ ] "Function Composition - Your Name" refers to `above` and `frame`, but doesn't list their contracts
- [ ] "Function Composition - Scale/XY" the instructions for the challenge problem don't read clearly to me
- [ ] Add an explicit link to the flags lesson, since we're calling it out in the box
- [ ] Let's discuss the "more than one way" page in our next meeting

**Comment by schanzer** [comment]
I like the video!!!

**Comment by flannery-denny** [comment]
Datatypes are capitalized in the programming context Number, String, String and formatted as code because that is how Pyret knows them.
