### ISSUE TITLE
Audit lesson plans for references to mathematical practices and strategies for ELL

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#458]
Current inclusion of these boxes in lesson plans is pretty sporadic and I'm often not understanding the connection that led someone to put them there.  Let's discuss.

- [ ] checking your work
- [ ] choosing your dataset
- [ ] combination
- [ ] permutation
- [x] contracts
- [x] coordinates
- [ ] correlations
- [x] defining functions
- [ ] defining table functions
- [x] defining values
- [ ] displaying categorical data
- [ ] displays and lookups
- [x] distance
- [ ] ds intro
- [ ] error analysis
- [ ] ethics and privacy
- [x] flags
- [x] function composition
- [x] functions for character animation
- [ ] grouped samples
- [ ] histograms
- [ ] histograms 2
- [ ] hoc wescheme intro
- [ ] hoc winter
- [ ] if expressions
- [x] ineq -collision
- [x] simple ineq
- [x] compound ineq
- [x] sam
- [ ] lr
- [ ] linearity
- [ ] linearity 2
- [x] making game images
- [ ] measures of center
- [ ] measures of spread
- [ ] method chaining
- [x] numbers inside video games
- [x] order of operations
- [x] piecewise functions
- [x] player animation
- [x] problem decomposition
- [ ] random samples
- [x] restating the problem
- [ ] scatter plots
- [x] simple datatypes
- [x] solving word problems
- [x] surface area rect prism
- [ ] table methods
- [ ] threats to validity

**Comment by flannery-denny** [comment]
@schanzer I can't remember whether we were waiting for sidebar infrastructure for this or whether this info just gets added to standards?

Also, I remember you having several lists of practices that we should be referencing. Could you please remind me where to find these so that I can read with an eye toward what needs to be included where? Thanks

**Comment by schanzer** [comment]
This can get added without worrying about sidebar, so there's no need to wait. [Here's a document](https://achievethecore.org/content/upload/Mathematical%20Routines.pdf) which lays out all the Mathematical Language Routines (MLRs).

**Comment by flannery-denny** [comment]
@schanzer 
- Mathematical Practices and NGSS Practices clearly go in lessons and standards 
AND
- the origin of this git issue was about MLRs, which have been in blue boxes in the lessons... are they now getting added to the standards so that they get listed in the side bar instead. Do I need to add an MLR standards dictionary in the shared folder in order to use them?

**Comment by schanzer** [comment]
We had a pretty substantive discussion about the practice standards, which led to the creation of `lessons-and-badges.rkt`. I assumed all of practices would go there. Are you suggesting putting those _back_ into the standards dictionary?

And yes, I think adding an MLR dictionary is the way to go here. Do you want me to do that, or are you comfortable enough with the build system that you can tackle it yourself?

**Comment by flannery-denny** [comment]
Not suggesting anything. Just trying to understand.

If I understand correctly, MPs are defined in the common core library dictionary, should be removed from the standards dictionary (there are definitely at least a few there - if you have an efficient way to do this without losing the information, please do), and instead should be listed in lessons-and-badges.rkt

Faster for me if you make the mlr dictionary.

Flannery

**Comment by schanzer** [comment]
@flannery-denny MPs are already moved into `lessons-and-badges`. Added the MLR practices dictionary in 31d5a9f6537ee61efbec019f7bd7c1e926e72941

**Comment by flannery-denny** [comment]
I know that you want the MLRs below to be added to `lessons-and-badges.rkt`.  

Confirming that the intention is that this will be in place of including them directly in the lesson plans and the MLR boxes that are currently in lesson plans should be removed in favor of including this info in the side bar?

The reason I'm not totally sure is that MLRs seem like they're supposed to be a strategy that we're offering to support ELLs, whereas MPs seem to be something that we think the lesson is already achieving.

**Comment by flannery-denny** [comment]
@schanzer - I'm looking at the NGSS dictionary and the NGSS Practices are broken down way more specifically than the 8 practices you included in this issue. Would you be ok with editing the dictionary to focus on the key 8 to make the audit more manageable?

**Comment by flannery-denny** [comment]
SEP1 Asking questions (for science) and defining problems (for engineering)
SEP2 Developing and using models
SEP3 Planning and carrying out investigations
SEP4 Analyzing and interpreting data
SEP5 Using math and computational thinking
SEP6 Constructing an explanation (for science) and designing a solution (for engineering)
SEP7 Engaging in an argument stemming from evidence
SEP8 Obtaining, evaluating, and communicating information

MLR.1 Stronger and Clearer Each Time
MLR.2 Collect and Display
MLR.3 Clarify, Critique and Correct
MLR.4 Information Gap
MLR.5 Co-Craft Questions and Problems
MLR.6 Three Reads
MLR.7 Compare and Connect
MLR.8 Discussion Supports

MP.1 Make sense of problems and persevere in solving them.
MP.2 Reason abstractly and quantitatively
MP.3 Construct viable arguments and critique the reasoning of others.
MP.4 Model with mathematics.
MP.5 Use appropriate tools strategically.
MP.6 Attend to precision.
MP.7  Look for and make use of structure.
MP.8 Look for and express regularity in repeated reasoning.

**Comment by schanzer** [comment]
@flannery-denny happy to do it. But I'm curious - why remove the unused ones that we aren't focusing on for now? Does it do any harm to keep them?

**Comment by flannery-denny** [comment]
@schanzer I'm fine to leave them, but, currently the overarching SEP are commented out.

**Comment by flannery-denny** [comment]
@schanzer also, confirming all 3 of these MP, SEP and MLR go in lessons and badges?

**Comment by schanzer** [comment]
Fixed the NGSS file as you requested. And yes, these should all go in lessons-and-badges.

**Comment by flannery-denny** [comment]
@schanzer We could definitely be making better use of 

> MATHEMATICAL LANGUAGE ROUTINE 3: CRITIQUE, CORRECT, AND CLARIFY
Purpose: To give students a piece of mathematical writing that is not their own to analyze,
reflect on, and develop.
The intent is to prompt student reflection with an incorrect, incomplete, or ambiguous written argument or explanation, and for students to improve upon the written work by correcting errors and clarifying meaning. Teachers can model how to effectively and respectfully critique the work of others with meta-think-alouds and press for details when necessary. This routine fortifies output and engages students in metaawareness.

**Comment by flannery-denny** [comment]
@schanzer Does the Error Analysis lesson I'm seeing listed in standards exist somewhere? the asciidoc file looks very incomplete to me.

**Comment by flannery-denny** [comment]
@schanzer No rush on this, but I just did a find in files search for _Strategies or English Language Learners_ and added all of the lesson with those boxes to the standards file.  Strangely not the strategies I had independently associated with the lessons. Anyhow, curious whether or not you want to leave all of those boxes in the lessons.

**Comment by schanzer** [comment]
Ooooh, good catch. I feel like adding boxes would come across as more weighty, but the workload/opportunity cost of doing it may greatly outweigh the benefits. What does your gut tell you?

**Comment by flannery-denny** [comment]
@flannery-denny review SEP for DS

**Comment by flannery-denny** [comment]
@schanzer I made notes in the lessons and standards file of which lessons have strategy boxes for MLRs and which connect to MLRs but don't have strategy boxes so we can revisit another time.

**Comment by flannery-denny** [comment]
@schanzer - this audit makes me think that it would be nice to have the research paper (and perhaps other projects) listed as a separate item in the lessons and badges file.  I think the project hits Science & Engineering Practices that the lessons themselves do not.
