### ISSUE TITLE
reference site properly

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#460]
```
include::datasheet-for-dataset-admin.adoc[tag=dist-how-common-answer]
```
needs to properly make the Bootstrap name a link.

**Comment by ds26gte** [comment]
Added `@Bootstrap` as a preproc directive that expands to `https://www.bootstrapworld.org/[Bootstrap]`.

**Comment by schanzer** [comment]
Ok to close?

**Comment by schanzer** [comment]
@shriram Ok to close?

**Comment by schanzer** [comment]
@shriram ping?
