### ISSUE TITLE
@@

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#461]
```
include::datasheet-for-dataset-admin.adoc[tag=maint-contact-common-answer]
```
is the `@@` intentional?

**Comment by ds26gte** [comment]
Yes. I borrowed `@` from Scribble as the symbol token that's used by the Racket preprocessor. For a literal `@` it is doubled.

That said, a single `@` should be OK, *if* whatever follows is known not to be a preprocessor directive. However, you will get a WARNING.

**Comment by schanzer** [comment]
In general I'm a fan of _more_ rigid structure, not less. Let's either disallow one `@`, or remove the warning altogether. I don't want to be training myself to ignore warnings.

**Comment by ds26gte** [comment]
Done. `@nondirective` doesn't warn, just renders as-is.

**Comment by shriram** [comment]
I'm sorry, I don't understand how @ds26gte's reply actually addressed my question. How can the answer to my question be "yes"?!? At the end of the day, will the email address be formatted correctly?

**Comment by ds26gte** [comment]
Yes, an email address where the "location" `@` is supplied as `@@` in the .adoc file will be rendered as an email hyperlink with a single   `@` in both the HTML and the PDF.
