### ISSUE TITLE
PDF formatting

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#464]
In the PDF version I cannot see ANY visual difference between the questions and the answers. The whole thing looks like one big run-on pile of prose. Please use a formatting distinction there just as we have on the Web. Also with spacing before each question.

**Comment by ds26gte** [comment]
I added some print-specific CSS (in ``lib/shared.css`) to the classes `.question` and `.answer`. I.e., a 3ex leading vertical margin for questions, and a 1.5ex margin for answers. 

These can be further modified to taste.

**Comment by schanzer** [comment]
Nice! I should have asked for this months ago. Thanks for bringing fresh eyes, @shriram !

**Comment by shriram** [comment]
I haven't looked at the output yet. Mind if I do so, @schanzer?

**Comment by shriram** [comment]
I'm not happy with the formatting:

![image](https://user-images.githubusercontent.com/75030/115565786-ae179d80-a287-11eb-994c-f6e6960d93ad.png)

Why is there so much space before the first entry in a section, and so little space after the last entry? I would in fact expect the opposite: a little space before the first question (to separate the header), perhaps a bit less between question and answer, and a bigger jump at the end of a section to visually denote the end of the "list" (and with it, the section).

**Comment by ds26gte** [comment]
I've added:

- 2ex before first question (immediately after header)
- 2.5ex before subsequent questoins (i.e., between previous answer and a question)
- 1.5ex between question and its answer
- 3.5ex after final answer, even if null (immediately before next header)

The dimens I chose are somewhat arbitrary of course. Please let me know your preferred values if you have a strong opinion.

Known problem: There is too little space currently between the datasheet copyright and first header.  @schanzer, I know you've calibrated this very precisely for other scenarios, so I don't want to break it. Do take a look. If it's not tractable, I may have to add a CSS body class specifically for datasheets.

**Comment by schanzer** [comment]
Yes! A custom body class is an excellent idea

**Comment by ds26gte** [comment]
Added a body class `.datasheetpage` only for datasheet pages. Used it in `shared.css` to style vertical space between copyright and first header (in the PDF).

We can actually make fairly involved datasheet-specific styles now.

**Comment by schanzer** [comment]
@shriram does this look good to you?

**Comment by schanzer** [comment]
@shriram ping?
