### ISSUE TITLE
PDF bottom-matter

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#465]
Why does the PDF not have the same bottom-matter as the Web version?

**Comment by ds26gte** [comment]
Deliberate decision. The (single-page) PDFs are only there to become part of a multi-page workbook, and it wasn't thought necessary to slap a copyright notice for every page of the printed book -- it already has a notice in _its_ frontmatter. 

Secondly, we want each single-page PDF to really be a single page, and any additional bottom matter will make this difficult.

**Comment by shriram** [comment]
So the PDFs will *never* be released stand-alone?

**Comment by shriram** [comment]
I don't see how the "single page" criterion is helpful since we're already well over, and we don't want people to not write prose just to fit into an arbitrary page limit?

**Comment by ds26gte** [comment]
@schanzer, I guess we can make an exception for pages such as datasheets/* that are obviously not going to be part of any workbook?   These may well profit from their own stylesheet too.

**Comment by schanzer** [comment]
Good call. Make it so.

**Comment by ds26gte** [comment]
All non-workbook pages now have the bottom matter even in the PDF.

(@schanzer: workbook-page HTMLs (only) now have an additional body class `.workbookpage`.  `lib/shared.css` uses this to identify when not to add the bottom matter for the PDF.)

**Comment by schanzer** [comment]
Fantastic - @shriram, close if you're happy with this?

**Comment by schanzer** [comment]
@shriram ping?
