### ISSUE TITLE
why do all PDFs build every time?

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#466]
Changing one line in a datasheet .adoc results in a bulid (*without `-F`) that takes anywhere from 15-25 seconds. *Most* of that time seems to be spent on "building all PDF files". Why are the PDFs not built on demand?

**Comment by schanzer** [comment]
We have the --nopdf option for this. (wkhtmltopdf is soooo slow, but the only game in town!)

**Comment by shriram** [comment]
Sorry, not so fast. The HTMLs build *by need*. Why don't the PDF's build *by need*? Aren't the two situations precisely analogous?

**Comment by schanzer** [comment]
I'm not sure I understand what you mean. Are you suggesting that it's building all of the PDFs, Even if only one file is changed?￼￼￼

**Comment by ds26gte** [comment]
Actually the individual PDFs for the pages are built on demand. However, the final multi-page workbook PDF which contains the constituent single-page PDFs must be rebuillt even if a single one of the latter is new.

**Comment by shriram** [comment]
Okay, so the tool output is misleading then? It should say "building … .pdf", and then separately "building multi-page PDF workbook" as two separate steps?

**Comment by ds26gte** [comment]
Yes. Pushed 3c93c7a.

**Comment by schanzer** [comment]
@shriram ok to close?
