### ISSUE TITLE
@Bootstrap

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#469]
There are now several references to `@Bootstrap` [https://github.com/bootstrapworld/curriculum/commit/5e009b9a9f496fd3c89282e21f798da61967caad] but none of them seem to resolve to anything: they're just showing up verbatim in the output!

**Comment by shriram** [comment]
HTML:

![image](https://user-images.githubusercontent.com/75030/115566847-9ee51f80-a288-11eb-908b-e800613b6e22.png)

PDF:

![image](https://user-images.githubusercontent.com/75030/115566881-a86e8780-a288-11eb-8440-18ec40c94595.png)

**Comment by ds26gte** [comment]
Please rebuild pathway with `-F` option.  

Any code changes (here the addition of a new directive `@Bootstrap`), as opposed to doc changes, require `-F` to take.

**Comment by shriram** [comment]
I just want to point out that if we had a Makefile, and it had an explicit dependency on the program file, then there wouldn't be need to see which files got updated in a git pull (which sometimes has *numerous* file updates) and hence which build process to run. Running a build would just redo computations if the program file changed and not if it didn't.

**Comment by shriram** [comment]
Confirming that this works after the re-build.
