### ISSUE TITLE
Portrait vs Landscape orientation in workbook

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#47]
It looks like the build automatically puts everything in portrait mode, which is fine - some worksheets will need to be reoriented (Estimation, 3 Reads)

**Comment by schanzer** [comment]
I believe this is fixed. @ds26gte can you confirm and close?

**Comment by ds26gte** [comment]
`lesson-index.rkt` now allows the file members in its list to be given as 
```
("file.adoc" "landscape")
```
or
```
("file.adoc" "portrait")
```
and `file.adoc` will be rendered accordingly. Simply entering
```
"file.adoc"
```
as before renders `file.adoc` in the default portrait mode.
