### ISSUE TITLE
Conditionally optional questions in datasheet

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#470]
The only issue/improvement outstanding from multi-issue #459 (text from @shriram).

There are multiple cases (3?) where the question is of a form:

"Does the dataset relate to people? If not, you may skip the remaining questions in this section."

We need a way whereby a person can use a No tag that you recognize, and if present, it ignores the remainder of the section's questions unless they have chosen to provide an answer.

***

(Currently, I'm ensuring that even conditionally optional questions are marked `.optional`, and that seems good enough, but we may want to keep them `.required` if the leading question is answered in the positive. I.e., they will show up in the datasheet even if they were left unanswered. This complicates the logic and syntax somewhat.)

**Comment by schanzer** [comment]
@ds26gte if this is the only outstanding issue from #459, can we close that and just focus on this?

**Comment by schanzer** [comment]
It appears that datasheets are going to be completely overhauled at some point in the future. Closing this.

**Comment by shriram** [comment]
That doesn't mean this won't still be an issue.

**Comment by schanzer** [comment]
@shriram give the new datasheet work we've got with Code.org, do you still see this issue as relevant?
