### ISSUE TITLE
why is there so much junk in the distribution directory?

### ISSUE THREAD

**Issue by shriram** [bootstrapworld/curriculum#471]
In addition to the `.adoc` files, and `.asc` files, there seem to now also be `.kp` files, two of them.

**Comment by ds26gte** [comment]
These files help reuse of previously built info on subsequent builds.  They should all be dot files, hence invisible during casual file navigation. Are they visible anyway because of how you explore files on your Mac?

**Comment by shriram** [comment]
Ah, I see. They are indeed dots. But I am viewing them in the browser

![image](https://user-images.githubusercontent.com/75030/115797482-0642c280-a3a2-11eb-846f-8581e4dd3eed.png)

which does not respect the convention (and the dot is pretty hard to see). I wonder if it doesn't make sense to put all these files in a separate directory, much like the `compiled` directory that Racket creates — perhaps one called `cached` — so a user both knows to ignore them and is unlikely to inadvertently edit them (which as you recall has been a problem with the `.adoc` files)?

**Comment by ds26gte** [comment]
.dot files further moved into a `.cached` subdirectory to be out of the way.  (fe1c49f6e)

**Comment by schanzer** [comment]
@shriram has Dorai's latest change fixed this to your satisfaction?
