### ISSUE TITLE
Make Design Recipe language agnostic

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#475]
The same dr directive should work for both languages

**Comment by flannery-denny** [comment]
@ds26gte If you're looking for pages to focus in on, checkout `defining-functions/pages/contracts-examples-definitions` and `defining-functions/pages/contracts-examples-definitions-2` in the June 2021 branch. They are not DR pages, themselves, but the fragments they draw from are... ideally they would work in both languages and currently at least the wescheme version doesn't work.

**Comment by schanzer** [comment]
@ds26gte `lessons/distance-formula/pages/line-length.adoc` doesn't seem to handle conditionals properly in Pyret mode.

**Comment by schanzer** [comment]
All known issues fixed by 5e188fb0618dbe1acf6d0fdf1c759105cc0fb55b
