### ISSUE TITLE
Reflect on OK pathway additions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#477]
There are a number of lessons that were written for Oklahoma that are currently "secret". Do we want to offer links to any of them from lesson plans so that other teachers can opt in to using them?

**Comment by schanzer** [comment]
I think it makes sense to keep them reserved for Oklahoma for now, and if anybody asks we can always give out the link. 

We are clearly approaching a point where we want to split the math material into multiple pathways, which is a really good thing! But we aren't there yet, and it's definitely not a priority for the summer.

If you're comfortable with this response, feel free to close. ￼￼￼￼￼
