### ISSUE TITLE
@soln directive

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#479]
Currently, our codebase is littered with:

`(if *solutions-mode?* ....stuff.... "")`

I'd love to be able to replace this with:

`@soln{...stuff...}`

**Comment by ds26gte** [comment]
I take it you meant you want `@show{(if *solutions-mode?* ...stuff... "")}` to be replaced by `@soln{...stuff...}`.

I've pushed this in 02cdba5f2, but for consistency, I've used `@showsoln` as the directive name.
