### ISSUE TITLE
Practice with Piecewise and Booleans

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#48]
Re: Kathi's email 7/1:
_Most of them were doing just fine during the workshop. One of the two who seemed to struggle the most has been asked by his principal to implement with 180 students this year.  He was planning to practice over the summer. It struck me that we have almost no practice materials after the design recipe, so teachers can't really practice booleans or conditionals on their own. This seems a problem we should fix._

We should have a few practice exercises with Piecewise functions and Booleans (not in the workbook). Some ideas:

**Booleans**
`is-hot : Number -> Boolean`
`; consumes a temp, and produces true if it's above 80 degrees`

`is-sunny : String -> Boolean`
`; consumes a forcecast, and produces true if it's "sunny"`

`is-beach : Number String -> Boolean`
`; consumes a temp and a forecasy, and produces true if it's beach weather`

**Piecewise**
`food-review : String -> String`
`; consumes a food, and produces what you think of that food`

**Comment by BootstrapJen** [comment]
Added DR pages for Boolean practice, added activity to Piecewise Functions to practice
