### ISSUE TITLE
fixes to algebra wescheme solutions book

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#482]
- [x] Page 51 word problem rocket height: contract and examples aren’t showing for me.
- [x] Both versions of compound-inequality-solutions.adoc should be merged and cleaned up
- [x] Do you want the credits page to read as it does?
- [x] Do we want notes on the editor on the order of operations notes page? 
- [x] page 14 (Translate Arithmetic Expressions to Circles of Evaluation &Code2) table extension is weird
- [x] page 28 scale function-your name table is weird
- [x] page 29 scale function-xy  table is weird
- [x] page 33 Chinese flag solution a page - should we provide the code they should be circling? looks a little weird to me.
- [x] page 36 - NEED HELP - getting syntax error messages.
- [x] page 38 - combinging images - code break - _remove_
- [x] page 39 decomposing flags
- [x] page 49 is missing contract and examples - writing examples from contracts and purpose statements
- [x] Thought we took page 52 out and were going to link to it as a resource? not sure which lesson it's being referenced from. couldn't find it via "find in files"
- [x] page 62 _rac_ needs fixing
- [x] what's going on with page 69 boolean functions?
- [x] solutions on page 70 (simple inequalities) are printing on top of each other
- [x] page 83. does the solutions page for challengers for update player look correct?
- [x] page 88 solutions page is missing a pair of parentheses in around -4. Also should this page be horizontal?
- [x] page 89 is missing in action
- [x] Solving word problems lesson plan - why is the notice and wonder box off-center?
- [x] Page 4 says “@ifsoln”
- [x] Solutions workbook page 2 (credits) not found (they’re also missing in ok and ds)
- [x] Page 4 says “@ifsoln”
- [x] Solving word problems lesson plan - why is the notice and wonder box off-center?

**Comment by schanzer** [comment]
@flannery-denny are you building with -F? Page 2 and 51 don't have these issues on my machine.

(Page 4 is covered in a separate issue for Dorai)
