### ISSUE TITLE
fixes needed in Ds workbook solutions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#484]
- [x] Page 29 - I’m not seeing solutions to gt & bc
- [x] Need one example for page 52 - samples from my dataset -in case it’s not clear to people how to use this page
- [x] Page 53 & 54. Is it intentional that the two DR pages for helper functions have part of their contracts filled in? Feels strange that we would do that through all 4 examples. We should probably give an example solution to one of them.

**Comment by schanzer** [comment]
@flannery-denny the third item (helper functions have parts of their contracts filled in) is expected: all table functions consume Rows, so it's ok to give that away. However, not all of them will produce Booleans so I've removed that. I also added wording explaining why the Domain is always a Row.
