### ISSUE TITLE
Consider adding more desmos exercises to our materials

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#486]
There are currently none for Simple Datatypes...

**Comment by retabak** [comment]
Before spending time on this task, I decided to see if any other BS teachers have created Desmos things. Here's what I found on Desmos that is not a part of our curriculum. (TBH, I thought I would find more stuff! I'm not especially inspired by what follows, but maybe y'all @schanzer or @flannery-denny will have thoughts / opinions on it, that might inform future Desmos projects?)

- Here's a [cumulative review](https://teacher.desmos.com/activitybuilder/custom/5bcf4154a85e9e0ca3b8b53b) of algebra by Monique Maynard (don't know who that is!).
- Ed Campos (who I know worked for BS previously?) has a Desmos review for each algebra "unit" (even though units no longer exist). Here's [unit 1](https://teacher.desmos.com/activitybuilder/custom/5a1c805bbfc8c40614d3904a), [unit 2](https://teacher.desmos.com/activitybuilder/custom/5a15e268dcb86b2b9fda3ce0), [unit 3](https://teacher.desmos.com/activitybuilder/custom/5b2951eb72d2ff0fdb584e2e), [unit 4](https://teacher.desmos.com/activitybuilder/custom/5b29524435980a2e26b0cc6e). Were these officially a part of our curriculum, or did he create them independently? They could use a bit of polish, in my opinion.

**Comment by flannery-denny** [comment]
@retabak ed made lots of stuff in desmos that needed a lot of polish and if it hasn’t received our attention already it’s because it definitely isn’t worth our time 

Flannery

**Comment by schanzer** [comment]
@flannery-denny totally agree. @retabak don't try to salvage these.

**Comment by retabak** [comment]
@flannery-denny @schanzer - 

Here's the [polygraph](https://teacher.desmos.com/activitybuilder/custom/63236f155568e61d8937cba6
) that I made on correlations. 

I googled a bit and found several others (already created by random teachers) that seem to align with our stuff. Check 'em out if you'd like: [box plots](https://teacher.desmos.com/activitybuilder/custom/5cb8dfd00a54690cad84e626), [scatter plots](https://teacher.desmos.com/activitybuilder/custom/560aa8c858fd074d1561808f), and [functions](https://teacher.desmos.com/activitybuilder/custom/5615f9cc916f89a107df6651).

**Comment by flannery-denny** [comment]
can't wait to see what other desmos suggestions you have :)

**Comment by retabak** [comment]
I cleared the milestone. We haven't figured out specific places where we want to use them. I can maybe brainstorm a list of ideas and share with you and Flannery at our next meeting? (or we can have the discussion right here.)

**Comment by flannery-denny** [comment]
@schanzer we can remove this from the milestone but should not close the issue. We haven’t added them anywhere!

Flannery

**Comment by flannery-denny** [comment]
@schanzer The original goal/title of this issue was to decide whether to add Desmos activities to new lessons that don’t have any.

When @retabak took it on, we set the goal of her identifying 3 desmos features besides card sorts we could be using.

Before we decide what lessons to add polygraphs to, it would be great to identify whether there are any other Desmos activity types well-suited to Bootstrap materials.

**Comment by retabak** [comment]
This issue has shifted its shape a number of times. I don't think my goal was to identify 3 desmos features - it was to actually make 1 or 2 desmos activities.

I'd like for us to revisit this and discuss in person. There are a few ideas / concerns floating around my brain that it think it would be easier to discuss in real time. 

Leaving this issue open for now, but I will add discussing Desmos to our curriculum meeting agenda.

**Comment by retabak** [comment]
Things to think about adding:
- polygraph
- challenge creator
- polypad
- card sort
