### ISSUE TITLE
look at language around circles of evaluation for pyret in order of operations lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#488]
While I know how to convert an expression into COE and pyret code, the language I have for converting COE to code is wescheme specific.

The Order of Operations lesson plan language also seems to be wescheme specific. I think I'd flagged this before for your help, but maybe I forgot? Either way, it needs attention because the ant idea doesn't make sense to me in the pyret context.

> When converting a Circle of Evaluation to code, it’s useful to imagine a spider crawling through the circle from the left and exiting on the right. The first thing the spider does is cross over a curved line (an open parenthesis!), then visit the operation at the top. After that, she crawls from left to right, visiting each of the inputs . Finally, she has to leave the circle by crossing another curved line (a close parenthesis).

Note: There are some cases where the outermost parentheses can be removed from the code and you may see code written that way, but it is never incorrect to include them.

**Comment by schanzer** [comment]
@flannery-denny What about this prose is WeScheme specific? 

You did flag this issue in _another_ location, but that was addressed a while ago.

**Comment by schanzer** [comment]
@flannery-denny I updated the lesson plan text to make this more clear. Let me know what you think?
