### ISSUE TITLE
In Pathway dist, main.html and index.html are redundant

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#49]
Let's get rid of main.html

**Comment by ds26gte** [comment]
This was a convenience. The pathway directory housing the narrative is allowed to have multiple `.adoc` files (which could include each other). If there is only one `.adoc` file, there is no ambiguity as to what the narrative source file is. However, if there are multiple `.adoc` files, it's usually indeterminate which of them qualifies as the narrative's source. In such cases, the basename `index` fixes that file to be the narrative source. However it is chosen, the narrative HTML file is called `index.html` (whether implicitly or explicitly) and so referred to by the final document tree.

I can certainly remove the HTML file that happens to be identical to `index.html`, but was allowing for the fact that a developer working on `main.adoc` usually tends to look for `main.html` to see how it worked out.

**Comment by ds26gte** [comment]
Done in 48d6d6e
