### ISSUE TITLE
Core cleanup to finish asap after June 1

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#490]
**Emmanuel**
Change the lessons-and-standards.rkt file for
- [x] simple datatypes
- [x] contracts
- [x] function composition
- [x] defining values
- [x] defining functions
- [x] inequality1-simple
- [x] defining table functions
- [x] solving word problems

Confirm lesson goals are up-to-date:
- [x] simple datatypes
- [x] contracts
- [x] function composition
- [x] defining values
- [x] defining functions
- [x] inequality1-simple
- [x] defining table functions
- [x] solving word problems

Fix:
- [x] Better-align lesson text and starter files between defining-table functions and table-methods
- [x] make video about pyret starter file
- [x] remove any `xtra/lang-prereq` files
- [x] add "framing around core" to the bookending DS and Algebra lessons
- [x] beautify table image in Defining Functions lesson plan that currently looks like this.
![Screen Shot 2021-05-29 at 4 51 50 PM](https://user-images.githubusercontent.com/66691020/120085536-990c0680-c09e-11eb-8402-7d68945574d2.png).

update slide decks for
- [x] inequality1-simple wescheme
- [x] inequality1-simple pyret
- [x] solving word problems wescheme
- [x] solving word problems pyret
- [x] update links in all algebra slide decks
- [x] Contracts slides (make Pyret starter file w include image)

**Flannery**

Fix
- [x] fix oklahoma contracts pages
- [x] fix all pages not in the workbook!!!

make slide decks for
- [x] function composition wescheme
- [x] function composition pyret
- [x] defining values pyret
- [x] defining values wescheme

Delete files / images not used in lesson plans:
- [x] simple datatypes 
- [x] contracts 
- [x] function composition
- [x] defining values 
- [x] defining functions 
- [x] inequality1-simple
- [x] defining table functions
- [x] solving word problems
- [x] Make inequalities 2 solution files part of the og file

**Comment by schanzer** [comment]
@flannery-denny I believe all of these are now complete. If you'd like to spot-check (and please give me feedback on the new images!), I'll leave it to you to close.

**Comment by flannery-denny** [comment]
Images for defining functions are fine. Ideally they would be the same height as each other.

**Comment by schanzer** [comment]
Closing because the images _are_ the same height -- they're just not the same width, which means shrinking the window does not shrink them both equally. The wider images get squished faster, resulting in the appearance of different heights.

Partially mitigated in d0307ebc5, by giving them more space via a narrower middle row.
