### ISSUE TITLE
Running list of bugs for Dorai to investigate

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#491]
- [x] Narrative pages need their own body class: `narrative`. Otherwise, some CSS rules break the homepage
- [x] Pathways are not building the solution pages for back-matter
- [x] Pathways are not building the combined "Contracts" page in the teacher resources section
- [x] Might as well pipe the wkhtmltopdf errors to >null again, since we know they don't impact the PDF output
- [x] In `solving-word-problems`, `create-examples-contracts-purpose-1` needs to run `sexp->code` in the left-hand side of the examples
- [x] Rebuilding a pathway (non-forced) still shows WARNING: No narrative in pathway algebra-pyret; creating one. Should not check for existence of adoc file, since that gets cleaned up and the check will always fail.
- [x] Most of the pages in `linearity` are throwing "unterminated table block" errors. This is caused by `@ifsoln{}` at the end of a table swallowing the newline, resulting in the terminating table block being put on the same line...which is invalid 
- [x] In all pathways, attributes page is not copied to solutions-pages. This causes the second page of the solutions book to be the "Page Not Found" error
- [x] Certain Design Recipes are not showing their solutions in the PDF, even if the HTML is correct. In `solving-word-problems`, `create-examples-contracts-purpose-1` is an example of this. (POSSIBLE CLUE: if you change `#:headless?` to true in `rocket-height`, you can reproduce the problem on that page as well!)
- [x] Regression: Nuking distribution and then running build-pathway seems to not copy `shared/curriculum.css`?

**Comment by ds26gte** [comment]
Re item abt solution PDF showing less content than the corresponding HTML: wkhtmltopdf --read-args-from-stdin seems the culprit. Rewrote to call wkhtmltopdf individually on each file. Slight time expense.

**Comment by ds26gte** [comment]
Re item about left-hand-side of examples: The problem was that I didn't take into account that an argument could be a function call.  In this case, the single argument was a function call (which is given as an s-expr), which was carried over unchanged. Fix involved recursively applying wescheme->pyret to every argument, instead of just string-joining the top level  arguments with comma separators.
