### ISSUE TITLE
workbook solutions fixes (page number according to pdf)

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#493]
- [x] Algebra - pretty sure that Dorai's contract script is making old style wescheme contracts
- [x] confirming wescheme contracts should have two colons, just like pyret, in which case we need to change : to {two-colons} on the contracts pages

Algebra Wescheme Workbook

- [x] page 92 Comparing Code Finding Missing Distance - I've tried unsuccessfully to get the math and code to align beneath the images. Do you have a simple fix for that? - _ES-they're different widths, so it won't like right to keep them centered. However, I've pushed a change that moves them to opposite sides of the page. Let me know what you think?_
- [x] page 45 isn't built correctly in the last file Emmanuel shared with me - it's missing the y columns of the tables and the function definitions (It built correctly on my computer the last time I built the workbook). - _ES - I can't figure out what's missing on page 45. There's no "y column" in the asciidoc file._
- [x] page 75  Compound Inequality Functions - show code for example! - _ES - I don't understand. Do you not see the code there?_
- [x] page 23 Practicing Contracts: Domain & Range- contracts should be shaded. - _ES - see comment below_
- [x] page 32 Function Composition — Your Name - contracts should shaded  - _ES - see comment below_
- [x] page 33 Function Composition — scale-xy - contracts should be shaded with space above & below  - _ES - see comment below_
- [x] It looks like all of the design recipes take up less vertical space than they used to. If that's true, it would be great to add a little vertical space between the top and bottom problems. - _ES - with the other pages running over, I don't think we can make this happen._
- [x] page 41 - would this page make more sense if we included the code for defining dot and background on the top of the page?

Algebra Solutions book:
- [x] page 12 right side of matching activity is missing the arithmetic expressions. - _ES-in the PDF I sent you?_
 - [x] page 70 seems to be missing the ANS formatting.
- [x] page 14 completing partial code from circles of evaluation #5 has a large amount of vertical space (could live with this if need be) - _ES-we're going to have to live with it for this release. This is a wkhtmltopdf bug that will be very hard to chase down._
- [x] page 12 Matching Circles ofEvaluation and Arithmetic Expressions - for some reason solutions break to next line. I can live with this, but it would look better if it didn't break and flagging because the asciidoc looks like it should work correctly to me so wondering if it's part of a bug.
- [x] page 2 mia
- [x] p95-98 mia

Algebra Pyret Workbook
- [x] page91 - really long fn/example body don't wrap. on 91 this causes "is" to be bumped to another line
- [x] Are you sure you don’t want sexp-> code to build parentheses to match the directions? Page 11-15 (I think at the very least we need to hand-generate the parentheses for "completing the code", which is designed as an early scaffold & doesn't have the parentheses described in the lesson). _- ES - if you want the (optional) parens in the code, @ds26gte is going to need to modify the sexp->code directive. I've opened a new issue for it._
- [x] Page 46 - matching examples & function definitions - code line break is funky - ES - I was able to fix all but one.
- [x] DR - 55-58 Titles are all the same
- [x] Page 94 - word problem is-collide - first and second is build in different spots
- [x] Page 95 - Contracts - first page - inequalities build with ( ) in a different place - are they operators & not functions? Do they not belong on contracts?

Algebra Pyret Solutions Book
- [x] page 62 - Design recipe- rect prism - bad line breaks and indenting cause the page to be too wide, resulting in a shrunken PDF
- [x] page 16 - translate arith to coe 2 - Code for #2. Parentheses are funky. Closing when they haven't opened. Opening without closing. 
- [x] page 47 - matching examples and contracts - code line break is strange
- [x] page 46 - matching examples and function definitions - fix matching solutions

Slides
- [x] Make sure link from contracts lesson to contracts page works [https://www.bootstrapworld.org/materials/fall2021/en-us/courses/algebra-pyret/resources/contracts.pdf](https://www.bootstrapworld.org/materials/fall2021/en-us/courses/algebra-pyret/resources/contracts.pdf

**Comment by schanzer** [comment]
@ds26gte I thought you checked in a fix for the first issue this afternoon? The third item here is related to issue #491

**Comment by schanzer** [comment]
@flannery-denny you want shading on pages 23, 32, and 33. Question: do you want all contracts and code in the workbook to be shaded? We currently have a global rule that turns shading off in the printed books, so I can either

1. Remove the rule, which means everything code-related gets shaded, or…
2. Turn it off only for those pages.

Preference?

**Comment by flannery-denny** [comment]
I think all the other places I thought should be shaded in the workbook were, so let’s turn it off for those three for now, not all.

Flannery 

On Jun 3, 2021, at 8:48 PM, Emmanuel Schanzer ***@***.***> wrote:

﻿
@flannery-denny you want shading on pages 23, 32, and 33. Question: do you want all contracts and code in the workbook to be shaded? We currently have a global rule that turns shading off in the printed books, so I can either

Remove the rule, which means everything code-related gets shaded, or…
Turn it off only for those pages.
Preference?
