### ISSUE TITLE
Try to generate a kid-friendlier message for Sam the Butterfly in Pyret

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#502]
Closing the window currently generates this message in the interactions area `reactor(world(320, 50))`
It's unnecessarily/unproductively intimidating for students exploring the file independently at this stage in the materials.

**Comment by schanzer** [comment]
Ben reminded me that I can use Racket semantics, where evaluating a list of expressions in the body of a function will print out the last expression. Changing this to the Pyret value `nothing` hides the REPL output of a reactor, removing the "scary" output.

Updated the Sam the Butterfly, Rocket-Height, and Game Teachpacks.

**Comment by flannery-denny** [comment]
Awesome!
