### ISSUE TITLE
We need to link non-solutions versions of the contracts pdfs in the contracts pages.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#503]
Currently, the links take us to password protected versions of the documents. 

- [x] @ds26gte are we currently building non-solution versions of the contracts pdfs? If so, how do I link to them.
- [x] Flannery - use @ifpathway & @ifproglang to link to the 3 different versions of this file.

**Comment by ds26gte** [comment]
In answer to the first subitem, where previously you had `...contracts.pdf` now use either `.../pages/contracts.pdf` (for the non-solution version) or `.../solution-pages/contracts.pdf` (or the solution version). I changed a few already.
