### ISSUE TITLE
algebra pyret fixes identified during workshop planning

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#505]
- [x] #507
- [x] I've been really wrestling with how to talk about COE in pyret, but the more I stop working from my wescheme training and just focus on math to circle to code, I'm starting to think pyret might translate more smoothly to coe since the operators go in the same place as they do in math. The catch is that, unlike in wescheme, the operators get located differently in the code than functions do. I'm not sure about using circles of evaluation for functions in pyret. Is it too inconsistent?  I like that the wescheme version of order of operations gets to text and a couple of other fuctions by way of coe.  But I think we should us @ifproglang for this section.  Could you please have a look and weigh in? If you agree, then I think we should also change the three function composition pages to not require coe... and the writing code using defined values to not require coe... I think we could make that be ifproglang specific within those files?
- [x] Do we really want a notice and wonder about the Ninja Cat desmos graph? There are 4 pages about ninjacat. It feels like one should be optional.
- [x] I just cut the notice and wonder for order of operations from the workbookpages.txt doc because this lesson now makes interfacing with a computer optional so the editor exploration is supposed to come in simple datatypes
- [x] This text in the order of operations lesson plan should not be red
![Screen Shot 2021-06-24 at 10 08 33 AM](https://user-images.githubusercontent.com/66691020/123288403-27747c00-d4d5-11eb-911c-b4fe71278be8.png)
- [x] Can you add the extra parentheses into the code in this notes section while you're at it?
![Screen Shot 2021-06-25 at 11 36 27 AM](https://user-images.githubusercontent.com/66691020/123457621-b6eb5f00-d5a9-11eb-8215-232e27705cf6.png)
- [x] I feel like this page was supposed to have more parentheses and they got removed during the automation of things. Was going to fix it myself, but I'm not 100% sure which ones you would add in.
![Screen Shot 2021-06-25 at 11 46 54 AM](https://user-images.githubusercontent.com/66691020/123458859-23b32900-d5ab-11eb-851c-44ddd46a56de.png)
- [x] Simple Datatypes lesson plan has an asterisk in front of lesson slides. I'm not seeing a mistake in the asciidoc file.
![Screen Shot 2021-06-25 at 12 16 32 PM](https://user-images.githubusercontent.com/66691020/123461927-519a6c80-d5af-11eb-8b42-5356e41f5cc7.png)
- [x] since minimum-wage is actually different all around the country, I'm recommending we change the problem from _minimum-wage_ to _wage_ pushing a fix. hope it works for you.

**Comment by schanzer** [comment]
We discussed the COE for Pyret, and I've made a new issue for Dorai re: workbook page integrity.
