### ISSUE TITLE
DR Print issues

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#51]
The (invisible) purpose statement content overflows the DOM node, generating a scrollbar when we print. Need to find a way around this.

**Comment by ds26gte** [comment]
Removed `overflow: auto` from `.recipe_purpose`  (in `curriculum.css`)

**Comment by ds26gte** [comment]
Purpose statement made empty string rather than long string of invisible `M`s when not showing. Fix in 28b9fa0
