### ISSUE TITLE
Update message in compound inequalities starter file

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#511]
Currently the message says, "All regions shaded blue are part of the solution" It would be more precise to write "all  regions shaded blue or marked as green are part of the solution"
![Screen Shot 2021-07-12 at 10 29 41 PM](https://user-images.githubusercontent.com/66691020/125385847-e5ff2000-e360-11eb-89db-cb2f63bd0617.png)

**Comment by schanzer** [comment]
It's easy to change this, but I'm not convinced that's a better message. We don't have any regions shaded green - only points. There's an important distinction between these two!

Is your concern purely about wording, or about the _visual appearance of those points?_

**Comment by flannery-denny** [comment]
purely about wording

**Comment by schanzer** [comment]
We can talk more about this in our call, but I'm not clear on what the wording concern is. The only regions on these charts are blue, and they _do_ represent solutions.

**Comment by flannery-denny** [comment]
we decided to address this in the lesson plan and the workbook page
