### ISSUE TITLE
Sam the butterfly lesson plan page numbering looks off

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#512]
I'm looking at this [Sam the Butterfly lesson plan](https://www.bootstrapworld.org/materials/fall2021/en-us/courses/algebra-pyret/lessons/inequalities3-sam/index.shtml) and the pages referenced are 58 and 59. In the pdf I have, Sam pages are 72-74.

**Comment by flannery-denny** [comment]
doesn't seem to be isolated to one lesson plan... 
I'm also seeing a similar issue with the distance lesson plan....

**Comment by schanzer** [comment]
All the page numbers for this lesson are correct, and I've checked two other lessons as well. When you say "the PDF I have", I assume you're talking about either the one on the website or one you've built yourself after a fresh pull?

**Comment by flannery-denny** [comment]
I am referring to the last PDF you uploaded to lulu & sent me over slack.

**Comment by schanzer** [comment]
@ds26gte has found and fixed the bug. Thank the stars!
