### ISSUE TITLE
netherland, ireland, mauritius starter file linked from teacher resources page (pyret) isn't running

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#513]
[teacher resource page](https://code.pyret.org/editor#share=1-fMBwqwUBIz2JYNFHmNa159uFTAClGrF)
[netherland, ireland, mauritius, ](https://code.pyret.org/editor#share=1-fMBwqwUBIz2JYNFHmNa159uFTAClGrF)

**Comment by schanzer** [comment]
Closed by 0f6ac7d
