### ISSUE TITLE
Solutions book pdf available in teacher resources is missing arithmetic on page 7

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#515]
[solutions book linked from teacher resources](https://www.bootstrapworld.org/materials/fall2021/en-us/courses/algebra-pyret/resources/protected/workbook-sols.pdf). I suspect it's not updated, as the page numbers also don't match the version of the workbook that I am looking at.

**Comment by schanzer** [comment]
fixed, now that Dorai's wb page fixes are in
