### ISSUE TITLE
Dependency calculation seems off

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#517]
See https://www.bootstrapworld.org/materials/fall2021/en-us/courses/data-science/lessons/checking-your-work/index.shtml

The lesson relies on table-methods, which _definitely_ rely on other lessons that come before. We should see more lessons starred in the lessons table. I think we're only calculating immediate dependencies here, not transitive ones.

**Comment by ds26gte** [comment]
checking-your-work depends on defining-table-functions, which relies on table-methods and defining-functions, all three of which are shown. table-methods depends on defining-functions, which is already accounted for. defining-functions depends on defining-values, but the latter is not in data-science's lesson-order.txt, so is not shown.

I don't see a transitivity failure.

**Comment by schanzer** [comment]
Doesn't defining-functions have dependencies of its own?

**Comment by ds26gte** [comment]
Only defining-values, which is not an included lesson in data-science.

**Comment by schanzer** [comment]
ACK. Fixed.
