### ISSUE TITLE
look at compound inequalities workbook pages and think about how to address green and red circles and their inclusion in shaded areas

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#518]

**Comment by schanzer** [comment]
@flannery-denny didn't we agree to update the wording in the lesson plan for this? Is there more you wanted to change?

**Comment by flannery-denny** [comment]
For this year, we wanted to address it in the lesson plan. I didn't do
that, maybe you did.
For future workbook runs, we should address it on the workbook page. Maybe
we should open a new issue called workbook changes to make in Spring 2022
to catalog the things to address in the spring?

**Comment by schanzer** [comment]
I've created a `spring2022` branch for these fixes. no need to wait!

**Comment by flannery-denny** [comment]
@schanzer I decided the most useful place to make the adjustments was in the FALL 2022 Starter Files for both Simple Inequalities and Compound Inequalities.  Feel free to look at them and make sure you think the wording is an improvement.
