### ISSUE TITLE
Sidebar enhancements

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#519]
Based on feedback from Eric:

- [x] checkbox inside "Lessons" list, with label "only prerequisites". When checked, hide non-prereq lessons
- [x] should be moved to the left, not right
- [x] we need a title called "Toolbar", with a unique id (or unique classname) so I can use CSS to aid discoverability
- [x] Add "texbooks" box, just like "Standards" (invisible for now, but needed for testing now that various alignments are about to land)

**Comment by ds26gte** [comment]
What's some sample input data for the proposed "textbooks" (sic?) portion of the sidebar?

**Comment by schanzer** [comment]
See `shared/langs/en-us/textbook-cm-dictionary` specifies the id->longname description, exactly as the standards and badges dictionaries do. 

I've just pushed a demo `lessons-and-textbooks.rkt` dictionary, which will be used to associate lessons with textbooks.
