### ISSUE TITLE
Slide issues

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#52]
- [x] Any time we're showing code on the slides, we need it to be formatted using a monospaced font (ideally Courier New).
- [x] I don't see "circle and label" anywhere on the slides for Defining Functions, nor is it in the lesson plans. How will teachers and students know to do this?

**Comment by schanzer** [comment]
@edcamposjr22 , you're the keeper of the slides. Can you address this?

**Comment by edcamposjr22** [comment]
I fixed the font issue a while back and I just added the "circle" and label" on the slide. The "circle and label" issue is mentioned in the lesson under Keypoints.

**Comment by schanzer** [comment]
Thanks!
