### ISSUE TITLE
Audit slide decks for old links and page numbers

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#526]
They are completely off in the the Restating the Problem slide deck. Guessing there are a number of other decks from the final push to check off #490 that still reference page numbers.

**Comment by schanzer** [comment]
In which decks are you still seeing page numbers?

**Comment by schanzer** [comment]
Completed -- I searched for "Page " in every Fall2021 folder inside the curriculum folder, with a filetype of "Presentation". Fixed about a half-dozen slides.
