### ISSUE TITLE
Consider adding mood generator starter file to algebra as an additional resource

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#527]
This would also need to include a WeScheme version of the file

**Comment by schanzer** [comment]
Note: Data Science (and mood-generator) uses the `if/then` construct, while Bootstrap:Algebra uses `ask`. We'll need to standardize on one of them, and then update all uses of that construct in one pathway.

This will be a *breaking change*, since it means invalidating some workbook pages.

**Comment by flannery-denny** [comment]
exciting! look forward to hearing the thinking behind why they are
different at this point.
In the Oregon Algebra pd I had teachers work with mood generator after they
worked with alice's restaurant. They noticed that the code was different (I
hadn't) but were ok with the idea that you could do things more than one
way.  And some of them shared that working with the mood generator file was
a highlight for them in their reflection for that day.

**Comment by schanzer** [comment]
Closing, now that this is subsumed in #590
