### ISSUE TITLE
consider scaffolding for update-target and update-danger in pyret

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#536]
The function takes in both x & y, even though it's only responding to x.

1. Make sure that, if we leave it this way, all students engage with Design recipe problems that take in two numbers before getting to this point
2. Is it possible to only take in x? That's how it works in scheme. Feels like an unnecessary layer of complexity...

**Comment by schanzer** [comment]
1. Our best bet is to modify the lesson plans here. We can't change the printed workbook at this point. :(
2. Pyret isn't flexible the way Scheme is here. We _have_ to take in 2 inputs if we think we'll ever want them.

**Comment by flannery-denny** [comment]
@schanzer Confirming you modified  the lesson plan before closing this

Flannery
