### ISSUE TITLE
Triangle Contracts updates for v2

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#539]
- [x] Include an image of a right isosceles triangle to support readers in knowing what we're talking about
- [x] teachers assumed isosceles would follow base - height. suggest using detailed contracts for the two functions on this page and move the others to the other page. Perhaps doing isosceles before right would also solve the problem?

**Comment by flannery-denny** [comment]
@schanzer can I add this isosceles triangle image into the page now or do I have to wait til next year?

**Comment by schanzer** [comment]
Add it - as long as it doesn't detract from what's already there.
