### ISSUE TITLE
side bar suggestions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#541]
- [x] I don't think the textbook alignment should be titled "Connect Mathematics Standards". Perhaps "Related Connected Mathematics Project Units" or "Related CMP3 Units"
- [x] If no prerequisites, standards or textbooks exist, we should show "none". An empty box of lessons or an empty list of standards looks like a web page glitch
- [x] Unless you mouse over them, the mathematical practices are impossible to read, and therefore not so helpful. Any way to make them legible?
- [x] the "toolbar" label is an improvement over previous iterations... but, if you scroll down and then mouse away the purple title is hidden and it feels like the sidebar has disappeared... perhaps that's a good reason to expand the text "lesson pathway, standards & practices"

**Comment by schanzer** [comment]
@flannery-denny what would make them legible? Are you just asking if they can be made larger?

@ds26gte see the second checkbox

**Comment by flannery-denny** [comment]
@schanzer. yes. they need to be larger

**Comment by ds26gte** [comment]
@flannery-denny Do you mean when there are 0 lessons/standards/textbooks/, the entire subsection in the sidebar should be missing, or that there should be the word "None" displayed under the subsection title?

**Comment by schanzer** [comment]
The word `None` should be displayed.

**Comment by ds26gte** [comment]
None is now displayed for empty standards and textbooks sections in sidebar.  (The lessons subsection will never be empty, as it will contain at least the current lesson.)
