### ISSUE TITLE
Resolve build-file directive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#543]
Having ./build-file eliminates access to ./build-pathway by tabbing from ./b
Last I heard ./build-file has never been fully implemented.  
Can we either decide we want it to work and use it or get rid of it, please?

**Comment by schanzer** [comment]
I think we can safely get rid of it. @ds26gte 's refactoring a few months back have made unforced builds _incredibly_ fast (<1m even for massive pathways like ok).
