### ISSUE TITLE
DS-Intro worksheet  "Can the given data answer this question?"

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#547]
Extra exercises for ds-intro - Can the given data answer this question? (from Need exercises about whether data can answer a given question curr#449)

**Comment by flannery-denny** [comment]
I converted the page on the cyclist's ride data from the previous structure
to a structure without compute, lookup, relate. Lmk if that's what you were
hoping for.
(also, am I missing something or are the average speeds wrong? when I
divide distance by time I get other values... didn't change them in case
flight altitude has made me forget something obvious, but, if they're
wrong, I'd like to fix them before we put them out in the world.)

If the new version of this page is what you're looking for, I can come up
with another mini dataset for another similar page..
In my mind, the extensions of this page would be to make a page with space
for them to describe *how *they could answer the question (without actually
doing the math). They don't know how to do it with code yet, but being able
to describe what they would want the code to do is the precursor...

The page might even end with a prompt to go back and see if there are any
questions that they think could be answered in more than one way.

**Comment by schanzer** [comment]
This is _exactly_ what I was hoping for! Awesome.

This chart was put together by an actual cyclist, and IIRC she uses different time counts for _total time from departure to return_ (including stops) vs. _total time when in motion_. If this feels counterintuitive, I don't mind you changing the values.

I like your extension idea a _lot_. I think fewer questions-per-page with deeper extensions would be a nice way to go here.

**Comment by flannery-denny** [comment]
@schanzer. Pushed an updated page. Please take a look at shrinking web font size so that the table reads better.  I think this page probably gets added before meet the animals. Would you agree?

**Comment by schanzer** [comment]
@flannery-denny I've updated the page formatting, and it now looks very close to the PDF. If you're happy with this, feel free to close!

**Comment by flannery-denny** [comment]
@schanzer I added a section to the lesson plan in [commit](https://github.com/bootstrapworld/curriculum/commit/1c084b7407fef9f5ef252969d58d1accbd260182). If it works for you, lmk and I'll update the slide deck accordingly.

**Comment by schanzer** [comment]
Looks good to me!

**Comment by flannery-denny** [comment]
slide deck updated
