### ISSUE TITLE
Matching pie-charts w/bar charts (add to `displaying-categorical-data` lesson)

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#548]
- [x] pie chart to bar chart page

**From Flannery**
Awaiting confirmation that @schanzer wants me to make the following. They would take very little effort and I think that they would be more valuable to teachers than the additional page I had already proposed.  How do these ideas sit with you?

- [x] 4 bar charts - notice and wonder (axes heights will vary, distribution will vary, racial demographics will vary, some will have gaps, some won't)
- [x] 4 pie charts - notice and wonder
- [x] mix bar & pie chart - notice and wonder
- [x] sj extension - school district v city comparison for a couple of locations some where the pop and school mirror each other more closely and some where they diverge. I'd probably also make this a notice and wonder rather than a super scaffolded activity.

**Comment by flannery-denny** [comment]
@schanzer I've drafted a pie-chart to bar-chart page and a bar-chart to pie-chart page, but I don't think it's actually what we want. 

I propose:

1.  one page where students match pie charts to bar charts - these will be major schools districts whose distribution varies 
2. a notice and wonder page with 4 bar charts at the top (axes heights will vary, distribution will vary, racial demographics will vary, some will have gaps, some won't)
3. a notice and wonder page with 4 pie charts at the top
4. a notice and wonder page with a mix of pie and bar charts

How does that sit with you?

**Comment by flannery-denny** [comment]
@schanzer I've pushed a draft of the file. I can't tell if it fits on the pdf because I can't actually build a pdf at the moment... If I were more proficient at inspecting an css magic, I would remove padding between the school district names and the plots they describe. If we could fit 5 on a page, I definitely have another pair.

**Comment by flannery-denny** [comment]
@schanzer 
Where does the matching pie-charts and bar charts page go? It’s currently in the displaying categorical data lesson, but I don’t see an obvious place for it in the lesson plan.

**Comment by schanzer** [comment]
This should go in the first section "Displaying Categorical Variables", since both pie and bar charts are for displaying categorical data.

**Comment by flannery-denny** [comment]
@schanzer - Do you feel good about all of these pages being left open ended as notice and wonders? Feel fine about the last two pages using pie charts or wish one of them used bar charts instead? 

If they're good to go, I'll figure out how to add them to the lesson plan.

**Comment by schanzer** [comment]
@flannery-denny These pages look _great_!

* The shading on the tables is off. I fixed it by adding `stripes=odd` to the asciidoc table syntax.
* "Do NYC Schools Reflect the City’s Diversity?" -- text at the top references the beginning sentence of the report. I feel like there's a missing sentence here, in which you ask students to do something with this information.
* "Matching Bar Charts to Pie Charts" - this only prints with room for three of each.  I tried shrinking the images a little, reducing some unused vertical space, and even moving the school district name into the pie-chart image. No matter what, it doesn't let me fit the fourth row on the same page. Are you ok removing one of them?

**Comment by flannery-denny** [comment]
@schanzer Please have a look at the Displaying Categorical Data lesson plan start to finish and [commit](https://github.com/bootstrapworld/curriculum/commit/91e8a580ccdd7d1ec6e028c36d3cf03ad7a2c184). I wonder whether plotting practice belongs somewhere earlier in the lesson plan rather than in additional practice section.  If it all works for you, I'll update the slide deck.

@retabak. I wish I understood your @codaplang work well enough to know whether the changes I made in the last commit under common misconceptions should all be copied into the codap section, but I don't yet. Please have a look at the commit and see whether I've made more work for you. Thanks!

**Comment by schanzer** [comment]
@flannery-denny notes on the lesson:

- As I'm reading the "Note for Teachers on Sex & Gender" explanation with fresher eyes, it looks like the point of that box is to explain that "hermaphrodite" is not meant to be used for people. But the _title_ of the box leaves me expecting to see an explanation of why the column is called "sex" instead of "gender". The first two sentences in the box serve that purpose quite nicely. If you want to keep the rest, maybe re-title the box "People aren't hermaphrodites?" But then again, is that an important note for teachers at this place in the curriculum?
- I moved the histogram wording a little. 
- Overall I really like this. The practice plotting section needs to go at the end because it's the least important part of the lesson - we'd rather teachers focus on the bar/pie chart learning goals! I could also moving the "practice plotting" section entirely into an optional worksheet next year, so the lesson **really** focuses on pie and bar charts. Then your additional pages would become an official part of the workbook, swapping places with the plotting ones.

Once you've updated the deck, you can close this off as well! You're on a tear!

**Comment by flannery-denny** [comment]
I think the box about sex gender & hermaphrodites is important because we don’t want to set people up to have to answer important questions they have no framework for. I’ll retitle it on Tuesday.

Flannery
