### ISSUE TITLE
Creativity! (Make an infographic?)

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#550]

**Comment by flannery-denny** [comment]
@schanzer 

- Curious how you see this infographic intersecting with the curriculum. Is it its own lesson? Is it getting added to the displaying categorical data lesson? 
- Which of the ideas in [this slide deck](https://docs.google.com/presentation/d/1kTKQ-GYplCFEdBEbL26ILwTBrMab2aC6g6BDVuiymbI/edit?usp=sharing) are most interesting to you.  
- One of the suggestions is about inserting images into pie charts and bar charts. Excel can do that. Sheets cannot. How do you feel about suggesting that people interact with excel?

**Comment by flannery-denny** [comment]
@schanzer - confirming that you now have access to the file

**Comment by schanzer** [comment]
Confirmed! Will reply by tonight.

**Comment by schanzer** [comment]
@flannery-denny 

- For now, I think of this as a mini-project (like "stress or chill", for example). Down the road it could easily become its own lesson.
- Wow, a lot of great ideas there! Slides 2, 3, 5, and 8 are most interesting to me. I particularly like the idea of students having a choice to do a digital or analog infographic.
- I think we should be tool-agnostic here. Some kids will want to grab the charts produces by Pyret or CODAP and put them into google slides, while others will use photoshop, canva, or god knows what. :)

**Comment by flannery-denny** [comment]
@schanzer I'd like to take a look at "stress or chill".  Find in files does
not turn up anything under that phrase. Can you help me to find it?

**Comment by schanzer** [comment]
It's in the "measures of spread" lesson: https://github.com/bootstrapworld/curriculum/blob/master/lessons/measures-of-spread/langs/en-us/pages/stress-project.adoc

**Comment by flannery-denny** [comment]
@schanzer 

1. Is it important to you that the infographic mini project has the same kind of subheadings as the stress project: the issue, objective, procedure, produce? I haven't tried working with them yet, but I don't think about them quite so linearly.
2. Would you like me to include example images of student work?

**Comment by flannery-denny** [comment]
@schanzer Fyi - In addition to images of my students' infographics, I got
permission from Mona Chalabi to utilize (& credit) images of her
infographics

**Comment by flannery-denny** [comment]
@schanzer.  If there are enough details in this as is, please close the issue. If it needs more words, lmk whether they would go in the task, the strategies or both.

**Comment by schanzer** [comment]
This is _fantastic_. Better than I could have hoped. Can we thank Mona via social media, to recognize the contribution of her and her students?

**Comment by flannery-denny** [comment]
Mona chalabi is not an educator. She’s my favorite data designer - I recommend checking her out! But, good idea, we should thank her on social media some day :)

Flannery

**Comment by flannery-denny** [comment]
@retabak If you think a rubric for the infographics projects would be useful to teachers, and feel that writing rubrics is a strength of yours, I'm totally happy to see you take that on!  The algebra teacher resources page offers this [rubric](https://docs.google.com/document/d/10YYUmMbE77VwC3W24yZykZe1I0ELL_jE2_NQyH473MY/edit?usp=sharing) for grading design recipe problems in the teacher resources section. I understand the utility of rubrics, and struggle with the things that rubrics inevitably leave out.

**Comment by retabak** [comment]
Challenge accepted!

**Comment by retabak** [comment]
Here's a draft of a rubric!

https://docs.google.com/document/d/1ibCZKFFofDYQhF7_3mLcZryIkfhg3-PyMyr7Tjmn0AU/edit?usp=sharing

I realized that when I make rubrics, I build a lot of process stuff into them normally that is probably unique to my classroom (i.e., student participated in partner brainstorming, etc) so I left that out. It's pretty brief as is, but this is just a mini project so I suppose that makes sense!

**Comment by flannery-denny** [comment]
@retabak Do you want me to turn this rubric into an asciidoc? Or do you want to give it a try?

**Comment by retabak** [comment]
Done!  My first asciidoc!  :tada:
It's located here: lessons/displaying-categorical-data/langs/en-us/pages/infographic-rubric.adoc

@flannery-denny  - responded to your feedback and added a row to address the importance of avoiding stereotyping. Let me know what you think.

@schanzer and @flannery-denny  - happy to respond to any feedback on formatting or content.

**Comment by schanzer** [comment]
@retabak I committed a small change that makes the asciidoc code a little more readable. I'll let @flannery-denny chime in on the content in more detail, but overall I like what I see here!

Finally, this should be linked from both the lesson plan and the infographic page itself.

**Comment by flannery-denny** [comment]
@retabak This looks great. One small nit - I don't think it makes sense to title the first column "Name". If you want to make a spot to write the student's name, put it above the table and use `@fitb` to make a blank to write the name on.  

We need to add links to this to:

- [ ] the lesson plan
- [ ] the lesson slide deck
- [ ] the infographic page.
- [ ] the data-science teacher resources page?

Lmk if you want help with any of that.

**Comment by retabak** [comment]
OK! Added links everywhere except the data science teacher resource page. The only other rubric we have (Joy's, for the final project) is sort of uniquely placed near Project Files, because it is so relevant to the project. 

Maybe a mini project rubric doesn't belong here? What do you think, @schanzer ?

@flannery-denny thanks for the assistance with this! :)

**Comment by flannery-denny** [comment]
@schanzer 

1. I think it makes sense to have a section on the teacher resources page for mini projects.  I think these are compelling and should maybe go right at the top and we have several that it would be nice to make more visible to teachers. There could be a section where they're listed or they could be listed on a separate page that you get to from a link called projects, located just below the workbook.
2. Makes sense to me that we would rename the `Project Files` Section to `Research Paper Files`. These could be at the bottom of the page and be linked to, just as we link to the datasets from the materials section of the `choosing your dataset` lesson.
3. Looking at the page I'm noticing that the vertical spacing of the Exercises and Solutions area (auto generated by `@all-exercises` has a lot more `@vspace` than other parts of the page. Can we adjust that?
4. I'm also noticing that there are a lot of resources at the top of things that we like but didn't make. I wonder whether they should be under a separate heading? Ideas?

**Comment by schanzer** [comment]
@flannery-denny 
1. GREAT idea. I totally agree. Do you want me to take this, or are you comfortable enough with asciidoc to give it a go?
2. Agreed. Once again, who owns it?
3. Do you mean the spaces between lesson titles? Or just the space _before and after_ those titles?
4. I don't think a lot is gained by sectioning off the 3rd party resources. In some ways, I think it's strength to present our materials as playing well with others!

**Comment by flannery-denny** [comment]
1 & 2) I'll tackle what I can. 
3) I mean the space between lesson titles.
4) ok

**Comment by flannery-denny** [comment]
@schanzer I've done what I can with updating the data science resource page. I think it's much better. I kind of want to be able to link to the two kinesthetic playdough activities from the Teacher Resources Page. Would you agree? If so, ideas on how to do that?

**Comment by retabak** [comment]
LOVE the idea of a mini-projects page! Excited to take a peek at Flannery's
updates tomorrow!

**Comment by schanzer** [comment]
Closing, since this is complete. I'll update the website with the new materials once `jsmakeworkbook` is merged, probably later today.
