### ISSUE TITLE
Alignment one-pagers

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#553]
- [x] generate prose for IM teachers about what would be exciting about Bootstrap to them
- [x] generate prose for CMP teachers about what would be exciting about Bootstrap to them
- [x] @schanzer adds 3-4 sentences of CS prose at the bottom of each page
- [ ] @ds26gte is adding code to the IM textbook file to allow the side bar to include Unit titles.
- [x] asciidocify a template from the mockups

**Comment by flannery-denny** [comment]
In our meeting today @retabak and I committed to sketching what we want the one pagers to look like. 
@ds26gte is adding code to the IM textbook file to allow the side bar to include Unit titles.

**Comment by flannery-denny** [comment]
@schanzer - based on Kathi & Shriram's feedback over the weekend, do you think we're ready for asciidocs? Would you be willing to take on adding the CS goals for these pages?

**Comment by schanzer** [comment]
@flannery-denny spoke to Kathi today. I think I know where to take this now.

**Comment by schanzer** [comment]
@flannery-denny @retabak First asciidoc template is up! There's a lot of work to be done, but let me know what you think so far.

**Comment by flannery-denny** [comment]
where do we find it?

**Comment by flannery-denny** [comment]
@schanzer. I see it's probably here,

/langs/en-us/resources/pages/cmp-grade-6.adoc

but how do we build it?

**Comment by schanzer** [comment]
build the algebra pathway as you normally would. It's in the resources/pages folder (though currently not linked from anywhere else)

**Comment by flannery-denny** [comment]
@schanzer - great start. 

- I think there needs to be some sort of vertical break between the left and right column. In the mockup it was a thin white line.
- The header column feels to tall to me
- The box plot is illegible in its current darkness and transparency. I think we can do better with that image.
- I'm not sure that the blue frame is doing us any favors. I'd rather have the color blocks be that wide and the titles of the block sections get to be larger.
- I don't think that "created with partial support from" should be bold and black.
- I like that the logos are all the same size now. And, it make NSF pretty tiny. I vote we give them back their full logo. For me, they're the organization that has the most clout on me taking folks seriously... and it'd be ok if it had to make all of the logos a little smaller.

**Comment by flannery-denny** [comment]
@schanzer even when I force build with --book I'm not able to view it as a pdf. Makes sense to me that we want to view it in pdf form. Can you put it in sample in such a way that we can see it as a pdf? That would make giving feedback much more efficient for all 3 of us.

**Comment by schanzer** [comment]
@flannery-denny vertical break added. Do you mean the header _row?_ If so, I've slimmed it down by just a few pixels. 
 Made the boxplot less transparent

Sorry, I should have said something about the blue frame: it's just there so you can see the edges of an 8.5x11 page, and get a feel for the margins.

"created with partial support from" -- this is what's in your gdoc, so I just matched it. Still sure you want me to change it?

Used the big NSF logo, but to make room I had to kill off the Infosys one. That's fine, actually - they only funded CSPdWeek, not us directly. 

It occurs to me that it might be good to have our website somewhere on the page, so I added it at the bottom.

**Comment by retabak** [comment]
This looks great! I don't have a lot of feedback.

Are we going to add hyperlinks to the relevant BS lessons? (Would it be valuable to hyperlink to the CMP lessons too?)
The bottom row in grey seems a little sad; can we go with a more vibrant color?
The logos at the bottom look really nice, and I like the inclusion of the link to our website.

Not ascii-related, but: It feels a little crowded to have two images included for surface area. Maybe we can pick just one? (That would also decrease the height of the yellow box, which is quite large at the moment.)

**Comment by flannery-denny** [comment]
@retabak If we slim the surface area images to one, the one that's actually
original to us is the black and white one. Does that sit ok with you?

@schanzer The numbers on the box plot are still illegible. Ideas on how to
get a clearer image out of pyret?

I still don't like the black text at the top and bottom.  It is that way on
the google doc, but not because I liked it ;) and it looks harsher in the
font on this webpage than it does in the font on the google doc.  I might
have to live with it, but I wonder what it would look like if we matched
the text color at the top and bottom to the bootstrap title. Or
whether @retabak might have other ideas.

At the very least, we have to get rid of those hideous yellow links. And
maybe putting a little more space between "created with partial support
from" and the logos would help? Rachel's original proposal had that text in
a dark blue or purple.

It looks like the logos on the bottom are left-justified rather than
centered. And I don't think the line above the logo is doing us any favors,
particularly because it's not the same length as the one below the logos.
A comment of Kathi's that we are ignoring is that she requested we use the
other bootstrap logo. Are we ok with ignoring that feedback?

Seems the next step is figuring out how the doublesided formatting works
for a  page with more content, like CMP 7.

**Comment by schanzer** [comment]
@flannery-denny @retabak 

I think starting with a better image is best way to improve boxplot legibility. I picked a different one which obviously doesn't fit the sample you created, but I'm not married to it and I don't mind if you want to replace it. Just use a screenshot from an already-small boxplot window, instead of scaling down a larger one.

I made the heading colors purple, but I have to say I think black looks a lot better. 

Yellow links are gone, and added space above the logos. Centered them on the screen.

I never heard any response to Kathi's feedback on the logo, so I assumed you'd chosen to ignore it. Let me know if you want to change it? Personally, I think it's a shame we never use the tagline, and I don't have any beef using an image here that isn't on our website.

**Comment by schanzer** [comment]
@flannery-denny @retabak Spoke with Kathi and Shriram, who made some convincing arguments about why we should list our funders on the website, but not necessarily these one-pagers. Let's discuss during our remix meeting tomorrow, then finalize the formatting.

**Comment by retabak** [comment]
@schanzer @flannery-denny 

The only new concern I might raise is that I miss the visual impact of the bullets. The middle (yellow) section now sticks out because it's both the longest by a lot and also the only section with bullets. (It also has three images! Let's please reduce to two; I think I'd be OK with just the B&W image there? Or perhaps we can find a different one?)

As for other concerns in this issue: 
- I kinda like the purple text! But I don't think I ever took issue with / was bothered by the black text.
- I very much prefer "Computing creatively + thriving mathematically" as the tagline for this specifc document. Makes more sense than the other one in this context.

**Comment by flannery-denny** [comment]
I'm not seeing the purple text @retabak is referring to (and I remember
from somewhere along the way). And, for some reason, the black text at the
bottom inviting them to visit our materials isn't centered any more.

**Comment by schanzer** [comment]
That's odd - here's what the heading looks like on my machine:
![image](https://user-images.githubusercontent.com/77126/134106939-310debaf-89ea-47e7-99dc-c26884159e67.png)

Is your heading text black?


And the text at the bottom is off-center?
![image](https://user-images.githubusercontent.com/77126/134106990-6370a69e-b1a0-44e7-8e9a-ba3072a6f555.png)

Can you post a screenshot of what you see?

**Comment by flannery-denny** [comment]
I was expecting all of this screenshotted text to be purple and the bottom
screenshotted text to be centered. The centering of the bottom text is
definitely important to me.[image: Screen Shot 2021-09-20 at 7.28.27
PM.png][image:
Screen Shot 2021-09-20 at 7.28.47 PM.png]
