### ISSUE TITLE
website bugs to fix

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#555]
- [x] On [https://www.bootstrapworld.org/materials/algebra/](https://www.bootstrapworld.org/materials/algebra/), there is a section about wescheme or pyret that looks like this

![Screen Shot 2021-08-10 at 10 31 35 PM](https://user-images.githubusercontent.com/66691020/128965582-568139c1-d455-4fa8-80ff-173215a891bb.png)

The **Bootstrap:Algebra in WeScheme** links takes you to https://www.bootstrapworld.org/materials/courses/algebra-pyret

- [x] The links from this hour of code page are broken[https://bootstrapworld.org/materials/latest/en-us/courses/hour-of-code/](https://bootstrapworld.org/materials/latest/en-us/courses/hour-of-code/)

Thanks to @retabak for noticing!

**Comment by schanzer** [comment]
Ah, it looks like the HOC links were pointing to `index.html`, rather than `index.shtml`! Back in the day all of our files were normal html files, but remix moved those to shtml. Fixed.
