### ISSUE TITLE
website workbook page suggestion

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#556]
How about adding another sentence here that says "Join our mailing list or follow us on social media to get updates as we add more workshops for the coming year!"
![Screen Shot 2021-08-13 at 3 08 59 PM](https://user-images.githubusercontent.com/66691020/129413530-7bfc1763-09e6-4306-ab8e-7dbf02ca42a3.png)

**Comment by schanzer** [comment]
We don't have a mailing list, per se, but we do have a form in which someone can request a workshop. I changed the text to be in line with @flannery-denny 's suggestion
