### ISSUE TITLE
Discourse reorganization

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#558]
- [ ] Set discourse settings so that all users can turn on notifications for tags and categories. 
- [x] Figure out how to feature the best posts with clear subheadings:
- Updates from the Bootstrap Curriculum Team
- Resources from Bootstrap Classrooms
- Pedagogy
- Building content knowledge for educators 
- Humor
- Debugging
- Course Outlines & Integration?
- Workshop Announcements

**Comment by flannery-denny** [comment]
@schanzer I just updated the discourse description on the teacher resources page. It used to say that discourse was the place to look for upcoming workshop announcements. I don't think that's been the case, but maybe we should consider it in our rethinking of discourse?

**Comment by flannery-denny** [comment]
@schanzer - Honestly, Discourse looks a little cumbersome. Two things that I can definitely do:

1. Create the topics listed above and manually move all old posts to the category that they belong in. If we do this, I vote we come up with one more category for anything we don't think is particularly useful to people (other?)

2. Make it so that only administrators could tag posts & then turn on _list tags by tag group on the Tags page_

I see some settings about forcing people to be subscribed to email notifications. But I haven't found anything about them being able to choose to subscribe yet.

**Comment by flannery-denny** [comment]
@schanzer as far as I can tell the Oklahoma team and Joy are the most active on Discourse. If they were my people, I would let them know that we're planning to do a discourse overhaul and make sure that I knew what would not disrupt them.  My guess is that Joy will be happy to see a more organized place for sharing Data Science resources & Annie will be fine as long as we don't mess with her pd cohorts. But, if you're still in Oklahoma, perhaps you could check in with her before I take on the proposed changes?

**Comment by schanzer** [comment]
Confirming that they're neutral-to-positive about the changes. :)

**Comment by flannery-denny** [comment]
@schanzer. great news. 
Is the next step for me to make the categories listed in the top of the issues and move things around?

OR

Do you want to also check with Joy or make a time to discuss further before I move things around?

**Comment by schanzer** [comment]
@flannery-denny go for it.

**Comment by flannery-denny** [comment]
@schanzer - What do you think about creating a category for people to post links to their completed games?

**Comment by schanzer** [comment]
Love it!

**Comment by schanzer** [comment]
@flannery-denny If there are zero posts in a cohort category, feel free to delete it. Let's leave OK June 2019, and move OR2021 introductions to general introductions.

(Note that the cohort groups are only visible to the people from that cohort, so the giant list you and I see is _not_ what's presented to most users)

**Comment by schanzer** [comment]
I think leaving the PD Cohorts section - and Annie's post - is the right call. Let me see what I can figure out re: getting notifications for a specific thread. In the meantime, you've done an _awesome_ job on this. Let's close the thread and celebrate!
