### ISSUE TITLE
web bug - function composition lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#559]
I'm looking at [this page](https://www.bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/lessons/function-composition/index.shtml) and seeing this
![Screen Shot 2021-08-16 at 4 08 11 PM](https://user-images.githubusercontent.com/66691020/129629906-7c413d99-8b29-4c89-82fb-f4eb5a705a01.png)

**Comment by schanzer** [comment]
@flannery-denny I need more information. What browser are you on? Here's what I see in both Brave and Chrome:

![image](https://user-images.githubusercontent.com/77126/129631213-980085c1-18cc-4ede-8054-84cd5c48aad2.png)

**Comment by flannery-denny** [comment]
I'm in Chrome.  
Started here [https://www.bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/](https://www.bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/). Just clicked it again. Not seeing the problem. Maybe that's what it does when the internet gets slow?

**Comment by schanzer** [comment]
Could be. :) Either way, there's nothing we can fix on the remix end,so I'll close it
