### ISSUE TITLE
add is-cat(dog) to exploring row and function definitions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#564]
we're not giving them a chance to get false [here](https://bootstrapworld.org/materials/latest/en-us/courses/data-science/lessons/table-methods/pages/exploring-definitions.html)

**Comment by flannery-denny** [comment]
@schanzer is this something I can fix now or do you want to wait for next year's workbook?

**Comment by schanzer** [comment]
Let's fix it now. Even if folks have already ordered the books, this is a pretty minor change
