### ISSUE TITLE
Consider whether we want defining functions to remain a core lesson 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#568]
gt was not part of the NYC DS training. Before I worked on core, gt was part of both algebra and ds.  Curious whether the summer's trainings reveal that it would make more sense to write a DS specific defining functions lesson?

**Comment by schanzer** [comment]
Yes it was. So was bc, and multiple matching representations worksheets.

Definitely keep it a core lesson.
