### ISSUE TITLE
Check ALL the slides

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#57]
Verify that all slides in game pathway are properly formatted for both Pyret and Wescheme.

- [ ] Coordinates 1
- [ ] Coordinates 2
- [ ] Order of Operations 
- [ ] Domain and Range
- [ ] Function Composition
- [ ] Defining Values
- [ ] Function Applications
- [ ] Defining Functions 1
- [ ] Defining Functions 2
- [ ] Defining Functions 3
- [ ] Function Applications 2
- [ ] Inequalities 1
- [ ] Inequalities 2
- [ ] Piecewise Functions 1
- [ ] Piecewise Functions 2
- [ ] Distance Formula

**Comment by schanzer** [comment]
And make sure links work! I just checked the "Function Composition 1" slide deck, which includes a link to Page 10 (?) of the workbook...and that link is broken.
