### ISSUE TITLE
Coverage Report upgrades

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#572]
- [x] The standard (e.g. - `HSS.IF.2.1`) is not nearly as useful as the english-language description of that standard. Can we add a column for that?
- [ ] Does the coverage report include lessons-and-practices and lessons-and-textbooks? It doesn't seem to

**Comment by flannery-denny** [comment]
Note: to see the coverage report run `./coverage-report`

@schanzer this document is still overwhelming. Let's put our heads together and see if we can spec something for Dorai that would be more useful to us in 

1. identifying standards we have forgotten to connect to lessons 
2. identifying standards we could and should be building lessons for

**Comment by schanzer** [comment]
@ds26gte I think it would be wise to add a "select which report..." menu, just as we have on the curriculum standards page. That way authors can look at one set of alignments at a time.

@flannery-denny agreed on the utility of adding a third state: aligned, not-align, _should-be-aligned_. Let's add this to our next meeting agenda to think through. We actually had something like this in our pre-remix days, but it was super clunky. Hopefully we can use that experience to come up with something better this time.

**Comment by schanzer** [comment]
@ds26gte it also appears that this coverage report doesn't mention textbooks or practices?

**Comment by schanzer** [comment]
Closing, since this is now functionality a duplicate of https://github.com/bootstrapworld/curriculum/issues/693
