### ISSUE TITLE
Expand Which Rows? Which Columns? What Display materials

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#573]
- [ ] Make more data displays pages
- [ ] Figure out how to weave this format of question asking into more places in the curriculum

> A `pie-chart` showing the `species` of animals from the shelter.
[cols="^1,^1,^1",options="header"]
|===
| Which Rows?			| Which Column(s)?		| What Display?
| _All the animals_		| @ifsoln{_species_}	| @ifsoln{_pie chart_}

|===

**Comment by schanzer** [comment]
@flannery-denny this is now complete, because this is part of the Data Cycle template that's being used all over the place (and will grow in use). OK to close?
