### ISSUE TITLE
Add keywords directive to lessons

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#576]
@flannery-denny brings up some excellent points:
* There are plenty of informal words that teachers might search by, which are not and _should not_ be in our descriptions or the standards.
* Some standards are so specific that our lesson might not touch on them, which would prevent a keyword like "isosceles" from matching a lesson involving isosceles triangles.
* Conversely, some standards are so general that they don't include keywords that we'd want to match

We'd like a simple way to tag lessons with a comma-separated list of words, e.g.:
`@keywords{angles, geometry, isosceles, equilateral, triangles}`

Ideally, these keywords should show up in the `meta` tag for the generated webpage (`<meta name="keywords" content="angles, geometry, isosceles, equilateral, triangles">`), AND in the lesson graph (see #575 )

**Comment by schanzer** [comment]
This is now complete!

**Comment by flannery-denny** [comment]
@schanzer Please clarify the process for authors to add keywords to lesson
plans now that the infrastructure has been built. Thanks.

**Comment by schanzer** [comment]
@flannery-denny `@keywords{larry, curly, moe}` can be used anywhere in the lesson doc. I'd suggest maybe putting it up near the lesson-description, just as a convention?

I'll document it on the README, if it hasn't been added already.
