### ISSUE TITLE
pyret thumbnails of box-plots seem to be emphasizing the line at 6, as if it were the median

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#577]
See [this file](https://code.pyret.org/editor#share=1q_yHgXVUHMeqVfdEuWotGXy4k149ecqZ&v=1904b2c)

with this code `box-plot(table, "a")`

screenshots below

![Screen Shot 2021-08-27 at 8 19 02 AM](https://user-images.githubusercontent.com/66691020/131133978-ff87f4a4-09e1-402f-9610-a2e6d75d8508.png)
![Screen Shot 2021-08-27 at 8 19 09 AM](https://user-images.githubusercontent.com/66691020/131133982-64c09974-b21d-4f3c-a275-e2ce2409cf53.png)
![Screen Shot 2021-08-27 at 8 23 44 AM](https://user-images.githubusercontent.com/66691020/131134251-5e0b1bdc-dc37-4c56-9c45-a5d75e4e3457.png)

**Comment by schanzer** [comment]
@flannery-denny What about this feels like an emphasis?

**Comment by flannery-denny** [comment]
When I look at the little images in this git issue, the dark line where it
doesn't belong is SO obvious to me. If you can't see it, we should discuss
on zoom with screesharing. Have another look? But, I'll add it to my
running list of things for us to discuss when we have time.

**Comment by schanzer** [comment]
Ah, I think I see what you're getting at: the full-sized image looks fine, but the thumbnails appear to have one line that is slightly thicker than the other?

Seems like an artifact of subpixel anti-aliasing: when scaling the image down, you get fractions of pixels whose values have to be averaged together. Sometimes the math works out such that you get an extra pixel of width. If this is sufficiently bothersome, you should open an issue on [code.pyret.org](http://github.com/brownplt/code.pyret.org/) instead.

**Comment by schanzer** [comment]
Moved this to https://github.com/brownplt/code.pyret.org/issues/401, so I'm closing it here
