### ISSUE TITLE
Glossary is underdeveloped and incorrectly described

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#58]
Surely we use more glossary terms than the handful that are listed here? I think we're missing a bunch.

More importantly, some of these definitions are really poor. Variable - "something that changes"? Is this the real, mathematical definition here?

Finally, these aren't "technical terms" - and calling them that is just plain scary. I'm a math teacher! I don't want to be teaching technical terms!

**Comment by BootstrapJen** [comment]
I propose:
Variable - A letter, symbol, or term that stands in for an expression or value
