### ISSUE TITLE
New Materials Landing page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#581]
Thought it might be helpful to have a place to track feedback / suggestions on the new [materials landing page](https://bootstrapworld.org/materials/fall2021/en-us/index-new.shtml?subject=math). 

- [x] Add "project boxes" to the explorer (game, sam, research paper, infographic, rocket...).
- [x] Reduce text at top of page. Proposed language:

_We provide all of our research-based materials free of charge. And of course, all of our courses are aligned to National and State Standards - including NGSS, Common Core, CSTA, K12-CS, and more! We work hard to provide a "curriculum-in-a-box" experience, offering  Hour of Code activities and four curated pathways, that come with a detailed student workbook, narrative project, and teacher materials. You can also mix and match our materials by building your own pathway._ 

- [x] Clarify directions for build your own pathway. Proposed language:

> Lessons that you can teach immediately are _shaded blue_.
> When you click on the lessons you'd like to teach,
> 
> - those lesson & any prerequisites for the lessons will **turn green**.
> - all of the lessons available to you by completing the green lessons, will _turn blue_. 
> 
> **Select** as many lessons as you'd like to include in your pathway before naming and saving.
> 

@schanzer Is it possible to highlight the word _shaded_ and **turn green** and **select** instead of putting a color block in front of the directions.
- [x] Add lesson links to lesson description bubbles
- [x] Address scrollbar issue (need to understand better)
- [x] add reset button
- [x]  when a user saves their custom pathway, prereqs should appear before the selected lessons. And lessons that are available with only some of the prereqs should appear before additional prereqs.
- [x] When I mouse over the course images, the pop up boxes move build your own pathway out of the place where I anticipate clicking on it. Wondering if it might be better if the text boxes opened up instead of down?
- [x] There is something strange going on with the text of the button for visualizing shape of data
- [x] Once I get to my own pathway, how do I actually save it for future use?  Is it a permanent url. Should we direct them to bookmark the page or save the url?
- [x] I like that what you can access without doing prereqs are all clustered at the beginning, but after that let's make sure that things that are most relatable to new to Bootstrap teachers appear on the first screen... things that are easily recognizable to math teachers as concepts that everyone teaches.
- [x] Some lessons show up duplicated

**Comment by flannery-denny** [comment]
@retabak - Do the directions above for build your own pathway work for you? If not, please include a revision in a comment below.

**Comment by schanzer** [comment]
@flannery-denny I copy/pasted your revised text for the top of the page (really nice job, btw), added a reset button, and largely implemented your directions. I changed the wording slightly, and I _think_ I implemented your formatting suggestion correctly. Let me know if I'm on the right track?

**Comment by flannery-denny** [comment]
@schanzer. I think it's definitely moving in the right direction :)

- When I mouse over the course images, the pop up boxes cover build your own pathway. Wondering if it might be better if the text boxes opened up instead of down?
- There is something strange going on with the text of the button for visualizing shape of data
- Once I get to my own pathway, how do I actually save it for future use?  Is it a permanent url. Should we direct them to bookmark the page or save the url?

**Comment by flannery-denny** [comment]
@schanzer @retabak confirmed that the proposed directions for build your own pathway make sense with a tense change which I have implemented.

**Comment by schanzer** [comment]
@flannery-denny 
- I've added code that lets the page grow downwards when you mouseover one of the curated pathways. 
- Figured out the nasty text encoding issue that was effecting the curly quotes around "shape" of data
- Once you get your pathway, you need to bookmark it. These instructions are already on the new landing page, but I've added them to the custom pathway page as well.
- clustering the math lessons at the beginning is a good idea. Which ones would you rank first?

**Comment by flannery-denny** [comment]
@schanzer 

I wonder whether it would make sense to think of the grid you have as 4 columns organized by theme (data - math - video games - ? at least until you run out of items - so that at first glance teachers get a sense of the range of the lessons available?) 

These are the lessons I think we want to make most visible to math teachers:

1. Order of Operations
2. Displaying Categorical Data - _The title needs to say bar charts and pie charts in it_
3. Scatterplots
4. Histograms
5. Spread of a Dataset - _The title needs to say box plots_
6. Functions for Character Animation
7. Sam the Butterfly - Applying Inequalities
8. Surface Area of a Rectangular Prism
9. Measures of center _the title needs to say mean, median, mode in it_
10. Flags - _ the title needs to say ratios and the coordinate plane_
11. Compound inequalities: solutions & non-solutions
12. Linear Regression
13. The Distance Formula

Lessons titles most likely to pique interest in programming

1. The Numbers inside video games
2. Coordinates & game design
3. player animation
4. ethics and privacy

I think of least interest to someone who has not yet bought into using the curriculum are:

- Method Chaining
- Defining Values
- Choosing your dataset
- Grouped Samples
- Checking Your work
- Piecewise Functions (this would not be true if it were titled image scatterplots)
- Problem Decomposition
- If-Expressions
- Restating the Problem
- Defining Functions
- Defining Values
- Contracts
- Table Methods
- Simple Datatypes

Probably missing something, but it's a start.

The last time I looked at this page there seemed to be more lessons. Pretty sure there was one called pong among them. Where did it go?

**Comment by retabak** [comment]
@schanzer @flannery-denny 

I like this proposal - but even *more*, I like the idea of having buttons that teachers can click which have important mathematical concepts on them! (Emmanuel knows I am into this idea, even though perhaps he is not.) I think a teacher who doesn't really know what we're about which will be much enticed to explore our lessons if they can click buttons that say things like "inequalities," "box plots," "ratios," "scaling," "word problems," etc.

**Comment by schanzer** [comment]
Unfortunately, there's no "four column" layout I can stick to. People with narrower screens might see only three columns, or two - or five! And on phones it will likely render as a single column. So I think we need to think of this a 1-dimensional list of lessons, with the highest value ones coming first. It sounds like we're in agreement that putting the "immediately accessible" list first is the right way to go, and then I'm hearing that we want the lessons in your first list to come next. **I also love the proposed renaming**!

Be aware, however, that hardcoding an order means the chance of this page breaking in the future goes WAY up. If we add a new lesson, remove a lesson, or change the folder name of a lesson, the hardcoded order will ALSO have to change. In general, introducing brittleness is a bad idea. If there's a way to do this dynamically based on the _properties_ of the lessons, it will be a far more robust system moving forward.

Let me offer an alternate proposal:

- Lessons with no prerequisites always come first
- After that, lessons are sorted based on the number of standards to which they're aligned (those which cover more come first)
- Lessons with the same # of standards are sorted by # of prerequisites

**Comment by schanzer** [comment]
Try this link: https://bootstrapworld.org/materials/fall2021/en-us/index-new.shtml?subject=math 

You wouldn't recognize the terms in the search bar animation?

Finding a place to put 30+ buttons on the page is going to be hard, and I don't think that actually helps teachers find what they're looking for.

**Comment by flannery-denny** [comment]
1. That link and the new order are better, but I don't think they're fully dialed in. 
2. I'm not seeing title edits.
3. The search bar animation is pretty subtle. But I do recognize the terms and the range of search strategies they represent.
4. I think we need to tighten up the spacing on the build your own pathway directions. I suggest, moving the second line up next to the first. Removing some of the white space before and after the bullets. Switching from numbers bullets to dots. Changing the word "it" from the first bullet to "the lesson"

**Comment by schanzer** [comment]
1. What's missing? 
2. I worry about renaming lessons in the middle of the school year - won't that be disorienting to teachers?
3. Made the search bar larger and gave it a slight background shadow to give it more attention
4. Implemented all these great suggestions.

**Comment by flannery-denny** [comment]
We don't have to change the names of the lesson in order to have these buttons read in a friendlier way.  Lesson Names can stay as is on their lesson plans and in the predefined DS and Algebra pathways. But, for this page, the buttons should make the math content of the lessons more visible.  

If you can't do that, then I think we either need to 
a) rethink the design of this page 
or 
b) build this page AND a page that makes the middles school math content more visible in the way that @retabak describes and I originally attempted to mock up.

**Comment by schanzer** [comment]
Adding a SECOND page is a non-starter.

Is the page at https://bootstrapworld.org/materials/fall2021/en-us/index-new.shtml?subject=math really that bad for math teachers? Can we not launch with this, and then have it get _meaningfully better_ a few months later?

**Comment by flannery-denny** [comment]
I am confused as to why it is a nonstarter to write a set of conditionals for this page for the section that prints the button titles, that take in the lesson plan titles and return something more math teacher friendly for the handful of lessons that we propose renaming.

**Comment by schanzer** [comment]
Ohhhhh - you're proposing changing the title ONLY for the button, but not for the lesson which generates it? 

And even then, only for the current school year, since we can change the lesson title after this year?

BRILLIANT. F@cking brilliant. I'll get on this ASAP!

**Comment by schanzer** [comment]
@flannery-denny lesson renaming is complete!

**Comment by flannery-denny** [comment]
thanks :) @schanzer. we may be able to dial the names in a little more once
@retabak weighs in with some other brilliant ideas about how to make the
page more beautiful/functional, but, for now, I think that's a huge
improvement.  (perhaps the compound inequalities button doesn't need
the subtitle so it doesn't get so big?)

**Comment by schanzer** [comment]
done. :)

**Comment by flannery-denny** [comment]
@schanzer A few more button change suggestions:

- move Intro to Comp Data Science & Simple Datatypes to the top
- move Solving Word Problems way down on the screen. It's definitely not the lesson we want teachers clicking on first.
- Rename Contracts to "Contracts: Name, Domain & Range"
- Rename Checking your Work to "Is the analysis trustworthy" or "testing for trustworthiness"

**Comment by flannery-denny** [comment]
@schanzer There are still a few buttons on this page whose mouseover text pops to the left, making it off screen.

**Comment by schanzer** [comment]
@flannery-denny 
* What do you mean by "move Intro to Comp Data Science & Simple Datatypes to the top"? Do you mean for the math-focused view, or for all views?
* Moved "Solving Word Problems" farther down in the math view
* Renamed Contracts
* how about "Evaluating Correctness" for checking-your-work?

@retabak 
* Common Core -> CCSS is done
* Used Flannery's text, and replaced "curriculum in a box" and "narrative project" with phrases that I hope are more descriptive!
* "Lessons you can teach immediately" does _not_ mean "even if you have no CS background and your students have never coded before"! If a teacher has taught six bootstrap lessons, the list of "lessons they can teach immediately" is quite large, and 100% assumes kids have coded before!
* "The lessons you've selected" is definitely a lie. I've revised this text. Let me know if it's better?
* We can do away with the name, I suppose. Maybe that's not a big deal? They could _all_ be called "Custom Pathway" I guess...
* We could number them, but that hides the fact that some re-ordering can be done. This isn't _as_ big of a deal in the custom pathways as it is in the curated ones, but are you sure the numbers would really give us a benefit worth the harm?
* Whoa, good call. Removed the logo.
* What other scrollbars do you mean?
* Clicking on the lesson's box was _always_ part the plan. That's coming, but after all the other stuff gets resolved.

**Comment by retabak** [comment]
First - I just checked out the math-specific page and I'm excited about it! It's great to see all of those relevant topics right away!

I see what @flannery-denny is talking about re: button text going off the edge, so I took a screenshot:
![image](https://user-images.githubusercontent.com/87144723/132695807-2de77eea-f066-4a41-8b14-9fcafd3ddf22.png)

The same thing happens for me with "Introduction to Computational Data Science" and "Grouped Samples" as well.

As for other concerns.
- The new text at the top of the page is much better (in my opinion)!
- Re: "lessons you can teach immediately" - oops, duh. I was thinking of the lessons that START out shaded blue. Nevermind, that comment was off-base!
- New text in place of "The lessons you've selected" is much better and no longer a lie. :)
- Re: 'doing away with the pathway name': My goal here is to remove barriers to entry! What advantage do you think requiring naming the pathway would have? 
- Re: numbering - I'm less attached to this one and think it's partially a personal preference. My only real argument is that it would feel familiar to teacheres and (again) potentially remove a barrier to entry. Using our stuff requires that folks learn a lot, get creative, and do some deep thinking about integration. Taking one thing (determining lesson order) off teachers' plates could be nice? Most other curricula (that are numbered sequentially) can be re-ordered to some extent; I think that is a challenge many teachers take on AFTER they've gained some familiarity by teaching the curriculum in the established order.
- Glad to know (or be reminded?) that accessing lessons was always a part of the plan!
- Here are the scrollbars (which also block the lesson description text a little bit on the right):
![image](https://user-images.githubusercontent.com/87144723/132700073-667ebb22-9fb9-4ff8-9d09-4089ce91c000.png)

**Comment by schanzer** [comment]
Tooltips are fixed! The issue was subtle: I do dynamic measurements of page width (every time the window is resized!), which computes which lesson buttons are on the right-hand or bottom edge. But that calculation didn't take the scrollbar width into account, so tips weren't being oriented properly.

**This has now been fixed.**

@retabak teachers may want to create more than one pathway. Given how similar the pages are, I think they need titles to differentiate them. If teachers don't add them here, we can't use them. How much of a barrier is it to just type some random characters, if a teacher wants to see it and doesn't care to come up with a name?

What else are we missing? :)

**Comment by schanzer** [comment]
New TODOs:

- [ ] At the bottom of the custom pathway page, add list of accessible lessons "now you can teach..."
- [ ] Number of accessible/required lessons at the bottom should take search results into account

**Comment by flannery-denny** [comment]
@schanzer - I agree with you that there are teachers who want to be able to
save more than one pathway and I agree with @retabak that it would be cool
to be able to see the pathway before saving. Any chance of making the
naming/save option appear once we get to the next page?

**Comment by schanzer** [comment]
No way to add the name later, no.

**Comment by retabak** [comment]
Bummer that folks can't save after viewing. In that case, I suppose putting in some random letters is not too big of an ask.

What about scroll bars? Any way to ditch those, or do others prefer to have them there?

And... numbering the lessons in the pathway? I think this feels familiar to teachers, and it's nice to see that there's a clear starting point.

**Comment by schanzer** [comment]
I assume you mean the scrollbars on the lesson explorer. Without those bars, how can people who use a mouse see all the lessons? Also, I don't think there's a cross-browser way to hide the bars completely, so the point may be moot.

Added numbers.

**Comment by retabak** [comment]
Whaaaaaat, that "Print Workbook" button is SO COOL! My mind is blown. I like the sequential lesson numbers too; hoping you're comfortable with them.

Confused why people who use a mouse wouldn't be able to see all lessons without the scroll bars? I'd like for folks to just be able to scroll down to see more.

The 2nd bullet under "build your own pathway" has a typo - it says, "if you haven't select any lesson yet." Should say, "If you haven't select**ed** any lesson**s** yet" I believe.

**Comment by flannery-denny** [comment]
My idea for this sentence was that it would end with the words "without any
additional programming!" and I'm not sure that the list you are providing
is actually accurate to that statement.

Once your students have finished this pathway, there are plenty of other
Bootstrap lessons your students are ready to dive into!

**Comment by schanzer** [comment]
@retabak The workbook thing is _very much in development_. Don't expect it to work reliable, or for the page numbers to be accurate. That stuff is coming, but this is mostly just a test of some technology that should also improve our build speeds.

If people don't have scrollbars, how are they supposed to scroll?

I really dislike the sequential numbering. @flannery-denny what do you think about this? And why don't you think the statement you quoted is accurate?

**Comment by flannery-denny** [comment]
@schanzer - take a look at [my sample pathway](https://bootstrapworld.org/materials/fall2021/en-us/customPathway.shtml?title=h&lessons=simple-datatypes,contracts,table-methods,defining-functions,defining-table-functions,histograms). I selected histograms as the lesson around which the pathway should be built. I don't think I should be able to do all of the lessons that it gives me as available... and I don't think that histograms also belongs on the list.

**Comment by schanzer** [comment]
@flannery-denny If you selected 'histograms', it **has** to be on the list. The list is literally "all the things you selected (plus any prerequisites)". Why do you think the lesson you chose should be missing?

As for what's available - both lists look correct to me. A _tremendous_ number of DS lessons become available once you've done "defining table functions" and "table methods". Is there a specific lesson that you know should not be accessible, but is marked as such? 

There are a few open issues or comments right now where I need to play 20 questions to understand what's wrong before I can fix it. We can be a lot more efficient here.

**Comment by retabak** [comment]
Re: "If people don't have scrollbars, how are they supposed to scroll?" 

On most websites these days, the only visible scrollbar is the one built into the browser. I feel like those scrollbars make our website look like it's from 20 years ago. If I go shopping for jeans at the Gap online, I just scroll down using the one and only scrollbar (that's built into the browser), and I see more and more photos of jeans. 

I think the exception is scroll bars on menus, which indicate to folks that there is more content to come. In the case of this "build your own ppathway" tool, I think there is *already* the expectation of more content, so the scrollbar is just visual clutter. (TBH, I think the black rectangle that frames all of the lessons is also unneeded.) I sincerely can't find any examples of a scrollbar like ours on any websites. I just see scrollbars alongside menus--again, to indicate "more content to come." 

Trying my best to be clear but worried that maybe this is still confusing.

**Comment by flannery-denny** [comment]
@schanzer How can it be correct that Histograms is listed as number 13 in [this pathway](https://bootstrapworld.org/materials/fall2021/en-us/customPathway.shtml?title=a&lessons=order-of-operations,simple-datatypes,table-methods,contracts,defining-values,defining-functions,function-composition,surface-area-rect-prism,inequalities1-simple,defining-table-functions,inequalities2-compound,inequalities3-sam,histograms,flags) and ALSO listed as a lesson in the What's next list?

**Comment by flannery-denny** [comment]
@schanzer - any reason not to edit the initial comment box to include all of the todos so that they are easy to find without rereading 37 comments and get tracked as completed or not by git? That's been my strategy for all other issues...

**Comment by schanzer** [comment]
@flannery-denny ah! Now I see what you mean. Fixed. And great idea about putting all the todos up top. Done.
@retabak - Is your proposal that the lesson explorer (all the boxes) just be as tall as it needs to be, with no box around it or scrolling? I'm open to that.

**Comment by flannery-denny** [comment]
@schanzer 

1. Is there a new link I should be using to get to the materials landing page? When I build a pathway around Displaying Categorical Data it's still showing up in the **What's Next?** list.

2. I'd also love to see the sentence: 
_Once your students have finished this Pathway, there are plenty of other lessons they are ready to dive into_ end with something like
**without any additional coding**
![Screen Shot 2021-09-16 at 9 50 30 AM](https://user-images.githubusercontent.com/66691020/133660810-42161139-aea2-4bc7-980c-dcddc3217763.png)

**Comment by schanzer** [comment]
@flannery-denny 

1. The [same link](https://bootstrapworld.org/materials/fall2021/en-us/index-new.shtml) should work. I just re-pushed the latest version, and I'm not seeing "Displaying Categorical Data".
2. Oooh, good call. The code I wrote on the landing page to sort-by-prereq should also be used on the custom pathway page. Done.
3. This new wording doesn't feel right to me. Those lessons DO require coding. The main thing is that those lessons require no new prerequisites, since they've already been taught as part of the custom pathway. How would you feel about _"Once your students have finished this pathway, they've already completed all the prerequisites for the following lessons:"_ ?

**Comment by flannery-denny** [comment]
@schanzer 

1. seems to be fixed
3. the wording you propose works for me.

**Comment by retabak** [comment]
RE: "Is your proposal that the lesson explorer (all the boxes) just be as tall as it needs to be, with no box around it or scrolling? I'm open to that."

Yes! Man, I guess I was really struggling to communicate that. Tall lesson explorer with no box + no scrolling. :)

**Comment by flannery-denny** [comment]
@schanzer I tried visiting the link at the top of this issue and the page I get to doesn't show any lessons. Lmk where to find what you want feedback on and I'll try to get it to you. Thanks!

**Comment by schanzer** [comment]
It's on the master branch. (In general, you should never look on the website for an issue that is in active development.￼)

**Comment by flannery-denny** [comment]
where on the master branch?

**Comment by flannery-denny** [comment]
@schanzer where on the master branch?

**Comment by schanzer** [comment]
1) Run ./build-pathway 
2) open distribution, and look for index-new.shtml

**Comment by flannery-denny** [comment]
./build-pathway for all of the pathways?

**Comment by flannery-denny** [comment]
1. **Directions** 

I would suggest renaming to "Project: Snacking Habits" so that the box is the same size as the others.

Under Build Your Own Pathway, I think it would look better if the highlighted question text were followed by the directions starting on the same line rather than on the next line.

I would change: _Where do you want to go?_ to something like _What are your Bootstrap goals?_

I would change this: _If you haven't selected anything yet, the blue items can be taught with no prerequisites. The more lessons and projects you select, the more material is immediately within reach_ to _If you haven't selected anything yet, the blue items can be taught with no prerequisites. As you commit to teaching lessons and projects, additional items will turn blue to indicate that they could be added without additional prerequisites._

2. **Project Boxes**
I think I like the interspersed projects better than having them all at the top.
I don't have a strong opinion about the look of the boxes. I think I like the word Project at the beginning rather than an icon because it's very clear. Since the boxes are already a unique shape, you might not have to use a separate color for them.

3. I'll think about individual project descriptions another time.

**Comment by schanzer** [comment]
@flannery-denny 
1. Great suggestions. I've implemented all of them.
2. I don't think the look is different enough for most people. I've changed them to use a more appealing color for now.
3. *nod* this is easy to change/improve later
4. Sounds good. Also easy to change.

One final point -- I'm really bothered by having all the boxes visible at one time. It seems to make the page go on forever! Are you and @retabak both strongly convinced that this is better than the scrollable, fixed-height container we had before?

**Comment by retabak** [comment]
Hey! This is on my to-do list. Hoping to take a look today or tomorrow.
Sorry I'm behind.

**Comment by retabak** [comment]
I don't think this was an issue before, but the very first thing I notice is that boxes with three rows of text are taller than boxes with two rows of texts. Can we make all boxes the same size?

Re: revised directions - they look good! Except that a bunch of text appears to be needlessly italicized?

Re: look fo project boxes - How do you feel about the look of the project boxes? It's funny, I prefer the look of the rounded corners and think I'd like to see that for all of these boxes (even though obviously the rounded corners are there to differentiate projects....) I think starting with the word "Project" is sufficient! I think icons would be too busy.

Re: project descriptions - I'm happy to help with this as well.

Final note: I like that I can see all of the boxes - but the right scroll bar is still (needlessly) there. Can it disappear?

**Comment by flannery-denny** [comment]
@schanzer When you eliminate all of the duplicate lessons, it won't be such a long list. Definitely better to have them all visible.
