### ISSUE TITLE
Big Animals or Random Samples or Random Animals Starter File?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#582]
I'm seeing that the name of the Pyret starter file doesn't match the name in the lesson plan or on the sampling and inference page.  

We should pick one name and stick to it. 

I might vote for Expanded Animals Starter File. And then in the starter file call it `animals-table-2` instead of `big-animals-table` which can be misconstrued as being a table of large animals.

Do you have a preference?

**Comment by schanzer** [comment]
I like `Expanded Animals Starter File` a lot. As for the table name, how about `more-animals`? There's nothing that says it has to end in `-table`

**Comment by flannery-denny** [comment]
@schanzer I really like these suggestions... 
I've changed the name of the starter file to `Expanded Animals Starter File` in the lesson plan and pyret.

The sampling and inference page in the printed workbooks currently refers to `big-animals-table`.  Should we wait to change to change the name of the table to  `more-animals` until the 2022 release?

**Comment by schanzer** [comment]
Unfortunately, yes. :(
