### ISSUE TITLE
Audit Lesson Descriptions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#584]
Now that lesson descriptions are appearing on the materials landing page as mouse over text, they need a read through with an eye as to how well they are serving the purpose.

**For @schanzer to tackle**
- [x] re-adding levels
- [x] re-nested structures
- [x] re timers
- [x] combination
- [x] permutation
- [x] re-adding collisions
- [x] re-algebra review
- [x] re-build-your-own-animation
- [x] re-functions that ask questions
- [x] re-intro to data structures
- [x] re-key events
- [x] re-making pong
- [x] re-refactoring
- [x] re-scoring
- [x] re-structures reactors animations
- [x] re your own drawing functions
- error analysis (not yet used)
- hoc wescheme intro (not used in landing page, has no description)
- hoc winter (not used in landing page, has no description)

**Flannery is working on:**
- [x] if expressions
- [x] piecewise functions
- [x] checking your work
- [x] choosing your dataset
- [x] contracts
- [x] coordinates
- [x] correlations
- [x] defining functions
- [x] defining table functions
- [x] defining values
- [x] displaying categorical data
- [x] displays and lookups
- [x] distance
- [x] ds intro
- [x] ethics and privacy
- [x] flags
- [x] function composition
- [x] functions for character animation
- [x] grouped samples
- [x] histograms
- [x] histograms 2
- [x] ineq -collision
- [x] simple ineq
- [x] compound ineq
- [x] sam
- [x] lr
- [x] linearity
- [x] linearity 2
- [x] making game images
- [x] measures of center
- [x] measures of spread
- [x] method chaining
- [x] numbers inside video games
- [x] order of operations
- [x] player animation
- [x] problem decomposition
- [x] random samples
- [x] restating the problem
- [x] scatter plots
- [x] simple datatypes
- [x] solving word problems
- [x] surface area rect prism
- [x] table methods
- [x] threats to validity

**Comment by flannery-denny** [comment]
@schanzer Combinations and Permutations need differentiation between their lesson description. They are also missing lesson goals and student facing goals. Can you tackle those?

**Comment by flannery-denny** [comment]
@schanzer this issue is ready to be closed as soon as you approve the last lesson description updates.

**Comment by schanzer** [comment]
Approved! Awesome job driving this to completion.
