### ISSUE TITLE
Revisit if-expressions lesson plan

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#587]
@schanzer 

1. This lesson starts with the custom animal images and ends with a scatterplot where species are distinguished by color. I don't think that sequence makes sense. Are you open to me drafting a rewrite of this lesson plan?
2. Also - on the new materials landing page, I think we should call this image scatter plots instead of if-expressions

**Comment by schanzer** [comment]
Totally fine with both!

**Comment by flannery-denny** [comment]
@schanzer Do you still want to keep if-expression (DS) and piecewise functions (Alg) as separate lessons? Seems they could become _core_... if we're ready to unify the code for how we do piecewise functions in algebra and DS. I can't remember why you think one is easier / harder / better than the other for one pathway or another. As far as I'm concerned they're equally easy for a new programmer to make sense of.

**Comment by schanzer** [comment]
Interesting idea! 🤯

Pros: all the usual benefits of core, which are not to be underestimated!
Cons: we lose efficiency. DS teachers need to teach a whole lesson on if-expressions just to _get_ to image-scatter-plots. 

The more I think about it, the more I like it. This would free the Image Scatter Plot lesson to really _be about image scatter plots_. As it stands, most teachers will spend the lesson teaching the programming and ignoring the stats (Simpson's Paradox, yo!) OR they'll wind up using up two lessons for it anyway.

I say go for it. This is awesome.

**Comment by schanzer** [comment]
Closing, now that this is subsumed in #590
