### ISSUE TITLE
How much money? How long does it take? How many people does it take to make a videogame?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#588]
Ideally, we would add an answer to these questions in the Numbers Inside Videogames lesson plan.

**Comment by schanzer** [comment]
These are _incredibly_ variable, and teachers may also wish to focus on different games with radically different development times, team sizes, and budgets.

**Comment by flannery-denny** [comment]
@schanzer Even so, wouldn't it be nice to offer teachers a range or a couple of anchor points... like what it took to build ms. pac man vs. minecraft?  

I know, for example, that cucumbers can be between 2 inches and 67 inches long, but most are in the 6 to 7 inch range unless they're Persian Cucumbers, which tend to be closer to 14 inches. 

I literally have no idea if video games are made by teams of thousands of people or might also be made by teams of 6, cost thousands of dollars or billions of dollars to make, etc.

**Comment by schanzer** [comment]
Just pushed [some data](https://github.com/bootstrapworld/curriculum/commit/63cc9cc6a2442096be7c2444ffd6183a1a078df2) for this. If this scratches the itch, feel free to close.
