### ISSUE TITLE
dog image / coordinates in slides and lesson plan don't match for coordinates and game design

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#591]

**Comment by schanzer** [comment]
@flannery-denny the slides appear to use the new purple and black images already. Just pushed an update to lesson images to match. Let me know if there are any other places you're seeing them?

**Comment by flannery-denny** [comment]
I'm still seeing this 0-5 scale in the lesson 
![Screen Shot 2021-09-10 at 11 51 15 AM](https://user-images.githubusercontent.com/66691020/132909880-3d65d141-d2c8-497f-85f7-baff60d6a3e2.png)
and this 0 -1000 scale image in slides
![Screen Shot 2021-09-10 at 11 51 50 AM](https://user-images.githubusercontent.com/66691020/132909872-91f5a50f-61d4-473e-a744-6b0b0ef695f0.png)

**Comment by schanzer** [comment]
@flannery-denny I wound up just copying the exact image, and a slice of the number line. OK to close?

**Comment by schanzer** [comment]
@flannery-denny ok to close?

**Comment by flannery-denny** [comment]
@schanzer I'm not sure why, but I am still not seeing the same image in the lesson plan. at [this link](https://bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/lessons/coordinates/index.shtml)

Am I looking in the wrong place?

**Comment by schanzer** [comment]
If you do a `git pull` and then `./build-pathway -f algebra`, you should see the new content. Let me know if this looks ok to close?

**Comment by flannery-denny** [comment]
now i can see the image, but the numberline in the lesson plan only goes from 300 to 700 whereas the slide goes from 0 to 1000. I don't think that supports teachers.

**Comment by schanzer** [comment]
@flannery-denny I'm really confused here. What doesn't support teachers? Are you saying the slide images need be exactly the same as the thumbnail lesson images? If so, why title the git issue this way? If not, why is it only _this_ image?

**Comment by flannery-denny** [comment]
Sorry. I thought I had communicated that they should be the same. I wasn't sure how they ended up so different, which is why I asked you to look at them. I can't think of any ideas why you would want them to be different...

**Comment by schanzer** [comment]
A slideshow is huge and visual. Big images make sense. A lesson plan is text-heavy and smaller, so images tend to be more like thumbnails or cropped versions. A slideshow is student-facing, while a lesson plan is teacher-facing. Lots of reasons why we might use a more limited/cropped/smaller visual tool in the lesson plan than in the slides. 

There are images in the slides, which are not in the lessons at all. There are images in the slides that are cropped or reduced in the lessons.

This isn't a hill I want to die on, so if you want all the images to be identical across both we can do that. I just want to know what the rule is, even if I don't necessarily agree with it.

**Comment by flannery-denny** [comment]
If there is a question in the lesson plan that directly refers to an image and the answer involves numbers that will come from looking at the image, the image in the slide show and the image in the lesson plan should always lead the viewer to the same answers.
