### ISSUE TITLE
Where should we as a team keep track of pioneers we read about that might be worth adding to our poster set?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#596]
I read [this article about Gitanjali Rao ](https://reasonstobecheerful.world/gitanjali-rao-interview-scientist-inventions-lead-water/?utm_source=Reasons+to+be+Cheerful&utm_campaign=43cbaf5a37-EMAIL_CAMPAIGN_2021_09_13_07_24&utm_medium=email&utm_term=0_89fb038efe-43cbaf5a37-389562924)this week and am not sure where else to save it so that it doesn't get lost... If y'all have another system in mind, I'm all ears!

**Comment by schanzer** [comment]
I've added you as a contributor to the pioneers repository. Here's a direct link to the spreadsheet: https://docs.google.com/spreadsheets/d/1FHJrFlqTqCQwhYWhsI_OuNwb2tQaPmv0EneWHvj1jWw/edit?usp=sharing
