### ISSUE TITLE
Audit All Starter Files for current Contract formatting

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#597]
They should all use:
`Name :: Domain -> Range`

These DATA SCIENCE files feel complicated... 
- [x] Fall 2020 Putting it all together
- [x] Fall2020 - Table Methods & Starter Files
- [x] I updated this Fall 2020 [word-length starter file](https://code.pyret.org/editor#share=13d6ydQuxgxKf1NLJa1Js3_-lipNEYSZ1&v=1904b2c) - where does it go?
- [x] Spring 2020: Putting it all together
- [x] Spring 2020: Table Methods
- [x] Spring 2020: Bootstrap Data Science

Didn't look at old/archived DS starter files.

Folder that were fine.
- [x] DATA SCIENCE Fall 2021
- [x] MATH Fall 2021
- [x] MATH Spring 2021
- [x] MATH Fall 2020
- [x] CORE

@schanzer Should they also all follow this template for labeling the sections of the code? 

> ; CONTRACT
> ; gt :: Number -> Image
> 
> ; EXAMPLES
>   (EXAMPLE (gt 10) (triangle 10 "solid" "green"))
>   (EXAMPLE (gt 20) (triangle 20 "solid" "green"))
>   (EXAMPLE (gt 30) (triangle 30 "solid" "green"))
>   (EXAMPLE (gt 40) (triangle 40 "solid" "green"))
>   (EXAMPLE (gt 50) (triangle 50 "solid" "green"))
> 
> ; FUNCTION DEFINITION
> (define (gt x)(triangle x "solid" "green"))

At what point do we want to make sure they all have a PURPOSE STATEMENT?

**Comment by flannery-denny** [comment]
@schanzer How do we want to handle starter files with contracts like these?
`# is-old :: (r :: Row) -> Boolean`

Archive them? And make a new starter file where the contract reads like this?
`# is-old :: Row -> Boolean`

**Comment by flannery-denny** [comment]
@schanzer looking at the flags starter files and not sure that VARIABLE is the right word here. Lmk if I should change it.

> # 3) Define a variable "puerto-rico" to make the image of the Puerto Rican flag as you described it above. 
> puerto-rico =
 > put-image(wstar, 225, 50,
   > put-image(btriangle, 75, 150,
     put-image(rrectangle, 75, 50,
       put-image(rrectangle, 225, 150,
         put-image(rrectangle, 110, 125,                                                          background)))))

**Comment by flannery-denny** [comment]
@schanzer The Flag of Mexico folder is currently in Fall 2021, because that's when it was created, but it seems a little strange to me to separate it from the flag folder, which is in Spring 2021. Not sure how to combine those logics.

**Comment by schanzer** [comment]
We agreed to use a duplicative folder structure, similar to how Dorai handles solution-pages. So you'd add another flag folder in Fall 2021, and put the flag of mexico files in it.

**Comment by flannery-denny** [comment]
@schanzer 

1. I fixed the flags folder. Thanks.
2. I did a find in files search to figure out where word-length goes. It's commented out and the end of the histograms2/Visualizing the shape of data lesson. It probably wouldn't take much more work to make that project ready since there's already the start of a worksheet and a starter file. Should we make it an issue?
3. Looks like all of the files I flagged were older, so I'll check whether the fall release is still referencing any of them. If it is easy I'll make an updated copy of the file for Fall 2021 and otherwise will leave them unchanged.

**Comment by schanzer** [comment]
2. It's already listed in the "DS ideas" issue, so no need to duplicate unless we're breaking it off and putting it on the front burner for now.

**Comment by flannery-denny** [comment]
@schanzer Not finding any reference to _putting it all together_ in Fall2021. I think it got replaced by _row functions starter file_. Does that seem correct?

**Comment by schanzer** [comment]
Ah, you're 100% right.
