### ISSUE TITLE
Teacher Resources Page formatting feels off

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#598]
Check out screenshot below. 
Are there supposed to be a whole bunch of scroll bars that don't scroll? The fact that the scroll bars don't do anything makes me think something is broken.
![image](https://user-images.githubusercontent.com/87144723/133669602-942e33ee-d378-400a-8ffe-cd4c57c33475.png)

**Comment by flannery-denny** [comment]
I'm not getting the scroll bars, but I'm also getting strange formatting
![Screen Shot 2021-09-16 at 11 13 52 AM](https://user-images.githubusercontent.com/66691020/133671708-de514ab1-2b64-4132-b79b-52278b1d3087.png)
.

**Comment by retabak** [comment]
On [this page](https://bootstrapworld.org/materials/latest/en-us/courses/data-science/resources/index.shtml), I still get weird formatting for "Method Chaining" and "Threats to Validity" (screenshots below).

https://bootstrapworld.org/materials/latest/en-us/courses/data-science/resources/index.shtml

![image](https://user-images.githubusercontent.com/87144723/134096427-1fd54b03-bc11-4755-b87b-5aba6726cff5.png)

**Comment by schanzer** [comment]
@retabak thanks for the reminder! It looks like the exclamation marks in the page titles are mucking up the build script. I removed them, but @ds26gte you may want to look into a way to defend against this in the future
