### ISSUE TITLE
Website bug -  Public is seeing broken version of WB page for Defining Functions lesson that uses @math{} and builds correctly in our repository... 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#599]
I'm looking at "Matching Examples and Definitions" and seeing that the workbook page is basically blank?

![image](https://user-images.githubusercontent.com/87144723/133677506-3905bbfd-d843-4a33-9d6a-0c948a078eff.png)

**Comment by flannery-denny** [comment]
@retabak I just force-built and the page builds fine so I'm closing the issue. Try `./build-pathway -F data-science`. If that still doesn't solve your problem, talk to Emmanuel about whether you have everything you need installed to be able to render `@math{}` correctly.

**Comment by retabak** [comment]
That screenshot comes directly from our website! That's what _everyone_ is seeing--so it needs to be addressed.
