### ISSUE TITLE
BSA:Coordinates

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#6]
See https://bootstrapworld.github.io/curriculum/distribution/bs-game-pathway/langs/en-us/lessons/CoordinatePlane1/index.html

- [x] Parentheticals need to have spaces. ![image](https://user-images.githubusercontent.com/77126/56448139-d526e780-62da-11e9-8826-5a4f73fd0a2a.png)
- [x] The "practice" section seems to require a second copy of the reverse engineering worksheet. Will there be one in the workbook? Also, won't this be insanely complex for modern games?
- [x] The last section should be a bulleted list. 
![image](https://user-images.githubusercontent.com/77126/56448167-09020d00-62db-11e9-8573-63c5e47cab8d.png)

**Comment by BootstrapJen** [comment]
@edcamposjr22 Tagging for your reference

**Comment by edcamposjr22** [comment]
I added another "Reverse Engineer worksheet" to the workbook. I agree that it is insanely complex for modern games and the goal of the activity is to drive that idea home for students so they understand why we are focusing on a simpler video game to start with and appreciate the complexity of those other games.

**Comment by schanzer** [comment]
Create/Apply is still not a bulleted list

**Comment by schanzer** [comment]
Now that it's merged in, I can see it's all fixed. Sorry about that!
