### ISSUE TITLE
Addressing empty "Supplemental Resources" boxes in lesson tables

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#603]
Noticing that the "Supplemental Resources" row of the lesson table is empty in many of our Data Science lessons. I suspect that supplemental materials are going to be added, soon (I know, for instance, that "Displaying Categorical Data" has a bunch of new stuff) - but I'm wondering if there could be some code to make that row disappear if it is blank? 

Alternatively, we could say, "There are no supplemental resources for this lesson." 

I do think an empty box on a table might make people wonder if something is broken. It also just takes up additional, unnecessary space.

**Comment by flannery-denny** [comment]
@retabak I noticed the same thing and it's been on my todo list to eliminate them from the lesson plans when they're not being used.

**Comment by retabak** [comment]
@flannery-denny  - Ah, I can do that when I see them too. Wasn't sure if there was an easier way.
