### ISSUE TITLE
Global dictionary of starter files

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#605]
The Teacher Resources Pages lists Starter Files, which we chronically forget to keep up-to-date.  Is there a way to flag starter files so that as we update them in lesson plans they automatically update in resources?

I know it's more complicated than the dataset table (`@include{../lessons/choosing-your-dataset/fragments/dataset-table.adoc}`) but that strategy is doing a great job at keeping teacher resources up-to-date.

**Comment by flannery-denny** [comment]
If this is easy, it would be lovely to (separately) also flag projects for an automated summarized list.

**Comment by schanzer** [comment]
@ds26gte this would basically mean creating a dictionary, mapping starter file name to URL. Then we'd replace all the URLs with the names, and anytime we update the dictionary the URLs would all be changed accordingly. What do you think?
