### ISSUE TITLE
Rubrics for Mini Projects

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#610]
I'm taking this on! 
(Unless someone @schanzer @flannery-denny  tells me it would not be a good use of my time.) 
Will share what I come up with here.

**Comment by schanzer** [comment]
@retabak I think we had one _ages_ ago, but it's very much worth revisiting. I like yours a lot! Perhaps there are also ways to incorporate some of the equity themes into this?

**Comment by flannery-denny** [comment]
@retabak The first thing that jumps out at me is that the rubric you made for the infographic had the first column showing a great job and this rubric has the first column showing a lousy job. I like great at the beginning better!

I think that also gets at our general todo from #456 to Audit our assessments with this idea in mind "**Develop formative assessments that highlight student knowledge rather than deficit knowledge**".

Since the blog post isn't part of the videogame, I would vote that you remove it from the main rubric. If you want to offer a second rubric that includes that, I'm all for it.
And, either way, I'd suggest adding the idea to the lesson plan in one of those little strategy boxes. What do you think about that @schanzer?

I'll have a few minor edits to wording once it's asciidocified, but nothing else big for now.

**Comment by flannery-denny** [comment]
I pushed some more edits. Honestly, I had lots of kids leave the title off and would love to see it in the rubric if we can fit it. Haven't figured out how to see a pdf version of this yet, but once @ds26gte helps me figure that out, am hopeful that we can get it all on one page without cutting that row.

**Comment by retabak** [comment]
Rubric-related question for @flannery-denny and @schanzer 

The video game rubric (asciidoc) is finished an pushed (that happened a while ago), but it's not advertised/hyperlinked anywhere on the site. I'm thinking it ought to go on the Teacher Resource page (not sure which section?), and perhaps in one of the earlier algebra lessons? My thinking here is that there's value in passing out a rubric at the outset of a project to help kids understand the final destination. 

So maybe we add a little box about the video game rubric in "Making Game Images" - given that the first rubric row is about sizing images and being certain they're facing the correct direction? I could also envision adding in a note about the rubric wherever it is pertinent -- but that doesn't seem totally our style because I don't think we're so fixated on assessing.

**Comment by schanzer** [comment]
@retabak it should _definitely_ be on the TR page. I would change the "Links to Starter Files" heading to "Projects and Starter Files", then add the rubric to the bottom of the Video Game section. 

I'm fine with it being linked in the Game Brainstorming lesson, and maybe again when students implement collision detection.

**Comment by retabak** [comment]
@schanzer I'll add the rubric to the TR page and work on a little text box to describe / add it elsewhere. (Would it be patronizing to remind teachers that it's a good idea to be transparent about assessment and introduce students to rubrics at the outset, *before* they actually receive a grade? Maybe I can reference some outside expert? This is clearly a thing I feel strongly about.) 

@schanzer @flannery-denny Here's another [rubric draft](https://docs.google.com/document/d/1EueiT8d97oBejd6HD2Vl9ia4hi5IpyTtyD4pVPWvtP0/edit), this one for "Food Habits." The "Time Use" project is almost identical in its structure / expectations, so I'll be able to modify it just slightly for that rubric.

**Comment by flannery-denny** [comment]
I think the rubric should be linked using the @opt-project directive so
that it gets auto included in the table with all of the other projects.
This might require an overarching description of the game project,
which I'm not sure we have, but would be useful to teachers.

I think referencing an expert about sharing rubrics ahead of time is not
patronizing but supportive.

**Comment by retabak** [comment]
Haven't made an Olympics Project rubric yet because I spent a long time revamping the project! Would love for @schanzer and @flannery-denny to take a look!

Here's the [old version](https://bootstrapworld.org/materials/latest/en-us/courses/data-science/lessons/linear-regression/pages/olympics-project.html), here's the [new (Gdoc at the moment) version](https://docs.google.com/document/d/1nC9T6lP-wezYuknlSj8gQEFXHoP_UtYv2LgrWoaapnI/edit#).

Is this project worth keeping? Should we scrap it for its focus on male / female binary? Can we use the project as an opportunity to dig into how those categories are not inclusive and make this project more relevant?

I won't start working a rubric until y'all have weighed in.

Side note: This project needed a BIG overhaul. It took me a really long time to even parse/ understand the original directions. I think it's much clearer and more accessible but might still need some work.

**Comment by schanzer** [comment]
@retabak this is MUCH better, and I think including the point about Christine and Beatrice is really valuable.

With the olympics coming around again in 2022, I think this is definitely worth keeping!

**Comment by retabak** [comment]
Here's a [revised project](https://docs.google.com/document/d/1nC9T6lP-wezYuknlSj8gQEFXHoP_UtYv2LgrWoaapnI/edit#heading=h.6zh4j53yj72p) (with a call out box about testosterone testing) and here's a [rubric ](https://docs.google.com/document/d/1yg5oNNCGMYokIeBc0biOXifusGUHv7fSpmDywggUbVM/edit)! 

Feedback welcome on both @flannery-denny @schanzer.

**Comment by schanzer** [comment]
@retabak left a few comments in the document. This is looking SO much better!

**Comment by retabak** [comment]
Rubrics are complete for all mini projects!
There is also one for the video game.

I started working on [this one](https://docs.google.com/document/d/17xaCufwV92128jWvCYzoJaIllGKwoWAh2NATkTNlLQI/edit) for the DS culminating project, and then decided maybe it's a pain in the ass? Like, yes, it's more objective and specific than [Joy's rubric](https://bootstrapworld.org/materials/latest/en-us/courses/data-science/resources/pages/final-paper-rubric.html) -- but maybe I'd rather grade my kids' work using Joy's rubric, given the scope of this project?

Let me kow if you have thoughts @schanzer @flannery-denny. I haven't made an asciidoc yet because I suddenly felt uncertain about it.

**Comment by flannery-denny** [comment]
@retabak. Yours is definitely a lot more wordy! I think Joy's might be easier to use.  Maybe the rethink should focus on whether Joy is really getting at all of the categories we think are important to assess. And perhaps it would be more consistent with your other rubrics to use a 5-1 scale instead of the complex weighting she's worked out to get to 100?

**Comment by schanzer** [comment]
@retabak Sorry for the delay in replying. I'm in agreement with @flannery-denny on this, especially the common 5-1 scale.
