### ISSUE TITLE
Should we have a landing page for buggy design recipes?

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#611]
On the [algebra teacher resource page](https://bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/resources/index.shtml), when I click "[Buggy Design Recipes Folder](https://bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/resources/BuggyRecipes/pages/)", this is where it takes me:

![image](https://user-images.githubusercontent.com/87144723/135128935-b8827b57-a55f-45d8-bd49-c6aa2b1abf09.png)

Not sure if that's what everyone else is seeing, but it's not pretty!

**Comment by schanzer** [comment]
@retabak please use descriptive issue titles - if you're not sure that it's a broken link, don't put it in the title. I had a mini heart attack until I read your text, and then I discovered that you probably just want a landing page for these recipes. :)

**Comment by retabak** [comment]
@schanzer - Oooh, you changed the title! (I was so confused.) And I didn't mean to give you a heart attack, I'm so sorry!
I thought that was a broken link but I suppose it's not? I'm still learning terminology.

**Comment by flannery-denny** [comment]
I agree that a landing page for these materials would be much more user-friendly.

**Comment by schanzer** [comment]
@retabak and @flannery-denny - I've just checked in a landing page. Close if this looks good to you?

**Comment by retabak** [comment]
@schanzer - I looked at the commit and still can't figure out how to find the landing page file. Can you tell me where the file is? I see all the individual buggy recipes and answer keys but not the landing page.

**Comment by schanzer** [comment]
@retabak click on "Teacher Resources" and then go to Buggy Design Recipes.

**Comment by retabak** [comment]
This looks good to me! So much more user-friendly for teachers!
Going to close. @flannery-denny , if you see any issues, feel free to re-open.
