### ISSUE TITLE
Meta-Issue for Dorai

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#615]
In descending order of urgency
- [x] #606
- [x] #605
- [x] #620
- [x] #618
- [x] #619
- [x] Comment out all the pd-workbook generation code
- [x] #632 
- [x] #640 
- [x] Debug `empty` appearing on https://github.com/bootstrapworld/curriculum/blob/if-expression/lessons/piecewise-functions-if-expressions/langs/en-us/pages/pyret/redshape-dr.adoc

**Comment by ds26gte** [comment]
Fixed "empty" bug in branch 'if-expr-plus-common-lessons'.  (Using a 'let' to store an intermediate string seems to avoid the braces in this string from being erased; I don't understand but I'll take it.) I can propagate this fix to other branches or wait till this branch itself is merged.
