### ISSUE TITLE
New Image Scatterplots lesson 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#634]
Scaffold a sequence that makes visible to students the many possibilities Image Scatterplots offer: 
- Compare Regular scatterplot of pounds vs. adoption time to [Scatterplot with speciestag ](https://code.pyret.org/editor#share=1Yskwvzbe5CSMX3F1fveEOgrL3ms2cxHV&v=1904b2c) - workbook page will guide them through reflecting on why this is useful and then practice writing similar code by creating a nametag function so that they can see a graph with the animals names. This page will also dig into the fact that the scatterplot function includes 3 variables.
- [Color sorted scatterplot](https://code.pyret.org/editor#share=1SOLAau653CYFY05x45NustZ0-ejKGQF0&v=1904b2c) - workbook page will have them reflect on why visually distinct dots are helpful for analysis and have them practice writing code by assign them the task of making an[ image scatterplot comparing age and adoption time where the dots are different sizes depending on the weight of animals ](https://code.pyret.org/editor#share=1OUuVCsm320LzZtwsrS4TLTt_Gp7tQD2A&v=1904b2c)
- [Custom animals scatterplot](https://code.pyret.org/editor#share=1SEMw8_aqLCvpY5g9dVvvSnUyyXZRmTyI&v=1904b2c) - workbook page will have them think about the benefits and risks of using clipart in a graph and brainstorm what image scatterplot they might want to make for their own dataset
- [x] makes lesson slides
- [x] add solutions to workbook pages!

**Comment by schanzer** [comment]
@flannery-denny yep! I can download the asciidoc file. Just gave it go. The student version has everything but the definition, and the solution has everything. Looks good!

Are you saying you want the asciidoc to contain both solutions, but comment out one of them for building html or pdfs? Totally doable. 

Or do you mean that you want to show students both solutions, but use the comment characters for the second one? Unfortunately, that one isn't doable with this directive.

**Comment by schanzer** [comment]
@flannery-denny sorry for the delay on this!

1. Wondering what you'd think of using a _multiline comment_ in the starter file, such as:
```
# image-scatter-plot :: ( 
#  t :: Table, 
#  xs :: String, 
#  ys :: String, 
#  f :: (Row -> Image)
#  ) -> Image
```

2. Made some small wording changes and typo fixes. Most of the changes involve conventions we use elsewhere: we capitalize names of data types, and we are careful to distinguish between function and what the function makes (e.g. - `image-scatterplot` is a function that _makes plots_ and not the plot itself). Let me know if you object to some of changed wording? 
3. "What was the first step for generating an image-scatter-plot with the animals' names?" There's something about this wording that doesn't feel right. "First step" implies there are steps for this, but we haven't talked about them yet. And why isn't the first step writing the `image-scatterplot` function and then writing the helper function that goes along with it?
4. I'm swapping out "piecewise functions" for "conditionals", since this lesson is much more firmly rooted in the programming realm than math. Are you OK with this?

In answer to your questions: the mouseover captions should just be (descriptive) titles. I think it's fine to add some text to the title like "scatterplot of pounds v. weeks, with dots sized according to number-of-legs".

Added CSS as requested.

Added `show-funname-defn?` parameter to design recipe, overriding the default value of `#f`with `#t`

**Comment by flannery-denny** [comment]
WIP - saving so I don't lose it. Will be updating.

- [ ] fixed-dot-dr is showing examples and I can't figure out how to hide them.
- [ ] The prereqs still aren't appearing correctly in the side bar.
- [ ] The sidebar currently defaults to Common Core standards instead of CSTA standards.
- [ ] One of the starter files could be listed as optional... I think I'm ok with not worrying about it and letting it appear in the main starter file list. Does that work for you? If not, we should ask Dorai for an `opt-starter-file` directive. Most of the time, starter files are not optional, but this is a particularly complex lesson in terms of the new code we're introducing and how much I expect motivated students to draw on it after completing the lesson.
- [ ] earlier today I could see the little lesson instructor character in the lesson plan. would be nice to have that feature pushed to `if-expr` and `fall2022`, because it made me make some changes regarding when not to use bullets.
- [ ] flagging that I used the `@show{(sexp->code 'scatter-plot)}` and `@show{(sexp->code 'image-scatter-plot)}` once each early in the lesson plan because I have a vague memory of that being one way that Dorai compiles functions for the language table. If you look carefully, you'll notice that the formatting doesn't match the other formatting for code on the page.
- [ ] I'm not 100% sure I love that the design recipes used in this lesson get the words "Word Problem" in front of them in their lesson plan links.

Other than that, it's ready for feedback.

If it looks good to you, please lmk whether or not you want Rachel to read it before I make slides.

**Comment by schanzer** [comment]
- [ ] First "Investigate" asks students to turn off a line of code by adding a `#` symbol. Let's use this as an opportunity to remind them what that means! "Before we move on, let’s comment-out the scatter-plot expression in the program by putting a # at the start of line 14. This will 'turn off' the expression, by telling Pyret to ignore that line"
- [ ] "How did having the dots labeled with the species change your understanding of the data?" -- I think I'd rather start by asking students what they notice and wonder, _then_ ask for the more directed question about how their understanding changed.
- [ ] "What was the first step for generating an image-scatter-plot with the animals' names?" -- I still find this pretty confusing. What steps? That's the first time in the whole lesson kids see the word "step". I'm not even sure I agree with the answer the lesson gives.
- [ ] There's no duration listed for the last section

Overall this is in really good shape. As to you question about changing the scatter-plot lesson, I think the answer is no. This lesson barely talks about the _meaning_ of scatter-plots at all right now, so I don't think there's a lot we can take out of the scatter-plot lesson. I would suggest adding some wording at the beginning of this lesson that says "you experimented with scatter-plots briefly when you explored all the various displays Pyret can make. We'll talk about the statistical use and meaning of scatter-plots later, but for now we're just going to play with them and extend our knowledge a bit." This is a hint to the teacher that they don't actually need to _teach_ scatterplots here. What do you think?

**Comment by flannery-denny** [comment]
Any time we're not referring to the function `image-scatter-plot` replace with "custom scatter plot"
.

**Comment by flannery-denny** [comment]
@schanzer - Slide deck is ready for your review. Once approved, you can close this issue. I have deciding on whether to use "Word Problem" at the beginning of every Design Recipe on our agenda for Tuesday and it feels separate from closing this issue.

**Comment by schanzer** [comment]
Looks great! I added a scatter plot image and normalized the formatting of code blocks. Hope you're ok with that?
