### ISSUE TITLE
make contracts pdf for contracts lesson that isn't pathway specific

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#636]

**Comment by flannery-denny** [comment]
make it in the contracts lesson
then add the pdf to the lib folder "Makeworkbook.js" file add to line 20

> const knownLongPages = [
  'flags-of-the-world-resource.pdf',
  'SavingImagesGuide.pdf',
  'infographics.pdf',
  'animation-worksheet.pdf'
];

**Comment by schanzer** [comment]
Woohoo!! 🚀
