### ISSUE TITLE
draft facebook post for IM groups re: one-pagers

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#637]
Note: wait until Nov 1 new landing page to post.

**Comment by retabak** [comment]
Here's a draft! If my tone is obnoxious or if this is too long, please edit. Was writing as an individual who is an actual member of the facebook group, not a representative of Bootstrap. 

https://pyret.slack.com/files/U027H4SU6KW/F03AE0Z581F/im_post

**Comment by schanzer** [comment]
Now that this has been moved on to Shriram, the "draft post" issue can be closed.
