### ISSUE TITLE
update pyret context for math, then update links to math starter files in starter file library

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#638]
@schanzer [I made this context](https://code.pyret.org/editor#share=1cPgA9tTzaoTBd-fr8z_hcSyz0Sgm90TG&v=1904b2c) with DS as the based. Might be more things that could get cut out of here. Perhaps there's also something you'd add. Lmk when it's good to go. Thanks!

**Comment by schanzer** [comment]
This looks great!  Nice catch including the various <this>-to-<that> functions. Good to go!
