### ISSUE TITLE
new algebra pyret context - a few glitches to resolve

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#639]
- [x] [game](https://code.pyret.org/editor#share=1_zdXA85BkkMqNvKXVdBcjq01foimuXkC&v=1904b2c)
![Screen Shot 2021-10-20 at 10 41 32 AM](https://user-images.githubusercontent.com/66691020/138130884-5d5aee50-f31d-4fee-8eaa-061ef21edf07.png)
- [ ] The print-images-libary for the surface area lesson didn't make it into the algebra teachpak. Not sure if it should. So I made a separate starter file. And I'm getting this error message. [link](https://code.pyret.org/editor#share=1UjWTxWi6FeDpKvP-n1o-EWhmGPDzbWPC&v=1904b2c)
![Screen Shot 2021-10-20 at 11 04 09 AM](https://user-images.githubusercontent.com/66691020/138131232-0e65127f-ddaa-4eb7-b75d-1716b24060d3.png)
- [x] [Rocket Height](https://code.pyret.org/editor#share=12Fa8MT2kZY7fFUYfsuRcHwOK0a5Vma-V&v=1904b2c)

_I proceeded with all of these as if they would be resolved at the teachpak end and linked the pyretv1.6 files in the starter file library #605._

- [x] There are 3 linearity starter files. But they don't seem to be saved in algebra or ds starter files. Looks like their update would include the data science teachpak, but I wanted to confer as to where you want them saved so I haven't made updated versions of these files yet.
- [x] Looks like the permutations and combinations starter file already got an updated context? but didn't get copied to the 2022 folder. Do we need to make an older version? Do you want to move it to the 2022 folder or keep it where it is? Haven't add this to the starter file library.

**Comment by schanzer** [comment]
@flannery-denny made some changes in a _new context_ (emphasized for future starter files!), which resolve the Pyret issues about.

re: linearity - I think they should be saved in math. Content-wise, they have a lot more to do with math than with Data Science. This makes me realize an unconscious heuristic that I was using before, which may be useful to surface -- Hierarchy of Learning Goals should influence the Directory Hierarchy.

re: permutations ands combinations - No need to make an older version.

**Comment by flannery-denny** [comment]
The context I am able to find doesn't seem to work for surface area. 

I don't understand your comment re: linearity, but I know that I made a case for them to be saved in algebra last year (since that's where we teach them) and was overruled. I'll save them in math.
