### ISSUE TITLE
Supplemental Activities linked in TR section are expired, and should be "owned" by the repo

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#64]
Clicking on any of the circle of evaluation activities, for example, brings up a warning about being out of date. 

- [x] Allow all circles exercises to render in racket
- [x] Allow all circles exercises to render in pyret

(subsumes #63)

**Comment by ds26gte** [comment]
I believe this is all done. If any have slipped thru the cracks, please inform.

If code is input in (Scheme) s-exps -- this is invariably the case for CoEs --, it should automatically be converted to Pyret when required. In cases, where the source has actual code (not intended for CoE, and often containing lang-specific syntax), the Pyret version of the code is supplied using the `pyret` subdirectory mechanism already in place.

**Comment by schanzer** [comment]
It looks like the pyret conversion for `string=?` isn't correcting the function name. 
![image](https://user-images.githubusercontent.com/77126/67947039-13219400-fbb9-11e9-9320-a0214b8b2073.png)

**Comment by schanzer** [comment]
Still some weirdness with less-than-or-equal-to (I know how much of a pain these are to stomp!)

![image](https://user-images.githubusercontent.com/77126/67947085-2d5b7200-fbb9-11e9-9310-9c9fa31612cc.png)

**Comment by BootstrapJen** [comment]
I'm going to close this one as the above issues along with other formatting/syntax issues have been moved to issue #87
