### ISSUE TITLE
Flexbox upgrades

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#641]
![Screen Shot 2021-10-20 at 5 25 27 PM](https://user-images.githubusercontent.com/66691020/138181083-740db574-bedd-4d85-86e9-c54cb9267e14.png)

**Comment by flannery-denny** [comment]
Oh boy! If I could have a `@fitb` finish out to the edge of the line without any guesswork, that would be amazing!

**Comment by schanzer** [comment]
[There is now a PR open for this](https://github.com/bootstrapworld/curriculum/pull/807). Low priority, but we can get this done after authoring is over.

**Comment by flannery-denny** [comment]
Very cool!

Flannery

**Comment by schanzer** [comment]
Closing, since the open PR is now a more up-to-date duplicate of this issue.
