### ISSUE TITLE
Need a place for pathway-agnostic, non-lesson adocs

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#644]
Our textbook alignment adocs need a place to live. They don't belong to any lesson or pathway, so it's not appropriate to put them there. Can the build script be adapted to process adocs in `/shared/docroot`? Or would you prefer this happens somewhere else?

Things that would go in this folder

- [ ] Textbook alignments

**Comment by schanzer** [comment]
@schanzer come up with proposed directory structure, send to Dorai

**Comment by ds26gte** [comment]
These agnostic lessons also don't vary with proglang, amiright?

**Comment by ds26gte** [comment]
Also:

**Comment by ds26gte** [comment]
Also:
- Only one such directory needed? Does it need subdirectories or can it be assumed to be flat? (Flatness is marginally more convenient for implemention, but subdirectories may allow authors to structure things. I know @schanzer has a design preference for not making things general, so as to not trouble the user with unnecessary choices.)
- It doesn't need to have a teacher's vs student's version?
- Do its pages need to be PDF'd at all? Do they ever merit inclusion in any of the workbooks?

**Comment by schanzer** [comment]
@ds26gte 

- Yes to subdirectories. We'd have one for textbook alignments, for example
- I don't believe we need a separate solutions folder. @flannery-denny want to weigh in on this? 
- Yes to PDFs, no to workbook inclusion

**Comment by flannery-denny** [comment]
I also can't think of a use-case for why this kind of page would need a solutions folder

**Comment by ds26gte** [comment]
I mistyped #664 for #644 in the commits addressing this issue.  Please pull and test.

The input is deemed to be in `shared/langs/en-us/pathway-independent` -- and I've put in some placeholder example adocs there. On conversion, these sit in `distribution/en-us/lessons/.pathway-independent` (note the *dot*). Despite being in the `lessons/` directory, these are converted differently from the regular run of lessons. The reason for choosing to put the directory there is so the new directive `@lesson-link` can be used to refer to them, eg, `@lesson-link{.pathway-independent/document.adoc}`.

Of course, no bona-fide lesson can have the name `.pathway-independent` (although it *can* have the name `pathway-independent`).

**Comment by ds26gte** [comment]
Open to better names than `pathway-independent` and `.pathway-independent`.

**Comment by schanzer** [comment]
@ds26gte I'd really like to see this directory structure sit alongside all the docroot stuff. In other words, everything in `pathway-independant` should show up as a sibling to `courses` and `lessons`. I understand that lesson-link won't get us there, but I'm comfortable using @link{} for this purpose. Eventually I'd like to see all the stuff in `docroot` go here as well, so there's a single location for the root hierarchy and anything other than adocs just gets copied verbatim.

**Comment by ds26gte** [comment]
OK. Pathway-agnostic files are now in `shared/langs/en-us/docroot` alongside the `.shtml` and `.png` files already there. They can be `*.adoc` files that are siblings of these files and they can also be inside arbitrarily deep subdirectories. Their converted forms go in `distribution/en-us`, with subdirectory nesting faithfully copied.

**Comment by schanzer** [comment]
@ds26gte this works great -- I just tested it out by moving the textbooks directory into the folder, and everything works beautifully!
