### ISSUE TITLE
Spanish language glossary

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#645]
- [x] send to reviewers
- [ ] add links to website
- [ ] course-specific vocab pages should be multi-lingual, with language code as CSS class and multiselect box to show/hide languages

**Comment by flannery-denny** [comment]
Data Science Terms: [https://github.com/bootstrapworld/curr/blob/master/lib/langs/es-mx/glossary-terms.rkt](https://github.com/bootstrapworld/curr/blob/master/lib/langs/es-mx/glossary-terms.rkt)

**Comment by flannery-denny** [comment]
@schanzer 2 questions about the Spanish glossary.

- [ ] The current version has English definitions for whatever we don't have Spanish definitions for. Preference for
a) leave it alone
b) delete words we only have English definitions for
c) write definitions for the words we only have English definitions for.
My preference is NOT a.

- [ ]  The glossary you sent is strictly data science. Do you know where to find one for Algebra? Should they be kept separate? My understanding is that they're together for English...

**Comment by flannery-denny** [comment]
@schanzer - 
Some of the english definitions I'm working with feel like they could be better, so 'i've changed them for the Spanish version. lmk if you approve of updating the english.

- [ ] axes: the **vertical and horizontal** number lines on a scatter plot, used to place points that represent pairs of values in data sets.
- [ ] rows: **horizontal** elements in a table, consisting of some group of values; each table is a collection of rows

**Comment by schanzer** [comment]
Works for me!

**Comment by flannery-denny** [comment]
@schanzer lots of errors when trying to build the Spanish glossary. pushed my work so far to master, assuming it won't cause errors for y'all if you're not trying to build in Spanish! It's hard for me to get an overview of the missing entries while looking at the asciidoc, so I'm mostly pausing my work on this until we figure out how to build it.

I think we should get clear on the actual goal of the build before we write a git issue for dorai. 

As I understand it, the ask from the teacher is for the Spanish glossary to be available even when they haven't clicked into Spanish mode (which doesn't currently exist). This makes me think we want this file to build as part of the English build...

Also, I know this isn't top priority for Dorai's time so I haven't asked him anything about it other than how he though it should work. He said "use --language es-mx as a build option" in case you want to give it a go and see what happens.

**Comment by schanzer** [comment]
@flannery-denny Yeah, there definitely appears to be some stale code here in the build script. 

One thing we DO have to do is add an `es-mx` folder inside the algebra pathway. I've done so, but I'm not seeing an lessons getting built. I'll open a separate issue for Dorai, to resurrect those parts of the script. Hopefully that's quick work, since the code just needs to be updated to reflect whatever stuff has changed recently.

**Comment by schanzer** [comment]
@flannery-denny Dorai has fixed the build script!

There's some UI work we should consider, for how to surface the existence of translations. Do we show a dropdown per-page? Links for just the glossary? I've added this to the agenda for tomorrow's call.

**Comment by schanzer** [comment]
**Notes from our call 10/9/21**

We'll use some UI element on the glossary page, which shows other languages for which the glossary is available. This UI element should be something we can reuse on other pages, when they get translated.

**Comment by flannery-denny** [comment]
build generates `distribution/en-us/lib/bilingual-glossary.html`

**Comment by flannery-denny** [comment]
Flagging that the Spanish term we're using for "dot accessor" raised eye brows. Would love to find someone who can verify or correct what we've got.

**Comment by flannery-denny** [comment]
@schanzer I recommend closing this issue and writing a spec for what you want Dorai to do as a separate issue

**Comment by schanzer** [comment]
@flannery-denny this spec is going to be a lot more involved, and largely dependent on whether we get more people offering to do translations. I'll note it for now, but I don't think there's cause for a new issue (especially when Dorai is looking into the slide creation stuff)
