### ISSUE TITLE
Common-Lessons cleanup

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#647]
Some assorted housekeeping and bug-stomping from the merger of common-lessons. Dorai moved at a breakneck pace to get this done, and it's remarkably complete considering how much of a plumbing change that was. However, there's still some errata to deal with:

1. Assorted bugs

- [x] I believe `include` paths may also need an update, at least for this one erroneous error - `asciidoctor: ERROR: lessons/choosing-your-dataset/.cached/.index.asc: line 98: include file not found: /Users/schanzer/Documents/Bootstrap/Development/curriculum/distribution/en-us/lessons/choosing-your-dataset/.cached/lessons/choosing-your-dataset/fragments/.cached/.dataset-table.asc`
- [x] CCBadge.png has the wrong path, shows as a broken image link
- [x] `bootstraplesson.js` should be loaded for lesson pages - lots of stuff breaks without it!
- [x] Lots of debugging output spew from the 'preparing lessons' phase
- [x] Logo images on pathway narrative pages are anonymized, but the IMG link points to the non-anonymized logo image and the fail to load at all. That file should not be anonymized to begin with.
- [x] Pathway narrative pages no longer list their lessons. Bring 'em back!
- [x] The dependency graph lists lessons that exist in multiple `proglang`s multiple times. (e.g. - there's a lesson called `contracts` and another called `contracts-wescheme`. We should just list them once, always defaulting to Pyret by dropping the `-XYZ` fields.

2. There are sections of the build script that we can likely remove. Let's give @ds26gte some time to audit the code behind those, and thinking about maintenance and future-proofing.

If there is post-processing work to be consolidated/culled, this should happen. Some brainstorms:

- [x] Is `checkifsinglepdfpage` dead code?
- [x] There's a lot of `JAVASCRIPTDELAY` code that's commented out. Can we kill it?
- [x] Is `removecodetags` dead code?
- [x] Everything other than PDF generation is lightning-fast. What if we only store checksums based on PDF modification dates, and force-build any and all other changes? Does this make the script simpler or faster? (No)

**This issue may include a potential 2m slowdown in a force-build scenario, on an older machine** - if there are HUGE improvements that we can get with a 2m slowdown on a machine like Flannery's, we should bite that bullet. `common-lessons` just bought us a 5-30m win, and we should be prepared to give some of that back on making the code cleaner and more maintainable

**Comment by ds26gte** [comment]
checkifsinglepdfpage is indeed deadcode now (because pdftk is no longer used), but don't we still need a check through other means that a workbook page converts to a single-page PDF?

**Comment by schanzer** [comment]
I've just re-enabled this, using `pdf-lib` in ee1765c9dee4f29654da6038655d63292eb63ba1. It's really fast, too! ;-)
