### ISSUE TITLE
We need to own Quizziz and Desmos

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#65]
@edcamposjr22 - every single item in remix that is linked from somewhere else *needs* to be shared from a Bootstrap Admin account. Can you get this done by Friday?

**Comment by edcamposjr22** [comment]
I am at the County again today but off tomorrow. I'll have it done by the
weekend for sure.

edcamposjr@bootstrapworld.orgwww.bootstrapworld.org(559) 303-3463
Sent with Mixmax  





On Wed, Oct 2, 2019 5:48 PM, Emmanuel Schanzer notifications@github.com  wrote:
@edcamposjr22  - every single item in remix that is linked from somewhere else 
needs  to be shared from a Bootstrap Admin account. Can you get this done by
Friday?

**Comment by schanzer** [comment]
Looks awesome! Nice job, @edcamposjr22
