### ISSUE TITLE
In the launch of checking your work, there's a link to an article on is AI racist, we could expand upon this and turn it into an activity, perhaps even getting permission to include the article from the week in the printed workbook?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#650]

**Comment by flannery-denny** [comment]
I've emailed to request permission to reprint the article in our workbook and am waiting to hear back.

**Comment by schanzer** [comment]
@flannery-denny This is a _fantastic_ idea! YES!

**Comment by flannery-denny** [comment]
@schanzer I have not heard back. And, honestly, there must be better articles out there by now, too.  What do you think about including one of these?
- https://www.theregister.com/2019/05/22/congress_facial_recognition/
- https://www.nytimes.com/2018/02/09/technology/facial-recognition-race-artificial-intelligence.html

**Comment by schanzer** [comment]
@flannery-denny I think these are _excellent_ options. I'm more interested in the first one, but both are great. Go for it!

**Comment by flannery-denny** [comment]
@schanzer Just committed the pdf of that article and a reflection that would work for it or the clip linked from it. Currently the reflection links to external sources rather than the pdf. Figure it's good to store the pdf in our repository as a backup, even if we decide just to link to the article for now (and I haven't received written permission to reprint it yet).

Current title of the reflection is:

> AI: Can computers be racist? sexist? wrong?

Previous iterations included:

- AI: What if machines learn from bad data?
- AI: Lousy data can lead to harmful outcomes

Preference?

- [ ] I haven't added SJ standards to the lesson, because SJ standards don't exist in the fall2022 branch.

**Comment by schanzer** [comment]
How about "Can Software be Biased?"

We'll address the SJ standards next week in our Merge Hell Day.
