### ISSUE TITLE
Identify at least one practice for each lesson.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#652]

**Comment by flannery-denny** [comment]
@schanzer - I've updated the `lessons-and-practices.rkt` file in `fall2020` to make sure that it includes all of the lessons and they are all titled correctly.  I'm not sure what practices to assign to `choosing-your-own-dataset` and the two combinations / permutations lessons. Could you add them, please?

Also, currently the combinations/permutations are listed under math... but they really only exist in Oklahoma at this point. Wonder if that's worth distinguishing for ourselves. Everything else in OK exists in either math or data-science

**Comment by schanzer** [comment]
@flannery-denny I've add practices for those three lessons. OK to close?

**Comment by flannery-denny** [comment]
Yes

Flannery
