### ISSUE TITLE
`(sexp->code ...)` appears to generate wescheme-formatted symbols in Pyret mode

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#656]
EXAMPLE: in the `if-expr` branch, build the `image-scatter-plot` lesson. In the very first overview section, you'll see:
![image](https://user-images.githubusercontent.com/77126/140608478-c9bacd6c-3241-4f53-9653-79373af45626.png)

This is subtle, but you'll notice that the code is slightly blue, whereas other places where the lesson uses `image-scatter-plot` look like this:
![image](https://user-images.githubusercontent.com/77126/140608496-2467654f-b862-4c5b-ab49-72666986539b.png)

Opening the inspector shows us that this is being formatted as a wescheme-symbol:
![image](https://user-images.githubusercontent.com/77126/140608514-77ee8b0a-9142-4e88-a4f6-8f7b6e608ac4.png)

This is correct in WeScheme pages, but Pyret pages should use the Pyret codepath for processing the output of this directive.

**Comment by ds26gte** [comment]
I think the classes `wescheme-*`, including `wescheme-symbol`, are simply misnomers. Their use in these cases has always been correct, it's just we need to replace the `wscheme-` with something generic perhaps?

**Comment by schanzer** [comment]
It's not the name that bothers me - it's that the class name means the text is rendered differently.

**Comment by schanzer** [comment]
Fixed by 8a82b894d747f716fd71356720a8c324f7e4b673
