### ISSUE TITLE
Suggested Revisions to Food Habits Project

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#659]
@flannery-denny @schanzer - feedback, please! :)

While attempting to create a rubric for the [Food Habits project](https://bootstrapworld.org/materials/latest/en-us/courses/data-science/lessons/random-samples/pages/food-habits-project.html), I took a reaaaal close look at the project directions and discovered that I would have a very difficult time making this project happen in my sixth grade classrooms!

Perhaps a HS teacher and HS kiddos could run with what's provided, but my sixth graders would need me to break things down much much more. (Interestingly, the [original project / source of inspiration](https://www.idsucla.org/wp-content/uploads/IDS_v3.0_Campaign-Guidelines_Food-Habits.pdf) is even more confusing!)

I took a go at making the project clearer. Let me know what you think. Here's [a google doc](https://docs.google.com/document/d/1xXOrCW-wQw16oemDLimcN5yK802PM1ekgMNMuTGzjDQ/edit?usp=sharing). I will have a much easier time making a rubric from my revised project than from the original, which was the impetus for these revisions! A few changes include:
- outlining the phases of the project (data collection, asking a statistical question, sharing results)
- providing a Google form for kids to just copy and use (rather than making their own). Having my kids make their own form would likely take at least an entire class period. It's a skill they don't have, and I don't really think is important for them to develop that skill for "mini project."
- Giving clearer directions about what should be provided in the slideshow (which will be further clarified in the rubric).
- It was unclear to me what purpose the two lists of questions was serving. I attempted to clarify.

Would love any thoughts/ feedback. Hope it's okay that I went ahead and did this!

**Comment by schanzer** [comment]
This is a terrific improvement! LOVE that you did it. I'll leave some feedback as comments in the doc

**Comment by retabak** [comment]
Also made the similar revisions to Time Use with commit [2fea7c84]  !

**Comment by flannery-denny** [comment]
I pushed a fix to the Time Use project regarding language around gender.
Reworded one cell of the Food Habits Rubric. Otherwise, looks great!
