### ISSUE TITLE
Project Descriptions

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#660]
Dorai:
- [x] Change `@lesson-description` to `@description`
- [x] Allow `@description` to exist in adoc files within `pages/`

Rachel:
- [x] Add descriptive text to each project

**Comment by ds26gte** [comment]
Please also supply place where you want the collected description prose to be automatically shown. Is it in the Mini Projects section of the resources page?  Currently that section is using explicit links and is not autogenerated.

**Comment by schanzer** [comment]
@retabak can answer the question about the resources page (although I think you are right!).

Personally, it would be awesome to have this included in the dependency graph somehow. At the moment I have some hardcoded project->description mappings, which I then programmatically insert into the graph as "lessons" whose prerequisites are the same as the prerequisites for the lessons that contain the project. Having this happen automatically would be pretty fantastic.

**Comment by retabak** [comment]
Yep, this seems right to me - the Mini Projects section of the resources page!
