### ISSUE TITLE
Slide audit for Fall2022

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#662]
- [x] Pyret Files should only be embedded if we don't want students to come back to them.
- [x] If we want students to save or come back to starter files, provide a link on  the page and direct them to open the starter file in a separate tab.
- [x] The first slide of every deck should include a note for teachers "To learn more about how to use pear deck and how to view the embedded links on these slides without going into present mode visit [https://help.peardeck.com/en](https://help.peardeck.com/en)"
- [x] Add this note to the title page of the slide deck template.
- [x] update the correlations slide deck - try to include some displays from the lesson. it is VERY text heavy

**Comment by schanzer** [comment]
Closing, since we're not using PearDeck for fall2022!

**Comment by flannery-denny** [comment]
@schanzer Really? Have teachers said that they don't like it? pretty surprised by that decision. I thought we were using markdown to make slides and then adding things like peardeck interactivity...

**Comment by schanzer** [comment]
Ah, good point!

**Comment by flannery-denny** [comment]
@schanzer much better. I'd suggest deleting slides 9 and 14. Otherwise, ready to close.
