### ISSUE TITLE
Other Starter File Idea - Takes in the name of an animal and produces the image of the animal.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#664]
Here's the draft of a [Pyret starter file](https://code.pyret.org/editor#share=192jU1e0jpGMGap4W8IFUTGkSiziTdIZX&v=1904b2c) to consider making materials for and weschemifying.

**Comment by ds26gte** [comment]
My commits were meant for #644 not this (#664) issue. Please ignore
