### ISSUE TITLE
"Bootstrap" name blog post?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#669]

**Comment by schanzer** [comment]
@flannery-denny @retabak [draft blog post is here](https://bootstrapworld.org/blog/misc/why-the-name-bootstrap.shtml)

**Comment by retabak** [comment]
@schanzer @flannery-denny 
I put the post in a Google doc so I could leave some comments! 
https://docs.google.com/document/d/1b8iF3MGhDMpGSqVcvOGIynbZm9wtSnBUfM2V5HnF3F4/edit#

**Comment by flannery-denny** [comment]
No big framing feedback on this, although I think we could do a better job with these two sentences and my brain isn't working well enough to tackle it at the moment.

`Today, the term "Bootstrap" has become a politically-charged one, used almost exclusively by appeals for individuals in need to "pull themselves up by their own Bootstraps". `

`We use math-aligned languages to let math teachers and students build on what they already know from math, and pedagogies like the Design Recipe to give students a structure to scaffold check their own work.`

A couple of typos:

- third paragraph is missing a parentheses `Kathi Fisler (then at WPI`
- paragraph beginning REASON 3 ` A critical milestone is reache**n** when`

**Comment by schanzer** [comment]
@retabak @flannery-denny see revisions on the google doc.

**Comment by retabak** [comment]
All my concerns have been addressed! Ready to close the issue if @flannery-denny is happy too.

**Comment by flannery-denny** [comment]
@schanzer reads much better!
One final suggestion, take it or leave it and close the issue.
Reason 1: A nod to the past - > Reason 1: A nod to our roots or Reason 1: A nod to our start

**Comment by flannery-denny** [comment]
beginnings?

**Comment by schanzer** [comment]
Love it. Done! Sending Kathi and Shriram a request for feedback, and once I hear back we can add this to our SM calendar...
