### ISSUE TITLE
Toolbar - practices should include the code *and* description

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#675]
Right now they just list the code (see bottom of img, below). They should also list the description (see top of img, below): 

![image](https://user-images.githubusercontent.com/77126/142923173-272eb717-1ebd-4af4-a135-c9339fcde5d9.png)

**Comment by ds26gte** [comment]
Implemented in 6ec55c965

**Comment by schanzer** [comment]
@ds26gte thanks! Any particular reason why these use `LI` elements, but the standards and textbook alignment structures use `DL` elements?

**Comment by ds26gte** [comment]
Pushed. 3e0be8c2e
