### ISSUE TITLE
CODAP nitpicky stuff 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#677]
@schanzer 

**Non-design recipe stuff:** 
- [x]  CODAP refers to "least square line" rather than "linear regression." You proposed I add a note to all relevant lessons about the different names for a linear regression line - but I wasn't certain all those names actually described the same thing. I think you said you were going to talk to Nancy about it?
- [x] We also talked about how we maybe want our worksheets to reflect the step of dragging attributes (from table to data display) - but we couldn't think of a way to capture that on worksheets. We said we'd think on it and revisit. (Consider this a reminder?)

**Design Recipe stuff:**
- [x] Can we make it so the solutions page has a little checkmark next to build / filter / transform (whichever one students ought to circle)?
- [x] Can we make it so that the tables automatically have the same number of rows (even if some of those rows are blank)? (This is my preference, although I can imagine a relatively sound argument against this.)
- [x] The title always includes "Word Problem: " - and there is the assumption that after the colon, we put the name of the Transformer. I don't think I always want to give away the Transformer's name in the title. Can we think of something different? (The Pyret worksheets just say "The Design Recipe" as the title.)
- [x] Can "Name" be in bold and / or not underlined? It looks like part of the solution, rather than a prompt.
- [x] We need some helper text below the big blank lin for the formula expression (i.e. "Pay careful attention to capitalization and quotation marks" or "i.e. Age > 12, or includes(Name,"s")"
- [x] The formula expression solution very often includes quotation marks. Right now, entering those quotation marks creates a whole bunch of errors (see below) and refuses to build when quotation marks are included.
- [x] If I remove the quotation marks in the formula expression, I can build the worksheet but I still get error messages, like this: `asciidoctor: ERROR: .codap-design-recipe-2.asc: line 92: level 0 sections can only be used when doctype is book`

👨‍💻CALLING RACKET IN BATCH MODE
-----------------------------------------------------------
ERROR: keyword<?: contract violation
  expected: keyword?
  given: 's
  argument position: 1st
  other arguments...:
   '#:solutions-mode? in "lessons/__sample-lesson/pages/codap-design-recipe-2.adoc"

ERROR: keyword<?: contract violation
  expected: keyword?
  given: 's
  argument position: 1st
  other arguments...:
   '#:solutions-mode? in "lessons/__sample-lesson/solution-pages/codap-design-recipe-2.adoc"

ERROR: keyword<?: contract violation
  expected: keyword?
  given: 's
  argument position: 1st
  other arguments...:
   '#:solutions-mode? in "lessons/__sample-lesson-codap/pages/codap-design-recipe-2.adoc"

ERROR: keyword<?: contract violation
  expected: keyword?
  given: 's
  argument position: 1st
  other arguments...:
   '#:solutions-mode? in "lessons/__sample-lesson-codap/solution-pages/codap-design-recipe-2.adoc"

**Comment by schanzer** [comment]
@retabak the quotes-in-formulas issue: use backslashes to tell Racket that the quotes are part of the string. See f00eac0ef572bf84722cec348431c229a634594d

**Comment by schanzer** [comment]
@retabak I want to push back on forcing the same number of input v. output rows.

If the author wants there to be the same number of rows, they should provide the same number of input and output rows. It's not up to the build script to enforce this. I could also see a situation where we want to give students a hint about what filter should do by showing only a certain number of blank rows in the output table. Let me know if this convinces you?

**Comment by retabak** [comment]
@schanzer I am convinced! It was more an aesthetics thing for me. This is a more compelling argument and I'm okay with it!

**Comment by schanzer** [comment]
@retabak I did some internet sleuthing, and "least square line" is a synonym for "regression line" _and_ "line of best fit". It's a weird choice of wording, since I don't believe "least square line" is really a term that's used in k12. But yeah, it's worth adding a pedagogy box that lists all the different terms for the same concept, and having that box show regardless of `proglang`

**Comment by retabak** [comment]
@schanzer are you cool with writing this pedagogy note? I could do more internet research but feel a bit out of my depth (aside from just saying, "yep, they're synonyms"). Feels like perhaps we want to talk about how the phrase "least square line" describes the method of finding the line of best fit / regression line?
