### ISSUE TITLE
Deal with basketball dataset feedback

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#680]

**Comment by flannery-denny** [comment]
@schanzer 
I added an identifier column, a Boolean column for if-traded, and a height column.
Any other requests before I make the starter file?
[nba](https://docs.google.com/spreadsheets/d/1C-LqFhkbI5eUKEGGWNXPseA824wCIbAH-Ik9chl9e6I/edit?usp=sharing)
When it's done, do you want it in Spring 2022 or Fall 2022?

**Comment by schanzer** [comment]
I'm happy with these changes - definitely an upgrade! If it's ready for use in the Spring semester let's put it there. 

I think it's fine to stick with attribution as you have it.
