### ISSUE TITLE
HOC Lesson is ready for feedback! Looking forward to hearing your thoughts on this!

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#684]
Lesson plan is here [
https://docs.google.com/document/d/1Y51duGtA2N_yeuN6VEWoG8IRWzRagFGAnFxCUGVbb2A/edit?usp=sharing](
https://docs.google.com/document/d/1Y51duGtA2N_yeuN6VEWoG8IRWzRagFGAnFxCUGVbb2A/edit?usp=sharing)

Please adjust timing on the sections to reflect your experience of them.

If you want to adjust pyret starter files they are here. [https://drive.google.com/drive/folders/1CtfzxOUySppcAEmnzijEXJd-Q_HgjKBs?usp=sharing](https://drive.google.com/drive/folders/1CtfzxOUySppcAEmnzijEXJd-Q_HgjKBs?usp=sharing)

I am inclined to think that there is already a lot going on in this lesson, but [Click this link](https://code.pyret.org/editor#share=1Mmoj9TqlAaLo6QuIirDY8O_Z86sKNWI3&v=1904b2c) to see an idea Nick had about a custom image scatter plot. If either of you is really excited about the first plot adding something to this lesson, I’ll work on cleaning it up.

**Comment by schanzer** [comment]
@flannery-denny left a bunch of comments. I think the 5m time estimates are generally tight. I'd wager they generally average out to 8m for most kids.

**Comment by retabak** [comment]
I looked through part 4 and added comments, will continue with part 5
through the end tomorrow! I agree that 5m per section is tight. For sixth
graders, I'd do 10 min per section - but I don't think that's our target
audience. I like Emmanuel's guess of 8m per section.

**Comment by flannery-denny** [comment]
@schanzer @retabak
I've incorporated all of your googledoc feedback here: [https://docs.google.com/document/d/1Y51duGtA2N_yeuN6VEWoG8IRWzRagFGAnFxCUGVbb2A/edit?usp=sharing](https://docs.google.com/document/d/1Y51duGtA2N_yeuN6VEWoG8IRWzRagFGAnFxCUGVbb2A/edit?usp=sharing)
Thanks!

Before it gets published:

- [ ] It needs to be branded. Preference for Bootstrap: Data Science? Boot? Bootstrap: Data Science with Stemworks reference? None of them look great at the top of this google doc...
- [ ] Decide on delivery platform:

- Google doc is ok with me, but it would be better if the link came from our website rather than our google drive so that it would lead people to poke around.
- It really isn't set up to be printed... which might be a reason to follow Rachel's suggestion of Desmosifying it.

**Comment by flannery-denny** [comment]
@retabak. I talked to @schanzer. We're on board with you desmosifying, assuming each page will link to its pyret file and questions will happen on that page. 

Not sure what the teacher interface looks like. Is it easy to offer up solutions, etc. on the kind of Desmos activity you're envisioning or should I work on an asciidoc of a teacher resource page?

Ultimately we're going to share the link on [this page](https://bootstrapworld.org/materials/latest/en-us/courses/hour-of-code/).
