### ISSUE TITLE
NSF Acknowledgement is showing up twice on all DR pages

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#69]
<img width="1024" alt="Screen Shot 2019-10-03 at 9 31 33 AM" src="https://user-images.githubusercontent.com/43153234/66136158-9f439a00-e5c0-11e9-8964-125e5fd739d0.png">

**Comment by ds26gte** [comment]
I've suppressed the NSF & Copyright notice on the exercise HTMLs, as they're typically included by HTML pages in the workbook directories, which have their own notice. The downside is that the user can browse both the workbook HTMLs and the exercise HTMLs. Maybe the latter should be made unreachable by user (using .htaccess) ...

**Comment by BootstrapJen** [comment]
Thanks! I'll defer to @schanzer about the downside you mentioned and when to close this issue.

**Comment by ds26gte** [comment]
I've added code to make sure the exercise HTMLs also have the Copyright and NSF notice. (The workbook HTML takes care to skin out the Copyright &c part when including an exercise DR.)

**Comment by schanzer** [comment]
@ds26gte why not just hide the copyright notice using the print media attribute?

**Comment by ds26gte** [comment]
That is already happening. This is for the HTML version of the workbook pages that are reachable by browser.  (Viz., an `.adoc` file residing in a `workbook-pages` directory that `include`s a DR `.adoc` file residing in an `exercises` directory.  When converted to HTML (on the way to becoming a PDF) it gets a copyright once for itself, and then again from the exercise file. It's corrected now.  The PDF is always safe from any copyright notices.)
