### ISSUE TITLE
Pathway Standards Upgrade

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#693]
Our current standards page (and standards dictionaries) could use some upgrades:

**Standards, Practices, and Textbook Dictionaries**
- [x] A dictionary should include a link (text and href) to refer to an external site that defines those standards, practices, etc in full

**Standards Page (pathway-standards.shtml)**
- [x] change filename to 'alignment.shtml'
- [x] Change Title to "Practices, Standards, and Textbook Alignment"
- [x] Add textbooks and practices to the multiselect box
- [x] Default selection to CC-Math
- [x] Show link to refer users to the external site for each 
- [x] Lesson links are all *broken!* They haven't been updated to the common-lessons format

**Lesson Toolbar**
- [x] (possibly) include link directly to the Alignment page?

*Coverage Report**
- [x] Generate a duplicate of this file in the top-level, hardcoding CSS to `/lib`, adding _all_ rows (even those not covered)

**Comment by schanzer** [comment]
@ds26gte it occurs to me that this issue has evolved into something almost identical to #572. Both of these issues ask for the same page to be generated, the only difference being that this one should only show rows for which we have coverage, and #572 wants every standard visible.

I suspect the same HTML could be generated for both, with CSS switching off the un-covered rows for this issue. I'm going to close the other issue and swap this one into the Jan milestone in its place.

**Comment by ds26gte** [comment]
Could you put the location of this external-link info here, so I can ensure our standards&c labels refer to them?

**Comment by schanzer** [comment]
**Standards**
Common Core Math: http://www.corestandards.org/Math/
Common Core ELA: http://www.corestandards.org/ELA-Literacy/
NGSS: https://www.nextgenscience.org/
Iowa: https://iowacore.gov/standards/iowa-core-standards
OK: https://sde.ok.gov/oklahoma-academic-standards
CSTA: https://www.csteachers.org/page/standards
K12CS: k12cs.org

**Textbooks**
CMP: https://connectedmath.msu.edu/
IM: https://illustrativemathematics.org/

**Practices**
Social Justice: https://www.learningforjustice.org/sites/default/files/2017-06/TT_Social_Justice_Standards_0.pdf
Science & Engineering Practices: https://ngss.nsta.org/practicesfull.aspx
Math Language Routines: https://achievethecore.org/peersandpedagogy/developing-math-language-routines/
