### ISSUE TITLE
make a pyret version of the snowman starter file to share with teachers on discourse as a week before the holidays activity

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#697]
[https://www.wescheme.org/openEditor?publicId=UgjYPyzBKZ](https://www.wescheme.org/openEditor?publicId=UgjYPyzBKZ)

**Comment by flannery-denny** [comment]
@schanzer if you want me to do this, please share the behind the scenes code from the wescheme file. Thanks!

**Comment by retabak** [comment]
.... could stick the links into a Desmos activity with a tiny bit of instruction and share it in the Desmos facebook group too! Folks always want holiday activities. Happy to throw something together, thinking it would be very simple.

**Comment by flannery-denny** [comment]
**WeScheme files from Jen**
[Snowman Teachpak](https://www.wescheme.org/view?publicId=ZiSamMGVV1)
[Snowman Puzzle](https://www.wescheme.org/view?publicId=tt8HB7mig9)

**Draft of Pyret files from Flannery** - context isn't quite working...
[Snowman Puzzle](https://code.pyret.org/editor#share=1Lgax_uAdFxUJzyGKPbx2BESj9BNkTK3i&v=1904b2c)
[Snowman Context](https://code.pyret.org/editor#share=1tUtN7form62YHxvBH2R2eHFG_klGNlC5&v=1904b2c)

@schanzer. Any idea why the puzzle says that all of the things defined in the context are unbound?

**Comment by schanzer** [comment]
@flannery-denny my hunch is that the context doesn't provide any of those symbols. You'll need to add one or more `provide ...` expressions at the top of the context file.

For reference, here's a snippet from the top of the fall2022 algebra context:
```
provide *

import color as C
import math as M
include reactors
include image-structs
include reactors
import sets as S

import lists as L
provide from L: 
  *,
  type *, 
  data *
end
import image as I
provide from I:
  *,
  type *,
  data *
end
```

I think you only really need the `image` code, and the top-level `provide *` expression

**Comment by flannery-denny** [comment]
Thanks. that solved it. Meant to use the algebra context but the new essentials tricked me into thinking they had everything I needed :)
