### ISSUE TITLE
simplify snowman hour of code lesson and desmosify it for easy sharing.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#699]
- [x] Swap Enter/Shift-Enter
- [x] Delay calls to `parley.run()` and see if we can avoid rapid-clicking that stalls the editor
- [x] make image take up full screen (see slide 15)
- [x] Various CSS glitches, in descending order of priority: input box is too talk, narrow windows cause the buttons to overlap,
- [x] would be nice to have a `loaded` callback handler in Repartee, so we can display a "loading" indicator the first time it loads and then hide it and run the code when it's ready. At the moment there's just a long pause on the first card, and then the call to `play()` gets swallowed before the editor loads so there's no output
- [x] Which name should we use in the directions we give kids? chatitor? repartee? something else?
- [x] Currently every slide has to use the code `include image` - can we load context essentials instead?
- [x] Currently repartee uses a smaller list of colors than pyret. Is this going to change?
- [x] Auto-Run code after each slide loads
- [x] Make a reset button that can be used on every page.
- [x] Add `videoConfig`
- [x] Embed repartée in old HoC infrastructure (see https://github.com/jpolitz/embed-repartee-example)

**Comment by schanzer** [comment]
@flannery-denny if there are more action items for this, can you add them to the issue? From here, I can't tell what else is left to do.

**Comment by flannery-denny** [comment]
Nothing has been done on this issue at all. It was deemed not urgent. We can discuss at our meeting.

Flannery

**Comment by flannery-denny** [comment]
perhaps wait and make use of repartee for this?

**Comment by flannery-denny** [comment]
Investigating whether [https://pyret-anchor.s3.amazonaws.com/anchor/index.html](https://pyret-anchor.s3.amazonaws.com/anchor/index.html) will make any of [this ](https://bootstrapworld.org/materials/fall2022/en-us/lessons/hoc-winter/index.shtml#)more accessible in preparing students for [this](https://code.pyret.org/editor#share=1Lgax_uAdFxUJzyGKPbx2BESj9BNkTK3i&v=1904b2c)

**Comment by flannery-denny** [comment]
@schanzer Any reason we couldn't use this [same infrastructure](https://bootstrapworld.org/materials/fall2022/en-us/lessons/hoc-winter/index.shtml#) and embed pyret or ide in it instead of wescheme?

**Comment by schanzer** [comment]
@flannery-denny pyret doesn't support embedded mode the way WeScheme does. (Sorry if this is a dumb question, but what's "ide"? Is this the thing Joe is working on?)

**Comment by schanzer** [comment]
Ah! So it is. It _might_ make it more accessible, but that's quite a ways in the future and will not be done for HoC this year. Let's stick with CPO for now.

**Comment by flannery-denny** [comment]
@schanzer We made a plan as a team in a full team meeting that we would explore using Joe’s new thing for hour of code. I had a meeting with him yesterday. It’ll be ready for TAs next week and ready  for Shriram’s class by end of month. I’ve been playing around with it. Seems promising that we’ll want to use a combination.

**Comment by schanzer** [comment]
That's great to hear that it will be ready! Unfortunately, it's unlikely we'll be able to reuse the infrastructure developed for WeScheme. I'll talk to Joe and see how much work it would take.

**Comment by flannery-denny** [comment]
@schanzer This is a sketch of where we're headed

[google slide draft](https://docs.google.com/presentation/d/1nXoDw7AG4wHn1GFySM4lKxoyo2wl82GmEey0E0kg3mM/edit?usp=sharing)

I don't think it's productive for me to go further with this until there's a place for me to work with it on git. if you need more details in order to sort out the infrastucture end of things lmk and I'll add it to next week's meeting.

**Comment by flannery-denny** [comment]
[https://pyret-anchor.s3.amazonaws.com/anchor/index.html#:~:text=program.arr-,snowman,-.arr](https://pyret-anchor.s3.amazonaws.com/anchor/index.html#:~:text=program.arr-,snowman,-.arr)

**Comment by flannery-denny** [comment]
consider using desmos with pyret instead of custom w repartee if repartee.

**Comment by schanzer** [comment]
Most embedding work is now complete, modulo a few CSS questions for Joe and behavior questions for Flannery.


https://user-images.githubusercontent.com/77126/190872197-ede2ad9b-b794-44db-99c6-bc15103996da.mp4

**Comment by flannery-denny** [comment]
@schanzer 
- [ ] How do we/students advance from one slide to the next?
- [ ] Why are there trailing ordered lists on the first slide?
- [ ] How do I embed a traditional Pyret starter file on the last slide?
![Screen Shot 2022-09-22 at 7 18 38 AM](https://user-images.githubusercontent.com/66691020/191734067-5b9ffd76-6c5d-4742-b68d-7df6d0932179.png)

**Comment by schanzer** [comment]
@flannery-denny If you check in your HTML I can take a look at it. Looks like you may have some dangling or unclosed tags somewhere.

**Comment by flannery-denny** [comment]
@schanzer I updated everything that I know how to do with this file and checked in my work first thing this morning. Reminding you that I'm working on the hoc branch. Thanks for looking at it.

**Comment by schanzer** [comment]
@flannery-denny reset button added

**Comment by flannery-denny** [comment]
@schanzer Once I know what Joe is / isn’t going to do, I will polish this. Some wording is dependent on how it’s going to work so it will definitely need another look before release.

Flannery

**Comment by retabak** [comment]
@flannery-denny - I'd love to take a look at how this has progressed! How / where do I find it?

**Comment by flannery-denny** [comment]
@retabak you'll need to get @schanzer to help you if you want to see this... and perhaps it makes more sense to wait until it's actually all working.

It works something like the following, but I am not currently able to make it work on my computer, so I figure Ive forgotten a step in the last several weeks...

1. check out to the `hoc` branch.
2. build the `hoc-snowman-repartee` lesson (I do this by putting it in my `__sample` pathway
3. navigate to `lessons` (not `distribution/lessons`)
4. click on `run-locally`
5. open the index file from the lesson
6. expect that you should be able to navigate between the slides, but there are still things that don't work because the team is still building the infrastructure for them.

**Comment by schanzer** [comment]
@flannery-denny a few corrections:

1) there's no need to build. You can run locally right from the lesson folder. This will launch the web server in a terminal window.

2) do NOT open the html file - instead, visit the address of the Web server (it's printed in the terminal).

This is because embedding pirate only works when served, and not when read from a local file

**Comment by schanzer** [comment]
@flannery-denny I've added a `videoConfig` option, along with an example slide. Do you want the videos to start playing automatically?

**Comment by flannery-denny** [comment]
@schanzer Thanks! I think it probably makes sense for the video to play automatically.

**Comment by schanzer** [comment]
@flannery-denny so, I have bad news -- I just investigated, and it turns out that autoplay ONLY works when the video is _muted!_ Personally, I think it would be way more confusing for kids to see the video playing without audio than for them to realize they need to press play.

Thoughts?

**Comment by flannery-denny** [comment]
There is no audio for that video.

**Comment by schanzer** [comment]
Check your speaker settings. I hear audio when I play.

**Comment by flannery-denny** [comment]
@schanzer I went back and relistened to that quicktime video `snowman.mov` and I'm still not hearing the audio that you are... I don't believe there is any.

I changed `movieConfig` to `videoConfig` on slide 13 where it's supposed to run and it's still not loading... Is that because it's `.mov` instead of `.mp4` (not sure how to change this - Quicktime doesn't seem to want to let me do that)? Or is there a different explanation?

Instead of inserting an irrelevant video at the beginning of the lesson (which I've tried to remove and cannot), could you please figure out how to get the video on slide 13 to load and play? Happy to make a time to work on it together if you prefer.

Also, I've written to Joe about this, but I'm getting errors on slide 8 and 10. I know that colors like 'lightgrey' are more complex than others, but I'm not sure why the type error message would refer to `red`
![Screen Shot 2022-10-19 at 2 16 06 PM](https://user-images.githubusercontent.com/66691020/196789049-6c84ecc9-97cc-44d1-99a0-869d18dea55f.png)

**Comment by schanzer** [comment]
@flannery-denny I'm not sure what `snowman.mov` is, but the movie I added as a sample is called `sample.mp4`. Can you really not hear any audio in the example I made?

On slide 13, you wrote: `<li videoConfig="videos/eye.mov">`, but when I look in the videos folder I don't see that movie. It should play once you add it, but if there's no file it won't be able to play.

What irrelevant video are you talking about? Do you mean the one I added as a demo for you to work from? Feel free to remove the `<li>` that I inserted before Page 1.

I don't know what's going on with the error message, but I'll ask Joe when we meet tomorrow.

**Comment by schanzer** [comment]
@flannery-denny absolutely positive. [It's not in your github branch folder](https://github.com/bootstrapworld/curriculum/tree/hoc/lessons/hoc-winter-repartee/langs/en-us/videos). Looks like it's on your computer, but not checked in.

**Comment by flannery-denny** [comment]
@schanzer I pushed another attempt at getting you what you need. lmk if there's still an issue

**Comment by schanzer** [comment]
@flannery-denny the video shows up and plays beautifully! And no, `eye.mov` does not have any audio. Feel free to delete the example video from slide "zero", since now you've got it working.

Aside from bugs in Joe's wheelhouse, is there anything else you need from me?

**Comment by schanzer** [comment]
@flannery-denny turns out that Pyret has "darkgray", but not "darkgrey" -- even though the documentation claims otherwise. Joe is working on it now, and also on throwing a helpful error message for when an unknown color is used

**Comment by schanzer** [comment]
@flannery-denny I've pushed a temporary CSS hack that fixes Parley things. Eventually Parley will include them, so we can delete them from our repo. Beyond that, I think this is...done? :)

**Comment by retabak** [comment]
Can I peek?! 

@flannery-denny gave me this link but it doesn't work: https://bootstrapworld.org/materials/fall2022/en-us/lessons/hoc-winter-parley/index.shtml#

What branch is this on?

**Comment by schanzer** [comment]
it's on `hoc` - but the link will work. I was able to take out the need for `.shtml`, so just go here: [https://bootstrapworld.org/materials/fall2022/en-us/lessons/hoc-winter-parley/](https://bootstrapworld.org/materials/fall2022/en-us/lessons/hoc-winter-parley/index.shtml#)

**Comment by retabak** [comment]
Wow! i'm so pumped about this HOC! So cool!

General notes: I wonder if we should say something about how you need to fix / delete buggy code for subsequent code to be read? Assuming this activity is self-guided, that seems like the one thing that could trip students up and cause them to get needlessly frustrated / give up. Or, maybe that should be an error message that appears when it happens? 

Nitpicky things:
- [ ] Slide 8 - "Defining and Composing Functions" - we should say _What do you think will happen if you type head and hit "Ctrl-Enter"? Test it out._ (Hitting "enter" just gets a new line.)
- [ ] Slide 13 - This slide needs some love. 
"So far we have been working in the chatitor version of Pyret. More complex programs get written in a different view." Kids won't know what "chatitor" means, nor will they know what "Pyret" is. (In fact, I googled "chatitor" and found NOTHING! Is that a real word?) Also, this slide is the first time kids see the word "Repartee." They might not know that they are working in Repartee. 

How about instead we say, _So far we have been working in Repartee, where code is evaluated as you type it.  Repartee is a SOME NICE ADJECTIVE version of Pyret, a platform that allows us to write more complex code. Here you see a screenshot of our classic Pyret editor._  Then remove the bullet about Repartee. And delete the extra period after the first bullet.

I would also delete "with the file pictured" from the last sentence - I think it's confusing.  That's the file that will open automatically when they click the button, so we dn't need to specify.

- [ ] Slide 14 - "When you click open the file linked below" - delete "click" 
- [ ] Slide 14 - just curious - why are we defining the snowman pieces behind the scenes? I feel like kids might be interested in seeing the code (and perhaps modifying it - changing hat color, carrot size). Is there a reason we are hiding this code?

**Comment by flannery-denny** [comment]
@retabak you asked for an in process peek. There hasn’t been any wordsmithing yet because the slides were made while the interactivity (and nomenclature) was still in development. Once I’m done, I’ll let you know where you can make edits.

Flannery

**Comment by retabak** [comment]
I saw Emmanuel's comment that maybe this issue was possibly done and was worried I missed the window Woops!

**Comment by flannery-denny** [comment]
@schanzer I've pushed my edits. Please push to the web when you and Joe are done addressing the things you were working on (It looks like he's already fixed the "Enter to submit" issue) and let @retabak know that it's ready for feedback.

@retabak To answer your question, it is important that this file use a teachpak because this is designed to be the first hour of coding exposure students will get and there are lots of opportunities for them to be overwhelmed and break the code if everything is visible. The concrete improvement that has been made over the previous iteration is that we have both given them a notional machine of what is actually happening behind the scenes and the tools to be empowered to define their own values if they are motivated to do so.

**Comment by schanzer** [comment]
@flannery-denny just push fixes to the snowman image and rapid-card-switching-breaks-run.

**Comment by retabak** [comment]
Things that I noticed throughout:
- [ ] Every intsance where it says to hit "Enter", it needs to say "Ctrl-Enter"
- [ ] Throughout, I suggested an idea re: the "make a prediction, click here" buttons. Take it or leave it! 
- [ ] General question about numbered items - at first, I thought they were always things for kids to do / code / type. That seemed to be how you were using them in the first few cards. As I progressed through the cards, the numbered items were also "thinking prompts" - for instance, "Why does right-triangle need two numbers?" - with no prompt. I think I'd like to see the numbered items represent a request for a particular student action, and maybe questions are not numbered?

Card 1:
- [ ] _The editor automatically runs each line of code_ -- Can we say actually "automatically." Maybe, "Once we submit a line of code, the Editor reads it and responds"? 
- [ ] _Then click the Update responses button or hit "Enter" to re-run the code._ - I'd say, "Then click the Update responses button - it's blue and in the upper left - or hit Ctrl-Enter to re-run the code." (I did the entire activity without noticing that button.)

Card 2: 
- [ ] What if we said, "Make a prediction then click the button to add the code to the editor and see the result." And then the button actually had some silly text on it, like, "Show me the star!" Seems more intuitive to me - and like it might slow kids down a bit / encourage them to actually make the prediction..
- [ ]  Change "Enter" to "Ctrl-Enter"

Card 4:
- [ ] I think we need to explicitly emphasize that kids need to CHANGE the code that's there, not type their revision in as a new entry. Assuming this activity is self-guided, that seems like the one thing that could trip students up and cause them to get needlessly frustrated / give up. 
- [ ] It's a little funny to have a numerated list with one item... but I don't know what the next item might be.

Card 5:
- [ ] On previous cards, the numbered lists were things for kids to do, and that's not the case here.
- [ ] Change Enter to "Ctrl-Enter"
- [ ] Same suggestion here re: the button. Say: "Make a prediction, then click the button to test it out!" Then the button would say, "Swap 50 and 100!"

Card 6:
- [ ] same suggestion re: button
- [ ] is it possible for the bolded headings not to be indented? Right now, it looks like you forgot to ennumerate "Experiment with right-triangle"

Card  7:
- [ ] Ctrl-Enter

Card 11:
- [ ] numbered list with one item again

Card 12:
- [ ] period and exclamation mark at the end of third item

**Comment by flannery-denny** [comment]
@retabak the ctrl-enter situation was a bug that joe introduced for about 6 hours and is not how it currently or should work. If you are still seeing that please report back.

Let's do a quick zoom about the rest and put this to rest together.

**Comment by schanzer** [comment]
@flannery-denny and @retabak Joe has come through with a fix for the Enter/Shift-Enter issue. 

After pulling the latest version of this branch, run `npm update` and test as you normally would. (I've also updated the version on the web)

**Comment by flannery-denny** [comment]
@schanzer please push my last commit and then close this issue.

**Comment by schanzer** [comment]
Done! Great work pushing this over the finish line
