### ISSUE TITLE
BSA:Coordinates2

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#7]
- [x] AsciiDoc tags are leaking through.  ![image](https://user-images.githubusercontent.com/77126/56448174-22a35480-62db-11e9-90a4-904e1a252114.png)
- [x] Use bulleted lists ![image](https://user-images.githubusercontent.com/77126/56448186-3949ab80-62db-11e9-9e83-bcd647250420.png)
- [x] Use bulleted lists ![image](https://user-images.githubusercontent.com/77126/56448191-46ff3100-62db-11e9-8a97-5f0884ca1547.png)

**Comment by edcamposjr22** [comment]
fixed ascii tag leaking through and bullets

**Comment by schanzer** [comment]
Need to use bullets for `create/apply` section.

**Comment by edcamposjr22** [comment]
The bullets look fine on my end and all the links work.
