### ISSUE TITLE
In PD Workbook - links are rendering as both shortcut text and big messy links

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#70]
<img width="914" alt="Screen Shot 2019-10-03 at 9 29 45 AM" src="https://user-images.githubusercontent.com/43153234/66136056-76230980-e5c0-11e9-9be1-ce05f4b2e361.png">

**Comment by ds26gte** [comment]
These are intentional by the PDF converter. Since link texts are not clickable on paper (i.e., dead tree), the small-type URL is the info the reader can use to go the link by other means. 

But this info is arguably not needed here, so I've used CSS to suppress it.
