### ISSUE TITLE
Restore link to about-datasets.adoc

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#700]
I made a big push last year to write a paragraph about each of our datasets. 

When the undergrads came on board in the winter, we made infrastructure called `about-dataset` to support them in writing useful descriptions.

Each time a dataset was added, authors wrote one of those fragments and added the fragment name to the main document.

The main file was supposed to be available to teachers on the teacher resources page.  I can not find any of those files any where on master or a link to the file on the website.

Do either of you know what happened?

**Comment by schanzer** [comment]
It's in the teacher resources folder, inside `pages`. See `datasets-overview.adoc`.

It looks like the link got removed in the TR page cleanup a while back, but it should definitely be returned!

**Comment by flannery-denny** [comment]
@schanzer That's an old version. It doesn't make use of the fragments. The fragments are missing.

**Comment by schanzer** [comment]
Files found, and added to master
