### ISSUE TITLE
detailed-oriented review of CODAP lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#703]
Hi, @flannery-denny ! Lucky you, @schanzer has declared that you are the best person to take a detail-oriented look at the five CODAP lesson drafts. We want to make sure *everything* is in working order, including workbook pages, slides, etc. Also, do the workbook pages make sense and feel useful? Are directions clear? Could you actually learn to use CODAP based on these materials?

At the moment, only the first three are ready for your eyes. Last two should be available for you soon. I'll let you know when, but didn't want to delay.

- [x] displaying-categorical-data
- [x] table-methods
- [x] method-chaining
- [x] random-samples
- [x] grouped-samples

**Comment by flannery-denny** [comment]
@schanzer a preliminary infrastructure noticing is that the codap version of datascience displays prerequisites that don't exist in the codap pathway... perhaps this will just magically disappear when the pathway is built? but I'm guessing not.

**Comment by schanzer** [comment]
Yeah, this is something we punted on for the time being. I'm _really_ hesitant about asking Dorai to build in a way to turn warnings off on a per-language basis. I think the right answer here is either to decouple the lesson's dependence on contracts OR (more likely) make a different lesson entirely that just focuses on introducing students to CODAP.

**Comment by flannery-denny** [comment]
@schanzer Lmk when you’re available  to talk.

**Comment by flannery-denny** [comment]
**Re: Displaying Categorical Data:**

- [ ] As someone new to codap, I don't feel I have the information to answer this question and it's frustrating... I have zero indication of which columns the graph is being generated from. Why ask it and leave me feel like I'm missing something?

> How do you think the position of each dot is determined?

- [ ] Why do you have them make two bar charts in exploring displays? If you are concerned about not have more-displays only have one plot (I'm not) and the only solution you can come up with is to make two bar charts, save the second bar chart for the 6th assignment so that students don't run out of time with repeated explorations of the same display type before engaging with the others.

See suggested edits in commit.

**Comment by flannery-denny** [comment]
**General Slide Deck Feedback**
In the math pathway, every slide deck is titled **Character Animation - Pyret** or **Character Animation - WeScheme**. We haven't had to do this in Data Science because everything was in Pyret, but big mistakes will be made if we don't identify the language of the slide deck now that Data Science is bilingual.

@retabak @schanzer I would expect to see these slidedecks stored in the 
```shared google folder/curriculum/data science/slide decks/spring 2022```
 or
 ```curriculum/data science-codap/slide decks/spring2022``` 

I am not finding them in either place. Please decide which makes more sense and update slide deck names. Thanks!

**Comment by schanzer** [comment]
All the decks are in fall2021 and fall2022. Rachel has added the CODAP decks to Fall2022, since they will likely be in beta mode until then.

All filenames have already been corrected.

**Comment by flannery-denny** [comment]
@schanzer I corrected file names. I am not going to read fall2021 versions.

**Comment by schanzer** [comment]
I don't think there's a need for the fall2021 names to change. Agreed?

**Comment by flannery-denny** [comment]
agreed. To be clear, storing them in Fall2022 folders and linking to them from Spring 2022 release means that when the decks get updated during beta for the Fall2022 release, Spring2022 lesson will link to changing slide decks

**Comment by schanzer** [comment]
@flannery-denny yep - that's it exactly.

**Comment by flannery-denny** [comment]
**RE: TABLE METHODS**

- [ ] Function Cards link doesn't work
- [ ] In some of our lesson plans, like [this one, for example,](https://bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/lessons/piecewise-functions/index.shtml) we offer sample answers to discussion questions. Wondering if that might be helpful for some of these big questions about codap?
- [ ] There are a lot of directions in this lesson for students to type very specific things into the formula expression box. I would suggest making some more @opt-printable exercises to support classrooms in being less teacher dependent.
- [ ] This is the first I'm seeing the word "test" and I stumbled on it and looked at the Domain for the word test before finishing reading the sentence. Is the word test a special codap word? Or could the sentence be simplified?

> Notice that the Domain for Filter says that test must be a formula, which consumes a Row and produces a Boolean

**Comment by flannery-denny** [comment]
**RE: METHOD CHAINING** WIP

- [ ] one of the links is formatted incorrectly
![Screen Shot 2021-12-15 at 10 53 19 AM](https://user-images.githubusercontent.com/66691020/146229885-c55b551f-c7aa-43ff-86c6-730989dbf6e7.png)

**Comment by flannery-denny** [comment]
@retabak @schanzer I'm done reading the 3 lessons that are ready for my review. Generally things look much better than the last time I peeked into this world. 

Let me know when one of the other lessons is ready for review, when the issues in one of these lessons have been resolved and are ready for another look, or if any of the feedback I left is worth discussing.

**Comment by retabak** [comment]
New to-dos for Rachel:

Displaying Cat Data:

- [ ] Change solutions to exploring-displays-1 and exploring-displays-2 to be hand-drawn rather than pyret produced; use same images for CODAP and pyret sets of worksheets
- [ ] plotting points worksheet needs revamp - insert tables [(like these)](https://docs.google.com/document/d/1tKhN44xqVb3gpjJHNuOahkqu7Q4m2BKRcWyVrBOci8c/edit?usp=sharing)

**Comment by retabak** [comment]
Hi, @flannery-denny ! 

If you want to revisit these five CODAP lessons, they are _mostly_ ready for you. 

I say "mostly" because I have new list of to-dos for myself (these felt a bit more labor intensive) after going through your feedback. (In other words, the majority of your concerns have been resolved, but not all of them.) 

Feel free to give me more to-dos!

**Comment by flannery-denny** [comment]
Intro to CODAP & Displaying Categorical Data -WIP

- [ ] lists itself as a prerequisite

**Comment by flannery-denny** [comment]
@schanzer Do you know why the CODAP animals-table uses gender instead of sex and how to fix it?

**Comment by schanzer** [comment]
Here's what I see:
![image](https://user-images.githubusercontent.com/77126/148944511-77452968-d89a-4810-8a4e-d2b2c8cbbf6e.png)


Am I looking in the wrong place?

**Comment by flannery-denny** [comment]
That’s great news! And means Rachel already knows how to fix it and just hasn’t fixed it everywhere.

Flannery
