### ISSUE TITLE
Build systems does not seem to be utilizing practices-sj-dictionary.rkt

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#705]
> WARNING: Lesson plan lessons/displaying-categorical-data/index.adoc: Standard SJ.2 not found

WARNING: Lesson plan lessons/displaying-categorical-data/index.adoc: Standard SJ.4 not found

WARNING: Lesson plan lessons/displaying-categorical-data/index.adoc: Standard SJ.7 not found

**Comment by schanzer** [comment]
The SJ practices were not added as standards, so these errors are accurate. You'll want to do the alignment in `lessons-and-practices`.
