### ISSUE TITLE
Switching back to default textbook alignment shows up empty

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#708]
In lesson defining-values, the default textbook alignment (`IM.Alg.1`) shows `IM.Alg1.4.2 - Function Notation`. However, if you choose a different textbook in the dropdown and go back to `IM.Alg.1`, nothing is shown under it.

**Comment by schanzer** [comment]
@ds26gte the value in the `option` elt is "textbook-IM_Alg.1" (with a dot). But the loop that compares the selection to the standards tables is seeing the value "textbook-IM_Alg_1". I couldn't find where this string munging happens, but somewhere along the lines the dot is turning into an underscore.
