### ISSUE TITLE
bug report --proglang codap

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#709]
When I delete my distribution and `./build-pathway data-science-codap --proglang codap --book` I get about a million warnings (see below - please note that many of these warning are for lessons that are not part of this pathway!). 

And when I click on the pdf versions of the pages in the method-chainging-codap/pages folder I get pyret pages. I also get a pyret version of the lesson plan. 

But when I built without --book, I got codap versions of the files and the codap versions still exist in the codap folder nested inside of pages.

> copying distribution/en-us/lib
📁 PREPARING LESSONS
-----------------------------------------------------------
preparing grouped-samples
 Completed in 8 s
building lesson plan: grouped-samples-codap

💀 BUILDING PATHWAY: en-us/data-science-codap
-----------------------------------------------------------
building /resources/solution-pages
building teacher resources: data-science-codap → resources → index.adoc

 Completed in 1 s
 
👨‍💻CALLING RACKET IN BATCH MODE
-----------------------------------------------------------
WARNING: Lesson plan lessons/displaying-categorical-data/index.adoc: Standard SJ.2 not found

WARNING: Lesson plan lessons/displaying-categorical-data/index.adoc: Standard SJ.4 not found

WARNING: Lesson plan lessons/displaying-categorical-data/index.adoc: Standard SJ.7 not found

WARNING: Lesson displaying-categorical-data: opt-printable-exercise refers to nonexistent file lessons/displaying-categorical-data/pages/infographic-rubric.html

WARNING: Lesson plan lessons/displaying-categorical-data-codap/index.adoc: Standard SJ.2 not found

WARNING: Lesson plan lessons/displaying-categorical-data-codap/index.adoc: Standard SJ.4 not found

WARNING: Lesson plan lessons/displaying-categorical-data-codap/index.adoc: Standard SJ.7 not found

WARNING: Lesson displaying-categorical-data-codap: opt-printable-exercise refers to nonexistent file lessons/displaying-categorical-data-codap/pages/infographic-rubric.html

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/ds-intro

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/contracts

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/displays-and-lookups

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/histograms

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/histograms2

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/measures-of-spread

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/scatter-plots

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/ds-intro

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/contracts

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/displays-and-lookups

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/defining-functions

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/defining-table-functions

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/choosing-your-dataset

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/histograms

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/histograms2

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/measures-of-spread

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/scatter-plots

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/correlations

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/linear-regression

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/ethics-and-privacy

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/ds-intro

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/contracts

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/displays-and-lookups

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/defining-functions

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/defining-table-functions

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/choosing-your-dataset

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/if-expressions

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/histograms

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/histograms2

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/measures-of-spread

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/scatter-plots

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/correlations

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/linear-regression

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/ethics-and-privacy

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/threats-to-validity

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/pages/../../../../lessons/contracts

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/ds-intro

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/contracts

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/displays-and-lookups

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/histograms

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/histograms2

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/measures-of-spread

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/scatter-plots

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/ds-intro

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/contracts

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/displays-and-lookups

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/defining-functions

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/defining-table-functions

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/choosing-your-dataset

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/histograms

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/histograms2

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/measures-of-spread

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/scatter-plots

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/correlations

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/linear-regression

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/ethics-and-privacy

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/ds-intro

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/contracts

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/displays-and-lookups

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/defining-functions

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/defining-table-functions

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/choosing-your-dataset

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/if-expressions

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/histograms

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/histograms2

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/measures-of-spread

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/scatter-plots

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/correlations

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/linear-regression

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/ethics-and-privacy

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/threats-to-validity

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/simple-datatypes

WARNING: courses/data-science-codap/resources/solution-pages/implementation-options.adoc: @link refers to nonexistent file courses/data-science-codap/resources/solution-pages/../../../../lessons/contracts

WARNING: Pathway narrative courses/data-science-codap/index.adoc: @link refers to nonexistent file courses/data-science-codap/../../ImplementationNotes.shtml

 Completed in 8 s
 
👨‍💻CALLING ASCIIDOCTOR IN BATCH MODE
-----------------------------------------------------------
asciidoctor: ERROR: .index.asc: line 60: include file not found: /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/courses/data-science-codap/lessons/choosing-your-dataset/fragments/.cached/.dataset-table.asc
 Completed in 2 s
 
👨‍💻POST-PROCESSING HTML
-----------------------------------------------------------
 Completed in 37 s
 
BUILDING PAGELIST JSON FOR LESSONS
🖨️PRINTING TO PDF
-----------------------------------------------------------

== Start:     2021-12-15 11:46:06.034
== Now:       2021-12-15 11:47:06.919 (running for 1.0 minutes)
== Progress:  123 / 123 (100.00%), errors: 1 (0.81%)
== Remaining: 0.0 ms (@ 2.02 pages/second)
== Sys. load: 68.3% CPU / 96.9% memory
== Workers:   4
   #0 IDLE 
   #1 IDLE 
   #2 IDLE 
   #3 IDLE 
 Completed in 62 s
 
WARNING:  ../../lessons/displaying-categorical-data-codap/pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/displaying-categorical-data-codap/solution-pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/pages/samples-from-animals-dataset.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/solution-pages/samples-from-animals-dataset.pdf has 2 pages
WARNING:  ../../lessons/displaying-categorical-data-codap/pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/pages/samples-from-animals-dataset.pdf has 2 pages
WARNING:  ../../lessons/displaying-categorical-data-codap/solution-pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/solution-pages/samples-from-animals-dataset.pdf has 2 pages
Flannerys-MacBook-Air:curriculum flannery$ ./build-pathway data-science-codap --proglang codap --book
📁 PREPARING LESSONS
-----------------------------------------------------------
preparing method-chaining
 Completed in 3 s
building /method-chaining/solution-pages

💀 BUILDING PATHWAY: en-us/data-science-codap
-----------------------------------------------------------

 Completed in 1 s
 
👨‍💻CALLING RACKET IN BATCH MODE
-----------------------------------------------------------
 Completed in 2 s
 
👨‍💻CALLING ASCIIDOCTOR IN BATCH MODE
-----------------------------------------------------------
 Completed in 0 s
 
👨‍💻POST-PROCESSING HTML
-----------------------------------------------------------
 Completed in 2 s
 
BUILDING PAGELIST JSON FOR LESSONS
🖨️PRINTING TO PDF
-----------------------------------------------------------

== Start:     2021-12-15 12:28:57.135
== Now:       2021-12-15 12:29:02.981 (running for 5.8 seconds)
== Progress:  6 / 6 (100.00%), errors: 0 (0.00%)
== Remaining: 0.0 ms (@ 1.03 pages/second)
== Sys. load: 44.5% CPU / 98.4% memory
== Workers:   4
   #0 IDLE 
   #1 IDLE 
   #2 IDLE 
   #3 IDLE 
 Completed in 6 s
 
WARNING:  ../../lessons/displaying-categorical-data-codap/pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/displaying-categorical-data-codap/solution-pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/pages/samples-from-animals-dataset.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/solution-pages/samples-from-animals-dataset.pdf has 2 pages
WARNING:  ../../lessons/displaying-categorical-data-codap/pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/pages/samples-from-animals-dataset.pdf has 2 pages
WARNING:  ../../lessons/displaying-categorical-data-codap/solution-pages/bar-chart-notice.pdf has 2 pages
WARNING:  ../../lessons/grouped-samples-codap/solution-pages/samples-from-animals-dataset.pdf has 2 pages

**Comment by flannery-denny** [comment]
@schanzer @ds26gte Please note the updated this issue description above. 
I am only seeing one error in this entire mess and it has nothing to do with this pathway.

**Comment by flannery-denny** [comment]
Still getting this error when I -F build without --book, but I'm back to seeing the Codap version of the lesson plan...

> 👨‍💻CALLING ASCIIDOCTOR IN BATCH MODE
-----------------------------------------------------------
asciidoctor: ERROR: .index.asc: line 60: include file not found: /Users/flannery/Documents/Bootstrap/curriculum/distribution/en-us/courses/data-science-codap/lessons/choosing-your-dataset/fragments/.cached/.dataset-table.asc

**Comment by schanzer** [comment]
@flannery-denny I see the revised wording, and I agree there's a bug regarding PDFs. Looking into it now.

The million warnings you're seeing all come from the teacher resources folder, which appears to be unchanged from the original DS pathway. I've removed some of the Pyret-pathway- or Pyret-language-specific material from that page, which reduces most of the link noise.

**Comment by schanzer** [comment]
Fixed by 950ff08213b55648cc03fc1a5816c859bc5cee05
