### ISSUE TITLE
Issues with conditional DRs

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#71]
- [x] `ask:`, both `end`, `then:` and pipes should show up in both blank DR page and solution page. (See image for example of how it should look on blank DR page)
<img width="471" alt="Screen Shot 2019-09-23 at 10 55 40 PM" src="https://user-images.githubusercontent.com/43153234/66138908-1418d300-e5c5-11e9-8820-b69837d31e72.png">

- [ ] Text is running over the `then:` (see image)
<img width="585" alt="Screen Shot 2019-10-03 at 10 00 47 AM" src="https://user-images.githubusercontent.com/43153234/66138863-f8adc800-e5c4-11e9-9300-d26dceecfaed.png">

**Comment by ds26gte** [comment]
It looks like it's the PDF that's getting all scrunched up. But there isn't a way to do line-splitting (with repeated indentation) for PDF and not for HTML.

I've used a heuristic to split `ask` lines that are "too long", and it covers this example. We can tune.
