### ISSUE TITLE
CODAP Workbook PDF issues

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#711]
This is a mix of papercuts, some of which require authoring (Rachel), CSS styling (Emmanuel) or some `codap-design-recipe` directive work (Dorai). These issues are based on courses/data-science-codap/workbook/workbook.pdf. Page numbers refer to the _page order in the PDF document_, not the number written at the bottom of the page.

**For Rachel**

- [x] (Page 3) the notes page mentions pie charts, but codap doesn't do pie charts
- [x] (Page 7) the notes page is almost entirely pyret-specific
- [x] (Page 8 -- now 6) this is all Pyret
- [x] (Page 9 -- now 7) this is all Pyret
- [x] (Page 10) the notes page is almost entirely pyret-specific
- [x] (Page 12) All the example tables here are filled in, in student mode. Is this what you want?
- [x] (Page 13) Can we use a code-formatted or italicized font in the function cards for the stuff after the colons?
- [x] (Page 14) All the example tables here are filled in, in student mode. Is this what you want?

**For Emmanuel**

- [x] Split Table-Methods into a separate lesson, remove offending pages (above)
- [x] (pages 21 - 21) all the stuff in courses/data-science-codap/back-pages is Pyret specific
- [x] (Design Recipe - multiple pages ) headless DRs have the wrong size for transformer name
- [x] (Design Recipe - multiple pages ) white transformer-type checkboxes need to be moved down a few pixels
- [x] (Design Recipe - multiple pages ) rubies are not placed correctly
- [x] (Design Recipe - multiple pages ) headless DRs have mis-positioned transformer-type checkboxes
- [x] (Page 18) table rows are weirdly tall

**For Dorai**

- [x] headless CODAP DRs do not have `codap` as a body classname (there are several glitches that all hinge on this)

**Comment by retabak** [comment]
@schanzer 

I've addressed all of these concerns, except for p. 8 and p.9.  These two Pyret worksheets go with the "Table Methods" lessons, and they are on "Reading Row and Function Definitions" and "Exploring Row and Function Definitions"  - topics which are not at all relevant to the CODAPified lesson.

In their place, I could maybe include a worksheet on writing appropriate formula expressions? (This was a suggestion by @flannery-denny, who observed that in the Table Methods lesson, "there are a lot of directions in this lesson for students to type very specific things into the formula expression box. I would suggest making some more @opt-printable exercises to support classrooms in being less teacher dependent.") I can brainstorm something in a google doc and you can let me know what you think?

Or....

I could change the pyret / codap lessons into their OWN lessons (removing @ifproglang) which would allow us to remove these two worksheets from the CODAP workbook.

**Comment by schanzer** [comment]
@retabak I like flannery's suggestion a LOT. But since these aren't optional pages, I wouldn't use opt-printable.
