### ISSUE TITLE
Bring back Pokemon dataset

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#722]
This dataset has proven insanely popular, to the extent that multiple teachers have asked where it went. And now a student has updated the spreadsheet to include the latest generation!

I think this is enough evidence to suggest that we should bring it back. I've already moved the new data into our existing spreadsheet (in a new tab, marked 2022). 

@flannery-denny any objection to me pushing this all the way through to our website?

**Comment by flannery-denny** [comment]
We cut it because I couldn’t gather any insights from the data after building nearly every display imaginable, but if they love it, they love it.

please make sure to add the fragment describing it.

Flannery
