### ISSUE TITLE
Who are Programmers Upgrades

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#728]
(https://github.com/bootstrapworld/curriculum/issues/629#issuecomment-978021718)

**Comment by flannery-denny** [comment]
[LA Times Perspective: A solution to tech’s lingering diversity problem? Try thinking about ketchup](https://www.latimes.com/business/technology/la-diversity-right-thing-snap-story.html)

**Comment by flannery-denny** [comment]
@schanzer ready for feedback

**Comment by schanzer** [comment]
- [ ] "The People behind the Programs we use" can we fix capitalization?
- [ ] The `@duration{}` directive is meant for 2nd-level headings, not 3rd level. Right now each subsection has its own duration, which is overly prescriptive.
- [ ] Can we include some suggestions for how the crowdsourcing happens, to give teachers ideas? We could recommend "have students share aloud",  "pair-and-share", "pass out sticky notes and then have students read each others' notes on the wall"...
- [ ] "Have students complete this Ketchup use google form. Be sure to copy the form before sharing it, so that you can look at your data as a class!" <-- I would suggest telling teachers to make a copy _first_, before providing a link and telling them to share it with the class.
- [ ] Also, that link forces teachers to manually re-create the form, instead of copying. Instead, provide the link to *original, editable form*, but replace `edit` with `copy` in the URL. Here's the link you want: `https://docs.google.com/forms/d/16tCvWZmTvHrztrVvQeInusQovwoK61WLsg3OTV0VIwg/copy`

**Comment by flannery-denny** [comment]
@schanzer next time it would be more helpful to tell me what capitalization you want. I just capitalized the P in Programs yesterday and it's not obvious to me what makes the most sense here. I've changed it to "The People Behind the Programs We Use"

Also, thanks for sharing the secret of how to make a google form copiable! Learning that was on our meeting agenda for today.

**Comment by schanzer** [comment]
Your edits look good! Closing.
