### ISSUE TITLE
PDF pages getting truncated 

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#73]
Design Recipes that are long (like conditionals) are getting truncated on my local builds.  Dorai speculates it might be a Mac-specific issue - @schanzer can you look at your local copy?

This is what is happening with mine (the rest of the DR is lost)

<img width="470" alt="Screen Shot 2019-10-04 at 2 17 57 PM" src="https://user-images.githubusercontent.com/43153234/66233957-1d339e00-e6b2-11e9-875c-33d5899fabbc.png">

**Comment by schanzer** [comment]
That's weird - I don't see any of the `ask` scaffolding when I build. Are you on a different branch? I _am_ seeing some more examples of pages being shrunk.

**Comment by ds26gte** [comment]
This page doesn't look truncated to me on bootstrapworld.org/preview/curriculum or on bootstrapworld.github.io/curriculum. I've done some linebreak economizing just in case.

But it is possible _local_ builds on macOS uses larger default fonts and hence truncates. (Both bootstrapworld.org and github.io use Linux.)

In general, each workbook page [sic] must be written to fit a single page.  If not, I could try to compress it or, in the worst case, the page must be physically split into two at the authoring end.
