### ISSUE TITLE
Turkish flag

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#730]
Add @opt-printable-exercises to flags lesson

**Comment by schanzer** [comment]
@flannery-denny I've created starter files to implement this - if they look good to you, feel free to close.

**Comment by flannery-denny** [comment]
@schanzer I am curious about your choice to be so proscriptive with this Turkish Flag starter file.  I would have envisioned this as a stretch for students who don't want their hands held quite so much, ending around line 11 of your starter file.

**Comment by schanzer** [comment]
@flannery-denny For those students, none of the provided code is interesting - nor should it be! Those kids know how to make a red rectangle, and put a white, rotated star on it. 

The _only_ interesting part of this is "how can I make a crescent?" Everything else is boilerplate, which is why I'm giving away most of it and asking them to tweak the code instead of write it whole-cloth. 

You said you're ok with line 11, so I'm guessing you're fine with the suggestion that a crescent can be made from two shapes. Does line 26 feel overly prescriptive to you? I can't think of many other ways to place one shape on top of another, so I didn't think this was giving away too much - but I can be persuaded! Maybe I should just take out everything from line 26 onwards?

**Comment by flannery-denny** [comment]
@schanzer I'm excited about what we did with this today! once you weschemify and add it to `shared/langs/en-us/starter-files.rkt`, this issue is ready to close.
