### ISSUE TITLE
Equity page on website

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#733]
A single page that describes our approach/handling of equity:

- [x] How does our _strategy_ impact equity (free, mainstream classes, etc)
- [x] How does out _content_ impact equity (SJ practices alignment, antiracist content and pedagogy, etc)

**Comment by schanzer** [comment]
@flannery-denny this file shows up inside `distribution/langes/en-us/equity.shtml`.

**Comment by flannery-denny** [comment]
@schanzer I think this is a great start with lots of good ideas! It would be more compelling if more attention were given to ordering those ideas. In several sections the most compelling point doesn't come until the end. Happy to take a pass at editing the asciidoc if you want. Or wait until the rest of the team weighs in. lmk what works best for you.

**Comment by flannery-denny** [comment]
@schanzer More broadly, I'd suggest making scaling the first section and only using its last paragraph. That would make the opener of the curriculum section make more sense.

**Comment by flannery-denny** [comment]
@schanzer it reads much better with that change... and I have many more thoughts ;) Would definitely edit the language in the curriculum design & pedagogy sections and would probably break engineering into multiple sections.

when you're ready for more detailed feedback, lmk how you want it.

**Comment by flannery-denny** [comment]
I didn’t realize there was a Google doc. Will have a look for it this afternoon.

Flannery

**Comment by flannery-denny** [comment]
@schanzer Not seeing a google doc in the team folder. Are you asking me to make one?

**Comment by schanzer** [comment]
Check your email - I sent it last week, and again a few hours ago.

**Comment by schanzer** [comment]
@flannery-denny I've updated the stats on the equity page, which should address the last comment in that [google doc](https://docs.google.com/document/d/18QanxGg3klurV_J9fXiVROM6Ct4cwzDWbxlP1UvWm7M/edit#) (Shriram seems to have closed it already!).

If you are comfortable with the finished product, the public URL is https://bootstrapworld.org/materials/latest/en-us/equity.shtml . Adding to social media Feb calendar....
