### ISSUE TITLE
Add pointed questions to some of the "synthesize" sections in DS.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#739]
From Assessing Bias:
3.1 Promote or provoke students asking critical questions about societal status quo (Freire, 1970; Duncan-Andrade, 2007).

- [x] displaying categorical data (bar charts empty bar vs. pie charts no label without a pie slice)
- [x] grouped samples (why might it be important to look at a subset of a population - why is it sometimes bad to only take random samples)
- [x] randoms samples (why is it important to take a random sample for addressing issues of bias or status quo?)
- [x] #771
- [x] #778
- [x] #772
- [x] #787
- [x] #786

- [x] *Made a separate issue for this for @schanzer*:
custom scatter plots (by treating all samples with the same dot how can we hide things - how can we expose bias by doing this? simpson's paradox - scatterplot showing jail time for dollar value of goods stolen. if you highlight dots that are people of color steep line vs. not)
(see #763 )

**Comment by flannery-denny** [comment]
- displaying categorical data (bar charts empty bar vs. pie charts no label without a pie slice)
- custom scatter plots (by treating all samples with the same dot how can we hide things - how can we expose bias by doing this? simpson's paradox - scatterplot showing jail time for dollar value of goods stolen. if you highlight dots that are people of color steep line vs. not)
- grouped samples (why might it be important to look at a subset of a population - why is it sometimes bad to only take random samples)
- randoms samples (why is it important to take a random sample for addressing issues of bias or status quo?)
- measures of spread / visualizing shape (extreme values / outliers - here's a histogram with an extreme outlier (the one blind person who goes to the football game - stadium is tracking how long it takes people to get to their seats - should the outlier be removed or is it the most important data point in the whole dataset - what to do with outliers is not cut and dry - the dot is a civil rights violation. same words with a box plot
- correlations / linear regression / threats to validity / ethics and privacy - make checklists and assign some to Emmanuel.

**Comment by flannery-denny** [comment]
@schanzer In our conversation, you mentioned Simpson's Paradox. When I do a find in files, I see zero references to Simpson's paradox in our materials. Seems worth adding! Would you agree? Perhaps in connection to the importance of familiarity with a topic as they choose their dataset?

**Comment by flannery-denny** [comment]
**Linear Regressions**
@schanzer I've made this [starter file](https://code.pyret.org/editor#share=1prqCzfZWJ-kuXJMclmi1qyE0cSdziLiV&v=1904b2c) for digging deeper into appropriate use of linear regressions.

My original intent was to use it to generate screenshots for workbook pages. Now that I have it, I wonder whether we want to engage students with it (I would clean it up more if so.)

Questions I think we could get at it from one single image:

Based on the linear regression, 
- about how many inches are kids in this dataset expected to grow per year?
- how tall would you expect a seven-year-old child to be? 
- how many of the seven-year-olds are actually that height?
- if a child were 45" tall at age eight, how tall would you expect them to be at age 12?
- if a ten-year-old were 55" tall at age 11, how tall would you expect them to have been at age 9?
- how tall would you expect a 13-year-old to be?
- how tall would you expect a 6-year-old to be?
- how tall would you expect a baby to be at birth?
- how tall would you expect a 90-year-old to be?
- which of these questions does it make the most sense to determine using the linear regression?
- which of these questions does it make the least sense to determine using the linear regression?

We could also then split the dataset by sex (I might change the column title to gender identity if we do that) and have them see how the regression on boys differs from the regression on girls? And before we actually filter the table we could have them look at the image scatter plot I've included in the starter file.  This could (of course) be done without giving them access to the starter file. Curious to hear your thoughts.

**Comment by schanzer** [comment]
@flannery-denny very interesting! Some thoughts:

- For readability's sake, I'd change the code to use the square function for boys instead of the text function. The current difference will draw attention where it's not needed, and I think this will be a big distraction for weaker students.
- Your list of questions is absolutely perfect. YES! Make sure you call out to the teacher that this list reinforces connections to algebra as well.
- It would be very worth tweaking the numbers so that the correlations for both boys and girls is high, but the correlation for the whole population is low.

**Comment by schanzer** [comment]
@flannery-denny separately, can you edit the original issue text to remind me which lessons you want me to tackle? I don't recall, and I don't want to step on your toes!

**Comment by flannery-denny** [comment]
@schanzer in thinking about the ethics and privacy questions I've been reading the case studies. The one from propublica on racial bias in sentencing had a link to [the data they used on github](https://github.com/propublica/compas-analysis). I haven't had a chance to dig in yet, but these graphs/stats from the article make me think that we should be using this dataset for something, may even be a good real example of simpson's paradox.
![Screen Shot 2022-02-21 at 12 57 42 PM](https://user-images.githubusercontent.com/66691020/155007366-17af51f6-d232-45f7-bce3-9643c8dfe590.png)
![Screen Shot 2022-02-21 at 1 00 42 PM](https://user-images.githubusercontent.com/66691020/155007373-df73c66b-46ba-4fef-89ae-e9b7a1bdd95e.png)

**Comment by flannery-denny** [comment]
@schanzer I think we need a case study that is not part of the jigsaw in order to add the requested debate to ethics and privacy.

- Do you have ideas of another issue that would be worth including?
- If not, think we should convert the target article or the facebook article for the purpose and have them do the jigsaw with the other two articles? Or should we move away from the jigsaw structure and make scaffolds for all three case studies that could be used in multiple ways? (We could perhaps create framing that doesn't require reading the whole article, but links to the article for further reading?)
