### ISSUE TITLE
Releasing new datasets

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#749]
The plan was to release the new datasets made by undergrads in the next month. They use the new Pyret context. I'm ok with that. @schanzer are you? if not, please move the items in this commit to the fall2022 branch.

**Comment by schanzer** [comment]
I'm OK with it, since there will never be two different versions of the same starter file.

**Comment by flannery-denny** [comment]
So the movie dataset that I recently added the Bechdel column needs to stay in the fall2022 branch?

**Comment by flannery-denny** [comment]
@schanzer So the movie dataset that I recently added the Bechdel test column to needs to stay in the fall2022 branch?

**Comment by flannery-denny** [comment]
I added 5 datasets today. I am expecting to receive 2-3 more this week. Will let you know when they've been added so you can push them to the website.

**Comment by schanzer** [comment]
@flannery-denny didn't you add the bechdel test column to a new copy of the file? Or maybe a new sheet within the same file? If you modified the original file in such a way that a teacher might have two students with different starter files, then the modification should be fall2022.
