### ISSUE TITLE
DRAFT: @project directive

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#751]
Dorai - please ignore this until you hear otherwise!

- [ ] Create `@project{....}` directive, which has the same parameters as `@opt-project{}`
- [ ] In the lesson plans, display the "required project" above any optional projects
- [ ] In the teacher resources page, combine _all_ project directives under a single "Projects" heading, sorted with required projects coming first.
- [ ] The projects we would expect to make use of the `@project` directive **are actually currently their own separate pages in the pathway resources pages folder**. At least in terms of their location, these file are really different from the `@opt-project` files. Furthermore, I would expect that generally `@opt-project` files are only referenced in one lesson and `@project` files are referenced in many lessons.

**Comment by flannery-denny** [comment]
@schanzer Noting that the projects we would expect to make use of the `@project` directive are actually currently their own separate pages in the pathway resources pages folder. At least in terms of their location, these file are really different from the `@opt-project` files. Furthermore, I would expect that generally `@opt-project` files are only referenced in one lesson and `@project` files are referenced in many lessons.
