### ISSUE TITLE
Small regression - alternate proglang options should be shown under the lesson title

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#757]
In the pre-common-lessons era, every lesson that was defined in other languages had a link to the other language at the top, under the title:
![image](https://user-images.githubusercontent.com/77126/151825437-6dc85496-3b5f-4341-be85-e5fd8730e906.png)

Now, that helpful link is gone:
![image](https://user-images.githubusercontent.com/77126/151825513-db91ac95-14ef-4a84-a920-741a0f403a33.png)

We'd like to bring this back.

**Comment by ds26gte** [comment]
Do you remember if a similar cross-link was also shown for the pathway narrative?  If so, do you want it in the new régime too, or just for the lesson plans?

**Comment by schanzer** [comment]
I believe it was. Would be good to have it there as well, but the lessons are definitely the highest priority.

Future-proofing: Now that we've got CODAP added to the mix for certain lessons, I wonder if it makes sense to  make this a dropdown, instead of link-to-the-only-other-language?

**Comment by ds26gte** [comment]
It's never more than two-way.  It's either {wescheme, pyret} for algebra,  or {pyret, codap} for data-science.

**Comment by schanzer** [comment]
Thus the term "future-proofing". ;-) 

It is likely that at least 2-3 lessons in Core will be available for WeScheme, Pyret _and_ CODAP
