### ISSUE TITLE
Stability - where are the shared images used in flags stored?

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#759]
We should make sure they're somewhere sensible on the team Google Drive

**Comment by flannery-denny** [comment]
@schanzer Currently all image files used in flag starter files live in the same folder as the starter file. See this [Mexican Flag folder](https://drive.google.com/drive/folders/1B36lUf7W5k5ZAsYlKtYlYLw-e7K6FkkP?usp=sharing) as an example.

**Comment by schanzer** [comment]
@flannery-denny ah, I see - each semester's folder can have a "flags" subfolder if new flags are defined. Makes sense.
