### ISSUE TITLE
Research Paper Template upgrade

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#761]
### **Revised Proposal 5/3**

- [ ] provide blank and pre-filled example versions of both artifacts, below

**Artifact 1: Exploring**
- Why is this dataset important to you? To your community? Why should someone outside your community care about this dataset?
- Where did the dataset come from? How many rows does it have? What columns does it have, and what types are they?
- Explore the columns of your dataset, making displays and calculating center and spread
- What stands out? What do you notice?
- table asking for column, display-type, code, image, findings, and followup question. Followups go at the _end_ of the document

**Artifact 2: Research Paper**
_Introduction_
- Why is this dataset important to you? To your community? Why should someone outside your community care about this dataset?
- Where did the dataset come from? How many rows does it have? What columns does it have, and what types are they?
- What research question(s) will you examine? 

_Analysis_ - data cycles
- What filters or transformations do you need to do, to answer your question(s)?
- Explore the results, making displays and calculating center and spread for the relevant columns
- What did you find? (Dead ends are still findings, too!)
- Did this lead to more followups? (If so, rinse and repeat the steps of this section)

_Findings_
- What threats to validity should you disclose?
- Are there any ethical implications?
- Summarize your findings

--------------------------------------------------------------------------------------------

**Proposal (4/6)**

_Section 1 - Exploring (motivation, open-ended inquiry, etc)_
- Why is this dataset important to you? To your community? Why should someone outside your community care about this dataset?
- Where did the dataset come from? How many rows does it have? What columns does it have, and what types are they?
- Explore the columns of your dataset, making displays and calculating center and spread
- What stands out? What do you notice?
- What question do you have about the dataset? (this section should be rewritten and revised over time. Maybe start with a list of random questions, which gets narrowed down and formalized?)

_Section 2 - Analyzing (lots of data cycle stories!)_
- What filters or transformations do you need to do, to answer that questions?
- Explore the results, making displays and calculating center and spread for the relevant columns
- What did you find? (Dead ends are still findings, too!)
- Did this lead to more followups? (If so, rinse and repeat the steps of this section)

_Section 3 - Discussing (the non-code, non-stats stuff)_
- What threats to validity should you disclose?
- Are there any ethical implications?
- Summarize your findings

**Comment by flannery-denny** [comment]
@schanzer I'm realizing that we have three open issues related to the research paper and they're all interlocking. I pushed a first pass at #688 (far from done!) and I think we need to understand where this template is headed before I tackle #737 

I think you wanted to take a first pass at this? But, I could also take on drafting a rewrite.

My inclination is that it would be good for us to move this forward before we tackle new lessons, since so many things hinge on it, but if you'd rather we set this (and the connected issues) aside til new stuff is written, I defer to you.

**Comment by schanzer** [comment]
@flannery-denny I've updated the project description in `c370c7cb0`. I don't think we're in a position to finalize the research paper template until we know (1) what the final lessons are, (2) what the order is, and (3) what the page numbers will be.

**Comment by flannery-denny** [comment]
@schanzer I can accept that as the process you'd like to follow... and I think it would also be possible to start fleshing out the template and have whatever framing and questions it surfaces be part of what informs the final lessons  & order.

**Comment by schanzer** [comment]
@flannery-denny I've created [a draft template](https://docs.google.com/document/d/1rSaR8dGEDtZz3NRVsvAjw_W50BiCNrM6zxID5hgkBY8/edit?usp=sharing) based on this proposal. Eager to hear what you think!

**Comment by schanzer** [comment]
@flannery-denny We now have two templates (exploring and the research paper). I've created examples of both:

- [Exploring your dataset](https://docs.google.com/document/d/1eBYMjAxrn0rPp0Mqd52cRjmwyXSz51RfBWe67DR93es/edit#)
- [Research Paper](https://docs.google.com/document/d/1rSaR8dGEDtZz3NRVsvAjw_W50BiCNrM6zxID5hgkBY8/edit#)

Let me know what you think? Once you're good with these I'll create the blank versions, and weave links and references throughout the DS pathway and teacher resources section.

**Comment by flannery-denny** [comment]
@schanzer 
I feel pretty good about exploring your dataset 

I think we still have a ways to go on thinking through what we really want the final research paper to include. I left you some questions. 

I feel very tempted to make a copy of the file and delete out all of the examples so that we can see just the directions... 

(that said... it wasn't til I made another example for the exploration doc that I realized we needed to give them the option to list more than one column...)

**Comment by flannery-denny** [comment]
@schanzer 
I think the research paper looks a lot better... Made some more formatting changes and left you one more comment. Will try to take another look with fresher eyes, but I'd like to think that we've made significant progress. Is there a data science teacher we could ask for feedback?

**Comment by schanzer** [comment]
@flannery-denny Emailed some of our most active teachers today. Will keep you posted.

**Comment by schanzer** [comment]
@flannery-denny they came back with some great suggestions.

From Joy:
_First, I love the idea of making an exploratory page.  I have had the students do this but in the research doc template.  They then go in and modify it, delete graphs that are not really a part of their story, etc.  So I do think a place to make them process all of the analysis questions separate from the final product is a brilliant idea.  I do want them making at least one of every type of graph and then analyzing whether or not that is beneficiary to their data story.
I do think the final paper should have a section for further questions (post analysis) that could be used for continued efforts on their topic - it is good for them to acknowledge that the data cycle continues.  I do not see that specifically mentioned in the final template.  I think it should be one of the last things they share._


From Susan:
_---Where did the dataset come from?
-while this section comes after the why bother section (which I consider good) - I use this and I find it encourages students in the wrong direction. These questions superficially suggest simple correct answers reminiscent of the type of writing that we do not want but this is important to be able to articulate - so how to get this information from the student but in a context...
--maybe some approach like this?
_for instance possibly: datasets are never created for no reason, usually there is an agenda or some point that an organization is trying to prove, such as an anti environmental group trying to prove that plastics do not affect fish - so in this context, where does your dataset come from and why might someone or some people have wanted to gather this data - can you imagine what question they were trying to answer or prove
-the number of rows in a dataset represent the number of respondents or incidents that were recorded - sometimes there may be a lot and sometimes only a few - think about how many were collected in your dataset - why that many? is it "enough" - what makes "enough" - enough?_

From Corri-Anne:
_To piggyback with Susan’s comments about getting students to think about why this dataset was created or who would or could be the target audience for this data? Audience is so important when it comes to research. I am constantly asking students “who would be interested in this research and why?” The answer “everyone” is not good enough. This also brings up the topic of bias as well. If you are beginning research with a specific goal in mind or for a specific audience won’t that skew your views on the data? But, isn’t that what typically happens anyway? It’s always a good class discussion. Maybe a question concerning bias might be appropriate here? Just to get students thinking about it? Not sure?_

**Comment by flannery-denny** [comment]
Awesome! Thanks for reaching out to them!

Flannery
