### ISSUE TITLE
Deployment script should not overwrite dependency-graph

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#764]
The deployment script has a nice feature: we can do _partial_ deployments, which only overwrite files that have changed. This is super handy when we need to push a fix to just one lesson or pathway, and build/deploy speed matters.

The feature, however, comes at a cost in our new common-lessons era: when only one pathway is built, the resulting dependency graph file is incomplete...and overwrites the full one on the server. This causes the build-your-own-pathway system to break, _hard._

We need to either: (1) remove the partial deployment feature (literally do not deploy unless every lesson has been built), (2) take care not to overwrite the existing dependency graph file, or (3) find a way to generate the entire dependency graph every time we build.

**Comment by ds26gte** [comment]
Please check fix proposed in 4f2f08fdc

**Comment by schanzer** [comment]
Confirmed fixed!
