### ISSUE TITLE
add link to article reading strategies to the lessons with articles

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#765]
make a breakout box in these lesson

**Comment by retabak** [comment]
How about [this](https://www.edutopia.org/blog/alternatives-to-round-robin-reading-todd-finley)?

Or if we wanna go more academic, maybe [this](https://www.researchgate.net/profile/Diane-Lapp/publication/321336458_If_You_Want_Students_to_Read_Widely_and_Well-Eliminate_Round-Robin_Reading/links/5a1d92a3aca2726120b307dc/If-You-Want-Students-to-Read-Widely-and-Well-Eliminate-Round-Robin-Reading.pdf)?

I prefer the Edutopia resource for accessiblity. 

@schanzer @flannery-denny let me know if you like one or neither of these.

**Comment by flannery-denny** [comment]
Thanks for looking into these @retabak. Honestly, I'm not into pointing teachers to either one of them.

The edutopia piece opens with a long bunch of negative before offering strategies. 

The longer one feels less negative... and makes me really feel like I've learned something about research-driven best practices, but most of the strategies are above and beyond what we can expect a math teacher to make use of: echo reading? readers theater? of articles on AI?

I am tempted to say let's not offer any strategies, but if you think some of these would have been helpful to you in the classroom I wonder whether @schanzer would support a pedagogy box offering the following two strategies (or any others that you want to highlight) giving credit as being excerpted from xyz.

> If you want students to actually comprehend the text, try [reciprocal teaching](https://www.readingrockets.org/strategies/reciprocal_teaching), a small group strategy in which students read small chunks of the text then take turns with the jobs of summarizing, questioning, clarifying, and predicting. Independent silent reading, with appropriate scaffolding like [anticipation guides](https://www.adlit.org/in-the-classroom/strategies/anticipation-guides) and [guided notes](https://www.theteachertoolkit.com/index.php/tool/guided-notes), works toward the ultimate goal of having students become independent readers.
> Finally, teacher read-aloud offers all kinds of benefits: Students hear the text read correctly and smoothly, so they can build an understanding of the text without constant interruption. This also models for them what proficient reading aloud sounds like, so they are only getting good examples, rather than being forced to listen to hours of less-skilled reading.

**Comment by retabak** [comment]
@flannery-denny - I agree with your reaction. I also why wondered why these articles had to go on and on about how popcorn reading is THE WORST before getting to the good stuff / research-based strategies, which is what I think teachers care about.

Your comment has me thinking perhaps we should abandon this proposal all together? I don't think our strategy boxes are a place to make digs at how people choose to support their kids in reading articles in math class, whether it's popcorn reading or not. 

If I had been able to find an article with easy-to-implement reading strategies for math class that are research-based, then I'd be sad to abandon this idea. But given that I didn't find that, I'm okay letting this go.... unless @schanzer wants to go with your idea of excerpting a strategy or two.

**Comment by schanzer** [comment]
My preference is to let this whole thing go, but @flannery-denny I know you felt strongly about this. If you'd like to add a pedagogy box I say go for it, and then close the issue.

**Comment by retabak** [comment]
I was the one who felt strongly! I don't think @flannery-denny did. I'm gonna close it. 

@flannery-denny , if you object, re-open!
