### ISSUE TITLE
Links in the materials section should appear in the same order that they appear in the lesson unless they are tagged as optional or project

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#768]
When I visit a lesson on the website through the Algebra Pathway, printable exercises appear with workbook page numbers in the same order in which they appear in the lesson (with projects and optional items coming at the end). This is how it should work.

When I build a page outside of the pathway the exercises are being shown in alphabetical order rather than the order in which they are used.

Previous directions re: what order optional and project directives appear should remain, but please fix the order links appear in within each category.

**Comment by flannery-denny** [comment]
@schanzer check out linear regression lesson local copy. "Which question makes sense to ask" belongs after "Drawing Predictors"

**Comment by schanzer** [comment]
@flannery-denny when adding a new workbook page to a lesson, you need to make sure to _also_ add that page to the `pages/workbook-pages.txt` file. That file is used for (among other things) computing the page number.

@ds26gte shouldn't we have gotten a build error if `@printable-exercise{xyz}` refers to a page that isn't in `workbook-pages.txt`?

**Comment by flannery-denny** [comment]
@schanzer Thanks for figuring that out. @ds26gte we definitely used to get that error.

**Comment by schanzer** [comment]
@ds26gte this just bit us again: in fall2022, We changed the lesson `image-scatter-plots` to `custom-scatter-plots`. The same change happened to the name of a WB page, but the `workbook-pages.txt` file wasn't updated. No error was generated, which means this could easily have slipped through to production!

**Comment by ds26gte** [comment]
Please check fix in 86b8b725b

**Comment by schanzer** [comment]
Confirmed fixed!
