### ISSUE TITLE
Update teacher resources form

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#769]
- [x] students in your classes (not school)
- [x] specify latinx/black

ORIGINAL: https://docs.google.com/forms/d/1nRb8G1SHfhQiX4_rjllJtdi4WgZbO5fCv3eR17flE2I/edit
UPDATED: https://docs.google.com/forms/d/1Z-kPMxElQ6l32qo8hXcsijGuAgjrs5TsG3hIXg4HbRA/edit

**Comment by schanzer** [comment]
@flannery-denny I've shared the updated form with you. Let me know what you think?

**Comment by flannery-denny** [comment]
4 suggestions:

- make preferred email optional 
- list training years beginning with never then in descending order from 2022.
- I wonder if we should include Native American on the list with AfrAm/Lat?
- add a question about gender non-binary students after girls/boys.

Flannery

**Comment by flannery-denny** [comment]
Also I’d suggest adding a checkbox question about what grades people teach.

And I’d turn the what kind of classes question into a checkbox question so that people can check more than one option.

Flannery

**Comment by schanzer** [comment]
@flannery-denny I've made most of these changes. A few responses:
* We absolutely need to know what teachers' preferred email is, so that can't be optional. But we CAN make the school email address options, which I did.
* The "what kind of classes" questions needs to have a single answer, so I changed the wording to focus on _primary_ subject.

**Comment by flannery-denny** [comment]
Feels shorter, which is good. We have resources for teaching ELLs but we’re not collecting data on them. For some reason I can’t edit to fix typos today.

Flannery

**Comment by schanzer** [comment]
@flannery-denny good call -- added a question for that. If this looks ready to go, I'll share with Shriram and Kathi for the next round of feedback.

**Comment by flannery-denny** [comment]
Sure

Flannery
