### ISSUE TITLE
extreme values / outliers debate - make a dataset

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#771]
For measures of spread / visualizing shape:

Spec 

> here's a histogram with an extreme outlier (the one blind person who goes to the football game - stadium is tracking how long it takes people to get to their seats - should the outlier be removed or is it the most important data point in the whole dataset - what to do with outliers is not cut and dry - the dot is a civil rights violation. same words with a box plot  - make a dataset

I'm passing it off to you, because I would definitely go looking for a dataset if we want to focus on a civil rights violation rather than making a dataset and I imagine something awesome would come out of that but it sounds like more time / thinking than you want me to devote to this.

**Comment by schanzer** [comment]
@flannery-denny I added content to set this up. If you feel good about the direction it's going, I can add an optional debate page.

**Comment by flannery-denny** [comment]
@schanzer proposed some wording changes. Also wondering if we ought to add some thoughts for teachers using `@ifsoln`

**Comment by schanzer** [comment]
@flannery-denny good call. See latest revision.
