### ISSUE TITLE
linear regression - synthesize questions

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#772]
> Just because you can draw a line, is it a story worth telling? A linear regression was performed on a dataset comparing students' ages to height. One person grew by a lot more, how is this possible? Can we use the same linear regression to forecast the height of an 80 year old? Why or why not?

- [x] I've pushed a page that engages with the lr-plot. It built beautifully until I add the solutions & now it's broken. I don't understand the warning it's giving. I'm hopeful you will. 
- [x] please confirm that wording (including for solutions) makes sense.
- [x] I thought about adding one more question that gets at what about the way the data was collected my limit the effectiveness of the correlation (all ages are given as a whole year, so someone who's seven and a half is counted as 7). Instead I included in a note in the solution to the second to last question. Feel free to make it more explicit if you want. I was struggling with how to word the question. 
- [x] I do not understand why this lesson plan links to "What's on your mind"/lists that page in the materials section. If we want them to write they're thinking down somewhere specific, we should make a page with the question on it. Otherwise, let's just ask them to write it down and not link to lined paper... agreed?
- [x] Is there a good reason to have all of these questions without a page for students to write them down on?
![Screen Shot 2022-02-10 at 1 44 27 PM](https://user-images.githubusercontent.com/66691020/153485483-cf94ba99-f199-4b5a-bc33-792fae91c5dd.png)
- [x] This lesson feels long. Not sure about whether to offer the extension with filtering the lr-plots in this lesson or put it in a different lesson.
- [x] feedback on scaffolding for new starter file & starter file format.
- [x] Row heights in theses tables are inconsistent and I don't think the first one has enough room for students to write in. Not sure how to fix. 

![Screen Shot 2022-02-15 at 7 12 21 PM](https://user-images.githubusercontent.com/66691020/154171560-be61aa4d-f085-48b5-ac26-7390c62ada11.png)
 
- [x] Also, I'm not sold on the formatting for the last one. Wondering if it might support students better to include this screenshot instead and put the text beside it? Not sure how to do that in asciidoc unless I use a table and put the image in the left column and the directions and text in the right. Is that the best option?

![Screen Shot 2022-02-15 at 7 15 14 PM](https://user-images.githubusercontent.com/66691020/154172037-21f39ad2-a33b-419d-b166-355e68e4358c.png)

**Comment by flannery-denny** [comment]
@schanzer see checklist above

**Comment by schanzer** [comment]
@flannery-denny 

* `@ifshowsoln{...}` is shorthand for `@ifsoln{@show{....}}`. It means "whatever is between these braces is _racket code"_. So Racket was trying to find the variable `_3 inches_` and throwing an error. You wanted to just use @ifsoln{..}
* I made some small wording changes. Happy to discuss if you're not happy with them
* I like the idea of putting it in the solution, actually! I changed to a different example that I think reads more clearly, but I'm not attached to it at all.
* Agreed. I removed "what's on your mind".
* I think those are worthwhile questions to keep, even without a scaffold. There are questions we'd like to see our teachers ask sometimes, but for which we don't need our students to write answers.
* Let's put it in this lesson for now. I suspect we'll be grouping and splitting up lessons a little later when the dust settles anyway.

**Comment by flannery-denny** [comment]
@schanzer Please check out this commit [https://github.com/bootstrapworld/curriculum/commit/982a66f6c51f13d209022e3e45a5ceccd2ec9bc7](https://github.com/bootstrapworld/curriculum/commit/982a66f6c51f13d209022e3e45a5ceccd2ec9bc7) when you have time.

**Comment by flannery-denny** [comment]
@schanzer Please check out the last commit when you have time and the new tasks that I've added to the questions in the top box.

**Comment by flannery-denny** [comment]
@schanzer Please check out the last commit when you have time and the new tasks/questions that I've added as checkboxes in the issue description

**Comment by schanzer** [comment]
@flannery-denny I've adjusted the CSS selectors to apply the rule to ALL tables, not just those with a particular class.

As for scatter plot settings - I _really_ want to avoid using images, whenever possible. They're a maintenance nightmare, they don't generalize, etc. If you don't like the table, perhaps we could just do it as normal text? The chart window is pretty easy to read, and having students look for "x-min" seems like a pretty light lift. And once they find it, all the other settings are that much easier to modify.
