### ISSUE TITLE
vertical spacing changes to consider

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#775]
Flagging that styling has changed somehow such that there is no vertical grace between the span lines and the text that follows them. Same for tables. In the linear regression age-v-height page I added vspace to deal with some of this and accepted the crowdedness of other spots. At some point we had added a bit of buffering between hard objects like lines and tables and the text that follows. I don't know where it went or what other pages it may have impacted. And I'm not sure whether it's better to put it back in or to deal with spacing on a page by page basis.

**Comment by schanzer** [comment]
@flannery-denny can you point me to some offending examples where I can see this?

**Comment by schanzer** [comment]
@flannery-denny There's been no change to the spacing between `.blanklines` and the line below them, but I agree that it would be convenient to add it! I've pushed this change in 1a42221, but you may want to flip through the Reactive and DS lesson PDFs to make sure that didn't throw off the spacing. 

There were _other_ places where a vspace follows a blankline, so I removed or shortened them.

While I was at it, I also noticed that there's a rarely-used `.vskip` property that basically does the same thing as `@vspace`, so I replaced one with the other and removed the property from CSS.
