### ISSUE TITLE
correlations lesson reorganization

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#778]
I am suggesting a reorganization of this lesson because it reads as if it's been written in phases and lots of cool stuff presents as an afterthought. The subsections of this lesson also feel very long and lectury. lmk if you support me tackling this.
- [x]  break it into smaller sections (form, direction, strength, r-value, analysis) each of which gets a proper launch that includes images.
- [x] make the guess the correlation game the launch of a new r-value section
- [x] Turn the 3 examples of correlations in the lesson plan with reasons why they aren't causal relationships into a brainstorming worksheet with a fake news headline for each of the factual correlations where students try to brainstorm why the headline doesn't make sense (ultimately revealing the stuff currently written into the lesson plan). 
- Ideally generate one more page of examples just like this one - **We decided it wasn't a priority for now**
- [x] Honestly, the more I look at the spurious correlations site, the less interesting I think it is. I suggest taking the list of examples from spurious correlations out of the lesson and either just leaving it in additional resources or making an optional activity where we ask students to find a spurious correlation that's of interest to them, write a fake news headline for it, and then describe why the headline makes no sense.

**Comment by schanzer** [comment]
@flannery-denny I'm cool with ALL of this -- but not removing spurious correlations from the lesson. I'm not sure how the WB page you propose (headline + debunk) address our learning goals, but I also may not be fully understanding your proposal. How about we hop on the phone to discuss, once the other items are addressed?

**Comment by flannery-denny** [comment]
@schanzer I propose turning these questions into a worksheet so students have time to reflect on them before a class discussion. Thoughts?

> What is the difference between a weak relationship and a negative relationship?

> What is the difference between a strong relationship and a positive relationship?
> 
> If we find a strong relationship in a sample, can we always infer that relationship holds for the whole population?
> 
> Suppose we have two correlations, one drawn from 10 data points and one drawn from 50. If both correlations are identical in direction and strength, should we trust them equally when making an inference about the larger population?

**Comment by flannery-denny** [comment]
@schanzer I pushed an updated version of the lesson, which takes a lot of things that were in the lesson and makes them into pages for students. If it works for you, I'll clean up the solutions and check it off. Open to whatever other thoughts you may have.

**Comment by schanzer** [comment]
This looks great! I made some small tweaks, but otherwise I'm ready to sign off. Clean up and close at your discretion!

**Comment by flannery-denny** [comment]
@schanzer do we want to remove the predictor functions from these images[https://bootstrapworld.org/materials/latest/en-us/lessons/correlations/pages/identifying-form-open-ended.html](https://bootstrapworld.org/materials/latest/en-us/lessons/correlations/pages/identifying-form-open-ended.html)?

**Comment by schanzer** [comment]
@flannery-denny really nice! I love the rewrite. I made a few small changes, but mostly I think this is ready to go as-is.

One note about `@printable-exercise`: it's designed to work exclusively with pages that belong to the lesson itself. If you're linking to a page in a different lesson (as with "disproving a claim"), you need to use `@link`.

**Comment by flannery-denny** [comment]
Thanks @schanzer. If you scroll up, you'll see that I left you two comments with questions 4 days ago and you haven't replied to them yet. Please lmk your thoughts regarding them so that I can resolve them and close the issue. Thanks.

**Comment by schanzer** [comment]
@flannery-denny thanks for the poke! 

- I think removing the link makes sense. Done.
- Removing the predictor function makes this worksheet harder, but not in a way that puts more focus on the learning goals. Let's discuss if you feel strongly about it.
