### ISSUE TITLE
Spec what we want Dorai to autogenerate for the Preparation Section

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#780]
Do we want all lessons to say these four things? Or can some of this text be cut?

- [ ] Make sure all materials have been gathered. **FD votes definitely remove - I want us to be more specific when there is something worth gathering**
- [ ] Decide how students will be grouped in pairs. **FD votes remove, although I feel less strongly about it**
- [ ] Computer for each student (or pair), with access to the internet **FD - I'm ok with this, although it seems like wasted breath since we're teaching coding and it feels obvious, and I'm cognizant of the fact that we have a handful of lessons that do not require computer access.**
- [ ] Students should have [Student workbook](https://github.com/bootstrapworld/curriculum/issues/workbook/workbook.pdf) and something to write with.

Some of our lessons also say something like this:

> All students should log into [code.pyret.org (CPO)](https://code.pyret.org/) and open the "[Animals Starter File](https://code.pyret.org/editor#share=1pc0CiS0YsL_62yLARUAYNkGBIZvhm2gi&v=1904b2c)" they saved from the prior lesson. If they don’t have the file, they can open a new one Animals Starter File.

I am ok with authors adding this by hand. 
And I am ok with deciding we never want to put this information here and only want to give those directions in the lesson plan.

We definitely want authors to be able to include directions like those below, when applicable:

> If a gallery walk works for your students, print a set of Pioneers in Computing and Mathematics Posters. If this isn’t feasible for your class, figure out what structure you will use to engage students with [these pioneers](https://bootstrapworld.org/materials/latest/en-us/lessons/who-are-programmers/pages/computing-pioneers.html).

> Choose a gentle timer sound on your phone, to facilitate transitions while students are sharing personal experiences.
> 
> Make a copy of the google form so that you can examine your class’s data. If you are using the slide deck, be sure to add the link to your copy of the form to the appropriate slide.

**Comment by schanzer** [comment]
@flannery-denny I agree with the first two removals, and leaving the rest to be added by hand.
