### ISSUE TITLE
Videogame Project Description

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#782]
@schanzer I drafted this video game description a while back as something for us to react to. We _certainly_ wouldn't want to publish this description as is. 

- [ ] Which parts to do you like? 
- [ ] Which do you think we don't need? 
- [ ] What's missing?

I'd love to sort this one out to a place that we like it before I start wrestling with the data science project description.

**Comment by schanzer** [comment]
@flannery-denny I started writing a lot of notes in response to your questions above, and then realized it might be faster for me to just implement my suggestions. Let me know what you think about the recent commit?

**Comment by flannery-denny** [comment]
@schanzer looks great! made a few small wording changes and am closing.
