### ISSUE TITLE
New @preparation directive

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#783]
The `@preparation` directive will be used in the preparation section of the lesson plan to auto include these two bullet points:

> - Students should have [Student workbook](https://github.com/bootstrapworld/curriculum/issues/workbook/workbook.pdf) and something to write with.
> - Computer for each student (or pair), with access to the internet 

Authors will be able to add other lesson-dependent bullet points to the preparation section on a lesson by lesson basis. And could also opt not to include `@preparation` when these bullets are not required for a particular lesson.

@ds26gte In any lesson plan whose preparation section currently reads exactly as follows, the whole thing can be replaced by `@preparation`

> - Make sure all materials have been gathered. 
> - Decide how students will be grouped in pairs. 
> - Computer for each student (or pair), with access to the internet 
> - Students should have [Student workbook](https://github.com/bootstrapworld/curriculum/issues/workbook/workbook.pdf) and something to write with.

**Please do not delete any alternate text from preparation sections** in any lesson plan as it has been thought about carefully and would require significant work to reconstruct. Thanks!

**Comment by flannery-denny** [comment]
@ds26gte I've added `@preparation` to all lesson plans that should use it, eliminated text that should be cut and left any additional bullets that are lesson specific. Currently it isn't working. Perhaps it hasn't been merged into fall2022 yet? Please work your magic so that these lesson plans can make use of your work. Thanks!

**Comment by flannery-denny** [comment]
@ds26gte also noting that in your commit you described it as `@Preparation` rather than `@preparation`. Neither work on fall2022. All other directives are lower case, so I used lower case.

**Comment by flannery-denny** [comment]
Looks like it's working... except... that when I build the sample pathway I don't get any words about the student workbook, even when i use `-f --book`

![Screen Shot 2022-02-24 at 1 43 00 PM](https://user-images.githubusercontent.com/66691020/155587594-8f96a226-f77b-4efc-bfbe-ff6ef8a6ac76.png)
I feel like there must be a better way. @schanzer thoughts re: this?

**Comment by schanzer** [comment]
@flannery-denny just pushed a fix for this. Does this resolve the last part of this issue?
