### ISSUE TITLE
Decide if/how we want to remove all MLR boxes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#785]
Currently we have mlr boxes in:

- [ ] making game images - FD I'm not sure how much this one is adding, but we can't list it in the practices for the lesson if it's not there.
- [ ] function composition - FD could leave or not
- [ ] restating the problem - FD this is a big box! looks like it was important to whoever wrote it. And maybe this isn't the ideal format for this?
- [ ] player animation - FD is ok with leaving this one.
- [ ] contracts - FD Votes we leave this one because it is specific to the lesson and not otherwise incorporated into the lesson plan.

**Comment by flannery-denny** [comment]
@schanzer this is ready for you to weigh in on. LMK if you want me to do something with any of these or close if you make edits yourself or feel free leaving them all alone.

**Comment by schanzer** [comment]
@flannery-denny Thanks! I'm comfortable keeping these, and I shortened the long MLR somewhat.
