### ISSUE TITLE
ethics and privacy - add MLR.3 debate in place of Extension as a part of the lesson.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#786]
- [x] I think we need a case study that is not part of the jigsaw in order to add the requested debate to ethics and privacy.

- Do you have ideas of another issue that would be worth including?
- If not, think we should convert the target article or the facebook article for the purpose and have them do the jigsaw with the other two articles? Or should we move away from the jigsaw structure and make scaffolds for all three case studies that could be used in multiple ways? (We could perhaps create framing that doesn't require reading the whole article, but links to the article for further reading?)

**Comment by flannery-denny** [comment]
@schanzer in thinking about the ethics and privacy questions I've been reading the case studies. The one from propublica on racial bias in sentencing had a link to [the data they used on github](https://github.com/propublica/compas-analysis). I haven't had a chance to dig in yet, but these graphs/stats from the article make me think that we should be using this dataset for something, may even be a good real example of simpson's paradox.
![Screen Shot 2022-02-21 at 12 57 42 PM](https://user-images.githubusercontent.com/66691020/155007366-17af51f6-d232-45f7-bce3-9643c8dfe590.png)
![Screen Shot 2022-02-21 at 1 00 42 PM](https://user-images.githubusercontent.com/66691020/155007373-df73c66b-46ba-4fef-89ae-e9b7a1bdd95e.png)

**Comment by flannery-denny** [comment]
@schanzer I can't move forward on this until you reply or we discuss. Perhaps you have time tomorrow?

**Comment by schanzer** [comment]
@flannery-denny 

1. How about an article on [racist chat bots](https://www.cbsnews.com/news/microsoft-shuts-down-ai-chatbot-after-it-turned-into-racist-nazi/)? Or, perhaps even better, [algorithmic bias for medical care](https://www.statnews.com/2020/06/17/racial-bias-skews-algorithms-widely-used-to-guide-patient-care/)?
2. Don't worry about using the data for now. We have bigger fish to fry.
