### ISSUE TITLE
threats to validity - add mlr3 questions that holler back at the learning goals. 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#787]
Given a particular situation, fight over whether the problem is selection bias or bias in the design. 

I'm struggling to come up with a good debate for this, unless we want the debate to be about a scenario that actually involves both kinds of bias.  For example:

> The school newspaper ran an article stating that chicken was more popular than pork in the East Village.
> 
> - Kendell thinks the design of the study was biased to make people pick chicken, because they asked, "Would you rather eat pork or delicious crispy fried chicken?"
> - Carson thinks the problem is actually selection bias because one of the survey locations was outside of the mosque and Muslims don't eat pork.
> 
> Who's right? How do you know?

Do you think that would be useful?

Alternatively, we could add a workbook page with a set of example scenarios where students have to decide whether each is an example of selection bias or bias in the design.  There are also two other stated types of threats in the lesson. Not sure whether you think identifying them is less conflicted? But this workbook page could include all 4.

Here are the beginnings of my brainstorming around possible scenarios for the worksheet.

Preference: pork or chicken? 
- Ask at the halal stand across from the mosque
- Would you rather eat pork or delicious crispy fried chicken?

Would you rather wear cotton or wool?
- ask on a humid summer day
- scratchy wool or soft cotton

Favorite after school activity 
- jump rope or talking on the phone?
- only asked kids who live in urban spaces?

Best restaurant in town
- survey people coming out of the health food store?
- World's best pizza or Sal's pizza?

Favorite fish: Survey in Louisiana impacts menu decisions in Alaska

**Poor choice of summary data**
- Average income in NYC, home to over 100 billionaires, more billionaires than almost any country in the world!

**Confounding variables**

**Comment by flannery-denny** [comment]
@schanzer curious to hear your thoughts on this.

**Comment by schanzer** [comment]
Ooooh - that's an excellent example. I'm comfortable closing unless there's more work you want to do?
