### ISSUE TITLE
font-weight ignored by wkhtmltopdf 0.12

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#79]
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3151

Ugh. We should dig through versions 0.13+ and see if we can find one that doesn't have OTHER problems.

**Comment by ds26gte** [comment]
Does anyone (@kfisler ?) remember the particular reason we were using a non-current version of `wkhtmltopdf` in the old `curr`?

**Comment by ds26gte** [comment]
Version 0.12.4 seems to be the problematic version. On Linux, version 0.12.5 -- which is also the last stable release -- works fine wrt `font-weight` changes.

In any case, our repo doesn't seem to rely on `font-weight` changes on Google web fonts. The deployed version does use `styles.css` which loads a Google web font `Lato`, but even so,

1. The PDF conversion happens before deployment.
2. The font used by `styles.css` doesn't seem to undergo `font-weight` changes. 

But the problem as stated does not occur in wkhtmltopdf version 0.12.5.  If you're on macOS and using version 0.12.4, updating to 0.12.5 (images are available on the wkhtmltopdf site) should remove any risk.

**Comment by schanzer** [comment]
Closing, since Dorai has found the root of the issue
