### ISSUE TITLE
New Collaboration Lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#790]
Split out DR telephone into its own lesson, along with other plugged and unplugged activities that require students to work in sequence, leaving breadcrumbs for their peers to follow

From Assessing Bias for inclusion in collaboration thinking
1.2. Support students utilizing collaborative pro- cesses with diverse people in knowledge con- struction to produce new understanding or knowledge that would exceed something that anyone alone could not achieve (Oksanen, 2017).
Our Reflection on this
We use teamwork and notice/wonder throughout our materials. This touches upon the notion of "new understanding that would exceed something that anyone alone could not achieve", but we can do a LOT more here.
Think about when and why we're suggesting collaboration. We offer strategies for collaborations. We have no control over diversity of groups. Not sure how often the collaborative experience exceeds what someone could do on their own.

- [ ] #803

**Comment by flannery-denny** [comment]
@schanzer you proposed the lesson for core. and the description talks about DR telephone (which I think has been algebra specific in the past). Confirming DR telephone is important to you and you feel its relevant to both pathways.

**Comment by schanzer** [comment]
@flannery-denny Yes, I think it's relevant to both pathways as long as we think the DR and collaboration are relevant to both. The DR is certainly relevant to both -- would you agree that collaboration is, too?

**Comment by flannery-denny** [comment]
@schanzer 

- What kinds of problems do we want DS students to play these DR games with? Feels like the collaboration games already exist and there are lots of DR problems for Algebra, but what we actually need to make this core is a set of problems that's relevant to DS. Would you agree?

- Are we open to renaming Restating the Problem, collaboration? In terms of actual instruction the majority of the lesson focuses on the DR games. And the current stated goal of this lesson is to focus on purpose statements, which is also your stated goal of Rocket Height.

**Comment by schanzer** [comment]
@flannery-denny 

1. I agree that we shouldn't have problems that are DS or A specific. I would use DR problems that focus on making simple images, since they are both engaging and easy to test. I could totally see a messed-up program's output being something that kids giggle about!
2. Totally re-open to it. I think that's a very smart idea.

**Comment by flannery-denny** [comment]
closing because this is a duplicate of #832
