### ISSUE TITLE
collide? to collision? in inequalities-collision lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#794]
**On Master**
- [x] fix slides
- [x] add pyret-specific DR page
- [x] use `@ifproglang` in lesson plan
- [x] resolve workbook page name issue
- [x] push to master and confirm that links on the `fall2021` `inequalities-collision-pyret` work
- [x] write to katrienv on discourse and let her know we've fixed it :)

**On Fall 2022**
- [x] Update collide? to collision? in the wescheme code
- [x] Use `@show{(sexp->code `collision?)} in the lesson plan
- [x] change design recipe function name to `collision?` on workbook page.
- [x] rename workbook page `collision.adoc`

**Comment by flannery-denny** [comment]
@schanzer I don't own the master wescheme file for the game code. Could you please change the code from `collide?` to `collision?`

**Comment by schanzer** [comment]
@flannery-denny wescheme link is updated

**Comment by flannery-denny** [comment]
Thanks! Looks like you still haven't pushed yesterday's fixes to Brown?
