### ISSUE TITLE
function and sexp->code formatting should match in lesson plans

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#795]
![Screen Shot 2022-03-03 at 1 25 07 PM](https://user-images.githubusercontent.com/66691020/156637966-f91947ec-481c-4e7a-ad65-c2b4cabe12d2.png)

In this lesson plan, "distance" was written using `distance`
and "is-collision" was written using `@show{(sexp->code 'collision?)}`

for the reader, both of them are functions, so formatting should be the same, right?

**Comment by schanzer** [comment]
Here's what I see on `master` after a fresh build:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/77126/156656123-706d5763-196f-4e5d-aaa2-1e995abd0120.png">

**Comment by flannery-denny** [comment]
@schanzer you have to look on `fall2022` because the version on master
isn't using `sexp->code`

**Comment by schanzer** [comment]
Ah, sorry - now I see which branch you want, and I see the issue.

@ds26gte , this is a symptom of a problem that has reared its ugly head a few times over the last year or so: the HTML generated by `sexp->code` is fundamentally different from code that uses asciidoc's normal code-formatting. And different HTML means different CSS behavior as well.

I still don't entirely understand why they have to be different to begin with. Can you weigh in on this? I feel like we're destined to keep finding the occasional glitch from this approach, and I want to make sure the implementation is worth the pain.
