### ISSUE TITLE
Smarter load-spreadsheet function

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#796]
Pyret's default load-spreadsheet function only accepts the fileID, which means an error-prone hunt through a URL.

We should shadow this function with a version of our own, which accepts the **whole damned url**.

**Comment by schanzer** [comment]
@flannery-denny I think you'll like this: our starter files can now just include the whole sheet URL! The old format still works, of course.

**Comment by flannery-denny** [comment]
cool. does it use the same code? Should we change the starter file to say

my-sheet =
load-spreadsheet("the-google-file-id-or-the-URL-of-your-spreadsheet")

**Comment by schanzer** [comment]
Same code. No changes needed, and it's backwards-compatible so there's no pressure to change our files right away.
