### ISSUE TITLE
Don't render lesson boxes for empty lessons in dependency-graph.js

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#801]
This lesson keeps showing up, resulting in a blank square in the choose-your-own-materials page. I can't find where it's coming from for the life of me. @ds26gte can you check it out?

**Comment by flannery-denny** [comment]
@ds26gte to be clear, the "Who are Programmers" lesson doesn't exist anymore. It's an old name for the lesson that is now called "Computing Needs All Voices."
