### ISSUE TITLE
Function Properties lesson

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#802]
**High-Level Notes**
- Can we call this `function-properties` instead of `functions-properties`? **It is currently called Properties of Functions. The folder is called functions-properties because all of the lessons about functions start with the word functions and are followed by their subtopic.**
-  If the only property we focus on is the vertical line test, maybe we should just rename this `vertical-line-test`. But honestly, I think continuity is a valuable property for us to include here. **I am fine with renaming this lesson vertical line test. I've never taught continuity as a property of functions. And I don't know why you think of it as a property of functions. Happy to learn something from you on the subject. But not over git.**
-  If we're going to focus exclusively on the vertical-line-test, there needs to be some workbook page at the end where students are given a mix of tables, graphs, and (possibly) machine descriptions, and asked to identify whether or not they are functions. This will drive home the idea of a single property being expressed in different representations.

**Lesson Sections**

**I am not attached to the vending machine stuff. It's the last page I made for the lesson and was a shift in framing so if it's not landing well, we can cut it. I am, however, attached to the idea of a concrete example of some machine that students are familiar with in the real world that can't physically create two different output for one input. And I don't want it to be about numbers. I'm all ears for what you propose as an alternative.**
-  1. Do Now - The drawing-rectangles-on-sticky-notes activity feels like it will take a lot of class time, which doesn't pay off in terms of the analogy. You could just as easily ask a single student to come to the board and draw a rectangle, and drive home the same point. The "what other functions could we define?" question is also time consuming, and doesn't feel connected to the learning goals of the lesson. Also, a Do Now would normally be the launch for a section - not its own **I don't think this would take a lot of class time - in my class it would have been done before I had everyone in the room. If there were a collection of rectangles on the board, the what other functions we could write activity would be an interesting exercise, not related to the goals of this lesson, but reinforcing the previous lesson.  I am not attached to it.  I'm ok with having one kid come up and draw a rectangle. And I'm ok with their being zero rectangles in this lesson. Perhaps it will become obsolete once we have an alternative to the vending machine.**
- 2. Functions have a Single Output for Each Set of Inputs - I like the goal of the second section and I _love_ the idea of a workbook page involving machines being reliable v. unreliable. But I don't think the workbook page gets us there. The crux of this section is that function machines are _predictable_, and we can reason about them. Maybe that's the title of the section? But more importantly, the workbook page needs to describe some input-output pairs (not button-output pairs!), and ask whether this is a machine that seems reliable. Happy to discuss more by phone.
-  3. Identifying Functions from Graphs is great. But it just makes me dislike the vending machine even more. it would be so cool if the machines in the preceding section spit out numbers/quantities, and students _revisited_ those same machines in graph form. That way it would be super-clear how the same property exists in both graphs and input-output tables!
-  4. Identifying Functions from Tables - In fact, if we could come up with machines that produce numeric outputs, this section would become almost identical to the second section. We could easily combine the two! (Minor nit: tables, by definition, are not continuous. There is literally no way to determine if a table definitively represents a function. You'll want to change the wording to be "_could_ this table represent a function?". )
-  4 (again) -- Curious to know what you see as possible Notice and Wonder responses here.
-  5. Function of notation -- shouldn't this be "function notation"?  Still skeptical this fits as part of the lesson. This feels like exactly where we want to use our graphic from [the current Defining Functions lesson](https://bootstrapworld.org/materials/latest/en-us/lessons/defining-functions/index.shtml?pathway=algebra-pyret#_examples_and_definitions). The tables you have here are all about seeing the pattern, and generalizing to figure out function notation. The fact that you're grabbing the workbook pages from that very same section suggests that you're trying to hit the same goals - why not use the same visuals? **I explicitly stated that I'm not sure that this belongs in this lesson and asked where else you think it might belong. You asked me to remove the math from the defining functions lesson. This is that and we need to find a home for it somewhere.**

**Workbook Pages**
- [x] Identifying Functions from Graphs - formatting of "function / not a function" is weird. You do it MUCH better in "how tables fail the vertical line test". I would use the formatting from that page everywhere. And no matter what you use, it should be consistent across all pages. And remember to use "could" when asking if a table represents a function.
- [ ] Identifying Functions from Tables - this is nice. My only comment is that we could draw a stronger connection back to "machines" if each table represented the output of a machine.

**Comment by flannery-denny** [comment]
@schanzer I left you this framing and these questions re this lesson in the previous git issue. Your response to the lesson tells me that you didn't see them. If you have ideas about how I could better structure the questions that I try to leave for you on git, I'm all ears.
![Screen Shot 2022-03-11 at 11 42 40 PM](https://user-images.githubusercontent.com/66691020/158005638-ea9b8e21-a16a-4e31-a784-74196f03230d.png)

I've attempted to respond to some of the bullets above in bold.

I don't know what to do with the feedback you've provided today other than to ask for a time to talk. I feel at a stand still with moving forward on the function work until then.

**Comment by flannery-denny** [comment]
@schanzer woke up thinking about the vending machine example. 
My attempt was to show a concrete real world example where inputs couldn't map to different outputs. 

The function I was working with in my mind is something like this.

`fun drink(button-name, $1) : customers-get end`

Wondering if it feel different to you if it said, "selection" instead of "button"

No worries if not, just wondered if trying to articulate that might move the conversation forward.

**Comment by schanzer** [comment]
@flannery-denny yes, I saw the notes. Thanks! This seems like a discussion best had during the phone/zoom time we've blocked out today, rather than back-and-forth over Git comments.
