### ISSUE TITLE
Collaboration RolePlay making piecewise functions, where each person has to add something to the list of options from a different perspective. 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#803]
The final product of this activity would be a set of piecewise functions or maybe a set of surveys?

The collaborative aspect is not about debugging code, but about thinking through a problem through a set of lenses. Each student will start with a card describing their advocacy role and a task.

The first person who encounters the task will add 3 items to the list. Each subsequent person will add another 2 items to the list based on an advocacy role that they are playing.

**Possible Scenarios:**

Snack options at school event
School clothing merch order from
Drink Vending machine
Activities at Field Day
Community Service Options for School-wide MLK Day of Service

**Possible Advocacy Roles:**

Stage of life: teens, babies, elderly people,  elementary school

Dietary restrictions: vegetarians, people with diabetes, lactose intolerant people / people with nut allergies, kosher/halal, people with gluten free diets

Physical restrictions: visually impaired, people with mobility issues, hearing impaired, overweight, asthmatic

Interests: athletes and other people who love to move their bodies, artists/designers, cooks, care-takers, makers, writers, 

Identity: Immigrants, BIPOC, Women/Girls, LGBTQI, Muslim

What might you add for babies / kids / teens / adults / elderly? Are there things on the list that consider girls? athletes? musicians? people in wheel chairs? people who wear glasses? etc. Assign each student an identity - role play.

**Comment by flannery-denny** [comment]
The final product of this activity would be a set of piecewise functions or maybe a set of surveys?

The collaborative aspect is not about debugging code, but about thing through a problem through a set of lenses. Each students will start with a card describing their advocacy role and a task.

The first person who encounters the task will add 3 items to the list. Each subsequent person will add another 2 items to the list based on an advocacy role that they are playing.

**Possible Scenarios:**
- Snack options at school event
- School clothing merch order from
- Drink Vending machine
- Activities at Field Day
- Community Service Options for School-wide MLK Day of Service

**Possible Advocacy Roles:**
- teens, people who wear glasses, vegetarians
- babies, pregnant people, lactose intolerant people people
- girls, athletes, people with mobility issues, people with nut allergies
- elderly people, large people, musicians, people with gluten free diets

What might you add for babies / kids / teens / adults / elderly? Are there things on the list that consider girls? athletes? musicians? people in wheel chairs? people who wear glasses? etc. Assign each student an identity - role play.

**Comment by flannery-denny** [comment]
@schanzer fyi I met with Rachel about this today and it looks like this is heading in a similar direction as the dr-telephone format... with a page of directions that link to other things that get printed... and no rubric. If you want to distinguish between `opt-printable-exercise` being for students and `opt-handout` being for teachers... not included in the extended-book or the materials section, this could be another application for the directive.

**Comment by schanzer** [comment]
@flannery-denny all the exercises and handouts are student-facing. It seems weird to make versions that are teacher-facing, especially since the teacher-facing content is neither an exercise nor a handout. 

Morally, these things are basically really giant strategy or pedagogy boxes. Perhaps this is simply a job for `@link{}`?

**Comment by flannery-denny** [comment]
Tried to come up with a context that met the goal of collaboration and thinking as an advocate for an improved outcome and haven't come up with any that feel that they support CS/DS learning goals adequately enough to justify inclusion.
