### ISSUE TITLE
audit our materials to see how often we have students create mathematical definitions in their own words in groups

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#805]
we already have a Domain and Range Frayer model in the `contracts` lesson
- [x] add function and variable as a frayer model.
- [x] add a word map for box plot words
- [x] make a solution for box plot word map

**Comment by flannery-denny** [comment]
we could add function and variable as a frayer model.

**Comment by flannery-denny** [comment]
@schanzer 

1. Here's an example of what a [box plot vocab map.pdf](https://github.com/bootstrapworld/curriculum/files/9428484/box.plot.vocab.map.pdf) would look like. Is it of interest to you? Are there other application that jump to mind? Can you image the arrows or do you need to see an example of it filled in?

2. I was going to tackle the frayer model and then wondered how much you care about visual consistency. I don't have access to the Domain & Range frayer models in any form other than pdf. I know that you just edited them to make solutions. Do you have an editable format that you could share with me or a tip for how to tackle it so that they end up looking the same? Or would you like to make a new frayer model template and save it on our google drive and then make all of the frayer models we use match?

**Comment by flannery-denny** [comment]
@schanzer look forward to hearing your thoughts on this.

**Comment by schanzer** [comment]
@flannery-denny 
1. I like the box plot vocab exercise as an opt-exercise. I think it would be even better in groups, so students have to discuss their arrows.
2. The Frayer Model - you and and I both have the same PDF, but I'm open to you making changes! If you're not sure how to modify a PDF, let's discuss in our next meeting.

**Comment by flannery-denny** [comment]
@schanzer 

1. please confirm that you agree with the solutions I've provided for `contracts/frayer-models-2`
2. currently the domain and range frayer model is being included in the workbook and this page is not. I'm ok with that, and it's how things have to be for fall2022, but wonder whether you want that change to for fall2023 and, if so, how we should track that... I'm inclined to think that the smallest headache is to make a git issue that lists changes we want to make to curriculum for next year's release, but I could change the lesson plan to include a different directive on the `fall2023` branch.

**Comment by schanzer** [comment]
@flannery-denny 

1. Confirmed! 
2. I think a "paper-cut" tracking issue for fall2023 is the way to go here. Make a checkbox for each small thing, and have those checkboxes link to other issues for larger things. Then you can check off the boxes as those changes are made in fall2023. 

WARNING: don't make changes _too_ eagerly! I'd rather save a 30sec change for 8 months from now than do that change right away. You never know how much major restructuring is going to happen between now and then, causing 1hr merge headaches for each 30sec change.

**Comment by flannery-denny** [comment]
@schanzer close if you're satisfied with the concept map solutions
