### ISSUE TITLE
New left, center, right directives

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#806]
@ds26gte Emmanuel and I would like to request three directives `@left{}`, `@center{}`, `@right{}`. Whatever content is inside the curly braces will either be left aligned, right aligned or centered.

To be clear `@left{...} will replace `@span{.left}{...}`

Once these are working we can retired some other directives.

**Comment by schanzer** [comment]
@ds26gte beautiful! 

Reminder to add `@clear`, which expands out to `<span style="clear: both"/>` in the generated HTML.
