### ISSUE TITLE
describe images - wip

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#809]
I'm working through fixing the labels of images in this [commit.](https://github.com/bootstrapworld/curriculum/commit/b2caf2066ee57868bba29a0260fc6b8e3ca74014)

I have questions about these:
- [x] lessons/correlations/langs/en-us/pages/identifying-form-open-ended.adoc
- [x] should we hardcode the code that's currently included as an image on lessons/defining-values/langs/en-us/pages/chinese-flag.adoc so that it becomes screenreader friendly?

**Comment by flannery-denny** [comment]
@schanzer this issue is ready to be closed once we resolve the two questions above and if you're ok with the histogram descriptions.

**Comment by schanzer** [comment]
@flannery-denny confirming I'm good with the histogram wording, and I took a pass at the other two pages. Thanks for kicking this issue's ass!💪
