### ISSUE TITLE
Functions make life easier lesson ready for feedback

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#817]
Not sure whether you want to give feedback on these lessons one at a time or once the whole set is done. But this one is ready for feedback. Does it scratch the itch?

https://github.com/bootstrapworld/curriculum/commit/729b09d9a2999197a4152d4f08d92f26d169a45e

**Comment by schanzer** [comment]
@flannery-denny 

**Meta Feedback**

Oh yeah, this totally scratches the itch. I LOVE this. I feel like you could add some questions at the end of the lesson to set them up for the VLT lesson as well, to really drive home that some functions take in one number, some take in more than one, and some take in a mix of numbers and strings.

**There’s Got to Be a Better Way!**

- [ ] Don't we _want_ students to type out the code from scratch each time? Why would we tell them the up-arrow shortcut? The idea is to make them realize how awful it would be without functions. Showing them the shortcut feels to me like it undermines that goal.
- [ ] _"Suppose we want to define a shortcut function called gt"_. We're defining a shortcut or a function, but not a "shortcut function". _All_ functions are shortcuts.
- [ ] I really like how thoroughly you've fleshed out the structure for the acting gig. Best write-up I've ever seen of it, and I think teachers will really be able to use it effectively.

**Identifying and Describing the Pattern**

- [ ] I love this whole section. Super clear, and the pattern work feels like it sets students up to handle formal examples easily! 
- [ ] _"If we keep everything that stayed the same and replace the numbers that changed with size, it looks like this:"_ Would it be possible to change "replace" to _"substitute"_? In formal mathematics, the "substitution model" is a really big deal and this is literally where it comes from. Plus, it will make Shriram incredibly happy. ;-)
- [ ] The Great GT Domain Debate - I find myself wanting to refer kids back to the rehearsal they witnessed. Is it worth mentioning it in the worksheet, like "Kermit and Oscar are arguing about the performance...."? Or are you intentionally leaving out the reference to ween kids from the acting example? 
- [ ] _"our volunteer inserted into the triangle function"_. Are you sure you mean the _function_? Recommend changing to _"our volunteer substituted into the triangle expression"_.
- [ ] Let’s Define Some New Functions! -- I love this!!!! Especially the reference back to acting. Assuming this is just draft formatting, and you'll make it look prettier in the final version?
- [ ] Describe and Define Your Own Functions! -- I was literally about to write a note that this would be a great worksheet to follow, and then here it is.  Is it worth making the third question into a challenge, where we dare them to make a function with (gasp!) **two** variables? That feels like it would be a nice brain stretcher, and result in some really stimulating exploration.
