### ISSUE TITLE
Do we want to be able to write `code` as @show{(code `code)} and have the styling match?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#820]
![Screen Shot 2022-03-28 at 2 26 50 PM](https://user-images.githubusercontent.com/66691020/160472219-8016407a-6663-4629-be04-c8a71fc24a9b.png)
![Screen Shot 2022-03-28 at 2 27 00 PM](https://user-images.githubusercontent.com/66691020/160472227-aa78fb7a-76d5-41f9-9214-c6772e32f8ee.png)
![Screen Shot 2022-03-28 at 2 27 17 PM](https://user-images.githubusercontent.com/66691020/160472230-9e463915-3729-41f3-b50d-ff89863c8228.png)
Perhaps I shouldn't be using `sun` here, but if I should be able to write it that way, it still doesn't match. Should I change my habits? Do we want to make these things match? Or should we ignore the styling differences?

**Comment by ds26gte** [comment]
Hmm. It looks like the boldness of the surrounding prose is being inherited by the embedded code fragment?

**Comment by flannery-denny** [comment]
Thanks for solving the mystery @ds26gte! resolved.
