### ISSUE TITLE
Function Notation Lesson ready for feedback and help with bolding mathjax

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#823]
- [x] FD - create piecewise function graph page
- [x] ES - approve new wording from revisions
- [x] ES - let fd know re: table page (see comment below)
- [x] As we discussed in our meeting, I'm trying to figure out how to bold the header definitions in the second table and the expressions that we see in the same table in non-solution-mode. 
![Screen Shot 2022-03-29 at 2 28 23 PM](https://user-images.githubusercontent.com/66691020/160692099-89ec5383-4c90-42bd-ae93-206c32d02754.png)
I look forward to learning from what you sort out... and it wouldn't be the end of the word if we just removed the [.bold] tag from the file and left it without the beautiful formatting I'm hoping for...

**Comment by schanzer** [comment]
@flannery-denny 

**Meta Feedback**
- Overall this lesson rocks, and I feel really good about it. 
- The biggest meta-question I have is: "this feels _really_ similar to some of the work in `linearity2`, in which students need to connect function notation (definitions) to graphs and tables. Is there an opportunity here to copy/create an optional exercise or two from that lesson into this one? Specifically I'm thinking of "definitions-from-graphs", 
"definitions-from-tables", "match-definitions-graphs", and "match-definitions-tables". 
- You seem to be using [.lesson-instruction] in a new way, which is different from how we've used it in the rest of the lessons. That format is when a specific direction is given to students, _not_ when there's just a talking point we want teachers to address. In this lesson, you've used it for both.
- I made some small wording changes and suggestions, which you may want to read first. This includes removing some uses of [.lesson-instruction]
- Any change that involves more than small wording adjustments is proposed below. Note that in some cases I may have tried to rewrite an instruction (small, done via commit), even if I'm actually questioning the whole activity (large, suggested below).
- Assorted nitpicks below

**Function Notation & Substitution**

- [ ] _Given the function f(x) = x + 8, what question could we ask that would return the same result as the expression f(3)?_ -- I could NOT figure out what you wanted until I saw the answer you were expecting. What's the goal of this question? Is it to review whether they understand substitution, or to make them think more flexibly about the concept by introducing them to the idea of this being a question? If it's the latter, I think they need more explicit instruction ("asking what is f(3) is the same as...")

**Function Notation - Graphs**

- [ ] "Function Notation - Graphs" -- I _really_ like the idea of including the scatterplot quite a lot. BUT: (1) we should mention this in the lesson plan and (2) we should show some piecewise graphs as well.
- [ ] This could be pitched as "this works even for more complex functions, which you haven't see yet!" This sets kids up beautifully for later material.

**Function Notation - Tables**
- [ ] "Function Notation - Tables" why does the first row of tables have two expressions beneath it, but the second row only has one? I think it's better to be consistent.

**Comment by schanzer** [comment]
Definitely. But then do you still follow up with "what is another way to ask it?", with the expected answer bring "what is 3+8"?

**Comment by flannery-denny** [comment]
@schanzer Just pushed an update. You'll get a warning about a missing page. I'll make it when I'm done with big picture thinking about the remaining lessons. 


- [ ] Please confirm that the second set of directions on function notation - substitution make more sense to you now.
- [ ] I added a scatterplot and a piecewise graph to the lesson plan in the graphs section. Does the wording work for you?
- [ ] I will add an @opt-printable exercise that looks just like the first with more graphs, including piecewise functions.
- [ ] The reason only one row of the page on tables asks for two values is about space. I think it's critical that students understand we can apply more than one value to a function, but I couldn't fit it for every row. Can you css magic me enough room on the page for a second set of questions on each of tables? Or should I pair back two only 8 tables and have them evaluate multiple expressions for each?

**Comment by schanzer** [comment]
@flannery-denny Confirming the new directions, plots/graphs, and opt-printable-exercise proposal.

I've used my CSS magic and added extra rows. I think it would be helpful to _number/name_ each table, so I did so by naming the functions a-l. I also took the liberty of breaking overly-rigid patterns when it comes to variable names, but I'm happy to talk discuss if you don't like it. I also explained in the instructions that not every relationship here is a function -- you ok with that?

**Comment by flannery-denny** [comment]
@schanzer you requested consistency on the `function notation tables` page re: asking students to evaluate 2 expressions per table. The `function notation graphs` pages have a similar issue where I am only able to fit asking for 2 expressions to be evaluated in one row of graphs.  Is this fixable by css?  Or should I drop to 6 graphs per page so that I can ask for multiple values?

(Asking because I'm working on the function notation piecewise graphs page and the

**Comment by flannery-denny** [comment]
@schanzer Close if you're satisfied. Noting that 2 of the graphs on the functions-graph page didn't have a second set of identifiable points. I add f(-infinity) for one and the other only has one expression.
