### ISSUE TITLE
Is it possible for us to distinguish when code should break lines and when it shouldn't

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#824]
When I type this into the lesson plan, 
`@show{(code '(EXAMPLE
      (gt  20) (triangle 20 "solid" "green")
      (gt  50) (triangle 50 "solid" "green")))}`
I expect it to appear in my lesson plan as 4 lines:

> examples:
> gt...
> gt...
> end

Instead it takes six lines. 

Look at the difference between the version screenshotted from pyret and the version produced by code.
![Screen Shot 2022-03-29 at 3 22 49 PM](https://user-images.githubusercontent.com/66691020/160700737-dcc28237-287d-4b4f-9e13-b2109a1e78c4.png)

Is there any way around this?

**Comment by flannery-denny** [comment]
Another example in my authoring work of where it would be useful to be in control of line breaks...
![Screen Shot 2022-03-29 at 5 27 08 PM](https://user-images.githubusercontent.com/66691020/160717216-e8778d95-57d7-48f4-9bcf-22e9e2dbb9e8.png)

**Comment by flannery-denny** [comment]
nm re: that last comment. going to hardcode it by proglang. Don't really need examples / end anyway.

**Comment by schanzer** [comment]
@ds26gte I thought `code` already knew how to handle multi-line contents?

**Comment by flannery-denny** [comment]
@schanzer I think we needed examples to look this way for a matching exercise... so what I'm asking is is there a way to decide how they look?

**Comment by schanzer** [comment]
That depends on @ds26gte 's answer. :)

**Comment by ds26gte** [comment]
This is a case where the preproc takes a heuristic approach to when the example line should be split (at `is`), based on how wide the clauses are.  Right now, it's checking to see if the combined length of the clause is more than 35 before deciding to split. 

35 is probably too small a bound. I can up it to 60, and also make it a parameter instead of hard-wiring it like I unaccountably have. That way, @schanzer can tweak it based on experience with the document over time.

**Comment by schanzer** [comment]
@ds26gte this seems to address @flannery-denny 's immediate concern. Flannery, can you confirm this?

1) Dorai and I spoke about a way to do this that doesn't rely on heuristics, and instead just obeys where the linebreaks are in the passed s-expression. He's going to explore if it's even possible.

2) @ds26gte , I notice that pyret functions are generated with a lot of extra whitespace between the colon and the function body. In `lessons/defining-functions/pages/match-examples-definitions.html`, for example, I'm seeing the following screenshot:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/77126/160924932-a897a265-6884-4ebd-9b39-4a511fe1f225.png">


Can we get rid of all the extra whitespace?
