### ISSUE TITLE
Functions as Contracts, Examples, and Definitions ready for Feedback

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#826]
- [x] I feel fine about this lesson, but not jazzed. Perhaps that's because I'd made new pages for it recently and it didn't need much creativity? Perhaps it's because we separated it from the gt acting? Think it works? or is it missing something?
- [x] I'm undecided as to whether we should include the matching pages in the workbook. They don't feel integral to the lesson, but they would be a good homework assignment, and, as such, might be worth giving teachers copies of in the workbook.

**Comment by schanzer** [comment]
@flannery-denny I've been thinking about this all day, and I have a suggestion. 

In the hierarchy of mastery levels, matching is definitely a lower-level skill than creation. I'd propose breaking this into two sections. The first section should have the exact launch you have here, which I think is strong and clear. But the investigate should be where those matching activities come in.  The second section should be the almost-DRs, where students use the patterns they've identified to actually _write_ those representations.

What do you think?

**Comment by flannery-denny** [comment]
@schanzer pushed a change. close if it works for you.

**Comment by schanzer** [comment]
@flannery-denny Nice work. This is perfect. Let's cross this one off!
