### ISSUE TITLE
Functions can be Linear & Defining Linear Functions ready for Feedback

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#827]
[ ] Feedback on Functions can be linear
[ ] Feedback on Defining Linear Functions

**Comment by flannery-denny** [comment]
@schanzer This lesson is close. Before I can wrap it up, I'm curious whether you like that it's all together, or would prefer to see it split into two lessons. I think I would split off just the last section "Defining Linear Functions". Lmk what you're leaning towards so I can finish polishing with that in mind.

**Comment by schanzer** [comment]
@flannery-denny looks great. Done!
