### ISSUE TITLE
Making freshly-clicked link visually different?

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#83]
There are a lot of links on the TR page, and as a visitor checking out the extra stuff and moving back and forth, it's hard to remember which one I was just at.  Can the link that was just clicked be a different color or somehow visually distinctive from the other links?

If this is not possible or seen as not necessary, feel free to comment and close.

**Comment by schanzer** [comment]
We can style links that have been clicked before, and we can style links that have never been clicked. But we can't style "the most recently-clicked link". Would it be okay to style unclicked links differently?

**Comment by schanzer** [comment]
I need @ds26gte to help me figure out how to add attributes to links in asciidoc, so they open in a new window. Otherwise, however, the visual cue should work on mouseover. Tell me what you think?

**Comment by BootstrapJen** [comment]
Looks great, thanks! It only seems to work on the WeScheme one, can it be on the Pyret one as well?

**Comment by BootstrapJen** [comment]
Looks great, thanks!
