### ISSUE TITLE
Collaboration Lesson w/ DR game and collaborative function composition exercises.

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#832]
Soliciting ideas for "word problems that students can collaborate on, such that when the resulting functions are composed cool things happen!"

-----------------------------------------------
Archived/Original description:
DR is only referenced 3 times in DS:

- defining table functions
- method-chaining
- choosing your dataset

**Comment by flannery-denny** [comment]
@schanzer Love this suggestion and it is not useful for Design Recipe Telephone. Any ideas of word problems that work for algebra and DS and the DR?

**Comment by schanzer** [comment]
@flannery-denny why is it not useful for Design Recipe Telephone? Maybe I'm not clear on what you're looking for here.

**Comment by flannery-denny** [comment]
@schanzer As I understand Design Recipe Telephone, we need a set of problems that can be read and then hidden after student 1 has written the contract and example. This activity was designed to be unplugged and I believe it should remain that way because:

1. They don't have to rely on each other's work if they're all looking at the same starter file.
2. When I was in the classroom, my students were happy to complete a design recipe if we were working offline, but if I gave them the starter file without having them do the design recipe in writing first, they were much more likely to try to skip steps... so, I would want to be able to do DR telephone offline.

Given how hard it is to come up with word problems that work in both pathways and aren't starter file dependent, **I propose we stop trying to make collaboration a core lesson** and instead:
- have an algebra collaboration lesson that focuses on the set of problems that we already have
- add DR telephone into the Defining Table Functions lesson you're going to rewrite
- focus creative energy on beefing up collaboration in DS through the other ideas we've already generated like #803,

**Comment by flannery-denny** [comment]
@schanzer You had me convinced to throw my energy into making this lesson core. I've spent the evening wrestling with thinking of 3 functions that could be generated using the dr and then combined in a starter file to make something cool. 

After many hours, here's why I think it's not the answer:

- [ ] While I have come up with 3 functions that would be useful to define, It is hard to write a word problem for them that is not almost exactly the same as the purpose statement... so these function aren't really forcing students to focus on writing good purpose statements
- [ ] When I think about writing examples for these, it feels frustrating because, while there are some images defined in the starter file, students won't be looking at them, so they'll have to write out all of the code for a shape as an input (many of which are terrible examples for rotation) or make up a url... much more complicated than examples that involve strings and numbers...

I think we'd get more buy in on the value of the design recipe if we used examples that need the Design Recipe more... and those are pathway specific.

Perhaps you'll agree when you look at the starter file? Or perhaps it will give you something concrete to respond to to alleviate my concerns?

[starter file](https://code.pyret.org/editor#share=1FJlZuIrfDR27gprdkGl0-myof5LmgUwL&v=1904b2c)

**Comment by schanzer** [comment]
@flannery-denny We can also change the wording of the problem statements to be a little less structured:

```
# Word Problem 1: 
# Define a function f that takes in an image shrinks it to 1/3rd the size.

# Word Problem 2:
# Define a function g that takes in an image, rotates it 36 degrees clockwise, and flips it horizontally.

# Word Problem 3: 
# Define a function r that takes in a color and returns a solid pentagon of size 300, in the given color. 
```

Writing the purpose statement from those word problems requires a little more thought, so perhaps this addresses your 1st concern?

As for writing examples - why not ask students to define two images at the beginning, or just _give_ them two images with instructions to evaluate them and then use them in their examples?

**Comment by flannery-denny** [comment]
# Word Problem 1: 
# Hali is decorating her tree house and is having a hard time fitting everything on the walls. She's figured out that if her artwork were 3/8 of the original size it would all fit. Help her by writing a function f to scale down any image to a size she can use!

# Word Problem 2:
# Define a function h that will take an image and rotate it clockwise one-tenth of the way around. Hint: A full rotation is 360 degrees, which you may have heard people refer to in skateboarding or snowboarding tricks.

# Word Problem 3: 
# Mia's favorite shape is a regular pentagon and she wants to decorate a special box with pentagons of every color. Help her to realize her dream by writing her a function r that takes in a color and returns a solid 5-sided regular polygon of size 300 in the given color.

**Comment by flannery-denny** [comment]
@schanzer this lesson is ready for review

**Comment by schanzer** [comment]
@flannery-denny Overall I like the direction this is going!

- [ ] The instructions for this are (understandably) complex. I wonder if it would be simpler to do this as a table, with rows for each "round" and columns for kids 1, 2, and 3. The cells would show what each kid is looking at for that round?
- [ ] a lot of the DR pages for this section have very important instructions at the bottom. Can we move them to the top?
- [ ] The right-trapezoid problem could really benefit from a diagram!
- [ ] How much time do you expect this activity to take? If it's a full class period, you'll want to add a `@duration{}` directive saying so.

**Comment by flannery-denny** [comment]
@schanzer we can't put the directions at the top of the DR pages because they'll get folded over and the notes are for the people writing the examples. I did, however, add a right-trapezoid, which I meant to do initially - thanks for the reminder!

I wish this lesson had a second part, but I'm not thinking of anything great at the moment and I think that it could take a full class as is. 

Close if you're satisfied.

**Comment by flannery-denny** [comment]
@schanzer we can't put the directions at the top of the DR pages because they'll get folded over and the notes are for the people writing the examples. I did, however, add a right-trapezoid, which I meant to do initially - thanks for the reminder!

I wish this lesson had a second part, but I'm not thinking of anything great at the moment and I think that it could take a full class as is. 

Close if you're satisfied.
