### ISSUE TITLE
Defining Table Functions Rewrite & Workbook expansion

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#833]
- [ ] This lesson will follow **Functions make life easier** in the DS pathway. It is the formal introduction of the Design Recipe, so that aspect of the lesson needs beefing up.
- [ ] Do we want to go lighter on custom scatterplots in Defining Table Functions now that we have a dedicated custom scatterplot lesson? Both lessons currently have students use `age-tag` in a custom scatterplot.

**Comment by schanzer** [comment]
Notes for self:

- [ ] can scatter-plots be introduced earlier?
- [ ] if so, do it and attach custom-scatter-plots
- [ ] Use custom-scatter-plots to motivate functions
