### ISSUE TITLE
"unplugged" filtering activity would benefit from revision

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#836]
I'm revisiting the unplugged function activity [here](url) as I'm working on CODAP stuff and I'm discovering that, if I were a teacher trying to run this activity, I'd be confused! 

Our directions say, "Have 6-8 students line up in front of the classroom, and have the filter method go to each student and say 'stay' or 'sit' depending on whether their function would return true or false for that student. If they say 'sit', the student sits down. If they say 'stay', the student stays standing." 

....but then we have functions such as "likes-tacos" (how would the filter method know just by looking which kids like tacos?) and "is-smiling" (during what moment in the activity?). 

Also, kids are supposed to guess the function on the card, which would be quite difficult in many instances - like if there are no students with red hair in the group of 6-8, so everyone remains standing. For this reason, I don't think we want to instruct that the filter method kid randomly chooses their function card. I think the teacher maybe needs to choose strategically? Or, teachers need to be offered guidance on what to do / how to respond thoughtfully if all children remain standing, or if all children sit down.

I also think we should provide an answer key! This is a discovery activity of sorts (and kids' first encounter with the filter method). I don't think the solutions are obvious. (Kids need to sort of imagine a fictitious dataset and think about what attribute names would be, right?)

**Comment by schanzer** [comment]
@retabak the filter method would _ask_ each student if they like tacos or not. And I agree that a note about choosing the cards strategically is a valuable addition.

The link you shared is broken, so I'm not sure what activity you mean. Can you fix the link, and I'll comment on the answer key?

**Comment by schanzer** [comment]
@retabak They can't guess `r["height"] > 5`, because they don't know what the variable name is. They also don't know what the column/attribute name is. _There is no code, so they can't guess code._

I think you're 100% right that the instructions should be more clear. The goal is for students to make educated guesses, but that's all.

**Comment by retabak** [comment]
Well, a teacher could guide her students to imagine a fictitious dataset and make an educated guess about the column / attribute name. That's actually what I thought you maybe wanted to happen -- which seemed VERY ambitious, especially without an answer key. 

Anyhow, I think you get my point that the directions leave folks with a lot of questions. I believe that quite a bit more guidance and specificity is needed.

**Comment by retabak** [comment]
Played around with this activity. Take a look at [this google doc](https://docs.google.com/document/d/1esp-E4CaJhlQGgI1UmKX-fuCD9DzE6Q4uUo2AwA_lbI/edit?usp=sharing)! (I can change the .adoc too once we're happy with a draft.)

**Comment by schanzer** [comment]
I love it. Left you a one small comment. Go for it.
