### ISSUE TITLE
We need variable-height paragraphs and revised flex-css for tables

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#840]
The `fall2022-flex` merger bought us _horizontal_ flexibility: blank lines can now stretch to the end of the page, regardless of where they began.

However, this came at a cost: we lost _vertical_ flexibility, so every line has a fixed height. 99% of the time this is fine, but there are several corner cases where we'd like the lines to be taller (e.g. - "what's on your mind?" pages, and others). So far, the only CSS solution I've found requires a fixed _minimum height_ -- it solves all of our problems, but empty lines that used to take up no vertical space now **do**. And that breaks a lot of pages, by added extra height.

**Comment by ds26gte** [comment]
Actually, `@include` very religiously does _not_ insert any extraneous newlines. I suspect there is an actual extra newline in the included file or newlines flanking the `@include` call.  Please give an example where an unwanted newline is sneaking in and I'll investigate.

**Comment by schanzer** [comment]
@ds26gte see the file I checked in with a185f6dde2c911c8cac05cfc5a76ba459dd96bd3

**Comment by schanzer** [comment]
There's been a regression in CSS-flex -- we need to revisit notice and wonder pages, as well as order-of-operation tables.

**Comment by schanzer** [comment]
After nearly a week of testing and reading StackOverflow threads, it appears that **a table cannot be stretched to fill its container!** I was able to construct a horrifically ugly hack that works for Notice and Wonder pages (only one body cell), but fails miserably for the many other workbook pages that involve tables. I think we may need to stick with fixed-height tables for the foreseeable future.

**Comment by schanzer** [comment]
AHA!! Maybe there's a way to make tables work after all -- [by treating them as grids](https://adamlynch.com/flexible-data-tables-with-css-grid/)

**Comment by schanzer** [comment]
Some pages needed to drop a blank line to fit after tables were made adaptive. Keeping note of them for fixing once we have variable-height lines

- [ ] computing-needs-all-voices/pages/advantages-of-diverse-teams
- [ ] functions-make-life-easier/pages/sun
- [ ] functions-dr/pages/fixing-purpose
- [ ] linear-regression/pages/interpreting-regression-lines-n-rvalues
- [ ] custom-scatter-plots/pages/defining-row-consuming-functions

Other issues:

- [ ] Landscape Pages aren't respecting margins
- [ ] WBPages with multiple subsections have extra space (see functions-examples-definitions/pages/name)
- [ ] Explore creating a separate class for FillVerticalSpace with headers

**Comment by schanzer** [comment]
These are fixed in #1148, pending review and approval
