### ISSUE TITLE
Find a home for "Where'd you get that?"

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#842]
Right now it's buried in functions-solving-word-problems, but it really needs a better place.

**Comment by flannery-denny** [comment]
**Where'd You Get That?**

Divide the class into pairs, giving each pair two word problems (the whole class can use the same set, or different ones), and have students solve one problem each _independently_. Once finished, students take turns _challenging each other_. The Challenger always starts at the *bottom* of the page, physically pointing to one part of the function definition and asking "where'd you get that?" The Defender has to _physically point_ to some location in the Examples, and explain exactly how they got that part of the definition. This is repeated for every other step in the recipe, as students work their way back to the original word problem. For example:

- *Challenger* (pointing at variable in the Definition): Where'd you get that?
- *Defender* (pointing at label in the Examples): Well, I circled the parts of the Examples that change, and gave them that label.
- *Challenger* (pointing at the label): OK, but where did you get the label?
- *Defender* (pointing at Purpose Statement): I used that term in the Purpose Statement.
- *Challenger* (pointing at Purpose Statement): Where'd you get that term?
- *Defender* (pointing to Word Problem): I got it from reading the Word Problem.
|===

*Optional:* Ask students to create their own appropriately challenging word problem (with a solution) and collect the responses for later use as "Do Now" tasks or formative assessment.
