### ISSUE TITLE
confirm that we're happy with new lesson titles on fall2022 so that we can fix corresponding standards and practices files

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#843]
The guiding principle I used was that the adoc files should be titled so that they're grouped logically for authors and the lesson titles should be as clear as possible for teachers. Here's what we have at the moment. Check off whichever are good to go and leave unchecked any we should discuss

- [x] functions-make-life-easier = Functions Make Life Easier
- [x] functions-vertical-line-test = The Vertical Line Test
- [x] function-notation = Function Notation
- [x] functions-examples-definitions = Functions: Contracts, Examples & Definitions
- [x] functions-can-be-linear = Functions Can Be Linear
- [x] function-definition-linear = Defining Linear Functions
- [x] functions-dr = Solving Word Problems Using the Design Recipe _renamed the file functions-dr from functions-solving-word-problems to make it easier on authors_
- [x] functions-collaboration = Collaboration

**Comment by schanzer** [comment]
@flannery-denny I'm good with all of the above, and was about to suggest `functions-dr` myself! :)
