### ISSUE TITLE
Confirm New Lesson Orders, Prereqs are Correct

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#845]
@schanzer 

- [ ] I'm about to push drafts of what the lesson orders for Algebra, Data Science and Oklahoma might look like post shake up. Feel free to adjust. Confirm that they are as you mentioned
- [ ] I've updated prereqs for the function lessons - please confirm that they make sense to you.

**Comment by schanzer** [comment]
@flannery-denny Here's the order your proposed:

**Comment by flannery-denny** [comment]
@schanzer 
I don't think VLT uses function notation at all.

**Comment by flannery-denny** [comment]
@schanzer biggest question was about DS  - do we want 3 lessons or just 2?

**Comment by schanzer** [comment]
@flannery-denny I've pushed a few proposed changes to the prereqs, along with some small formatting tweaks. 

I think functions-examples-definitions is a core lesson -- separating the _existence_ of three representations from _using those three in the Design Recipe_ is a substantive change that we made last year, which got some great feedback. I think we should keep it in all of our pathways.

**Comment by schanzer** [comment]
@flannery-denny Your Algebra sequence looks good. If you feel good about the sequence in #847 , I can push these changes through to OK and Reactive.

**Comment by flannery-denny** [comment]
@schanzer I'm definitely not sold on #847. Will give it another look after you tackle the comments I left in the issue. lmk if you want me to take on any of it.

**Comment by schanzer** [comment]
@flannery-denny ok to close? Not sure if I sold you on #847

**Comment by flannery-denny** [comment]
@schanzer 
custom scatterplots and method chaining both use the full design recipe - they need to come after functions-dr

Should the DR practice section from Method Chaining move up to Table Methods? 

Also re: Scatter plots - I still think the first synthesize is confusing.

**Comment by schanzer** [comment]
@flannery-denny I've tweaked the custom-scatter-plot lessons to make sure it belongs _before_ functions-dr, and modified the synthesize section in scatter-plots.

table-methods comes before the functions-dr, so the DR practice wouldn't make sense there.

Anything else regarding lesson order and prereqs?

**Comment by flannery-denny** [comment]
@schanzer Looks much better. My only remaining question is about the Design Recipe Practice in Method Chaining.

The first file "Design Recipe: is-dog / is-female" has everything on the first problem completed except for a single missing example.

- [ ] If this degree of scaffolding is still necessary, let's please fully complete the first DR in its entirety and adjust the Directions on the wb page and in the lesson plan to acknowledge that the first one has been completed for them.

**Comment by schanzer** [comment]
@flannery-denny good catch! I've removed a lot of the answers, and clarified the instructions. Close if you're good with this.
