### ISSUE TITLE
DS Restructuring

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#847]
**scatter-plots** 

- [x] discuss randomness
- [x] show random scatter plots
- [x] consider the datasaurus!
- [x] focus on seeing patterns

**custom-scatter-plots**

- [x] see if it requires the DR. If not, move it before `functions-dr`
- [x] come up with at least 2 function definition ideas that do NOT require if/then/else
- [x] show the species-image starter file, and provide a link to `piecewise-functions-conditionals`

**table-methods**

- [x] TBD - might not need a change at all!

**defining-table-functions**

- [x] refocus around collaboration, leveraging the model in `functions-collaboration`
- [x] Change 1st section to be primarily self-driven review
- [x] replace `nametag` with a better example!
- [x] Come up with two sets of 3DRs, which can be combined to produce an interesting result from the animals table

**Comment by schanzer** [comment]
Closing, since the only remaining checkbox is #833

**Comment by schanzer** [comment]
@flannery-denny this rewrite is complete, and ready for review! The sequence in question is:

random-samples
scatter-plots
functions-make-life-easier
functions-examples-definitions
custom-scatter-plots
table-methods
method-chaining
functions-dr
functions-collaboration
defining-table-functions

The non-`functions` lessons have all been modified to reflect the change.

**Comment by flannery-denny** [comment]
@schanzer 

- [ ] The overview of Random Samples is really long and includes directions about how to interact with students, which would be a very unconventional move or our lesson plan format. The  example about voting appears both in the overview and the launch. Please revisit these two sections and decide which part you meant to include in the launch and which part you meant to put in the overview.

**Comment by schanzer** [comment]
@flannery-denny 

**Big Picture** 

- I've hidden the lines that let them define filter and builder functions, but I'm not going to hide the line that asks them which rows. That's an important thing for them to see and consciously decide! 
- As for the functions-dr part, we spoke by phone so you know this won't change.

**Random Samples** - this lesson is going to be overhauled anyway, so I'm not addressing these issues just yet.

**Scatter plots**

- What pattern do you see in the scatter plot? 
- I've made it clearer in the text that we're asking students to find a pattern _in the scatter plot they drew on the wb page._ I like the suggestion of adding "...do we want to investigate"! 
- Modified the data cycle template to add that text to the "rows" and "columns" rubies. 
- As for the second question showing up - you're right, and I've deleted it. But this also exposed a bug, which I'll file with Dorai. Thanks!

**Custom Scatter Plots**

- working on it...

**Table Methods** - All of your suggestions are spot on. I've pushed these changes

**Defining Table Functions** - I'm happy with your wording changes. Agree re: retitling the telephone section, and I've fixed the links on the sophisticated analysis pages

**Comment by flannery-denny** [comment]
@schanzer I pushed some proposed wording tweaks for the scatter plots lesson. 

Thinking maybe this set of questions from the end of the lesson deserves a workbook page.

> How are the pounds of an animal related to its age?
> 
> How are the number of weeks it takes for an animal to be adopted related to its number of legs?
> 
> How are the number of legs an animal has related to its age?
> 
> Do you see a linear (straight-line) relationship in any of these, evidenced by a cloud of points that’s clearly rising or falling from left to right?
> 
> Are there any unusual observations?

**Comment by flannery-denny** [comment]
@schanzer just pushed a change to **creating scatter plots** . It felt crowded and I wasn't convinced the first question was productive. revert if you don't like it.

**Comment by flannery-denny** [comment]
@schanzer 
- [ ] now that **defining row-consuming functions** has students write the **species-tag** function, we need to decide whether to tell them to compare their definition to the one provided for them in the **custom scatterplot starter file** or to change the starter file so that they have to add it themselves.
- [ ] I'm not sold on this part of the Custom Scatter Plot Explore page. 
> 1 What is the data type of species-tag?
> 
> In the program, define a row called sasha, which is the first row in the table (index 0).
> 
> Then define a row called snuffles, which is the second row in the table (index 1).
> 
> 2 Click Run. What happens when you evaluate species-tag(sasha)?

- Is it important to have them define some rows? If so, some parts of the lesson refer to Animal A and Animal B. This part refers to Sasha. Let's pick one and stick to it.
- If we want them to define rows in the starter file, let's add an obvious spot for them to do so in the starter file.\

**Comment by schanzer** [comment]
@flannery-denny good call. Addressed both issues in the latest commit. And your wording changes look fine to me.

**Comment by flannery-denny** [comment]
@schanzer Table Methods still inconsistently uses animalA, animal B, dog-row, cat-row. And I think the workbook pages could scaffold more of the directions being given in the lesson plan about how to interact with the Table Methods starter file. Want to take another pass? Or would you like me to tackle this and push something for you to review?

**Comment by schanzer** [comment]
@flannery-denny where do you see animalA being used? They don't show up anywhere in the lesson plan, starter file, or workbook pages. You're welcome to push something to review.

**Comment by flannery-denny** [comment]
I'll fix the starter file and push some suggestions for the lesson

![Screen Shot 2022-04-19 at 1 04 10 PM](https://user-images.githubusercontent.com/66691020/164057680-1a8099e3-9ef7-44d0-a7d3-c7c26c38101b.png)

**Comment by flannery-denny** [comment]
@schanzer check out my last commit and consider whether the table makes sense to you. A question I have regarding the starter file is that you ask students to write 3 more examples for is-dog, but you don't ask them to write examples for any of the other functions.

Do you want them to write examples for the other functions?

If not, can we edit the starter file to get rid of **Write 3 similar examples for dog-row on the lines below** and just let them do that on the wb page?

**Comment by schanzer** [comment]
@flannery-denny I like the changes! I've tweaked the formatting a bit to make it all fit on one page, but otherwise the wording is unchanged.

Modified the starter file to remove the "write 3 similar examples" language.
