### ISSUE TITLE
Collected Notes pages on Teacher Resources page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#848]
Dorai - we'd like to have a new section on the Teacher Resources page, which contains the collected links of every "notes" page inside a lesson plan. All of these files start with `notes-`, and ONLY these files.

Is this doable?

---------------------------------------------------------------------------------------------------------
Original Issue:
When I taught BS:Algebra (and did not use student workbooks), I was unaware of the existence of the notes pages.

Do these exist anywhere other than the workbook PDF? (If so, I am unable to find.) Should they perhaps be on the lesson table, or referred to in the lesson?  Or could they be linked with the exercises / solutions on the teacher resource page? 

This is a nice resource that I think perhaps folks are not using because they may not be aware that it exists.

**Comment by ds26gte** [comment]
I've added the desired links, using the titles of the notes pages as the link texts. Let me know if you prefer some other link text.
