### ISSUE TITLE
Formatting fixes for DS workbook once build is stable

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#851]
- [x] extend notice and wonder page - _which notice and wonder page needs to be extended? the one in computing-needs-all-voices seems to fill the page._
- [x] extends windows and mirrors writing space
- [x] expand writing area for reflection: Problem solving advantages of diverse teams
- [x] add 4 more lines to the what's on your mind pages
- [x] defining row consuming functions. add another line for question 3
- [x] species-dot-explore extend notice and wonder
- [x] Fixing Purpose Statements - add another line to each.
- [x] Which Questions Make Sense to Ask? Add 2-3 lines for numbers 7 & 8.
- [x] Add `computing-pioneers.adoc` to `workbook-pages.txt`
- [x] make sure @schanzer has added all to the options beneath rows for Data Cycle pages
- [x] Add Computing Needs All Voices page to lesson order
- [x] extend bar & pie notice and wonder 
- [x] space out custom-scatter-plot-explore
- [x] reading-row-and-function-definitions - No.11 add room for them to write the functions definition and more space to describe it.
- [x] Trust but verify 1 and 2. Add some lines so that there are at total of 9 for question 1 -- 9 lines didn't seem to fit, so I added 9. Is that ok?
- [x] My dataset is 2 page
- [x] Reflection on Form, Direction and Strength - all questions should have 4 response lines
- [x] Correlation Does Not Imply Causation! - give 3 more lines for each
- [x] Correlations in the Animals Dataset - No.3 make space for "stronger" "weaker" and then add a few more lines. - _I'm not sure I understand the part about more space for "stronger" and "weaker", but I added lines. Can you clarify?_ **Fixed it -fd**

**Comment by flannery-denny** [comment]
@schanzer please confirm that you are ok with the new wording for defining row functions. I realized that the old wording didn't make it completely clear that we were expecting kids to write code.

**Comment by schanzer** [comment]
@flannery-denny  Totally happy with it
