### ISSUE TITLE
Sharing Pioneers lesson in 2 facebook groups

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#852]
I belong to two different facebook groups that I would like to share our pioneers lesson to!  The first is called "Equity and Social Justice in Math Education" and the second is "Desmos Educators." We discussed sharing in the Desmos group a while ago but I'm just now making it happen.

Blurbs in [this google doc](https://docs.google.com/document/d/1ICUX6mjxVkqJnKoq1d8PuAkvt0urMKjSV2i_VCR_w6I/edit). Please share any thoughts / feedback!

I know the first impression might be that it's not appropriate to post in Desmos, but I'm confident that it's fine. People use that group (wihch is very active, and full of very dedicated teachers) to share all kinds of great resources. (Yes, most are Desmos resources, but not exclusively.)

**Comment by schanzer** [comment]
I love the blurbs, @retabak , but yeah - my reservation was about the nature of the desmos group. But if you're confident that it's fine, I'll trust you.

**Comment by flannery-denny** [comment]
@retabak @schanzer is there a great reason to post these right now?  Can we wait for the next release? The version live on our website includes kimberly bryant and doesn't include skip ellis or evelyn granville. We aren't allowed to make those live on our website until Emmanuel creates a way for us to credit the images from the archives.

**Comment by retabak** [comment]
Yeah - totally no rush! I was posting the IM one-pagers and my brain was in
Facebook land so I decided to draft something. (Also, I'm genuinely excited
to share the lesson.) Will wait a little bit.

**Comment by flannery-denny** [comment]
@schanzer pioneers on fall2022 branch can be pushed to the web whenever you want. Once that happens @retabak can share whenever she wants.

No rush on any of this in my opinion. The next time I'd be likely to redo my bulletin boards with something other than student work at this point is for the start of the 2022-2023 school year ;) But maybe I'd teach the lesson in June after exams if I knew about it? Defer to y'all on optimal timing for posting / how often you think it's ok to share.

**Comment by schanzer** [comment]
@flannery-denny it took me all of 10sec to update, so my part is done. @retabak , feel free to make this happen...AFTER the immediate publishing deadlines are met. :)

**Comment by retabak** [comment]
Needs to happen prior to 8/15/22
