### ISSUE TITLE
Add image credit to Pioneer Template

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#854]
Some of the archives that have given us photos have requested that we include a specific photo credit. As we discussed a while back, we need to add a spot for including it to the template.

I think it might look best if it were on the right side of the image, but I'm not even sure if that's possible.

**Comment by schanzer** [comment]
@flannery-denny I believe this is now complete. It actually _required_ one of the flex branch's CSS features to work, so I'm including it there.

Ajay Bhatt's file has a demo for how to add an image credit.

**Comment by flannery-denny** [comment]
@schanzer 
For some reason the way you've added the credit messes with the image frame. 
See how nicely Ajay Bhatt fits in the frame in the old file and how there's white space (and the frame overlaps the credit) on the new file.
[ajay-bhatt-og.pdf](https://github.com/bootstrapworld/curriculum/files/8500297/ajay-bhatt-og.pdf)
[ajay-bhatt-w-credit.pdf](https://github.com/bootstrapworld/curriculum/files/8500298/ajay-bhatt-w-credit.pdf)

**Comment by schanzer** [comment]
Wow. It doesn't look like that on my machine at all! Damn you, CSS!! I'll keep poking...

**Comment by schanzer** [comment]
@flannery-denny it's a guessing game of pixels at this point. I've added a few more. Let me know if this is enough to resolve the glitch on your machine?

**Comment by flannery-denny** [comment]
@schanzer I can read the credit now (the bottom the p on provided is cut off a little, but it's not a deal breaker) but the frame still doesn't correspond to the shape of the image like it used to.

Notice that Ajay Bhatt's right shoulder is cut off and then there is a lot of white space to the right. In the og version (see the one included above) the frame is just barely to the right of the end of his image
[ajay-bhatt.pdf](https://github.com/bootstrapworld/curriculum/files/8502585/ajay-bhatt.pdf)
.

**Comment by schanzer** [comment]
@flannery-denny Should be fixed now!

**Comment by flannery-denny** [comment]
@schanzer @retabak 
Thinking about text for the image credits for the posters. 
What do you think about the following

- Photo courtesy of xyz cartoonized using vanceai.com 

or 

- Photo courtesy of xyz processed using vanceai.com

**Comment by schanzer** [comment]
@flannery-denny I like the 1st one.

**Comment by retabak** [comment]
I do not have a strong opinion here. Either works!

**Comment by flannery-denny** [comment]
@schanzer 
I tried to put a credit on Evelyn Granville's page and, because it's not starting the box in the bottom right, it's making the poster 2 pages. To be clear, this is the text the archive requested we use.
[evelyn-granville.pdf](https://github.com/bootstrapworld/curriculum/files/8524647/evelyn-granville.pdf)

Also, I notice that the frame is now leaving white space on the left and not the right.

**Comment by schanzer** [comment]
I'm not seeing this in the asciidoc. Can you push so I can check it out?

**Comment by flannery-denny** [comment]
@schanzer The Clarence Ellis Poster works
[clarence-ellis.pdf](https://github.com/bootstrapworld/curriculum/files/8524663/clarence-ellis.pdf)

but

- The credit isn't where I would expect it to be (we'd talked about bottom right)
- I know that I worked really hard to get this text to fit exactly in the alotted space last week... and now there's lots of extra space. Something significant has changed about the formatting.
-

**Comment by schanzer** [comment]
@flannery-denny I give up. We need to put this text someplace else. Vertical orientation is a mess in CSS, and so far this one request has eaten up _two full days_ of my time. Can you think about another place you'd like to see this text?

**Comment by schanzer** [comment]
@flannery-denny aaaaand of course as soon as I write that I have ONE MORE thing I want to try. Which seems to have fixed it. :) But please understand how incredibly brittle this is to do in CSS. If we need to make this more complex, I suggest we abandon the vertical stuff and try something simpler.

As for Clarence Ellis having extra space -- that's because we need to preserve an extra line's worth to handle Very Long Credits.

**Comment by flannery-denny** [comment]
I’m not attached to the credits going there. It was an idea. I don’t have another right now.

I can’t imagine any credit being longer than the text we had to write for Evelyn Granville.

Flannery

**Comment by schanzer** [comment]
@flannery-denny ok, if you're happen with it as it is now, feel free to close.

**Comment by flannery-denny** [comment]
@schanzer. Frames look great. Credits look great. Thanks.

Text paragraph still seems to be smaller font than it used to be and we're missing a space between the pioneer's title and the body paragraph. I'm not sure how we lost it. If changing the font size is hard, I guess just add the space back in. I know that Clarence Ellis and Ajay Bhatt were maxing out the available space before the footer until the credit got added in.

**Comment by schanzer** [comment]
@flannery-denny the font size has not changed since January. I've added some space between the title and body paragraph.

**Comment by flannery-denny** [comment]
@schanzer where would I find the document that determines the spacing of these posters?
