### ISSUE TITLE
fix "Also available in" message on lessons unique to CODAP

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#855]
These CODAP lessons are their own entities, and were not created with <ifproglang>. 
- codap-disaplying-categorical-data
- codap-simple-data-types
- codap-transformers-1
- codap-transformers-2

Either we need to delete "Also available in" or edit it / populate it somehow? Don't know the best solution.

**Comment by schanzer** [comment]
@ds26gte take a look?

**Comment by ds26gte** [comment]
Fixed in b9c925735

**Comment by schanzer** [comment]
@ds26gte this seems to have introduced another bug — now force-building data science results in a pathway narrative page that’s missing all the lesson summaries, and it appears to insert some whitespace in the lesson links, as well
