### ISSUE TITLE
Fix spacing on row and function definitions - probably a bigger fix than just this page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#857]
There's something funky going on in the spacing between #6 and 7 in both the pdf and html versions of this page

**Comment by schanzer** [comment]
@flannery-denny fixed

**Comment by flannery-denny** [comment]
@schanzer still not building correctly for me and I have deleted the lesson and rebuilt. sure you pushed?

**Comment by schanzer** [comment]
ack! Sorry about that. done.
