### ISSUE TITLE
there's gotta be a better way --- what's on your mind

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#858]
We have a gazillion of these pages and when I just looked at them, they all had a different number of blank lines on them! Is there really no way to just have a single one of these that all of the lessons pull from?

**Comment by schanzer** [comment]
@ds26gte this seems like a job for a directive! Can we get @page-of-lines to generate the markup on `lessons/table-methods/pages/whats-on-your-mind`? Then @flannery-denny and I standardize all those pages.

**Comment by ds26gte** [comment]
04a8ec31c

**Comment by ds26gte** [comment]
Existing blank-line pages use either `@span{.blankline}{}` or `@fitb{}{}` -- the latter with some additional CSS.  I've chosen the former to expand out the `@page-of-lines` for now.
