### ISSUE TITLE
Kill "all the lessons" page

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#860]
I clicked this out of curiosity - https://bootstrapworld.org/materials/latest/en-us/courses/data-science/.pathway-lessons.shtml - and a million sidebars appear, one on top of the other. I can't minimize. The formatting looks funny, too. Maybe we turn off the sidebar on this page? Or make it so this page isn't an option if it's gonna look like this? (Do people need / use this page? Seems unnecessary, but I could be wrong.)

<img width="960" alt="image" src="https://user-images.githubusercontent.com/87144723/164243141-45a09b4d-92f0-433e-94ec-e8560e79a9ec.png">

**Comment by ds26gte** [comment]
9c8fcc56f
