### ISSUE TITLE
Data Cycle worksheet for CODAP (Grouped Samples lesson)

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#861]
This should work for CODAP with a few adjustments:

In general, CODAP refers to rows as "cases" and columns as "attributes." Is it possible to use those terms (or include them) in the CODAP version? 

Analyze:
- [x] "If you only need some rows, define your filter function here" should say, "If you only need some rows, write an expression for your Filter Transformer here."
- [x] For build - "If you need to make a new column, write an expression for your Build Attribute Transformer here."
- [x] Let's add the Transform Transformer? "If you need to transform a column, write an expression for your Transform Attribute Transformer here."
- [x] Delete the row that says, "write the code that will make the table or display that you want."

**Comment by retabak** [comment]
Looks good! I'd close except I still can't see the icons? (I realize this was not in the original issue, sorry.)
<img width="623" alt="image" src="https://user-images.githubusercontent.com/87144723/164491811-3d77b1e3-cd71-481d-a305-fd8b604d0a82.png">

**Comment by schanzer** [comment]
@retabak yup, not part of the issue. closing.
