### ISSUE TITLE
CODAP DR tweaks

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#863]
Some thoughts:

- [x] Where I've highlighted pink, we need a capital T
- [x] The actual Transformer names are "Transform Attribute" and "Build Attribute". Should we include the word "attribute"? Just a thought.
- [x] Can we add titles to the example tables? I'm thinking where it's yellow, we could say "original dataset," and where it's blue, we could say, "modified copy of the dataset" or "transformed dataset"? Seems like it might clear things up a bit.
- [x] The Transformers no longer use the word "Formula" on them, just expression. I'm not sure what we want to call this entire section, but I don't think Formula is the right word. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/87144723/164450488-387d36c5-5281-4e7c-8084-d4889f2280b6.png">

**Comment by schanzer** [comment]
@retabak I worry about the wordiness of the page, and I also want to minimize the Attribute/Column split as much as possible. Keeping ourselves disciplined about using language-neutral words _now_ means less work merging the two _later_. If you feel strongly about this I can be convinced, but I think we should only do it if it means a lot less confusion for kids.

Let me know what you think?

**Comment by retabak** [comment]
These changes look good. I don't feel compelled to convince you about the others, except...

I noticed we have "domain" and "range" in lower-case. They should be capitalized, right? 

Once that's taken care of, this can be closed.

**Comment by schanzer** [comment]
done! closing.
