### ISSUE TITLE
@description should not appear on the page where it is found in the asciidoc

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#868]
The pages that describe projects begin with @description. These are supposed to appear as the description of the project on the teacher resources page, not on the page describing the individual projects.

**Comment by schanzer** [comment]
@flannery-denny is this it such bad thing to make the descriptions visible? 

If we want to hide them, we'll need to ask Dorai to label them with a classname, so that I can hide it with CSS. It's not hard, but it adds complexity and I want to make absolutely sure this is what we want.

**Comment by schanzer** [comment]
@flannery-denny removed descriptions from non-lesson pages. OK to close?

**Comment by flannery-denny** [comment]
thanks
