### ISSUE TITLE
Instruction Box Audit

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#869]
- [ ] All `[.lesson-instruction]` boxes should be in student-facing voice
- [ ] Strive to use fewer, larger boxes instead of many small ones.
- [ ] If a question is included, make sure there's an answer

----------------------------------------------------------
I got some feedback from @schanzer that I'm still using [.lesson-instruction] boxes incorrectly. I decided to look through our lessons to find clarity... and I became even more confused! We aren't very consistent with our conventions. Or, if we are, the guiding principles are not obvious and ought to be tweaked to help teachers navigate our stuff!

Who are these boxes _directed_ to? Are these instructions supposed to be directed to the teacher (i.e. "Have students..." or "ask a volunteer...") or are they things that can be read aloud (verbatim), directed to the students (i.e. "Open your workbook" and "what do you get when...?"). I prefer the latter but we have a mix of both.

@schanzer - you told me these blocks are instructions for students to carry out, and NOT places to teach new concepts or information... yet I often see teaching happening in these blocks. 

Also curious why this Investigate is in a box but not this Launch (below)?
<img width="449" alt="image" src="https://user-images.githubusercontent.com/87144723/165355898-eee36291-b3ed-4561-920a-f38b7b2e24e0.png">

What about role play? The role play activity in The Distance Formula lesson goes in an instruction box, but the role play activty in Table Methods does not. (Do we have enough role play activities for it to merit its own little icon?! I'm not sure.)

Sometimes, an entire section won't have any lesson instruction boxes. That seems off to me.

"Synthesize" sections seem to be different every time they appear. Often, there is a list of reflection questions. However, sometimes they're bulleted, sometimes they're numbered. Sometimes they're in a lesson instruction box, and sometimes not.

**Comment by retabak** [comment]
I can work on this issue, but have a few questions about things to review:
- Should the synthesize section go in a `[.lesson-instruction]`?  Seems like when we've just go a bulleted list of synthesis questions, that it would make sense to use the box. 
- Are there instances when student-facing questions do _not_ belong in a `[.lesson-instruction]` box ?
- Should "do this worksheet" always go in a a `[.lesson-instruction]` box?

**Comment by retabak** [comment]
Some thoughts on [.lesson-point], which we're using inconsistently....

I think the formatting works best when we're hammering home a concept that has been explaind in some detail. It ought to summarize the big idea we were trying to convey within a longer chunk of text.

In [histograms2](https://bootstrapworld.org/materials/fall2022/en-us/lessons/histograms2/index.shtml?pathway=data-science) and elsewhere, however, the lesson points function as section headers. Some examples of 'section header' lesson points include: "Skewed left, or low outliers" and "Skewed right, or high outliers." These are not even complete sentence therefore cannot be lesson points (unless I'm missing something?). In instances such as these, I think a numbered list would be more appropriate? What do you think @schanzer @flannery-denny ? (I'm going to make that change for now - but if that doesn't feel right, let me know!)

The [.lesson-point] formatting is often used to highlight a new topic - with the text inside serving as a topic sentence. Intuitively, I think the [.lesson-point] formatting works better to wrap up a paragraph or a section.

**Comment by flannery-denny** [comment]
@retabak agreed

**Comment by schanzer** [comment]
@retabak agreed. Please open a separate git issue to track this.

**Comment by retabak** [comment]
Will do! 
I've definitely fixed a few instances of it as I was going through the algebra pathway, but I'm seeing these issues much more often in data science. (Not sure why that is.)
