### ISSUE TITLE
Supplemental exercises formatting issues

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#87]
A list of things: Formatting issues are in both WeScheme and Pyret, syntax issues are Pyret-specific:

- [x] In `complete-coe-from-arith1` problem 4, it looks like it says "4x - 2" instead of 4 x -2.  Maybe just switch the 4 and the -2 so it looks less confusing? 
- [x] In `arith-to-coe1`, `arith-to-coe2`, `arith-to-coe3`, when printed, spaces should be large enough for student work but small enough to all fit on one page - See https://www.bootstrapworld.org/materials/fall2019/courses/algebra/en-us/units/unit1/exercises/Order-of-Operations/arith-to-coe1.html for reference
- [x] In `complete-code-from-coe1`, there is some weirdness happening with commas in problems 2 and 3
- [x] In `many-types-coe-to-code1` problem 3, `sqrt` should be `num-sqrt`
- [x] In `many-types-coe-to-code2` answers 4d, missing parentheses
- [x] In `id-expr-pieces2`, function names should be in monospace font and datatypes should be capitalized
- [x] In `match-contracts-exprs1`, everything is still in Racket syntax
- [x] In `match-examples-functions1`, the example and function blocks should be indented/left-aligned
- [x] In `create-contracts-examples1` and `create-contracts-examples2`, contract line needs two colons and no comment, and datatypes should be capitalized
- [x] In `examples-same-contracts1`, contract line needs two colons and no comment, datatypes should be capitalized
- [x] In `examples-same-contracts2`, contract line needs two colons and no comment, datatypes should be capitalized, answers are showing up on the original, answers are overtyping on the answers page
- [x] In `boolean-coe-to-code1`, `string=?` should be changed to `string-equal` or just `==`
- [x] In `boolean-coe-to-code2`, `string=?` should be changed to `string-equal` or `==`.  `=` should be `==`, some `<=` are showing up as arrows
- [x] Under Inequalities 2, remove links to `boolean-coe-to-code1` and `boolean-coe-to-code2`

**Comment by BootstrapJen** [comment]
On `create-contract-examples1`, the answer key looks good but the original still has the Racket formatting.

<img width="843" alt="Screen Shot 2019-11-04 at 10 10 47 AM" src="https://user-images.githubusercontent.com/43153234/68136750-682c1580-feeb-11e9-9172-cfd4a8112bc2.png">

**Comment by schanzer** [comment]
@BootstrapJen can you confirm these are fixed, and close this issue?
