### ISSUE TITLE
Algebra workbook fixes

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#870]
All of Flannery's noticings are either committed to this issue by page number or listed below

- [x] I am curious what @retabak and @schanzer think about the Computing Needs All Voices pages being the first things in the workbook. I'm excited it's in the book, ok with it being here, and also wondered about other placements.

**Things probably best tackled by @schanzer** 
- [x] page 7 & 8 have the same game image... At the very least we should make both images appear at the same size and in the same place on the page.  But I'm wondering if it would be better if one of them had a slightly different game image or if we maybe we should even fit both sets of questions about the image on the same page? 
- [x] page 9 why do we want them to label all four corners of their brainstorming sketch with coordinates? if we still do, we should specify the length and width of the rectangle so that they can figure out what coordinates to use.
- [x] page 22 Why are we including this frayer model. In general, I like them and found them to be quite valuable in my classroom. But what do we realistically expect students to supply us with as non examples for Domain and Range. I have no idea!
- [x] page 23 Does it make sense to keep the word **type** lowercase?
- [x] page 45 css fix? In number 3 the first example has very little space for writing
- [x] page 60 css fix? the font is SO tiny! and there's plenty of more room...
- [x] page 88 css fix? @fitb lines on are very small

We made a decision to use **if else**  rather than **ask** in the core piecewise functions lesson.  As a result, we need to change the following pages. Perhaps Flannery will find headspace to remember how to make these fixes? Turning toward feedback on other things for now.
- [x] page 97  modify pyret notes accordingly
- [x] page 101 and 102. I'm pretty sure we decided to make alice's restaurant optional. Either way, it currently uses ask rather than if-else.
- [x] page 103 update-player should also use if-else
- [x] page 105 line-length should also use if-else

**landscape page orientation** - currently the bottoms of all of the pages are meeting the seam. It is much easier to write when the bottoms of the pages are at the edge of the page. If you look at the contracts pages, the ideal would be the opposite. You weren't able to do this last year. Instead you made all of the pages have the bottom to the right. This is imperfect, but better than all of them being in the middle. pages that this should resolve:
- [x] 17
- [x] 33 
- [x] 37
- [x] 59
- [x] 81
- [x] 82
- [x] 109
- [x] contracts

**Comment by retabak** [comment]
Re: the pioneers page - I like it being the first page! Curious what other placements you were considering, @flannery-denny ?

I do have one issue with the page: Ada Lovelace looks kinda lonely on that last line, all by herself. It feels a little like we ran out of pioneers, given that we didn't fill in the entire last row (or the entire page). Is there any way to make the pioneers take up all of the available space? Or could we do something creative/ interesting / inspiring with the blank space?

**Comment by flannery-denny** [comment]
In response to Rachel's question about the pioneers... what if

**Comment by flannery-denny** [comment]
@retabak Would this scratch your itch?
[computing-pioneers.pdf](https://github.com/bootstrapworld/curriculum/files/8573448/computing-pioneers.pdf)

**Comment by flannery-denny** [comment]
@retabak that page is pretty complicated because it has a different number of images on each line of the array than the webpage does, so I've had to take it what it looks like in both versions into consideration for the order of the faces. 

If you think this looks any better, lmk. 
[computing-pioneers.pdf](https://github.com/bootstrapworld/curriculum/files/8573555/computing-pioneers.pdf)

Otherwise I think it's probably the best we can do for now, but we've got a running list of more pioneers to write up some day :)

**Comment by retabak** [comment]
Nah, I don't think the other version is any better. Looks good to me, more
incentive to add more pioneers!

**Comment by flannery-denny** [comment]
@retabak @schanzer I'm done with my algebra workbook fixes. Made a big list of things that I know still need to be dealt with above. Probably the most efficient path forward is for you to take your notes on the hard copy you have and see whether there's a commit for the page number you want to see fixed. Click on it to see whether what I fixed addresses your concern. If it doesn't, either fix it yourself or add it to the list above.

**Comment by flannery-denny** [comment]
@schanzer this workbook looks better than ever & part of that is due to your @fitb work

**Comment by retabak** [comment]
Wow! You were thorough! I'll definitely look at the hard copy first. Good
tip.

**Comment by schanzer** [comment]
@flannery-denny pushed edits that resolve these issues.

- non-examples for Domain and Range? `4`, `"hello"`, and `true`. 
- I think we should keep the game image the same on pages 7+8.
- I'll work on the landscape pages over the weekend. This one is tricky.

@ds26gte can you modify your sexp->pyret converter to generate if/then/else, instead of `ask`?

**Comment by flannery-denny** [comment]
@schanzer having thought more about your request to @ds26gte to update the sexp to use if else, I think it probably makes sense to make the change if possible, since this is and will continue to be the predominant use-case and it means we don't need to make a bunch more pyret & wescheme folders. We can make the one workbook page we need to build the other way for the piecewise functions lesson without sexp.

**Comment by schanzer** [comment]
@flannery-denny I'm not sure I totally understand your request about the landscape pages. I _think_ you're suggesting that I swap the rotation for left and right pages, so that they face in opposite directions?

**Comment by schanzer** [comment]
@retabak All of the issues Flannery left for me have been resolved. If you see additional ones, make a checkbox list and I'll work through it. If you see NO additional issues, feel free to close this!

**Comment by retabak** [comment]
@schanzer : p. 105 - the coordinates for the bird have the little squiggle underlines beneath them. (Microsoft Word was trying to warn you about a misspelling or grammatical error.)

Also - I've finished looking through the workbook. About to start making fixes. Will ping you once I'm done so that the workbook printing order can be placed.

**Comment by retabak** [comment]
I do believe that the code on #2 of workbook page 98 needs to be written in the code font - but due to @ifproglang directives, weird things were happening when I tried to fix it. Sadly, I need to logoff now! Maybe @schanzer or @flannery-denny can fix? 

Aside from that, I am DONE! @flannery-denny was suuuuuper meticulous. I was very pleased with myself whenever (very rarely) I caught something that she missed.

**Comment by schanzer** [comment]
WOOHOO! 

@retabak you may want to look at my latest commit to see how I fixed page 98.

Anyway, I'm closing this and printing the next round of books!
