### ISSUE TITLE
Modifying the way that pages with subheadings print to pdf

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#871]
As we discussed yesterday, if we use === or == in an asciidoc, they show up as dark black bars across the page in print. My inclination was to stop using === and == on pages that get printed. But you suggested we could modify the printed output... and I'm looking at page 19 in the algebra workbook, which has 4 huge dark black rectangles for titles. On the opposing page are two tables with greyed headers.  My guess is that it would be an easy change to switch from the print formatting of the headings on the left to the print formatting of the headings on the right and it would make a number of our project description pages look a lot better!

**Comment by schanzer** [comment]
@flannery-denny Ready for review

**Comment by flannery-denny** [comment]
Thanks! It's definitely better. Can we get rid of the black line at the top of the grey box?
![Screen Shot 2022-04-28 at 8 02 19 AM](https://user-images.githubusercontent.com/66691020/165758274-6ce1eaed-285c-4739-b114-cfdd26d3a4dd.png)

**Comment by schanzer** [comment]
@flannery-denny done!

**Comment by schanzer** [comment]
@flannery-denny ok to close?

**Comment by flannery-denny** [comment]
Much better.
