### ISSUE TITLE
codap build logic may need tweaking

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#874]
When I `./build-pathway --proglang codap data-science-codap` I get some lesson folders that don't make much sense.

For example, in `codap-simple-data-types-codap` I get everything that belongs. But there's a second lesson folder that gets built without a lesson plan titled `codap-simple-data-types`. It should not be being built.

**Comment by schanzer** [comment]
@ds26gte at one point ALL lessons built for Pyret as an invariant. that would explain these folders.

Is the ingvariance still true?

**Comment by schanzer** [comment]
@flannery-denny the non-codap version of the lesson is NOT being built - the files are copied, but not processed in any way. After talking with @ds26gte I believe this is an invariant of the build system.
