### ISSUE TITLE
Make Markdown Files for Slides for Algebra

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#875]
Absolutely Critical for PD:

- [x] order-of-operations
- [x] simple-data-types
- [x] contracts
- [x] function-composition
- [x] defining-values
- [x] functions-examples-definitions  
- [x] functions-dr
- [x] numbers-inside-video-games
- [x] functions-for-character-animation _@schanzer didn't reply to whether or not the role play was important - leaving it out, as it was also left out in 2021_
- [x] inequalities1-simple 
- [x] inequalities2-compound
- [x] inequalities3-sam 
- [x] problem-decomposition
- [x] piecewise-functions-conditionals
- [x] player-animation _This draft file will need to be updated once we make the posn page and update the lesson plan accordingly_
- [x] distance-formula
- [x] inequalities-collision

Important for PD:
- [x] functions-make-life-easier
- [x] functions-vertical-line-test
- [x] function-definition-linear
- [x] flags

Not essential for PD
- [ ] computing-needs-all-voices
- [ ] coordinates
- [ ] making-game-images
- [ ] functions-collaboration _(FYI - I find it highly unlikely that anyone who doesn't try the DR in PD will use it in their classroom...)_
- [ ] surface-area-rect-prism
- [ ] function-notation
- [ ] functions-can-be-linear

**Comment by flannery-denny** [comment]
@ds26gte please check out my last commit. That deck isn't building because of a contract error. Not sure what I need to do differently with @show. Please lmk so I can apply it moving forward.

**Comment by flannery-denny** [comment]
@schanzer The [fall2021 slide deck for Character Animation](https://docs.google.com/presentation/d/1P5P4M9MJ51XaIu9Y5tY4jmdKmsfOmaX_ZXspuKboMZQ/edit) leaves out discussion of the acting activity. I have followed suit for fall2022. Feel free to add slides if you think the deck should include that activity.

**Comment by flannery-denny** [comment]
@ds26gte curious whether you have any ideas for how to get images that are included in tables to actually end up in the table, rather than just on the slide. See `inequalities3-sam` slide 6 for an example.

@schanzer curious whether this version of including the role play from the lesson makes sense to you? (see slide 6)

**Comment by schanzer** [comment]
@flannery-denny the role play for sam looks good.

**Comment by retabak** [comment]
For @retabak:
Check off lesson if: (1) {layout} specifications have been added; (2) have manually tweaked slides; (3) have saved in GDrive fall2022.

- [ ] order-of-operations
- [ ] simple-data-types
- [ ] contracts
- [ ] function-composition
- [ ] defining-values
- [ ] functions-examples-definitions
- [ ] functions-dr
- [ ] numbers-inside-video-games
- [ ] functions-for-character-animation _Awaiting approval from @schanzer_
- [ ] inequalities1-simple 
- [ ] inequalities2-compound
- [ ] inequalities3-sam _Awaiting approval from @schanzer_
- [ ] problem-decomposition
- [ ] piecewise-functions-conditionals
- [ ] player-animation _This draft file will need to be updated once we make the posn page and update the lesson plan accordingly_
- [ ] distance-formula
- [ ] inequalities-collision _the lesson plan links to 2 starter files that it doesn't refer to at all. If they are supposed to be part of the lesson, they'll need to be incorporated into the slides._

Important for PD:
- [ ] functions-make-life-easier
- [ ] functions-vertical-line-test
- [ ] function-definition-linear
- [ ] flags

Not essential for PD
- [ ] computing-needs-all-voices
- [ ] coordinates
- [ ] making-game-images
- [ ] functions-collaboration _(FYI - I find it highly unlikely that anyone who doesn't try the DR in PD will use it in their classroom...)_
- [ ] surface-area-rect-prism
- [ ] function-notation
- [ ] functions-can-be-linear

**Comment by schanzer** [comment]
@retabak this issue seems like a subset of #893 . Any reason not to close?

**Comment by flannery-denny** [comment]
@schanzer Issue #875 is mine. If #893 is complete you can close it.
Otherwise, please leave it for me.

**Comment by flannery-denny** [comment]
@schanzer Closing this issue. And making sure you saw my note about the fact that you put function-collaboration on the not necessary for pd list. I'm fine with that, but I find it highly unlikely that anyone who doesn't do DR telephone in pd will do it with their class.
