### ISSUE TITLE
Make a solution page for the frayer model in the contracts lesson 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#878]

**Comment by schanzer** [comment]
@flannery-denny this is complete. Close when ready

**Comment by flannery-denny** [comment]
@schanzer Thank you for making this! It clarifies some things and will definitely help teachers in supporting students! Unfortunately, the text for Facts and Characteristics of a Domain is getting cut off and I can't fix it for you, given the way this file was generated.
