### ISSUE TITLE
Add solutions to Numbers Inside Video Games Discussion

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#879]
Please add the answers you would expect to the following questions in the lesson plan.

- If the x- and y-coordinates are each numbers, how many numbers does it take to represent a single frame of the video game?
- How are those numbers changing - or _varying_ - as the game plays? When do they increase? Decrease?
- How many numbers would we need if the dog could also move up and down?
- How many numbers would we need to have a two-player game?
- How many numbers would we need if the entire game was in 3d?
- How many numbers would we need to make a modern game?

**Comment by schanzer** [comment]
@flannery-denny I believe this is complete
