### ISSUE TITLE
Buggy Design Recipe formatting issues

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#88]
- [x] Some of the Buggy Design Recipes are displaying some extra lines:

<img width="511" alt="Screen Shot 2019-10-31 at 4 25 58 PM" src="https://user-images.githubusercontent.com/43153234/67987496-8ea43500-fbfb-11e9-9bc4-d1da023ab6f2.png">

- [x] The contracts for WeScheme shouldn't have commas in the Domain:
<img width="589" alt="Screen Shot 2019-10-31 at 4 30 11 PM" src="https://user-images.githubusercontent.com/43153234/67987597-db880b80-fbfb-11e9-93db-6b7feaca4e56.png">

- [x] The contracts for Pyret should have no comment and double colon

- [x] The datatypes should be capitalized

**Comment by ds26gte** [comment]
(BTW, the buggy recipes are all in WeScheme.)

**Comment by schanzer** [comment]
Safe to close?

**Comment by ds26gte** [comment]
Yes, all subboxes fixed
