### ISSUE TITLE
piecewise conditional DR page upgrade

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#880]
We have just switched the default version of conditionals in pyret from **ask** to **if-else**.
Code is doing a great job of this. Thanks!

On the DR pages, I am seeing:
```
fun
______
______
______
end
end
```

I would expect to see:
```
fun
if _________: __________
else if _________: _________
else if _________: __________
else if _________: _________
else: _________
end
end
```

Please make it so!

**Comment by schanzer** [comment]
@flannery-denny is this ok to close?
