### ISSUE TITLE
Figure out where to add line-length into the distance lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#881]
Somehow, `line-length` is printing in the workbook but there is no reference to it from the lesson plan. Not sure exactly where it should go, but we need to figure it out.

**Comment by schanzer** [comment]
@flannery-denny since we already give them the code, the DR is merely an optional place to practice the DR. I've removed it from the WB and made it optional, and clarified its use in the lesson. Close if you're happy. :)

**Comment by flannery-denny** [comment]
@schanzer - In looking at the lesson I see that it ends with the following

> Have students practice using the Design Recipe to solve line-length on their own, and/or modify it to make use of the absolute value function: num-abs.

Seems like the perfect place for the `line-length-dr`!

Adding it now
