### ISSUE TITLE
Decide how we want to title DR Pages

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#883]
Currently, if there is a single DR problem on the page a `Word Problem: _____` title is autogenerated. 

When we have two problems on the page, we are naming the pages ourselves.

Many pages have titles like:  `The Design Recipe (Geometry - Circles)`

Many other pages have titles like:  `Danger and Target Movement`

Are we ok with this? Do we want to be more consistent?

I'm pretty sure that @schanzer told me that research says we have to use Design Recipe in the title?

**Comment by schanzer** [comment]
@flannery-denny the research says it's helpful to put "Word Problem" on them as often as possible. 

I'm totally OK with things being the way they are.
