### ISSUE TITLE
@starterfile{} for the programming environments

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#884]
The `@starterfile` directive has allowed us to get rid of a lot of `@ifproglang` directives.

The current infrastructure allows us to give one name that links to two different files, depending on the programming language

```
("bc" "bc Starter File"
    ("pyret" "https://code.pyret.org/editor#share=1_FBRxM-CzjOaCEj7XCe7J9zk27fd11l0")
    ("wescheme" "https://www.wescheme.org/openEditor?publicId=2eMcXop5hZ")
    )
```
This is USUALLY what we want!

But in the case of linking to the programming environments, we want **the displayed text to vary** with the programming language, 

Instead of this...
```
("editor" "the programming environment"
    ("pyret" "https://code.pyret.org")
    ("wescheme" "https://www.wescheme.org")
```
We are looking for the option to provide more info in the file. Perhaps something like this?

```
("editor" ""
    ("pyret" "https://code.pyret.org)" "code.pyret.org (CPO)")
    ("wescheme" "https://www.wescheme.org") "WeScheme")
```

Possible?

**Comment by flannery-denny** [comment]
such a smart solution :) love it!

**Comment by schanzer** [comment]
@flannery-denny ok to close?

**Comment by flannery-denny** [comment]
@schanzer @ds26gte 
It does everything I asked for it to and will the work that has been done will offer valuable flexibiliy for other applications... but I didn't think of everything we needed.

**We do not want CPO and WeScheme to be autoincluded in the materials** list the way that _all of the other starter files_ are. 

- [ ] Is there a way to put `@starter-file{editor}` on a list that won't get auto-included in the materials section

**Comment by ds26gte** [comment]
There are two ways to go about this, slightly different in their intent: 

- You can have the starter-file for `editor` always be excluded from the autogen'd material links, or 

- You can have an optional argument when you call `@starter-file` on `editor` in a particular lesson file that excludes it from the autogen'd material links for that lesson plan -- i.e., you have the option to not use this opt arg in some other lesson plan, and this would do the default action of including the `editor` link in its material links.

I'm leaning toward the second option, as it gives the author more control -- although forcing her to explicitly specify when she wants the link disallowed.

**Comment by ds26gte** [comment]
First option chosen after discussion. Feature pushed in commit 306a8536c
