### ISSUE TITLE
Review Collision Lesson 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#885]
- [x] The collisions lesson repeatedly hot-links back to problem-decomposition. We don't do this in most of our lessons. I am curious as to why the decision was made to include all of these links. 
- [x] The materials section of the collision lesson includes two starter files. Neither of them is referred to in the lesson plan. How do you imagine teachers interacting with them? If we don't provide some direction, they probably don't belong in the materials section.

**Comment by schanzer** [comment]
If you want to remove the links, that's fine. But we need to make a big deal out of explicitly pointing out that we are revisiting the problem decomposition concept from the earlier lesson.

This is about far more than just listing a prerequisite

**Comment by flannery-denny** [comment]
There's already an entire section of the lesson plan titled Problem Decomposition Returns - it's not subtle.

**Comment by flannery-denny** [comment]
And it is not currently a prerequisite. Do you think it should be?

**Comment by flannery-denny** [comment]
I'm going to leave it to you to have a look and make decisions when you have a chance. I honestly think that's the best way. But, please don't do it until you actually have space to read the words in the lesson. To my eye, the term problem decomposition would be more effective if used half as much.

**Comment by flannery-denny** [comment]
@schanzer I added a second bullet to this issue because I realized that the starter files listed in the file are not being utilized in the lesson. That might actually be an issue that we need to resolve prior to pd.

**Comment by schanzer** [comment]
@flannery-denny done. It looks like the starter file links are a relic from when the distance lesson included both the calculation of distance and the check for whether it's enough for a collision. I remove those, along with links to prior lessons.

**Comment by flannery-denny** [comment]
@schanzer 

- I've added those starter files to the Distance Lesson, where they would be helpful to teachers. 
- In looking at that lesson I see that it ends with the following

> Have students practice using the Design Recipe to solve line-length on their own, and/or modify it to make use of the absolute value function: num-abs.

Seems like the perfect place for the `line-length-dr`!

I was going to move it, but you've deleted it from the repo and I don't know how to bring it back without recreating it. Please link it to that last sentence in the Distance lesson.

- I noticed some other overlap between the Distance and Collisions lessons and cleaned that up some. Check out the commit if you're curious.
