### ISSUE TITLE
Distance Lesson Overhaul - Feedback Request and Followup Items 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#887]
- When I revisited making slides for this lesson today, which I'd already attempted once this week, I still couldn't make sense of the sequencing of the lesson. 
- I remembered that I was also overwhelmed by the lesson plan last year, when I finished making all of those new pages and had you add my work to the lesson plan instead of dealing with it.
- I decided that if I got overwhelmed by the lesson on three separate occasions, it was time to try to make sense of it and give it an overhaul.

I'm not sure that I've really nailed it, but I am sure that it's an improvement!

- [x]  Feel free to edit as much as you see fit and lmk when you approve of its state enough for me to turn to making slides. I am aware that I have done some experimental things with formatting in an attempt to sort it out.

**The lesson still has the following issues that need to be resolved.**

- [x] [This starterfile](https://code.pyret.org/editor#share=1y1eWn1YyDDqilj0MFqEpMy4egVh-G81W) uses both `if-else` and `ask`. I've never noticed before because I've only clicked run and looked at the game... but today I read the code... and I don't think it's a good model for the teachers who access it from our teacher resources section looking for a reference. I looked for it in [this folder](https://drive.google.com/drive/folders/1BUTF8d9eAXWn7iymM0OL2XG-W5m_E5z_?usp=sharing) and fixed a file, but ended up fixing a file that had never been published before and got overwhelmed by not understanding the thinking behind the existence of those four different files or know which, if any of them, are actually being linked to from our materials. 
- [x] Double check that the sample game with distance made visible linked to from`starter-files.rkt` is also consistent in using if else.
- [x] I feel tempted to make a `line-length-explore.adoc` file with the questions from the first investigate section, because that's the advice I always give when I read other people's lesson plans. Think that's a good idea?
- [x] There's a moment in the lesson where I just can't imagine moving forward without doing some Pythagorean Theorem Practice so I included a link to a page from Kuta, but I could (and have) definitely made better versions myself. Here's one from my files. Some formatting is a little imperfect as a result of changing versions of Word, but maybe it's still better than linking to Kuta as the opt-printable-exercise we offer up? Or maybe I should put it on my to do list to make something shorter and tailored more specifically to this moment in the lesson?
[Pythag practice 1.pdf](https://github.com/bootstrapworld/curriculum/files/8646101/Pythag.practice.1.pdf)

**Comment by schanzer** [comment]
@flannery-denny did we give up on the pythagorean triangles? Now we're assuming kids already know the theorem before they take the lesson?

**Comment by flannery-denny** [comment]
@schanzer I am happy to discuss. And am available to chat. Try me anytime.

I have not given up on anything. I have spent an entire day trying to connect the threads in this lesson into something that is clearer. 

If you haven't built and read the revised lesson, please do so.

There are lots and lots of triangles and they are powerful, but this lesson is not currently (and has never yet to date) been written as an introduction to the Pythagorean Theorem. 

I think we are doing a disservice to teachers not to let them know that it would be helpful for teaching the many complicated things that are happening in these 55 minutes if their students had already worked with the Pythagorean Theorem.

Even if you don't want to communicate that important information to teachers, that comment at the beginning of the lesson has very little to do with the work that I have put into this issue today.

I look forward to your feedback on the meat of what has happened in this lesson and your help in resolving the issues I have flagged. Thanks.

**Comment by schanzer** [comment]
@flannery-denny 

- Re: starter files questions - At this point, I think `ask` shouldn't be used at all. You'll want to make a copy of the starter file in Fall2022, make sure it uses `if/then/else`, then re-publish and update starter-files.rkt.
- Re: line-length: I think a separate wbpage for `line-length` could be helpful, but it should be optional-only if you make it. A TON of teachers really skip/hand-wave this function, so it shouldn't take up printed wb space.
- Re: pythagorean theorem practice - I'd put this in as an optional page, since your avg math teacher is likely to have a library of practice problems like this already.

Perhaps the best course of action is to create an issue with a checklist for post-print todos, and add it to a June or July milestone. We can add all the optional pages to it, since they're (a) important but also (b) not as important as finalizing the print issues?

**Comment by schanzer** [comment]
I've updated all the starter files and cleaned up a merge issue that was wreaking havoc with the lesson plan. All that remains now is the optional files you wanted to add, so I'm shifting this over to the Fall2022 milestone

**Comment by flannery-denny** [comment]
@schanzer 
All that's left to do is decide whether line-length explore belongs in the workbook (I think it probably makes most sense that way) or as an opt-printable exercise.

If it's going in the workbook, we need to change the wording of the sentence in the lesson plan, change the link type and add it to workbook-pages.txt. 

If not, the issue is ready to close.

**Comment by schanzer** [comment]
@flannery-denny Given that exploring line-length is not essential to completing the lesson (and that many Alg 1 teachers don't cover piecewise functions at all!), I think this is best kept out of the workbook.
