### ISSUE TITLE
Data Science review

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#888]
Adding in the "exploration paper" was a revelation, which opened up a LOT of opportunities for re-organization. Notable changes:

- Almost all of the display lessons (bar and pie, histogram, box, and scatter) are now introduced before students choose their own, AND before they encounter the Design Recipe. This allows teachers who want the least amount of programming to go a lot farther -- which was a major request from middle school and non-STEM teachers.
- Data Cycles are used as scaffolding throughout, and the back of the book contains a number of blanks
- Lots of changes between displaying-categorical-data and displays-and-lookups -- these two had gotten tangled together with the addition of the data cycle, and this is now resolved
- Now that we're using more core lessons to build up function definition, I removed the function definition review from the start of histograms2
- `.blankline` -> `@fitb`

Given the amount of reshuffling, this really needs a read-through with fresh eyes. For those of us whose computers take a long time to generate PDFs, I've uploaded a copy of the workbook here.

[workbook.pdf](https://github.com/bootstrapworld/curriculum/files/8647732/workbook.pdf)

Changes I'm already seeing, which need to be made:

- [x] split up displays-and-lookups, move lookups for pre-DR-intro
- [x] rename `displaying-categorical-data` to `bar-and-pie-charts` (adjust alignments accordingly)
- [x] create notes pages for data-cycle and data-collection
- [x] move my-dataset pages back into earlier lessons
- [x] create a project description for exploration paper
- [x] create a project description for research paper (#737 , #688  )

**General Question re: line spacing:** 
Why did the spacing on the what's on your mind @fitb (eg p44) end up bigger than the spacing on the other pages (eg.p45).  Which is the minimum height that I measured for you? 
- [x] Confirm that neither ended up smaller than the minimum.

From the workbook pdf (using pdf page not wkbk page number)
- [x] p9 quantitative or qualitative -  It might be helpful to add the definitions to this page. There's plenty of room
- [x] p10 questions and column desciptions -why are 2 of the lines filled in? Is this still the best title for this page?
- [x] p19 using contracts - Let's give a little more vertical space to the 2 questions that ask **What changes with the first Number**
- [x] p24 bar & pie chart - notice & wonder make what do you notice box extend to bottom of page
- [x] p29 Which Question Type? Does hp stand for something in Pokemon that could be written differently for those of who don't know anything about the game?
- [x] p30 Question Type - would be best to explain what the 3 question types are on this page (there's a lot more room on page 31 if you can' figure out how to put the explanation on p30... and it could go on the notes page if need be)
- [x] p32 Data Displays - Suggest encouraging them to test the code to make sure it works.
- [x] p33 confirm we are still using animal a and animal b 
- [x] p37 I suggest we expand this notes section to include some reference images: bar chart v histogram. skew L / skew R. the foot
- [x] p38 do we want to put titles on the two displays? "Bar Chart" "Histogram"
- [x] p41 is missing
- [x] p44 is missing
- [x] p46 Why did the spacing on the what's on your mind @fitb end up bigger than the spacing on the other pages (eg.p45).  Which is the minimum height that I measured for you? Hopefully neither ended up smaller than that.
- [x] p50 capitalize Why It's Misleading in table header for number 5
- [x] p52 is missing
- [x] p55 Computing Standard Deviation number 8 @fitb is shorter than the rest
- [x] p56 the table in number 2 is building incorrectly. Somehow count isn't ending up in the title row
- [x] p57 how is the question at the end different from the interpret data section of the Data Cycle. I'm not actually doing the page, so maybe i'm wrong, but it looks like we're asking them to do the same thing twice...
- [x] p58 is missing
- [x] p61 add 2 more fitb
- [x] p62 we have lots of room. let's make this into two separate bullets **−1 or +1 are the strongest possible negative and possible correlations.**
- [x] p63 we could probably simplify number 4, which currently reads **4 What would the scatter plot look like if there was NO relationship between the age and weeks? Draw a scatter plot with no relationship in the smaller graph on the right.**
- [x] p.65 cut **body:not(.LessonPlan) p { min-height: 2rem; }**
- [x] p66 we could add some for fitb to fill out the page
- [x] p68 can we delete the word question and get the second question on a single line
- [x] p71 and 72 bold display types so they stand out more
- [x] p75 **add to Ernie's last line**. It currently reads "but all we had to tell our actor was gt(20) ..." **and they returned triangle(20, "solid", "green")**
- [x] p89 add @fitb to 2, 3, 5,7,8
- [x] p94 in 11 the soln (Error) is bleeding through
- [x] p104 - the function `name-has-s` is revealed. Intentional?
- [x] p108 use of animalA and animalB is different than on p33.  Should we use animalC and animalD here?
- [x] p109 we could take advantage of fitb for the second on in 2.
- [x] p109 add fitb for number 7
- [x] p125 doesn't appear to be using flex to fill the line.
- [x] p128 8 ended up on the fitb instead of out in front of it for some reason
- [x] p130 Confirming this is real data because kids are definitely going to think they can draw conclusions from it
- [x] p130 suggest adding a question about in what ways the plot tricks the viewer.
- [x] p138 delete **body:not(.LessonPlan) p { min-height: 2rem; }**
- [x] p138 lines are all screwed up: 2 are short. 2 are thicker and longer than the others
WIP TIME FOR BED - Need to read words again starting at p62

**Thoughts from reading the lesson plans**
- [x] We need to figure out how to make Collaboration read as an optional lesson in DS - (ES - why? We don't do that for any of the other optional lessons) **FD - I look forward to discussing in our meeting. I'm curious what other optional lessons you are thinking about?**
- [x] In meet Pyret I think it’s important to address why we would want to import the table into Pyret instead of working with google sheets - (ES - why? I wouldn't assume that students are power-spreadsheet users, and without that assumption it's not easy to explain why) **FD - This is a common question / point of resistance in pd. Teachers are used to teaching with sheets... and people like Rachel and Nancy Cousins who find our materials without being trained rely on the information provided in lesson plans. I would also guess that most students encountering our materials have used sheets before. A pedagogy box would go a long way.**
- [x] Contracts - Let’s provide alternate wording for this section (in addition to what’s here) for teachers whose students haven’t seen function notation before. We could just as easily write this as y=x+4 and reference substitution. - (ES - in equations, the function doesn't exist and therefore has no name. There's also nothing being applied, and no expression we can reference. How would you re-write _any_ of these questions? Also note that this is not specific to DS) **FD - Let's discuss this in our meeting. This intro to contracts was written before we wrote a function notation lesson, when we assumed that math was going to support computing. However, we decided that wasn't the right model. We now assume in the function notation lesson that students probably haven't grasped function notation before and that computing will support math. We have agreed in past discussions that this should be our working model.  It is unnecessary to include this in the launch of contracts and for many will do more harm than good. Maybe we should just delete it? Maybe we should put it in an optional box?**
> Students know about Numbers, Strings, Booleans and Operators -- all of which behave just like they do in math. But what about functions? Students may remember functions from algebra: 
> 𝑓(𝑥)=𝑥+4
> * What is the name of this function? f 
> * The expression 𝑓(2) applies the function 𝑓 to the number 2. What will it evaluate to? 6 
> * What will the expression 𝑓(3) evaluate to? 7 
> * The values to which we apply a function are called its arguments. How many arguments does 𝑓 expect? 1 
- [x] What do you think about putting “Data Cycle:” in the title of all of the Data Cycle Files?
- [x] **Intro to DS** Why is it important to show the picture of zero data rows? - (ES - because tables don't need any data rows...but they do need a header row. This is an abstract idea, so I wanted to provide a concrete example to go with it)
- [x] Because we are introducing the EDITOR in SIMPLE DATATYPES, and this comes after INTRO TO CS which has students interacting with the Animals Dataset... Maybe get rid of (Anytime something on the left changes, we need to click "Run" to give Pyret the hint that something has changed! from Intro to CS)
- [x] In Intro to DS, this example doesn’t make sense to me, because we can’t build something in Pyret we don’t have the data for from the spreadsheet… _Or perhaps we want to build a column! For example, there could be a vaccination for all cats under the age of 3, and we want to add a vaccinate column that says true or false for animal_
- [x] **Displaying Categorical Data** Use subbullets for responses. - for some reason this lesson plan is missing from repository right now...
- [x] Choosing your dataset - We need a new tutorial video for the new context.
- [x] Change description of Choosing your dataset, Once we have a second teaching dataset  
 **Current Description** Students select a real world dataset to investigate for the remainder of the course.  **we could add…** If your class is planning to write the capstone research paper, this is the lesson when…    (ES - added to #889)
- [x] Measures of Center - I think this lesson should come back to the question about whether average would be a good way to decide on medicine dosages for animals. Maybe in the synthesize section of measures of spread?
> Let’s check the “41 pounds” claim and see if it’s an appropriate measure of center. Later on, you’ll have a chance to apply what you’ve learned to your own dataset, to find the best way to provide an overall summary of the data.
- [x] What happened to matching box plots and histograms?
- [x] **Scatter Plots** It seems that the data cycle expect students to build a scatterplot or two using the data cycle, but there is nowhere in this lesson that engages students with the contract for scatterplots. That seems like a big gap.  I really think this deserves a workbook page. There’s some language that could be borrowed from Custom Scatter Plots.

**Comment by flannery-denny** [comment]
@schanzer It's impressive how much better the workbook is looking.

**Comment by flannery-denny** [comment]
@schanzer what do you think of this proposal b4284454975c4f1be5ddfa2003e57a27e9a96a1b

**Comment by schanzer** [comment]
@flannery-denny proposal approved! :)

**Comment by schanzer** [comment]
@flannery-denny I've pushed draft project descriptions and rubrics, which are ready for your review. They can be found at `data-science/resources/pages/`.

**Comment by flannery-denny** [comment]
@schanzer I've pushed some fixes, but still have a lingering question. 

While it is exciting to see equity come through so forcefully in the rubric, rubric's are tricky because they are one-size-fits-all. I wonder whether it's really possible for students to earn full credit for the category quoted below from all of our datasets... think about how this applies to pokemon, for example. I'm not sure it belongs unless we 

> I explained my findings clearly and in detail. I also wrote about possible threats to validity, considering all of the different threats we learned about **in the context of diversity, bias, power, and discrimination**. I explained why (or why not) the results were enough to make a strong claim. I thought about the ethical implications of collecting this data, or how my research might be used in good or bad ways. I wrote about how I would continue this research, with more data and/or more questions.

**Comment by schanzer** [comment]
@flannery-denny  Note that Threats to Validity is broader than just considering diversity, bias, power and discrimination. A student can still do well on this rubric even if those specific issues don't apply to their dataset. But I would say that the Pokemon dataset in particular includes pokemon that are considered "legal" or "illegal" for tournament play -- and that determination is made solely by the company that owns the brand. That means they consciously skew the dataset towards characters whose various "points" fit a specific model that is almost certainly driven by profit -- a true threat to validity that stems from the role of power and diversity.

**Comment by schanzer** [comment]
@flannery-denny I've added the discussion of spreadsheets to `ds-intro`, and removed the function notation dependency from `contracts`. I've also updated the slide deck accordingly.

If these changes look good to you, feel free to go ahead and close this issue.

**Comment by flannery-denny** [comment]
@schanzer 
I was expecting to see function notation optionally included in contracts, but I honestly don't miss it in the least!

**Comment by flannery-denny** [comment]
@schanzer
The ds-intro discussion of spreadsheets you've added is way more in depth than I was expecting. 

You answered the question "Why not Spreadsheets?"

I think the question I was thinking we would answer is **"What's the advantage of loading the spreadsheet into pyret rather than just using it in google?"** or **Why are we loading a spreadsheet here?**

I thought it might go directly after this

>  After that, we see a line of code that _defines_ `shelter-sheet` to be a spreadsheet.
> 
> `shelter-sheet = load-spreadsheet("https://docs.google.com....")`
> 
> This table is loaded from Google Drive, so now Pyret can see the same spreadsheet you do. If you look carefully, you'll notice that the address listed here is the same address as the spreadsheet we just looked at! After that, we see the following code:
> 
>   # load the 'pets' sheet as a table called animals-table
>   animals-table = load-table: name, species, sex, age, fixed, legs, pounds, weeks
>     source: pets-sheet.sheet-by-name("pets", true)
>   end

Seeing what you added makes it more clear to me why you wondered why I thought it was important... Do you want to take another pass? would you like me to take a go at it? think we should have Rachel weigh in?
