### ISSUE TITLE
Reconcile Buggy Design Recipes with answer key

### ISSUE THREAD

**Issue by BootstrapJen** [bootstrapworld/curriculum#89]
- [x] Write up remaining Buggy DRs from original (found on the server at bootstrapworld.org/materials/fall2019/courses/algebra/en-us/resources/teachers/Buggy-Design-Recipes)

- [x] Make answer key for Pyret

- [x] Make answer key match up with exercises

**Comment by ds26gte** [comment]
I've made an `answer-key.adoc` that uses the 8 buggy recipes that are mentioned in the original PDF (and that I've re-created locally in adoc). The original answer key mentions 5 other buggy recipes: viz., `calc-pencils` `late-to-class?` `long-name?` `offscreen?` and `state-tax`. I don't have much context on what these should look like (let alone how to make them buggy in an instructional way).

**Comment by BootstrapJen** [comment]
I've already started on them and will push them in tomorrow morning, thanks!

**Comment by schanzer** [comment]
Status?

**Comment by BootstrapJen** [comment]
The answer key for Pyret needs some changes, I'll take care of it today.
