### ISSUE TITLE
audit lesson glossaries 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#890]
1. make sure we have used the @vocab directive to auto-include all of the most important words in the lesson's glossary
2. if a glossary is really long, confirm that we indeed think that all of the terms being defined should be highlighted in this lesson.

alg
- [x] computing-needs-all-voices
- [x] numbers-inside-video-games
- seems like this lesson should use the word variable somewhere
- [x] coordinates
- [x] order-of-operations
- suggest adding order of operations
- [x] simple-data-types
- [x] contracts
- [x] function-composition
- [x] defining-values
- [x] flags
- I added a lot of definitions here. Please confirm they land well with you.
- [x] making-game-images
- [x] functions-make-life-easier
- [x] functions-vertical-line-test
- [x] function-notation
- [x] functions-examples-definitions
- [x] functions-can-be-linear
- I added a definition for scale in the flags lesson. Seems we need a second definition that covers axes. Thoughts?
- [x] function-definition-linear
- [x] functions-dr
- should we add a definition for linear function?
- [x] functions-problem-solving-together
- [x] functions-for-character-animation
- [x] surface-area-rect-prism
- [x] problem-decomposition
- should we define profit, revenue and cost?
- [x] inequalities1-simple
- confirm that ES agrees with new definitions
- [x] inequalities2-compound
- suggest adding compose and compound to the glossary 
- should we add real numbers?
- [x] inequalities3-sam
- should we add boundary to the glossary?
- [x] piecewise-functions-conditionals
- [x] player-animation
- [x] distance-formula
- [x] inequalities-collision
-suggest adding function composition to the glossary

DS
- [x] ds-intro	
- suggest adding bias and infer		 				
- [x] bar-and-pie-charts 					
- [x] data-cycle	
- there are no vocab words in this lesson - and many words used that exist in our glossary file - which ones do we want to highlight?
- do we want to add the word statistical? or data?		 				
- [x] random-samples			
- suggest adding probability, deviation, bias
- we should rename the lesson folder to better match the lesson title
- [x] choosing-your-dataset				
- suggest adding probability, bias, and display to the glossary - FD is nervous to do this, forget a step, and mess up the build.
- should we add dataset to the glossary?
- [x] histograms							
- suggest adding bin to glossary
- [x] histograms2							
- suggest adding summarize and distribution to glossary
- [x] measures-of-center	
- suggest adding algorithm and center			
- [x] box-plots	
- add durations to box plots lesson sections						
- [x] standard-deviation					
- consider adding center to glossary
- [x] scatter-plots 			
- suggest adding random to glossary			
- [x] ethics-privacy-and-bias		
- there are no vocab words in this lesson. suggest adding bias.		
- [x] data-collection	
- there are no vocab words in this lesson. are there any words worth highlighting?					
- [x] lookups 							
- [x] custom-scatter-plots				
- [x] table-methods		 
- there were no vocab words in this lesson. Do we want to define order? filter? other things?				
- [x] method-chaining	
- there is no glossary. do we want to define chaining? ordering? filtering?					
- [x] defining-table-functions 
- there is no glossary for this lesson. are we ok with that?			
- [x] grouped-samples	
- suggest defining subset
- should we add "count" to the glossary?					
- [x] correlations						
- [x] linear-regression					
- [x] checking-your-work
- suggest adding testing table and artificial intelligence				
- [x] threats-to-validity			
- suggest adding bias, confounding variables, summary data

**Comment by flannery-denny** [comment]
@schanzer I'm working my way through this list and leaving you questions in the issue description as I go, lesson by lesson. Feel free to reply / check off boxes that you are satisfied with. Also fine to ignore for now and wait until I'm done with the full audit and transfer the issue to you.

**Comment by flannery-denny** [comment]
@schanzer I've completed the audit and left you lots of suggestions and questions. Assigning this to you.  If you add the suggested vocab words and they're ready for translation, feel free to reassign this to me.

**Comment by schanzer** [comment]
@flannery-denny here are my comments on the algebra lessons. Will add DS later in the week, as I dig out from under 4 of the last 5 weeks being PD weeks :P 

- Numbers Inside Videogames -- why should we include "variable"? It doesn't show up in the student-facing text anywhere
- Order of Operations -- sure, we can add that.
- Flags -- there are lots of concepts that _can_ be taught with this lesson, but I don't think it's a good idea to list every possible vocabulary word here. I don't think "comments" is a critical term here, such that it rises to the level of the other ones. I'm happy with the others, and the definition you added to the glossary for comments is a good one worth keeping.
- functions-can-be-linear -- looks like you already added axes? 
- functions-dr -- this lesson is more about the mechanics of the DR than any one function class. I think adding a definition for linear functions would lead a teacher to believe the learning goals of this lesson are different from what they are.
- problem-decomposition -- no, those functions are defined within the DR pages already, and the learning goals of the lesson have nothing to do with profit, revenue or cost
- inequalities1 - left you a comment on the specific commit
- inequalities2 - is "real number" truly an important vocabulary word to understand for this lesson? It's _mentioned_ here, but does it rise to the level of must-have-for-learning-goal?
- inequalities3 - I don't think boundary is needed
- inequalities-collision -- agreed. Let's add the definition, and also introduce/use it in the function composition lesson

**Comment by schanzer** [comment]
@flannery-denny 

- Numbers Inside Videogames -- missing an _opportunity_ to introduce it is quite different from listing it as an essential vocabulary word. I suggest adding a small note that this _could_ be introduced, but still not putting it in the vocabulary section.

- inequalities2 -- Same thing: _maybe_ worth adding a small note, but we can't use the vocabulary section as a list of words-that-might-be-useful. This is related to our "surface area" discussiong earlier today.

**Data Science**

-  ds-intro -- "inference" is way too high-level of a concept to introduce here. Let's use something more common in the lesson? As for "bias", I'm fine including this as long as it's a sufficiently common-sense definition that can be reused in later lessons without seeming inadequate.
- data-cycle - I don't think any of the vocabulary words that are used in this lesson are essential for understanding the lesson. "Statistical" and "Data" aren't really used in this lesson by themselves. "Statistical _Question_" is, but that's defined here and isn't a term that exists outside of our course. 
- random-samples -- agreed re: probability, but not bias or deviation. Both of those terms have technical definitions that are not needed here. Renaming the lesson is fine (another reason not to use `latest` in links!)
- choosing-your-dataset -- **let's find some time to talk. I think a lot of these suggestions are coming from the same idea, which is that words that are _used_ in a lesson should be listed as vocabulary words if they are in our glossary. We should discuss whether that's true before continuing with the other lessons in the list.**

**Comment by schanzer** [comment]
@flannery-denny added definitions for the following words to the glossary, which will need translations:

- [ ] distribution
- [ ] bias
- [ ] selection bias
- [ ] confounding variables

Otherwise I've gone through the lessons and implemented most of the changes listed above. Thanks for doing this!
