### ISSUE TITLE
Slide infrastructure

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#891]
- [x] custom font size
- [x] Make text placeholders auto-fit text by shrinking the font - impossible due to a google API bug
- [x] handle `coe` directive by generating images
- [x] Allow the `table{}` directive to take in an argument declaring whether or not there's a header. If there IS a header, do a simple MD passthrough. If there's NO header, use the current behavior and have md2gslides strip that out
- [x] When generating a slide deck, prepend "AUTO-GEN:" to the title
- [x] In the resulting `slides-*.html` page, include the timestamp and fileID, and ensure that the link opens the deck in a new tab
- [x] change `./build-slide` and `build-slides` so that the `-f` option always results in a new slide deck
- [x] if no layout is defined, default to Blank
- [x] cull unused placeholders

**Comment by flannery-denny** [comment]
@schanzer One more thought re: how to make automated slide generation more efficient. 

- [ ] Could we slightly modify the size of the titles in the template 
- [ ] and extend the title text box itself so they can accommodate more characters

Here's an example fo what builds automatically now
<img width="961" alt="image (5)" src="https://user-images.githubusercontent.com/66691020/167708432-cd6cbd13-1b71-4558-997b-6b19d775ef44.png">

And a reformatting of the same title on a different slide
<img width="961" alt="image (4)" src="https://user-images.githubusercontent.com/66691020/167708452-8e3984e0-8674-449c-b198-cad4238aef03.png">
?

Realizing that I have spent lots of time in my slide making extending the text boxes to fill the space available and resizing titles and it would probably be easy enough to make many more of the section titles work from the get go

**Comment by schanzer** [comment]
@flannery-denny done!

[The template can be edited here](https://docs.google.com/presentation/d/1jAjRtOGXhxfTGOx4F1vKAXfxUxQj2RXyTgwNuiOa_-w/edit#). Any change you make will be passed on to any NEW slide decks you create from the script. Feel free to edit as you like!

Here's the important part -- you need to actually delete the `slide-id.txt` file in order to make a new deck. Otherwise, the script will merely make changes to the old file...which has the old template and the old formatting. This is a classic example of "when we get it right, life gets better -- but until then it's going to be a little tedious"

**Comment by ds26gte** [comment]
Note that an SVG produced by a hypothetical `coe->svg` would still be converted into an image by `md2googleslides`, and would therefore suffer the same image-quota limitations as other images.
