### ISSUE TITLE
MD Slide Deck Audit

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#893]
Order of Ops
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Simple Data Types
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Contracts
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Function Composition
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Defining Values
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Funcs-Examples-Definitions
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Functions DR
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Numbers Inside VGs
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Inequalities 1
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Inequalities 2
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Inequalities 3 
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Problem Decomp
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Piecewise Funcs Conditionals
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Important for PD:
Functions-make-life-easier
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Functions-vertical-line-test
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Function-definition-linear
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Flags
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

**If you finish all checkboxes for all slide decks above, feel free to proceed to these. Otherwise, wait and let Flannery deal with them next week.  The general arc of the lesson plans is solid. But there are some optional pages that are still getting sorted out in these lessons.**

Funcs for Character Animation (awaiting approval)
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Player Animation (draft file will need to be updated once we make the posn page and update the lesson plan accordingly)
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] make WeScheme version of slides

Distance Formula
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

Inequalities Collision _the lesson plan links to 2 starter files that it doesn't refer to at all. If they are supposed to be part of the lesson, they'll need to be incorporated into the slides._
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

ds-intro
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

bar-and-pie-charts
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

data-cycle
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

random-samples
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

choosing-your-dataset
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

histograms
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

histograms2
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

measures-of-center
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

scatter-plots
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

lookups
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

table-methods
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

box-plots
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

method-chaining
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

defining-table-functions
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

grouped-samples
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

correlations
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

linear-regression
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

### Not essential for PD
computing-needs-all-voices
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

coordinates
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

making-game-images
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] WeScheme slides

functions-problem-solving-together _(FYI - I find it highly unlikely that anyone who doesn't try the DR in PD will use it in their classroom...)_
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] WeScheme slides

surface-area-rect-prism
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] WeScheme slides

function-notation
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] WeScheme slides

functions-can-be-linear
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt
- [x] WeScheme slides

checking-your-work
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

ethics-and-privacy
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

standard-deviation
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

custom-scatter-plots
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

data-collection
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

threats-to-validity
- [x] manual adjustments
- [x] peardeck
- [x] slides-id-pyret.txt

**Comment by flannery-denny** [comment]
@retabak please start w following important slide decks through to the finish line!

Before june 7 I or @schanzer need to use them to make the master algebra pd deck. 

If you get to the second tier and are able to see them through, great… 

But the window isn’t big before ds workbook edits and important slides for ds are top priority.

And pd is about to launch into full gear!

Less important decks can happen after june 7 pd if need be.

Also, chances are you’ll discover new feature requests in the process and maybe some infrastructure updates will result that make the rest of the work easier.

Flannery

**Comment by schanzer** [comment]
@retabak flannery is right - the important slide decks to be audited and completed!

WeScheme slides for Algebra can be done _after_ the Pyret ones are complete/audited. And yes, we're adding PearDeck as well.

**Comment by retabak** [comment]
@schanzer @flannery-denny - "debugging" was not on @flannery-denny 's original list (issue #875) of slide decks to make. Are we including it? Happy to make it, just wasn't sure if it was excluded for a reason.

**Comment by schanzer** [comment]
@retabak good call! yes, it would be GREAT if you can make that deck!
