### ISSUE TITLE
Replace "car", "caddr", and every other godforsaken ancient lisp-ism with "first", "second", "third", etc

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#894]
Maintainability/readability request: I understand that we probably can't get rid of the arcane `bash` script that runs this thing. But holy _hell_, can we at least dispense with lisp-isms that refer to _decades-old memory architectures?_

I say this jokingly. But only half-jokingly.

**Comment by ds26gte** [comment]
7de241260
