### ISSUE TITLE
@slideLayout directive

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#899]
In `slides-preproc.rkt`, `@slideLayout{XYZ} should expand to a no-op.

In `preproc.rkt`, `@slideLayout{XYZ} should expand to:
```
---
{Layout="XYZ"}
```

**Comment by ds26gte** [comment]
Why is `@slideLayout{XYZ}` required to expand to anything at all in (non-slides) `preproc.rkt`?  Shouldn't it be a no-op?

**Comment by schanzer** [comment]
@ds26gte stupid, rushed-copy/paste-while-discussing-on-zoom error.🥴

Fixed.
