### ISSUE TITLE
Unify formatting for role-play

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#901]
We currently use two different formats for role-play activities -- sometimes they're in a box, sometimes they're not. We should come up with a unique box, and use it consistently throughout the lessons:

- [x] Sam
- [x] Table Methods
- [x] Distance
- [x] Functions for Character Animation

**Comment by flannery-denny** [comment]
@schanzer - I like this proposals :)

**Comment by schanzer** [comment]
Addressed by d167e155639228c7872396804ac31fcd4e235868

@flannery-denny and @retabak , let me know if you approve of these changes?

**Comment by retabak** [comment]
Can we make it so the role play box looks more like the instruction box than the pedagogy box?

I think that the pedagogy box is generally something that I think of as "optional". If you're a teacher who is skimming the lesson in a hurry to get the gist of it, you can usually skim past these boxes. The role play activities, however, are generally not optional.  They are often the only actual instruction taking place on a given topic.

Is this possible?

**Comment by retabak** [comment]
additional thought:
Is the activity in the first section [here](https://bootstrapworld.org/materials/fall2022/en-us/lessons/piecewise-functions-conditionals/index.shtml?pathway=algebra-pyret) also role play?

**Comment by retabak** [comment]
@schanzer - not seeing any change? What commit?

**Comment by schanzer** [comment]
@retabak arg! looks like the push failed because of a merge warning and I didn't notice! :P Try now?

**Comment by retabak** [comment]
Looks good!
