### ISSUE TITLE
Add 4 pioneers 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#904]
**Work is on the `pioneers` branch**

Bob Moses
- [x] FD signed off
- [x] Rachel signed off
- [x] Emmanuel signed off

Joy Buolamwini (we do not have the right to modify this images)
- [x] FD signed off
- [x] Rachel signed off
- [x] Emmanuel signed off

Timnit Gebru (we do not have the right to modify this images)
- [x] FD signed off
- [x] Rachel signed off
- [x] Emmanuel signed off

Margaret Hamilton 
- [x] FD signed off
- [x] Rachel signed off
- [x] Emmanuel signed off

Computing-pioneers.adoc (look at both html and pdf versions)
- [x] FD signed off
- [x] Rachel signed off

Decide whether to cartoonify Bob Moses
- [x] Rachel signs off

Merge to master

- [x] Rachel will alert @ds26gte or @schanzer when ready

Could we feature an organization? [Skytruth](https://skytruth.org/about/) is an interesting project using data for environmental monitoring... we could highlight an individual from it, but perhaps the team is a better fit?

Shriram suggested Lorinda Cherry - no open source images on google - could [buy usage rights for $99](https://www.facesofopensource.com/blog/)

Maybe:
- [Rejma Saushani, Radia Perlman, Karen Spark Jones Hedy Lamarr?](https://www.digitaltrends.com/cool-tech/influential-women-in-tech/#dt-heading-reshma-saujani-1975-present)
- [Sophie Wilson](https://newrelic.com/blog/nerd-life/10-lgbt-computer-science-pioneers) or [this](https://www.computersciencedegreehub.com/30-most-influential-computer-scientists-alive-today/)  or [this](https://www.computerweekly.com/photostory/252503062/Important-LGBTQ-figures-who-shaped-techs-history/3/Sophie-Wilson) (female/lgbt)
-  [Edith Windsor](https://www.computerweekly.com/photostory/252503067/Important-LGBTQ-figures-who-shaped-techs-history/7/Edith-Windsor) (female/lgbt)

**Comment by schanzer** [comment]
I don’t know her at all, unfortunately. Shriram has a connection of some kind - I’d ask him.

**Comment by flannery-denny** [comment]
@schanzer The focus for the next 4 pioneers is on people who use math / cs / ds for activism. What do you think about including Bob Moses? Do you have other ideas of who to include?

**Comment by retabak** [comment]
Recently read some stuff by Catherine D’Ignazio in grad school: http://www.kanarinka.com/ 

Maybe her?

Or maybe she's too academic. Check her out.

**Comment by flannery-denny** [comment]
@retabak which image would you prefer that I pursue first
![Screen Shot 2022-08-29 at 6 23 25 PM](https://user-images.githubusercontent.com/66691020/187309505-4a98926a-1ace-4336-9359-c929ae7e64f6.png)
![Screen Shot 2022-08-29 at 6 21 45 PM](https://user-images.githubusercontent.com/66691020/187309508-0fdf842a-31c3-4165-b4cc-b9ba582d0518.png)

**Comment by retabak** [comment]
Wow! I love the 2nd one but I think (sadly) that it would be too tricky to pull off. I'm imagining disappointing results for folks who print the poster on anything but a super deluxe fancy printer.

And so, I vote for the first photo, which is also very nice.

I really like that we're gonna feature Bob Moses, btw! Good choice.

**Comment by flannery-denny** [comment]
@schanzer @retabak Do either of you have a black and white printer on which you can test how the poster drafts for Joy and Timnit print? They're on the pioneers branch. Thanks!

**Comment by retabak** [comment]
Uggggh, my printer needs a new ink cartridge. Ordering now - can do this by Monday!

**Comment by retabak** [comment]
![PXL_20220912_152348932](https://user-images.githubusercontent.com/87144723/189693967-eb685d65-00de-4bfe-88ca-2aad253b913a.jpg)
![PXL_20220912_152330693](https://user-images.githubusercontent.com/87144723/189693975-371bc7c4-be65-46dc-974f-69d63147b97c.jpg)

**Comment by flannery-denny** [comment]
@retabak looks like timnit's image is usable as is. Do you think Joy's is too dark? or should we just work with it?

**Comment by retabak** [comment]
I would prefer all of the posters to have the same look / feel but I do think these are both usable if need be.

**Comment by flannery-denny** [comment]
@schanzer @retabak. please read the pioneer posters for joy, timnit and bob moses and sign off in the checkboxes at the top of the issue.

**Comment by schanzer** [comment]
@flannery-denny the Bob Moses text has a great summary of his bio, but very little about his professional contribution or mission. Somewhere in there, we should talk about the fact that he saw Algebra essentially as a civil right, and argued for rigorous math instruction _for all_ as an equity issue.

**Comment by flannery-denny** [comment]
@schanzer Hmm... I tried to address that by way of including his quote.

> “The most urgent social issue facing poor people and people of color today is economic access. In today's world, economic access and full citizenship depend crucially on math and science literacy. The absence of mathematics literacy in urban and rural communities throughout this country is an issue as urgent as the lack of registered Black voters in Mississippi was in 1961.”

I guess it didn't do the job...

**Comment by flannery-denny** [comment]
@schanzer @retabak all 4 of the new pioneers are now available for review on the `pioneers` branch.

**Comment by retabak** [comment]
The Joy pic is sadly very tiny.

![joy-buolamwini](https://user-images.githubusercontent.com/87144723/198328404-8cae8bef-17da-4dd4-a2d2-ef7a2ec81a96.png)

![joy-buolamwini-2](https://user-images.githubusercontent.com/87144723/198328415-b0b8ab76-5534-4e81-8a02-83a81575528c.png)


![robert-moses](https://user-images.githubusercontent.com/87144723/198328778-12e0caf5-7f2a-4b30-9888-31ad843fd9bf.png)

![timnit-gebru](https://user-images.githubusercontent.com/87144723/198329942-27dbfeb2-3de9-448c-a3e5-31216f5a156e.png)

![marg-hamilton jpg](https://user-images.githubusercontent.com/87144723/198335234-2c044737-c1df-4838-a7cf-0913cecad5c8.png)

**Comment by retabak** [comment]
Okay! I removed the background from Alan Turing and tried to played around a lot with the Bob Moses pic. This is the best I can do with these images! If they aren't passable, then I suppose we just revert to what you originally posted, @flannery-denny. Maybe we can discuss on Tuesday. 

![alan-turing png](https://user-images.githubusercontent.com/87144723/199020382-f2bbf98b-3852-4503-b263-96a5dfe57e20.png)
![margaret-hamilton png](https://user-images.githubusercontent.com/87144723/199020395-93c96996-2522-4761-ad8f-cd6243ae913f.png)
![robert-moses png](https://user-images.githubusercontent.com/87144723/199020409-25fe3fa3-7003-4c12-a509-1d0de2549284.png)
![timnit-gebru png](https://user-images.githubusercontent.com/87144723/199020418-dfee56fb-0eef-40b8-8bac-0b3cfb7e303a.png)

**Comment by flannery-denny** [comment]
@schanzer I can confirm that these posters are building correctly again on master.

@retabak please update the credit for Bob Moses' poster to let the viewer know where the image you found came from and what license gives us permission to use it, if applicable. I'm 99% sure that the current image credit is for the previous image, which I had found.
