### ISSUE TITLE
Find a way to indicate if a lesson is "unplugged" 

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#906]
Maybe an icon? Or maybe we could have a collection of our unplugged materials somewhere? Or maybe we even just make a social media post that says, "Hey! We have some stuff that doesn't use tech!"

(tbh, I'm not sure how many lessons we have that fit this description - so maybe this is not a good idea?)

I wonder if this could be a way to get folks to dip their toes into our curriculum?

**Comment by schanzer** [comment]
@retabak I want to push back on this -- while it's true that we have a few unplugged lessons, I don't think it's fair to advertise us as a provider of "unplugged CS". If anyone is encouraged to "dip their toes" into our curriculum by the promise unplugged lessons, they're going to be disappointed.

**Comment by retabak** [comment]
Heard. (When I initially posted, I said I wasn't sure if this was a good idea!)

That said - I do think just having some sort of icon or even a sentence added to the lesson overview could help make our stuff more navigable and easily understood/digested by teachers. It's a little disorienting to read through the lesson and then realize there is no computer use! Even for planning purposes, 'unplugged' status could be useful to indicate. (At my school, I had to check out a laptop cart on days when I was doing Bootstrap.)

**Comment by schanzer** [comment]
In that case, how about putting "_**This lesson is unplugged**, and does not require a computer_," at the top of the materials list for those lessons?

**Comment by retabak** [comment]
works for me!
I can do this. Do you happen to know quickly which lessons need this added?

**Comment by schanzer** [comment]
@retabak off the top of my head, this is the list. There may some false positives here, so be sure to double check within this list.

- [ ] computing needs all voices
- [ ] coordinates
- [ ] data-cycle
- [ ] ethics-privacy-bias
- [ ] function-notation
- [ ] vertical line test
- [ ] threats to validity
