### ISSUE TITLE
Can we add a directive that inserts vertical space that is less than 1ex? 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#911]
I want this all the time when making workbook pages...

**Comment by schanzer** [comment]
@flannery-denny why not use `vspace{0.5ex}`?

**Comment by flannery-denny** [comment]
@schanzer Try it. Does it make a half height space for you? I'm pretty sure that it works like the bin width for histograms in google charts and either rounds down to 0 space or up to a whole space.

**Comment by schanzer** [comment]
@flannery-denny ah, that's a CSS issue -- new lines have a minimum height that we can't go any lower. This is not fixable.
