### ISSUE TITLE
Give "functions can be linear" some tlc

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#915]
While working on the slides for "functions can be linear," I found myself thinking, "This lesson is LONG."

There are nine worksheets! Teachers will really need to race through worksheets and discussions to  squeeze this 4-segment lesson into one class period.

What if "Simple Sequences and Straight Lines" paired with "Linear, Non-Linear, Or Bust" to form one lesson....

And "Slope and y-Intercept from Tables" pairs with "Slope and y-Intercept from Graphs" form a second lesson?

It's overwhelming to skim through this lesson because there are SO MANY graphs and tables and worksheets and objectives. These are also important objectives. I feel very strongly about this. 

Other minor issues with this lesson: 
- I think there needs to be more description as to why the shortcut for finding the y-intercept works! ("Mulltiply any x in the table by the slope, and subtract the result from the corresponding y" is provided without explanation.)
- Table "rows" are referred to, but the tables are sideways so I think "columns" would be more accurate. Regardless, it's confusing.
- The synthesize text in the last two sections (Slope and Y-Intercept from Tables, Slope and y-Intercept from Graphs) is identical.

**Comment by schanzer** [comment]
No lessons are being split, merged or inserted at this point. We are long past the point of that level of restructuring.

**Comment by retabak** [comment]
@schanzer Understood!

That said, there are 31 slides in the deck! Maybe we can think of a way to pare it down / streamline it without totally restructuring (agreed, definitely a bad idea this late in the game).

Or, maybe we can revisit it next year.  There's lots of good stuff there in the meantime. Folks can modify to meet their needs.

@flannery-denny - happy to discuss the minor things tomorrow!

**Comment by retabak** [comment]
- Use of rows is no longer an issue - this is much clearer.
- Regarding finding y-intercept from 2 points - to me this still reads like an old-school textbook. I'm afraid we're setting kids up to follow the algorithm mindlessly, without understanding what they're doing. Why does this work? An explanation is needed.

ALSO: I keep staring at this lesson and reading it over and over and trying to wrap my head around how it could happen in 55 minutes and try as I might, it **really** feels impossible to me.  What age group is this lesson for? It seems to assume that students will grasp the concepts of slope and y-intercept quickly and without struggle. It feels rushed and like there is just no time to play and explore before flipping to the next worksheet (of 10!). **I know we can't split this lesson into smaller pieces now, but I really would like to keep that idea on the table to revisit at a later date.**  You mention that many of these pages are not meant to be engaged with for long - but they are thoughtful and could be used to facilitate rich discussion and as a teacher I'd be said to cut my kids off after 3-4 minutes.

I'm sorry I'm giving feedback so late in the game; I wish I had been asked to review this sooner because - as I'm sure you can tell - this lesson is not sitting right with me. Maybe it's because it's for older kids. Anyhow, here are some other thoughts:
- Why are slope and y-intercept first introduced via tables? I feel as though these concepts don't (can't) mean much to students unless they are seen graphically. Can they? 
- In the first section (Simple Sequences and Straight Lines), what does the 2nd N&W offer that the first one (which has both a graph and a table) doesn't?
- I get the desire to include real-world context, but how does the discussion of "linear relationships are everywhere?" support the learning goal ("students explore the concept of linearity, as represented in tables and graphs"). In a very long lesson, this feels like extra fluff (especially since there's not really any real-world context anywhere else).

**Comment by flannery-denny** [comment]
@retabak Thanks for pushing to clear up the rows issue. 

1) Happy to know that the y-intercept explanation still doesn’t sit well with you. That solidifies the case for moving it to the lesson which discusses finding slope & intercept from the equation and using the equation as the anchor.

2) Happy to revisit this lesson for next year. 

3) For now, please work on the following frame your feedback. Instead of stressing about 55 minutes, ask yourself, if you could take as much time as you needed to teach with these materials…

- do you have what you need?
- is there anything you would cut?
- is there anything you would reorder?

For the record, I welcomed you giving feedback on all of the functions lesson months ago and told you where to find them… and which were codap priorities… it’s been a busy year ;)

Finally, this is not designed to be the only lesson students see about slope and y-interecept. And it’s not for 6th grade.

**Comment by flannery-denny** [comment]
@retabak 
I've addressed most of what we discussed and made the lesson plan more concise in the process.  In looking more carefully at the materials, what we have for slope and y-intercept from tables is much more fully developed as an introduction than what we have for graphs. We can set it as a goal to make some more workbook pages for next year with higher resolution images that allow us to start with graphs, but it's not a fix we can make this year.

**Comment by flannery-denny** [comment]
@retabak @schanzer when I headed to the hospital yesterday I was in the middle of trying to figure out how to add the y-intercept bit to the `function-definition-linear` lesson. I still haven't cracked it. It feels like we're talking at kids rather than offering them an activity. 

If I knew how to embed tables inside of pedagogy boxes, I probably would have made it shorter and moved it into one at the end of the lesson instead of making a new lesson section.

If we're going to make it a lesson section, it feels like it deserves a workbook page (optional at this point).

**Comment by flannery-denny** [comment]
@retabak Looks like the slides for the functions-can-be-linear lesson might still say "slope & y-intercept from tables"

**Comment by retabak** [comment]
Kids still find y-intercept by extending tables, they just don't find it
between any two random points. Do you want to remove y-intercept from
tables entirely? (I started taking it out of the lesson, but then figured
you left it on purpose.)

**Comment by flannery-denny** [comment]
@retabak you're right. I just noticed that your commit had removed it from
some place and not others. I wasn't thinking about why you may or may not
have removed it. It should probably stay in all places.

**Comment by schanzer** [comment]
@retabak I know you're busting your butt on this, but it's time to triage -- we need to put this lesson to bed TOMORROW, and that includes the WeScheme and Pyret slides. Do whatever it takes -- we need to get this _done_.

We can tweak the lesson plan and slides as much as we want in the next few months. But the workbook needs to go to print.

**Comment by retabak** [comment]
@schanzer - Everything (except Wescheme slides) is done!

**Comment by schanzer** [comment]
Looking good!

Not quite everything was done -- none of the new worksheets had solutions written, and there were a handful of small formatting glitches to address before doing the slides.

But now all slides are done, and we can close the issue! GREAT work on this.
