### ISSUE TITLE
Fix / Clarify @ifsoln within @fitbruby

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#919]
When I use `@fitbruby{15em}{@ifsoln{quantitative}}{_categorical or quantitative_}` the `@ifsoln` shows up when I'm not in @ifsoln mode. 

Pages where this is an issue are committed below.

**Comment by schanzer** [comment]
@ds26gte This is your wheelhouse

**Comment by schanzer** [comment]
@flannery-denny close if this addresses the issue?

**Comment by schanzer** [comment]
Confirming this is fixed on the referenced page, as well as spot-checks in other pages.
