### ISSUE TITLE
very minor concerns in ds-into

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#924]
The "Questions and Columns Descriptions" worksheet - 

I suspect many teachers will need the answer keys to complete the two fill-in-the-blank prompts underneath the Notice/ Wonder table. There are so many blanks and not much context; I kinda just stared at these feeling confused for a few minutes before I put the pieces together. If it were up to me, we would delete these.

I'm also seeing that, in the lesson, we say this: "There’s a third column, called 'Answered by Dataset' — we’re going to return to that later, so you can ignore it for now." The third column, however, does not reappear in the lesson. Does it return at a later lesson? If so, can we tell teachers when to expect it? If not, can we be certain that it does?

**Comment by schanzer** [comment]
@retabak I'm asking students what they Notice and Wonder -- what kind of answer key could I possibly provide? I already added an example Notice and an example Wonder.

**Comment by retabak** [comment]
I'm referring to the prompts *under* the Notice& Wonder table.

**Comment by retabak** [comment]
Oh, interesting. The answer key offers "categorical or quantitative" _beneath_ the 2nd blank. Can we make that show up on the student version? My concern is that there are so many blanks and so few words that kids won't understand what they're supposed to do here, or how to begin.

How about "we're going to return to that later"?

**Comment by retabak** [comment]
On page 8 of the printed workbook, I don't see "categorical or
quantitative" beneath the blanks

Was that a printing issue?

**Comment by schanzer** [comment]
@retabak I believe it was. Anyway, I think this is ready to close when you have a moment to look at it
