### ISSUE TITLE
function-notation lesson is rough in WeScheme

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#925]
At the very least, there should be some explicit acknowledgement of the fact that WeScheme's notation is different.

**Comment by schanzer** [comment]
@flannery-denny @retabak I just pushed some small changes to the lesson, which I feel address this issue:

- I explicitly call out the fact that programming notation and function notation have differences
- I provide a side-by-side comparison for students, asking them to identify what's the same and what's not
- Slight rewording in a few places
- Moved piecewise functions to a strategy-box

I'd love to have one of you just read through the change, and let me know if you're comfortable with it.

**Comment by flannery-denny** [comment]
@schanzer This lesson makes me want to ask a big picture question... 

**Is there a point at which we will stop publishing all new lessons in WeScheme?** 
I am clear on why we would want to maintain the ability to do what current bootstrap teachers know how to do in WeScheme, but, just as we don't attempt to port all Data Science lessons into WeScheme, I wonder if, perhaps, some lessons, like the function notation lesson are best left as pyret only... I can't say that I truly believe this is an instance where programming is supporting the math learning goal.

That said, the lesson does read much better as a WeScheme lesson than I had anticipated you would be able to pull off.

Two concrete question marks:
The headings on the three tables are nonsensical to me. 
![Screen Shot 2022-06-12 at 12 55 02 PM](https://user-images.githubusercontent.com/66691020/173246865-5efb9bc7-d635-4f54-8b48-8e3622a9c8c6.png)
Perhaps it would make more sense to me as:

> Expression | What it really does | Final Product

or 

> Expression | Translated Expression | Final Product

or 

> Expression | Translated Expression with Substituted Input | Final Product

**very flexible about what happens here, just think it needs to change, especially the middle column title**

Why do you think it's worth providing this table? I'm not understanding what it adds.
![Screen Shot 2022-06-12 at 12 57 41 PM](https://user-images.githubusercontent.com/66691020/173246871-c2bb2c71-9ecb-4fbc-916f-edf2a477a842.png)

**Comment by schanzer** [comment]
@flannery-denny Pathways contain the same list of lessons, regardless of proglang. 

I didn't come up with those table headings, but I quite like them.

Calling the first column "Expression" is not useful, as we've already shown students lots of different expressions that have nothing to do with function application (e.g.  - `42`, `21 * 2`). We should use the proper, most-precise terminology whenever possible.

The second column is where I'm more flexible. Of your suggestions, "what it translates to" is the closest to what I want here. The key word here, however, is "substitution" -- when a function is applied to some inputs, those inputs are substituted in place of the variables in the function body. 

How about "after substitution"?

**Comment by flannery-denny** [comment]
@schanzer I’ll put it on our big picture curriculum thinking to discuss further what the definition of a pathway is.

After substitution is an improvement.

The thing is that in the first row, the 10 is what’s being substituted, but the column headings make it seem like be triangle solid green is what is being substituted… since 10 appears in the first and second column and is not what’s changing…

Flannery

**Comment by schanzer** [comment]
@flannery-denny "what it translates to" leaves out some important math vocabulary, and one of THE big ideas of function notation is that it shows students which inputs get substituted where. I don't want to leave that out. 

Pathways are not changing, especially when we could just as easily define two separate `algebra-pyret` and `algebra-wescheme` pathways and allow them to have different lessons. I could especially see the wescheme pathway being optimized for elementary and middle school, with Pyret spanning grades 4-12. And remember: our goal for next year is to have the plurality of pathways front-and-center! 

Let's not create more work when we don't need to!

**Comment by flannery-denny** [comment]
@schanzer for the record, the math vocabulary “substitution” is all over this lesson plan and I think the text of the lesson plan does a much more thoughtful job of explaining substitution than the titles of the columns in these tables do. Perhaps we’ll have better ideas in the future.

Also, the pathways you are proposing are the beginning of the big picture conversation I am looking forward to. I am not proposing extra work. Or urgent work. Just recognizing that there’s more rethinking to come.

**Comment by flannery-denny** [comment]
@schanzer I woke up still thinking about this and went back and looked at what you did with my feedback. Unless you forgot to commit something, you neither adjusted the column titles per your proposal, nor addressed my confusion as to why you added in the third table. I've changed the title and removed the table in separate commits. And in the process discovered some other issues that needed fixing. Please review and close if satisfied

**Comment by flannery-denny** [comment]
hmmm... missed a space on that last commit so it didn't auto attach. Will try to link  be872ba

**Comment by schanzer** [comment]
@flannery-denny You're right - looks like I hadn't committed. And in looking at the titles with fresh eyes this morning, I think there's something even better we can do.

The only other "fixes" I see are centering the functions. I'm not sure this is the right way to go, but I won't fight you on it. However, I do insist that we use the proper directives, now that we asked Dorai to make them.

Please check the latest commit.

**Comment by flannery-denny** [comment]
@schanzer here's my last commit 
[https://github.com/bootstrapworld/curriculum/commit/65be872babc61b96c23f214defb74c3ad58a09b3](https://github.com/bootstrapworld/curriculum/commit/65be872babc61b96c23f214defb74c3ad58a09b3)

**Comment by schanzer** [comment]
@flannery-denny I like the changes to the learning goals! However, I am not OK with the rest of your changes.

I am not comfortable removing the third table. Students need to see at least _one_ of these tables using function notation. 
You also removed the lesson-instruction formatting, which makes it inconsistent with other lessons. I've put it back in.

If you feel strongly about these changes, please call me.

**Comment by flannery-denny** [comment]
@schanzer nearly all of the workbook pages for this lesson use the word pyret. And most of them have pyret function definitions.
