### ISSUE TITLE
Auto-insert links to slide decks

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#926]
Now that slides are completed, we need a way to have lessons build and automatically use the right decks by looking at the `slides.id` files and the `proglang`.

**Comment by ds26gte** [comment]
After approval of 634bf9d88, we can remove the explicit links to Lesson Slides in lesson plans. The ids used in these explicit links don't seem to match the ones in the slides-PROGLANG.id files.

**Comment by schanzer** [comment]
Can we add a warning if no slide is exists for the target proglang?
