### ISSUE TITLE
Directive to identify and link lesson slides page

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#928]
Typically the `@material-links` directive includes a link to the lesson slides, calculated dynamically from the contents of `slides-PROGLANG.id`. However, the `piecewise-functions-conditionals` lesson plan doesn't use `@material-links`, preferring to list the materials by hand. The hand-made links to the lesson slides hard-codes the presentation ID, instead of using `slides-PROGLANG.id`. We may need a `@lesson-slides` directive for such cases. (Or avoid manual material links sections entirely.)

**Comment by flannery-denny** [comment]
There's a good reason why that lesson doesn't use autogenerated materials. @lesson-slides would be a better solution here.
