### ISSUE TITLE
Some link checking...

### ISSUE THREAD

**Issue by ds26gte** [bootstrapworld/curriculum#93]
Added script `verify-links` to check  all the links in the deployed docs for liveness. (It uses the optional package `linkchecker` on Ubuntu; may also be available on macOS.)

I fixed all the low-hanging typos. The following three require some content checking but they should be easily fixable by the author(s):

- `CreatingFunctions1/*/CreatingFunctions1.adoc` refers to `workbook-pages/FastFunctions1.pdf`, which doesn't exist. (Perhaps this is the `FastFunctions.pdf` in lesson `DefiningFunctions1`?)

- `DefiningFunctions1/*/DefiningFunctions1.adoc` refers to `workbook-pages/MappingExamplesWithCoE1.pdf`.  But there are only `*CoE.pdf` and `*CoE2.pdf`. It should be one of them?

- `DefiningFunctions3/*/DefiningFunctions3.adoc` refers to `workbook-pages/WordProblem.pdf`. (There are several candidates for this with different names, and they also have a solution version.)

**Comment by BootstrapJen** [comment]
`CreatingFunctions1` is a defunct lesson, changes made to the other two.
