### ISSUE TITLE
@proglang should produce the current PL name

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#930]
There are lots of places where we'd like to write `In @ifproglang{pyret}{Pyret} @ifproglang{wescheme}{WeScheme}, we blah blah`. Sometimes we do, and sometimes we use sub-optimal phrasing like "In _our programming language_...".

It would be lovely to just use the tool-name as a variable, and simplify our markup:
`In @proglang, we blah blah...`

**Comment by ds26gte** [comment]
But you can already do this. And you've already used this directive in the various `front-cover.adoc` files.

**Comment by schanzer** [comment]
OMG. *headdesk*
