### ISSUE TITLE
reorder autogeneration of the materials section

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#932]
- [x] @ds26gte make the tag for @schanzer to add the workbook pages to the materials section following slides and starter files.
- [x] @schanzer polish autogeneration so that the order of materials listed is as follows (subbulleted list and the linked pdf of the workbook are such an improvement!)

- slides
- starter files
- pages from the workbook with bulleted list
- online exercises
- optional starter files
- opt-printable exercises.
- opt-online exercises

**Comment by schanzer** [comment]
@ds26gte this one’s in your wheelhouse

**Comment by flannery-denny** [comment]
@schanzer @ds26gte I'm noticing that when the lesson plan first opens, for a split second slides are listed at the top and then the order changes...

**Comment by ds26gte** [comment]
Could one of you give me a typical lesson name illustrating where this is needed.

**Comment by schanzer** [comment]
@ds26gte `distribution/en-us/lessons/linear-regression/index.shtml`

**Comment by flannery-denny** [comment]
@ds26gte not sure whether or not you think this is fixed, but I'm noticing that ds-intro still has something building ahead of slides in the materials section.

**Comment by schanzer** [comment]
@ds26gte this is because my javascript code inserts itself as the first bullet in the list, because I don't have any other reliable way to calculate the correct position. But _you_ can alert me to it by setting a CSS class for an empty bullet in the DOM. And that's what the first checkbox is about.

**Comment by ds26gte** [comment]
I've added an empty item whose content is an empty span of class `materialSectionPlaceholder`. Please feel free to change the class's name if it's ungainly.

**Comment by schanzer** [comment]
Thanks, Dorai! @flannery-denny , close if this works the way you would like
