### ISSUE TITLE
add student response peardeck feature to slide decks

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#933]
If we're asking a question, it's helpful to have a space for students to reply. We use this all the time in pd!

For example, I would expect student response features on slides 4-6 of this deck. [https://docs.google.com/presentation/d/1sXQEhvUKahcP-HeW0_AGNmh9rBjqzA4jAL0nrI-wn8w/edit#slide=id.c861a475-dc41-11ec-8c6c-554beba67667](https://docs.google.com/presentation/d/1sXQEhvUKahcP-HeW0_AGNmh9rBjqzA4jAL0nrI-wn8w/edit#slide=id.c861a475-dc41-11ec-8c6c-554beba67667)

- [ ] computing-needs-all-voices
- [ ] numbers-inside-video-games
- [ ] coordinates
- [ ] order-of-operations
- [ ] simple-data-types
- [ ] contracts
- [ ] function-composition
- [ ] defining-values
- [ ] flags
- [ ] making-game-images
- [ ] functions-make-life-easier
- [ ] functions-vertical-line-test
- [ ] function-notation
- [ ] functions-examples-definitions
- [ ] functions-can-be-linear
- [ ] function-definition-linear
- [ ] functions-dr
- [ ] functions-problem-solving-together
- [ ] functions-for-character-animation
- [ ] surface-area-rect-prism
- [ ] problem-decomposition
- [ ] inequalities1-simple
- [ ] inequalities2-compound
- [ ] inequalities3-sam
- [ ] piecewise-functions-conditionals
- [ ] player-animation
- [ ] distance-formula
- [ ] inequalities-collision
- [x] ds-intro			 				
- [x] bar-and-pie-charts 					
- [x] data-cycle			 				
- [x] random-samples						
- [x] choosing-your-dataset				
- [x] histograms							
- [x] histograms2							
- [x] measures-of-center					
- [x] box-plots							
- [x] standard-deviation				
- [x] scatter-plots 					
- [x] ethics-privacy-and-bias				
- [x] data-collection						
- [x] lookups 							
- [x] custom-scatter-plots				
- [x] table-methods		 			
- [x] method-chaining						
- [x] defining-table-functions 			
- [x] grouped-samples						
- [x] correlations					
- [x] linear-regression				
- [x] checking-your-work				
- [x] threats-to-validity

**Comment by retabak** [comment]
@schanzer and I discussed this and decided against it for two main reasons.

We're not sure what percentage of our teachers use PearDeck. (I don't think it's a very high percentage.) Folks who do use it can add and customize questions on their own pretty easily.

The other reason is connected to the slides build system. With each build, PearDeck additions are erased and need to be added manually. Feels like we're creating an extra layer of work that doesn't have much benefit for very many people?

**Comment by schanzer** [comment]
@flannery-denny Every hour spent customizing the peardeck functionality will have to be repeated each year (and in some cases each semester). As @retabak says, teachers are likely to add their own anyway.

With the Data Science slides, I added a few text response questions to every lesson and I consider them complete. If you want to push ahead with adding 2-3 PearDeck responses to the Algebra slides, that's fine -- but please don't both until a LOT of other issues are resolved. Adding pioneers, unifying role-play formatting, and auditing glossaries are all far more important.
