### ISSUE TITLE
Add threads for posting pd products to discourse

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#939]
- [ ] share your game
- [ ] share your exploration & research papers
- [ ] add slides at the end of pd decks instructing people to post

**Comment by flannery-denny** [comment]
@schanzer I've added these to discourse. Please have a look. Close if you're satisfied. Edit if you have ideas for how to improve upon them. [https://discourse.bootstrapworld.org/c/resources-from-bootstrap-teachers/88](https://discourse.bootstrapworld.org/c/resources-from-bootstrap-teachers/88)

**Comment by schanzer** [comment]
Perfect. 

_"Bootstrap materials made by teachers for their students… share yours! Be inspired by others!" ❤️_
