### ISSUE TITLE
links to projects on materials landing page need attention

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#943]
- [x] In the data science lesson order there is no displaying categorical data lesson anymore. On the materials landing page the making infographics project links to that lesson. This same situation may be true of other lessons whose names have changed? I would expect us to get a warning...
- [x] currently project links go to lessons.  we discussed them going directly to project descriptions. What steps need to happen to make this so and who should do them? @schanzer please let us know if some of the steps are in our wheelhouses!

**Comment by flannery-denny** [comment]
@schanzer I thought that I was looking at fall2022 version of this, but I'm realizing that I don't have a link to get to the fall version of the materials landing page. I tried this [https://bootstrapworld.org/materials/fall2022-beta/en-us/](https://bootstrapworld.org/materials/fall2022-beta/en-us/). Please advise.

**Comment by schanzer** [comment]
Go to the landing page and change the address to fall2022-beta

**Comment by schanzer** [comment]
I went in to debug this, but apparently the landing page is not generated on `master`. Looks like some bugs from the merge are still biting us...

**Comment by schanzer** [comment]
@flannery-denny Are you sure you've done a fresh build? 

Displaying-Categorical-Data has been renamed, and the Infographics link has been updated appropriately.
Project links already go directly to pages, where appropriate. 

Can you point to something specific that does not work as you expected, and tell me how you'd like it to work?

**Comment by flannery-denny** [comment]
@schanzer I can't get to the beta version of the materials landing page... when I click [https://bootstrapworld.org/materials/fall2022-beta/en-us/](https://bootstrapworld.org/materials/fall2022-beta/en-us/) I get
![Screen Shot 2022-06-16 at 6 36 46 AM](https://user-images.githubusercontent.com/66691020/174062088-16c24434-b113-438d-a0c5-5a21b34a351e.png)

lmk when it's fixed and I'll doublecheck that the buttons do what we would expect them to.

**Comment by schanzer** [comment]
@flannery-denny There is nothing to fix. Please use a fresh build on your own machine.
