### ISSUE TITLE
Improve description of Function Notation Lesson

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#944]
[Function Notation](https://bootstrapworld.org/materials/fall2022-beta/en-us/lessons/function-notation/index.shtml?pathway=algebra-pyret)  Students learn to read function notation.

**Comment by flannery-denny** [comment]
@schanzer close if you're satisfied. modify if you're not.

**Comment by schanzer** [comment]
This looks great. Thanks!
