### ISSUE TITLE
Piecewise Functions lesson needs some attention

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#945]
The pedagogy box about more than one way to define piecewise functions completely disrupts the flow of this lesson plan to the point that I am confused in reading it

And there is definitely a mistake in this code - it shouldn't be about cost

![Screen Shot 2022-06-15 at 3 27 02 PM](https://user-images.githubusercontent.com/66691020/173921109-c6c516bf-2c36-400b-a455-d0503bf15120.png)

**Comment by schanzer** [comment]
@flannery-denny I've corrected the code example.

As for the pedagogy box -- this seems very aligned to that part of the lesson to me. Students have just learned the syntax for using `if/then`, and have completed `red-shape`. Now there's an optional extension showing an alternate syntax, and recommending having students rewrite `red-shape` to use `ask` instead.

Where else would you put this box? What about the current placement is disruptive to the flow?

**Comment by flannery-denny** [comment]
@schanzer I was talking about the other pedagogy box. If you're satisfied with my reorganization of the end of the lesson, feel free to close.

**Comment by schanzer** [comment]
nice!
