### ISSUE TITLE
Link sizes / fonts are inconsistent on teacher resources page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#946]
[https://bootstrapworld.org/materials/fall2022-beta/en-us/courses/data-science/resources/index.shtml](https://bootstrapworld.org/materials/fall2022-beta/en-us/courses/data-science/resources/index.shtml)

There are a lot of different font sizes on this page. Any way to unify them?
It feels strange that **[Research Paper Resources & Datasets](https://bootstrapworld.org/materials/fall2022-beta/en-us/courses/data-science/resources/index.shtml#Research-Paper)** is in the faint blue

**Comment by schanzer** [comment]
@flannery-denny I've pushed a fix for this. Close if this addresses the issue for you?

**Comment by schanzer** [comment]
@flannery-denny can you check this out, and close if it looks good to you?
