### ISSUE TITLE
Projects are missing from Algebra Teacher Resource Page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#947]
We worked on a video game project description. Where is it? 
Are there other projects we should have here?

**Comment by schanzer** [comment]
@flannery-denny I added a "projects" section, and included a link to the video game project. Feel free to add others (flags, etc)!

**Comment by flannery-denny** [comment]
thanks @schanzer. Closing for now. Will add other projects as we write them up.
