### ISSUE TITLE
Upgrades to teacher resources page

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#948]
- [x] make printables for classroom walls more visible
- [x] link to hoc lessons?

**Comment by flannery-denny** [comment]
@retabak @schanzer I've added a section to the teacher resources pages for _printables for classroom walls_. In algebra it just links to pioneer posters. In DS is also links to statistical fallacies to avoid. If you have other ideas feel free to add them.

Curious what you think about linking to the hour of code lessons from these teacher resources pages.

**Comment by schanzer** [comment]
@flannery-denny I love this! And I think adding Hour of Code lessons is an excellent idea. Feel free to close after those have been added.
