### ISSUE TITLE
starter files on data-science teacher resources page should all be in one section

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#949]
I'm seeing this at [https://bootstrapworld.org/materials/fall2022-beta/en-us/courses/data-science/resources/index.shtml](https://bootstrapworld.org/materials/fall2022-beta/en-us/courses/data-science/resources/index.shtml)
![Screen Shot 2022-06-15 at 3 48 45 PM](https://user-images.githubusercontent.com/66691020/173924693-3281e46a-dbb2-4b0b-8564-5b9243d322c3.png)

**Comment by schanzer** [comment]
@flannery-denny good call! These were using outdated hardlinks! I've updated them to use `@starter-file`, and made sure that the list is complete.
