### ISSUE TITLE
Starter Files with optional link text should use the original text in the materials section

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#954]
The recently-added feature seems to be messing up the link collection. See the image below, taken from the scatter-plots lesson.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/77126/174055598-863a9016-cac8-4020-9f67-f29a88a9bd55.png">

**Comment by retabak** [comment]
I noticed this issue for worksheets (not starter files). See image below. Don't know if this should be a new issue, or if the wizard's fix can include both starter files _and_ worksheets?

![image](https://user-images.githubusercontent.com/87144723/174155479-ebbdf07a-99e6-46d1-bdfe-4fc857aebfb5.png)

**Comment by schanzer** [comment]
@retabak I believe Dorai's fix resolves the issue. Close if you agree?

**Comment by schanzer** [comment]
Just checked it myself, and it looks great! Thanks, Dorai!
