### ISSUE TITLE
The link to the Language Tables seems to be MIA from the lesson plan

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#955]
I remember we decided to link from it. Can't remember if it was supposed to be in the Materials section or elsewhere.

**Comment by retabak** [comment]
Came here to say the same thing! Noticed it here: https://bootstrapworld.org/materials/fall2022-beta/en-us/lessons/simple-data-types/index.shtml?pathway=algebra-pyret

![image](https://user-images.githubusercontent.com/87144723/174148446-253d8e71-e5bc-4d15-8ef8-22d41407c2c3.png)

**Comment by schanzer** [comment]
@flannery-denny @retabak whoa - this entire feature seems to have _disappeared!_ I'm wondering if it got lost in a merge somewhere? I'll investigate.
