### ISSUE TITLE
Increase font size at top of Alignments pages

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#957]
The directions are really important and so small that the drop down menu where you can choose what you want to see is almost undiscoverable.

![Screen Shot 2022-06-16 at 6 20 19 AM](https://user-images.githubusercontent.com/66691020/174059326-3e6c4aca-1bbf-436f-9768-f127e2beb50e.png)

**Comment by schanzer** [comment]
It looks like a CSS change was accidentally merged in when I switched to master. This caused _several_ non-workbook pages to get the wrong font size. Pushing a fix the reverts this change.
