### ISSUE TITLE
pathwayTOCs have trailing whitespace after lesson names - causes incorrect lesson JS behavior

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#960]
Notably, the lesson order doc starts with computing needs all voices lesson and it's missing. Perhaps others are, too?
![Screen Shot 2022-06-16 at 6 33 23 AM](https://user-images.githubusercontent.com/66691020/174061307-fea4aa51-8d44-40f8-88e6-10fe288bfddd.png)

**Comment by schanzer** [comment]
@ds26gte the pathwayTocs.js file is being generated with trailing spaces after every lesson plan:

```
var pathwayTocs = {
   "data-science": ["computing-needs-all-voices ", "ds-intro ", "simple-data-types ", "contracts ", "bar-and-pie-charts ", "data-cycle ", "random-samples ", "choosing-your-dataset ", "histograms ", "histograms2 ", "measures-of-center ", "box-plots ", "standard-deviation ", "scatter-plots ", "ethics-privacy-and-bias ", "data-collection ", "lookups ", "functions-make-life-easier ", "functions-examples-definitions ", "custom-scatter-plots ", "table-methods ", "functions-dr ", "functions-problem-solving-together ", "method-chaining ", "defining-table-functions ", "grouped-samples ", "correlations ", "linear-regression ", "checking-your-work ", "threats-to-validity "]
}
```

The lesson JS checks to see if the current lesson is present in the selected pathway via string comparison. These trailing spaces cause the check to fail, so only the prerequisite lessons are being selected. This happens for all pathways.

**Comment by schanzer** [comment]
Confirmed fixed!
