### ISSUE TITLE
Suggestion for ethics, privacy and bias lesson launch

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#965]
- [x] I would suggest cutting the nazi example from the lesson

The description of Josef Mengele's work isn't specific enough to discuss. Also no need to elevate him / trigger people with a photo. I think the photo of the bomb is enough to connect us to the real world consequences of science and the description of the syphillis experiment is concrete enough to support discussion.

- [x] I would suggest adding a bolded **Should data scientists be bound by any ethical rules? If so, what rules?**, mirroring the line of questioning already happening in the lesson.

**Comment by retabak** [comment]
Strongly agree with removing Mengele and his photo. (Secondarily, including his photo adds a bunch of extra / awkward white space.)

**Comment by schanzer** [comment]
@flannery-denny done. Close if these changes are to your liking
