### ISSUE TITLE
maybe we should implement retractable/expandable prerequisites sections of the lesson table?

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#967]
When our materials list is very long, that section of the table shrinks unless you're mousing over it. Here's a good example of that in action [https://bootstrapworld.org/materials/fall2022-beta/en-us/lessons/order-of-operations/index.shtml?pathway=algebra-pyret](https://bootstrapworld.org/materials/fall2022-beta/en-us/lessons/order-of-operations/index.shtml?pathway=algebra-pyret)

 I wonder if we should do the same with prerequisites, except for more aggressively... so that only the first 4 or 5 prerequisites are revealed when you first open the page? 

Here's an example of a page where I think it would be particularly helpful [https://bootstrapworld.org/materials/fall2022-beta/en-us/lessons/threats-to-validity/index.shtml?pathway=data-science](https://bootstrapworld.org/materials/fall2022-beta/en-us/lessons/threats-to-validity/index.shtml?pathway=data-science)

**Comment by schanzer** [comment]
@flannery-denny done!

**Comment by flannery-denny** [comment]
@schanzer Thanks! I see that you have made the prereq section minimize to the same length that the materials section minimizes to. If it's easy to make the prereq table shorter so that it only shows 4 bullets, I vote for that, but I don't have any sense of how much effort that would be and this is already enough of an improvement that I can tell when I load that there is a materials section and it's worth scrolling down.  Either refine and close or decide it's too much work for right now and close.
