### ISSUE TITLE
Audit of standards alignments

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#968]
It appears that only two (!!) of our lessons are aligned to K12CS standards - defining-functions and defining-values.
https://bootstrapworld.org/materials/latest/en-us/courses/algebra-pyret/pathway-alignments.shtml

I discovered this when searching out a standard to assign to "Computing Needs All Voices." (I found one! In the K12CS standards!) I think we ought to go through and assign K12CS standards to each lesson. (Unless there's a reason it was never done?) 

I also noticed that the Iowa alignment appears to be incomplete. (Only four of our lessons are aligned to these standards.) I also see that we have a .rkt doc of NGSS standards, but they have never been assigned to lessons either. So it looks like standards alignment in general would benefit from a little TLC.

**Comment by schanzer** [comment]
This issue will require the following:

- [x] ensure that all common core states are included
- [x] spread existing CC standards alignment across all CC states (e.g. - make Iowa complete)
- [ ] K12CS Standards Alignment
- [ ] NGSS Standards Alignment

**Comment by schanzer** [comment]
We can _only_ align to the NGSS _practices_ -- we just don't have much for science _content_ right now.

**Comment by schanzer** [comment]
A PR is now open for this issue. Closing this in favor of the PR, which will track any merge issues
