### ISSUE TITLE
Algebra should be split into wescheme and pyret pathways, allowing for a different lesson order.

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/curriculum#971]
We've finally reached the point where there's too much divergence between WeScheme and Pyret for our Algebra pathway to be truly bilingual. 

Dorai, is there anything that needs to be done besides creating separate pathway folders? If so, can you make that change in the build script?

**Comment by schanzer** [comment]
@ds26gte I nuked the distribution directory, and built with the following command:
`./build-pathway -f algebra-pyret algebra-wescheme data-science ok reactive`

algebra-wescheme did not show up in the pathways folder. What's the right way to do this, in a post-proglang-split world?

**Comment by ds26gte** [comment]
`--proglang all`, as always.  Otherwise, by default only the `pyret` versions are built.
