### ISSUE TITLE
Consider whether to automate italicization of @ifsoln

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#973]
We have standardized the fact that solutions should be italicized. And we also often forget to do so.

I don't think that it would mess anything up to automate this. The only exception I can think of is multiple choice, where we usually bold an option, but I don't think it would harm anything if those ended up bolded by hand and automatically italicized.

**Comment by schanzer** [comment]
@ds26gte could we change that directive to wrap contents inside `<span class="solution">...</span>`?

**Comment by ds26gte** [comment]
`@ifsoln` can contain paragraphs (and does, the way we use them). It is not possible to wrap a `<span>` around possible block elements, at least if we want valid HTML.

**Comment by schanzer** [comment]
@ds26gte Hrmmm. Can it impart a className to all children?

**Comment by ds26gte** [comment]
A low-hanging :apple: is ensuring a class (like `solution2` -- I notice we already have a `solution` class that may be used for other reasons) always encloses the in-text (i.e., doesn't contain paragraph separators or blocks) uses of `@ifsoln`.  You can explicitly write `[.solution2]` before block uses of `@ifsoln`, and they're not that many. Asciidoc makes it very difficult to programmatically enclose `div`s around blocked text, because we don't know if such text already contains such qualified blocks.

I guess I could also search for presence of `--` in the `@ifsoln` text and in all other cases, manually enclose a

```
[.solution2]
--
<author text>
--
```

Would this be a good compromise?

**Comment by schanzer** [comment]
@ds26gte `.solution` can (and should!) be used for this

This still doesn't do it for me. What about the translating all `@ifsoln{ABC}` expressions produced the following asciidoc:

```
[.solution]
--
ABC
--
```

Wouldn't this work, for essentially any `ABC`?

**Comment by ds26gte** [comment]
Asciidoctor doesn't seem to allow nested open blocks (regardless of issues raised and seemingly addressed), so in your example, if `ABC` itself contained blocks enclosed with `--`, the intended result won't obtain. And we have quite a few such cases. (I have been trying nested blocks with Asciidoctor every few months to see if the situation has improved. It has not.)

Secondly, not all of our `@ifsoln`s produce blocks. We use a lot of _in-text_ `@ifsoln`s, i.e., they are part of a sentence.
Wrapping a block around them would produce the wrong output. (I would hazard that _in-text_ uses constitute the majority of our `@ifsoln`s.)

I already have un-checkedi-in code that for my suggested compromise.

**Comment by flannery-denny** [comment]
@ds26gte @schanzer In thinking about this I would guess that the only time we use blocks is when the solution is code... which is a situation where we also don't need italicization. Perhaps the whole thing would be solved by disaggregating solutions that use code blocks and those that don't with two different directives. Let's discuss when we meet.

**Comment by schanzer** [comment]
@ds26gte in preparation for our meeting tonight, can you prepare some data on how often we use blocks inside `@ifsoln{...}`, and in what forms (code, raw asciidoc, etc)?

If we're using blocks infrequently, I would rather stick with the simpler solution and get rid of those instances by hand.

**Comment by schanzer** [comment]
This is now completed on the [italic-solutions](https://github.com/bootstrapworld/curriculum/compare/italic-solutions) branch. Merge after workbook revisions go to print.

**Comment by schanzer** [comment]
Closed by 84fa224b6
