### ISSUE TITLE
Live on website - weird blank bullet in "Materials" section of many different lessons

### ISSUE THREAD

**Issue by retabak** [bootstrapworld/curriculum#975]
Here's one example:
https://bootstrapworld.org/materials/latest/en-us/lessons/measures-of-center/index.shtml?pathway=data-science

There are several others.

![image](https://user-images.githubusercontent.com/87144723/174461756-43b79f95-4482-417f-938c-2b2358f43f60.png)

**Comment by schanzer** [comment]
Looks good to me!

<img width="737" alt="image" src="https://user-images.githubusercontent.com/77126/174461847-374ba9a8-1b3d-488c-8f70-e839661bf2e7.png">


Have you reloaded with the shift key down?

**Comment by retabak** [comment]
Lol, problem solved!
