### ISSUE TITLE
Font size for text within @ifsoln{} and @ifnotsoln{} is different from other text

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#976]
for example, see `functions-vertical-line-test/functions-tables`

Actually, wondering if the difference is between columns labeled `1` vs columns labeled `1a`

See `functions-can-be-linear/notice-wonder-linearity`

**Comment by schanzer** [comment]
@flannery-denny looks like an asciidoc default was leaking through. Thanks for reporting it! I've fixed the CSS.

AsciiDoc column descriptors take up to four arguments: horizontal and vertical alignment, width-ratio, and _whether or not the table cells contain asciidoc_. The difference between `1` and `1a` is that the latter will process asciidoc formatting within a table, but `1` won't.

I also add solutions to these files.
