### ISSUE TITLE
add explanation of how to convert circles to code in pyret back into order of operations lesson 

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#979]

**Comment by schanzer** [comment]
@flannery-denny I've fixed the lesson and slides, along with generating new images.

Also updated the slide images in our Fall2022 folder. If these look good to you, feel free to update the PD decks accordingly and close the issue.

**Comment by schanzer** [comment]
@flannery-denny I went ahead an updated the PD decks as well. Close if you're happy with how the slides look?

**Comment by flannery-denny** [comment]
@schanzer the lesson plan looks great... there are some ways that the slides diverge from the lesson plan that don't make sense to me. I'll work on fixing it.

**Comment by flannery-denny** [comment]
@schanzer wow. the slides.md file has so many instance where wescheme and pyret should be different and there's no @ifproglang being used... I'm not sure whether we expect the build to remain stable enough that there's a point to fixing it at this point or if I should just fix the slides on googledrive... 

I think this is a pretty stable lesson and it looks like you've been updating slides.md so I'm inclined to think it's worth getting it right on git...  if that's the goal, I need a zoom date to clarify some things.

**Comment by schanzer** [comment]
@flannery-denny I'm not seeing what you're seeing. I took a careful pass and actually _removed_ two @ifproglangs. 

I don't see much that needs to be different for Pyret v. WeScheme. If you feel strongly, please feel free to propose a change.

**Comment by flannery-denny** [comment]
@schanzer aren't most of the coe and code images proglang specific? I'm not seeing that in the `slides.md` file

**Comment by schanzer** [comment]
@flannery-denny Check out the slides themselves. If you see any problems, let me know. They all look good to me.

Also note that language-specific images do _not_ necessarily need to be wrapped in @ifproglang: the images directory for this lesson has `pyret` and `wescheme` subfolders, which allows the asciidoc and markdown files to refer to them by filename and let the build system handle sorting out which image is which.

**Comment by schanzer** [comment]
@flannery-denny Ah! The teachers' notes! 

OK, done and pushed.

**Comment by flannery-denny** [comment]
@schanzer

   1. don't we want `#:parens true` for this code?
   2. why are we asking them to write the code for the two examples we've
   just shown them how to write the code for - the lesson plan doesn't do that.
   3. and why are we leaving out this text from the lesson plan?



*Arithmetic expressions involving more than one operation, will end up with
more than one ***@***.***{wescheme}{and more than one pair of
***@***.***{pyret}{and, whether or not there are parentheses
in the original expression, the code requires parentheses to clarify the
order in which the operations should be completed.}*

**Comment by schanzer** [comment]
@flannery-denny 

1. We _do_ have `#:parens true` in the code! see line 207
2. Good point! I removed the code
3. That text is _in_ the lesson plan! Are you asking about the slides? Rachel did all the slides for the Algebra pathway, so you'd have to ask her. I'm fine with you adding this to the slides.

**Comment by flannery-denny** [comment]
@schanzer I've pushed suggestions, but don't remember how to build slides so haven't confirmed that they look how I expect them to and haven't broken anything.

**Comment by flannery-denny** [comment]
> As in math, in Pyret there are some cases where the outermost parentheses can be removed:
> (1 + 2) can be safely written as 1 + 2, and the same goes for the Pyret code
> (1 * 2) * 3) can be safely written as 1 * 2 * 3, and the same goes for the Pyret code
> It is always better to at least start with the parentheses before taking them out. It is never wrong to include them!
> 

All four of the examples before the slide above should have all of the parentheses. and avoiding @ifproglang is putting the fate of the parentheses in Dorai's code, which defaults to

2*(3+8) instead of (2 * (3 + 8))

@schanzer I added the outer parentheses in the speaker notes of the pyret slide decks by hand, because I need to move on to finishing the deck.  If someone builds the slides in git, my fixes will be overwritten. If you can figure out how to fix them in slides.md, great.

**Comment by schanzer** [comment]
@flannery-denny I've already fixed slides.md, so your fixes will not be forgotten! 

@retabak , in the future be sure to use `@show{(code '(+ 1 2)}` instead of writing `1 + 2`. This ensures that the correct code will be generated regardless of proglang.

In [the Pyret slide deck](https://docs.google.com/presentation/d/1DDurzjEi5Z5VRh-LomZNYfgIC1ORRvvMfestzqij6YI/edit#slide=id.g1365845d0ec_0_64), all the code examples have all the parentheses. 

Closing at last!
