### ISSUE TITLE
add fall 2021 and spring 2022 to the list of previous versions of materials

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#990]

**Comment by schanzer** [comment]
Done!

**Comment by flannery-denny** [comment]
the link to spring 2022 is listed as spring 2021 on the materials landing page
![Screen Shot 2022-07-01 at 10 13 38 AM](https://user-images.githubusercontent.com/66691020/176921904-cd27ad27-9120-4699-89d0-5910f8682843.png)
.
