### ISSUE TITLE
Add a way to include a message on slides.md that flags images that need to be manually adjusted after a slide build

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#998]
Because images are autopositioned on the slide, it is sometimes not possible to autogenerate a slide where the image and the accompanying text are both legible and don't overlap. Ideally we would come up with a system for flaggin this so that we are reminded to do manual adjustments.

One low-tech option could be that authors write notes on a slide that comes before the cover slide so that if a deck has special requirements it's very obvious that it doesn't look right. I'm sure there are other options.

**Comment by schanzer** [comment]
@flannery-denny go for it! Just open the [Slide Template](https://docs.google.com/presentation/d/1jAjRtOGXhxfTGOx4F1vKAXfxUxQj2RXyTgwNuiOa_-w/edit#slide=id.simple-light-2), copy an existing layout that's close to what you want (I bet LaunchC and InvestigateC are close), then name it something that fits the convention used elsewhere. Once that's done you should be able to refer to it with the `{layout="..."}` syntax.

**Comment by retabak** [comment]
I kicked around the idea of creating another slide template (largely to include inequalities on the bottom of the slide!), but was reluctant about over-complicating things with too many templates.

Upon seeing this issue, I agree that having slides build correctly without manual adjustment is the best solution!
