### ISSUE TITLE
Live on our website - slides are saying "you need access"

### ISSUE THREAD

**Issue by flannery-denny** [bootstrapworld/curriculum#999]
![Screen Shot 2022-06-27 at 11 15 01 AM](https://user-images.githubusercontent.com/66691020/175987474-baa5be07-a607-4229-80e6-fe98df483763.png)

- [x] functions-vertical-line-test pyret
- [x] functions-vertical-line-test wescheme
- [x] function-notation-pyret
- [x] function-notation-wescheme
- [x] compound inequalities-pyret
- [x] compound inequalities-wescheme
- [ ] problem decomposition-pyret
- [ ] problem decomposition-wescheme

**Comment by schanzer** [comment]
@flannery-denny all of the slides are world-readable. These lessons appear to link to slides that are NOT part of our GDrive.

Any idea what happened?
